--------------------------------------------------------
-- DDL Statements for table ABCLIMS .CMS_SYSTEM_BANK
--------------------------------------------------------
 

CREATE TABLE ABCLIMS .CMS_SYSTEM_BANK  (
		  ID 					BIGINT NOT NULL , 
		  VERSION_TIME 			BIGINT NOT NULL , 
		  CREATE_BY 			VARCHAR(50) NOT NULL , 
		  CREATION_DATE 		TIMESTAMP NOT NULL , 
		  LAST_UPDATE_BY		VARCHAR(50) NOT NULL , 
		  LAST_UPDATE_DATE 		TIMESTAMP NOT NULL , 
		  DEPRECATED 			CHAR(1) NOT NULL , 
		  STATUS 				VARCHAR(20) NOT NULL , 
		  SYSTEM_BANK_CODE 		VARCHAR(100) NOT NULL , 
		  SYSTEM_BANK_NAME	 	VARCHAR(300) NOT NULL , 
		  CONTACT_NUMBER 		BIGINT ,
		  FAX_NUMBER 		    BIGINT , 
		  ADDRESS 				VARCHAR(1024) , 
		  MASTER_ID 			BIGINT , 
		  CITY_TOWN 			VARCHAR(200) NOT NULL , 
		  STATE 				VARCHAR(200) NOT NULL , 
		  REGION 				VARCHAR(200) , 
		  COUNTRY 				VARCHAR(200) NOT NULL , 
		  CONTACT_MAIL 			VARCHAR(200) )   
		 IN USERSPACE1 ; 


-- DDL Statements for indexes on Table ABCLIMS .CMS_SYSTEM_BANK

CREATE INDEX EONCLOS .PK_SYSTEM_BANK ON ABCLIMS .CMS_SYSTEM_BANK 
		(ID ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;
-- DDL Statements for primary key on Table ABCLIMS .CMS_SYSTEM_BANK

ALTER TABLE ABCLIMS .CMS_SYSTEM_BANK 
	ADD CONSTRAINT PK_SYSTEM_BANK PRIMARY KEY
		(ID);

		
		

--------------------------------------------------------------
-- DDL Statements for table ABCLIMS .CMS_STAGE_SYSTEM_BANK
--------------------------------------------------------------
 

CREATE TABLE ABCLIMS .CMS_STAGE_SYSTEM_BANK  (
		  ID 					BIGINT NOT NULL , 
		  VERSION_TIME    		BIGINT NOT NULL , 
		  CREATE_BY 			VARCHAR(50) NOT NULL , 
		  CREATION_DATE 		TIMESTAMP NOT NULL , 
		  LAST_UPDATE_BY 		VARCHAR(50) NOT NULL , 
		  LAST_UPDATE_DATE 		TIMESTAMP NOT NULL , 
		  DEPRECATED 			CHAR(1) NOT NULL , 
		  STATUS 				VARCHAR(20) NOT NULL , 
		  SYSTEM_BANK_CODE 		VARCHAR(100) NOT NULL , 
		  SYSTEM_BANK_NAME 		VARCHAR(300) NOT NULL , 
		  CONTACT_NUMBER 		BIGINT ,
		  FAX_NUMBER 		    BIGINT ,
		  ADDRESS 				VARCHAR(1024) , 
		  MASTER_ID 			BIGINT , 
		  CITY_TOWN 			VARCHAR(200) NOT NULL , 
		  STATE 				VARCHAR(200) NOT NULL , 
		  REGION 				VARCHAR(200) , 
		  COUNTRY 				VARCHAR(200) NOT NULL , 
		  CONTACT_MAIL 			VARCHAR(200) )   
		 IN USERSPACE1 ; 



----------------------------------------------------------------
-- DDL Statements for table ABCLIMS .CMS_SYSTEM_BANK_BRANCH
----------------------------------------------------------------
 

CREATE TABLE ABCLIMS .CMS_SYSTEM_BANK_BRANCH  (
		  ID 						BIGINT NOT NULL , 
		  VERSION_TIME 				BIGINT NOT NULL , 
		  CREATE_BY 				VARCHAR(50) NOT NULL , 
		  CREATION_DATE 			TIMESTAMP NOT NULL , 
		  LAST_UPDATE_BY 			VARCHAR(50) NOT NULL , 
		  LAST_UPDATE_DATE 			TIMESTAMP NOT NULL , 
		  DEPRECATED 				CHAR(1) NOT NULL , 
		  STATUS 					VARCHAR(20) NOT NULL , 
		  SYSTEM_BANK_BRANCH_CODE 	VARCHAR(100) NOT NULL , 
		  SYSTEM_BANK_BRANCH_NAME 	VARCHAR(300) NOT NULL , 
		  SYSTEM_BANK_CODE 			VARCHAR(100) NOT NULL , 
		  CONTACT_NUMBER 			BIGINT ,
		  FAX_NUMBER 		    BIGINT ,
		  ADDRESS 					VARCHAR(1024) , 
		  MASTER_ID 				BIGINT , 
		  CITY_TOWN 				VARCHAR(200) NOT NULL , 
		  STATE 					VARCHAR(200) NOT NULL , 
		  REGION 					VARCHAR(200) , 
		  COUNTRY 					VARCHAR(200) NOT NULL , 
		  CONTACT_MAIL 				VARCHAR(200) )   
		 IN USERSPACE1 ; 



------------------------------------------------
-- DDL Statements for table ABCLIMS .CMS_STAGE_SYSTEM_BANK_BRANCH
------------------------------------------------
 

CREATE TABLE ABCLIMS.CMS_STAGE_SYSTEM_BANK_BRANCH  (
		  ID 						BIGINT NOT NULL , 
		  VERSION_TIME 				BIGINT NOT NULL , 
		  CREATE_BY 				VARCHAR(50) , 
		  CREATION_DATE 			TIMESTAMP , 
		  LAST_UPDATE_BY 			VARCHAR(50) , 
		  LAST_UPDATE_DATE 			TIMESTAMP , 
		  DEPRECATED 				CHAR(1) , 
		  STATUS 					VARCHAR(20) , 
		  SYSTEM_BANK_BRANCH_CODE 	VARCHAR(100) , 
		  SYSTEM_BANK_BRANCH_NAME 	VARCHAR(300) , 
		  SYSTEM_BANK_CODE 			VARCHAR(100) , 
		  CONTACT_NUMBER 			BIGINT , 
		  FAX_NUMBER 		        BIGINT ,
		  ADDRESS 					VARCHAR(1024) , 
		  MASTER_ID 				BIGINT , 
		  CITY_TOWN 				VARCHAR(200) , 
		  STATE 					VARCHAR(200) , 
		  REGION 					VARCHAR(200) , 
		  COUNTRY 					VARCHAR(200) , 
		  CONTACT_MAIL 				VARCHAR(200) )   
		 IN USERSPACE1 ; 


--------------------------------
--- Stage System Bank Branch Dummy Entry
--------------------------------

INSERT INTO CMS_STAGE_SYSTEM_BANK_BRANCH VALUES(1,1,'SA_MAKER','2011-01-28-00.00.00.000000','SA_MAKER','2011-01-28-00.00.00.000000','N','ACTIVE','111','PAWAI HDFC BANK','1',2333377,'PAWAI , MUMBAI',1,'MUMBAI','MAHARASTRA','EAST','INDIA','pawai@hdfc.com');



-----------------------------------
--- System Bank Branch Dummy Entry
-----------------------------------

INSERT INTO CMS_SYSTEM_BANK_BRANCH VALUES(1,1,'SA_MAKER','2011-01-28-00.00.00.000000','SA_MAKER','2011-01-28-00.00.00.000000','N','ACTIVE','111','PAWAI HDFC BANK','1',2333377,'PAWAI , MUMBAI',1,'MUMBAI','MAHARASTRA','EAST','INDIA','pawai@hdfc.com');



--------------------------------
--- Stage System Bank Dummy Entry
--------------------------------

INSERT INTO CMS_STAGE_SYSTEM_BANK VALUES(1,20,'SA_MAKER','2011-01-05-00.00.00.000000','SA_CHECKER','2011-01-20-00.00.00.000000','N','ACTIVE','1','HDFC BANK',115484,'HDFC Bank House,Senapati Bapat Marg,Lower Parel,India - 400 013',1,'Mumbai','Maharastra','South','India','hdfc_parel@hdfc.com');




		
--------------------------------
--- System Bank Dummy Entry
--------------------------------

INSERT INTO CMS_SYSTEM_BANK VALUES(1,20,'SA_MAKER','2011-01-05-00.00.00.000000','SA_CHECKER','2011-01-20-00.00.00.000000','N','ACTIVE','1','HDFC BANK',115484,'HDFC Bank House,Senapati Bapat Marg,Lower Parel,India - 400 013',1,'Mumbai','Maharastra','South','India','hdfc_parel@hdfc.com');


	
------------------------------------------------
--- System Bank and Branches Transaction Entries
------------------------------------------------

	
INSERT INTO ABCLIMS.TRANSACTION (TRANSACTION_ID	,FROM_STATE,USER_ID,LOGIN_ID,TRANSACTION_TYPE,CREATION_DATE,TRANSACTION_DATE
,REFERENCE_ID,STATUS,STAGING_REFERENCE_ID,TEAM_ID,VERSION,REMARKS,TRX_REFERENCE_ID,OPSDESC,LEGAL_NAME,LEGAL_ID
,CUSTOMER_NAME,CUSTOMER_ID,TRX_ORIGIN_COUNTRY,TRX_ORIGIN_ORGANISATION,LIMIT_PROFILE_ID,LIMIT_PROFILE_REF_NUM,TRX_SEGMENT
,USER_INFO,CUR_TRX_HISTORY_ID,TEAM_TYPE_ID,TRANSACTION_SUBTYPE,TO_GROUP_TYPE_ID,TO_GROUP_ID,TO_USER_ID,DEAL_NO,TEAM_MEMBERSHIP_ID)
VALUES('20110131000002155','PENDING_UPDATE',20070101000002,'SA_CHECKER','SYSTEM_BANK_BRANCH','2011-01-21-19.46.42.463000','2011-02-25-12.35.42.950000',1,'ACTIVE',1,20070101000001,1298617542966,'approved',20110131000002155,'CHECKER_APPROVE_UPDATE','','','SA_MAKER',-999999999,'--','--',-999999999,'','--','SA_CHECKER ( SA_CHECKER )','20110225000000434',3,'','-999999999',-999999999,-999999999,'',20070101000002);

INSERT INTO TRANSACTION (TRANSACTION_ID	,FROM_STATE,USER_ID,LOGIN_ID,TRANSACTION_TYPE,CREATION_DATE,TRANSACTION_DATE
,REFERENCE_ID,STATUS,STAGING_REFERENCE_ID,TEAM_ID,VERSION,REMARKS,TRX_REFERENCE_ID,OPSDESC,LEGAL_NAME,LEGAL_ID
,CUSTOMER_NAME,CUSTOMER_ID,TRX_ORIGIN_COUNTRY,TRX_ORIGIN_ORGANISATION,LIMIT_PROFILE_ID,LIMIT_PROFILE_REF_NUM,TRX_SEGMENT
,USER_INFO,CUR_TRX_HISTORY_ID,TEAM_TYPE_ID,TRANSACTION_SUBTYPE,TO_GROUP_TYPE_ID,TO_GROUP_ID,TO_USER_ID,DEAL_NO,TEAM_MEMBERSHIP_ID) 
VALUES('20110131000002154','PENDING_UPDATE',20070101000002,'SA_CHECKER','SYSTEM_BANK','2011-01-31-18.24.10.396000','2011-02-24-11.44.07.681000',1,'ACTIVE',1,20070101000001,1298528047697,'approved',20110131000002154,'CHECKER_APPROVE_UPDATE','','','SA_MAKER',-999999999,'--','--',-999999999,,'--','SA_CHECKER ( SA_CHECKER )','20110224000000398',3,'','-999999999',-999999999,-999999999,'',20070101000002);	




