--SET CURRENT PATH = SYSIBM,SYSFUN,SYSPROC,SYSIBMADM,CLIMS_LOCAL;
DROP VIEW VIEW_SI_DW001_CLMFINCOL;
DROP VIEW VIEW_SI_DW002_CLMPHYCOL;
DROP VIEW VIEW_SI_DW003_CLMGTECOL;
DROP VIEW VIEW_SI_DW004_CLMRECCOL;
DROP VIEW VIEW_SI_DW005_CLMACTLNK;
DROP VIEW VIEW_SI_DW006_CLMFACLNK;

-------------------------------
-- DW001 - Financial Collateral
-------------------------------
CREATE VIEW VIEW_SI_DW001_CLMFINCOL AS
	SELECT S.SOURCE_ID, S.CMS_COLLATERAL_ID, ST.SECURITY_TYPE_ID, S.SECURITY_SUB_TYPE_ID, S.SCI_SECURITY_CURRENCY,
		ST.SUBTYPE_STANDARDISED_APPROACH, ST.SUBTYPE_ADVANCED_IRB AS FIRB, ST.SUBTYPE_ADVANCED_IRB AS AIRB, 
		S.IS_LEGAL_ENFORCE, S.IS_LEGAL_ENFORCE_DATE, CD.DEPOSIT_MATURITY_DATE AS SECURITY_MATURITY_DATE,
		'' AS STOCK_EXCHANGE, '' AS STOCK_CODE, '' AS ISIN_CODE, 0 AS NO_OF_UNITS, 0 AS UNIT_PRICE, '' AS ISSUER_NAME, '' AS INDEX_NAME,
		CD.DEPOSIT_RECEIPT_NUMBER, CD.DEPOSIT_REFERENCE_NUMBER, CD.ISSUE_DATE,
		V.VALUATION_DATE, SPR.VALUATION_FREQUENCY, SPR.VALUATION_FREQUENCY_UNIT,
		'Y' AS IRREVOCABLE_FLAG, 'Basel' AS HAIRCUT_SET_ID, LSM.DELETION_DATE, CH.CHARGE_AMOUNT, 
		PD.PLG_LE_ID, PD.PLG_ID_TYPE_VALUE, PD.PLG_ID_NUM_TEXT
	FROM CMS_SECURITY S
		INNER JOIN CMS_SECURITY_SUB_TYPE ST ON S.SECURITY_SUB_TYPE_ID = ST.SECURITY_SUB_TYPE_ID AND ST.STATUS <> 'DELETED'
		INNER JOIN CMS_CASH C ON C.CMS_COLLATERAL_ID = S.CMS_COLLATERAL_ID
		INNER JOIN CMS_CASH_DEPOSIT CD ON CD.CMS_COLLATERAL_ID = C.CMS_COLLATERAL_ID AND CD.STATUS <> 'DELETED'
		LEFT OUTER JOIN CMS_VALUATION V ON V.CMS_COLLATERAL_ID = S.CMS_COLLATERAL_ID
		LEFT OUTER JOIN CMS_SECURITY_PARAMETER SPR ON SPR.SECURITY_SUB_TYPE_ID = S.SECURITY_SUB_TYPE_ID AND SPR.COUNTRY_ISO_CODE = S.SECURITY_LOCATION AND SPR.STATUS <> 'DELETED'
		LEFT OUTER JOIN CMS_LIMIT_SECURITY_MAP LSM ON LSM.CMS_COLLATERAL_ID = S.CMS_COLLATERAL_ID AND LSM.UPDATE_STATUS_IND <> 'D'
		LEFT OUTER JOIN CMS_LIMIT_CHARGE_MAP LCM ON LCM.CHARGE_ID = LSM.CHARGE_ID AND LCM.STATUS <> 'DELETED'
		LEFT OUTER JOIN CMS_CHARGE_DETAIL CH ON CH.CHARGE_DETAIL_ID = LCM.CHARGE_DETAIL_ID AND CH.STATUS <> 'DELETED'
		LEFT OUTER JOIN SCI_SEC_PLDGR_MAP SPM ON SPM.CMS_COLLATERAL_ID = S.CMS_COLLATERAL_ID AND SPM.UPDATE_STATUS_IND <> 'D'
		LEFT OUTER JOIN SCI_PLEDGOR_DTL PD ON PD.CMS_PLEDGOR_DTL_ID = SPM.CMS_PLEDGOR_DTL_ID AND PD.UPDATE_STATUS_IND <> 'D'
	WHERE S.STATUS <> 'DELETED'
	UNION
	SELECT S.SOURCE_ID, S.CMS_COLLATERAL_ID, ST.SECURITY_TYPE_ID, S.SECURITY_SUB_TYPE_ID, S.SCI_SECURITY_CURRENCY,
		ST.SUBTYPE_STANDARDISED_APPROACH, ST.SUBTYPE_ADVANCED_IRB AS FIRB, ST.SUBTYPE_ADVANCED_IRB AS AIRB, 
		'Y' AS IS_LEGAL_ENFORCE, PD.TRANSACTION_DATE AS IS_LEGAL_ENFORCE_DATE, P.SECURITY_MATURITY_DATE,
		P.STOCK_EXCHANGE, P.STOCK_CODE, P.ISIN_CODE, P.NO_OF_UNITS, P.UNIT_PRICE, P.ISSUER_NAME, P.INDEX_NAME,
		'' AS DEPOSIT_RECEIPT_NUMBER, '' AS DEPOSIT_REFERENCE_NUMBER, P.BOND_ISSUE_DATE AS ISSUE_DATE,
		V.VALUATION_DATE, SPR.VALUATION_FREQUENCY, SPR.VALUATION_FREQUENCY_UNIT,
		'Y' AS IRREVOCABLE_FLAG, 'Basel' AS HAIRCUT_SET_ID, LSM.DELETION_DATE, CH.CHARGE_AMOUNT,
		PD.PLG_LE_ID, PD.PLG_ID_TYPE_VALUE, PD.PLG_ID_NUM_TEXT
	FROM CMS_SECURITY S
		INNER JOIN CMS_SECURITY_SUB_TYPE ST ON S.SECURITY_SUB_TYPE_ID = ST.SECURITY_SUB_TYPE_ID AND ST.STATUS <> 'DELETED'
		INNER JOIN CMS_MARKETABLE_SEC MS ON MS.CMS_COLLATERAL_ID = S.CMS_COLLATERAL_ID
		INNER JOIN CMS_PORTFOLIO_ITEM P ON P.CMS_COLLATERAL_ID = MS.CMS_COLLATERAL_ID AND P.STATUS <> 'DELETED'
		INNER JOIN CMS_PORTFOLIO_ITEM_DTL PD ON PD.ITEM_ID = P.ITEM_ID AND PD.STATUS <> 'DELETED'
		LEFT OUTER JOIN CMS_VALUATION V ON V.CMS_COLLATERAL_ID = S.CMS_COLLATERAL_ID
		LEFT OUTER JOIN CMS_SECURITY_PARAMETER SPR ON SPR.SECURITY_SUB_TYPE_ID = S.SECURITY_SUB_TYPE_ID AND SPR.COUNTRY_ISO_CODE = S.SECURITY_LOCATION AND SPR.STATUS <> 'DELETED'
		LEFT OUTER JOIN CMS_LIMIT_SECURITY_MAP LSM ON LSM.CMS_COLLATERAL_ID = S.CMS_COLLATERAL_ID AND LSM.UPDATE_STATUS_IND <> 'D'
		LEFT OUTER JOIN CMS_LIMIT_CHARGE_MAP LCM ON LCM.CHARGE_ID = LSM.CHARGE_ID AND LCM.STATUS <> 'DELETED'
		LEFT OUTER JOIN CMS_CHARGE_DETAIL CH ON CH.CHARGE_DETAIL_ID = LCM.CHARGE_DETAIL_ID AND CH.STATUS <> 'DELETED'
		LEFT OUTER JOIN SCI_SEC_PLDGR_MAP SPM ON SPM.CMS_COLLATERAL_ID = S.CMS_COLLATERAL_ID AND SPM.UPDATE_STATUS_IND <> 'D'
		LEFT OUTER JOIN SCI_PLEDGOR_DTL PD ON PD.CMS_PLEDGOR_DTL_ID = SPM.CMS_PLEDGOR_DTL_ID AND PD.UPDATE_STATUS_IND <> 'D'
	WHERE S.STATUS <> 'DELETED';

-------------------------------
-- DW002 - Physical Collateral
-------------------------------
CREATE VIEW VIEW_SI_DW002_CLMPHYCOL AS
	SELECT S.SOURCE_ID, S.CMS_COLLATERAL_ID, ST.SECURITY_TYPE_ID, S.SECURITY_SUB_TYPE_ID, S.SCI_SECURITY_CURRENCY, ST.SUBTYPE_STANDARDISED_APPROACH,
		ST.SUBTYPE_ADVANCED_IRB AS FIRB, ST.SUBTYPE_ADVANCED_IRB AS AIRB, S.IS_LEGAL_ENFORCE, S.IS_LEGAL_ENFORCE_DATE,
		S.SECURITY_MATURITY_DATE, V.VALUATION_DATE, SP.VALUATION_FREQUENCY, SP.VALUATION_FREQUENCY_UNIT, V.VALUATION_CURRENCY,
		V.CMV, V.FSV, S.RESERVE_PRICE,
		A.PURCHASE_PRICE, 'Y' AS IRREVOCABLE_FLAG, 'Basel' AS HAIRCUT_SET_ID
	FROM CMS_SECURITY S
		INNER JOIN CMS_SECURITY_SUB_TYPE ST ON ST.SECURITY_SUB_TYPE_ID = S.SECURITY_SUB_TYPE_ID AND ST.STATUS <> 'DELETED'
		INNER JOIN CMS_ASSET A ON A.CMS_COLLATERAL_ID = S.CMS_COLLATERAL_ID
		LEFT OUTER JOIN CMS_VALUATION V ON V.CMS_COLLATERAL_ID = S.CMS_COLLATERAL_ID
		LEFT OUTER JOIN CMS_SECURITY_PARAMETER SP ON S.SECURITY_SUB_TYPE_ID = SP.SECURITY_SUB_TYPE_ID AND S.SECURITY_LOCATION = SP.COUNTRY_ISO_CODE AND SP.STATUS <> 'DELETED'
	WHERE S.STATUS <> 'DELETED'
	UNION
	SELECT S.SOURCE_ID, S.CMS_COLLATERAL_ID, ST.SECURITY_TYPE_ID, S.SECURITY_SUB_TYPE_ID, S.SCI_SECURITY_CURRENCY, ST.SUBTYPE_STANDARDISED_APPROACH,
		ST.SUBTYPE_ADVANCED_IRB AS FIRB, ST.SUBTYPE_ADVANCED_IRB AS AIRB, S.IS_LEGAL_ENFORCE, S.IS_LEGAL_ENFORCE_DATE,
		S.SECURITY_MATURITY_DATE, V.VALUATION_DATE, SP.VALUATION_FREQUENCY, SP.VALUATION_FREQUENCY_UNIT, V.VALUATION_CURRENCY,
		V.CMV, V.FSV, S.RESERVE_PRICE,
		P.SALE_PURCHASE_VALUE AS PURCHASE_PRICE, 'Y' AS IRREVOCABLE_FLAG, 'Basel' AS HAIRCUT_SET_ID
	FROM CMS_SECURITY S
		INNER JOIN CMS_SECURITY_SUB_TYPE ST ON ST.SECURITY_SUB_TYPE_ID = S.SECURITY_SUB_TYPE_ID AND ST.STATUS <> 'DELETED'
		INNER JOIN CMS_PROPERTY P ON P.CMS_COLLATERAL_ID = S.CMS_COLLATERAL_ID
		LEFT OUTER JOIN CMS_VALUATION V ON S.CMS_COLLATERAL_ID = V.CMS_COLLATERAL_ID
		LEFT OUTER JOIN CMS_SECURITY_PARAMETER SP ON S.SECURITY_SUB_TYPE_ID = SP.SECURITY_SUB_TYPE_ID AND S.SECURITY_LOCATION = SP.COUNTRY_ISO_CODE AND SP.STATUS <> 'DELETED'
	WHERE S.STATUS <> 'DELETED';

-------------------------------
-- DW003 - Guarantee
-------------------------------
CREATE VIEW VIEW_SI_DW003_CLMGTECOL AS
	SELECT DISTINCT S.SOURCE_ID, S.CMS_COLLATERAL_ID, ST.SECURITY_TYPE_ID, S.SECURITY_SUB_TYPE_ID, S.SCI_SECURITY_CURRENCY,
		ST.SUBTYPE_STANDARDISED_APPROACH, ST.SUBTYPE_ADVANCED_IRB AS FIRB, ST.SUBTYPE_ADVANCED_IRB AS AIRB,
		S.IS_LEGAL_ENFORCE, S.IS_LEGAL_ENFORCE_DATE, S.SECURITY_MATURITY_DATE, V.VALUATION_DATE, SP.VALUATION_FREQUENCY, SP.VALUATION_FREQUENCY_UNIT,
		G.GUARANTEE_AMT, 'Y' AS IRREVOCABLE_FLAG, 'Basel' AS HAIRCUT_SET_ID, P.CMS_PLEDGOR_DTL_ID
	FROM CMS_SECURITY S
		INNER JOIN CMS_SECURITY_SUB_TYPE ST ON S.SECURITY_SUB_TYPE_ID = ST.SECURITY_SUB_TYPE_ID AND ST.STATUS <> 'DELETED'
		INNER JOIN CMS_GUARANTEE G ON G.CMS_COLLATERAL_ID = S.CMS_COLLATERAL_ID
		LEFT OUTER JOIN CMS_VALUATION V ON S.CMS_COLLATERAL_ID = V.CMS_COLLATERAL_ID
		LEFT OUTER JOIN CMS_SECURITY_PARAMETER SP ON S.SECURITY_SUB_TYPE_ID = SP.SECURITY_SUB_TYPE_ID AND S.SECURITY_LOCATION = SP.COUNTRY_ISO_CODE AND SP.STATUS <> 'DELETED'
		LEFT OUTER JOIN SCI_SEC_PLDGR_MAP SPM ON S.CMS_COLLATERAL_ID = SPM.CMS_COLLATERAL_ID AND SPM.UPDATE_STATUS_IND <> 'D'
		LEFT OUTER JOIN SCI_PLEDGOR_DTL P ON SPM.CMS_PLEDGOR_DTL_ID = P.CMS_PLEDGOR_DTL_ID AND P.UPDATE_STATUS_IND <> 'D'
	WHERE S.STATUS <> 'DELETED';

-------------------------------
-- DW004 - Receivables
-------------------------------
CREATE VIEW VIEW_SI_DW004_CLMRECCOL AS
	SELECT DISTINCT S.SOURCE_ID, S.CMS_COLLATERAL_ID, ST.SECURITY_TYPE_ID, S.SECURITY_SUB_TYPE_ID, S.SCI_SECURITY_CURRENCY,
		ST.SUBTYPE_STANDARDISED_APPROACH, ST.SUBTYPE_ADVANCED_IRB AS FIRB, ST.SUBTYPE_ADVANCED_IRB AS AIRB,
		S.IS_LEGAL_ENFORCE, S.IS_LEGAL_ENFORCE_DATE, S.SECURITY_MATURITY_DATE,
		LSM.DELETION_DATE, CD.CHARGE_AMOUNT, 'Y' AS IRREVOCABLE_FLAG, '1' AS HOLDING_NO,
		V.VALUATION_CURRENCY, V.CMV, V.FSV, P.CMS_PLEDGOR_DTL_ID
	FROM CMS_SECURITY S
		INNER JOIN CMS_SECURITY_SUB_TYPE ST ON S.SECURITY_SUB_TYPE_ID = ST.SECURITY_SUB_TYPE_ID AND ST.STATUS <> 'DELETED'
		INNER JOIN CMS_LIMIT_SECURITY_MAP LSM ON S.CMS_COLLATERAL_ID = LSM.CMS_COLLATERAL_ID AND LSM.UPDATE_STATUS_IND <> 'D'
		INNER JOIN CMS_LIMIT_CHARGE_MAP LCM ON LSM.CHARGE_ID = LCM.CHARGE_ID AND LCM.STATUS <> 'DELETED'
		INNER JOIN CMS_CHARGE_DETAIL CD ON LCM.CHARGE_DETAIL_ID = CD.CHARGE_DETAIL_ID AND CD.STATUS <> 'DELETED'
		LEFT OUTER JOIN CMS_VALUATION V ON S.CMS_COLLATERAL_ID = V.CMS_COLLATERAL_ID
		LEFT OUTER JOIN SCI_SEC_PLDGR_MAP SPM ON S.CMS_COLLATERAL_ID = SPM.CMS_COLLATERAL_ID AND SPM.UPDATE_STATUS_IND <> 'D'
		LEFT OUTER JOIN SCI_PLEDGOR_DTL P ON SPM.CMS_PLEDGOR_DTL_ID = P.CMS_PLEDGOR_DTL_ID AND P.UPDATE_STATUS_IND <> 'D'
	WHERE S.STATUS <> 'DELETED';

-------------------------------
-- DW005 - Account CRM Link
-------------------------------
CREATE VIEW VIEW_SI_DW005_CLMACTLNK AS
	SELECT S.CMS_COLLATERAL_ID, LSX.LSX_EXT_SYS_ACCT_NUM, CD.CHARGE_AMOUNT, CD.SECURITY_RANK, L.CREATE_DATE, L.CMS_ACT_SEC_COVERAGE
	FROM CMS_SECURITY S, CMS_LIMIT_SECURITY_MAP LSM, SCI_LSP_LMTS_XREF_MAP LXM, SCI_LSP_SYS_XREF LSX,
		CMS_LIMIT_CHARGE_MAP LCM, CMS_CHARGE_DETAIL CD, SCI_LSP_APPR_LMTS L
	WHERE S.CMS_COLLATERAL_ID = LSM.CMS_COLLATERAL_ID AND LSM.CMS_LSP_APPR_LMTS_ID = LXM.CMS_LSP_APPR_LMTS_ID
		AND LXM.CMS_LSP_SYS_XREF_ID = LSX.CMS_LSP_SYS_XREF_ID AND LSM.CMS_LSP_APPR_LMTS_ID = L.CMS_LSP_APPR_LMTS_ID
		AND LSM.CHARGE_ID = LCM.CHARGE_ID AND LCM.CHARGE_DETAIL_ID = CD.CHARGE_DETAIL_ID
		AND S.STATUS <> 'DELETED' AND LSM.UPDATE_STATUS_IND <> 'D' AND LXM.CMS_STATUS <> 'D'
		AND LSX.ACCT_STATUS <> 'D' AND LCM.STATUS <> 'DELETED' AND CD.STATUS <> 'DELETED' AND L.CMS_LIMIT_STATUS <> 'DELETED';

-------------------------------
-- DW006 - Facility CRM Link
-------------------------------
CREATE VIEW VIEW_SI_DW006_CLMFACLNK AS
	SELECT S.CMS_COLLATERAL_ID, L.CMS_LSP_APPR_LMTS_ID, L.SOURCE_ID, CD.CHARGE_AMOUNT, CD.SECURITY_RANK, L.CREATE_DATE, L.CMS_ACT_SEC_COVERAGE
	FROM CMS_SECURITY S, CMS_LIMIT_SECURITY_MAP LSM, SCI_LSP_APPR_LMTS L, CMS_LIMIT_CHARGE_MAP LCM, CMS_CHARGE_DETAIL CD
	WHERE S.CMS_COLLATERAL_ID = LSM.CMS_COLLATERAL_ID AND LSM.CMS_LSP_APPR_LMTS_ID = L.CMS_LSP_APPR_LMTS_ID
		AND LSM.CHARGE_ID = LCM.CHARGE_ID AND LCM.CHARGE_DETAIL_ID = CD.CHARGE_DETAIL_ID
		AND S.STATUS <> 'DELETED' AND LSM.UPDATE_STATUS_IND <> 'D' AND L.CMS_LIMIT_STATUS <> 'DELETED'
		AND LCM.STATUS <> 'DELETED' AND CD.STATUS <> 'DELETED';
		
COMMIT;
