CREATE INDEX LMT_PRF_I4
	ON SCI_LSP_LMT_PROFILE(CMS_ORIG_COUNTRY, CMS_ORIG_ORGANISATION)
	ALLOW REVERSE SCANS 
	COLLECT STATISTICS;
	
CREATE INDEX LMT_PRF_I6
	ON SCI_LSP_LMT_PROFILE(CMS_ORIG_ORGANISATION, CMS_ORIG_COUNTRY, CMS_LSP_LMT_PROFILE_ID)
	ALLOW REVERSE SCANS 
	COLLECT STATISTICS;	
	
CREATE INDEX LMT_PRF_I5
	ON SCI_LSP_LMT_PROFILE(CMS_ACT_SEC_COVERAGE, CMS_REQ_SEC_COVERAGE)
	ALLOW REVERSE SCANS 
	COLLECT STATISTICS;	
	
CREATE INDEX LMT_PRF_I2
	ON SCI_LSP_LMT_PROFILE(CMS_BCA_CREATE_DATE)
	ALLOW REVERSE SCANS 
	COLLECT STATISTICS;
	
create index LE_SUB_PRF_I6 on sci_le_sub_profile
(ulsp_short_name asc, cms_le_sub_profile_id )
allow reverse scans
COLLECT STATISTICS;

CREATE UNIQUE INDEX LSP_APPR_LMTS_IDX6
	ON SCI_LSP_APPR_LMTS(CMS_LSP_APPR_LMTS_ID, CMS_BKG_ORGANISATION DESC, CMS_BKG_COUNTRY DESC, CMS_LIMIT_PROFILE_ID DESC)
	ALLOW REVERSE SCANS 
	COLLECT STATISTICS;

CREATE INDEX LSP_APPR_LMTS_IDX2
	ON SCI_LSP_APPR_LMTS(LMT_OUTER_LMT_ID, SOURCE_ID, CMS_LIMIT_STATUS, CMS_LSP_APPR_LMTS_ID)
	ALLOW REVERSE SCANS 
	COLLECT STATISTICS;	

CREATE INDEX LE_MAIN_PRF_I2
	ON SCI_LE_MAIN_PROFILE (LMP_ID_NUMBER, LMP_ID_TYPE_VALUE, LMP_ID_COUNTRY_ISSUED)
	ALLOW REVERSE SCANS
	COLLECT STATISTICS;
	
CREATE INDEX TRX_I3
	ON TRANSACTION(TRANSACTION_DATE)
	ALLOW REVERSE SCANS 
	COLLECT STATISTICS;
	
CREATE INDEX TRX_I8
	ON TRANSACTION(TEAM_ID)
	ALLOW REVERSE SCANS 
	COLLECT STATISTICS;
	
CREATE INDEX TRX_HIS_I3
	ON TRANS_HISTORY(TRANSACTION_DATE, TRANSACTION_TYPE)
	ALLOW REVERSE SCANS 
	COLLECT STATISTICS;
	
CREATE INDEX INS_PLC_I3
	ON CMS_INSURANCE_POLICY(EXPIRY_DATE)
	ALLOW REVERSE SCANS 
	COLLECT STATISTICS;

CREATE INDEX INS_PLC_I2
	ON CMS_INSURANCE_POLICY(DOCUMENT_NO)
	ALLOW REVERSE SCANS 
	COLLECT STATISTICS;
	
CREATE INDEX LMT_CHG_I1
	ON CMS_LIMIT_CHARGE_MAP(CMS_LSP_CO_BORROW_LMT_ID, CMS_COLLATERAL_ID)
	ALLOW REVERSE SCANS 
	COLLECT STATISTICS;
	
CREATE INDEX LMT_SEC_I3
	ON CMS_LIMIT_SECURITY_MAP(CMS_LSP_CO_BORROW_LMT_ID)
	ALLOW REVERSE SCANS 
	COLLECT STATISTICS;
	
CREATE INDEX "SI_MIMB_CO003_I7" ON "CMS_LIMIT_SECURITY_MAP" 
("UPDATE_STATUS_IND" ASC, "DELETION_DATE" ASC, "CMS_COLLATERAL_ID" ASC, "CMS_LSP_APPR_LMTS_ID" ASC, "SOURCE_ID" ASC) 
ALLOW REVERSE SCANS
COLLECT STATISTICS; 

CREATE INDEX "SI_MIMB_CO004_I3" ON "CMS_LIMIT_SECURITY_MAP" 
("SOURCE_ID" ASC, "UPDATE_STATUS_IND" ASC, "DELETION_DATE" ASC, "CMS_COLLATERAL_ID" ASC, "CMS_LSP_APPR_LMTS_ID" ASC) 
ALLOW REVERSE SCANS 
COLLECT STATISTICS;

CREATE INDEX SEC_I6	
	ON CMS_SECURITY (NEXT_REMARGIN_DATE, SECURITY_SUB_TYPE_ID, CMS_COLLATERAL_ID)
	ALLOW REVERSE SCANS
	COLLECT STATISTICS;
	
CREATE INDEX SEC_I2
	ON CMS_SECURITY(IS_SECURITY_PERFECTED, CMS_COLLATERAL_ID DESC)
	ALLOW REVERSE SCANS 
	COLLECT STATISTICS;
	
create index tat_doc_idx1 on cms_tat_document
	(FILE_FROM_BIZ_CENTER_DATE, DOC_COMPLETION_DATE, CMS_LSP_LMT_PROFILE_ID)
	allow reverse scans
	COLLECT STATISTICS;

CREATE INDEX INS_PLC_I3
	ON CMS_INSURANCE_POLICY(EXPIRY_DATE)
	ALLOW REVERSE SCANS 
	COLLECT STATISTICS;
	
create index INS_PLC_I5 on cms_insurance_policy
	(SOURCE_SECURITY_ID) allow reverse scans
	COLLECT STATISTICS;
	
create index VAL_I4 on cms_valuation 
	(LOS_VALUATION_ID) allow reverse scans
	COLLECT STATISTICS;   			
	
CREATE INDEX SEC_I7
	ON CMS_SECURITY (LOS_SECURITY_DTL_ID)
	ALLOW REVERSE SCANS
	COLLECT STATISTICS;
	
create index LE_MAIN_PRF_I8 on sci_le_main_profile
	(LMP_ID_NUMBER, LMP_ID_TYPE_VALUE, LMP_ID_TYPE_NUM) allow reverse scans
	COLLECT STATISTICS;
	
create index LE_MAIN_PRF_I9 on sci_le_main_profile
	(LMP_SECOND_ID_NUMBER, LMP_SECOND_ID_TYPE_VALUE,LMP_SECOND_ID_TYPE_NUM) allow reverse scans
	COLLECT STATISTICS;
	
create index LE_MAIN_PRF_I10 on sci_le_main_profile
	(LMP_THIRD_ID_NUMBER, LMP_THIRD_ID_TYPE_VALUE, LMP_THIRD_ID_TYPE_NUM) allow reverse scans
	COLLECT STATISTICS;