-- Insert into function access
--Delete from CMS_FUNCTION_ACCESS where ACTION in ('ContractFinancing','CF_FacilityType','CF_TNC','CF_FDR','CF_AdvsPayment','CF_Payment','CF_SG_AdvsPayment','CF_SG_Payment','FacilityType','TNC','FDR','AdvsPayment','Payment','AdvsPayment','Payment');
	
INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800001, 'ContractFinancing' , 'approve', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800002, 'ContractFinancing' , 'delete', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800003, 'ContractFinancing' , 'list_summary', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800004, 'ContractFinancing' , 'list_summary', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800005, 'ContractFinancing' , 'maker_close', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800006, 'ContractFinancing' , 'maker_navigate_tab', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800007, 'ContractFinancing' , 'maker_navigate_tab', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800008, 'ContractFinancing' , 'maker_prepare_close', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800009, 'ContractFinancing' , 'maker_prepare_create', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800010, 'ContractFinancing' , 'maker_prepare_delete', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800011, 'ContractFinancing' , 'maker_prepare_update', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800012, 'ContractFinancing' , 'maker_process', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800013, 'ContractFinancing' , 'maker_update', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800014, 'ContractFinancing' , 'process', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800015, 'ContractFinancing' , 'reject', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800016, 'ContractFinancing' , 'save', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800017, 'ContractFinancing' , 'submit', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800018, 'ContractFinancing' , 'to_track', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800019, 'ContractFinancing' , 'to_track', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800020, 'ContractFinancing' , 'view', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (21800021, 'ContractFinancing' , 'view', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22200001, 'CF_FacilityType' , 'checker_list_summary', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22200002, 'CF_FacilityType' , 'checker_view', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22200003, 'CF_FacilityType' , 'create', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22200004, 'CF_FacilityType' , 'delete', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22200005, 'CF_FacilityType' , 'list_summary', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22200006, 'CF_FacilityType' , 'list_summary', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22200007, 'CF_FacilityType' , 'maker_navigate_tab', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22200008, 'CF_FacilityType' , 'maker_navigate_tab', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22200009, 'CF_FacilityType' , 'maker_prepare_close', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22200010, 'CF_FacilityType' , 'maker_prepare_create', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22200011, 'CF_FacilityType' , 'maker_prepare_update', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22200012, 'CF_FacilityType' , 'update', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22200013, 'CF_FacilityType' , 'view', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22200014, 'CF_FacilityType' , 'view', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22300001, 'CF_TNC' , 'checker_list_summary', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22300002, 'CF_TNC' , 'checker_view', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22300003, 'CF_TNC' , 'create', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22300004, 'CF_TNC' , 'delete', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22300005, 'CF_TNC' , 'list_summary', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22300006, 'CF_TNC' , 'list_summary', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22300007, 'CF_TNC' , 'maker_navigate_tab', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22300008, 'CF_TNC' , 'maker_navigate_tab', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22300009, 'CF_TNC' , 'maker_prepare_close', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22300010, 'CF_TNC' , 'maker_prepare_create', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22300011, 'CF_TNC' , 'maker_prepare_update', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22300012, 'CF_TNC' , 'update', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22300013, 'CF_TNC' , 'view', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22300014, 'CF_TNC' , 'view', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22400001, 'CF_FDR' , 'checker_list_summary', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22400002, 'CF_FDR' , 'checker_view', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22400003, 'CF_FDR' , 'create', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22400004, 'CF_FDR' , 'delete', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22400005, 'CF_FDR' , 'list_summary', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22400006, 'CF_FDR' , 'list_summary', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22400007, 'CF_FDR' , 'maker_navigate_tab', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22400008, 'CF_FDR' , 'maker_navigate_tab', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22400009, 'CF_FDR' , 'maker_prepare_delete', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22400010, 'CF_FDR' , 'maker_prepare_close', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22400011, 'CF_FDR' , 'maker_prepare_create', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22400012, 'CF_FDR' , 'maker_prepare_update', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22400013, 'CF_FDR' , 'update', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22400014, 'CF_FDR' , 'view', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (22400015, 'CF_FDR' , 'view', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100001, 'CF_AdvsPayment' , 'checker_list_summary', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100002, 'CF_AdvsPayment' , 'checker_view', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100003, 'CF_AdvsPayment' , 'create', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100004, 'CF_AdvsPayment' , 'delete', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100005, 'CF_AdvsPayment' , 'list_summary', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100006, 'CF_AdvsPayment' , 'list_summary', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100007, 'CF_AdvsPayment' , 'maker_navigate_tab', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100008, 'CF_AdvsPayment' , 'maker_navigate_tab', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100009, 'CF_AdvsPayment' , 'maker_prepare_delete', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100010, 'CF_AdvsPayment' , 'maker_prepare_close', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100011, 'CF_AdvsPayment' , 'maker_prepare_create', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100012, 'CF_AdvsPayment' , 'maker_prepare_update', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100013, 'CF_AdvsPayment' , 'update', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100014, 'CF_AdvsPayment' , 'view', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100015, 'CF_AdvsPayment' , 'view', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100016, 'CF_AdvsPayment' , 'prepare_form', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100017, 'CF_AdvsPayment' , 'maker_prepare_add_item', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100018, 'CF_AdvsPayment' , 'maker_prepare_edit_item', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100019, 'CF_AdvsPayment' , 'delete_item', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100020, 'CF_AdvsPayment' , 'view_item', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100021, 'CF_AdvsPayment' , 'view_item', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23100022, 'CF_AdvsPayment' , 'refresh', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23200001, 'CF_Payment' , 'checker_list_summary', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23200002, 'CF_Payment' , 'checker_view', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23200003, 'CF_Payment' , 'create', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23200004, 'CF_Payment' , 'delete', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23200005, 'CF_Payment' , 'list_summary', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23200006, 'CF_Payment' , 'list_summary', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23200007, 'CF_Payment' , 'maker_navigate_tab', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23200008, 'CF_Payment' , 'maker_navigate_tab', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23200009, 'CF_Payment' , 'maker_prepare_close', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23200010, 'CF_Payment' , 'maker_prepare_create', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23200011, 'CF_Payment' , 'maker_prepare_update', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23200012, 'CF_Payment' , 'update', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23200013, 'CF_Payment' , 'view', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23200014, 'CF_Payment' , 'view', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300001, 'CF_SG_AdvsPayment' , 'checker_list_summary', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300002, 'CF_SG_AdvsPayment' , 'checker_view', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300003, 'CF_SG_AdvsPayment' , 'create', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300004, 'CF_SG_AdvsPayment' , 'delete', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300005, 'CF_SG_AdvsPayment' , 'list_summary', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300006, 'CF_SG_AdvsPayment' , 'list_summary', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300007, 'CF_SG_AdvsPayment' , 'maker_navigate_tab', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300008, 'CF_SG_AdvsPayment' , 'maker_navigate_tab', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300009, 'CF_SG_AdvsPayment' , 'maker_prepare_delete', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300010, 'CF_SG_AdvsPayment' , 'maker_prepare_close', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300011, 'CF_SG_AdvsPayment' , 'maker_prepare_create', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300012, 'CF_SG_AdvsPayment' , 'maker_prepare_update', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300013, 'CF_SG_AdvsPayment' , 'update', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300014, 'CF_SG_AdvsPayment' , 'view', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300015, 'CF_SG_AdvsPayment' , 'view', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300016, 'CF_SG_AdvsPayment' , 'prepare_form', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300017, 'CF_SG_AdvsPayment' , 'maker_prepare_add_item', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300018, 'CF_SG_AdvsPayment' , 'maker_prepare_edit_item', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300019, 'CF_SG_AdvsPayment' , 'delete_item', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300020, 'CF_SG_AdvsPayment' , 'view_item', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300021, 'CF_SG_AdvsPayment' , 'view_item', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23300022, 'CF_SG_AdvsPayment' , 'refresh', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23400001, 'CF_SG_Payment' , 'checker_list_summary', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23400002, 'CF_SG_Payment' , 'checker_view', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23400003, 'CF_SG_Payment' , 'create', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23400004, 'CF_SG_Payment' , 'delete', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23400005, 'CF_SG_Payment' , 'list_summary', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23400006, 'CF_SG_Payment' , 'list_summary', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23400007, 'CF_SG_Payment' , 'maker_navigate_tab', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23400008, 'CF_SG_Payment' , 'maker_navigate_tab', 11);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23400009, 'CF_SG_Payment' , 'maker_prepare_close', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23400010, 'CF_SG_Payment' , 'maker_prepare_create', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23400011, 'CF_SG_Payment' , 'maker_prepare_update', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23400012, 'CF_SG_Payment' , 'update', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23400013, 'CF_SG_Payment' , 'view', 10);

INSERT INTO CMS_FUNCTION_ACCESS (ID, ACTION, EVENT, ROLE_TYPE)
values (23400014, 'CF_SG_Payment' , 'view', 11);





-- Insert into transaction state matrix

--DELETE FROM TR_STATE_MATRIX WHERE STATEINS = 'CONTRACT_FINANCE';

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5501,'CONTRACT_FINANCE','CHECKER_APPROVE','PENDING_CREATE','ACTIVE','ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5502,'CONTRACT_FINANCE','CHECKER_APPROVE','PENDING_DELETE','CLOSED','CLOSED', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5503,'CONTRACT_FINANCE','CHECKER_APPROVE','PENDING_UPDATE','ACTIVE','ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5504,'CONTRACT_FINANCE','CHECKER_REJECT','PENDING_CREATE','REJECTED','REJECTED', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5505,'CONTRACT_FINANCE','CHECKER_REJECT','PENDING_DELETE','REJECTED','REJECTED', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5506,'CONTRACT_FINANCE','CHECKER_REJECT','PENDING_UPDATE','REJECTED','REJECTED', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5507,'CONTRACT_FINANCE','MAKER_CLOSE','DRAFT','CLOSED','CLOSED', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5508,'CONTRACT_FINANCE','MAKER_CLOSE','REJECTED','CLOSED','CLOSED', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5509,'CONTRACT_FINANCE','MAKER_CLOSE_DELETE','REJECTED','ACTIVE','ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5510,'CONTRACT_FINANCE','MAKER_CLOSE_UPDATE','DRAFT','ACTIVE','ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5511,'CONTRACT_FINANCE','MAKER_CLOSE_UPDATE','REJECTED','ACTIVE','ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5512,'CONTRACT_FINANCE','MAKER_CREATE','DRAFT','PENDING_CREATE','PENDING_CREATE', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5513,'CONTRACT_FINANCE','MAKER_CREATE','ND','PENDING_CREATE','PENDING_CREATE', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5514,'CONTRACT_FINANCE','MAKER_CREATE','REJECTED','PENDING_CREATE','PENDING_CREATE', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5515,'CONTRACT_FINANCE','MAKER_DELETE','ACTIVE','PENDING_DELETE','PENDING_DELETE', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5516,'CONTRACT_FINANCE','MAKER_DELETE','REJECTED','PENDING_DELETE','PENDING_DELETE', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5517,'CONTRACT_FINANCE','MAKER_SAVE','ACTIVE','DRAFT','DRAFT', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5518,'CONTRACT_FINANCE','MAKER_SAVE','DRAFT','DRAFT','DRAFT', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5519,'CONTRACT_FINANCE','MAKER_SAVE','ND','DRAFT','DRAFT', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5520,'CONTRACT_FINANCE','MAKER_SAVE','REJECTED','DRAFT','DRAFT', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5521,'CONTRACT_FINANCE','MAKER_UPDATE','ACTIVE','PENDING_UPDATE','PENDING_UPDATE', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5522,'CONTRACT_FINANCE','MAKER_UPDATE','DRAFT','PENDING_UPDATE','PENDING_UPDATE', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES(5523,'CONTRACT_FINANCE','MAKER_UPDATE','REJECTED','PENDING_UPDATE','PENDING_UPDATE', '1', '1');


-- 3. CMS Trx To Track
--DELETE FROM CMS_TRX_TOTRACK WHERE TRANSACTION_TYPE = 'CONTRACT_FINANCE' ;

insert into CMS_TRX_TOTRACK ( TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE,FROM_STATE, TRANSACTION_SUBTYPE )
values ('CONTRACT_FINANCE', 'ContractFinancing.do?initEvent=to_track&event=to_track&trxID=', 'PENDING_CREATE', 'Pending Create', 'Maintain Contract Financing', null, null);

insert into CMS_TRX_TOTRACK ( TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE,FROM_STATE, TRANSACTION_SUBTYPE )
values ('CONTRACT_FINANCE', 'ContractFinancing.do?initEvent=to_track&event=to_track&trxID=', 'PENDING_UPDATE', 'Pending Update', 'Maintain Contract Financing', null, null);

insert into CMS_TRX_TOTRACK ( TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE,FROM_STATE, TRANSACTION_SUBTYPE )
values ('CONTRACT_FINANCE', 'ContractFinancing.do?initEvent=to_track&event=to_track&trxID=', 'REJECTED', 'Rejected', 'Maintain Contract Financing', null, null);

insert into CMS_TRX_TOTRACK ( TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE,FROM_STATE, TRANSACTION_SUBTYPE )
values ('CONTRACT_FINANCE', 'ContractFinancing.do?initEvent=to_track&event=to_track&trxID=', 'DRAFT', 'Draft', 'Maintain Contract Financing', null, null);

insert into CMS_TRX_TOTRACK ( TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE,FROM_STATE, TRANSACTION_SUBTYPE )
values ('CONTRACT_FINANCE', 'ContractFinancing.do?initEvent=to_track&event=to_track&trxID=', 'PENDING_DELETE', 'Pending Delete', 'Maintain Contract Financing', null, null);

insert into CMS_TRX_TOTRACK ( TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE,FROM_STATE, TRANSACTION_SUBTYPE )
values ('CONTRACT_FINANCE', 'ContractFinancing.do?initEvent=to_track&event=to_track&trxID=', 'ACTIVE', 'Approved', 'Maintain Contract Financing', null, null);


-- 4. CMS State matrix action

-- delete old data if any
--DELETE FROM CMS_STATEMATRIX_ACTION WHERE URL LIKE 'ContractFinancing.do?%' ;

-- pending_create
INSERT INTO CMS_STATEMATRIX_ACTION ( STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL ) 
VALUES ( 5501, 11, 'Process', 'ContractFinancing.do?initEvent=process&event=process&trxID=', NULL); 

-- pending_update
INSERT INTO CMS_STATEMATRIX_ACTION ( STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL ) 
VALUES ( 5503, 11, 'Process', 'ContractFinancing.do?initEvent=process&event=process&trxID=', NULL); 

-- pending_delete
INSERT INTO CMS_STATEMATRIX_ACTION ( STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL ) 
VALUES ( 5502, 11, 'Process', 'ContractFinancing.do?initEvent=process&event=process&trxID=', NULL); 

-- Draf
INSERT INTO CMS_STATEMATRIX_ACTION ( STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL ) 
VALUES ( 5507, 10, 'Process', 'ContractFinancing.do?initEvent=maker_prepare_update&event=maker_prepare_update&trxID=', NULL); 

INSERT INTO CMS_STATEMATRIX_ACTION ( STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL ) 
VALUES ( 5507, 10, 'Close', 'ContractFinancing.do?initEvent=maker_prepare_close&event=maker_prepare_close&trxID=', NULL);

-- Rejected
INSERT INTO CMS_STATEMATRIX_ACTION ( STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL ) 
VALUES ( 5508, 10, 'Process', 'ContractFinancing.do?initEvent=maker_process&event=maker_process&isRejected&trxID=', NULL); 

INSERT INTO CMS_STATEMATRIX_ACTION ( STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL ) 
VALUES ( 5508, 10, 'Close', 'ContractFinancing.do?initEvent=maker_prepare_close&event=maker_prepare_close&isRejected&trxID=', NULL);

