LOAD DATA
INFILE 'FILES\Document Master Facility Global(Collaterals).csv'
 "str '~~~'"
BADFILE 'PARTIAL_ERROR_LOG\Document Master Facility Global(Collaterals).bad'
DISCARDFILE 'PARTIAL_ERROR_LOG\Document Master Facility Global(Collaterals).dsc'
DISCARDMAX 1241513983
APPEND INTO TABLE MIG_FACILITY_DOC_MASTER_ITEM
FIELDS TERMINATED BY '|||'
TRAILING NULLCOLS
(
DOCID "REPLACE(REPLACE(DECODE(UPPER(:DOCID),'NULL',NULL,:DOCID), CHR(10),''), CHR(13),'')",
DOCNAME "DECODE(UPPER(:DOCNAME),'NULL',NULL,:DOCNAME)",
DOCGROUP "DECODE(UPPER(:DOCGROUP),'NULL',NULL,:DOCGROUP)",
DOCTYPE "DECODE(UPPER(:DOCTYPE),'NULL',NULL,:DOCTYPE)",
DOCTENURE "DECODE(UPPER(:DOCTENURE),'NULL',NULL,:DOCTENURE)",
RISKEFFECT "DECODE(UPPER(:RISKEFFECT),'NULL',NULL,:RISKEFFECT)",
INCLUDEINRL "DECODE(UPPER(:INCLUDEINRL),'NULL',NULL,:INCLUDEINRL)"
)