drop table DC_OT;

drop table DC_OT_ERR;

CREATE TABLE DC_OT (
	CIF_NUMBER VARCHAR(20),
	BORROWER_NAME VARCHAR(100),
	ACCOUNT_NUMBER VARCHAR(40),
	BUSINESS_UNIT VARCHAR(15),
	BRANCH_CODE VARCHAR(3),
	CMS_COLLATERAL_ID BIGINT NOT NULL,	
	COLLATERAL_CODE VARCHAR(4),
	--COLLATERAL_CODE_DESC VARCHAR(200), -- ignore description
	COLLATERAL_NAME VARCHAR(30),
	SECURITY_MATURITY_DATE TIMESTAMP, -- update
	SECURITY_PERFECTION_DATE TIMESTAMP, -- update
	LEGAL_ENFORCEABILITY_IND CHAR(1), -- update
	LEGAL_ENFORCEABILITY_DATE TIMESTAMP, -- update 
	ASSET_DESC VARCHAR(250), -- update (optional)
	CURRENT_MARKET_VALUE DECIMAL(17,2), --update
	VALUATION_DATE TIMESTAMP, -- update 
	FSV DECIMAL(20,20), -- update (optional)
	VALUATION_TYPE_DESC VARCHAR(10), --update
	VALUATION_TYPE CHAR(1), -- update
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	VALID_IND CHAR(1) DEFAULT 'Y'
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "DC_OT" 
	ADD CONSTRAINT "DC_OT_U" UNIQUE
		("CMS_COLLATERAL_ID",
		 "REGION");

CREATE TABLE DC_OT_ERR LIKE DC_OT
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE DC_OT_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE DC_OT_ERR
  ADD REASON	CLOB;