DROP TABLE CMS_PROPERTY_STATE_TEMP;
create table CMS_PROPERTY_STATE_TEMP (
	CMS_COLLATERAL_ID BIGINT,
	CMS_STG_COLLATERAL_ID BIGINT,
	SCI_SECURITY_DTL_ID VARCHAR(50),
	STATE_CODE VARCHAR(40)
);

CREATE UNIQUE INDEX PROPERTY_TEMP_IDX1 ON CMS_PROPERTY
("CMS_COLLATERAL_ID" ASC) 
INCLUDE ( "STATE") 
ALLOW REVERSE SCANS ; 

CREATE INDEX PROPERTY_TEMP_IDX2 ON CMS_PROPERTY_STATE_TEMP
("CMS_COLLATERAL_ID" ASC) 
ALLOW REVERSE SCANS ; 

CREATE INDEX PROPERTY_TEMP_IDX3 ON CMS_PROPERTY_STATE_TEMP
("CMS_COLLATERAL_ID" ASC, "STATE_CODE" DESC) 
ALLOW REVERSE SCANS ; 

CREATE UNIQUE INDEX PROPERTY_TEMP_IDX4 ON CMS_STAGE_PROPERTY
("CMS_COLLATERAL_ID" ASC) 
INCLUDE ( "STATE") 
ALLOW REVERSE SCANS ; 

CREATE INDEX PROPERTY_TEMP_IDX5 ON CMS_PROPERTY_STATE_TEMP
("CMS_STG_COLLATERAL_ID" ASC) 
ALLOW REVERSE SCANS ; 

CREATE INDEX PROPERTY_TEMP_IDX6 ON CMS_PROPERTY_STATE_TEMP
("CMS_STG_COLLATERAL_ID" ASC, "STATE_CODE" DESC) 
ALLOW REVERSE SCANS ;
