DROP TABLE MIG_CU001_CU;
DROP TABLE MIG_CA001_AA;
DROP TABLE MIG_CA002_JB;
DROP TABLE MIG_CA003_1;
DROP TABLE MIG_CA003_2_BNM;
DROP TABLE MIG_CA003_3_OFF;
DROP TABLE MIG_CA003_4_REL;
DROP TABLE MIG_CA003_5_INS;
DROP TABLE MIG_CA003_6_MUL;
DROP TABLE MIG_CA003_7_ISL;
DROP TABLE MIG_CA003_8_BBA;
DROP TABLE MIG_CA004;

/* --------- Start of Collateral ---------- */
DROP TABLE MIG_CO001_AB;
DROP TABLE MIG_CO002_AB_GOLD;
DROP TABLE MIG_CO005_CS;
DROP TABLE MIG_CO008_MS;
DROP TABLE MIG_CO009_PT;
DROP TABLE MIG_CO010_GT;
DROP TABLE MIG_CO011_OT;
DROP TABLE MIG_CO012_IN;
DROP TABLE MIG_CO014_CL;

DROP TABLE MIG_CO015_VL;
DROP TABLE MIG_CO016_IN;
DROP TABLE MIG_CO017_CD;
DROP TABLE MIG_CO018_PG;
DROP TABLE MIG_CO019_PL;

/* --------- Start of Schema ---------- */
CREATE TABLE MIG_CU001_CU(
	CMS_LE_MAIN_PROFILE_ID 		BIGINT,
    IS_VALID                    CHAR(1)     DEFAULT 'Y',    
    CIF_ID                      VARCHAR(19),    
    PRIMARY_ADD_TYPE_CODE       VARCHAR(10),    
    SECONDARY_ADD_TYPE_CODE     VARCHAR(10),    
    MAILING_ADD_TYPE_CODE     	VARCHAR(10),    
    CUST_NAME_L                 VARCHAR(150),
    CUST_NAME_S                 VARCHAR(80),
    CUST_CLASS_CODE             VARCHAR(40),
    ID_TYPE_CODE                VARCHAR(40),    
    ID_ISSUE_COUNTRY            VARCHAR(2),
    ID_NUMBER                   VARCHAR(100),
    ID_ISSUE_DATE              TIMESTAMP,
    SECONDARY_ID_TYPE_CODE      VARCHAR(10),    
    SECONDARY_ID_COUNTRY_ISSUED VARCHAR(2), 
    SECONDARY_ID_NUMBER         VARCHAR(100),
    CUST_TYPE                   VARCHAR(10),
    CUST_START_DATE             TIMESTAMP,
    BLACKLISTED                 VARCHAR(1),
    ISIC_CODE                   VARCHAR(10),
    PRIMARY_ADD_1               VARCHAR(100),
    PRIMARY_ADD_2               VARCHAR(100),
    PRIMARY_ADD_3               VARCHAR(50),
    PRIMARY_ADD_4               VARCHAR(50),
    PRIMARY_ADD_5               VARCHAR(50),
    PRIMARY_POSTCODE            VARCHAR(30),
    PRIMARY_CITY                VARCHAR(40),
    PRIMARY_STATE               VARCHAR(40),
    PRIMARY_COUNTRY             VARCHAR(2),
    SECONDARY_ADD_1             VARCHAR(100),
    SECONDARY_ADD_2             VARCHAR(100),
    SECONDARY_ADD_3             VARCHAR(50),
    SECONDARY_ADD_4             VARCHAR(50),
    SECONDARY_ADD_5             VARCHAR(50),
    SECONDARY_POSTCODE          VARCHAR(30),
    SECONDARY_CITY              VARCHAR(40),
    SECONDARY_STATE             VARCHAR(40),
    SECONDARY_COUNTRY           VARCHAR(2),
    LMP_ACC_OFFICER_NUM         VARCHAR(40), 
    LMP_ACC_OFFICER_VALUE       VARCHAR(10),
    CMS_SUB_ORIG_ORGANISATION   VARCHAR(10),
    LSP_DMCL_CNTRY_ISO_CODE     VARCHAR(2),
    MAILING_ADD_1             	VARCHAR(100),
    MAILING_ADD_2             	VARCHAR(100),
    MAILING_ADD_3             	VARCHAR(50),
    MAILING_ADD_4             	VARCHAR(50),
    MAILING_ADD_5             	VARCHAR(50),
    MAILING_POSTCODE          	VARCHAR(30),
    MAILING_CITY              	VARCHAR(40),
    MAILING_STATE             	VARCHAR(40),
    MAILING_COUNTRY           	VARCHAR(2),	
    CUST_CLASS_CAT              VARCHAR(20) DEFAULT '56',
    ID_TYPE_CAT                 VARCHAR(20) DEFAULT 'ID_TYPE',
    SECONDARY_ID_TYPE_CAT       VARCHAR(40) DEFAULT 'ID_TYPE',
    CUST_TYPE_CAT               VARCHAR(20) DEFAULT '8',
    INCOME_GROUP_CAT            VARCHAR(20) DEFAULT 'INCOME_RANGE',
    ISIC_CAT                    VARCHAR(10) DEFAULT '17',
    LANGUAGE_CAT                VARCHAR(40) DEFAULT '11',
    PRIMARY_ADD_TYPE_CAT        VARCHAR(40) DEFAULT '4',    
    SECONDARY_ADD_TYPE_CAT      VARCHAR(40) DEFAULT '4',
	MAILING_ADD_TYPE_CAT      	VARCHAR(40) DEFAULT '4',
	RECORD_TYPE                 VARCHAR(1)
)in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX MIG_CU001_CU_IDX1 ON MIG_CU001_CU
(IS_VALID ASC, CIF_ID ASC) ALLOW REVERSE SCANS;   

CREATE INDEX MIG_CU001_CU_IDX2 ON MIG_CU001_CU
	(IS_VALID DESC, CMS_LE_MAIN_PROFILE_ID, PRIMARY_ADD_TYPE_CODE) 
	ALLOW REVERSE SCANS;

-- Added by KLYong (For QC report 7)
CREATE INDEX MIG_CU001_CU_IDX3 ON MIG_CU001_CU
	("CIF_ID" ASC, "CUST_NAME_S" DESC)
	ALLOW REVERSE SCANS; 

-- CREATE INDEX MIG_CU001_CU_IDX4 ON MIG_CU001_CU
-- 	("IS_VALID" ASC, "LSP_DMCL_CNTRY_ISO_CODE" ASC, "CMS_SUB_ORIG_ORGANISATION" ASC, "CIF_ID" ASC) 
-- 	ALLOW REVERSE SCANS; 
	

CREATE TABLE MIG_CA001_AA(  
    CMS_ACT_CIF_ID  	    BIGINT,     
    CMS_ACT_LMT_PROFILE_ID	BIGINT,
    IS_VALID                CHAR(1)     DEFAULT 'Y',       
    CIF_ID                  VARCHAR(19),
    CIF_SOURCE              VARCHAR(4),
    LOS_BCA_REF_NUM         VARCHAR(35),
    AA_NUMBER               VARCHAR(35),
    JOINT_BORROWER_IND      VARCHAR(1),
    AA_APPROVED_DATE        TIMESTAMP,
    ORI_LOC_COUNTRY         VARCHAR(2),
    ORI_LOC_ORG_CODE        VARCHAR(20),
    ANNUAL_REVIEW_DATE      TIMESTAMP,
    AA_STAT                 VARCHAR(20),
    AA_CREATE_DATE          TIMESTAMP,
    APPLICATION_TYPE        VARCHAR(2),
    APPLICATION_LAW_TYPE    VARCHAR(3),
    AA_STATUS_CAT           VARCHAR(40) DEFAULT 'AA_STATUS',
    ORI_LOC_ORG_CAT         VARCHAR(20) DEFAULT '40',
    APP_LAW_TYPE_CAT        VARCHAR(40) DEFAULT 'APP_LAW',
    RECORD_TYPE             VARCHAR(1)
)in CMS_MIG index in CMS_MIG_INDEX;

-- CREATE INDEX MIG_CA001_AA_IDX1 ON MIG_CA001_AA
-- (IS_VALID ASC, AA_NUMBER ASC);  

CREATE INDEX MIG_CA001_AA_IDX2 ON MIG_CA001_AA
(IS_VALID, CIF_ID ASC);  

CREATE INDEX MIG_CA001_AA_IDX3 ON MIG_CA001_AA
(IS_VALID ASC, LOS_BCA_REF_NUM ASC);  

-- Added by KLYong
CREATE INDEX MIG_CA001_AA_IDX4 ON MIG_CA001_AA
	("IS_VALID" ASC, "CIF_ID" ASC, "LOS_BCA_REF_NUM" ASC) 
	ALLOW REVERSE SCANS; 

-- For QCReport 7
CREATE INDEX MIG_CA001_AA_IDX5 ON MIG_CA001_AA
	("LOS_BCA_REF_NUM" ASC, "CIF_ID" ASC, "APPLICATION_TYPE" ASC) 
	ALLOW REVERSE SCANS; 
	
-- For QCReport 7	
CREATE INDEX MIG_CA001_AA_IDX6 ON MIG_CA001_AA
	("LOS_BCA_REF_NUM" ASC, "CIF_ID" ASC, "APPLICATION_LAW_TYPE" ASC) 
	ALLOW REVERSE SCANS; 	

CREATE INDEX MIG_CA001_AA_IDX7 ON MIG_CA001_AA
	(IS_VALID , CMS_ACT_LMT_PROFILE_ID)
	ALLOW REVERSE SCANS;

CREATE TABLE MIG_CA002_JB(
    IS_VALID    CHAR(1)     DEFAULT 'Y',    
    CMS_ACT_CIF_ID  	    BIGINT,
    CMS_ACT_LMT_PROFILE_ID  	    BIGINT,    
    CIF_ID      VARCHAR(19),
    CIF_SOURCE  VARCHAR(4),
    AA_NUMBER   VARCHAR(35),
    RECORD_TYPE VARCHAR(1)   
)in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX MIG_CA002_JB_IDX1 ON MIG_CA002_JB
(IS_VALID ASC, AA_NUMBER ASC);  

CREATE INDEX MIG_CA002_JB_IDX2 ON MIG_CA002_JB
(CIF_ID ASC);

CREATE TABLE MIG_CA003_1(
    CMS_ACT_LMT_PROFILE_ID          BIGINT,
    CMS_ACT_LMT_ID 	                BIGINT,
    CMS_STG_LMT_ID 	                BIGINT,
    CMS_ACT_FAC_MASTER_ID           BIGINT,
    CMS_STG_FAC_MASTER_ID           BIGINT,    
    IS_VALID    	                CHAR(1)     DEFAULT 'Y',        
    LOS_AA_NUMBER	                VARCHAR(35),
    AA_NUMBER 		                VARCHAR(19),
    LIMIT_ID 		                VARCHAR(43),
    FACILITY_CODE 	                VARCHAR(3),
    FACILITY_SEQ 	                BIGINT,
    CIF_ID 		                    VARCHAR(19),    
    ACF_NO 		                    VARCHAR(20),    
    EXPIRY_DATE 	                TIMESTAMP,
    ORI_LOC_COUNTRY 	            VARCHAR(2),
    ORG_LOC_ORG_CODE 	            VARCHAR(5),
    PRODUCT_TYPE_CODE 	            VARCHAR(10),
    LIMIT_CURRENCY 	                VARCHAR(3),
    LIMIT_AMT 		                DECIMAL(15,2),
    LIMIT_TENOR 	                BIGINT,
    LIMIT_TENOR_UOM 	            VARCHAR(1),
    DRAWING_LIMIT_AMT 	            DECIMAL(15,2),
    OUTSTANDING_AMT 	            DECIMAL(16,2),
    FINANCED_AMOUNT	                DECIMAL(15,2),
    APPLICATION_DATE	            TIMESTAMP,
    INSTALLMENT_AMOUNT	            DECIMAL(15,2),
    FINAL_PAYMENT	                DECIMAL(15,2),
    LOAN_PURPOSE_CODE_VALUE         VARCHAR(2),
    OFFER_DATE		                TIMESTAMP,
    OFFER_ACCEPTED_DATE	            TIMESTAMP,
    APPROVED_DATE	                TIMESTAMP,
    PERSON_APPROVED_CODE_VALUE      VARCHAR(10),
    CAR_CODE_FLAG	                VARCHAR(1),
    CAR_CODE_VALUE	                VARCHAR(2),
    OFFICER_CODE_VALUE	            VARCHAR(10),
    LMT_STATUS_CODE_VALUE           VARCHAR(2),
    FAC_STATUS_CODE_VALUE           VARCHAR(1),
    INTEREST_RATE	                DECIMAL(11,7),
    INTEREST_TYPE_CODE_VALUE        VARCHAR(5),
    SPREAD		                    DECIMAL(11,7),
    SPREAD_SIGN		                VARCHAR(1),
    PRIME_RATE_FLOOR	            DECIMAL(11,7),
    PRIME_RATE_CEILING	            DECIMAL(11,7),
    PRIME_REVIEW_DATE	            TIMESTAMP,
    PRIME_REVIEW_TERM	            SMALLINT,
    PRIME_REVIEW_TERM_CODE_VALUE    VARCHAR(1),
    OD_EXCESS_RATE_VAR	            DECIMAL(11,7),
    OD_EXCESS_RATE_VAR_CODE         VARCHAR(1),
    PAR_VALUE_SHARES	            VARCHAR(1),
    DEALER_NUM_LPP_CODE_VALUE       VARCHAR(20),
    LATE_CHARGE_TYPE	            SMALLINT,
    COMMISSION_FEES	                DECIMAL(15,2),
    HANDLING_FEES	                DECIMAL(15,2),
    SUBSIDY_AMOUNT	                DECIMAL(15,2),
    OTHERS_FEE		                DECIMAL(15,2),
    COMMISSION_RATE	                DECIMAL(11,7),
    COMMISSION_BASIS_CODE_VALUE     VARCHAR(2),
    MAX_COMSSN_AMOUNT	            DECIMAL(15,2),
    MIN_COMSSN_AMOUNT	            DECIMAL(15,2),
    STANDBY_LINE_FAC_CODE           VARCHAR(3),
    STANDBY_LINE_FAC_SEQ            BIGINT,
    COMMITMENT_RATE	                DECIMAL(11,7),
    COMTMT_RATE_NUM_CODE_VALUE      VARCHAR(5),
    LAST_MAINTENANCE_DATE           TIMESTAMP,
    ORIGINAL_AMOUNT	                DECIMAL(15,2),
    MAIN_FACILITY_IND	            VARCHAR(1),
    MAIN_FACILITY_AA_NUM            VARCHAR(19),
    MAIN_FACILITY_CODE	            VARCHAR(3),
    MAIN_FACILITY_SEQ	            BIGINT,
    STANDBY_LINE	                VARCHAR(1),
    LEVEL		                    SMALLINT,
    UTILISED_AMOUNT	                DECIMAL(15,2),
    SPEC_PROVISION	                DECIMAL(15,2),
    INT_IN_SUSPENSE	                DECIMAL(15,2),
    OUTSTANDING_AMOUNT	            DECIMAL(15,2),
    PAYMENT_CODE_VALUE           	VARCHAR(1),
    PAYMENT_FREQ_VALUE         		VARCHAR(3),
    PAYMENT_FREQ_CODE_VALUE      	VARCHAR(1),
    INT_PAYMENT_FREQ_VALUE     		VARCHAR(3),
    INT_PAYMENT_FREQ_CODE_VALUE  	VARCHAR(1),
    GRADE_PERIOD_VALUE         		VARCHAR(3),
    GRADE_PERIOD_CODE_VALUE      	VARCHAR(1),
    REVOLVING_IND	                VARCHAR(1),
    REVOLVING_ON_CRITERIA_IND       VARCHAR(1),
    FLOOR_PLEDGED_LIMIT	            DECIMAL(15,2),
    ACTUAL_PLEDGED_LIMIT            DECIMAL(15,2),
    ALT_SCHEDULE	                VARCHAR(1),
    AVAIL_PERIOD_MONTH	            SMALLINT,
    AVAIL_PERIOD_DAY	            SMALLINT,
    RETENTION_SUM	                DECIMAL(15,2),
    RETENTION_PERIOD	            SMALLINT,
    RETENTION_PERIOD_CODE           VARCHAR(1),
    APPL_SRC_CODE_VALUE	            VARCHAR(10),
    LAWYER_CODE_VALUE	            VARCHAR(10),
    DISBURSEMENT_MANNER	            VARCHAR(2),
    CAL_FIRST_INSTL_DATE            VARCHAR(1),
    ISO_REFERRAL_NUM	            VARCHAR(20),
    ALLOW_INCENTIVE_IND	            VARCHAR(1),
    CGC_BNM_APPROVED_DATE           TIMESTAMP,
    ALT_RATE		                VARCHAR(1),
    CREDIT_LINE_IND	                VARCHAR(1),
    PROD_PACKAGE_CODE_VALUE         VARCHAR(10),
    EFFECTIVE_COSE_OF_FUND          VARCHAR(1),
    ECOF_ADMIN_COST	                DECIMAL(15,2),
    ECOF_RATE		                DECIMAL(11,9),
    ECOF_VARIANCE	                DECIMAL(11,9),
    ECOF_VARIANCE_CODE	            VARCHAR(1),
    AVAIL_DATE		                TIMESTAMP,
    AVAIL_PERIOD	                VARCHAR(2),
    DATE_INSTRUCTED	                TIMESTAMP,
    SOLICITOR_REFERENCE	            VARCHAR(40),
    DEPARTMENT_CODE_VALUE           VARCHAR(5),
    REFINANCE_FROM_BANK_CODE_VALUE  VARCHAR(10),
    SOLICITOR_NAME	                VARCHAR(20),
	ENTERED_DATE					TIMESTAMP,
	INTEREST_BASE					SMALLINT,
	INTEREST_MODE					VARCHAR(1),
	INTEREST_YEAR_BASE				SMALLINT,
    ORG_LOC_ORG_CAT 	            VARCHAR(20) DEFAULT '40',
    PRODUCT_TYPE_CAT 	            VARCHAR(20) DEFAULT '27',
    FACILITY_TYPE_CAT 	            VARCHAR(20) DEFAULT '26',
    LMT_TENOR_BASIS_NUM	            VARCHAR(20) DEFAULT '28',
    LOAN_PURPOSE_CODE_NUM           VARCHAR(20) DEFAULT 'LOAN_PURPOSE',
    PERSON_APPROVED_CODE_NUM        VARCHAR(20) DEFAULT 'APPROVED_BY',
    CAR_CODE_NUM 	                VARCHAR(20) DEFAULT 'CAR_CODE',
    OFFICER_CODE_NUM 	            VARCHAR(20) DEFAULT 'OFFICER',
    LMT_STATUS_CODE_NUM	            VARCHAR(20) DEFAULT 'LMT_STATUS',
    FAC_STATUS_CODE_NUM	            VARCHAR(20) DEFAULT 'FACILITY_STATUS',
    INTEREST_TYPE_CODE_NUM          VARCHAR(20) DEFAULT 'FAC_RATE',
    DEALER_NUM_LPP_CODE_NUM         VARCHAR(20) DEFAULT 'DEALER',
    COMMISSION_BASIS_CODE_NUM       VARCHAR(20) DEFAULT 'COMMISSION_BASIS',
    COMTMT_RATE_NUM_CODE_NUM        VARCHAR(20) DEFAULT 'FAC_RATE',
    APPL_SRC_CODE_NUM               VARCHAR(20) DEFAULT 'APPLICATION_SOURCE',
    LAWYER_CODE_NUM                 VARCHAR(20) DEFAULT 'SOLICITOR',
    PROD_PACKAGE_CODE_NUM           VARCHAR(20) DEFAULT 'PRODUCT_PACKAGE',
    DEPARTMENT_CODE_NUM             VARCHAR(20) DEFAULT 'DEPARTMENT',
    REFINANCE_FROM_BANK_CODE_NUM    VARCHAR(20) DEFAULT 'REFINANCE_BANK',
    PRIME_REVIEW_TERM_CODE_NUM      VARCHAR(25) DEFAULT 'PRIME_REVIEW_TERM_CODE',
    RECORD_TYPE		                VARCHAR(1)    
)in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX MIG_CA003_1_IDX1 ON MIG_CA003_1
(IS_VALID ASC, AA_NUMBER ASC, LIMIT_ID ASC, FACILITY_CODE ASC, FACILITY_SEQ ASC) ALLOW REVERSE SCANS;   

CREATE INDEX MIG_CA003_1_IDX2 ON MIG_CA003_1
(CIF_ID ASC);  

CREATE INDEX MIG_CA003_1_IDX3 ON MIG_CA003_1
(IS_VALID DESC, CMS_ACT_FAC_MASTER_ID ASC) ALLOW REVERSE SCANS;   

CREATE INDEX MIG_CA003_1_IDX4 ON MIG_CA003_1 
(LIMIT_ID ASC, IS_VALID DESC) ALLOW REVERSE SCANS ; 

CREATE INDEX MIG_CA003_1_IDX5 ON MIG_CA003_1 
("IS_VALID" ASC, "CMS_STG_FAC_MASTER_ID" ASC, "LIMIT_ID" ASC) 
ALLOW REVERSE SCANS ; 

-- CREATE INDEX MIG_CA003_1_IDX6 ON MIG_CA003_1
    -- (IS_VALID, CMS_ACT_LMT_ID)
    -- ALLOW REVERSE SCANS;
    
CREATE INDEX MIG_CA003_1_IDX6 ON MIG_CA003_1
(CMS_ACT_LMT_ID ASC, IS_VALID DESC)
ALLOW REVERSE SCANS;
    
    
CREATE INDEX MIG_CA003_1_IDX7 ON MIG_CA003_1
(CMS_ACT_LMT_PROFILE_ID, IS_VALID DESC, FAC_STATUS_CODE_VALUE)
ALLOW REVERSE SCANS;

-- Added By KLYong
CREATE INDEX MIG_CA003_1_IDX8 ON MIG_CA003_1
	("LIMIT_ID" ASC, "LOS_AA_NUMBER" ASC) 
	ALLOW REVERSE SCANS; 


CREATE TABLE MIG_CA003_2_BNM (
    CMS_ACT_FAC_MASTER_ID   	    BIGINT,
	CMS_ACT_LIMIT_ID				BIGINT,
    IS_VALID    	    	        CHAR(1)     DEFAULT 'Y',    
    LMT_ID                          VARCHAR(43),
    LLP_BCA_REF_NUM                 VARCHAR(19),
    LMT_FAC_CODE                    VARCHAR(19),
    LMT_FAC_SEQ                     BIGINT,
    INDUSTRY_CODE_VALUE		        VARCHAR(4),
    SECTOR_CODE_VALUE		        VARCHAR(2),
    STATE_CODE_VALUE		        VARCHAR(2),
    BUMI_NRCC_CODE_VALUE	        VARCHAR(1),
    SMALL_SCALE_CODE_VALUE	        VARCHAR(1),
    PRESCRIBED_RATE_CODE_VALUE	    VARCHAR(2),
    RELATIONSHIP_CODE_VALUE	        VARCHAR(1),
    GOODS_FINANCED_ONE_CODE_VALUE   VARCHAR(1),
    GOODS_FINANCED_TWO_CODE_VALUE   VARCHAR(1),
    EXEMPTED_CODE_IND		        VARCHAR(1),
    EXEMPTED_CODE_VALUE		        VARCHAR(4),
    HOST_TIER_SEQ		            BIGINT,
    PURPOSE_CODE_VALUE		        VARCHAR(4),
    INDUSTRY_CODE_NUM		        VARCHAR(40) DEFAULT 'BNM_INDUSTRY',
    SECTOR_CODE_NUM		            VARCHAR(40) DEFAULT '8',
    STATE_CODE_NUM		            VARCHAR(40) DEFAULT 'BNM_STATE',
    BUMI_NRCC_CODE_NUM		        VARCHAR(40) DEFAULT 'BNM_BUMI_NRCC',
    SMALL_SCALE_CODE_NUM	        VARCHAR(40) DEFAULT 'BNM_SML_SCALE',
    PRESCRIBED_RATE_CODE_NUM	    VARCHAR(40) DEFAULT 'BNM_PRSCB_RT',
    RELATIONSHIP_CODE_NUM	        VARCHAR(40) DEFAULT 'BNM_RELSHIP',
    GOODS_FINANCED_ONE_CODE_NUM	    VARCHAR(40) DEFAULT 'BNM_GOOD_FINANCE_1',
    GOODS_FINANCED_TWO_CODE_NUM	    VARCHAR(40) DEFAULT 'BNM_GOOD_FINANCE_2',
    EXEMPTED_CODE_NUM		        VARCHAR(40) DEFAULT 'BNM_EXMPT_CODE',
    PURPOSE_CODE_NUM		        VARCHAR(40) DEFAULT 'BNM_PURPOSE',
    RECORD_TYPE 	                VARCHAR(1)    
)in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX MIG_CA003_2_IDX1 ON MIG_CA003_2_BNM
(LMT_ID ASC, LLP_BCA_REF_NUM ASC, LMT_FAC_CODE ASC, LMT_FAC_SEQ ASC, IS_VALID DESC) ALLOW REVERSE SCANS;   

CREATE INDEX MIG_CA003_2_IDX2 ON MIG_CA003_2_BNM
(IS_VALID DESC, CMS_ACT_FAC_MASTER_ID ASC) ALLOW REVERSE SCANS;   

CREATE INDEX MIG_CA003_2_IDX3 ON MIG_CA003_2_BNM
	(IS_VALID, LMT_ID)
	ALLOW REVERSE SCANS;
	
CREATE INDEX MIG_CA003_2_IDX4 ON MIG_CA003_2_BNM
	(IS_VALID, CMS_ACT_LIMIT_ID)
	ALLOW REVERSE SCANS;
		
CREATE TABLE MIG_CA003_3_OFF (
    CMS_ACT_FAC_MASTER_ID   	    BIGINT,
    CMS_STG_FAC_MASTER_ID  	    BIGINT,
    CMS_ACT_FAC_OFFICER_ID   	    BIGINT,
	CMS_ACT_LIMIT_ID			BIGINT,
    IS_VALID    	    	    CHAR(1)     DEFAULT 'Y',    
    LMT_ID                          VARCHAR(43),
    LLP_BCA_REF_NUM                 VARCHAR(19),
    LMT_FAC_CODE                    VARCHAR(19),
    LMT_FAC_SEQ                     BIGINT,
    SEQ_NUM		    	    BIGINT,
    RELATIONSHIP_CODE_VALUE	    VARCHAR(2),
    OFFICER_CODE_VALUE		    VARCHAR(10),
    OFFICER_TYPE_CODE_VALUE	    VARCHAR(3),
    RELATIONSHIP_CODE_NUM	    VARCHAR(40) DEFAULT 'OFFICER_RELATIONSHIP',
    OFFICER_CODE_NUM		    VARCHAR(40) DEFAULT 'OFFICER',
    OFFICER_TYPE_CODE_NUM	    VARCHAR(40) DEFAULT 'OFFICER_TYPE',
    RECORD_TYPE 	            VARCHAR(1)    
)in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX MIG_CA003_3_IDX1 ON MIG_CA003_3_OFF
(LMT_ID ASC, LLP_BCA_REF_NUM ASC, LMT_FAC_CODE ASC, LMT_FAC_SEQ ASC, IS_VALID DESC) ALLOW REVERSE SCANS;  

CREATE INDEX MIG_CA003_3_IDX2 ON MIG_CA003_3_OFF
(LMT_ID ASC, SEQ_NUM DESC) ALLOW REVERSE SCANS;  

CREATE INDEX MIG_CA003_3_IDX3 ON MIG_CA003_3_OFF
(IS_VALID DESC, CMS_ACT_FAC_MASTER_ID ASC, CMS_ACT_FAC_OFFICER_ID) ALLOW REVERSE SCANS;  

-- Added by KLYong
CREATE INDEX MIG_CA003_3_IDX4 ON MIG_CA003_3_OFF
	("SEQ_NUM" ASC, "IS_VALID" ASC, "CMS_ACT_FAC_MASTER_ID" ASC, "CMS_ACT_FAC_OFFICER_ID" ASC) 
	ALLOW REVERSE SCANS; 


CREATE TABLE MIG_CA003_4_REL (
	CMS_ACT_FAC_MASTER_ID   	BIGINT,
	CMS_STG_FAC_MASTER_ID  	    	BIGINT,
	CMS_ACT_FAC_RELATIONSHIP_ID    	BIGINT,	
	CMS_ACT_LIMIT_ID		BIGINT,
	IS_VALID    	        	CHAR(1) 	DEFAULT 'Y',	
	LMT_ID				VARCHAR(43),
	LLP_BCA_REF_NUM			VARCHAR(19),
	LMT_FAC_CODE			VARCHAR(3),
	LMT_FAC_SEQ			BIGINT,
	CIF_NUMBER 			VARCHAR(19),
	ACCT_RELATIONSHIP_CODE_NUM	VARCHAR(15) DEFAULT 'RELATIONSHIP',
	ACCT_RELATIONSHIP_CODE_VALUE	VARCHAR(2),
	GUARANTEE_AMOUNT		DECIMAL(15,2),
	GUARANTEE_PERCENTAGE		DECIMAL(11,7),
	SHARE_HOLDER_PERCENTAGE		DECIMAL(11,7),
	HOST_ADD_SEQ_NUM		BIGINT,
	RECEIVE_MAIL_CODE		VARCHAR(1),
	HOLD_MAIN_CODE_NUM		VARCHAR(10) DEFAULT 'HOLD_MAIL',
	HOLD_MAIN_CODE_VALUE		VARCHAR(1),
	NAME_ASSOC_WITH_FAC_ORDER	SMALLINT,
	NAME_CONJUNCTION_POSITION	CHARACTER(1),
	NAME_CONJUNCTION_CAT		VARCHAR(18) DEFAULT 'NAME_CONJUNCTION',
	NAME_CONJUNCTION_CODE		VARCHAR(10),
	PROFIT_RATIO			DECIMAL(11,7),
	DIVIDEND_RATIO			DECIMAL(11,7),
	CUSTOMER_NAME			VARCHAR(80),
	CURRENCY_CODE			VARCHAR(3),
	CMS_LE_MAIN_PROFILE_ID          BIGINT      DEFAULT 0, 	
	RECORD_TYPE			VARCHAR(1)
)in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX MIG_CA003_4_IDX1 ON MIG_CA003_4_REL
    (IS_VALID DESC, LMT_ID ASC) ALLOW REVERSE SCANS;
	
CREATE INDEX MIG_CA003_4_IDX2 ON MIG_CA003_4_REL
    (LMT_ID ASC, CIF_NUMBER DESC) ALLOW REVERSE SCANS;
	
-- CREATE INDEX MIG_CA003_4_IDX3 ON MIG_CA003_4_REL
-- (IS_VALID DESC, CMS_ACT_FAC_MASTER_ID ASC) ALLOW REVERSE SCANS;  

-- Added by KYong	
CREATE INDEX MIG_CA003_4_IDX4 ON MIG_CA003_4_REL
	("IS_VALID" ASC, "CMS_ACT_FAC_MASTER_ID" ASC, "CMS_ACT_FAC_RELATIONSHIP_ID" ASC) 
	ALLOW REVERSE SCANS; 
	
-- CREATE INDEX MIG_CA003_4_IDX5 ON MIG_CA003_4_REL
-- 	("CMS_ACT_FAC_MASTER_ID" ASC, "IS_VALID" DESC) 
-- 	ALLOW REVERSE SCANS; 

--create index mig_ca003_4_idx6 on mig_ca003_4_rel
--	(is_valid, cif_number, cms_act_fac_master_id)
--	allow reverse scans;	

--create index mig_ca003_4_idx6 on mig_ca003_4_rel
--	(is_valid, cms_act_fac_master_id, cif_number)
--	allow reverse scans;	

CREATE INDEX MIG_CA003_4_IDX6 ON MIG_CA003_4_REL
	(IS_VALID, CMS_ACT_LIMIT_ID) ALLOW REVERSE SCANS;

CREATE TABLE MIG_CA003_5_INS (
    CMS_ACT_FAC_MASTER_ID   	    BIGINT,
    CMS_STG_FAC_MASTER_ID  	    	BIGINT,
    CMS_REF_ID_1                BIGINT,
    CMS_REF_ID_2                BIGINT,
    MIG_SET_1                   CHAR(1)     DEFAULT 'N',
    MIG_SET_2                   CHAR(1)     DEFAULT 'N',
    IS_VALID    	            CHAR(1)     DEFAULT 'Y',    
    LMT_ID                      VARCHAR(43),
    LLP_BCA_REF_NUM             VARCHAR(19),
    LMT_FAC_CODE                VARCHAR(19),
    LMT_FAC_SEQ                 BIGINT,
    COVERAGE_TYPE_CODE_VALUE	VARCHAR(10),
    INSR_COMPANY_CODE_VALUE 	VARCHAR(10),
    POLICY_NUMBER           	VARCHAR(100),
    POLICY_NUMBER_CV_NOTE   	VARCHAR(100),
    INSURED_AMOUNT          	DECIMAL(20,2),
    INSURANCE_PREMIUM       	DECIMAL(20,2),
    ISSUED_DATE             	TIMESTAMP,
    EXPIRY_DATE             	TIMESTAMP,
    EFFECTIVE_DATE          	TIMESTAMP,
    ARRANGEMENT_IND         	CHARACTER(1),
    REMARKS                 	VARCHAR(100),
    -- 2nd set of data
    COVERAGE_TYPE_CODE_VALUE_1	VARCHAR(10),
    INSR_COMPANY_CODE_VALUE_1 	VARCHAR(10),
    POLICY_NUMBER_1           	VARCHAR(100),
    POLICY_NUMBER_CV_NOTE_1   	VARCHAR(100),
    INSURED_AMOUNT_1          	DECIMAL(20,2),
    INSURANCE_PREMIUM_1       	DECIMAL(20,2),
    ISSUED_DATE_1             	TIMESTAMP,
    EXPIRY_DATE_1             	TIMESTAMP,
    EFFECTIVE_DATE_1          	TIMESTAMP,
    ARRANGEMENT_IND_1         	CHARACTER(1),
    REMARKS_1                 	VARCHAR(100),
    COVERAGE_TYPE_CODE_NUM  	VARCHAR(40) DEFAULT 'INSURANCE_TYPE',
    INSR_COMPANY_CODE_NUM   	VARCHAR(40) DEFAULT 'INSURER_NAME',
    RECORD_TYPE 	            VARCHAR(1)    
)in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX MIG_CA003_5_IDX1 ON MIG_CA003_5_INS
    (LMT_ID ASC, IS_VALID DESC) ALLOW REVERSE SCANS;   

CREATE INDEX MIG_CA003_5_IDX2 ON MIG_CA003_5_INS
    (LMT_ID ASC, COVERAGE_TYPE_CODE_VALUE ASC, IS_VALID DESC) ALLOW REVERSE SCANS;   

CREATE INDEX MIG_CA003_5_IDX3 ON MIG_CA003_5_INS
	(IS_VALID DESC, CMS_ACT_FAC_MASTER_ID)
	ALLOW REVERSE SCANS;
	    
CREATE TABLE MIG_CA003_6_MUL (
    CMS_ACT_FAC_MASTER_ID   BIGINT,
    CMS_STG_FAC_MASTER_ID   BIGINT,
    CMS_REF_ID   	    BIGINT,
    IS_VALID    	        CHAR(1)     DEFAULT 'Y',    
    LMT_ID                  VARCHAR(43),
    LLP_BCA_REF_NUM         VARCHAR(19),
    LMT_FAC_CODE            VARCHAR(19),
    LMT_FAC_SEQ             BIGINT,
    TIER_SEQ_NO      	    SMALLINT,
    TIER_TERM        	    SMALLINT,
    TIER_TERM_CODE   	    CHARACTER(1),
    RATE             	    DECIMAL(11,7),
    RECORD_TYPE 	        VARCHAR(1)    
)in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX MIG_CA003_6_IDX1 ON MIG_CA003_6_MUL
    (LMT_ID ASC, IS_VALID DESC) ALLOW REVERSE SCANS;   

CREATE INDEX MIG_CA003_6_IDX2 ON MIG_CA003_6_MUL
    (LMT_ID ASC, TIER_SEQ_NO ASC, IS_VALID DESC) ALLOW REVERSE SCANS;   
    
CREATE INDEX MIG_CA003_6_IDX3 ON MIG_CA003_6_MUL
	(IS_VALID DESC, CMS_ACT_FAC_MASTER_ID, CMS_REF_ID)
	ALLOW REVERSE SCANS;
	
CREATE TABLE MIG_CA003_7_ISL (
    CMS_ACT_FAC_MASTER_ID   	    BIGINT,
    CMS_STG_FAC_MASTER_ID  	    	BIGINT,
    IS_VALID    	    CHAR(1)     DEFAULT 'Y',    
    LMT_ID                          VARCHAR(43),
    LLP_BCA_REF_NUM                 VARCHAR(19),
    LMT_FAC_CODE                    VARCHAR(19),
    LMT_FAC_SEQ                     BIGINT,
    GPP_TERM                        SMALLINT,
    GPP_TERM_CODE                   VARCHAR(1),
    GPP_PAYMENT_MODE_VALUE        	VARCHAR(10),
    SELLING_PRICE                 	DECIMAL(20,2),
    TOTAL_GPP_AMT                 	DECIMAL(20,2),
    SPTF_GRACE_EXP_DATE             TIMESTAMP,
    SECURITY_DEP_OF_MTH           	SMALLINT,
    SECURITY_DEP_PERCENTAGE       	DECIMAL(11,9),
    SECURITY_DEP_AMT              	DECIMAL(20,2),
    CUSTOMER_INTEREST_RATE        	DECIMAL(11,7),
    GPP_CALCULATION_MEHTOD_VALUE  	VARCHAR(10),
    FULREL_PROFIC_CALC_METHOD     	VARCHAR(1),
    FIXED_AMT_REFUND                DECIMAL(15,2),
    COMPOUNDING_METHOD            	CHARACTER(1),
    DATE_STOP_COMPOUNDING         	TIMESTAMP,
    REFUND_GPP_PROFIT_VALUE       	VARCHAR(10),
    REFUND_FULREL_PROFIT_VALUE    	VARCHAR(10),
    COMMISSION_RATE               	DECIMAL(11,9),
    FIXED_COM_AMOUNT              	DECIMAL(20,2),
    COMMISSION_TERM               	SMALLINT,
    COMMISSION_EXPIRY_DATE        	TIMESTAMP,
    EXC_CMP_IN_PMT_AMT            	CHARACTER(1),
    SPTF_DUAL_REPAYMENT_MODE_VALUE	VARCHAR(10),
    SNP_AGREEMENT_DATE            	TIMESTAMP,
    GPP_DURATION_FOR_SNP          	VARCHAR(1),
    SNP_TERM                      	SMALLINT,
    SNP_TERM_CODE_VALUE           	VARCHAR(10),
    FULL_REL_PFT_12_METHOD        	CHARACTER(1),    
    GPP_PAYMENT_MODE_NUM          	VARCHAR(40) DEFAULT 'GPP_PAYMENT_MODE',
    GPP_CALCULATION_METHOD_NUM    	VARCHAR(40) DEFAULT 'GPP_CALCULATION_METHOD',
    REFUND_GPP_PROFIT_NUM         	VARCHAR(40) DEFAULT 'REFUND_GPP_PROFIT',
    REFUND_FULREL_PROFIT_NUM      	VARCHAR(40) DEFAULT 'REFUND_FULREL_PROFIT',
    SPTF_DUAL_REPAYMENT_MODE_NUM  	VARCHAR(40) DEFAULT 'SPTF_DUAL_PAYMENT_MODE',
    RECORD_TYPE 	                VARCHAR(1)    
)in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX MIG_CA003_7_IDX1 ON MIG_CA003_7_ISL
    (LMT_ID ASC, IS_VALID DESC) ALLOW REVERSE SCANS;   

CREATE INDEX MIG_CA003_7_IDX2 ON MIG_CA003_7_ISL
	(IS_VALID DESC, CMS_ACT_FAC_MASTER_ID)
	ALLOW REVERSE SCANS;
	
CREATE TABLE MIG_CA003_8_BBA (
    CMS_ACT_FAC_MASTER_ID   	    BIGINT,
    CMS_STG_FAC_MASTER_ID  	    	BIGINT,
    IS_VALID    	    CHAR(1)     DEFAULT 'Y',    
    LMT_ID                          VARCHAR(43),
    LLP_BCA_REF_NUM                 VARCHAR(19),
    LMT_FAC_CODE                    VARCHAR(19),
    LMT_FAC_SEQ                     BIGINT,
    CUST_PROF_RATE                  DECIMAL(11,9),
    REBATE_METHOD                   VARCHAR(1),
    GPP_PAYMENT_MODE                VARCHAR(1),
    GPP_CAL_METHOD                  VARCHAR(1),
    GPP_TERM                        SMALLINT,
    GPP_TERM_CODE                   VARCHAR(1),
    FULL_RELEASE_PROFIT             VARCHAR(1),
    REFUND_FULL_RELEASE_PROFIT      VARCHAR(1),
    FUL_REL_PROFIT_CAL_METHOD       VARCHAR(1),
    INSTALLMENT                     DECIMAL(20,2),
    FINAL_PAYMENT_AMT               DECIMAL(20,2),
    TOTAL_GPP_AMT                   DECIMAL(20,2),
    SELLING_PRICE                   DECIMAL(20,2),
    TOTAL_PROFIT                    DECIMAL(20,2),
    LAST_MAINTAIN_DATE              TIMESTAMP,
    REBATE_METHOD_CAT               VARCHAR(40) DEFAULT 'REBATE_METHOD',
    GPP_PAYMENT_MODE_CAT            VARCHAR(40) DEFAULT 'GPP_PAYMENT_MODE',
    GPP_CAL_METHOD_CAT              VARCHAR(40) DEFAULT 'GPP_CALCULATION_METHOD',
    GPP_TERM_CODE_CAT               VARCHAR(40) DEFAULT 'PRIME_REVIEW_TERM_CODE',
    REFUND_FULL_RELEASE_PROFIT_CAT  VARCHAR(40) DEFAULT 'REFUND_FULREL_PROFIT',
    FUL_REL_PROFIT_CAL_METHOD_CAT   VARCHAR(40) DEFAULT 'FULREL_PROFIT_CALC_METHOD',
    RECORD_TYPE 	                VARCHAR(1)    
)in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX MIG_CA003_8_IDX1 ON MIG_CA003_8_BBA
    (LMT_ID ASC, IS_VALID DESC) ALLOW REVERSE SCANS;   

CREATE INDEX MIG_CA003_8_IDX2 ON MIG_CA003_8_BBA
	(IS_VALID DESC, CMS_ACT_FAC_MASTER_ID)
	ALLOW REVERSE SCANS;
	    
CREATE TABLE MIG_CA004(
    IS_VALID    	     CHAR(1)     DEFAULT 'Y',
    CMS_ACT_LIMIT_ID	BIGINT,
    CMS_STG_LIMIT_ID	BIGINT,
    CMS_ACT_ACCT_ID		BIGINT,
    CMS_STG_ACCT_ID		BIGINT,
    LIMIT_ID 		     VARCHAR(43),    
    EXTERNAL_SYSTEM_ACCT_NO  VARCHAR(19),
    ACCT_SEQ 		     BIGINT,        
    AA_NUMBER 		     VARCHAR(19),
    FACILITY_CODE 	     VARCHAR(3),
    FACILITY_SEQ 	     BIGINT,
    ACCT_TYPE 		     VARCHAR(1),
    LOC_COUNTRY 	     VARCHAR(2),
    LOC_ORG_CODE 	     VARCHAR(5),
    LOC_ORG_CAT 	     VARCHAR(20) DEFAULT '40', 
    RECORD_TYPE 	     VARCHAR(1)    
)in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX MIG_CA004_IDX1 ON MIG_CA004
(IS_VALID ASC, AA_NUMBER ASC, LIMIT_ID ASC, FACILITY_CODE ASC, FACILITY_SEQ ASC) ALLOW REVERSE SCANS;   

CREATE INDEX MIG_CA004_IDX2 ON MIG_CA004
    (IS_VALID DESC, EXTERNAL_SYSTEM_ACCT_NO ASC, ACCT_SEQ ASC ) ALLOW REVERSE SCANS;   
    
CREATE INDEX MIG_CA004_IDX3 ON MIG_CA004
	(IS_VALID, LIMIT_ID)
	ALLOW REVERSE SCANS;
	
CREATE INDEX MIG_CA004_IDX4 ON MIG_CA004
	(IS_VALID, CMS_ACT_LIMIT_ID, CMS_ACT_ACCT_ID)
	ALLOW REVERSE SCANS;
	
CREATE INDEX MIG_CA004_IDX5 ON MIG_CA004
	(IS_VALID, CMS_STG_LIMIT_ID, CMS_STG_ACCT_ID)
	ALLOW REVERSE SCANS;
			
create index mig_ca004_idx6 on mig_ca004
	(is_valid desc, cms_act_acct_id)
	allow reverse scans;
	
create index mig_ca004_idx7 on mig_ca004
	(is_valid desc, cms_stg_acct_id)
	allow reverse scans;
		
-- Added by KLYong	
-- CREATE INDEX MIG_CA004_IDX3 ON MIG_CA004
-- 	("LIMIT_ID" ASC, "IS_VALID" ASC, "ACCT_TYPE" ASC, "LOC_ORG_CODE" ASC, "LOC_COUNTRY" ASC, "AA_NUMBER" ASC, "ACCT_SEQ" ASC, "EXTERNAL_SYSTEM_ACCT_NO" ASC) 
-- 	ALLOW REVERSE SCANS; 	
    
/* ----------------------------------------------- Start of Collateral ---------------------------------------- */
CREATE TABLE MIG_CO001_AB(
    CMS_ACT_COL_ID              BIGINT,
    CMS_STG_COL_ID              BIGINT,
	IS_VALID                    CHAR(1) DEFAULT 'Y',	
	SECURITY_ID                 VARCHAR(19),        --cms_security
	CMS_SECURITY_SUBTYPE_ID     VARCHAR(10),        --cms_security
	SECURITY_REF_NOTE           VARCHAR(40),        --cms_security
	SOURCE_SECURITY_TYPE        VARCHAR(5),         --cms_security
	SOURCE_SECURITY_SUB_TYPE    VARCHAR(3),         --cms_security
	CURRENCY                    VARCHAR(3),         --cms_security
	LOC_COUNTRY                 VARCHAR(2),         --cms_security
	LOC_ORG_CAT                 VARCHAR(10) DEFAULT '40',
	LOC_ORG_CODE                VARCHAR(5),         --cms_security
	CUSTODIAN_TYPE              VARCHAR(1),         --cms_security
	LEGAL_ENFORCEABILITY        VARCHAR(1),         --cms_security
	LEGAL_ENFORCEABILITY_DATE   TIMESTAMP,          --cms_security
	SECURITY_PERFECTION_DATE    TIMESTAMP,          --cms_security
	ASSET_DESC                  VARCHAR(140),       --cms_asset
	ASSET_TYPE_CAT              VARCHAR(40),        -- category for ASSET_TYPE_CODE - to be determine at run time        
	ASSET_TYPE_CODE             VARCHAR(40),        --cms_asset
	PURCHASE_PRICE              DECIMAL(17,2),      --cms_asset
	PURCHASE_PRICE_CURRENCY     VARCHAR(3),         --cms_asset
	PURCHASE_DATE               TIMESTAMP,          --cms_asset
	REG_DATE                    TIMESTAMP,          --cms_asset
	MANUFACTURE_YEAR            BIGINT,             --cms_asset
	MODEL_NO                    VARCHAR(60),        --cms_asset
	-- RESIDUAL_ASSET_LIFE         BIGINT,             --cms_asset
	SALES_PROCEED               DECIMAL(15,2),      --cms_asset
	REG_NO                      VARCHAR(25),        --cms_asset
	REG_FEE                     DECIMAL(15,2),      --cms_asset
	BRAND                       VARCHAR(60),        --cms_asset
	GOOD_STAT                   VARCHAR(1),         --cms_asset
	REG_CARD_NUMBER             VARCHAR(11),        --cms_asset
	CHASSIS_NUMBER              VARCHAR(25),        --CMS_ASSET_VEHICLE
	REPOSESSION_DATE            TIMESTAMP,          --cms_asset
	REPOSESSION_AGE             BIGINT,             --cms_asset
	ENGINE_NUMBER               VARCHAR(25),        --CMS_ASSET_VEHICLE
	HORSE_POWER                 VARCHAR(20),        --CMS_ASSET_VEHICLE
	DOWN_PAYMENT_TRADE_IN       DECIMAL(15,2),      --CMS_ASSET_VEHICLE, CMS_ASSET_PLANT_EQUIP          
	DOWN_PAYMENT_CASH           DECIMAL(15,2),      --CMS_ASSET_VEHICLE, CMS_ASSET_PLANT_EQUIP
	FREIGHT_CHARGES             DECIMAL(15,2),      --CMS_ASSET_VEHICLE
	PRICE_LIST                  DECIMAL(15,2),      --CMS_ASSET_VEHICLE
	PUBLIC_TRANSPORT            VARCHAR(1),         --cms_asset
    SECURITY_MATURITY_DATE      TIMESTAMP,          --cms_security
    SECURITY_CUSTODIAN          VARCHAR(100),       --cms_security
    PHY_INSPECTION_DONE         VARCHAR(1),         --cms_asset
    ENV_RISKY_STATUS            VARCHAR(2),         --cms_asset
    ENV_RISKY_DATE              TIMESTAMP,          --cms_asset
    BORROWER_DEPENDENCY         VARCHAR(1),         --cms_security
    SERIAL_NO                   VARCHAR(50),        --CMS_ASSET_PLANT_EQUIP
    --INVOICE_NO                  VARCHAR(50),        --CMS_ASSET_PLANT_EQUIP
    SCRAP_VALUE                 DECIMAL(20,2),      --cms_asset
    EXCHANGE_CONTROL_OBTAINED   VARCHAR(2),         --cms_security
    -- EXCHANGE_CONTROL_DATE       TIMESTAMP,          --cms_security
    IS_CGC_PLEDGED              VARCHAR(1),         --cms_security
    --ENV_RISKY_REMARK            VARCHAR(250),       --cms_asset
    CHATTEL_SOLD_DATE           TIMESTAMP,          --cms_asset
    RL_SERIAL_NO                VARCHAR(50),        --cms_asset
    COLLATERAL_STATUS           VARCHAR(1),         --cms_security
    -- PBT_PBR_INDICATOR           VARCHAR(40),        --CMS_ASSET_VEHICLE
    -- DEALER_NAME                 VARCHAR(40),        --CMS_ASSET_VEHICLE
    -- TRANSMISSION_TYPE           VARCHAR(1),         --CMS_ASSET_VEHICLE
    -- ENERGY_SOURCE               VARCHAR(1),         --CMS_ASSET_VEHICLE
    VEHICLE_COLOR               VARCHAR(15),        --CMS_ASSET_VEHICLE
    ROAD_TAX_AMT_TYPE           VARCHAR(15),        --CMS_ASSET_VEHICLE
    -- ROAD_TAX_AMT                DECIMAL(15,2),      --CMS_ASSET_VEHICLE
    ROAD_TAX_EXPIRY_DATE        TIMESTAMP,          --CMS_ASSET_VEHICLE
    E_HAK_MILIK_NUMBER          VARCHAR(50),        --CMS_ASSET_VEHICLE
	CMS_SECURITY_TYPE_ID        VARCHAR(5),         --cms_security
    SOURCE_SEC_CAT              VARCHAR(40) DEFAULT 'SOURCE_CMS_SEC_TYPE_MAP',
    YARD_CAT                    VARCHAR(40) DEFAULT 'YARD',      
    --PBT_PBR_CAT                 VARCHAR(40) DEFAULT 'PBR_PBT_IND',      
    --TRANSMISSION_CAT            VARCHAR(40) DEFAULT 'TRANSMISSION_TYPE',          
    --ENERGY_CAT                  VARCHAR(40) DEFAULT 'ENERGY_SOURCE',          
    GOODS_STATUS_CAT            VARCHAR(40) DEFAULT 'GOODS_STATUS',          
    MODEL_CAT                   VARCHAR(40) DEFAULT 'MODEL',          
    BRAND_CAT                   VARCHAR(40) DEFAULT 'VEHICLE_BRAND',          
    COLLATERAL_STATUS_CAT       VARCHAR(40) DEFAULT 'COL_STATUS',
	RECORD_TYPE                 VARCHAR(1)    
)in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX idx_ab1 ON MIG_CO001_AB
	(security_id ASC, is_valid ASC) ALLOW REVERSE SCANS;

CREATE INDEX idx_ab2 ON MIG_CO001_AB
	(cms_act_col_id);

CREATE INDEX idx_ab3 ON MIG_CO001_AB
	(cms_stg_col_id);
	
-- Added by KLYong	
CREATE INDEX idx_ab4 ON MIG_CO001_AB
	("SOURCE_SECURITY_SUB_TYPE" ASC, "SOURCE_SEC_CAT" DESC) 
	ALLOW REVERSE SCANS; 
	
CREATE INDEX IDX_AB5 ON MIG_CO001_AB
	(CMS_SECURITY_SUBTYPE_ID, IS_VALID DESC)
	ALLOW REVERSE SCANS;
    
CREATE TABLE MIG_CO002_AB_GOLD(
    CMS_ACT_COL_ID            BIGINT,
    CMS_STG_COL_ID            BIGINT,
	IS_VALID 		  CHAR(1) DEFAULT 'Y',	
	SECURITY_ID 		        VARCHAR(20),
	CMS_SECURITY_SUBTYPE_ID   VARCHAR(10),	
	SECURITY_REF_NOTE 	        VARCHAR(40),
	SOURCE_SECURITY_TYPE 	  VARCHAR(40),
	SOURCE_SECURITY_SUB_TYPE  VARCHAR(60),
	CMS_SECURITY_TYPE_ID 	  VARCHAR(5),		-- Internal use	
	CURRENCY 		  VARCHAR(3),
	LOC_COUNTRY 		  VARCHAR(2),
	LOC_ORG_CODE 		  VARCHAR(20),
	CUSTODIAN_TYPE 		  VARCHAR(1),
	LEGAL_ENFORCEABILITY 	  VARCHAR(1),
	LEGAL_ENFORCEABILITY_DATE TIMESTAMP,
	SECURITY_PERFECTION_DATE  TIMESTAMP,
	ASSET_DESC 		  VARCHAR(40),
	ASSET_TYPE_CODE 	  VARCHAR(3),
	PURCHASE_PRICE 		  DECIMAL(19,2),
	PURCHASE_PRICE_CURRENCY   VARCHAR(3),
	SALES_PROCEED 		  DECIMAL(19,2),
	GOLD_GRADE 		  VARCHAR(3),
	PURCHASE_RECEIPT_NO 	  VARCHAR(20),
	GOLD_UNIT_PRICE 	  DECIMAL(19,5),
	GOLD_UNIT_PRICE_UOM 	  VARCHAR(1),
	GOLD_WEIGHT 		  DECIMAL(11,2),
	GOLD_WEIGHT_UOM 	  VARCHAR(1),
	AUCTION_DATE 		  TIMESTAMP,
	AUCTION_PRICE 		  DECIMAL(15,2),
	AUCTIONEER 		  VARCHAR(20),
	SECURITY_MATURITY_DATE 	  TIMESTAMP,
	SECURITY_CUSTODIAN 	  VARCHAR(100),
	CERT_EXPIRY_DATE 	  TIMESTAMP,
	ENV_RISKY_STATUS 	  VARCHAR(2),
	EXCHANGE_CONTROL_OBTAINED VARCHAR(1),
	PHY_INSPECTION_DONE 	  VARCHAR(1),
	BORROWER_DEPENDENCY 	  VARCHAR(1),
	IS_CGC_PLEDGED 		  VARCHAR(1),
	COLLATERAL_STATUS 	  VARCHAR(1),
	LOG_ORG_CAT 		    VARCHAR(10) DEFAULT '40',
   	SOURCE_SEC_CAT          VARCHAR(40) DEFAULT 'SOURCE_CMS_SEC_TYPE_MAP',
	ASSET_TYPE_CAT 		    VARCHAR(10) DEFAULT 'GOLD_TYPE',
	GOLD_UOM_CAT 		    VARCHAR(10) DEFAULT 'GOLD_UOM',
    COL_STATUS_CAT          VARCHAR(40) DEFAULT 'COL_STATUS', 
	RECORD_TYPE 		        VARCHAR(1)             
)in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX IDX_AB_GOLD1 ON MIG_CO002_AB_GOLD
	(SECURITY_ID ASC, IS_VALID ASC) ALLOW REVERSE SCANS;

CREATE INDEX IDX_AB_GOLD2 ON MIG_CO002_AB_GOLD 
	(CMS_ACT_COL_ID);

CREATE INDEX IDX_AB_GOLD3 ON MIG_CO002_AB_GOLD 
	(CMS_STG_COL_ID);

-- Added by KLYong	
CREATE INDEX IDX_AB_GOLD4 ON MIG_CO002_AB_GOLD
	("SOURCE_SECURITY_SUB_TYPE" ASC, "SOURCE_SEC_CAT" DESC) 
	ALLOW REVERSE SCANS; 
	
    
CREATE TABLE MIG_CO005_CS(
    CMS_ACT_COL_ID              BIGINT,
    CMS_STG_COL_ID              BIGINT, 
	IS_VALID                    CHAR(1) DEFAULT 'Y',	
	SECURITY_ID                 VARCHAR(19),
	CMS_SECURITY_SUBTYPE_ID     VARCHAR(10),
	SECURITY_REF_NOTE 	    VARCHAR(40),
	SOURCE_SECURITY_TYPE        VARCHAR(5),
	SOURCE_SECURITY_SUB_TYPE    VARCHAR(3),
	CURRENCY                    VARCHAR(3),
	LOC_COUNTRY                 VARCHAR(2),
	LOC_ORG_CODE                VARCHAR(5),
	CUSTODIAN_TYPE              VARCHAR(1),
	CUSTODIAN                   VARCHAR(40),
	LEGAL_ENFORCEBILITY         VARCHAR(1),
	LEGAL_ENFORCEBILITY_DATE    TIMESTAMP,
	SECURITY_PERFECTION_DATE    TIMESTAMP,
	INTEREST_CAPITAL            VARCHAR(1),
    IS_OWN_BANK                 VARCHAR(1),
	GROUP_ACCOUNT_NO            VARCHAR(19),
	REF_NO                      VARCHAR(19),
	AMT_CURRENCY                VARCHAR(3),
	DEPOSIT_AMT                 DECIMAL(15,2),
    DEPOSIT_MATURITY_DATE       TIMESTAMP,
    TENURE                      DECIMAL(3,0),
    TENURE_UNIT                 VARCHAR(1),
    EXCHANGE_CONTROL_OBTAINED   VARCHAR(2),
    CHARGE_NATURE               VARCHAR(20),
    CHARGE_AMOUNT               DECIMAL(20,2),
    LEGAL_CHARGE_DATE           TIMESTAMP,
    CHARGE_TYPE                 VARCHAR(1),
    BORROWER_DEPENDENCY         VARCHAR(1),
    IS_CGC_PLEDGED              VARCHAR(1),
    DESCRIPTION                 VARCHAR(250),
    ISSUER                      VARCHAR(100),
	COLLATERAL_STATUS           VARCHAR(1),
    HOLD_STATUS                 VARCHAR(1), 
	CMS_SECURITY_TYPE_ID        VARCHAR(5),
	LOC_ORG_CAT                 VARCHAR(10) DEFAULT '40',
    SOURCE_SEC_CAT              VARCHAR(40) DEFAULT 'SOURCE_CMS_SEC_TYPE_MAP',
    CHARGE_TYPE_CAT             VARCHAR(40) DEFAULT 'CHARGE_TYPE',
    CHARGE_NATURE_CAT           VARCHAR(40) DEFAULT 'NAT_OF_CHARGE_CASH',
    TENURE_CAT                  VARCHAR(40) DEFAULT '28',
    COLLATERAL_STATUS_CAT       VARCHAR(40) DEFAULT 'COL_STATUS',
	RECORD_TYPE                 VARCHAR(1)    
)in CMS_MIG index in CMS_MIG_INDEX;    
    
CREATE INDEX IDX_CASH1 ON MIG_CO005_CS
	(SECURITY_ID ASC, IS_VALID ASC) ALLOW REVERSE SCANS;
	
-- Added by KLYong	
CREATE INDEX IDX_CASH2 ON MIG_CO005_CS
	("CMS_SECURITY_SUBTYPE_ID" ASC) 
	ALLOW REVERSE SCANS; 

CREATE INDEX IDX_CASH3 ON MIG_CO005_CS
	("CMS_SECURITY_TYPE_ID" ASC) 
	ALLOW REVERSE SCANS; 	
	
CREATE INDEX IDX_CASH4 ON MIG_CO005_CS
	("IS_VALID" ASC, "SECURITY_ID" DESC) 
	ALLOW REVERSE SCANS; 	
    
    
CREATE TABLE MIG_CO008_MS(
    CMS_ACT_COL_ID              BIGINT,
    CMS_STG_COL_ID              BIGINT, 
	IS_VALID                    CHAR(1) DEFAULT 'Y',	
	SECURITY_ID                 VARCHAR(19),
	SECURITY_REF_NOTE           VARCHAR(40),
	SOURCE_SECURITY_TYPE        VARCHAR(5),
	SOURCE_SECURITY_SUB_TYPE    VARCHAR(3),
	CURRENCY                    VARCHAR(3),
	LOC_COUNTRY                 VARCHAR(2),
	LOC_ORG_CODE                VARCHAR(5),
	TYPE                        VARCHAR(1),
	CERTIFICATE_NUMBER          VARCHAR(30),
	NUMBER_OF_UNITS             BIGINT,
	STOCK_EXCHANGE_BOND_MARKET  VARCHAR(40),
	STOCK_CODE_BOND_CODE        VARCHAR(30),
	RECOGNIZED_EXCHANGE         VARCHAR(1),
    IS_LEGAL_ENFORCE            VARCHAR(1),
	IS_LEGAL_ENFORCE_DATE       TIMESTAMP,
	SECURITY_PERFECTION_DATE    TIMESTAMP,
    BORROWER_DEPENDENCY         VARCHAR(1),
    IS_CGC_PLEDGED              VARCHAR(1),
    -- AGENT_NAME                  VARCHAR(120),
    -- AGENT_CONFIRM_DATE          TIMESTAMP,
    -- REGISTERED_NAME             VARCHAR(120),
    -- CLIENT_CODE                 VARCHAR(30), 
    CDS_NUMBER                  VARCHAR(20),
    -- UNIT_PRICE                  DECIMAL(21,6),
    -- NOMINAL_VALUE               DECIMAL(20,2),
    SECURITY_REFERRED           VARCHAR(1),
    CUSTODIAN_TYPE              VARCHAR(1),
    SECURITY_CUSTODIAN          VARCHAR(100),
    SECURITY_MATURITY_DATE      TIMESTAMP,
    ISSUER_NAME                 VARCHAR(50),
    -- ISSUER_ID_TYPE              VARCHAR(30),
    STOCK_EXCHANGE_COUNTRY      VARCHAR(50),
    LOCAL_EXCHANGE              VARCHAR(10),
    -- INDEX_NAME                  VARCHAR(100),
    BASEL_COMPLIANT_TEXT        VARCHAR(50),
    EXCHANGE_CONTROL_OBTAINED   VARCHAR(1),
    -- EXCHANGE_CONTROL_DATE       TIMESTAMP,
    CHARGE_NATURE               VARCHAR(20),
    CHARGE_AMOUNT               DECIMAL(20,2),
    LEGAL_CHARGE_DATE           TIMESTAMP,
    CHARGE_TYPE                 VARCHAR(1),
	UNIT_PRICE					DECIMAL(15,0),
	UNIT_PRICE_CURRENCY			VARCHAR(3),
    CAPPED_PRICE                DECIMAL(20,2),
    -- EXERCISE_PRICE              DECIMAL(20,4),
    -- BROKER_NAME                 VARCHAR(120),
    -- RISK_MITIGATION_CATEGORY    VARCHAR(40),
    -- GOVT_GUARANTEE              VARCHAR(1),
    -- NAME_OF_GOVT                VARCHAR(100),
    COLLATERAL_STATUS           VARCHAR(1),
	SOURCE_ID					VARCHAR(4),
	CMS_SECURITY_TYPE_ID        VARCHAR(5),
	CMS_SECURITY_SUBTYPE_ID     VARCHAR(10),	
	LOC_ORG_CAT                 VARCHAR(10) DEFAULT '40',
    SOURCE_SEC_CAT              VARCHAR(40) DEFAULT 'SOURCE_CMS_SEC_TYPE_MAP',
    CHARGE_TYPE_CAT             VARCHAR(40) DEFAULT 'CHARGE_TYPE',
    CHARGE_NATURE_CAT           VARCHAR(40) DEFAULT 'NAT_OF_CHARGE_MARKSEC',
    COLLATERAL_STATUS_CAT       VARCHAR(40) DEFAULT 'COL_STATUS',
	RECORD_TYPE                 VARCHAR(1)             
)in CMS_MIG index in CMS_MIG_INDEX;
    
CREATE INDEX IDX_MS1 ON MIG_CO008_MS
	(SECURITY_ID ASC, IS_VALID ASC) ALLOW REVERSE SCANS;
	
-- Added by KLYong
CREATE INDEX IDX_MS2 ON MIG_CO008_MS
	("SECURITY_ID" ASC, "STOCK_EXCHANGE_BOND_MARKET" ASC, "STOCK_CODE_BOND_CODE" ASC, "TYPE" ASC, "SOURCE_SECURITY_SUB_TYPE" ASC) 
	ALLOW REVERSE SCANS; 

CREATE INDEX IDX_MS3 ON MIG_CO008_MS
	("IS_VALID" ASC, "CMS_SECURITY_TYPE_ID" ASC, "CMS_SECURITY_SUBTYPE_ID" ASC, "SECURITY_ID" ASC) 
	ALLOW REVERSE SCANS;	
    
    
CREATE TABLE MIG_CO009_PT(
    CMS_ACT_COL_ID                  BIGINT,
    CMS_STG_COL_ID                  BIGINT, 
    IS_VALID                        CHAR(1) DEFAULT 'Y',    
    SECURITY_ID                     VARCHAR(19),
    CMS_SECURITY_SUBTYPE_ID         VARCHAR(10),
    SECURITY_REF_NOTE 	    	    VARCHAR(40),
    SOURCE_SECURITY_TYPE            VARCHAR(5),
    SOURCE_SECURITY_SUB_TYPE        VARCHAR(3),
    CURRENCY                        VARCHAR(3),
    LOC_COUNTRY                     VARCHAR(2),
    LOC_ORG_CODE                    VARCHAR(5),
    CUSTODIAN_TYPE                  VARCHAR(1),
    CUSTODIAN                       VARCHAR(100),
    SECURITY_EXPIRY_DATE            TIMESTAMP,
    LEGAL_ENFORCEABILITY            VARCHAR(1),
    LEGAL_ENFORCEABILITY_DATE       TIMESTAMP,
    SECURITY_PERFECTION_DATE        TIMESTAMP,
    SALE_PURCHASE_AGREEMENT_VALUE   DECIMAL(15,2),
    SALE_PURCHASE_DATE              TIMESTAMP,
    TITLE_TYPE                      VARCHAR(1),
    MASTER_TITLE                    VARCHAR(1),
    MASTER_TITLE_NUMBER             VARCHAR(20),
    TITLE_NUMBER_PREFIX             VARCHAR(40),
    TITLE_NUMBER                    VARCHAR(20),
    LOT_NO                          VARCHAR(10),
    --LOT_NO_TYPE                     VARCHAR(2),
    POST_CODE                       VARCHAR(6),
    STATE_CODE                      VARCHAR(40),
    LAND_AREA                       DECIMAL(28,8),
    LAND_AREA_UOM                   VARCHAR(20),
    BUILT_UP_AREA                   DECIMAL(19,6),
    BUILD_AREA_UOM                  VARCHAR(20),
    TENURE                          BIGINT,
    TENURE_UNIT                     VARCHAR(1),
    QUIT_RENT_RECEIPT               VARCHAR(1),
    QUIT_RENT_AMT_PAID              DECIMAL(15,2),
    QUIT_RENT_PAYMENT_DATE          TIMESTAMP,
    PROPERTY_USAGE                  VARCHAR(3),
    --BUILDING_VALUE                  VARCHAR(40), 
    ABANDONED_PROJECT               VARCHAR(1),
    PROPERTY_COMPLETION_STATUS      VARCHAR(1),
    PROPERTY_TYPE_CODE              VARCHAR(3),
    AUCTIONEER                      VARCHAR(20),
    AUCTION_PRICE                   DECIMAL(15,2),
    AUCTION_DATE                    TIMESTAMP, 
    CHATTEL_SOLD_DATE               TIMESTAMP,
    PRI_CAVEAT_GUARANTEE_DATE       TIMESTAMP,
    AMOUNT_REDEEM                   DECIMAL(15,2),
    UNIT_PRICE                      DECIMAL(15,2),
    PROPERTY_ADDRESS                VARCHAR(150),
    PROPERTY_ADDRESS_2              VARCHAR(50),
    PROPERTY_ADDRESS_3              VARCHAR(50),
    ASSESSMENT_RATE                 DECIMAL(15,2),
    ASSESSMENT_PAYMENT_DATE         TIMESTAMP,
    ASSESSMENT                      VARCHAR(1),
    EXCHANGE_CONTROL_OBTAINED       VARCHAR(2),         --cms_security
    BORROWER_DEPENDENCY             VARCHAR(1),
    IS_CGC_PLEDGED                  VARCHAR(1),         --cms_security
    IS_PHY_INSPECT                  VARCHAR(1),         
    ENV_RISKY_STATUS                VARCHAR(1),         
    INDEPENDENT_VALUER_FLAG         VARCHAR(1),
    COLLATERAL_STATUS               VARCHAR(1),    
    -- DEVELOPER_NAME_CODE             VARCHAR(10),
    -- PROJECT_NAME_CODE               VARCHAR(11),
    -- INSURANCE                       VARCHAR(1),
    -- DISTRICT_CODE                   VARCHAR(10),
    -- MUKIM_CODE                      VARCHAR(10),
    LOC_ORG_CAT                     VARCHAR(20) DEFAULT '40',
    --LAND_USE_CAT                    VARCHAR(20) DEFAULT 'LAND_USE_CAT',
    PROPERTY_TYPE_CAT               VARCHAR(20) DEFAULT 'PROPERTY_TYPE',
    LOT_NO_CAT                      VARCHAR(20) DEFAULT 'LOT_NO',
    ASSET_TYPE_CAT                  VARCHAR(20) DEFAULT 'ASSET_TYPE',
    STATE_CAT                       VARCHAR(20) DEFAULT 'STATE',
    -- DISTRICT_CAT                    VARCHAR(20) DEFAULT 'DISTRICT',
    -- MUKIM_CAT                       VARCHAR(20) DEFAULT 'MUKIM',
    AREA_UOM_CAT                    VARCHAR(20) DEFAULT 'AREA_UOM',
    -- DEVELOPER_NAME_CAT              VARCHAR(20) DEFAULT 'DEVELOPER_CODE',
    -- PROJECT_NAME_CAT                VARCHAR(20) DEFAULT '',
    SOURCE_SEC_TYPE_CAT             VARCHAR(20) DEFAULT 'SOURCE_SEC_TYPE', 
    TITLE_TYPE_CAT                  VARCHAR(20) DEFAULT 'TITLE_TYPE',
    TENURE_PROP_CAT                 VARCHAR(20) DEFAULT 'TENURE_PROP', 
    PROPERTY_USAGE_CAT              VARCHAR(20) DEFAULT 'PROPERTY_USAGE', 
    PROPERTY_COMPLETION_CAT         VARCHAR(40) DEFAULT 'PROPERTY_COMPLETION_STATUS', 
    COLLATERAL_STATUS_CAT           VARCHAR(40) DEFAULT 'COL_STATUS',
    RECORD_TYPE                     VARCHAR(1)
)in CMS_MIG index in CMS_MIG_INDEX;
    
CREATE INDEX IDX_PT1 ON MIG_CO009_PT 
	(CMS_ACT_COL_ID);

CREATE INDEX IDX_PT2 ON MIG_CO009_PT 
	(CMS_STG_COL_ID);
	
CREATE INDEX IDX_PT3 ON MIG_CO009_PT
	(SECURITY_ID ASC, IS_VALID ASC) ALLOW REVERSE SCANS;
	
    
CREATE TABLE MIG_CO010_GT(
    CMS_ACT_COL_ID              BIGINT,
    CMS_STG_COL_ID              BIGINT, 
    IS_VALID                    CHAR(1)     DEFAULT 'Y',    
    SECURITY_ID                 VARCHAR(19),
	CMS_SECURITY_SUBTYPE_ID     VARCHAR(10),
    SECURITY_REF_NOTE           VARCHAR(40),
    SOURCE_SECURITY_TYPE        VARCHAR(5),
    SOURCE_SECURITY_SUB_TYPE    VARCHAR(3),
    CURRENCY                    VARCHAR(3),
    LOC_COUNTRY                 VARCHAR(2),
    LOC_ORG_CODE                VARCHAR(5),
    CUSTODIAN_TYPE              VARCHAR(1),
    SECURITY_EXPIRY_DATE        TIMESTAMP,
    LEGAL_ENFORCEABILITY        VARCHAR(1),
    LEGAL_ENFORCEABILITY_DATE   TIMESTAMP,
    SECURITY_PERFECTION_DATE    TIMESTAMP,
    GUARANTEES_DESC             VARCHAR(50),
    REF_NO                      VARCHAR(20),
    GUARANTEE_AMT               DECIMAL(15,2),
    GUARANTEE_DATE              TIMESTAMP,
    --SCI_ORIG_SECURITY_CURRENCY  VARCHAR(3),
    BORROWER_DEPENDENCY         VARCHAR(1),
    --CLAIM_PERIOD                DECIMAL(9,3),
    --CLAIM_DATE                  TIMESTAMP,
    BENEFICIARY_NAME            VARCHAR(100), 
    SECURITY_CUSTODIAN          VARCHAR(100),
	--BANK_COUNTRY_RISK_APPROVAL  VARCHAR(1),
    CHARGE_TYPE                 VARCHAR(1)      DEFAULT 'S',
    ISSUING_BANK                VARCHAR(40),
    ISSUING_BANK_COUNTRY        VARCHAR(2),
    EXCHANGE_CONTROL_OBTAINED   VARCHAR(2),
    --EXCHANGE_CONTROL_DATE       TIMESTAMP,
    -- COMMENT                     VARCHAR(250),
    COLLATERAL_STATUS           VARCHAR(1),
	CMS_SECURITY_TYPE_ID        VARCHAR(5),
    LOC_ORG_CAT                 VARCHAR(20)     DEFAULT '40',
    SOURCE_SEC_CAT              VARCHAR(40)     DEFAULT 'SOURCE_CMS_SEC_TYPE_MAP',
    CHARGE_TYPE_CAT             VARCHAR(40)     DEFAULT 'CHARGE_TYPE',
    COLLATERAL_STATUS_CAT       VARCHAR(40)     DEFAULT 'COL_STATUS',
    RECORD_TYPE                 VARCHAR(1)
) in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX IDX_GT1 ON MIG_CO010_GT 
	(SECURITY_ID ASC, IS_VALID ASC) ALLOW REVERSE SCANS;

CREATE INDEX IDX_GT2 ON MIG_CO010_GT 
	(CMS_ACT_COL_ID);

CREATE INDEX IDX_GT3 ON MIG_CO010_GT 
	(CMS_STG_COL_ID);
	
-- Added by KLYong	
CREATE INDEX IDX_GT4 ON MIG_CO010_GT
	("IS_VALID" ASC, "CMS_ACT_COL_ID" ASC, "SECURITY_ID" ASC) 
	ALLOW REVERSE SCANS; 
	
CREATE INDEX IDX_GT5 ON MIG_CO010_GT
	("IS_VALID" ASC, "CMS_STG_COL_ID" ASC, "SECURITY_ID" ASC) 
	ALLOW REVERSE SCANS; 	
	
    
CREATE TABLE MIG_CO011_OT(
    CMS_ACT_COL_ID              BIGINT,
    CMS_STG_COL_ID              BIGINT, 
    IS_VALID                    CHAR(1)     DEFAULT 'Y',
    CMS_SECURITY_TYPE_ID        VARCHAR(5),    
    SECURITY_ID                 VARCHAR(19), -- CMS_SECURITY
    CMS_SECURITY_SUBTYPE_ID     VARCHAR(10), -- CMS_SECURITY
    SECURITY_REF_NOTE           VARCHAR(40), -- CMS_SECURITY
    SOURCE_SECURITY_TYPE        VARCHAR(5), -- CMS_SECURITY
    SOURCE_SECURITY_SUB_TYPE    VARCHAR(3), -- CMS_SECURITY
    CURRENCY                    VARCHAR(3), -- CMS_SECURITY
    LOC_COUNTRY                 VARCHAR(2), -- CMS_SECURITY
    LOC_ORG_CODE                VARCHAR(5), -- CMS_SECURITY
    CUSTODIAN_TYPE              VARCHAR(1),  -- CMS_SECURITY
    SECURITY_CUSTODIAN		    VARCHAR(100), -- CMS_SECURITY
    IS_PHY_INSPECT		        VARCHAR(1),   -- CMS_OTHER
    ENV_RISKY_STATUS 	  	    VARCHAR(2), -- CMS_OTHER
    BORROWER_DEPENDENCY		    VARCHAR(1), -- CMS_SECURITY
    LEGAL_ENFORCEABILITY        VARCHAR(1), -- CMS_SECURITY
    LEGAL_ENFORCEABILITY_DATE   TIMESTAMP, -- CMS_SECURITY
    SECURITY_MATURITY_DATE 	    TIMESTAMP, -- CMS_SECURITY
    IS_CGC_PLEDGED              VARCHAR(1), -- CMS_SECURITY
    NUMBER_OF_UNITS		        DECIMAL(15,2), -- CMS_OTHER
    DESCRIPTION_OTHERS		    VARCHAR(50), -- CMS_OTHER
    COLLATERAL_STATUS           VARCHAR(1), -- CMS_SECURITY
    LOC_ORG_CAT                 VARCHAR(20)     DEFAULT '40',
    SOURCE_SEC_CAT              VARCHAR(40)     DEFAULT 'SOURCE_CMS_SEC_TYPE_MAP',
    COLLATERAL_STATUS_CAT       VARCHAR(40) DEFAULT 'COL_STATUS',          
    RECORD_TYPE                 VARCHAR(1)    
) in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX IDX_OT1 ON MIG_CO011_OT 
	(SECURITY_ID ASC, IS_VALID ASC) ALLOW REVERSE SCANS;
	
-- Added by KLyong
CREATE INDEX IDX_OT2 ON MIG_CO011_OT
	("SOURCE_SECURITY_SUB_TYPE" ASC, "SOURCE_SEC_CAT" DESC) 
	ALLOW REVERSE SCANS; 
	

CREATE TABLE MIG_CO012_IN(
    CMS_ACT_COL_ID              BIGINT,
    CMS_STG_COL_ID              BIGINT, 
    IS_VALID                    CHAR(1)     DEFAULT 'Y',
    SECURITY_ID                 VARCHAR(19),
    CMS_SECURITY_SUBTYPE_ID     VARCHAR(10),
    SECURITY_REF_NOTE           VARCHAR(40),
    SOURCE_SECURITY_TYPE        VARCHAR(5),
    SOURCE_SECURITY_SUB_TYPE    VARCHAR(3),
    CURRENCY                    VARCHAR(3),
    LOC_COUNTRY                 VARCHAR(2),
    LOC_ORG_CODE                VARCHAR(5),
    CUSTODIAN_TYPE              VARCHAR(1),
    SECURITY_CUSTODIAN          VARCHAR(100),    
    CHARGE_TYPE                 VARCHAR(1),
    CHARGE_NATURE               VARCHAR(20),
    CHARGE_AMOUNT               DECIMAL(20,2),
    LEGAL_CHARGE_DATE           TIMESTAMP,
    IS_LEGAL_ENFORCE            VARCHAR(1),
	IS_LEGAL_ENFORCE_DATE       TIMESTAMP,
    COLLATERAL_STATUS           VARCHAR(1),
    LOC_ORG_CAT                 VARCHAR(20) DEFAULT '40',
    SOURCE_SEC_CAT              VARCHAR(40) DEFAULT 'SOURCE_CMS_SEC_TYPE_MAP',
    CHARGE_TYPE_CAT             VARCHAR(40) DEFAULT 'CHARGE_TYPE',
    CHARGE_NATURE_CAT           VARCHAR(40) DEFAULT 'NAT_OF_CHARGE_INS',
    COLLATERAL_STATUS_CAT       VARCHAR(40) DEFAULT 'COL_STATUS',    
    RECORD_TYPE                 VARCHAR(1)    
) in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX idx_in1 ON MIG_CO012_IN 
	(security_id ASC, is_valid ASC) ALLOW REVERSE SCANS;
	
CREATE INDEX IDX_IN2 ON MIG_CO012_IN
    (CMS_ACT_COL_ID, IS_VALID) AlLOW REVERSE SCANS;
    
CREATE TABLE MIG_CO014_CL(
    CMS_ACT_COL_ID              BIGINT,
    CMS_STG_COL_ID              BIGINT, 
    IS_VALID                    CHAR(1)     DEFAULT 'Y',
    CMS_SECURITY_TYPE_ID        VARCHAR(5),    
    SECURITY_ID                 VARCHAR(19),
    CMS_SECURITY_SUBTYPE_ID     VARCHAR(10),
    SECURITY_REF_NOTE           VARCHAR(40),
    SOURCE_SECURITY_TYPE        VARCHAR(5),     
    SOURCE_SECURITY_SUB_TYPE    VARCHAR(3),
    LOC_COUNTRY                 VARCHAR(2),
    LOC_ORG_CODE                VARCHAR(5),
    IS_LEGAL_ENFORCE            VARCHAR(1),
	IS_LEGAL_ENFORCE_DATE       TIMESTAMP,
    COLLATERAL_STATUS           VARCHAR(1),
	CURRENCY                    VARCHAR(3) DEFAULT 'MYR',
    LOC_ORG_CAT                 VARCHAR(20) DEFAULT '40',
    SOURCE_SEC_CAT              VARCHAR(40) DEFAULT 'SOURCE_CMS_SEC_TYPE_MAP',
    COLLATERAL_STATUS_CAT       VARCHAR(40) DEFAULT 'COL_STATUS',          
    RECORD_TYPE                 VARCHAR(1)    
) in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX IDX_CLEAN1 ON MIG_CO014_CL
    (is_valid ASC, security_id ASC);

-- Added by KLYong
CREATE TABLE MIG_CO015_VL(	
	IS_VALID 				CHAR(1) DEFAULT 'Y',
	SECURITY_ID 				VARCHAR(19),
	VALUER_CAT 				VARCHAR(10) DEFAULT 'VALUER',
	VALUER_CODE 				VARCHAR(5),
	VALUATION_DATE 				TIMESTAMP,
	VALUATION_CURRENCY 			VARCHAR(3),
	CMV 					DECIMAL(15,2),
	FSV 					DECIMAL(15,2),
	-- ASSUMPTION_VALUE 			VARCHAR(1),
	RESERVE_PRICE 				DECIMAL(15,2),
	RESERVE_PRICE_DATE 			TIMESTAMP,
	--APPRAISAL_VALUE 			DECIMAL(15,2),
	--APPRAISAL_VALUE_DATE 			TIMESTAMP,		
	RECORD_TYPE 				VARCHAR(1)
)in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX IDX_VAL1 ON MIG_CO015_VL
	(IS_VALID, SECURITY_ID)
	ALLOW REVERSE SCANS;


CREATE TABLE MIG_CO016_IN(	
	cms_act_col_id 				bigint,
    cms_stg_col_id 				bigint,
    cms_act_insr_id 			bigint,
    cms_stg_insr_id 			bigint,
	IS_VALID 					CHAR(1) DEFAULT 'Y',
	SECURITY_ID 				VARCHAR(20),
	POLICY_SEQ_NO				VARCHAR(3),	
	POLICY_NUMBER 				VARCHAR(20),
	INSURER_NAME_CAT 			VARCHAR(15) DEFAULT 'INSURER_NAME',
	INSURER_NAME_CODE 			VARCHAR(3),
	INSURANCE_TYPE_CAT 			VARCHAR(15) DEFAULT 'INSURANCE_TYPE',
	INSURANCE_TYPE_CODE 			VARCHAR(3),
	INSURANCE_POLICY_CURRENCY 		VARCHAR(3) 	DEFAULT 'MYR',
	INSURED_AMT 				DECIMAL(19,2),
	EFFECTIVE_DATE 				TIMESTAMP,
	EXPIRY_DATE 				TIMESTAMP,
	PROP_NO_COVER_NOTE_NUMBER 		VARCHAR(20),
	GROSS_PREMIUM 				DECIMAL(13,2),
	STAMP_DUTY 					DECIMAL(13,2),
	NET_PREMIUM_PAY_TO_INS_COMP DECIMAL(13,2),
	NET_PREMIUM_PAY_BY_BORROWER DECIMAL(13,2),
	COMMISSION_EARNED 			DECIMAL(13,2),
	BANK_CUST_ARRANGE_INS_CAT 	VARCHAR(15) DEFAULT 'ARR_INSURER',
	BANK_CUST_ARRANGE_INS_IND 	VARCHAR(1),
	NONSCHEMA_SCHEMA			VARCHAR(1),
	INS_PREMIUM					DECIMAL(13,2),
	INS_ISSUE_DATE				TIMESTAMP,
	AUTO_DEBIT					VARCHAR(1),
	TAKAFUL_COMMISSION			DECIMAL(13,2),
	NEW_AMT_INSURED				DECIMAL(15,2),
	ENDORSEMENT_DATE			TIMESTAMP,
	BUILDING_OCCUPATION_CAT		VARCHAR(5) 	DEFAULT 'BO',
	BUILDING_OCCUPATION_CODE	VARCHAR(3),
	NATURE_OF_WORK				VARCHAR(50),
	TYPE_OF_BUILDING			VARCHAR(3),
	NUMBER_OF_STOREY			DECIMAL(9,2),
	WALL						VARCHAR(3),
	EXTENSION_WALL				VARCHAR(3),
	ROOF						VARCHAR(3),
	EXTENSION_ROOF				VARCHAR(3),
	ENDORSEMENT_CODE			VARCHAR(3),
	REMARK1						VARCHAR(60),
	REMARK2						VARCHAR(60),
	REMARK3						VARCHAR(60),
	POLICY_CUSTODIAN_CAT		VARCHAR(15) DEFAULT 'INSURER_TAG',
	POLICY_CUSTODIAN_CODE		VARCHAR(2),
	INSURANCE_CLAIM_DATE		TIMESTAMP,
	INSURANCE_EXCHANGE_RATE		DECIMAL(13,2),
	TYPE_OF_FLOOR				VARCHAR(3),
	TYPE_OF_PERILS1				VARCHAR(3),
	TYPE_OF_PERILS2				VARCHAR(3),
	TYPE_OF_PERILS3				VARCHAR(3),
	TYPE_OF_PERILS4				VARCHAR(3),
	TYPE_OF_PERILS5				VARCHAR(3),
	DEBITING_ACC_NO				VARCHAR(19), --DECIMAL(19,0), -- change to varchar since its easier to strip away to leading 0 instead of casting then strip the 0
	ACC_TYPE_CAT				VARCHAR(10) DEFAULT 'ACCT_TYP',
	ACC_TYPE_CODE				VARCHAR(1),
	RECORD_TYPE 				VARCHAR(1)
)in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX IDX_INSR_SECSEQ1 ON MIG_CO016_IN
	(SECURITY_ID ASC, IS_VALID ASC) ALLOW REVERSE SCANS;

CREATE INDEX IDX_COL1 ON MIG_CO016_IN
	(CMS_ACT_COL_ID ASC) ALLOW REVERSE SCANS;

CREATE INDEX IDX_COL2 ON MIG_CO016_IN
	(CMS_STG_COL_ID ASC) ALLOW REVERSE SCANS;
	
CREATE INDEX IDX_INSR1 ON MIG_CO016_IN
	(CMS_ACT_INSR_ID ASC, IS_VALID ASC);

CREATE INDEX IDX_INSR2 ON MIG_CO016_IN
	(CMS_STG_INSR_ID ASC, IS_VALID ASC);

create index mig_co016_idx1 on mig_co016_in
	(is_valid, CMS_ACT_COL_ID, POLICY_SEQ_NO) allow reverse scans;		

create index mig_co016_idx2 on mig_co016_in
	(is_valid, CMS_STG_COL_ID, POLICY_SEQ_NO) allow reverse scans;		

CREATE TABLE MIG_CO017_CD(
	cms_act_col_id 				bigint,
  	cms_stg_col_id 				bigint,
  	cms_act_lmt_id 				bigint,
  	cms_stg_lmt_id 				bigint,
	cms_act_chrg_id 			bigint,
  	cms_stg_chrg_id 			bigint,
 	cms_act_aa_id 				bigint,
	cms_act_chrg_dtl_id 		bigint,
	cms_stg_chrg_dtl_id 		bigint,  
	IS_VALID 					CHAR(1) DEFAULT 'Y',	
	SECURITY_ID 				VARCHAR(19),
	LIMIT_ID					VARCHAR(42),
	APPLICATION_NO 				VARCHAR(19),
	FACILITY_SEQ 				BIGINT,	
	FACILITY_CODE 				VARCHAR(3),
	currency_code				varchar(3),	
	RANKING_OF_SECURITY 		BIGINT,
	CHARGE_AMT 					DECIMAL(15,2),
	DATE_LEGALLY_CHARGE 		TIMESTAMP,
	PRESENTATION_NO 			VARCHAR(20),
	PRESENTATION_DATE 			TIMESTAMP,
	FOLIO						VARCHAR(10),
	JILID						VARCHAR(10),
	FIRST_THIRD_PARTY_CHARGE	VARCHAR(1),
	CHARGE_TYPE_CAT				VARCHAR(40) DEFAULT 'CHARGE_TYPE',
	CHARGE_TYPE_CODE			VARCHAR(1),
	NATURE_OF_CHARGE			VARCHAR(20),
	-- CHARGEE_OF_PRIOR_CHARGE		VARCHAR(100),
	-- PRIOR_CHARGE_TYPE_CAT		VARCHAR(40) DEFAULT 'PRIOR_CHARGE_TYPE',
	-- PRIOR_CHARGE_TYPE_CODE 		VARCHAR(10),
	-- PRIOR_CHARGE_AMOUNT			DECIMAL(17,2),
	CHARGE_PENDING_REDEMPTION	VARCHAR(1),
	-- CHARGE_REGISTERED_DATE		TIMESTAMP,
	CAVEAT_WAIVED_IND			VARCHAR(1),
	-- CAVEAT_PRESENTATION_NO		VARCHAR(15),
	-- CAVEAT_EXPIRY_DATE			TIMESTAMP,
	-- SOLICITOR_NAME				VARCHAR(100),
	RECORD_TYPE 				VARCHAR(1)	
)in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX IDX_CHRG1 ON MIG_CO017_CD 
	(CMS_ACT_COL_ID ASC, RANKING_OF_SECURITY ASC ) ALLOW REVERSE SCANS;
             
CREATE INDEX IDX_CHRG2 ON MIG_CO017_CD 
	(CMS_STG_COL_ID ASC, RANKING_OF_SECURITY ASC ) ALLOW REVERSE SCANS;

CREATE INDEX IDX_CHRG3 ON MIG_CO017_CD
	(IS_VALID ASC) ALLOW REVERSE SCANS;

CREATE INDEX IDX_CHRG4 ON MIG_CO017_CD 
	(CMS_ACT_CHRG_DTL_ID ASC, IS_VALID ASC) ALLOW REVERSE SCANS;

CREATE INDEX IDX_CHRG5 ON MIG_CO017_CD 
	(CMS_STG_CHRG_DTL_ID ASC, IS_VALID ASC) ALLOW REVERSE SCANS;

CREATE INDEX IDX_LMTSECM1 ON MIG_CO017_CD
	(CMS_ACT_CHRG_ID ASC, IS_VALID ASC) ALLOW REVERSE SCANS;

CREATE INDEX IDX_LMTSECM3 ON MIG_CO017_CD 
	(CMS_STG_CHRG_ID ASC, IS_VALID ASC) ALLOW REVERSE SCANS;	
	
-- Added by KLYong
CREATE INDEX IDX_CHRG6 ON MIG_CO017_CD
	("FACILITY_SEQ" ASC, "FACILITY_CODE" DESC) 
	ALLOW REVERSE SCANS; 

CREATE INDEX IDX_CHRG7 ON MIG_CO017_CD
	("CMS_ACT_LMT_ID" ASC, "CMS_ACT_COL_ID" DESC) 
	ALLOW REVERSE SCANS; 
	
CREATE INDEX IDX_CHRG8 ON MIG_CO017_CD
	("CMS_ACT_CHRG_DTL_ID" ASC, "IS_VALID" ASC, "CMS_ACT_COL_ID" ASC, "RANKING_OF_SECURITY" ASC) 
	ALLOW REVERSE SCANS;

CREATE INDEX IDX_CHRG9 ON MIG_CO017_CD
	("IS_VALID" ASC, "CMS_ACT_CHRG_ID" ASC, "LIMIT_ID" ASC, "CHARGE_AMT" ASC) 
	ALLOW REVERSE SCANS;  	
	
CREATE INDEX IDX_CHRG10 ON MIG_CO017_CD
	("RANKING_OF_SECURITY" ASC, "CMS_STG_COL_ID" DESC) 
	ALLOW REVERSE SCANS; 	
	
CREATE INDEX IDX_CHRG11 ON MIG_CO017_CD
	("IS_VALID" ASC, "CMS_STG_CHRG_ID" ASC, "LIMIT_ID" ASC, "CHARGE_AMT" ASC) 
	ALLOW REVERSE SCANS; 	
	

CREATE TABLE MIG_CO018_PG(
	cms_pldgr_id 				bigint,
	cms_stg_pldgr_id			bigint,
	cms_act_col_id 				bigint,
	cms_stg_col_id			bigint,
	cms_act_spm_id			bigint,
	IS_VALID 					CHAR(1) DEFAULT 'Y',
	SECURITY_ID 				VARCHAR(19),	
	PLEDGOR_CIF_ID 				VARCHAR(19),
	PLEDGOR_COUNTRY				CHAR(2),
	PLEDGOR_ORG_CODE			VARCHAR(40),
	PLEDGOR_ID_NUM				VARCHAR(30),
	PLEDGOR_LEGAL_NAME 			VARCHAR(150),
	REL_WITH_BORROWER_CAT 		VARCHAR(15) DEFAULT 'RELATIONSHIP',
	REL_WITH_BORROWER_CODE 		VARCHAR(10),
	REL_WITH_BORROWER_DESC		VARCHAR(20),
	RECORD_TYPE 				VARCHAR(1)	
)in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX IDX_PLG1 ON MIG_CO018_PG
	(PLEDGOR_CIF_ID ASC, IS_VALID ASC) ALLOW REVERSE SCANS;

-- CREATE INDEX IDX_PLG2 ON MIG_CO018_PG 
-- 	(CMS_PLDGR_ID) ALLOW REVERSE SCANS;

-- CREATE INDEX IDX_COL3 ON MIG_CO018_PG
-- 	(SECURITY_ID ASC, IS_VALID ASC) ALLOW REVERSE SCANS;

CREATE INDEX IDX_PLGCOL ON MIG_CO018_PG
	(is_valid, CMS_ACT_COL_ID ASC, CMS_PLDGR_ID ASC) ALLOW REVERSE SCANS;
	
-- Added by KLYong
-- CREATE INDEX IDX_PLG3 ON MIG_CO018_PG 
-- 	("PLEDGOR_CIF_ID") 
-- 	ALLOW REVERSE SCANS;

CREATE INDEX IDX_PLG4 ON MIG_CO018_PG
	("CMS_PLDGR_ID" ASC, "IS_VALID" ASC, "PLEDGOR_CIF_ID" ASC) 
	ALLOW REVERSE SCANS;	
	
CREATE INDEX IDX_PLG5 ON "MIG_CO018_PG" 
	("IS_VALID" ASC, "SECURITY_ID" ASC) 
	ALLOW REVERSE SCANS; 	

	
CREATE TABLE MIG_CO019_PL(
	IS_VALID 				CHAR(1) DEFAULT 'Y',
    CMS_ACT_LMT_PROFILE_ID  		BIGINT,
	CMS_ACT_COL_ID 				BIGINT,
  	CMS_STG_COL_ID 				BIGINT,
  	CMS_ACT_LMT_ID 				BIGINT,
  	CMS_STG_LMT_ID 				BIGINT,	
	SECURITY_ID 				VARCHAR(19),
    LIMIT_ID 		    		VARCHAR(42),
	APPLICATION_NO 				VARCHAR(19),
	FACILITY_CODE				VARCHAR(3),
	FACILITY_SEQUENCE			BIGINT,
  	SRC_LE_ID				VARCHAR(20),	
	AMOUNT_PLEDGED				DECIMAL(15,2),
	PERCENT_PLEDGED				DECIMAL(5,2),
	AMOUNT_DRAW				DECIMAL(15,2),
	PERCENT_DRAW				DECIMAL(5,2),
		APPLICATION_TYPE			VARCHAR(2),
		APPLICATION_LAW_TYPE		VARCHAR(3),	
		CIF_ID						VARCHAR(20),
		CUST_NAME_S					VARCHAR(80),
		CMS_SECURITY_SUBTYPE_ID     VARCHAR(10),
		SOURCE_SECURITY_SUB_TYPE	VARCHAR(3),
		LOC_ORG_CODE 	     		VARCHAR(5),
	RECORD_TYPE 				VARCHAR(1)	
)in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX IDX_PL1 ON MIG_CO019_PL
	(SECURITY_ID ASC, IS_VALID ASC) ALLOW REVERSE SCANS;

CREATE INDEX IDX_PL2 ON MIG_CO019_PL
	(APPLICATION_NO ASC, LIMIT_ID ASC, FACILITY_CODE ASC, FACILITY_SEQUENCE ASC, IS_VALID ASC) ALLOW REVERSE SCANS;
	
CREATE INDEX IDX_PL3 ON MIG_CO019_PL
	(CMS_ACT_COL_ID, IS_VALID)
	ALLOW REVERSE SCANS;
	
CREATE INDEX IDX_PL4 ON MIG_CO019_PL
	(CMS_ACT_LMT_ID, IS_VALID)
	ALLOW REVERSE SCANS;

-- CREATE INDEX IDX_PL5 ON MIG_CO019_PL
	-- (IS_VALID, CMS_ACT_COL_ID, CMS_ACT_LMT_ID)
	-- ALLOW REVERSE SCANS;	

CREATE INDEX IDX_PL5 ON MIG_CO019_PL
	(CMS_ACT_LMT_ID ASC, CMS_ACT_COL_ID ASC, IS_VALID DESC)
	ALLOW REVERSE SCANS;	

CREATE INDEX IDX_PL6 ON MIG_CO019_PL
	(CMS_ACT_LMT_ID ASC, CMS_STG_COL_ID ASC, IS_VALID DESC)
	ALLOW REVERSE SCANS;			
    
---------------------------------------------------------------------	
-- Added by KLYong
DROP INDEX MIG_IDX_0001;
CREATE INDEX MIG_IDX_0001 ON CMS_FAC_OFFICER
	("SEQ_NUM" ASC, "CMS_FAC_MASTER_ID" ASC, "ID" ASC) 
	ALLOW REVERSE SCANS; 

DROP INDEX MIG_IDX_0002;
CREATE INDEX MIG_IDX_0002 ON CMS_FAC_OFFICER
	("CMS_REF_ID" ASC, "CMS_FAC_MASTER_ID" ASC, "SEQ_NUM" ASC) 
	ALLOW REVERSE SCANS; 		

DROP INDEX MIG_IDX_0003;	
CREATE INDEX MIG_IDX_0003 ON CMS_FAC_RELATIONSHIP
	("CMS_FAC_MASTER_ID" ASC, "ID" DESC) 
	ALLOW REVERSE SCANS;
	
DROP INDEX MIG_IDX_0004;	
CREATE INDEX MIG_IDX_0004 ON CMS_FAC_RELATIONSHIP 
	("CMS_REF_ID" ASC, "CMS_FAC_MASTER_ID" DESC) 
	ALLOW REVERSE SCANS; 	
	
-- DROP INDEX MIG_IDX_0005;	
-- CREATE INDEX MIG_IDX_0005 ON CMS_FAC_INSURANCE
	-- ("CMS_FAC_MASTER_ID" ASC, "CMS_REF_ID" ASC) 
	-- ALLOW REVERSE SCANS; 	

DROP INDEX MIG_IDX_0006;	
CREATE INDEX MIG_IDX_0006 ON CMS_STAGE_SECURITY
	("SECURITY_SUB_TYPE_ID" ASC) 
	ALLOW REVERSE SCANS; 	
	
DROP INDEX MIG_IDX_0007;	
CREATE UNIQUE INDEX MIG_IDX_0007 ON CMS_SECURITY_SUB_TYPE 
	("SECURITY_SUB_TYPE_ID", "SUBTYPE_NAME", "SECURITY_TYPE_NAME")
	ALLOW REVERSE SCANS;	
	
DROP INDEX MIG_IDX_0008;	
CREATE INDEX MIG_IDX_0008 ON CMS_STAGE_SECURITY
	("SCI_SECURITY_TYPE_VALUE" ASC, "SCI_SECURITY_DTL_ID" ASC, "CMS_COLLATERAL_ID" ASC) 
	ALLOW REVERSE SCANS; 

DROP INDEX MIG_IDX_0009;	
CREATE INDEX MIG_IDX_0009 ON CMS_SECURITY
	("SCI_SECURITY_TYPE_VALUE" ASC, "SCI_SECURITY_DTL_ID" ASC, "CMS_COLLATERAL_ID" ASC) 
	ALLOW REVERSE SCANS; 
	
DROP INDEX MIG_IDX_0010;
CREATE INDEX MIG_IDX_0010 ON CMS_PRICE_FEED
	("STOCK_CODE" ASC, "EXCHANGE" ASC, "BOARD_TYPE" ASC, "FEED_ID" ASC) 
	ALLOW REVERSE SCANS; 	
	
DROP INDEX MIG_IDX_0011;	
CREATE INDEX MIG_IDX_0011 ON CMS_PORTFOLIO_ITEM
	("STOCK_CODE" ASC, "NO_OF_UNITS" ASC) 
	ALLOW REVERSE SCANS; 

DROP INDEX MIG_IDX_0012;	
CREATE INDEX MIG_IDX_0012 ON CMS_EARMARK_GROUP
	("FEED_ID" ASC) 
	ALLOW REVERSE SCANS; 	
	
DROP INDEX MIG_IDX_0013;	
CREATE UNIQUE INDEX MIG_IDX_0013 ON CMS_PRICE_FEED
	("FEED_ID" ASC) 
	INCLUDE ( "STOCK_CODE", "FEED_GROUP_ID") 
	ALLOW REVERSE SCANS; 	

-- DROP INDEX MIG_IDX_0014;	
-- CREATE INDEX MIG_IDX_0014 ON COMMON_CODE_CATEGORY_ENTRY
-- 	("ENTRY_CODE" ASC, "CATEGORY_CODE" ASC, "REF_ENTRY_CODE" ASC) 
-- 	ALLOW REVERSE SCANS; 	
	
DROP INDEX MIG_IDX_0015;	
CREATE INDEX MIG_IDX_0015 ON CMS_SECURITY
	("SOURCE_ID" ASC, "SECURITY_SUB_TYPE_ID" ASC, "TYPE_NAME" ASC, "SUBTYPE_NAME" ASC, "SCI_SECURITY_DTL_ID" ASC) 
	ALLOW REVERSE SCANS; 	

DROP INDEX MIG_IDX_0016;	
CREATE INDEX MIG_IDX_0016 ON SCI_LSP_APPR_LMTS
	("SOURCE_ID" ASC, "LMT_ID" ASC, "LMT_LE_ID" ASC, "LMT_FAC_CODE" ASC, "LMT_BCA_REF_NUM" ASC, "LMT_FAC_SEQ" ASC, "CMS_LSP_APPR_LMTS_ID" ASC) 
	ALLOW REVERSE SCANS; 	
	
DROP INDEX MIG_IDX_0017;	
CREATE INDEX MIG_IDX_0017 ON CMS_CHARGE_DETAIL
	("SOURCE_ID" ASC, "STATUS" ASC, "CMS_COLLATERAL_ID" ASC, "SECURITY_RANK" ASC, "CHARGE_DETAIL_ID" ASC) 
	ALLOW REVERSE SCANS; 

DROP INDEX MIG_IDX_0018;	
CREATE INDEX MIG_IDX_0018 ON CMS_LIMIT_SECURITY_MAP
	("SOURCE_ID" ASC, "CHARGE_AMOUNT" ASC, "SCI_LAS_LMT_ID" ASC, "CHARGE_ID" ASC) 
	ALLOW REVERSE SCANS; 

DROP INDEX MIG_IDX_0019;	
CREATE INDEX MIG_IDX_0019 ON CMS_STAGE_CHARGE_DETAIL 
	("SOURCE_ID" ASC, "SECURITY_RANK" ASC, "CMS_COLLATERAL_ID" ASC, "CHARGE_DETAIL_ID" DESC) 
	ALLOW REVERSE SCANS; 	
	
DROP INDEX MIG_IDX_0020;	
CREATE INDEX MIG_IDX_0020 ON CMS_STAGE_LIMIT_SECURITY_MAP
	("SOURCE_ID" ASC, "CHARGE_AMOUNT" ASC, "SCI_LAS_LMT_ID" ASC, "CHARGE_ID" ASC) 
	ALLOW REVERSE SCANS; 
	
DROP INDEX MIG_IDX_0021;	
CREATE INDEX MIG_IDX_0021 ON SCI_PLEDGOR_DTL
	("SOURCE_ID" ASC, "PLG_LE_ID" ASC, "CMS_PLEDGOR_DTL_ID" ASC) 
	ALLOW REVERSE SCANS; 	
	
DROP INDEX MIG_IDX_0022;	
CREATE INDEX MIG_IDX_0022 ON STAGE_PLEDGOR_DTL
	("SOURCE_ID" ASC, "PLG_LE_ID" ASC, "CMS_PLEDGOR_DTL_ID" ASC) 
	ALLOW REVERSE SCANS; 	
	
DROP INDEX MIG_IDX_0023;	
CREATE INDEX MIG_IDX_0023 ON TRANSACTION
	("TRANSACTION_TYPE" ASC, "REFERENCE_ID" ASC, "STAGING_REFERENCE_ID" ASC) 
	ALLOW REVERSE SCANS; 	
	
DROP INDEX MIG_IDX_0024;		
CREATE UNIQUE INDEX MIG_IDX_0024 ON STAGE_LIMIT_PROFILE
	("CMS_LSP_LMT_PROFILE_ID" ASC) 
	INCLUDE ( "SOURCE_ID", "LOS_BCA_REF_NUM") 
	ALLOW REVERSE SCANS; 	
	
DROP INDEX MIG_IDX_0025;	
CREATE UNIQUE INDEX MIG_IDX_0025 ON SCI_LSP_LMT_PROFILE
	("CMS_LSP_LMT_PROFILE_ID" ASC) 
	INCLUDE ( "SOURCE_ID", "LOS_BCA_REF_NUM") 
	ALLOW REVERSE SCANS; 	
	
-- DROP INDEX MIG_IDX_0026;	
-- CREATE INDEX MIG_IDX_0026 ON TRANSACTION
--     ("TRANSACTION_TYPE" ASC, "STAGING_REFERENCE_ID" ASC, "REFERENCE_ID" ASC) 
--     ALLOW REVERSE SCANS; 	
	
DROP INDEX MIG_IDX_0027;	
CREATE INDEX MIG_IDX_0027 ON SCI_LSP_LMT_PROFILE
	("LOS_BCA_REF_NUM" ASC, "IS_MIGRATED_IND" ASC, "SOURCE_ID" ASC, "CMS_LSP_LMT_PROFILE_ID" ASC) 
	ALLOW REVERSE SCANS; 	

DROP INDEX MIG_IDX_0028;	
CREATE INDEX MIG_IDX_0028 ON STP_MASTER_TRANS
("REFERENCE_ID" ASC, "TRANSACTION_ID" ASC) 
ALLOW REVERSE SCANS ; 

-- DROP INDEX MIG_IDX_0029;	
-- CREATE INDEX MIG_IDX_0029 ON TRANSACTION
-- ("TRANSACTION_TYPE" ASC, "STATUS" ASC, "REFERENCE_ID" ASC, "TRANSACTION_ID" ASC, "CUR_TRX_HISTORY_ID" ASC) 
-- ALLOW REVERSE SCANS ; 

-- DROP INDEX MIG_IDX_0030;	
-- CREATE INDEX MIG_IDX_0030 ON STP_TRANS 
-- ("MASTER_TRX_ID" ASC, "TRX_TYPE" ASC) 
-- ALLOW REVERSE SCANS ; 

--DROP INDEX MIG_IDX_0031;	
--CREATE UNIQUE INDEX MIG_IDX_0031 ON STAGE_LIMIT_PROFILE
--	(LOS_BCA_REF_NUM, SOURCE_ID) 
--	INCLUDE ( CMS_LSP_LMT_PROFILE_ID) 
--	ALLOW REVERSE SCANS; 	

DROP INDEX MIG_IDX_0031;	
CREATE INDEX MIG_IDX_0031 ON CMS_FACILITY_MASTER 
("CMS_LSP_APPR_LMTS_ID" ASC, "ID" DESC) 
ALLOW REVERSE SCANS ; 

DROP INDEX MIG_IDX_0032;	
CREATE INDEX MIG_IDX_0032 ON SCI_LSP_APPR_LMTS
("LMT_ID" ASC, "SOURCE_ID" DESC) 
ALLOW REVERSE SCANS ; 

DROP INDEX MIG_IDX_0033;	
CREATE INDEX MIG_IDX_0033 ON STAGE_LIMIT 
("LMT_ID" ASC, "CMS_LSP_APPR_LMTS_ID" ASC) 
ALLOW REVERSE SCANS ; 

-- DROP INDEX MIG_IDX_0034;	
-- CREATE INDEX MIG_IDX_0034 ON CMS_STG_FACILITY_MASTER 
-- ("CMS_LSP_APPR_LMTS_ID" ASC, "ID" ASC) 
-- ALLOW REVERSE SCANS ; 

DROP INDEX MIG_IDX_0035;	
CREATE INDEX MIG_IDX_0035 ON CMS_STG_FACILITY_MASTER 
("CMS_LSP_APPR_LMTS_ID" ASC) 
ALLOW REVERSE SCANS ; 

DROP INDEX MIG_IDX_0036;
CREATE INDEX MIG_IDX_0036 ON CMS_STAGE_SECURITY
 (SCI_SECURITY_DTL_ID, SOURCE_ID, CMS_COLLATERAL_ID)
ALLOW REVERSE SCANS;

DROP INDEX MIG_IDX_0037;
create index MIG_IDX_0037 on stage_limit_profile
	(LOS_BCA_REF_NUM, SOURCE_ID, cms_lsp_lmt_profile_id)
	ALLOW REVERSE SCANS;

DROP INDEX MIG_IDX_0038;	
CREATE INDEX MIG_IDX_0038 ON CMS_SECURITY
	("SCI_SECURITY_DTL_ID" ASC, "SOURCE_ID" ASC, "SECURITY_SUB_TYPE_ID" ASC, "SOURCE_SECURITY_SUB_TYPE" ASC, "SCI_REFERENCE_NOTE" ASC) 
	ALLOW REVERSE SCANS; 