CREATE TABLE STGE_TEMP_IMAGE_UPLOAD
(	IMG_ID NUMBER(19,0) primary key NOT NULL, 
	IMG_FILENAME VARCHAR2(100 CHAR), 
	IMG_SIZE NUMBER(19,0), 
	IMG_DEPRICATED CHAR(1 CHAR), 
	VERSION_TIME NUMBER DEFAULT 0, 
	CUST_ID VARCHAR2(20 CHAR), 
	CUST_NAME VARCHAR2(100 CHAR), 
	IMG_PATH VARCHAR2(200 CHAR), 
	IMG_SEND_FOR_APP CHAR(1 CHAR), 
	IMG_APPR_ID NUMBER(19,0), 
	HAS_SUBFOLDER VARCHAR2(1 BYTE), 
	SUBFOLDER_NAME VARCHAR2(40 BYTE), 
	STATUS NUMBER DEFAULT 1 NOT NULL , 
	ERROR VARCHAR2(300 BYTE), 
	CREATION_DATE TIMESTAMP (9), 
	CREATE_BY NUMBER(30,0), 
	DOCUMENT_NAME VARCHAR2(100 BYTE), 
	FROM_SERVER VARCHAR2(20 BYTE) 
   );
  
  CREATE INDEX STGE_TEMP_IMAGE_UPLOAD_INDEX1 ON STGE_TEMP_IMAGE_UPLOAD (STATUS, FROM_SERVER);
  CREATE INDEX STGE_TEMP_IMAGE_UPLOAD_INDEX2 ON STGE_TEMP_IMAGE_UPLOAD (CUST_ID);
  CREATE INDEX STGE_TEMP_IMAGE_UPLOAD_INDEX3 ON STGE_TEMP_IMAGE_UPLOAD (CUST_ID, SUBFOLDER_NAME);
  CREATE SEQUENCE STGE_IMG_UPLOAD_SEQ  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  CYCLE;