------------------------------------
-- Data Cleanup Related Tables 
------------------------------------
DROP TABLE MIG_DATA_CLEANUP;
DROP TABLE MIG_DATA_CLEANUP_REPORT;

CREATE TABLE MIG_DATA_CLEANUP (
  SI_NUMBER	BIGINT	GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE, NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  TIME_STAMP	TIMESTAMP,
  SYSTEM_ID	    VARCHAR(10),
  INTERFACE_ID	VARCHAR(10),
  KEY1_VALUE	VARCHAR(50),
  KEY2_VALUE	VARCHAR(50),
  KEY3_VALUE	VARCHAR(50),
  KEY4_VALUE	VARCHAR(50),
  KEY5_VALUE	VARCHAR(50),
  KEY6_VALUE	VARCHAR(50),
  KEY7_VALUE	VARCHAR(50),
  KEY8_VALUE	VARCHAR(50),
  KEY9_VALUE	VARCHAR(50),
  KEY10_VALUE	VARCHAR(50),
  KEY11_VALUE	VARCHAR(50),
  KEY12_VALUE	VARCHAR(50),
  KEY13_VALUE	VARCHAR(50),
  KEY14_VALUE	VARCHAR(50),
  KEY15_VALUE	VARCHAR(50),
  KEY16_VALUE	VARCHAR(50),
  KEY17_VALUE	VARCHAR(50),
  ERROR_CODE	VARCHAR(20),
  ERROR_MSG	    VARCHAR(1000)
) in CMS_MIG index in CMS_MIG_INDEX;

CREATE INDEX MIG_DATA_CLEANUP_IDX1 ON MIG_DATA_CLEANUP
(INTERFACE_ID ASC, SYSTEM_ID ASC) ALLOW REVERSE SCANS;   


CREATE TABLE MIG_DATA_CLEANUP_REPORT(
    MIG_ID		BIGINT	NOT NULL	GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE, NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
    RECORD_TYPE     	VARCHAR(30),
    TEXT            	VARCHAR(2000),
    SYSTEM_ID       	VARCHAR(4),
    CRITERIA		VARCHAR(7),
    INTERFACE_ID	VARCHAR(7)
)  IN CMS_MIG;


