insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'AD', 'ANDORRA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'AE', 'UNITED ARAB EMIRATES');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'AF', 'AFGHANISTAN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'AG', 'ANTIGUA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'AL', 'ALBANIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'AN', 'NETHERLANDS ANTILLES');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'AO', 'ANGOLA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'AQ', 'ANTARTICA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'AR', 'ARGENTINA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'AS', 'AMERICAN SAMOA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'AT', 'AUSTRIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'AU', 'AUSTRALIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'BB', 'BARBADOS');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'BD', 'BANGLADESH');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'BE', 'BELGIUM');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'BG', 'BULGARIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'BH', 'BAHRAIN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'BI', 'BURUNDI');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'BJ', 'BENIN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'BM', 'BERMUDA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'BN', 'BRUNEI DARUSSALAM');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'BO', 'BOLIVIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'BR', 'BRAZIL');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'BS', 'BAHAMAS');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'BT', 'BHUTAN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'BU', 'BURMA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'BV', 'BOUVET ISLAND');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'BW', 'BOTSWANA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'BY', 'BYELORUSSIAN SSR');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'BZ', 'BELIZE');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'CA', 'CANADA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'CC', 'COCOS(KEELING)ISLAND');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'CF', 'CENTRAL AFRICAN REP');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'CG', 'CONGO');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'CH', 'SWITERLAND');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'CI', 'IVORY COAST');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'CK', 'COOK ISLANDS');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'CL', 'CHILE');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'CM', 'CAMEROON UNITED REP');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'CN', 'CHINA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'CO', 'COLOMBIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'CR', 'COSTA RICA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'CS', 'CZECHOSLAVAKIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'CT', 'CANTON AND ENDERBURY');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'CU', 'CUBA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'CV', 'CAPE VERDE');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'CX', 'CHRISTMAS ISLAND');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'CY', 'CYPRUS');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'DD', 'GERMAN D''CRATIC REP');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'DE', 'GERMANY');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'DJ', 'DJIBOUTI');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'DK', 'DENMARK');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'DM', 'DOMINICA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'DO', 'DOMINICAN REPUBLIC');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'DZ', 'ALGERIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'EC', 'ECUADOR');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'EG', 'EGYPT');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'EH', 'WESTERN SAHARA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'ES', 'SPAIN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'ET', 'ETHIOPIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'FI', 'FINLAND');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'FJ', 'FIJI');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'FK', 'FALKLAND ISLANDS');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'FO', 'FAEROE ISLANDS');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'FR', 'FRANCE');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'GA', 'GABON');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'GB', 'UNITED KINGDOM');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'GD', 'GRENADA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'GF', 'FRENCH GUIANA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'GH', 'GHANA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'GI', 'GIBRALTAR');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'GL', 'GREENLAND');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'GM', 'GAMBIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'GN', 'GUINEA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'GP', 'GUADALOUPE');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'GQ', 'EQUATORIAL GUINEA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'GR', 'GREECE');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'GT', 'GUATEMALA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'GU', 'GUAM');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'GW', 'GUINEA-BISSAU');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'GY', 'GUYANA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'HK', 'HONG KONG');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'HM', 'HEARD & MC DONALD');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'HN', 'HONDURAS');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'HT', 'HAITI');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'HU', 'HUNGARY');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'HV', 'UPPER VOLTA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'ID', 'INDONESIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'IE', 'IRELAND');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'IL', 'ISRAEL');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'IN', 'INDIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'IO', 'BRITISH INDIAN OCEAN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'IQ', 'IRAQ');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'IR', 'IRAN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'IS', 'ICELAND');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'IT', 'ITALY');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'JM', 'JAMAICA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'JO', 'JORDAN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'JP', 'JAPAN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'JT', 'JOHNSTON ISLAND');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'KE', 'KENYA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'KH', 'KAMPUCHEA,DEMOCRATIC');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'KM', 'COMOROS');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'KN', 'ST KITIS-NEVIS-ANGUI');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'KP', 'KOREA, NORTH');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'KR', 'KOREA, SOUTH');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'KW', 'KUWAIT');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'KY', 'CAYMAN ISLANDS');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'KZ', 'KAZAKHSTAN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'LA', 'LAOS');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'LB', 'LEBANON');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'LC', 'SAINT LUCIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'LI', 'LIECHTENSTEN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'LK', 'SRI LANKA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'LN', 'LABUAN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'LR', 'LIBERIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'LS', 'LESOTHO');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'LU', 'LUXEMBOURG');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'LY', 'LIBYAN ARAB JAMAHIRI');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MA', 'MOROCCO');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MC', 'MONACO');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MG', 'MADAGASCAR');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MI', 'MIDWAY ISLANDS');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'ML', 'MALI');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MM', 'MYANMAR');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MN', 'MONGOLIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MO', 'MACAU');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MQ', 'MARTINIQUE');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MR', 'MAURITANIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MS', 'MONTSERRAT');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MT', 'MALTA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MU', 'MAURITIUS');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MV', 'MALDIVES');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MW', 'MALAWI');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MX', 'MEXICO');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MY', 'MALAYSIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MZ', 'MOZAMBIQUE');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'NA', 'NAMIBIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'NC', 'NEW CALENDONIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'NE', 'NIGER');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'NF', 'NORFOLK ISLAND');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'NG', 'NIGERIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'NI', 'NICARAGUA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'NL', 'NETHERLANDS');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'NO', 'NORWAY');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'NP', 'NEPAL');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'NQ', 'DRONING MAUD LAND');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'NR', 'NAURU');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'NT', 'NEUTRAL ZONE');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'NU', 'NIUE');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'NZ', 'NEW ZEALAND');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'OM', 'OMAN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'OO', 'OTHERS');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'OT', 'OTHERS');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'PA', 'PANAMA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'PC', 'PACIFIC ISLANDS');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'PE', 'PERU');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'PF', 'FRENCH POLYNESIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'PG', 'PAPUA NEW GUINEA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'PH', 'PHILIPPINES');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'PK', 'PAKISTAN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'PL', 'POLAND');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'PM', 'ST PIERRE & MIQUELON');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'PN', 'PITCAIRN ISLAND');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'PP', 'UNIDENTIFIED CITIZEN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'PR', 'PUERTO RICO');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'PT', 'PORTUGAL');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'PU', 'UNITED STATES MISC');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'PY', 'PARAGUAY');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'QA', 'QATAR');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'RE', 'REUNION');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'RO', 'ROMANIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'RW', 'RWANDA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'SA', 'SAUDI ARABIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'SB', 'SOLOMON ISLANDS');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'SC', 'SEYCHELLES');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'SD', 'SUDAN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'SE', 'SWEDEN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'SF', 'SOUTH AFRICA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'SG', 'SINGAPORE');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'SH', 'ST HELENA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'SJ', 'SVALBARD & JAN MAYEN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'SL', 'SIERRA LEONE');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'SM', 'SAN MARINO');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'SN', 'SENEGAL');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'SO', 'SOMALIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'SR', 'SURINAM');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'ST', 'SAO TOME & PRINCIPE');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'SU', 'USSR');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'SV', 'EL SALVADOR');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'SY', 'SYRIAN ARAB REPUBLIC');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'SZ', 'SWAZILAND');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'TC', 'TURKS & CAICOS ISLAN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'TD', 'CHAD');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'TG', 'TOGO');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'TH', 'THAILAND');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'TK', 'TOKELAU');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'TN', 'TUNISIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'TO', 'TONGA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'TP', 'EAST TIMOR');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'TR', 'TURKEY');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'TT', 'TRINIDAD AND TOBAGO');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'TV', 'TUVALU');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'TW', 'TAIWAN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'TZ', 'TANZANIA UNITED REP');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'UA', 'UKRAINIAN SSR');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'UG', 'UGANDA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'US', 'UNITED STATES');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'UY', 'URUGUAY');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'UZ', 'UZBEKISTAN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'VA', 'VATICAN CITY STATE');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'VC', 'SAINT VINCENT & THE');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'VE', 'VENEZUELA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'VG', 'VIRGIN ISLAND(BRIT)');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'VI', 'UNITED STATES VIEGIN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'VN', 'VIETNAM');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'VU', 'VANUATU');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'WF', 'WALLIS AND FUTUNA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'WK', 'WAKE ISLAND');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'WS', 'SAMOA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'YD', 'YEMEN DEMOCRATIC');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'YE', 'YEMEN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'YU', 'YUGOSLAVIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'ZA', 'SOUTH AFRICA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'ZM', 'ZAMBIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'ZR', 'ZAIRE');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'ZW', 'ZIMBABWE');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'EE', 'ESTONIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'AX', 'ALAND ISLANDS');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'AI', 'ANGUILLA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'AM', 'ARMENIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'AW', 'ARUBA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'AZ', 'AZERBAIJAN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'BA', 'BOSNIA & HERZEGOVINA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'BF', 'BURKINO FASO');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'CD', 'CONGO');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'HR', 'CROTIA (HRVATSKA)');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'CZ', 'CZECH REPUBLIC');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'ER', 'ERITREA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'FX', 'FRANCE, METROPOLITAN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'TF', 'FRENCH STN TERRITORY');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'GE', 'GEORGIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'KI', 'KIRIBATI');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'KG', 'KYRGYZSTAN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'LV', 'LATVIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'LT', 'LITHUANIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MK', 'MACEDONIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MH', 'MARSHALL ISLANDS');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'YT', 'MAYOTTE');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'FM', 'MICRONESIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MD', 'MOLDOVA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'MP', 'NR MARIANA ISLANDS');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'PW', 'PALAU');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'PS', 'PALESTINIAN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'RU', 'RUSSIAN FEDERATION');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'SK', 'SLOVAKIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'SI', 'SLOVENIA');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'GS', 'GEORGIA & SANDWICH');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'TJ', 'TAJIKISTAN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'TL', 'TIMOR-LESTE');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'TM', 'TURKMENISTAN');
insert into sci_country (cms_country_id, ctr_cntry_iso_code, ctr_cntry_name) values (next value for sci_country_seq, 'UM', 'MINOR OUTLYING ISLAN');
