---------------------------------------
----  Image Tag TO Track
---------------------------------------
insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values ('IMAGE_TAG','ImageTagMap.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_CREATE','Pending Create','Maintain Image Tag ','','');
insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values ('IMAGE_TAG','ImageTagMap.do?event=rejected_delete_read&toTrack=yes&TrxId=','ACTIVE','Approved','Maintain Image Tag ','','');
insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values ('IMAGE_TAG','ImageTagMap.do?event=rejected_delete_read&toTrack=yes&TrxId=','REJECTED','Rejected','Maintain Image Tag ','','');
insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values ('IMAGE_TAG','ImageTagMap.do?event=rejected_delete_read&toTrack=yes&TrxId=','CLOSED','Closed','Maintain Image Tag ','','');
insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values ('IMAGE_TAG','ImageTagMap.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_UPDATE','Pending Update','Maintain Image Tag ','','');
insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values ('IMAGE_TAG','ImageTagMap.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_DELETE','Pending Delete','Maintain Image Tag ','','');
insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values ('IMAGE_TAG','ImageTagMap.do?event=rejected_delete_read&toTrack=yes&TrxId=','DELETED','Deleted','Maintain Image Tag ','','');


--------------------------------------------
--- Image Tag Tr State Matrix
--------------------------------------------
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (7801,'IMAGE_TAG','EDIT_REJECTED_DELETE_IMAGE_TAG','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (7802,'IMAGE_TAG','CREATE_IMAGE_TAG','ND','PENDING_CREATE','PENDING_CREATE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (7803,'IMAGE_TAG','APPROVE_IMAGE_TAG','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (7804,'IMAGE_TAG','UPDATE_IMAGE_TAG','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (7805,'IMAGE_TAG','APPROVE_CREATE_IMAGE_TAG','PENDING_CREATE','ACTIVE','ACTIVE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (7806,'IMAGE_TAG','REJECT_IMAGE_TAG','PENDING_UPDATE','REJECTED','REJECTED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (7807,'IMAGE_TAG','EDIT_REJECTED_UPDATE_IMAGE_TAG','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (7808,'IMAGE_TAG','CLOSE_REJECTED_UPDATE_IMAGE_TAG','REJECTED','CLOSED','CLOSED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (7809,'IMAGE_TAG','REJECT_IMAGE_TAG','PENDING_CREATE','REJECTED','REJECTED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (7810,'IMAGE_TAG','CLOSE_REJECTED_CREATE_IMAGE_TAG','REJECTED','CLOSED','CLOSED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (7811,'IMAGE_TAG','EDIT_REJECTED_CREATE_IMAGE_TAG','REJECTED','PENDING_CREATE','PENDING_CREATE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (7812,'IMAGE_TAG','DELETE_IMAGE_TAG','ACTIVE','PENDING_DELETE','PENDING_DELETE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (7813,'IMAGE_TAG','DELETE_IMAGE_TAG','PENDING_DELETE','DELETED','DELETED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (7814,'IMAGE_TAG','REJECT_IMAGE_TAG','PENDING_DELETE','REJECTED','REJECTED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (7815,'IMAGE_TAG','CLOSE_REJECTED_DELETE_IMAGE_TAG','REJECTED','CLOSED','CLOSED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (7816,'IMAGE_TAG','UPDATE_IMAGE_TAG','PENDING_UPDATE','ACTIVE','PENDING_UPDATE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (7817,'IMAGE_TAG','CHECKER_APPROVE_UPDATE','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (7818,'IMAGE_TAG','CHECKER_APPROVE_DELETE','PENDING_DELETE','DELETED','DELETED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (7819,'IMAGE_TAG','APPROVE_IMAGE_TAG','PENDING_DELETE','DELETED','DELETED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (7820,'IMAGE_TAG','CHECKER_APPROVE_UPDATE','PENDING_DELETE','DELETED','DELETED','1','1');


----------------------------------------------
--- Image Tag State Matrix Action
----------------------------------------------

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7809,37,'Process','ImageTag.do?event=checker_process_edit&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7806,37,'Process','ImageTag.do?event=checker_process_edit&TrxId=','ImageTag.do?event=to_track&TrxId=');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7807,36,'Process','ImageTag.do?event=maker_prepare_resubmit_delete&TrxId=','ImageTag.do?event=to_track&TrxId=');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7808,36,'Close','ImageTag.do?event=maker_prepare_close&TrxId=','ImageTag.do?event=to_track&TrxId=');



------------------------------------------------------
---- System Bank And Branches Maintain Function Access
------------------------------------------------------



INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(60000004,'systemBank','maker_list_systemBank',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(60000007,'systemBank','maker_view_systemBank',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(60000008,'systemBankBranch','maker_list_systemBankBranch',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(60000009,'systemBankBranch','maker_view_systemBankBranch',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(60000121,'systemBankBranch','maker_edit_systemBankBranch_read',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(60000122,'systemBank','maker_edit_systemBank_read',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(60000145,'systemBank','maker_edit_systemBank',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(60000144,'systemBankBranch','maker_delete_systemBankBranch',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(60000487,'systemBankBranch','maker_edit_systemBankBranch',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(60000458,'systemBankBranch','maker_delete_systemBankBranch_read',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(600000087,'systemBankBranch','maker_search_list_systemBankBranch',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(600000047,'systemBankBranch','list_pagination',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484888,'systemBank','checker_edit_read',9);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484889,'systemBank','checker_approve_edit',9);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484890,'systemBank','rejected_delete_read',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484831,'systemBank','checker_reject_edit',9);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484832,'systemBank','maker_prepare_resubmit',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484833,'systemBank','maker_prepare_close',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484834,'systemBank','maker_confirm_resubmit_edit',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484835,'systemBank','rejected_delete_read',9);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484836,'systemBank','maker_confirm_close',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484837,'systemBank','checker_list_systemBank',9);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484838,'systemBankBranch','checker_list_systemBankBranch',9);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484839,'systemBankBranch','maker_view_systemBankBranch',9);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484840,'systemBank','maker_view_systemBank',9);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484841,'systemBank','checker_view_systemBank',9);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484842,'systemBankBranch','maker_list_systemBankBranch',9);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484843,'systemBankBranch','checker_edit_read',9);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484844,'systemBankBranch','checker_approve_edit',9);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484845,'systemBankBranch','rejected_delete_read',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484846,'systemBankBranch','checker_reject_edit',9);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484847,'systemBankBranch','maker_prepare_resubmit',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484848,'systemBankBranch','maker_prepare_close',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484849,'systemBankBranch','maker_confirm_resubmit_edit',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484850,'systemBankBranch','rejected_delete_read',9);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484851,'systemBankBranch','maker_confirm_close',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484852,'systemBankBranch','checker_view_systemBankBranch',9);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484853,'systemBankBranch','checker_process_edit',9);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484854,'systemBankBranch','checker_process_delete',9);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484855,'systemBankBranch','maker_prepare_resubmit_delete',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484856,'systemBankBranch','maker_confirm_resubmit_delete',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484857,'systemBankBranch','maker_prepare_close_delete',8);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484858,'systemBankBranch','list_pagination',9);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484859,'systemBankBranch','checker_search_list_systemBankBranch',9);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51484860,'systemBankBranch','checker_list_pagination',9);
	
	
	
------------------------------------------------
--- System Bank and Branches Transaction Entries
------------------------------------------------

	
INSERT INTO ABCLIMS.TRANSACTION (TRANSACTION_ID	,FROM_STATE,USER_ID,LOGIN_ID,TRANSACTION_TYPE,CREATION_DATE,TRANSACTION_DATE
,REFERENCE_ID,STATUS,STAGING_REFERENCE_ID,TEAM_ID,VERSION,REMARKS,TRX_REFERENCE_ID,OPSDESC,LEGAL_NAME,LEGAL_ID
,CUSTOMER_NAME,CUSTOMER_ID,TRX_ORIGIN_COUNTRY,TRX_ORIGIN_ORGANISATION,LIMIT_PROFILE_ID,LIMIT_PROFILE_REF_NUM,TRX_SEGMENT
,USER_INFO,CUR_TRX_HISTORY_ID,TEAM_TYPE_ID,TRANSACTION_SUBTYPE,TO_GROUP_TYPE_ID,TO_GROUP_ID,TO_USER_ID,DEAL_NO,TEAM_MEMBERSHIP_ID)
VALUES('20110131000002155','PENDING_UPDATE',20070101000002,'SA_CHECKER','SYSTEM_BANK_BRANCH','2011-01-21-19.46.42.463000','2011-02-25-12.35.42.950000',1,'ACTIVE',1,20070101000001,1298617542966,'approved',20110131000002155,'CHECKER_APPROVE_UPDATE','','','SA_MAKER',-999999999,'--','--',-999999999,'','--','SA_CHECKER ( SA_CHECKER )','20110225000000434',3,'','-999999999',-999999999,-999999999,'',20070101000002);

INSERT INTO TRANSACTION (TRANSACTION_ID	,FROM_STATE,USER_ID,LOGIN_ID,TRANSACTION_TYPE,CREATION_DATE,TRANSACTION_DATE
,REFERENCE_ID,STATUS,STAGING_REFERENCE_ID,TEAM_ID,VERSION,REMARKS,TRX_REFERENCE_ID,OPSDESC,LEGAL_NAME,LEGAL_ID
,CUSTOMER_NAME,CUSTOMER_ID,TRX_ORIGIN_COUNTRY,TRX_ORIGIN_ORGANISATION,LIMIT_PROFILE_ID,LIMIT_PROFILE_REF_NUM,TRX_SEGMENT
,USER_INFO,CUR_TRX_HISTORY_ID,TEAM_TYPE_ID,TRANSACTION_SUBTYPE,TO_GROUP_TYPE_ID,TO_GROUP_ID,TO_USER_ID,DEAL_NO,TEAM_MEMBERSHIP_ID) 
VALUES('20110131000002154','PENDING_UPDATE',20070101000002,'SA_CHECKER','SYSTEM_BANK','2011-01-31-18.24.10.396000','2011-02-24-11.44.07.681000',1,'ACTIVE',1,20070101000001,1298528047697,'approved',20110131000002154,'CHECKER_APPROVE_UPDATE','','','SA_MAKER',-999999999,'--','--',-999999999,,'--','SA_CHECKER ( SA_CHECKER )','20110224000000398',3,'','-999999999',-999999999,-999999999,'',20070101000002);	