--------------------------------
--- CMS_FUNCTION_ACCESS Entries 
--------------------------------

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000201,'InsuranceCoverage','maker_submit_create_insurance_coverage',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000202,'InsuranceCoverage','prepare_create_insurance_coverage',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000203,'InsuranceCoverage','prepare_maker_submit_edit',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000204,'InsuranceCoverage','prepare_maker_submit_remove',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000205,'InsuranceCoverage','view_insurance_coverage_by_index',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000206,'InsuranceCoverage','checker_approve_edit',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000207,'InsuranceCoverage','checker_edit_read',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000208,'InsuranceCoverage','checker_process_create',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000209,'InsuranceCoverage','checker_process_delete',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000210,'InsuranceCoverage','checker_process_edit',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000211,'InsuranceCoverage','checker_reject_edit',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000212,'InsuranceCoverage','maker_confirm_close',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000213,'InsuranceCoverage','maker_confirm_resubmit_edit',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000214,'InsuranceCoverage','maker_edit_InsuranceCoverage',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000215,'InsuranceCoverage','maker_prepare_close',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000216,'InsuranceCoverage','maker_prepare_close',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000217,'InsuranceCoverage','maker_prepare_resubmit',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000218,'InsuranceCoverage','maker_prepare_resubmit_create',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000219,'InsuranceCoverage','maker_submit_edit',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000220,'InsuranceCoverage','maker_submit_remove',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000221,'InsuranceCoverage','rejected_delete_read',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000222,'InsuranceCoverage','rejected_delete_read',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000223,'InsuranceCoverage','rejected_read',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000224,'InsuranceCoverage','search_insurance_coverage',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000225,'InsuranceCoverage','view_insurance_coverage',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000226,'InsuranceCoverage','maker_save_create_insurance_coverage',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000227,'InsuranceCoverage','maker_update_save_process',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000228,'InsuranceCoverage', 'maker_draft_close_process',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000229,'InsuranceCoverage', 'maker_confirm_draft_close',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000230,'InsuranceCoverage', 'maker_confirm_resubmit_draft',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000231,'InsuranceCoverage', 'maker_save_update_insurance_coverage',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000232,'InsuranceCoverage', 'maker_save_process',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000233,'InsuranceCoverage', 'maker_confirm_resubmit_update',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000234,'InsuranceCoverage', 'maker_update_save_process',6);

	

-----------------------------------
--- CMS_STATEMATRIX_ACTION Entries 
-----------------------------------

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9201,6,'Process','InsuranceCoverage.do?event=maker_prepare_resubmit&TrxId=','InsuranceCoverage.do?event=to_track&TrxId=');

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9202,7,'Process','InsuranceCoverage.do?event=checker_process_create&TrxId=',null);

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9206,7,'Process','InsuranceCoverage.do?event=checker_edit_read&TrxId=',null);

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9207,6,'Process','InsuranceCoverage.do?event=maker_prepare_resubmit_create&TrxId=',null);

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9208,6,'Process','InsuranceCoverage.do?event=maker_prepare_resubmit_create&TrxId=',null);

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9211,6,'Close','InsuranceCoverage.do?event=maker_prepare_close&TrxId=',null);

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9213,7,'Process','InsuranceCoverage.do?event=checker_process_delete&TrxId=',null);

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9216,7,'Process','InsuranceCoverage.do?event=checker_process_edit&TrxId=','InsuranceCoverage.do?event=to_track&TrxId=');


insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9230,6,'Process','InsuranceCoverage.do?event=maker_save_process&TrxId=','InsuranceCoverage.do?event=to_track&TrxId=');

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9231,6,'Process','InsuranceCoverage.do?event=maker_update_save_process&TrxId=','InsuranceCoverage.do?event=to_track&TrxId=');

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9234,6,'Close','InsuranceCoverage.do?event=maker_draft_close_process&TrxId=','InsuranceCoverage.do?event=to_track&TrxId=');

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9236,6,'Process','InsuranceCoverage.do?event=maker_update_save_process&TrxId=','InsuranceCoverage.do?event=to_track&TrxId=');


-----------------------------------
--- CMS_TRX_TOTRACK Entries 
-----------------------------------

insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values ('INSURANCE_COVERAGE','InsuranceCoverage.do?event=rejected_delete_read&toTrack=yes&TrxId=','DELETED','Deleted','Maintain Insurance Coverage',null,null);

insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values ('INSURANCE_COVERAGE','InsuranceCoverage.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_CREATE','Pending Create','Maintain Insurance Coverage',null,null);

insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values ('INSURANCE_COVERAGE','InsuranceCoverage.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_DELETE','Pending Delete','Maintain Insurance Coverage',null,null);

insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values ('INSURANCE_COVERAGE','InsuranceCoverage.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_UPDATE','Pending Update','Maintain Insurance Coverage',null,null);

insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values ('INSURANCE_COVERAGE','InsuranceCoverage.do?event=rejected_delete_read&toTrack=yes&TrxId=','REJECTED','Rejected','Maintain Insurance Coverage',null,null);

insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values('INSURANCE_COVERAGE','InsuranceCoverage.do?event=rejected_delete_read&toTrack=yes&TrxId=','DRAFT','Draft','Maintain Insurance Coverage',null,null);


-----------------------------------
--- TR_STATE_MATRIX Entries 
-----------------------------------

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9201,'INSURANCE_COVERAGE','EDIT_REJECTED_DELETE','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9202,'INSURANCE_COVERAGE','CREATE_INSURANCE_COVERAGE','PENDING_CREATE','PENDING_CREATE','PENDING_CREATE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9203,'INSURANCE_COVERAGE','APROVE_INSURANCE_COVERAGE','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9204,'INSURANCE_COVERAGE','UPDATE_INSURANCE_COVERAGE','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9205,'INSURANCE_COVERAGE','APPROVE_CREATE_INSURANCE_COVERAGE','PENDING_CREATE','ACTIVE','ACTIVE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9206,'INSURANCE_COVERAGE','REJECT_INSURANCE_COVERAGE','PENDING_UPDATE','REJECTED','REJECTED','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9207,'INSURANCE_COVERAGE','EDIT_REJECTED_UPDATE_INSURANCE_COVERAGE','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9208,'INSURANCE_COVERAGE','CLOSE_REJECTED_UPDATE_INSURANCE_COVERAGE','REJECTED','CLOSED','CLOSED','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9209,'INSURANCE_COVERAGE','REJECT_INSURANCE_COVERAGE','PENDING_CREATE','REJECTED','REJECTED','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9210,'INSURANCE_COVERAGE','CLOSE_REJECTED_CREATE_INSURANCE_COVERAGE','REJECTED','CLOSED','CLOSED','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9211,'INSURANCE_COVERAGE','EDIT_REJECTED_CREATE_INSURANCE_COVERAGE','REJECTED','PENDING_CREATE','PENDING_CREATE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9212,'INSURANCE_COVERAGE','DELETE_INSURANCE_COVERAGE','ACTIVE','PENDING_DELETE','PENDING_DELETE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9213,'INSURANCE_COVERAGE','DELETE_INSURANCE_COVERAGE','PENDING_DELETE','DELETED','DELETED','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9214,'INSURANCE_COVERAGE','REJECT_INSURANCE_COVERAGE','PENDING_DELETE','REJECTED','REJECTED','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9215,'INSURANCE_COVERAGE','CLOSE_REJECTED_INSURANCE_COVERAGE','REJECTED','CLOSED','CLOSED','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9216,'INSURANCE_COVERAGE','UPDATE_INSURANCE_COVERAGE','PENDING_UPDATE','ACTIVE','PENDING_UPDATE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9217,'INSURANCE_COVERAGE','CHECKER_APPROVE_UPDATE','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9218,'INSURANCE_COVERAGE','CHECKER_APPROVE_DELETE','PENDING_DELETE','DELETED','DELETED','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9219,'INSURANCE_COVERAGE','APPROVE_INSURANCE_COVERAGE','PENDING_DELETE','DELETED','DELETED','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9220,'INSURANCE_COVERAGE','CHECKER_APPROVE_UPDATE','PENDING_DELETE','DELETED','DELETED','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9221,'INSURANCE_COVERAGE','CREATE_INSURANCE_COVERAGE','ND','PENDING_CREATE','PENDING_CREATE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9222,'INSURANCE_COVERAGE','CLOSE_REJECTED_DELETE_INSURANCE_COVERAGE','REJECTED','CLOSED','CLOSED','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9223,'INSURANCE_COVERAGE','DELETE_INSURANCE_COVERAGE','CLOSED','PENDING_DELETE','PENDING_DELETE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9224,'INSURANCE_COVERAGE','APPROVE_DELETE_INSURANCE_COVERAGE','PENDING_DELETE','DELETED','DELETED','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9225,'INSURANCE_COVERAGE','CREATE_INSURANCE_COVERAGE','ACTIVE','PENDING_CREATE','PENDING_CREATE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9226,'INSURANCE_COVERAGE','EDIT_REJECTED_DELETE_INSURANCE_COVERAGE','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9227,'INSURANCE_COVERAGE','EDIT_REJECTED_INSURANCE_COVERAGE','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9228,'INSURANCE_COVERAGE','EDIT_REJECTED_INSURANCE_COVERAGE','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9229,'INSURANCE_COVERAGE','EDIT_REJECTED_DELETE','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9230,'INSURANCE_COVERAGE','UPDATE_INSURANCE_COVERAGE','CLOSED','PENDING_UPDATE','PENDING_UPDATE','1','1');


insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9231,'INSURANCE_COVERAGE','SAVE_INSURANCE_COVERAGE','PENDING_PERFECTION','DRAFT','DRAFT','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9232,'INSURANCE_COVERAGE','CREATE_INSURANCE_COVERAGE','DRAFT','PENDING_CREATE','PENDING_CREATE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9233,'INSURANCE_COVERAGE','MAKER_UPDATE_SAVE','ACTIVE','DRAFT','DRAFT','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9234,'INSURANCE_COVERAGE','UPDATE_INSURANCE_COVERAGE','DRAFT','PENDING_UPDATE','PENDING_UPDATE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9235,'INSURANCE_COVERAGE','MAKER_UPDATE_CLOSE','DRAFT','ACTIVE','ACTIVE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9236,'INSURANCE_COVERAGE','CLOSE_CREATE_INSURANCE_COVERAGE','DRAFT','CLOSED','CLOSED','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9237,'INSURANCE_COVERAGE','SAVE_UPDATE_INSURANCE_COVERAGE','ACTIVE','DRAFT','DRAFT','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9238,'INSURANCE_COVERAGE','SAVE_UPDATE_INSURANCE_COVERAGE','CLOSED','DRAFT','DRAFT','1','1');