@echo off

REM Establish connection
rem db2 ACTIVATE DATABASE %DB_NAME%

db2 CONNECT TO %DB_NAME% USER %DB_USER% USING %DB_PASSWD%

db2 set CURRENT SCHEMA = %DB_SCHEMA%

db2 set CURRENT PATH = SYSIBM,SYSFUN,SYSPROC,SYSIBMADM,%DB_SCHEMA%