@echo off

call ..\setenv.cmd
call ..\connect.cmd

echo -------------------------------------
echo %date% - %time% Reorg Table ...

echo %date% - %time% Reorg: Customer Information ...
db2 REORG TABLE MIG_CU001_CU

echo %date% - %time% Reorg: Credit Application Information ...
db2 REORG TABLE MIG_CA001_AA

echo %date% - %time% Reorg: Credit CA - Joint Borrowers Info ...
db2 REORG TABLE MIG_CA002_JB

echo %date% - %time% Reorg: Credit Facility Master ...
db2 REORG TABLE MIG_CA003_1

echo %date% - %time% Reorg: Credit Facility BNM ...
db2 REORG TABLE MIG_CA003_2_BNM

echo %date% - %time% Reorg: Credit Facility Officer ...
db2 REORG TABLE MIG_CA003_3_OFF

echo %date% - %time% Reorg: Credit Facility Relationship ...
db2 REORG TABLE MIG_CA003_4_REL

echo %date% - %time% Reorg: Credit Facility Insurance ...
db2 REORG TABLE MIG_CA003_5_INS

echo %date% - %time% Reorg: Credit Facility Multi Tier Financing ...
db2 REORG TABLE MIG_CA003_6_MUL

echo %date% - %time% Reorg: Credit Facility Islamic Master ...
db2 REORG TABLE MIG_CA003_7_ISL

echo %date% - %time% Reorg: Credit Facility BBA Vari Package ...
db2 REORG TABLE MIG_CA003_8_BBA

echo %date% - %time% Reorg: CA - Limit Account Info ...
db2 REORG TABLE MIG_CA004


echo %date% - %time% Reorg: Collateral Asset Based - Vehicle, Plant and Equipment ...
db2 REORG TABLE MIG_CO001_AB

echo %date% - %time% Reorg: Collateral Asset Based - Gold ...
db2 REORG TABLE MIG_CO002_AB_GOLD

echo %date% - %time% Reorg: Collateral Deposit ...
db2 REORG TABLE MIG_CO005_CS

echo %date% - %time% Reorg: Collateral - Marketable Security - Stocks ...
db2 REORG TABLE MIG_CO008_MS

echo %date% - %time% Reorg: Collateral Property ...
db2 REORG TABLE MIG_CO009_PT

echo %date% - %time% Rusntat: Collateral Guarantees ...
db2 REORG TABLE MIG_CO010_GT

echo %date% - %time% Reorg: Collateral Others ...
db2 REORG TABLE MIG_CO011_OT

echo %date% - %time% Reorg: Collateral Insurance Protection ...
db2 REORG TABLE MIG_CO012_IN

echo %date% - %time% Reorg: Collateral Clean ...
db2 REORG TABLE MIG_CO014_CL

echo %date% - %time% Reorg: Collateral Valuation Detail ...
db2 REORG TABLE MIG_CO015_VL

echo %date% - %time% Reorg: Collateral Insurance Policy Detail ...
db2 REORG TABLE MIG_CO016_IN

echo %date% - %time% Reorg: Collateral Charge Detail ...
db2 REORG TABLE MIG_CO017_CD

echo %date% - %time% Reorg: Collateral Pledgor Detail ...
db2 REORG TABLE MIG_CO018_PG

echo %date% - %time% Reorg: Collateral Pledge Information ...
db2 REORG TABLE MIG_CO019_PL


echo %date% - %time% Reorg: Limit ...
db2 REORG TABLE SCI_LSP_APPR_LMTS

echo %date% - %time% Reorg: Pledgor ...
db2 REORG TABLE SCI_PLEDGOR_DTL

echo %date% - %time% Reorg: Stage Plegor ...
db2 REORG TABLE STAGE_PLEDGOR_DTL

echo %date% - %time% Reorg: Security ...
db2 REORG TABLE CMS_SECURITY

echo %date% - %time% Reorg: Stage Security ...
db2 REORG TABLE CMS_STAGE_SECURITY

echo %date% - %time% Reorg: Security Sub Type ...
db2 REORG TABLE CMS_SECURITY_SUB_TYPE

echo %date% - %time% Reorg: Charge Detail ...
db2 REORG TABLE CMS_CHARGE_DETAIL

echo %date% - %time% Reorg: Stage Charge Detail ...
db2 REORG TABLE CMS_STAGE_CHARGE_DETAIL

echo %date% - %time% Reorg: Portfolio Item ...
db2 REORG TABLE CMS_PORTFOLIO_ITEM

echo %date% - %time% Reorg: Stage Portfolio Item ...
db2 REORG TABLE CMS_STAGE_PORTFOLIO_ITEM

echo %date% - %time% Reorg: Price Feed ...
db2 REORG TABLE CMS_PRICE_FEED

echo %date% - %time% Reorg: Limit Security Map ...
db2 REORG TABLE CMS_LIMIT_SECURITY_MAP

echo %date% - %time% Reorg: Stage Limit Security Map ...
db2 REORG TABLE CMS_STAGE_LIMIT_SECURITY_MAP

echo %date% - %time% Reorg: Facility Master ...
db2 REORG TABLE CMS_FACILITY_MASTER

echo %date% - %time% Reorg: Facility Officer ...
db2 REORG TABLE CMS_FAC_OFFICER

echo %date% - %time% Reorg: Fac Relationship ...
db2 REORG TABLE CMS_FAC_RELATIONSHIP

echo %date% - %time% Reorg: Facility Insurance ...
db2 REORG TABLE CMS_FAC_INSURANCE

echo %date% - %time% Reorg: Common Code Category Entry ...
db2 REORG TABLE COMMON_CODE_CATEGORY_ENTRY

echo %date% - %time% Reorg: Transaction ...
db2 REORG TABLE TRANSACTION

echo -------------------------------------
echo %date% - %time% Reorg: Script end.