#!/bin/sh

. ../setenv.sh
. ../connect.sh

echo -------------------------------------
echo `date +"%Y/%m/%d %H:%M:%S"` Reorg Table ...

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Customer Information ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CU001_CU

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Credit Application Information ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CA001_AA

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Credit CA - Joint Borrowers Info ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CA002_JB

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Credit Facility Master ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CA003_1

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Credit Facility BNM ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CA003_2_BNM

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Credit Facility Officer ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CA003_3_OFF

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Credit Facility Relationship ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CA003_4_REL

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Credit Facility Insurance ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CA003_5_INS

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Credit Facility Multi Tier Financing ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CA003_6_MUL

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Credit Facility Islamic Master ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CA003_7_ISL

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Credit Facility BBA Vari Package ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CA003_8_BBA

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: CA - Limit Account Info ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CA004


echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Collateral Asset Based - Vehicle, Plant and Equipment ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CO001_AB

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Collateral Asset Based - Gold ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CO002_AB_GOLD

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Collateral Deposit ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CO005_CS

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Collateral - Marketable Security - Stocks ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CO008_MS

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Collateral Property ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CO009_PT

echo `date +"%Y/%m/%d %H:%M:%S"` Rusntat: Collateral Guarantees ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CO010_GT

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Collateral Others ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CO011_OT

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Collateral Insurance Protection ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CO012_IN

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Collateral Clean ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CO014_CL

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Collateral Valuation Detail ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CO015_VL

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Collateral Insurance Policy Detail ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CO016_IN

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Collateral Charge Detail ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CO017_CD

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Collateral Pledgor Detail ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CO018_PG

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Collateral Pledge Information ...
"$DB2_HOME"/bin/db2 REORG TABLE MIG_CO019_PL


echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Customer ...
"$DB2_HOME"/bin/db2 REORG TABLE SCI_LE_MAIN_PROFILE

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Customer Sub ...
"$DB2_HOME"/bin/db2 REORG TABLE SCI_LE_SUB_PROFILE

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Limit ...
"$DB2_HOME"/bin/db2 REORG TABLE SCI_LSP_APPR_LMTS

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Pledgor ...
"$DB2_HOME"/bin/db2 REORG TABLE SCI_PLEDGOR_DTL

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Stage Plegor ...
"$DB2_HOME"/bin/db2 REORG TABLE STAGE_PLEDGOR_DTL

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Security ...
"$DB2_HOME"/bin/db2 REORG TABLE CMS_SECURITY

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Stage Security ...
"$DB2_HOME"/bin/db2 REORG TABLE CMS_STAGE_SECURITY

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Security Sub Type ...
"$DB2_HOME"/bin/db2 REORG TABLE CMS_SECURITY_SUB_TYPE

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Charge Detail ...
"$DB2_HOME"/bin/db2 REORG TABLE CMS_CHARGE_DETAIL

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Stage Charge Detail ...
"$DB2_HOME"/bin/db2 REORG TABLE CMS_STAGE_CHARGE_DETAIL

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Portfolio Item ...
"$DB2_HOME"/bin/db2 REORG TABLE CMS_PORTFOLIO_ITEM

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Stage Portfolio Item ...
"$DB2_HOME"/bin/db2 REORG TABLE CMS_STAGE_PORTFOLIO_ITEM

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Price Feed ...
"$DB2_HOME"/bin/db2 REORG TABLE CMS_PRICE_FEED

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Limit Security Map ...
"$DB2_HOME"/bin/db2 REORG TABLE CMS_LIMIT_SECURITY_MAP

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Stage Limit Security Map ...
"$DB2_HOME"/bin/db2 REORG TABLE CMS_STAGE_LIMIT_SECURITY_MAP

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Facility Master ...
"$DB2_HOME"/bin/db2 REORG TABLE CMS_FACILITY_MASTER

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Facility Officer ...
"$DB2_HOME"/bin/db2 REORG TABLE CMS_FAC_OFFICER

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Fac Relationship ...
"$DB2_HOME"/bin/db2 REORG TABLE CMS_FAC_RELATIONSHIP

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Facility Insurance ...
"$DB2_HOME"/bin/db2 REORG TABLE CMS_FAC_INSURANCE

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Common Code Category Entry ...
"$DB2_HOME"/bin/db2 REORG TABLE COMMON_CODE_CATEGORY_ENTRY

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Transaction ...
"$DB2_HOME"/bin/db2 REORG TABLE TRANSACTION

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: STP Master Transaction ...
"$DB2_HOME"/bin/db2 REORG TABLE STP_TRANS

echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: STP Transaction ...
"$DB2_HOME"/bin/db2 REORG TABLE STP_MASTER_TRANS

echo -------------------------------------
echo `date +"%Y/%m/%d %H:%M:%S"` Reorg: Script end.