#!/bin/sh
DB2_HOME=/opt/IBM/db2/V9.1
. ../setenv.sh

echo "-------------------------------------"
/opt/IBM/db2/V9.1/bin/db2 drop database $DB_NAME

/opt/IBM/db2/V9.1/bin/db2 "create database $DB_NAME ON /data/EONCMS using codeset utf-8 territory us CATALOG TABLESPACE MANAGED BY DATABASE using ( FILE '/data/EONCMS/CATALOG.DAT' 125000) TEMPORARY TABLESPACE MANAGED BY SYSTEM using ( '/data/EONCMS/TEMPTS') USER TABLESPACE MANAGED BY DATABASE using ( FILE '/data/EONCMS/USERTTS.DAT' 50000 )"

/opt/IBM/db2/V9.1/bin/db2 connect to $DB_NAME user "eoncms" using "eoncms"

/opt/IBM/db2/V9.1/bin/db2 create schema $DB_NAME

echo `date +"%Y/%m/%d %H:%M:%S"` "Restore database in progress ... "
"$DB2_HOME"/bin/db2 "RESTORE DATABASE EONCMS FROM /data/eoncms_scripts/restore TAKEN AT 20090412143422 ON /data/EONCMS DBPATH ON /data/EONCMS INTO EONCMS WITH 2 BUFFERS BUFFER 1024 REDIRECT PARALLELISM 1 WITHOUT PROMPTING"
"$DB2_HOME"/bin/db2 "SET TABLESPACE CONTAINERS FOR 3 IGNORE ROLLFORWARD CONTAINER OPERATIONS USING (FILE '/data/EONCMS/CMS_SMALL_DATA' 2530000)"
"$DB2_HOME"/bin/db2 "SET TABLESPACE CONTAINERS FOR 4 IGNORE ROLLFORWARD CONTAINER OPERATIONS USING (FILE '/data/EONCMS/CMS_DATA' 165000)"
"$DB2_HOME"/bin/db2 "SET TABLESPACE CONTAINERS FOR 5 IGNORE ROLLFORWARD CONTAINER OPERATIONS USING (FILE '/data/EONCMS/CMS_MEDIUM_DATA' 25000)"
"$DB2_HOME"/bin/db2 "SET TABLESPACE CONTAINERS FOR 6 IGNORE ROLLFORWARD CONTAINER OPERATIONS USING (FILE '/data/EONCMS/CMS_LARGE_DATA' 2000)"
"$DB2_HOME"/bin/db2 "SET TABLESPACE CONTAINERS FOR 7 IGNORE ROLLFORWARD CONTAINER OPERATIONS USING (FILE '/data/EONCMS/CMS_INDEX' 960000)"
"$DB2_HOME"/bin/db2 "SET TABLESPACE CONTAINERS FOR 8 IGNORE ROLLFORWARD CONTAINER OPERATIONS USING (FILE '/data/EONCMS/CMS_BATCH' 72500)"
"$DB2_HOME"/bin/db2 "SET TABLESPACE CONTAINERS FOR 9 IGNORE ROLLFORWARD CONTAINER OPERATIONS USING (FILE '/data/EONCMS/CMS_BATCH_INDEX' 100000)"
"$DB2_HOME"/bin/db2 "SET TABLESPACE CONTAINERS FOR 12 IGNORE ROLLFORWARD CONTAINER OPERATIONS USING (FILE '/data/EONCMS/CMS_STP' 45000)"
"$DB2_HOME"/bin/db2 "SET TABLESPACE CONTAINERS FOR 13 IGNORE ROLLFORWARD CONTAINER OPERATIONS USING (FILE '/data/EONCMS/CMS_STP_INDEX' 68000)"
"$DB2_HOME"/bin/db2 "SET TABLESPACE CONTAINERS FOR 14 IGNORE ROLLFORWARD CONTAINER OPERATIONS USING (FILE '/data/EONCMS/CMS_AUDIT_DATA' 50000)"
"$DB2_HOME"/bin/db2 "SET TABLESPACE CONTAINERS FOR 17 IGNORE ROLLFORWARD CONTAINER OPERATIONS USING (FILE '/data/EONCMS/CMS_MIGRATION.dat' 1000000)"
"$DB2_HOME"/bin/db2 "SET TABLESPACE CONTAINERS FOR 18 IGNORE ROLLFORWARD CONTAINER OPERATIONS USING (FILE '/data/EONCMS/CMS_MIGRATION_INDEX.dat' 200000)"
"$DB2_HOME"/bin/db2 RESTORE DATABASE $DB_NAME CONTINUE

echo "-------------------------------------"
echo `date +"%Y/%m/%d %H:%M:%S"` "Restore process completed."