------------------------
-- QC Report Table 
------------------------
DROP TABLE MAN_MIG_QC_REPORT;

CREATE TABLE MAN_MIG_QC_REPORT(
    MIG_ID	BIGINT	NOT NULL	GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE, NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
    RECORD_TYPE VARCHAR(30),
    TEXT  VARCHAR(2000),
    SYSTEM_ID VARCHAR(4),
    INTERFACE_ID	VARCHAR(5)
)  IN CMS_MIG;

