LOAD DATA
INFILE 'FILES\Currency master.csv'
 "str '~~~'"
BADFILE 'PARTIAL_ERROR_LOG\Currency master.bad'
DISCARDFILE 'PARTIAL_ERROR_LOG\Currency master.dsc'
DISCARDMAX 1241513983
APPEND INTO TABLE MIG_CMS_FOREX
FIELDS TERMINATED BY '|||'
TRAILING NULLCOLS
(
CCYMBCODE "REPLACE(REPLACE(:CCYMBCODE, CHR(10),''), CHR(13),'')",
  CCYCODE,
  CCYDESC,
  CCYRATE
)
