drop table MIG_AB111;

drop table MIG_AB111_ERR;

drop table MIG_CHARGE_AB111;

drop table MIG_CHARGE_AB111_ERR;

drop table MIG_PLEDGOR_AB111;

drop table MIG_PLEDGOR_AB111_ERR;

drop table MIG_VAL_AB111;

drop table MIG_VAL_AB111_ERR;


CREATE TABLE MIG_AB111 (
	CIF_NUMBER VARCHAR(20),
	FAC_DESC VARCHAR(40),
	SOURCE_SECURITY_ID VARCHAR(19) NOT NULL,
	SECURITY_TYPE VARCHAR(40) DEFAULT 'Asset Based',
	SECURITY_SUB_TYPE VARCHAR(80) DEFAULT 'Vessel',
	SECURITY_TYPE_ID CHAR(2) DEFAULT 'AB',
	SECURITY_SUB_TYPE_ID VARCHAR(5) DEFAULT 'AB111',
	SECURITY_CURRENCY CHAR(3),
	SECURITY_LOCATION CHAR(2) DEFAULT 'MY',
	SECURITY_ORGANISATION VARCHAR(60),
	SECURITY_ORGANISATION_CODE VARCHAR(10),	
	SECURITY_CUSTODIAN_TYPE VARCHAR(10) DEFAULT 'I',
	CUSTODIAN_TYPE_CODE CHAR(1),
	SECURITY_CUSTODIAN_VALUE VARCHAR(100),
	CUSTODIAN_VALUE_CODE VARCHAR(10),
	SECURITY_MATURITY_DATE TIMESTAMP,
	SECURITY_PERFECTION_DATE TIMESTAMP,
	LEGAL_ENFORCEABILITY_IND CHAR(1),
	LEGAL_ENFORCEABILITY_DATE TIMESTAMP,
	SECURITY_REF_NOTE VARCHAR(2500),
	EXCHANGE_CONTROL_OBTAINED CHAR(1) DEFAULT 'N',
	PHYSICAL_INSPECTION_IND CHAR(1),
	LAST_PHYSICAL_INSPECTION_DATE TIMESTAMP,
	NEXT_PHYSICAL_INSPECTION_DATE TIMESTAMP,
	PHYSICAL_INSPECTION_FREQ_UNIT VARCHAR(10),
	PHYSICAL_INSPECTION_FREQ_UOM VARCHAR(2),	
	SEC_ENVIRONMENTAL_RISKY_IND CHAR(2) DEFAULT 'NA',
	DATE_SEC_CONFIRM_ENV_RISKY TIMESTAMP,
	REMARKS_SEC_ENV_RISKY VARCHAR(250),
	ASSET_TYPE VARCHAR(60),
	BUILT_YEAR INT,
	PURCHASE_PRICE DECIMAL(17,2),
	PURCHASE_DATE TIMESTAMP,
	INSURER VARCHAR(100),
	VESSEL_NAME VARCHAR(60),
	FLAG_REGISTERED CHAR(2),
	VESSEL_STATE VARCHAR(20),
	EXPECTED_OCCUPANCY_DATE TIMESTAMP,
	EXPECTED_OCCUPANCY VARCHAR(60),
	OCCUPANCY_TYPE VARCHAR(15),
	BUILDER VARCHAR(60),
	MAIN_REGISTRATION VARCHAR(40),
	LENGTH VARCHAR(40),
	WIDTH VARCHAR(40),
	DEPTH VARCHAR(40),
	DECK_LOADING VARCHAR(40),
	DECK_WEIGHT VARCHAR(40),
	SIDE_BOARD VARCHAR(40),
	BOW VARCHAR(40),
	DECK VARCHAR(40),
	DECK_THICKNESS VARCHAR(40),
	BOTTOM VARCHAR(40),
	WINCH_DRIVE VARCHAR(40),
	BHP VARCHAR(40),
	SPEED VARCHAR(40),
	ANCHOR VARCHAR(40),
	ANCHOR_DRIVE VARCHAR(40),
	CLASS_SOCIETY VARCHAR(40),
	CONSTRUCTION_COUNTRY CHAR(2),
	CONSTRUCTION_PLACE VARCHAR(40),
	VESSEL_USE VARCHAR(60),
	CHARTER_CONTRACT CHAR(1),
	CHARTERER_NAME VARCHAR(40),
	CHARTER_PERIOD INT,
	CHARTER_PERIOD_UOM VARCHAR(10),
	CHARTER_AMT DECIMAL(17,2),
	CHARTER_CCY CHAR(3),
	CHARTER_RATE VARCHAR(10),
	CHARTER_RATE_OTHERS VARCHAR(40),
	CHARTER_REMARKS VARCHAR(2000),
	ASSET_DESC VARCHAR(250),
	CMS_COLLATERAL_STG_ID BIGINT,
	CMS_COLLATERAL_ID BIGINT,
	SOURCE_ID VARCHAR(10),
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	VALID_IND CHAR(1) DEFAULT 'Y'
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "MIG_AB111" 
	ADD CONSTRAINT "MIG_AB111_U" UNIQUE
		("SOURCE_SECURITY_ID",
		 "REGION");

CREATE TABLE MIG_AB111_ERR LIKE MIG_AB111
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE MIG_AB111_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE MIG_AB111_ERR
  ADD REASON	CLOB;
  

-- CHARGE
CREATE TABLE MIG_CHARGE_AB111 (
	SOURCE_SECURITY_ID VARCHAR(19) NOT NULL,
	SOURCE_LIMIT_ID VARCHAR(20) NOT NULL,
	SECURITY_RANKING INT NOT NULL,
	CHARGE_TYPE CHAR(10) DEFAULT 'G',
	NATURE_OF_CHARGE VARCHAR(60),
	CHARGE_CURRENCY CHAR(3),
	CHARGE_AMT DECIMAL(20,2),
	DATE_LEGALLY_CHARGE TIMESTAMP,
	PRIOR_CHARGEE VARCHAR(100),
	PRIOR_CHARGE_TYPE VARCHAR(10),
	PRIOR_CHARGE_CCY CHAR(3),
	PRIOR_CHARGE_AMT DECIMAL(20,2),
	SOURCE_ID VARCHAR(10),
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	VALID_IND CHAR(1) DEFAULT 'Y',
	VALID_CHARGE_IND CHAR(1) DEFAULT 'Y',
	CHARGE_TYPE_CODE VARCHAR(10),
	NATURE_OF_CHARGE_CODE VARCHAR(10),
	CMS_ACT_CHARGE_ID BIGINT, 
	CMS_ACT_LMT_ID BIGINT,
	CMS_STG_CHARGE_ID BIGINT,
	CMS_ACT_LMT_PROFILE_ID BIGINT,
	CMS_ACT_DTL_ID BIGINT, 
	CMS_STG_DTL_ID BIGINT,
	PRIOR_CHARGE_TYPE_CODE VARCHAR(10)
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "MIG_CHARGE_AB111" 
	ADD CONSTRAINT "MIG_CHARGE_AB111_U" UNIQUE
		("SOURCE_LIMIT_ID",
		 "SOURCE_SECURITY_ID",
		 "SECURITY_RANKING",
		 "REGION");

CREATE TABLE MIG_CHARGE_AB111_ERR LIKE MIG_CHARGE_AB111
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE MIG_CHARGE_AB111_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE MIG_CHARGE_AB111_ERR
  ADD REASON	CLOB;
  
-- PLEDGOR
CREATE TABLE MIG_PLEDGOR_AB111 (
	CIF_NUMBER VARCHAR(20) NOT NULL,
	SOURCE_LIMIT_ID VARCHAR(20) NOT NULL,
	SOURCE_SECURITY_ID VARCHAR(19) NOT NULL,
	IS_BORROWER_PLEDGOR CHAR(1), 
	CIF_PLEDGOR1 VARCHAR(19),
	CIF_PLEDGOR2 VARCHAR(19),
	CIF_PLEDGOR3 VARCHAR(19),
	CIF_PLEDGOR4 VARCHAR(19),
	CMS_PLEDGOR_ID BIGINT,
	CMS_PLEDGOR1_ID BIGINT,
	CMS_PLEDGOR2_ID BIGINT,
	CMS_PLEDGOR3_ID BIGINT,
	CMS_PLEDGOR4_ID BIGINT,
	SOURCE_ID VARCHAR(10),
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	IS_BRRW_PLGR_IND CHAR(1) DEFAULT 'Y',
	CIF_PLEDGOR1_IND CHAR(1) DEFAULT 'Y',
	CIF_PLEDGOR2_IND CHAR(1) DEFAULT 'Y',
	CIF_PLEDGOR3_IND CHAR(1) DEFAULT 'Y',
	CIF_PLEDGOR4_IND CHAR(1) DEFAULT 'Y'
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "MIG_PLEDGOR_AB111" 
	ADD CONSTRAINT "MIG_PGR_AB111_U" UNIQUE
		("CIF_NUMBER",
		 "SOURCE_LIMIT_ID",
		 "SOURCE_SECURITY_ID",
		 "REGION");

CREATE TABLE MIG_PLEDGOR_AB111_ERR LIKE MIG_PLEDGOR_AB111
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE MIG_PLEDGOR_AB111_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE MIG_PLEDGOR_AB111_ERR
  ADD REASON	CLOB;


CREATE TABLE MIG_VAL_AB111 (
	SOURCE_SECURITY_ID VARCHAR(19) NOT NULL,
	VALUATION_DATE TIMESTAMP NOT NULL,
	VALUATION_CCY CHAR(3),
	VALUATION_OMV DECIMAL(17,2) NOT NULL,
	VALUER VARCHAR(200),
	VALUER_CODE VARCHAR(10),
	VALUATION_FSV DECIMAL(17,2),
	COMMENTS VARCHAR(250),
	RESERVE_PRICE DECIMAL(17,2),
	RESERVE_PRICE_DATE TIMESTAMP,
	VALUATION_ID BIGINT,
	VALUATION_STG_ID BIGINT,
	SOURCE_ID VARCHAR(10),
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	VALID_IND CHAR(1) DEFAULT 'Y'
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "MIG_VAL_AB111" 
	ADD CONSTRAINT "MIG_VAL_AB111_U" UNIQUE
		("SOURCE_SECURITY_ID",
		 "VALUATION_DATE",
		 "VALUATION_OMV",
		 "REGION");

CREATE TABLE MIG_VAL_AB111_ERR LIKE MIG_VAL_AB111
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE MIG_VAL_AB111_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE MIG_VAL_AB111_ERR
  ADD REASON	CLOB;