update CMS_FAC_INTEREST set SPREAD_SIGN = null where length(SPREAD_SIGN) = 0;

update CMS_STG_FAC_INTEREST set SPREAD_SIGN = null where length(SPREAD_SIGN) = 0;

update CMS_FAC_INTEREST set INTEREST_MODE = null where length(INTEREST_MODE) = 0;

update CMS_STG_FAC_INTEREST set INTEREST_MODE = null where length(INTEREST_MODE) = 0;

update CMS_FAC_ISLAMIC_MASTER set GPP_DURATION_FOR_SNP = null where length(GPP_DURATION_FOR_SNP) = 0;

update CMS_STG_FAC_ISLAMIC_MASTER set GPP_DURATION_FOR_SNP = null where length(GPP_DURATION_FOR_SNP) = 0;

update CMS_FAC_ISLAMIC_MASTER set GPP_TERM_CODE = null where length(GPP_TERM_CODE) = 0;

update CMS_STG_FAC_ISLAMIC_MASTER set GPP_TERM_CODE = null where length(GPP_TERM_CODE) = 0;

update CMS_FAC_BBA_VARI_PACKAGE set REBATE_METHOD = null where length(REBATE_METHOD) = 0;

update CMS_STG_FAC_BBA_VARI_PACKAGE set REBATE_METHOD = null where length(REBATE_METHOD) = 0;

update CMS_FAC_BBA_VARI_PACKAGE set GPP_TERM_CODE = null where length(GPP_TERM_CODE) = 0;

update CMS_STG_FAC_BBA_VARI_PACKAGE set GPP_TERM_CODE = null where length(GPP_TERM_CODE) = 0;

update CMS_FAC_BBA_VARI_PACKAGE set REFUND_FULL_RELEASE_PROFIT = null where length(REFUND_FULL_RELEASE_PROFIT) = 0;

update CMS_STG_FAC_BBA_VARI_PACKAGE set REFUND_FULL_RELEASE_PROFIT = null where length(REFUND_FULL_RELEASE_PROFIT) = 0;

update CMS_FAC_BBA_VARI_PACKAGE set FUL_REL_PROFIT_CAL_METHOD = null where length(FUL_REL_PROFIT_CAL_METHOD) = 0;

update CMS_STG_FAC_BBA_VARI_PACKAGE set FUL_REL_PROFIT_CAL_METHOD = null where length(FUL_REL_PROFIT_CAL_METHOD) = 0;

update CMS_FAC_INSURANCE set ARRANGEMENT_IND = null where length(ARRANGEMENT_IND) = 0;

update CMS_STG_FAC_INSURANCE set ARRANGEMENT_IND = null where length(ARRANGEMENT_IND) = 0;

update CMS_FAC_RELATIONSHIP set GUARANTEE_TYPE_IND = null where length(GUARANTEE_TYPE_IND) = 0;

update CMS_STG_FAC_RELATIONSHIP set GUARANTEE_TYPE_IND = null where length(GUARANTEE_TYPE_IND) = 0;

update CMS_FAC_RELATIONSHIP set NAME_CONJUNCTION_POSITION = null where length(NAME_CONJUNCTION_POSITION) = 0;

update CMS_STG_FAC_RELATIONSHIP set NAME_CONJUNCTION_POSITION = null where length(NAME_CONJUNCTION_POSITION) = 0;

update CMS_FAC_MULTI_TIER_FINANCING set TIER_TERM_CODE = null where length(TIER_TERM_CODE) = 0;

update CMS_STG_FAC_MULTI_TIER_FINANCING set TIER_TERM_CODE = null where length(TIER_TERM_CODE) = 0;

