drop table MIG_PT;

drop table MIG_PT_ERR;

drop table MIG_CHARGE_PT;

drop table MIG_CHARGE_PT_ERR;

drop table MIG_PLEDGOR_PT;

drop table MIG_PLEDGOR_PT_ERR;

drop table MIG_VAL_PT;

drop table MIG_VAL_PT_ERR;

CREATE TABLE MIG_PT (
	CIF_NUMBER VARCHAR(20),
	FAC_DESC VARCHAR(40),
	SOURCE_SECURITY_ID VARCHAR(19) NOT NULL,
	SECURITY_TYPE VARCHAR(40),
	SECURITY_SUB_TYPE VARCHAR(80),
	SECURITY_TYPE_ID CHAR(2) DEFAULT 'PT',
	SECURITY_SUB_TYPE_ID VARCHAR(5),
	SECURITY_CURRENCY CHAR(3),
	SECURITY_LOCATION CHAR(2) DEFAULT 'MY',
	SECURITY_ORGANISATION VARCHAR(60),
	SECURITY_ORGANISATION_CODE VARCHAR(10),	
	SECURITY_CUSTODIAN_TYPE VARCHAR(10),
	CUSTODIAN_TYPE_CODE CHAR(1),
	SECURITY_CUSTODIAN_VALUE VARCHAR(100),
	CUSTODIAN_VALUE_CODE VARCHAR(10),
	SECURITY_MATURITY_DATE TIMESTAMP,
	SECURITY_PERFECTION_DATE TIMESTAMP,
	LEGAL_ENFORCEABILITY_IND CHAR(1),
	LEGAL_ENFORCEABILITY_DATE TIMESTAMP,
	SECURITY_REF_NOTE VARCHAR(2500),
	EXCHANGE_CONTROL_OBTAINED CHAR(1),	
	PHYSICAL_INSPECTION_IND CHAR(1) DEFAULT 'N',
	LAST_PHYSICAL_INSPECTION_DATE TIMESTAMP,
	NEXT_PHYSICAL_INSPECTION_DATE TIMESTAMP,
	PHYSICAL_INSPECTION_FREQ_UNIT INT,
	PHYSICAL_INSPECTION_FREQ_UOM VARCHAR(2),
	SEC_ENVIRONMENTAL_RISKY_IND CHAR(2) DEFAULT 'NA',
	DATE_SEC_CONFIRM_ENV_RISKY TIMESTAMP,
	REMARKS_SEC_ENV_RISKY VARCHAR(250),
	ASSET_DESC VARCHAR(250),
	SALES_PURCHASE_AGREEMENT_VALUE DECIMAL(15,2),
	TITLE_TYPE VARCHAR(15),
	TITLE_NUMBER VARCHAR(100),
	LOT_NO VARCHAR(150),
	LOT_LOCATION VARCHAR(100),
	POSCODE VARCHAR(15),
	LAND_AREA DECIMAL(18,2),
	LAND_AREA_UOM VARCHAR(10),
	BUILT_UP_AREA DECIMAL(10,0),
	BUILT_UP_AREA_UOM VARCHAR(10),
	TENURE_VALUE DECIMAL(5,0),
	TENURE VARCHAR(25),
	RESTRICTION_CONDITION VARCHAR(3000) DEFAULT 'N/A',
	EXPRESSED_CONDITION VARCHAR(3000) DEFAULT 'N/A',
	REMARKS VARCHAR (250),
	REGISTERED_OWNER VARCHAR (250),
	PROPERTY_ADDRESS VARCHAR (1000),
	STATE VARCHAR (40),
	DISTRICT VARCHAR (40),
	MUKIM VARCHAR (80),
	REAL_ESTATE_FEW_RENTAL_UNITS VARCHAR(1),
	PROPERTY_USAGE_TYPE VARCHAR(40),
	DEVELOPER_NAME VARCHAR(40),
	ABANDONED_PROJECT_IND CHAR(1),
	PROPERTY_COMPLETION_STATUS CHAR(25),
	CATEGOTY_OF_LAND_USE VARCHAR(40),
	PROPERTY_TYPE VARCHAR(40),
	PHASE_NUMBER VARCHAR(20),
	PROJECT_NAME VARCHAR (40),
	UNIT_PARCEL_NO VARCHAR(10),
	INDEPENDENT_VALUER_IND CHAR(10) DEFAULT 'Y',
	QUIT_RENT_IND CHAR(1),
	QUIT_RENT_RECEIPT_IND CHAR(1),
	QUIT_RENT_AMT_PAID DECIMAL(17,2),
	PROJECT_NUMBER DECIMAL (11,0),
	CMS_COLLATERAL_ID BIGINT,
	CMS_COLLATERAL_STG_ID BIGINT,
	SOURCE_ID VARCHAR(10),
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	VALID_IND CHAR(1) DEFAULT 'Y'
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "MIG_PT" 
	ADD CONSTRAINT "MIG_PT_U" UNIQUE
		("SOURCE_SECURITY_ID", "REGION");

CREATE TABLE MIG_PT_ERR LIKE MIG_PT
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE MIG_PT_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE MIG_PT_ERR
  ADD REASON	CLOB;

-- CHARGE
CREATE TABLE MIG_CHARGE_PT (
	SOURCE_SECURITY_ID VARCHAR(19) NOT NULL,
	SOURCE_LIMIT_ID VARCHAR(20) NOT NULL,
	SECURITY_RANKING INT NOT NULL,
	CHARGE_TYPE CHAR(1) DEFAULT 'G',
	NATURE_OF_CHARGE VARCHAR(20),
	CHARGE_CURRENCY CHAR(3),
	CHARGE_AMT DECIMAL(20,2),
	DATE_LEGALLY_CHARGE TIMESTAMP,
	PRIOR_CHARGEE VARCHAR(100),
	PRIOR_CHARGE_TYPE VARCHAR(10),
	PRIOR_CHARGE_CCY CHAR(3),
	PRIOR_CHARGE_AMT DECIMAL(20,2),
	CAVEAT_WAIVED_IND CHAR(1),
	CAVEAT_REF_NUMBER VARCHAR(50),
	EXPIRY_DATE TIMESTAMP,
	PRESENTATION_NUMBER VARCHAR(50),
	PRESENTATION_DATE TIMESTAMP,
	DATE_LODGED TIMESTAMP,
	SOLICITOR_NAME VARCHAR (100),
	SOURCE_ID VARCHAR(10),
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	VALID_IND CHAR(1) DEFAULT 'Y',
	VALID_CHARGE_IND CHAR(1) DEFAULT 'Y',
	CHARGE_TYPE_CODE VARCHAR(10),
	NATURE_OF_CHARGE_CODE VARCHAR(10),
	CMS_ACT_CHARGE_ID BIGINT, 
	CMS_ACT_LMT_ID BIGINT,
	CMS_STG_CHARGE_ID BIGINT,
	CMS_ACT_LMT_PROFILE_ID BIGINT,
	CMS_ACT_DTL_ID BIGINT, 
	CMS_STG_DTL_ID BIGINT,
	PRIOR_CHARGE_TYPE_CODE VARCHAR(10)	
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "MIG_CHARGE_PT" 
	ADD CONSTRAINT "MIG_CHARGE_PT_U" UNIQUE
		("SOURCE_LIMIT_ID",
		 "SOURCE_SECURITY_ID");

CREATE TABLE MIG_CHARGE_PT_ERR LIKE MIG_CHARGE_PT
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE MIG_CHARGE_PT_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE MIG_CHARGE_PT_ERR
  ADD REASON	CLOB;

-- PLEDGOR
CREATE TABLE MIG_PLEDGOR_PT (
	CIF_NUMBER VARCHAR(20) NOT NULL,
	SOURCE_LIMIT_ID VARCHAR(20) NOT NULL,
	SOURCE_SECURITY_ID VARCHAR(19) NOT NULL,
	IS_BORROWER_PLEDGOR CHAR(1), 
	CIF_PLEDGOR1 VARCHAR(19),
	CIF_PLEDGOR2 VARCHAR(19),
	CIF_PLEDGOR3 VARCHAR(19),
	CIF_PLEDGOR4 VARCHAR(19),
	CMS_PLEDGOR_ID BIGINT,
	CMS_PLEDGOR1_ID BIGINT,
	CMS_PLEDGOR2_ID BIGINT,
	CMS_PLEDGOR3_ID BIGINT,
	CMS_PLEDGOR4_ID BIGINT,
	SOURCE_ID VARCHAR(10),
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	IS_BRRW_PLGR_IND CHAR(1) DEFAULT 'Y',
	CIF_PLEDGOR1_IND CHAR(1) DEFAULT 'Y',
	CIF_PLEDGOR2_IND CHAR(1) DEFAULT 'Y',
	CIF_PLEDGOR3_IND CHAR(1) DEFAULT 'Y',
	CIF_PLEDGOR4_IND CHAR(1) DEFAULT 'Y'
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "MIG_PLEDGOR_PT" 
	ADD CONSTRAINT "MIG_PGR_PT_U" UNIQUE
		("CIF_NUMBER",
		 "SOURCE_LIMIT_ID",
		 "SOURCE_SECURITY_ID");

CREATE TABLE MIG_PLEDGOR_PT_ERR LIKE MIG_PLEDGOR_PT
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE MIG_PLEDGOR_PT_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE MIG_PLEDGOR_PT_ERR
  ADD REASON	CLOB;


CREATE TABLE MIG_VAL_PT (
	SOURCE_SECURITY_ID VARCHAR(19) NOT NULL,
	VALUATION_DATE TIMESTAMP NOT NULL,
	VALUATION_CCY CHAR(3),
	VALUATION_OMV DECIMAL(17,2) NOT NULL,
	VALUER VARCHAR(200),
	VALUER_CODE VARCHAR(10),
	VALUATION_FSV DECIMAL(17,2),
	COMMENTS VARCHAR(250),
	RESERVE_PRICE DECIMAL(17,2),
	RESERVE_PRICE_DATE TIMESTAMP,
	VALUATION_ID BIGINT,
	VALUATION_STG_ID BIGINT,
	SOURCE_ID VARCHAR(10),
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	VALID_IND CHAR(1) DEFAULT 'Y'
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "MIG_VAL_PT" 
	ADD CONSTRAINT "MIG_VAL_PT_U" UNIQUE
		("SOURCE_SECURITY_ID",
		 "VALUATION_DATE",
		 "VALUATION_OMV");

CREATE TABLE MIG_VAL_PT_ERR LIKE MIG_VAL_PT
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE MIG_VAL_PT_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE MIG_VAL_PT_ERR
  ADD REASON	CLOB;