drop table MIG_CL;

drop table MIG_CL_ERR;

drop table MIG_CHARGE_CL;

drop table MIG_CHARGE_CL_ERR;

CREATE TABLE MIG_CL (
	CIF_NUMBER VARCHAR(20),
	FAC_DESC VARCHAR(40),
	SOURCE_SECURITY_ID VARCHAR(19) NOT NULL,
	SECURITY_TYPE VARCHAR(40),
	SECURITY_SUB_TYPE VARCHAR(80),
	SECURITY_TYPE_ID CHAR(2) DEFAULT 'CL', 
	SECURITY_SUB_TYPE_ID VARCHAR(5) DEFAULT 'CLEAN' ,
	CMS_COLLATERAL_ID BIGINT,
	CMS_COLLATERAL_STG_ID BIGINT,
	SOURCE_ID VARCHAR(10),
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	VALID_IND CHAR(1) DEFAULT 'Y'
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "MIG_CL" 
	ADD CONSTRAINT "MIG_CL_U" UNIQUE
		("SOURCE_SECURITY_ID", "REGION");

CREATE TABLE MIG_CL_ERR LIKE MIG_CL;

ALTER TABLE MIG_CL_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE MIG_CL_ERR
  ADD REASON	CLOB;
  
-- CHARGE
CREATE TABLE MIG_CHARGE_CL (
	SOURCE_SECURITY_ID VARCHAR(19) NOT NULL,
	SOURCE_LIMIT_ID VARCHAR(20) NOT NULL,
	SOURCE_ID VARCHAR(10),
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	VALID_IND CHAR(1) DEFAULT 'Y',
	VALID_CHARGE_IND CHAR(1) DEFAULT 'Y',
	CHARGE_TYPE_CODE VARCHAR(10),
	NATURE_OF_CHARGE_CODE VARCHAR(10),
	CMS_ACT_CHARGE_ID BIGINT, 
	CMS_ACT_LMT_ID BIGINT,
	CMS_STG_CHARGE_ID BIGINT,
	CMS_ACT_LMT_PROFILE_ID BIGINT,
	CMS_ACT_DTL_ID BIGINT, 
	CMS_STG_DTL_ID BIGINT,
	PRIOR_CHARGE_TYPE_CODE VARCHAR(10)
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "MIG_CHARGE_CL" 
	ADD CONSTRAINT "MIG_CHARGE_CL_U" UNIQUE
		("SOURCE_LIMIT_ID",
		 "SOURCE_SECURITY_ID");

CREATE TABLE MIG_CHARGE_CL_ERR LIKE MIG_CHARGE_CL
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE MIG_CHARGE_CL_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE MIG_CHARGE_CL_ERR
  ADD REASON	CLOB;