--------------------------------
--- CMS_VALUATION_AGENCY 
--------------------------------


CREATE TABLE "ABCLIMS"."CMS_VALUATION_AGENCY" (
  "ID"	BIGINT	NOT NULL,
  "VERSION_TIME"	BIGINT	NOT NULL,
  "CREATE_BY"	VARCHAR(50)	NOT NULL,
  "CREATION_DATE"	TIMESTAMP	NOT NULL,
  "LAST_UPDATE_BY"	VARCHAR(50)	NOT NULL,
  "LAST_UPDATE_DATE"	TIMESTAMP	NOT NULL,
  "DEPRECATED"	CHARACTER(1)	NOT NULL,
  "STATUS"	VARCHAR(20)	NOT NULL,
  "MASTER_ID"	BIGINT,
  "VALUATION_AGENCY_CODE"	VARCHAR(30)	NOT NULL,
  "VALUATION_AGENCY_NAME"	VARCHAR(50)	NOT NULL,
  "ADDRESS"	VARCHAR(200),
  "CITY_TOWN"	VARCHAR(200)	NOT NULL,
  "STATE"	VARCHAR(200)	NOT NULL,
  "REGION"	VARCHAR(200),
  "COUNTRY"	VARCHAR(200)	NOT NULL
) 
  IN "USERSPACE1";
  
  
--------------------------------
--- CMS_STAGE_VALUATION_AGENCY 
--------------------------------
  
  
CREATE TABLE "ABCLIMS"."CMS_STAGE_VALUATION_AGENCY" (
  "ID"	BIGINT	NOT NULL,
  "VERSION_TIME"	BIGINT	NOT NULL,
  "CREATE_BY"	VARCHAR(50)	NOT NULL,
  "CREATION_DATE"	TIMESTAMP	NOT NULL,
  "LAST_UPDATE_BY"	VARCHAR(50)	NOT NULL,
  "LAST_UPDATE_DATE"	TIMESTAMP	NOT NULL,
  "DEPRECATED"	CHARACTER(1)	NOT NULL,
  "STATUS"	VARCHAR(20)	NOT NULL,
  "MASTER_ID"	BIGINT,
  "VALUATION_AGENCY_CODE"	VARCHAR(30)	NOT NULL,
  "VALUATION_AGENCY_NAME"	VARCHAR(50)	NOT NULL,
  "ADDRESS"	VARCHAR(200),
  "CITY_TOWN"	VARCHAR(200)	NOT NULL,
  "STATE"	VARCHAR(200)	NOT NULL,
  "REGION"	VARCHAR(200),
  "COUNTRY"	VARCHAR(200)	NOT NULL
) 
  IN "USERSPACE1";  