LOAD DATA
INFILE 'FILES\Credit Approver.csv'
 "str '~~~'"
BADFILE 'PARTIAL_ERROR_LOG\Credit Approver.bad'
DISCARDFILE 'PARTIAL_ERROR_LOG\Credit Approver.dsc'
DISCARDMAX 1241513983
APPEND INTO TABLE MIG_CREDIT_APPROVAL
FIELDS TERMINATED BY '|||'
TRAILING NULLCOLS
(
APPROVERID "REPLACE(REPLACE(DECODE(UPPER(:APPROVERID),'NULL',NULL,:APPROVERID), CHR(10),''), CHR(13),'')",
APPROVERNAME "DECODE(UPPER(:APPROVERNAME),'NULL',NULL,:APPROVERNAME)",
MAXAGRLIMIT "DECODE(UPPER(:MAXAGRLIMIT),'NULL',NULL,:MAXAGRLIMIT)",
DISCPOWER  "DECODE(UPPER(:DISCPOWER),'NULL',NULL,:DISCPOWER)",
SEGMENTID "DECODE(UPPER(:SEGMENTID),'NULL',NULL,:SEGMENTID)",
CCMAILID "DECODE(UPPER(:CCMAILID),'NULL',NULL,:CCMAILID)",
SENIOR "DECODE(UPPER(:SENIOR),'NULL',NULL,:SENIOR)",
RISK "DECODE(UPPER(:RISK),'NULL',NULL,:RISK)",
DEFERRALPOWERS "DECODE(UPPER(:DEFERRALPOWERS),'NULL',NULL,:DEFERRALPOWERS)",
WAIVINGPOWERS "DECODE(UPPER(:WAIVINGPOWERS),'NULL',NULL,:WAIVINGPOWERS)",
REGION "DECODE(UPPER(:REGION),'NULL',NULL,:REGION)"
)