drop table MIG_IN;

drop table MIG_IN_ERR;

drop table MIG_CHARGE_IN;

drop table MIG_CHARGE_IN_ERR;

drop table MIG_PLEDGOR_IN;

drop table MIG_PLEDGOR_IN_ERR;

drop table MIG_VAL_IN;

drop table MIG_VAL_IN_ERR;

CREATE TABLE MIG_IN (
	CIF_NUMBER VARCHAR(20),
	FAC_DESC VARCHAR(40),
	SOURCE_SECURITY_ID VARCHAR(19) NOT NULL,
	SECURITY_TYPE VARCHAR(40) DEFAULT 'Insurance',
	SECURITY_SUB_TYPE VARCHAR(80),
	SECURITY_TYPE_ID CHAR(2) DEFAULT 'IN',
	SECURITY_SUB_TYPE_ID VARCHAR(5),
	SECURITY_CURRENCY CHAR(3),
	SECURITY_LOCATION CHAR(2) DEFAULT 'MY',
	SECURITY_ORGANISATION VARCHAR(60),
	SECURITY_ORGANISATION_CODE VARCHAR(10),	
	SECURITY_CUSTODIAN_TYPE VARCHAR(10) DEFAULT 'I',
	CUSTODIAN_TYPE_CODE CHAR(1),
	SECURITY_CUSTODIAN_VALUE VARCHAR(100),
	CUSTODIAN_VALUE_CODE VARCHAR(10),
	SECURITY_MATURITY_DATE TIMESTAMP,
	SECURITY_PERFECTION_DATE TIMESTAMP,
	LEGAL_ENFORCEABILITY_IND CHAR(1),
	LEGAL_ENFORCEABILITY_DATE TIMESTAMP,
	SECURITY_REF_NOTE VARCHAR(2500),
	EXCHANGE_CONTROL_OBTAINED CHAR(1) DEFAULT 'N',	
	INSURER_NAME VARCHAR(100),
	INSURANCE_TYPE VARCHAR(20),
	INSURED_CURRENCY CHAR(3),
	INSURED_AMT DECIMAL(17,2),
	INSURANCE_EFFECTIVE_DATE TIMESTAMP,
	POLICY_NUMBER VARCHAR(30),
	INSURANCE_EXPIRY_DATE TIMESTAMP,
	BANK_INTEREST_DULY_NOTED CHAR(1),
	EXTERNAL_LEGAL_COUNSEL VARCHAR(100),
	ACCELERATION_CLAUSE CHAR(1),
	LOCAL_CCY_IN_LOCAL_MARKETS CHAR(3),
	CORE_MARKETS_TAG VARCHAR(10),
	ISDA_MASTER_AGREEMENT_DATE TIMESTAMP,
	TREASURY_DOCUMENTATION_DATE TIMESTAMP,
	BANK_ENTITY VARCHAR(150),
	HEDGE_TYPE VARCHAR(150),
	HEDGE_REFERENCE VARCHAR(150),
	CDS_REFERENCE VARCHAR(150),
	TRADE_ID VARCHAR(150),
	TRADE_DATE TIMESTAMP,
	DEAL_DATE TIMESTAMP,
	START_DATE TIMESTAMP,
	CDS_MATURITY_DATE TIMESTAMP,
	TENOR_UNIT INT,
	TENOR_UOM VARCHAR(150),
	TRADE_CURRENCY CHAR(3),
	NOTIONAL_HEDGED_AMT DECIMAL(17,2),
	REFERENCE_ENTITY VARCHAR(100),
	CDS_BKG_LOCATION VARCHAR(150),
	LOAN_BOND_BKG_LOCATION VARCHAR(150),
	REFERENCE_ASSET VARCHAR(100),
	ISSUER VARCHAR(100),
	ISSUER_ID VARCHAR(50),
	ISSUER_DETAIL VARCHAR(250),
	DEALT_PRICE DECIMAL(17,2),
	RESIDUAL_MATURITY DECIMAL(17,2),
	SETTLEMENT VARCHAR(150),
	PAR_VALUE DECIMAL(17,2),
	DECLINE_MARKET_VALUE DECIMAL(17,2),
	EVENT_DETERMINATION_DATE TIMESTAMP,
	COMPLIANCE_CERT_OBTAINED VARCHAR(150),
	CDS_VALUATION_DATE TIMESTAMP,
	CDS_VALUATION_CCY CHAR(3),
	CDS_MARGIN DECIMAL(17,2),
	CDS_NOMINAL_VALUE DECIMAL(17,2),
	CDS_VALUATION_CMV DECIMAL(30,2),
	CDS_VALUATION_FSV DECIMAL(30,2),
	CMS_COLLATERAL_ID BIGINT,
	CMS_COLLATERAL_STG_ID BIGINT,
	CDS_ID BIGINT,
	CDS_STG_ID BIGINT,
	SOURCE_ID VARCHAR(10),
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	VALID_IND CHAR(1) DEFAULT 'Y'
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "MIG_IN" 
	ADD CONSTRAINT "MIG_IN_U" UNIQUE
		("SOURCE_SECURITY_ID", "REGION");

CREATE TABLE MIG_IN_ERR LIKE MIG_IN
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE MIG_IN_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE MIG_IN_ERR
  ADD REASON	CLOB;

-- CHARGE
CREATE TABLE MIG_CHARGE_IN (
	SOURCE_SECURITY_ID VARCHAR(19) NOT NULL,
	SOURCE_LIMIT_ID VARCHAR(20) NOT NULL,
	CHARGE_TYPE CHAR(10),
	NATURE_OF_CHARGE VARCHAR(60),
	CHARGE_CURRENCY CHAR(3),
	CHARGE_AMT DECIMAL(20,2),
	DATE_LEGALLY_CHARGE TIMESTAMP,
	SOURCE_ID VARCHAR(10),
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	VALID_IND CHAR(1) DEFAULT 'Y',
	VALID_CHARGE_IND CHAR(1) DEFAULT 'Y',
	CHARGE_TYPE_CODE VARCHAR(10),
	NATURE_OF_CHARGE_CODE VARCHAR(10),
	CMS_ACT_CHARGE_ID BIGINT, 
	CMS_ACT_LMT_ID BIGINT,
	CMS_STG_CHARGE_ID BIGINT,
	CMS_ACT_LMT_PROFILE_ID BIGINT,
	CMS_ACT_DTL_ID BIGINT, 
	CMS_STG_DTL_ID BIGINT,
	PRIOR_CHARGE_TYPE_CODE VARCHAR(10)	
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "MIG_CHARGE_IN" 
	ADD CONSTRAINT "MIG_CHARGE_IN_U" UNIQUE
		("SOURCE_LIMIT_ID",
		 "SOURCE_SECURITY_ID");

CREATE TABLE MIG_CHARGE_IN_ERR LIKE MIG_CHARGE_IN
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE MIG_CHARGE_IN_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE MIG_CHARGE_IN_ERR
  ADD REASON	CLOB;

-- PLEDGOR
CREATE TABLE MIG_PLEDGOR_IN (
	CIF_NUMBER VARCHAR(20) NOT NULL,
	SOURCE_LIMIT_ID VARCHAR(20) NOT NULL,
	SOURCE_SECURITY_ID VARCHAR(19) NOT NULL,
	IS_BORROWER_PLEDGOR CHAR(1), 
	CIF_PLEDGOR1 VARCHAR(19),
	CIF_PLEDGOR2 VARCHAR(19),
	CIF_PLEDGOR3 VARCHAR(19),
	CIF_PLEDGOR4 VARCHAR(19),
	CMS_PLEDGOR_ID BIGINT,
	CMS_PLEDGOR1_ID BIGINT,
	CMS_PLEDGOR2_ID BIGINT,
	CMS_PLEDGOR3_ID BIGINT,
	CMS_PLEDGOR4_ID BIGINT,
	SOURCE_ID VARCHAR(10),
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	IS_BRRW_PLGR_IND CHAR(1) DEFAULT 'Y',
	CIF_PLEDGOR1_IND CHAR(1) DEFAULT 'Y',
	CIF_PLEDGOR2_IND CHAR(1) DEFAULT 'Y',
	CIF_PLEDGOR3_IND CHAR(1) DEFAULT 'Y',
	CIF_PLEDGOR4_IND CHAR(1) DEFAULT 'Y'
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "MIG_PLEDGOR_IN" 
	ADD CONSTRAINT "MIG_PGR_IN_U" UNIQUE
		("CIF_NUMBER",
		 "SOURCE_LIMIT_ID",
		 "SOURCE_SECURITY_ID");

CREATE TABLE MIG_PLEDGOR_IN_ERR LIKE MIG_PLEDGOR_IN
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE MIG_PLEDGOR_IN_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE MIG_PLEDGOR_IN_ERR
  ADD REASON	CLOB;


CREATE TABLE MIG_VAL_IN (
	SOURCE_SECURITY_ID VARCHAR(19) NOT NULL,
	VALUATION_DATE TIMESTAMP NOT NULL,
	VALUATION_CCY CHAR(3),
	VALUATION_OMV DECIMAL(17,2) NOT NULL,
	VALUER VARCHAR(200),
	VALUER_CODE VARCHAR(10),
	VALUATION_FSV DECIMAL(17,2),
	COMMENTS VARCHAR(250),
	RESERVE_PRICE DECIMAL(17,2),
	RESERVE_PRICE_DATE TIMESTAMP,
	VALUATION_ID BIGINT,
	VALUATION_STG_ID BIGINT,
	SOURCE_ID VARCHAR(10),
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	VALID_IND CHAR(1) DEFAULT 'Y'
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "MIG_VAL_IN" 
	ADD CONSTRAINT "MIG_VAL_IN_U" UNIQUE
		("SOURCE_SECURITY_ID",
		 "VALUATION_DATE",
		 "VALUATION_OMV");

CREATE TABLE MIG_VAL_IN_ERR LIKE MIG_VAL_IN
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE MIG_VAL_IN_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE MIG_VAL_IN_ERR
  ADD REASON	CLOB;