
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3600, 'BOND_FEED_GROUP', 'ACTION_MAKER_UPDATE', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3601, 'BOND_FEED_GROUP', 'ACTION_MAKER_SUBMIT', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3602, 'BOND_FEED_GROUP', 'ACTION_MAKER_UPDATE_REJECTED', 'REJECTED', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3603, 'BOND_FEED_GROUP', 'ACTION_MAKER_CLOSE_REJECTED', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3604, 'BOND_FEED_GROUP', 'ACTION_CHECKER_APPROVE_BOND_FEED_GROUP', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3605, 'BOND_FEED_GROUP', 'ACTION_CHECKER_REJECT_BOND_FEED_GROUP', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3606, 'BOND_FEED_GROUP', 'ACTION_MAKER_UPDATE', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3607, 'BOND_FEED_GROUP', 'ACTION_MAKER_SUBMIT', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3608, 'BOND_FEED_GROUP', 'ACTION_MAKER_SUBMIT_REJECTED', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3609, 'BOND_FEED_GROUP', 'ACTION_MAKER_CLOSE_DRAFT', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');

Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3500, 'COBORROWER_LIMIT', 'CREATE', 'ND', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3501, 'COBORROWER_LIMIT', 'MAKER_UPDATE', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3502, 'COBORROWER_LIMIT', 'SYSTEM_CLOSE', 'ACTIVE', 'CLOSED', 'CLOSED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3503, 'COBORROWER_LIMIT', 'HOST_UPDATE', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3504, 'COBORROWER_LIMIT', 'CHECKER_APPROVE_UPDATE', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3505, 'COBORROWER_LIMIT', 'CHECKER_REJECT_UPDATE', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3506, 'COBORROWER_LIMIT', 'SYSTEM_CLOSE', 'PENDING_UPDATE', 'CLOSED', 'CLOSED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3507, 'COBORROWER_LIMIT', 'HOST_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3508, 'COBORROWER_LIMIT', 'MAKER_RESUBMIT_UPDATE', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3509, 'COBORROWER_LIMIT', 'MAKER_CANCEL_UPDATE', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3510, 'COBORROWER_LIMIT', 'SYSTEM_CLOSE', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3511, 'COBORROWER_LIMIT', 'HOST_UPDATE', 'REJECTED', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3512, 'COBORROWER_LIMIT', 'SYSTEM_DELETE', 'REJECTED', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3513, 'COBORROWER_LIMIT', 'SYSTEM_DELETE', 'PENDING_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3514, 'COBORROWER_LIMIT', 'SYSTEM_DELETE', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (100, 'COL', 'SUBSCRIBE_CREATE', 'ND', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (101, 'COL', 'MAKER_UPDATE', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (102, 'COL', 'CHECKER_APPROVE_UPDATE', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (103, 'COL', 'MAKER_SAVE', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (104, 'COL', 'MAKER_CANCEL', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (105, 'COL', 'MAKER_UPDATE', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (106, 'COL', 'CHECKER_REJECT_UPDATE', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (107, 'COL', 'MAKER_SAVE', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (108, 'COL', 'MAKER_CANCEL', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (109, 'COL', 'PART_DELETE', 'PENDING_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (110, 'COL', 'FULL_DELETE', 'PENDING_UPDATE', 'DELETED', 'DELETED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (111, 'COL', 'FULL_DELETE', 'ACTIVE', 'DELETED', 'DELETED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (112, 'COL', 'FULL_DELETE', 'DRAFT', 'DELETED', 'DELETED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (113, 'COL', 'PART_DELETE', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (114, 'COL', 'PART_DELETE', 'REJECTED', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (115, 'COL', 'FULL_DELETE', 'REJECTED', 'DELETED', 'DELETED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (116, 'COL', 'MAKER_SAVE', 'REJECTED', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (117, 'COL', 'MAKER_UPDATE', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (118, 'COL', 'PART_DELETE', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (119, 'COL', 'SYSTEM_CANCEL', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (120, 'COL', 'SYSTEM_CANCEL', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (121, 'COL', 'SYSTEM_CANCEL', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (122, 'COL', 'SYSTEM_UPDATE', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (123, 'COL', 'SYSTEM_UPDATE', 'REJECTED', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (124, 'COL', 'SYSTEM_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (125, 'COL', 'SYSTEM_UPDATE', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (126, 'COL', 'HOST_UPDATE', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (127, 'COL', 'HOST_UPDATE', 'REJECTED', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (128, 'COL', 'HOST_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (129, 'COL', 'HOST_UPDATE', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
VALUES(130, 'COL', 'MANUAL_CREATE', 'ND', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');

INSERT INTO TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
VALUES(131, 'COL', 'MANUAL_UPDATE', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');

INSERT INTO TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
VALUES(132, 'COL', 'MANUAL_UPDATE', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');

INSERT INTO TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
VALUES(133, 'COL', 'MANUAL_UPDATE', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');

INSERT INTO TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
VALUES(134, 'COL', 'MANUAL_DRAFT', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');

INSERT INTO TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
VALUES(135, 'COL', 'MANUAL_DRAFT', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');

INSERT INTO TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
VALUES(136, 'COL', 'MANUAL_DRAFT', 'REJECTED', 'DRAFT', 'DRAFT', '1', '1');

INSERT INTO TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
VALUES(137, 'COL', 'MANUAL_CLOSE', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
VALUES(138, 'COL', 'MANUAL_CLOSE', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
VALUES(139, 'COL', 'MANUAL_APPROVE_UPDATE', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
VALUES(140, 'COL', 'MANUAL_REJECT_UPDATE', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');

INSERT INTO TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
VALUES(141, 'COL', 'MANUAL_DRAFT', 'ND', 'DRAFT', 'DRAFT', '1', '1');

INSERT INTO TR_STATE_MATRIX 
( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
 VALUES 
 ( 142, 'COL', 'MAKER_DELETE', 'ACTIVE', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1'); 

INSERT INTO TR_STATE_MATRIX 
( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
 VALUES 
 ( 143, 'COL', 'MAKER_DELETE', 'DRAFT', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1'); 

 INSERT INTO TR_STATE_MATRIX 
( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
 VALUES 
 ( 144, 'COL', 'MAKER_DELETE', 'REJECTED', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1'); 

 
 INSERT INTO TR_STATE_MATRIX 
( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
 VALUES 
 ( 145, 'COL', 'CHECKER_APPROVE_DELETE', 'PENDING_DELETE', 'DELETED', 'DELETED', '1', '1'); 

 
 INSERT INTO TR_STATE_MATRIX 
( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
 VALUES 
 ( 146, 'COL', 'CHECKER_REJECT_DELETE', 'PENDING_DELETE', 'REJECTED', 'REJECTED', '1', '1'); 
   
INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP )
VALUES
    ( 147, 'COL', 'MAKER_DIRECT_CREATE', 'ND', 'ACTIVE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (148,'COL', 'SYSTEM_APPROVE', 'LOADING', 'ACTIVE', 'IMPLEMENTED', '1', '1');
	
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (149,'COL', 'SYSTEM_REJECT', 'LOADING', 'PENDING_PERFECTION', 'PENDING_PERFECTION', '1', '1');
	
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (150,'COL', 'SYSTEM_UPDATE', 'LOADING', 'PENDING_RETRY', 'PENDING_RETRY', '1', '1');
	
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (151,'COL', 'SYSTEM_APPROVE', 'LOADING_DELETE', 'DELETED', 'DELETED', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (152,'COL', 'SYSTEM_REJECT', 'LOADING_DELETE', 'PENDING_PERFECTION', 'PENDING_PERFECTION', '1', '1');
	
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (153,'COL', 'SYSTEM_UPDATE', 'LOADING_DELETE', 'PENDING_RETRY', 'PENDING_RETRY', '1', '1');
		
INSERT INTO tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (154, 'COL', 'MAKER_SAVE', 'ND', 'DRAFT', 'DRAFT', '1', '1');

INSERT INTO tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (155, 'COL', 'MAKER_CREATE', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');

INSERT INTO tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (156, 'COL', 'MAKER_CREATE', 'DRAFT', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');

INSERT INTO tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (157, 'COL', 'CHECKER_APPROVE_UPDATE', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');

INSERT INTO tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (158, 'COL', 'CHECKER_REJECT_UPDATE', 'PENDING_CREATE', 'REJECTED_CREATE', 'REJECTED_CREATE', '1', '1');

INSERT INTO tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (159, 'COL', 'MAKER_SAVE', 'REJECTED_CREATE', 'DRAFT', 'DRAFT', '1', '1');

INSERT INTO tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (160, 'COL', 'MAKER_CANCEL', 'REJECTED_CREATE', 'CLOSED', 'CLOSED', '1', '1');

INSERT INTO tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (161, 'COL', 'MAKER_CREATE', 'REJECTED_CREATE', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');

INSERT INTO tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (162, 'COL', 'CHECKER_APPROVE_PASS', 'PENDING_CREATE', 'LOADING', 'LOADING', '1', '1');

INSERT INTO tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (163, 'COL', 'CHECKER_APPROVE_FAIL', 'PENDING_CREATE', 'PENDING_PERFECTION', 'PENDING_PERFECTION', '1', '1');

INSERT INTO tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (164, 'COL', 'CHECKER_APPROVE_PASS', 'PENDING_RETRY', 'LOADING', 'LOADING', '1', '1');

INSERT INTO tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (165, 'COL', 'MAKER_UPDATE', 'PENDING_PERFECTION', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');

INSERT INTO tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (166, 'COL', 'MAKER_SAVE', 'PENDING_PERFECTION', 'DRAFT', 'DRAFT', '1', '1');

INSERT INTO tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (167, 'COL', 'CHECKER_APPROVE_LOAD_DELETE', 'PENDING_DELETE', 'LOADING_DELETE', 'LOADING_DELETE', '1', '1');

INSERT INTO tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (168, 'COL', 'CHECKER_APPROVE_LOAD_DELETE', 'PENDING_RETRY', 'LOADING_DELETE', 'LOADING_DELETE', '1', '1');

INSERT INTO tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (169, 'COL', 'CHECKER_APPROVE_PASS', 'PENDING_UPDATE', 'LOADING', 'LOADING', '1', '1');

INSERT INTO tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (170, 'COL', 'CHECKER_APPROVE_FAIL', 'PENDING_UPDATE', 'PENDING_PERFECTION', 'PENDING_PERFECTION', '1', '1');
	
INSERT INTO tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (171, 'COL', 'HOST_UPDATE', 'PENDING_PERFECTION', 'PENDING_PERFECTION', 'PENDING_PERFECTION', '1', '1');

Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1800, 'COLPARAM', 'MAKER_UPDATE', 'ND', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1801, 'COLPARAM', 'MAKER_UPDATE', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1802, 'COLPARAM', 'MAKER_UPDATE', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1803, 'COLPARAM', 'MAKER_SAVE', 'ND', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1804, 'COLPARAM', 'MAKER_SAVE', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1805, 'COLPARAM', 'MAKER_SAVE', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1806, 'COLPARAM', 'CHECKER_APPROVE', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1807, 'COLPARAM', 'CHECKER_REJECT', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1808, 'COLPARAM', 'MAKER_CANCEL', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1809, 'COLPARAM', 'MAKER_CANCEL', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1810, 'COLPARAM', 'MAKER_UPDATE', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1811, 'COLPARAM', 'MAKER_SAVE', 'REJECTED', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (700, 'COLSUBTYPE', 'MAKER_UPDATE', 'ND', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (701, 'COLSUBTYPE', 'MAKER_UPDATE', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (702, 'COLSUBTYPE', 'MAKER_SAVE', 'ND', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (703, 'COLSUBTYPE', 'MAKER_SAVE', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (704, 'COLSUBTYPE', 'MAKER_SAVE', 'REJECTED', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (705, 'COLSUBTYPE', 'MAKER_SAVE', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (706, 'COLSUBTYPE', 'MAKER_UPDATE', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (707, 'COLSUBTYPE', 'MAKER_UPDATE', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (708, 'COLSUBTYPE', 'MAKER_CANCEL', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (709, 'COLSUBTYPE', 'MAKER_CANCEL', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (710, 'COLSUBTYPE', 'CHECKER_APPROVE', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (711, 'COLSUBTYPE', 'CHECKER_REJECT', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');

Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (301, 'CUSTOMER', 'CREATE_CUSTOMER', 'ND', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (302, 'CUSTOMER', 'MAKER_UPDATE_CUSTOMER', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (303, 'CUSTOMER', 'CHECKER_APPROVE_UPDATE_CUSTOMER', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (304, 'CUSTOMER', 'CHECKER_REJECT_UPDATE_CUSTOMER', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (305, 'CUSTOMER', 'MAKER_CANCEL_UPDATE', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (306, 'CUSTOMER', 'MAKER_RESUBMIT_UPDATE_CUSTOMER', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (307, 'CUSTOMER', 'HOST_UPDATE', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (308, 'CUSTOMER', 'HOST_DELETE', 'ACTIVE', 'DELETED', 'DELETED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (309, 'CUSTOMER', 'HOST_DELETE', 'PENDING_UPDATE', 'DELETED', 'DELETED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (310, 'CUSTOMER', 'HOST_DELETE', 'REJECTED', 'DELETED', 'DELETED', '1', '1');
   
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (4000, 'FOREX_FEED_GROUP', 'ACTION_MAKER_UPDATE', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (4001, 'FOREX_FEED_GROUP', 'ACTION_MAKER_SUBMIT', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (4002, 'FOREX_FEED_GROUP', 'ACTION_MAKER_UPDATE_REJECTED', 'REJECTED', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (4003, 'FOREX_FEED_GROUP', 'ACTION_MAKER_CLOSE_REJECTED', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (4004, 'FOREX_FEED_GROUP', 'ACTION_CHECKER_APPROVE_FOREX_FEED_GROUP', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (4005, 'FOREX_FEED_GROUP', 'ACTION_CHECKER_REJECT_FOREX_FEED_GROUP', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (4006, 'FOREX_FEED_GROUP', 'ACTION_MAKER_UPDATE', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (4007, 'FOREX_FEED_GROUP', 'ACTION_MAKER_SUBMIT', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (4008, 'FOREX_FEED_GROUP', 'ACTION_MAKER_SUBMIT_REJECTED', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (4009, 'FOREX_FEED_GROUP', 'ACTION_MAKER_CLOSE_DRAFT', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');
   
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES (7600, 'GOLD_FEED_GROUP', 'ACTION_MAKER_UPDATE', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES (7601, 'GOLD_FEED_GROUP', 'ACTION_MAKER_SUBMIT', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES (7602, 'GOLD_FEED_GROUP', 'ACTION_MAKER_UPDATE_REJECTED', 'REJECTED', 'DRAFT', 'DRAFT', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES (7603, 'GOLD_FEED_GROUP', 'ACTION_MAKER_CLOSE_REJECTED', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES (7604, 'GOLD_FEED_GROUP', 'ACTION_CHECKER_APPROVE_GOLD_FEED_GROUP', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES (7605, 'GOLD_FEED_GROUP', 'ACTION_CHECKER_REJECT_GOLD_FEED_GROUP', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES (7606, 'GOLD_FEED_GROUP', 'ACTION_MAKER_UPDATE', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES (7607, 'GOLD_FEED_GROUP', 'ACTION_MAKER_SUBMIT', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES (7608, 'GOLD_FEED_GROUP', 'ACTION_MAKER_SUBMIT_REJECTED', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES (7609, 'GOLD_FEED_GROUP', 'ACTION_MAKER_CLOSE_DRAFT', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');


Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (401, 'LIMIT', 'CREATE', 'ND', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (402, 'LIMIT', 'MAKER_UPDATE', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (403, 'LIMIT', 'SYSTEM_CLOSE', 'ACTIVE', 'CLOSED', 'CLOSED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (404, 'LIMIT', 'HOST_UPDATE', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (405, 'LIMIT', 'CHECKER_APPROVE_UPDATE', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (406, 'LIMIT', 'CHECKER_REJECT_UPDATE', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (407, 'LIMIT', 'SYSTEM_CLOSE', 'PENDING_UPDATE', 'CLOSED', 'CLOSED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (408, 'LIMIT', 'HOST_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (409, 'LIMIT', 'MAKER_RESUBMIT_UPDATE', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (410, 'LIMIT', 'MAKER_CANCEL_UPDATE', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (411, 'LIMIT', 'SYSTEM_CLOSE', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (412, 'LIMIT', 'HOST_UPDATE', 'REJECTED', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (413, 'LIMIT', 'SYSTEM_DELETE', 'REJECTED', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (414, 'LIMIT', 'SYSTEM_DELETE', 'PENDING_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (415, 'LIMIT', 'SYSTEM_DELETE', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (416, 'LIMIT', 'SYSTEM_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (417, 'LIMIT', 'SYSTEM_UPDATE', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (418, 'LIMIT', 'SYSTEM_UPDATE', 'REJECTED', 'REJECTED', 'REJECTED', '1', '1');
   
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (501, 'LIMITPROFILE', 'CREATE', 'ND', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (502, 'LIMITPROFILE', 'MAKER_CREATE_TAT', 'NEW', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (503, 'LIMITPROFILE', 'HOST_UPDATE', 'NEW', 'NEW', 'NEW', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (504, 'LIMITPROFILE', 'SYSTEM_CLOSE', 'NEW', 'CLOSED', 'CLOSED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (505, 'LIMITPROFILE', 'CHECKER_APPROVE_CREATE_TAT', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (506, 'LIMITPROFILE', 'CHECKER_REJECT_CREATE_TAT', 'PENDING_CREATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (507, 'LIMITPROFILE', 'HOST_UPDATE', 'PENDING_CREATE', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (508, 'LIMITPROFILE', 'SYSTEM_CLOSE', 'PENDING_CREATE', 'CLOSED', 'CLOSED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (509, 'LIMITPROFILE', 'MAKER_UPDATE', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (510, 'LIMITPROFILE', 'SYSTEM_CLOSE', 'ACTIVE', 'CLOSED', 'CLOSED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (511, 'LIMITPROFILE', 'HOST_UPDATE', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (512, 'LIMITPROFILE', 'CHECKER_APPROVE_UPDATE', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (513, 'LIMITPROFILE', 'CHECKER_REJECT_UPDATE', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (514, 'LIMITPROFILE', 'SYSTEM_CLOSE', 'PENDING_UPDATE', 'CLOSED', 'CLOSED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (515, 'LIMITPROFILE', 'HOST_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (516, 'LIMITPROFILE', 'MAKER_RESUBMIT_UPDATE', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (517, 'LIMITPROFILE', 'MAKER_CANCEL_UPDATE', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (518, 'LIMITPROFILE', 'MAKER_RESUBMIT_CREATE_TAT', 'REJECTED', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (519, 'LIMITPROFILE', 'MAKER_CANCEL_CREATE_TAT', 'REJECTED', 'NEW', 'NEW', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (520, 'LIMITPROFILE', 'SYSTEM_CLOSE', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (521, 'LIMITPROFILE', 'HOST_UPDATE', 'REJECTED', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (522, 'LIMITPROFILE', 'UPDATE_TAT', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (523, 'LIMITPROFILE', 'UPDATE_TAT', 'PENDING_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (524, 'LIMITPROFILE', 'UPDATE_TAT', 'REJECTED', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (525, 'LIMITPROFILE', 'SYSTEM_UPDATE', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (526, 'LIMITPROFILE', 'SYSTEM_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (527, 'LIMITPROFILE', 'SYSTEM_UPDATE', 'REJECTED', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (528, 'LIMITPROFILE', 'RENEW_LIMIT_PROFILE', 'NEW', 'NEW', 'NEW', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (529, 'LIMITPROFILE', 'RENEW_LIMIT_PROFILE', 'PENDING_CREATE', 'NEW', 'NEW', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (530, 'LIMITPROFILE', 'RENEW_LIMIT_PROFILE', 'ACTIVE', 'NEW', 'NEW', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (531, 'LIMITPROFILE', 'RENEW_LIMIT_PROFILE', 'PENDING_UPDATE', 'NEW', 'NEW', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (532, 'LIMITPROFILE', 'RENEW_LIMIT_PROFILE', 'REJECTED', 'NEW', 'NEW', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (533, 'LIMITPROFILE', 'SYSTEM_DELETE', 'REJECTED', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (534, 'LIMITPROFILE', 'SYSTEM_DELETE', 'PENDING_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (535, 'LIMITPROFILE', 'SYSTEM_DELETE', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (536, 'LIMITPROFILE', 'SYSTEM_DELETE', 'NEW', 'NEW', 'NEW', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (537, 'LIMITPROFILE', 'SYSTEM_DELETE', 'PENDING_CREATE', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (538, 'LIMITPROFILE', 'SYSTEM_UPDATE', 'NEW', 'NEW', 'NEW', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (539, 'LIMITPROFILE', 'SYSTEM_UPDATE', 'PENDING_CREATE', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
   
INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (540, 'LIMITPROFILE', 'MAKER_CREATE', 'DRAFT', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (541, 'LIMITPROFILE', 'MAKER_CREATE', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (542, 'LIMITPROFILE', 'MAKER_CREATE', 'REJECTED_CREATE', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (543, 'LIMITPROFILE', 'MAKER_UPDATE', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (544, 'LIMITPROFILE', 'MAKER_UPDATE', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (545, 'LIMITPROFILE', 'CHECKER_APPROVE_UPDATE', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (546, 'LIMITPROFILE', 'CHECKER_APPROVE_UPDATE', 'PENDING_DELETE', 'CLOSED', 'CLOSED', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (547, 'LIMITPROFILE', 'CHECKER_REJECT_UPDATE', 'PENDING_CREATE', 'REJECTED_CREATE', 'REJECTED_CREATE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (548, 'LIMITPROFILE', 'CHECKER_REJECT_UPDATE', 'PENDING_DELETE', 'REJECTED_DELETE', 'REJECTED_DELETE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (549, 'LIMITPROFILE', 'MAKER_CANCEL', 'DRAFT', 'CLOSED', 'CLOSED', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (550, 'LIMITPROFILE', 'MAKER_CANCEL_CREATE', 'REJECTED_CREATE', 'CLOSED', 'CLOSED', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (551, 'LIMITPROFILE', 'MAKER_CANCEL_UPDATE', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (552, 'LIMITPROFILE', 'MAKER_CANCEL_UPDATE', 'REJECTED_DELETE', 'ACTIVE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (553, 'LIMITPROFILE', 'MAKER_DELETE', 'ACTIVE', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (554, 'LIMITPROFILE', 'MAKER_DELETE', 'REJECTED_DELETE', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
	
insert into tr_state_matrix values
((select max(stateid)+1 from tr_state_matrix where stateins = 'LIMITPROFILE'), 
'LIMITPROFILE', 'MAKER_DIRECT_UPDATE', 'NEW', 'NEW', 'NEW', '1', '1');

insert into tr_state_matrix values
((select max(stateid)+1 from tr_state_matrix where stateins = 'LIMITPROFILE'), 
'LIMITPROFILE', 'MAKER_DIRECT_UPDATE', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');   
   
   
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3900, 'PROPIDX_FEED_GROUP', 'ACTION_MAKER_UPDATE', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3901, 'PROPIDX_FEED_GROUP', 'ACTION_MAKER_SUBMIT', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3902, 'PROPIDX_FEED_GROUP', 'ACTION_MAKER_UPDATE_REJECTED', 'REJECTED', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3903, 'PROPIDX_FEED_GROUP', 'ACTION_MAKER_CLOSE_REJECTED', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3904, 'PROPIDX_FEED_GROUP', 'ACTION_CHECKER_APPROVE_PROPERTY_INDEX_FEED_GROUP', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3905, 'PROPIDX_FEED_GROUP', 'ACTION_CHECKER_REJECT_PROPERTY_INDEX_FEED_GROUP', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3906, 'PROPIDX_FEED_GROUP', 'ACTION_MAKER_UPDATE', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3907, 'PROPIDX_FEED_GROUP', 'ACTION_MAKER_SUBMIT', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3908, 'PROPIDX_FEED_GROUP', 'ACTION_MAKER_SUBMIT_REJECTED', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3909, 'PROPIDX_FEED_GROUP', 'ACTION_MAKER_CLOSE_DRAFT', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3800, 'STOCKIDX_FEED_GROUP', 'ACTION_MAKER_UPDATE', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3801, 'STOCKIDX_FEED_GROUP', 'ACTION_MAKER_SUBMIT', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3802, 'STOCKIDX_FEED_GROUP', 'ACTION_MAKER_UPDATE_REJECTED', 'REJECTED', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3803, 'STOCKIDX_FEED_GROUP', 'ACTION_MAKER_CLOSE_REJECTED', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3804, 'STOCKIDX_FEED_GROUP', 'ACTION_CHECKER_APPROVE_STOCK_INDEX_FEED_GROUP', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3805, 'STOCKIDX_FEED_GROUP', 'ACTION_CHECKER_REJECT_STOCK_INDEX_FEED_GROUP', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3806, 'STOCKIDX_FEED_GROUP', 'ACTION_MAKER_UPDATE', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3807, 'STOCKIDX_FEED_GROUP', 'ACTION_MAKER_SUBMIT', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3808, 'STOCKIDX_FEED_GROUP', 'ACTION_MAKER_SUBMIT_REJECTED', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3809, 'STOCKIDX_FEED_GROUP', 'ACTION_MAKER_CLOSE_DRAFT', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (800, 'STOCK_FEED_GROUP', 'ACTION_MAKER_UPDATE', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (801, 'STOCK_FEED_GROUP', 'ACTION_MAKER_SUBMIT', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (802, 'STOCK_FEED_GROUP', 'ACTION_MAKER_UPDATE_REJECTED', 'REJECTED', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (803, 'STOCK_FEED_GROUP', 'ACTION_MAKER_CLOSE_REJECTED', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (804, 'STOCK_FEED_GROUP', 'ACTION_CHECKER_APPROVE_STOCK_FEED_GROUP', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (805, 'STOCK_FEED_GROUP', 'ACTION_CHECKER_REJECT_STOCK_FEED_GROUP', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (806, 'STOCK_FEED_GROUP', 'ACTION_MAKER_UPDATE', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (807, 'STOCK_FEED_GROUP', 'ACTION_MAKER_SUBMIT', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (808, 'STOCK_FEED_GROUP', 'ACTION_MAKER_SUBMIT_REJECTED', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (809, 'STOCK_FEED_GROUP', 'ACTION_MAKER_CLOSE_DRAFT', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1101, 'TEAM', 'MAKER_CREATE_TEAM', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1102, 'TEAM', 'CHECKER_REJECT_CREATE_TEAM', 'PENDING_CREATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1103, 'TEAM', 'CHECKER_APPROVE_CREATE_TEAM', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1104, 'TEAM', 'MAKER_RESUBMIT_CREATE_TEAM', 'REJECTED', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1105, 'TEAM', 'MAKER_RESUBMIT_UPDATE_TEAM', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1106, 'TEAM', 'MAKER_RESUBMIT_DELETE_TEAM', 'REJECTED', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1107, 'TEAM', 'MAKER_CANCEL_CREATE_TEAM', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1108, 'TEAM', 'MAKER_CANCEL_UPDATE_TEAM', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1109, 'TEAM', 'MAKER_CANCEL_DELETE_TEAM', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1110, 'TEAM', 'CHECKER_APPROVE_UPDATE_TEAM', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1111, 'TEAM', 'CHECKER_REJECT_UPDATE_TEAM', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1112, 'TEAM', 'CHECKER_APPROVE_DELETE_TEAM', 'PENDING_DELETE', 'DELETED', 'DELETED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1113, 'TEAM', 'CHECKER_REJECT_DELETE_TEAM', 'PENDING_DELETE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1114, 'TEAM', 'MAKER_UPDATE_TEAM', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1115, 'TEAM', 'MAKER_DELETE_TEAM', 'ACTIVE', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3700, 'UNITTRUST_FEED_GROUP', 'ACTION_MAKER_UPDATE', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3701, 'UNITTRUST_FEED_GROUP', 'ACTION_MAKER_SUBMIT', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3702, 'UNITTRUST_FEED_GROUP', 'ACTION_MAKER_UPDATE_REJECTED', 'REJECTED', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3703, 'UNITTRUST_FEED_GROUP', 'ACTION_MAKER_CLOSE_REJECTED', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3704, 'UNITTRUST_FEED_GROUP', 'ACTION_CHECKER_APPROVE_UNIT_TRUST_FEED_GROUP', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3705, 'UNITTRUST_FEED_GROUP', 'ACTION_CHECKER_REJECT_UNIT_TRUST_FEED_GROUP', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3706, 'UNITTRUST_FEED_GROUP', 'ACTION_MAKER_UPDATE', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3707, 'UNITTRUST_FEED_GROUP', 'ACTION_MAKER_SUBMIT', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3708, 'UNITTRUST_FEED_GROUP', 'ACTION_MAKER_SUBMIT_REJECTED', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3709, 'UNITTRUST_FEED_GROUP', 'ACTION_MAKER_CLOSE_DRAFT', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1000, 'USER', 'ADD_USER', 'ND', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1001, 'USER', 'MAKER_CREATE_USER', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1002, 'USER', 'CHECKER_REJECT_CREATE', 'PENDING_CREATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1003, 'USER', 'CHECKER_APPROVE_CREATE', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1004, 'USER', 'MAKER_RESUBMIT_CREATE', 'REJECTED', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1005, 'USER', 'MAKER_RESUBMIT_UPDATE', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1006, 'USER', 'MAKER_RESUBMIT_DELETE', 'REJECTED', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1007, 'USER', 'MAKER_CANCEL_CREATE', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1008, 'USER', 'MAKER_CANCEL_UPDATE', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1009, 'USER', 'MAKER_CANCEL_DELETE', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1010, 'USER', 'CHECKER_APPROVE_UPDATE', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1011, 'USER', 'CHECKER_REJECT_UPDATE', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1012, 'USER', 'CHECKER_APPROVE_DELETE', 'PENDING_DELETE', 'DELETED', 'DELETED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1013, 'USER', 'CHECKER_REJECT_DELETE', 'PENDING_DELETE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1014, 'USER', 'MAKER_UPDATE_USER', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1015, 'USER', 'MAKER_DELETE_USER', 'ACTIVE', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1016, 'USER', 'UPDATE_USER', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');

Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (200, 'VAL', 'MANUAL_FEEDS_CREATE', 'ND', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (201, 'VAL', 'MANUAL_CREATE', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (202, 'VAL', 'CHECKER_APPROVE', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (203, 'VAL', 'CHECKER_REJECT', 'PENDING_CREATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (204, 'VAL', 'MANUAL_UPDATE', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (205, 'VAL', 'MANUAL_RESUBMIT_CREATE', 'REJECTED', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (206, 'VAL', 'CHECKER_REJECT', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (207, 'VAL', 'MANUAL_RESUBMIT_UPDATE', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (208, 'VAL', 'CHECKER_APPROVE', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (209, 'VAL', 'MANUAL_CANCEL_CREATE', 'REJECTED', 'CANCELLED', 'CANCELLED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (210, 'VAL', 'MANUAL_CANCEL_UPDATE', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (211, 'VAL', 'MANUAL_FEEDS_UPDATE', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (212, 'VAL', 'SYSTEM_CLOSE', 'PENDING_CREATE', 'CLOSED', 'CLOSED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (213, 'VAL', 'SYSTEM_CLOSE', 'ACTIVE', 'CLOSED', 'CLOSED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (214, 'VAL', 'SYSTEM_CLOSE', 'PENDING_UPDATE', 'CLOSED', 'CLOSED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (215, 'VAL', 'SYSTEM_CLOSE', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (216, 'VAL', 'SYSTEM_CREATE', 'ND', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (217, 'VAL', 'SYSTEM_UPDATE', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');

--  Create transaction state matrix for Maintain Marketability Factor Checklist module 
INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5901, 'MF_CHECKLIST', 'MAKER_CREATE', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5902, 'MF_CHECKLIST', 'MAKER_CREATE', 'DRAFT', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
 
INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5903, 'MF_CHECKLIST', 'MAKER_CREATE', 'REJECTED_CREATE', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5904, 'MF_CHECKLIST', 'MAKER_UPDATE', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5905, 'MF_CHECKLIST', 'MAKER_UPDATE', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
 
INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5906, 'MF_CHECKLIST', 'MAKER_UPDATE', 'REJECTED_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5907, 'MF_CHECKLIST', 'MAKER_CLOSE', 'DRAFT', 'CLOSED', 'CLOSED', '1', '1');
 
INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5908, 'MF_CHECKLIST', 'MAKER_CLOSE', 'REJECTED_CREATE', 'CLOSED', 'CLOSED', '1', '1');
  
INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5909, 'MF_CHECKLIST', 'MAKER_CLOSE_UPDATE', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5910, 'MF_CHECKLIST', 'MAKER_CLOSE_UPDATE', 'REJECTED_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5911, 'MF_CHECKLIST', 'CHECKER_APPROVE', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5912, 'MF_CHECKLIST', 'CHECKER_APPROVE', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
  
INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5913, 'MF_CHECKLIST', 'CHECKER_REJECT', 'PENDING_CREATE', 'REJECTED_CREATE', 'REJECTED_CREATE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5914, 'MF_CHECKLIST', 'CHECKER_REJECT', 'PENDING_UPDATE', 'REJECTED_UPDATE', 'REJECTED_UPDATE', '1', '1');   
	
	
--  Create transaction state matrix for Maintain Marketability Factor Template module 
INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5801, 'MF_TEMPLATE', 'MAKER_CREATE', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5802, 'MF_TEMPLATE', 'MAKER_CREATE', 'DRAFT', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
 
INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5803, 'MF_TEMPLATE', 'MAKER_CREATE', 'REJECTED_CREATE', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5804, 'MF_TEMPLATE', 'MAKER_UPDATE', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5805, 'MF_TEMPLATE', 'MAKER_UPDATE', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
 
INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5806, 'MF_TEMPLATE', 'MAKER_UPDATE', 'REJECTED_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5807, 'MF_TEMPLATE', 'MAKER_DELETE', 'ACTIVE', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');

INSERT INTO TR_STATE_MATRIX
     ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
 VALUES
     (5808, 'MF_TEMPLATE', 'MAKER_DELETE', 'REJECTED_DELETE', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5809, 'MF_TEMPLATE', 'MAKER_CLOSE', 'DRAFT', 'CLOSED', 'CLOSED', '1', '1');
 
INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5810, 'MF_TEMPLATE', 'MAKER_CLOSE', 'REJECTED_CREATE', 'CLOSED', 'CLOSED', '1', '1');
  
INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5811, 'MF_TEMPLATE', 'MAKER_CLOSE_UPDATE', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5812, 'MF_TEMPLATE', 'MAKER_CLOSE_UPDATE', 'REJECTED_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5813, 'MF_TEMPLATE', 'MAKER_CLOSE_UPDATE', 'REJECTED_DELETE', 'ACTIVE', 'ACTIVE', '1', '1');
 
INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5814, 'MF_TEMPLATE', 'CHECKER_APPROVE', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5815, 'MF_TEMPLATE', 'CHECKER_APPROVE', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
  
INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5816, 'MF_TEMPLATE', 'CHECKER_APPROVE', 'PENDING_DELETE', 'CLOSED', 'CLOSED', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5817, 'MF_TEMPLATE', 'CHECKER_REJECT', 'PENDING_CREATE', 'REJECTED_CREATE', 'REJECTED_CREATE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5818, 'MF_TEMPLATE', 'CHECKER_REJECT', 'PENDING_UPDATE', 'REJECTED_UPDATE', 'REJECTED_UPDATE', '1', '1');

INSERT INTO TR_STATE_MATRIX
    ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
VALUES
    (5819, 'MF_TEMPLATE', 'CHECKER_REJECT', 'PENDING_DELETE', 'REJECTED_DELETE', 'REJECTED_DELETE', '1', '1');	

Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1500, 'RECURRENT_CHECKLIST', 'CREATE_RECURRENT_CHECKLIST', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1501, 'RECURRENT_CHECKLIST', 'APPROVE_CREATE_RECURRENT_CHECKLIST', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1502, 'RECURRENT_CHECKLIST', 'REJECT_RECURRENT_CHECKLIST', 'PENDING_CREATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1503, 'RECURRENT_CHECKLIST', 'EDIT_REJECTED_CREATE_RECURRENT_CHECKLIST', 'REJECTED', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1504, 'RECURRENT_CHECKLIST', 'CLOSE_REJECTED_CREATE_RECURRENT_CHECKLIST', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1505, 'RECURRENT_CHECKLIST', 'UPDATE_RECURRENT_CHECKLIST', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1506, 'RECURRENT_CHECKLIST', 'REJECT_RECURRENT_CHECKLIST', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1507, 'RECURRENT_CHECKLIST', 'EDIT_REJECTED_UPDATE_RECURRENT_CHECKLIST', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1508, 'RECURRENT_CHECKLIST', 'APPROVE_UPDATE_RECURRENT_CHECKLIST', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1509, 'RECURRENT_CHECKLIST', 'CLOSE_REJECTED_UPDATE_RECURRENT_CHECKLIST', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1510, 'RECURRENT_CHECKLIST', 'REJECT_RECURRENT_CHECKLIST_RECEIPT', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1511, 'RECURRENT_CHECKLIST', 'UPDATE_RECURRENT_CHECKLIST_RECEIPT', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1512, 'RECURRENT_CHECKLIST', 'EDIT_REJECTED_UPDATE_RECURRENT_CHECKLIST_RECEIPT', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1513, 'RECURRENT_CHECKLIST', 'APPROVE_UPDATE_RECURRENT_CHECKLIST_RECEIPT', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1514, 'RECURRENT_CHECKLIST', 'CLOSE_REJECTED_UPDATE_RECURRENT_CHECKLIST_RECEIPT', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1515, 'RECURRENT_CHECKLIST', 'SYSTEM_CLOSE_RECURRENT_CHECKLIST', 'ACTIVE', 'CLOSED', 'CLOSED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1516, 'RECURRENT_CHECKLIST', 'SYSTEM_CLOSE_RECURRENT_CHECKLIST', 'PENDING_CREATE', 'CLOSED', 'CLOSED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1517, 'RECURRENT_CHECKLIST', 'SYSTEM_CLOSE_RECURRENT_CHECKLIST', 'PENDING_UPDATE', 'CLOSED', 'CLOSED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1518, 'RECURRENT_CHECKLIST', 'SYSTEM_CLOSE_RECURRENT_CHECKLIST', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1519, 'RECURRENT_CHECKLIST', 'CLOSE_DRAFT_RECURRENT_CHECKLIST_RECEIPT', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1520, 'RECURRENT_CHECKLIST', 'SAVE_RECURRENT_CHECKLIST_RECEIPT', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1521, 'RECURRENT_CHECKLIST', 'SAVE_RECURRENT_CHECKLIST_RECEIPT', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1522, 'RECURRENT_CHECKLIST', 'SAVE_RECURRENT_CHECKLIST_RECEIPT', 'REJECTED', 'DRAFT', 'DRAFT', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1523, 'RECURRENT_CHECKLIST', 'UPDATE_RECURRENT_CHECKLIST_RECEIPT', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1524, 'RECURRENT_CHECKLIST', 'SAVE_CREATE_RECURRENT_CHECKLIST', 'ND', 'DRAFT', 'DRAFT', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1525, 'RECURRENT_CHECKLIST', 'DRAFT_CREATE_RECURRENT_CHECKLIST', 'DRAFT', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1526, 'RECURRENT_CHECKLIST', 'DRAFT_SAVE_RECURRENT_CHECKLIST', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1527, 'RECURRENT_CHECKLIST', 'CLOSE_DRAFT_CREATE_RECURRENT_CHECKLIST', 'DRAFT', 'CLOSE', 'CLOSE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1528, 'RECURRENT_CHECKLIST', 'DRAFT_SAVE_RECURRENT_CHECKLIST', 'REJECTED', 'DRAFT', 'DRAFT', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1529, 'RECURRENT_CHECKLIST', 'DRAFT_UPDATE_RECURRENT_CHECKLIST', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1530, 'RECURRENT_CHECKLIST', 'SAVE_ACTIVE_RECURRENT_CHECKLIST', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1531, 'RECURRENT_CHECKLIST', 'CLOSE_DRAFT_ACTIVE_RECURRENT_CHECKLIST', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');
insert into tr_state_matrix 
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
values
    (1532,'RECURRENT_CHECKLIST','SYSTEM_CREATE_RECURRENT_CHECKLIST','ND','ACTIVE','ACTIVE','1','1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES  
(8000, 'TEAM_FUNCTION_GRP', 'ACTION_MAKER_SUBMIT_CREATE', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES 
(8001, 'TEAM_FUNCTION_GRP', 'ACTION_MAKER_SUBMIT_UPDATE', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES 
(8002, 'TEAM_FUNCTION_GRP', 'ACTION_CHECKER_APPROVE_TEAM_FUNCTION_GRP', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES 
(8003, 'TEAM_FUNCTION_GRP', 'ACTION_CHECKER_APPROVE_TEAM_FUNCTION_GRP', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES 
(8004, 'TEAM_FUNCTION_GRP', 'ACTION_CHECKER_REJECT_TEAM_FUNCTION_GRP', 'PENDING_CREATE', 'REJECTED', 'REJECTED', '1', '1');
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES 
(8005, 'TEAM_FUNCTION_GRP', 'ACTION_CHECKER_REJECT_TEAM_FUNCTION_GRP', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES 
(8006, 'TEAM_FUNCTION_GRP', 'ACTION_MAKER_CLOSE_REJECTED', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES 
(8007, 'TEAM_FUNCTION_GRP', 'ACTION_MAKER_SUBMIT_REJECTED', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES 
(8008, 'TEAM_FUNCTION_GRP', 'ACTION_MAKER_SUBMIT_UPDATE', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES 
(8009, 'TEAM_FUNCTION_GRP', 'SYSTEM_CLOSE', 'PENDING_CREATE', 'CLOSED', 'CLOSED', '1', '1');
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES 
(8010, 'TEAM_FUNCTION_GRP', 'SYSTEM_CLOSE', 'PENDING_UPDATE', 'CLOSED', 'CLOSED', '1', '1');
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES 
(8011, 'TEAM_FUNCTION_GRP', 'SYSTEM_CLOSE', 'ACTIVE', 'CLOSED', 'CLOSED', '1', '1');
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES 
(8012, 'TEAM_FUNCTION_GRP', 'SYSTEM_CLOSE', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) VALUES 
(8013, 'TEAM_FUNCTION_GRP', 'SYSTEM_CLOSE', 'DRAFT', 'CLOSED', 'CLOSED', '1', '1');

COMMIT WORK;

