DROP TABLE HP_TEMP_PF100;
CREATE TABLE HP_TEMP_PF100(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  ADD_TYPE VARCHAR(1) NOT NULL,
  ADD_TYPE_DESC VARCHAR(40)
)in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF101;
CREATE TABLE HP_TEMP_PF101(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  COUNTRY_CODE VARCHAR(3) NOT NULL,
  COUNTRY_NAME VARCHAR(20) 
)in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF102;
CREATE TABLE HP_TEMP_PF102(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  COUNTRY_CODE VARCHAR(3) ,
  STATE_CODE VARCHAR(3) NOT NULL,
  STATE_NAME VARCHAR(20)   
)in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF103;
CREATE TABLE HP_TEMP_PF103(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  VIP_CODE VARCHAR(2) NOT NULL,
  VIP_DESC VARCHAR(40)
)in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF104;
CREATE TABLE HP_TEMP_PF104(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  JOB_DESIG_CODE VARCHAR(5) NOT NULL,
  JOB_DESIG_DESC VARCHAR(40)
)in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF105;
CREATE TABLE HP_TEMP_PF105(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  ID_NUM_CODE VARCHAR(3) NOT NULL,
  ID_NUM_DESC VARCHAR(50)
)in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF106;
CREATE TABLE HP_TEMP_PF106(
  RECORD_TYPE VARCHAR(1)  DEFAULT'D',
  INSIDER_CODE VARCHAR(1) NOT NULL,
  INSIDER_DESC VARCHAR(20)
)in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF107;
CREATE TABLE HP_TEMP_PF107(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  ELEC_ADDR_CODE VARCHAR(2) NOT NULL,
  ELEC_ADDR_DESC VARCHAR(40)
)in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF108;
CREATE TABLE HP_TEMP_PF108(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  MARITAL_STAT_CODE VARCHAR(1) NOT NULL,
  MARITAL_DESC VARCHAR(15)
)in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF109;
CREATE TABLE HP_TEMP_PF109(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  BUSINESS_TYPE VARCHAR(4) NOT NULL,
  STD_IND_NAME VARCHAR(40)
)in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF110;
CREATE TABLE HP_TEMP_PF110(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  BRANCH_NUM BIGINT NOT NULL,
  FIS_BRANCH_ID VARCHAR(3) ,
  BANK_BRANCH_NAME VARCHAR(40) ,
  BANK_BRANCH_ID_NUM VARCHAR(40) ,
  SPTF_BRANCH_ID_NUM VARCHAR(40) ,
  BRANCH_OPEN_DATE BIGINT ,
  COUNTRY_CODE VARCHAR(3) ,
  STATE_CODE VARCHAR(3)
--   MASB_TAG VARCHAR(1)
)in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF111;
CREATE TABLE HP_TEMP_PF111(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  CLASS_CODE VARCHAR(1) NOT NULL,
  CLASS_DESC VARCHAR(20)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF112;
CREATE TABLE HP_TEMP_PF112(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  LPCCOD BIGINT NOT NULL
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF113;
CREATE TABLE HP_TEMP_PF113(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  FACILITY_CODE VARCHAR(3) NOT NULL,
  LOAN_TYPE VARCHAR(10) ,
  CURRENCY VARCHAR(4) ,
  ACCOUNT_TYPE VARCHAR(1) ,
  REVOLVING_IND VARCHAR(1) ,
  REV_OS_BAL_ORGAMT VARCHAR(1) ,
  DESCRIPTION VARCHAR(50)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF114;
CREATE TABLE HP_TEMP_PF114(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  LOAN_TYPE VARCHAR(10) NOT NULL,
  TYPE_DESC VARCHAR(20) ,
  GRP_CODE VARCHAR(3) ,
  GRP_DESC VARCHAR(20) ,
  COMM_RETAIL VARCHAR(1) ,
  INTEREST_BASE BIGINT ,
  CURRENCY_TYPE VARCHAR(4) ,
  MIN_INT_RATE DECIMAL(11,9) ,
  MAX_INT_RATE DECIMAL(11,9) ,
  RATE_FLOOR DECIMAL(11,9) ,
  RATE_CEILING DECIMAL(11,9) ,
  PAYMENT_FREQ BIGINT,
  PAYMENT_FREQ_CODE VARCHAR(1) ,
  PAYMENT_CODE BIGINT,
  REBATE_METH VARCHAR(1) ,
  STAFF_IND VARCHAR(1) ,
  ACT_IND VARCHAR(1) ,
  M_O_I VARCHAR(1) ,
  TIER_LOAN VARCHAR(1) ,
  SPTF_LOAN_TYPE VARCHAR(1) ,
  CONCEPT_CODE VARCHAR(1) ,
  DEF_PRIME_RATE BIGINT ,
  PROD_LIMIT DECIMAL(15,2) ,
  PROD_EXP_DATE BIGINT ,
  PROD_GRP VARCHAR(2) ,
  PROD_AGE_LMT BIGINT ,
  DEALER_PROD VARCHAR(1)
--   PROMO_PKG_CODE VARCHAR(1) ,
--   GRAT_FINANCING VARCHAR(1) ,
--   MAX_LOAN_TENU BIGINT ,
--   MIN_LOAN_TENU BIGINT
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF115;
CREATE TABLE HP_TEMP_PF115(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  PURPOSE_CODE VARCHAR(2) NOT NULL,
  PURPOSE_DESC VARCHAR(60)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF116;
CREATE TABLE HP_TEMP_PF116(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  DESIG_CODE VARCHAR(10) NOT NULL,
  DESCRIPTION VARCHAR(50)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF117;
CREATE TABLE HP_TEMP_PF117(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
--   CALCEL_CODE VARCHAR(2) NOT NULL,
  DESCRIPTION VARCHAR(40) ,
  REASON_CODE VARCHAR(1)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF118;
CREATE TABLE HP_TEMP_PF118(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  OFFICER_CODE VARCHAR(10) NOT NULL,
  BRANCH_NUM BIGINT ,
  OFFICER_NAME VARCHAR(40)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF119;
CREATE TABLE HP_TEMP_PF119(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  LMT_STATUS VARCHAR(2) NOT NULL,
  LMT_STATUS_DESC VARCHAR(40)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF120;
CREATE TABLE HP_TEMP_PF120(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  RATE_NUM BIGINT NOT NULL,
  CURR_RATE DECIMAL(11,9),
  RATE_DESC VARCHAR(50)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF121;
CREATE TABLE HP_TEMP_PF121(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  DEALER_NUM BIGINT NOT NULL,
  DEALER_NAME VARCHAR(40) ,
  DEALER_SHORT_NAME VARCHAR(20) ,
  FMT_SHORT_NAME VARCHAR(20) ,
  DEALER_CIF_NUM BIGINT ,
  DEALER_ADD1 VARCHAR(40) ,
  DEALER_ADD2 VARCHAR(40) ,
  DEALER_ADD3 VARCHAR(40) ,
  DEALER_PHONE VARCHAR(30) ,
  DEALER_PHONE2 VARCHAR(30) ,
  DEALER_LMT DECIMAL(15,2) ,
  DEALER_RSV_AMT DECIMAL(15,2) ,
  DEALER_AMT_UTL DECIMAL(15,2) ,
  DEALER_PLAN VARCHAR(1) ,
  DEALER_GRP VARCHAR(10) ,
  OFFICER_CODE VARCHAR(10) ,
  DEALER_EXP_DATE BIGINT ,
  REVOLVING_IND BIGINT ,
  DEALER_ACC_PERC DECIMAL(11,9) ,
  DEALER_STATUS VARCHAR(2) ,
  DATE_RECR BIGINT ,
  MIN_INT_DAY BIGINT ,
  INT_SUB_DAY BIGINT ,
  PRODUCT_GRP VARCHAR(2) ,
  BRANCH_SERV BIGINT ,
  GRO_DEV_VAL DECIMAL(15,2) ,
  GRO_DEV_COST DECIMAL(15,2) ,
  SEC_VAL DECIMAL(15,2) ,
  UND_LIM_FBR DECIMAL(15,2) ,
  UND_LIM_FBT DECIMAL(15,2) ,
  RECOND VARCHAR(1) ,
  USED VARCHAR(1) ,
  NEW VARCHAR(1) ,
  NEW_NTL VARCHAR(1) ,
  DEALER_STATUS2 VARCHAR(1) ,
  DEALER_STATUS_DATE BIGINT ,
  RESCHDL_IND VARCHAR(1) ,
  DEL_RATE DECIMAL(11,9) ,
  FIS_MEMBER VARCHAR(1) ,
  FIS_DEALER_CODE VARCHAR(10) ,
  REMARKS VARCHAR(50)
--   DEALER_PROJECT_TYPE VARCHAR(1)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF122;
CREATE TABLE HP_TEMP_PF122(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  SRC_CODE VARCHAR(10) NOT NULL,
  DESCRIPTION VARCHAR(40)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF123;
CREATE TABLE HP_TEMP_PF123(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  LAWY_ID_CODE VARCHAR(10) NOT NULL,
  LAWY_TYPE VARCHAR(1) ,
  LAWY_REF_NUM VARCHAR(40) ,
  LAWY_NAME VARCHAR(40) ,
  LAWY_STATUS VARCHAR(1) ,
  REMARKS VARCHAR(50)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF124;
CREATE TABLE HP_TEMP_PF124(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  DEPT_CODE VARCHAR(5) NOT NULL,
  DEPT_DESC VARCHAR(40)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF125;
CREATE TABLE HP_TEMP_PF125(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  BANK_CODE VARCHAR(10) NOT NULL,
  BANK_DESC VARCHAR(40)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF126;
CREATE TABLE HP_TEMP_PF126(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  REL_CODE VARCHAR(2) NOT NULL,
  TEXT VARCHAR(50)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF127;
CREATE TABLE HP_TEMP_PF127(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  CUST_CODE VARCHAR(4) NOT NULL,
  ECON_SECT_DESC VARCHAR(120) ,
  SUMM_O_DETAIL VARCHAR(1)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF128;
CREATE TABLE HP_TEMP_PF128(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  CUST_CODE VARCHAR(2) NOT NULL,
  CUST_DESC VARCHAR(60) ,
  SUMM_O_DETAIL VARCHAR(1)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF129;
CREATE TABLE HP_TEMP_PF129(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  STATE_CODE VARCHAR(1) NOT NULL,
  STATE_DESC VARCHAR(40)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF130;
CREATE TABLE HP_TEMP_PF130(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  DFT_BUMI_NRCC_CODE VARCHAR(1) NOT NULL,
  DESCRIPTION VARCHAR(150)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF131;
CREATE TABLE HP_TEMP_PF131(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  LOAN_SEC_MIX VARCHAR(2) NOT NULL,
  DESCRIPTION VARCHAR(60)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF132;
CREATE TABLE HP_TEMP_PF132(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  COLL_TYPE_CODE VARCHAR(2) NOT NULL,
  DESCRIPTION VARCHAR(60)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF133;
CREATE TABLE HP_TEMP_PF133(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  COLL_ISSUER_CODE VARCHAR(2) NOT NULL,
  DESCRIPTION VARCHAR(60)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF134;
CREATE TABLE HP_TEMP_PF134(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  REL_CODE VARCHAR(2) NOT NULL,
  DESCRIPTION VARCHAR(20)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF135;
CREATE TABLE HP_TEMP_PF135(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  OFFICER_TYPE VARCHAR(3) NOT NULL,
  OFFICER_IND VARCHAR(1) ,
  TYPE_DESC VARCHAR(50)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF136;
CREATE TABLE HP_TEMP_PF136(
  RECORD_TYPE VARCHAR(1) DEFAULT 'D',
  TYPE_INS_CODE BIGINT NOT NULL,
  DESCRIPTION VARCHAR(40)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF137;
CREATE TABLE HP_TEMP_PF137(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  INS_NUM BIGINT NOT NULL,
  INS_NAME VARCHAR(40) ,
  INS_ADDR VARCHAR(40) ,
  INS_CITY_STATE VARCHAR(40) ,
  INS_CO_PHONE_NUM VARCHAR(30) ,
  RSV_PERC DECIMAL(11,9) ,
  PANEL_IND VARCHAR(1)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF138;
CREATE TABLE HP_TEMP_PF138(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  HOLD_MAIL_CODE VARCHAR(1) NOT NULL,
  HOLD_MAIL_DESC VARCHAR(40)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF139;
CREATE TABLE HP_TEMP_PF139(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  OFFICER_REL_CODE VARCHAR(2) NOT NULL,
  OFFICER_RELL_DESC VARCHAR(40)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF140;
CREATE TABLE HP_TEMP_PF140(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  DEP_TYPE_CODE VARCHAR(10) NOT NULL,
  CURR_TYPE VARCHAR(4) ,
  TYPE_DESC VARCHAR(20) ,
  GROUP_CODE BIGINT ,
  INT_FREE_BANKING VARCHAR(1)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF141;
CREATE TABLE HP_TEMP_PF141(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  CAR_CODE VARCHAR(2) NOT NULL,
  DESCRIPTION VARCHAR(20)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF142;
CREATE TABLE HP_TEMP_PF142(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  MSG_TYPE_CODE VARCHAR(3) NOT NULL,
  MSG_TEXT VARCHAR(50)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF143;
CREATE TABLE HP_TEMP_PF143(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  MSG_SEVERITY BIGINT NOT NULL,
  DESCRIPTION VARCHAR(40)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF144;
CREATE TABLE HP_TEMP_PF144(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  ETH_CODE VARCHAR(3) NOT NULL,
  ETH_DESC VARCHAR(50)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF145;
CREATE TABLE HP_TEMP_PF145(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  TRANS_ROUT_NUM BIGINT NOT NULL,
  BANK_NAME VARCHAR(40)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF146;
CREATE TABLE HP_TEMP_PF146(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  GOLD_CODE VARCHAR(3) NOT NULL,
  GRADE VARCHAR(20)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF147;
CREATE TABLE HP_TEMP_PF147(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  ITEM_TYPE VARCHAR(3) NOT NULL,
  ITEM_DESC VARCHAR(20)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF148;
CREATE TABLE HP_TEMP_PF148(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  TYPE_UNIT VARCHAR(3) NOT NULL,
  DESCRIPTION VARCHAR(40)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF149;
CREATE TABLE HP_TEMP_PF149(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  PROP_TYPE VARCHAR(3) NOT NULL,
  PROP_TYPE_DESC VARCHAR(40)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF150;
CREATE TABLE HP_TEMP_PF150(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  LPECOD VARCHAR(3) NOT NULL,
  LPEDSC VARCHAR(20)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF151;
CREATE TABLE HP_TEMP_PF151(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  MAKE VARCHAR(20) NOT NULL,
  MODEL_NUM VARCHAR(20) NOT NULL,
  YEAR_MANUF BIGINT NOT NULL
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF152;
CREATE TABLE HP_TEMP_PF152(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  SHARE_COUNT VARCHAR(20) NOT NULL,
  DESCRIPTION VARCHAR(40)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF153;
CREATE TABLE HP_TEMP_PF153(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  DEALER_GRP VARCHAR(10) NOT NULL,
  DESCRIPTION VARCHAR(40)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF154;
CREATE TABLE HP_TEMP_PF154(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  COUNTRY_CODE VARCHAR(3) NOT NULL,
  STATE_CODE VARCHAR(3) ,
  HOL_DATE BIGINT NOT NULL,
  HOL_DESC VARCHAR(40)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF155;
CREATE TABLE HP_TEMP_PF155(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  BUSI_DAY_FLAG VARCHAR(1) ,
  CURR_PROC_JULI BIGINT ,
  CAL_BRANCH BIGINT
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF156;
CREATE TABLE HP_TEMP_PF156(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  VALUER_CODE VARCHAR(5) NOT NULL,
  VALUER_NAME VARCHAR(40)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF157;
CREATE TABLE HP_TEMP_PF157(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  FAC_NAME VARCHAR(3) ,
  LOAN_TYPE VARCHAR(10) NOT NULL,
  CURR_TYPE VARCHAR(4)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF158;
CREATE TABLE HP_TEMP_PF158(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  BANK_NUM BIGINT ,
  CAP_FUND DECIMAL(17,2) ,
  DATE_LAST_MAINT TIMESTAMP
--   ISCL_SEC_LOAN DECIMAL(7,4) ,
--   ISCL_UNSEC_LOAN DECIMAL(7,4) ,
--   SEC_INDV DECIMAL(17,2) ,
--   UNSEC_INDV DECIMAL(17,2)
) in CMS_BATCH index in CMS_BATCH_INDEX;

-- DROP TABLE HP_TEMP_PF159;
-- CREATE TABLE HP_TEMP_PF159(
--   RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
--   SCHEME VARCHAR(10) NOT NULL,
--   DESCRIPTION VARCHAR(40)
-- ) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF159;
CREATE TABLE HP_TEMP_PF159(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  RATE_TYPE VARCHAR(3) NOT NULL,
  RATE_TYPE_DESC VARCHAR(50)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF160;
CREATE TABLE HP_TEMP_PF160(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  PEN_INT_TYPE BIGINT NOT NULL,
  DESCRIPTION VARCHAR(40)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF161;
CREATE TABLE HP_TEMP_PF161(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  TERR_CODE VARCHAR(3) NOT NULL,
  TERR_DESC VARCHAR(40)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF162;
CREATE TABLE HP_TEMP_PF162(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  LOAN_TYPE VARCHAR(10) ,
  CURR_TYPE VARCHAR(4) ,
  HP_AITAB_VAR_RATE VARCHAR(1)
) in CMS_BATCH index in CMS_BATCH_INDEX;

----

DROP TABLE HP_TEMP_PF200;
CREATE TABLE HP_TEMP_PF200(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  CODE VARCHAR(60) NOT NULL,
  DESCRIPTION VARCHAR(750) ,
  IS_DELETED VARCHAR(3)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF201;
CREATE TABLE HP_TEMP_PF201(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  CODE VARCHAR(60) NOT NULL,
  DESCRIPTION VARCHAR(750) ,
  IS_DELETED VARCHAR(3)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF202;
CREATE TABLE HP_TEMP_PF202(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  CODE VARCHAR(60) NOT NULL,
  DESCRIPTION VARCHAR(750) ,
  IS_DELETED VARCHAR(3)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF203;
CREATE TABLE HP_TEMP_PF203(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  CODE VARCHAR(60) NOT NULL,
  DESCRIPTION VARCHAR(750) ,
  IS_DELETED VARCHAR(3)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF204;
CREATE TABLE HP_TEMP_PF204(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  CODE VARCHAR(60) NOT NULL,
  DESCRIPTION VARCHAR(750) ,
  IS_DELETED VARCHAR(3)
) in CMS_BATCH index in CMS_BATCH_INDEX;

DROP TABLE HP_TEMP_PF205;
CREATE TABLE HP_TEMP_PF205(
  RECORD_TYPE VARCHAR(1)  DEFAULT 'D',
  CODE VARCHAR(60) NOT NULL,
  DESCRIPTION VARCHAR(750) ,
  IS_DELETED VARCHAR(3)
) in CMS_BATCH index in CMS_BATCH_INDEX;