--DROP TABLE SI_TEMP_QUAN_CU008;
--DROP TABLE SI_TEMP_QUAN_CU002;
--DROP TABLE SI_TEMP_QUAN_CA020;

CREATE TABLE SI_TEMP_QUAN_CU008( 
    RECORD_TYPE VARCHAR(1),
    CIF_ID VARCHAR(19),
    CUST_NAME_LONG VARCHAR(120),
	CUST_NAME_SHORT VARCHAR(80),
	CUST_CLASS_CAT VARCHAR(20) DEFAULT '56',
	CUST_CLASS_CODE VARCHAR(3),	
	CUST_CLASS_DESC VARCHAR(50),
    ID_ISSUE_COUNTRY VARCHAR(2), 
    ID_TYPE_CAT VARCHAR(20) DEFAULT 'ID_TYPE',
    ID_TYPE_CODE VARCHAR(3),    
    ID_NUMBER VARCHAR(40),
    SECONDARY_ID_TYPE_CAT VARCHAR(20) DEFAULT 'ID_TYPE',
    SECONDARY_ID_TYPE_CODE VARCHAR(3),    
    SECONDARY_ID_NUMBER VARCHAR(40),
    CUST_TYPE_CAT  VARCHAR(20) DEFAULT '8',
	CUST_TYPE_CODE  VARCHAR(1),
	CUST_SEGMENT_CAT VARCHAR(20) DEFAULT 'ID_TYPE',
	CUST_SEGMENT_CODE VARCHAR(5),  
	CUST_SEGMENT_DESC VARCHAR(40),  
	PRIMARY_ADD_TYPE_CAT VARCHAR(20) DEFAULT '4',
    PRIMARY_ADD_TYPE_CODE VARCHAR(1),    
    PRIMARY_ADD_1 VARCHAR(50),
    PRIMARY_ADD_2 VARCHAR(50),
    PRIMARY_ADD_3 VARCHAR(50),
	PRIMARY_ADD_4 VARCHAR(50),
    PRIMARY_POSTCODE VARCHAR(9),    
    PRIMARY_COUNTRY VARCHAR(2),
	IS_VALID CHAR(1) DEFAULT 'Y',
	CMS_LE_MAIN_PROFILE_ID BIGINT,
	CMS_LE_SUB_PROFILE_ID BIGINT)
	IN CMS_BATCH INDEX IN CMS_BATCH_INDEX;  
    
CREATE TABLE SI_TEMP_QUAN_CU002(
    RECORD_TYPE VARCHAR(1),
    CIF_ID VARCHAR(19),
    CREDIT_GRADE_TYPE_CAT VARCHAR(20) DEFAULT '18',
    CREDIT_GRADE_TYPE VARCHAR(1),
    CREDIT_GRADE_VALUE_CAT VARCHAR(20) DEFAULT '19',
    CREDIT_GRADE_VALUE VARCHAR(3),
    CREDIT_GRADE_EFFECTIVE_DATE TIMESTAMP,
	IS_VALID CHAR(1) DEFAULT 'Y',
	CMS_LE_MAIN_PROFILE_ID BIGINT)
	IN CMS_BATCH INDEX IN CMS_BATCH_INDEX;
    
CREATE TABLE SI_TEMP_QUAN_CA020(
    RECORD_TYPE VARCHAR(1),
    CIF_ID VARCHAR(19),
    MREX_CUST_IND VARCHAR(1),
    AA_NUMBER VARCHAR(19),
    EXPIRY_DATE TIMESTAMP,
    LIMIT_ID VARCHAR(43),
    OUTER_LIMIT_ID VARCHAR(43),
    ORI_LOC_ORG_CAT VARCHAR(20) DEFAULT '40',
    ORI_LOC_ORG_CODE VARCHAR(5),    
    ORI_LOC_ORG_DESC VARCHAR(40),
    LIMIT_CURRENCY VARCHAR(3),
    LIMIT_AMT DECIMAL(15,2),
    OUTSTANDING_AMT DECIMAL(15,2),
    PRODUCT_TYPE_CAT VARCHAR(20) DEFAULT '27',	
    PRODUCT_TYPE_CODE VARCHAR(10),
    PRODUCT_TYPE_DESC VARCHAR(50),
    LOAN_SECTOR_CODE VARCHAR(10) DEFAULT '0420',
    DISBURSED_IND VARCHAR(1) DEFAULT 'F',
	IS_VALID CHAR(1) DEFAULT 'Y',
	IS_OUTER_LMT CHAR(1) DEFAULT 'N',
	CMS_CUSTOMER_ID BIGINT,
    CMS_ACT_AA_ID BIGINT,
    CMS_STG_AA_ID BIGINT,
	CMS_OUTER_LIMIT_ID BIGINT,
	CMS_STG_OUTER_LIMIT_ID BIGINT,
	CMS_LIMIT_PROFILE_ID BIGINT,
	CMS_ACT_LMT_ID BIGINT,
    CMS_STG_LMT_ID BIGINT)
	IN CMS_BATCH INDEX IN CMS_BATCH_INDEX;   


-- create SI index

-- SI index for CU008   
		
CREATE INDEX SI_QUAN_CU008_IDX1 ON si_temp_quan_cu008
(CIF_ID ASC, IS_VALID ASC);   

create index SI_QUAN_CU008_IDX2 on si_temp_quan_cu008(cms_le_main_profile_id ASC);
create index SI_QUAN_CU008_IDX3 on si_temp_quan_cu008(cms_le_sub_profile_id ASC);

REORG INDEXES ALL FOR TABLE SI_TEMP_QUAN_CU008 ALLOW READ ACCESS;

-- SI index for CU002

CREATE INDEX SI_QUAN_CU002_IDX1 ON si_temp_quan_cu002
(IS_VALID ASC, CIF_ID ASC) allow reverse scans;

create index SI_QUAN_CU002_IDX2 on si_temp_quan_cu002(cms_le_main_profile_id ASC);

REORG INDEXES ALL FOR TABLE si_temp_quan_cu002 ALLOW READ ACCESS;

-- SI index for CA020

create index SI_QUAN_CA020_IDX1 on si_temp_quan_ca020 (limit_id asc, cms_act_lmt_id asc, is_valid asc)
allow reverse scans;

create index SI_QUAN_CA020_IDX2 on si_temp_quan_ca020 (limit_id asc, cms_stg_lmt_id asc, is_valid asc)
allow reverse scans;

create index SI_QUAN_CA020_IDX3 on si_temp_quan_ca020 (limit_id asc, is_valid asc)
allow reverse scans;

create index SI_QUAN_CA020_IDX4 on si_temp_quan_ca020(cms_act_lmt_id asc)
allow reverse scans;

create index SI_QUAN_CA020_IDX5 on si_temp_quan_ca020(cms_stg_lmt_id asc)
allow reverse scans;

REORG INDEXES ALL FOR TABLE si_temp_quan_ca020 ALLOW READ ACCESS;


COMMIT WORK;