--DROP TABLE SI_TEMP_BOST_CU005;
--DROP TABLE SI_TEMP_BOST_CA001;
--DROP TABLE SI_TEMP_BOST_CA015;
--DROP TABLE SI_TEMP_BOST_CO022;
--DROP TABLE SI_TEMP_BOST_CO022_PLEDGOR;
--DROP TABLE SI_TEMP_BOST_CO023;
--DROP TABLE SI_TEMP_BOST_CO025;
--DROP TABLE SI_TEMP_BOST_CO025_PLEDGOR;
--DROP TABLE SI_TEMP_BOST_SH001;

CREATE TABLE SI_TEMP_BOST_CU005 (
  RECORD_TYPE	VARCHAR(1),
  CIF_ID	VARCHAR(19),
  CUST_NAME_LONG	VARCHAR(120),
  CUST_NAME_SHORT	VARCHAR(80),
  CUST_CLASS_CAT	VARCHAR(10)	DEFAULT '56',
  CUST_CLASS_CODE	VARCHAR(7),
  CUST_CLASS_DESC	VARCHAR(40),
  ID_ISSUE_COUNTRY	VARCHAR(2),
  ID_TYPE_CAT	VARCHAR(10)	DEFAULT 'ID_TYPE',
  ID_TYPE_CODE	VARCHAR(3),
  ID_NUMBER	VARCHAR(12),
  ID_ISSUE_DATE	TIMESTAMP,
  SECONDARY_ID_TYPE_CAT	VARCHAR(10)	DEFAULT 'ID_TYPE',
  SECONDARY_ID_TYPE_CODE	VARCHAR(3),
  SECONDARY_ID_NUMBER	VARCHAR(40),
  CUST_TYPE	VARCHAR(1),
  CUST_START_DATE	TIMESTAMP,
  CUST_SEGMENT_CAT	VARCHAR(10)	DEFAULT '5',
  CUST_SEGMENT_CODE	VARCHAR(5),
  PRIMARY_ADD_TYPE_CAT	VARCHAR(10)	DEFAULT '4',
  PRIMARY_ADD_TYPE_CODE	VARCHAR(1),
  PRIMARY_ADD_1	VARCHAR(50),
  PRIMARY_ADD_2	VARCHAR(50),
  PRIMARY_ADD_3	VARCHAR(50),
  PRIMARY_ADD_4	VARCHAR(50),
  PRIMARY_ADD_5	VARCHAR(50),
  PRIMARY_POSTCODE	VARCHAR(9),
  PRIMARY_COUNTRY	VARCHAR(2),
	ISIC_CODE VARCHAR(4),
  UPDATE_STAT_IND	VARCHAR(1),
  IS_VALID	CHARACTER(1)	DEFAULT 'Y'
) 
  IN CMS_BATCH INDEX IN CMS_BATCH_INDEX;
	
CREATE TABLE SI_TEMP_BOST_CA001 (
  RECORD_TYPE	VARCHAR(1),
  CIF_ID	VARCHAR(19),
  CIF_SOURCE	VARCHAR(4),
  AA_NUMBER	VARCHAR(19),
  JOINT_BORROWER_IND	VARCHAR(1),
  AA_APPROVED_DATE	TIMESTAMP,
  ORI_LOC_COUNTRY	VARCHAR(2),
  ORI_LOC_ORG_CAT	VARCHAR(10)	DEFAULT '40',
  ORI_LOC_ORG_CODE	VARCHAR(5),
  ORI_LOC_ORG_DESC	VARCHAR(40),
  ANNUAL_REVIEW_DATE	TIMESTAMP,
  AA_STAT	VARCHAR(20),
  AA_CREATE_DATE	TIMESTAMP,
  UPDATE_STAT_IND	VARCHAR(1),
  IS_VALID	CHARACTER(1)	DEFAULT 'Y'
) 
  IN CMS_BATCH INDEX IN CMS_BATCH_INDEX;

CREATE TABLE SI_TEMP_BOST_CA015 (
  RECORD_TYPE	VARCHAR(1),
  CIF_ID	VARCHAR(19),
  AA_NUMBER	VARCHAR(19),
  LIMIT_ID	VARCHAR(19),
  EXPIRY_DATE	TIMESTAMP,
  ORI_LOC_COUNTRY	VARCHAR(2),
  ORG_LOC_ORG_CAT	VARCHAR(10)	DEFAULT '40',
  ORG_LOC_ORG_CODE	VARCHAR(5),
  ORG_LOC_ORG_DESC	VARCHAR(40),
  PRODUCT_TYPE_CAT	VARCHAR(10)	DEFAULT '27',
  PRODUCT_TYPE_CODE	VARCHAR(5),
  PRODUCT_TYPE_DESC	VARCHAR(40),
  LIMIT_CURRENCY	VARCHAR(3),
  LIMIT_AMT	DECIMAL(17,2),
  LIMIT_TENOR	BIGINT,
  LIMIT_TENOR_UNIT	VARCHAR(1),
  INTEREST_MARGIN	DECIMAL(17,6),
  AVAILABLE_LIMIT	DECIMAL(17,2),
  OUTSTANDING_AMT	DECIMAL(17,2),
  OUTSTANDING_AMT_SIGN	VARCHAR(1),
  LOAN_SECTOR_CODE	VARCHAR(10),
  LOAN_SECTOR_DESC	VARCHAR(60),
  DISBURSED_IND	VARCHAR(1),
  NPL_IND	VARCHAR(1),
  EQUITY_VAL	DECIMAL(17,2),
  EQUITY_VAL_SIGN	VARCHAR(1),
  IS_VALID	CHARACTER(1)	DEFAULT 'Y'
) 
  IN CMS_BATCH INDEX IN CMS_BATCH_INDEX;
	
CREATE TABLE SI_TEMP_BOST_CO022 (
  RECORD_TYPE	VARCHAR(1),
  SECURITY_ID	VARCHAR(29),
  CIF_ID	VARCHAR(19),
  SECURITY_TYPE	VARCHAR(2),
  CMS_SECURITY_TYPE_ID	VARCHAR(5),
  CMS_SECURITY_SUBTYPE_ID	VARCHAR(10),
  ORIGINAL_CURRENCY	VARCHAR(3),
  LOC_COUNTRY	VARCHAR(2),
  ORG_LOC_ORG_CAT	VARCHAR(10)	DEFAULT '40',
	ORG_LOC_ORG_CODE	VARCHAR(5),
	ORG_LOC_ORG_DESC	VARCHAR(40),
  SECURITY_CUSTODIAN_TYPE	VARCHAR(1),
  SECURITY_EXPIRY_DATE	TIMESTAMP,
  EXCHANGE_CONTROL_OBTAINED	VARCHAR(1),
  LEGAL_ENFORCEABILITY	VARCHAR(1),
  LEGAL_ENFORCEABILITY_DATE	TIMESTAMP,
  SECURITY_PERFECTION_DATE	TIMESTAMP,
  TYPE	VARCHAR(20),
  NOMINEE_NAME	VARCHAR(120),
  REGISTERED_NAME	VARCHAR(120),
  UNITS	BIGINT,
  UNITS_SIGN	VARCHAR(1),
  UNIT_PRICE	DECIMAL(10,6),
  CUSTODIAN_TYPE	VARCHAR(1),
  CUSTODIAN	VARCHAR(120),
  MATURITY_DATE	TIMESTAMP,
  STOCK_EXCHANGE	VARCHAR(3),
  STOCK_EXCHANGE_COUNTRY	VARCHAR(2),
  INDEX_NAME	VARCHAR(10),
  COUNTER_CODE	VARCHAR(14),
  STOCK_CODE	VARCHAR(14),
  ISIN_CODE	VARCHAR(20),
  RECOGNIZED_EXCHANGE	VARCHAR(1),
  CMS_COLLATERAL_ID	BIGINT,
  CMS_COLLATERAL_ID_STG	BIGINT,
  CMS_LSP_APPR_LMTS_ID	BIGINT,
	CMS_LIMIT_PROFILE_ID	BIGINT,
  CMS_PLEDGOR_DTL_ID	BIGINT,
  IS_VALID	CHARACTER(1)	DEFAULT 'Y'
) 
  IN CMS_BATCH INDEX IN CMS_BATCH_INDEX;
  
CREATE TABLE SI_TEMP_BOST_CO022_PLEDGOR (
  CIF_NUMBER	VARCHAR(19),
  PLEDGOR_CIF_SOURCE	VARCHAR(4),
  PLEDGOR_LEGAL_NAME	VARCHAR(80),
  INCORPORATION_COUNTRY	VARCHAR(2),
  ID_CAT	VARCHAR(10)	DEFAULT 'ID_TYPE',
  ID_TYPE	VARCHAR(3),
	INC_NUM_TEXT	VARCHAR(100)
) 
  IN CMS_BATCH INDEX IN CMS_BATCH_INDEX;


CREATE TABLE SI_TEMP_BOST_CO023 (
  RECORD_TYPE	VARCHAR(1),
  CIF	VARCHAR(19),
  SECURITY_ID	VARCHAR(29),
  SHARE_ID	VARCHAR(50),
  TRANSACTION_DATE	TIMESTAMP,
  SHARES_TYPE	VARCHAR(1),
  UNITS	BIGINT,
  SIGN_OF_UNITS	VARCHAR(1),
  COUNTER_CODE	VARCHAR(14),
  CMS_ITEM_ID BIGINT,
  IS_VALID	CHARACTER(1)	DEFAULT 'Y'
) 
  IN CMS_BATCH INDEX IN CMS_BATCH_INDEX;

CREATE TABLE SI_TEMP_BOST_CO025 (
  RECORD_TYPE	VARCHAR(1),
  CIF_NUMBER	VARCHAR(19),
  SECURITY_ID	VARCHAR(29),
  SECURITY_TYPE	VARCHAR(40),
  CURRENCY	VARCHAR(3),
  SECURITY_LOC	VARCHAR(2),
  --SECURITY_ORG	VARCHAR(5),
  ORG_LOC_ORG_CAT	VARCHAR(10)	DEFAULT '40',
	ORG_LOC_ORG_CODE VARCHAR(5),
	ORG_LOC_ORG_DESC VARCHAR(40),
  SECURITY_CUSTODIAN_TYPE	VARCHAR(1),
  SECURITY_CUSTODIAN_VALUE	VARCHAR(120),	
  LEGAL_ENFORCEABILITY_DATE	TIMESTAMP,
  SECURITY_PERFECTION_DATE	TIMESTAMP,
  INTEREST_CAPITALISATION	VARCHAR(1),
  DEPOSIT_RECEIPT_NO	VARCHAR(30),
  DEPOSIT_AMT	DECIMAL(17,2),
  SIGN_OF_DEPOSIT_AMT	VARCHAR(1),
  CMS_COLLATERAL_ID	BIGINT,
  CMS_COLLATERAL_ID_STG	BIGINT,
  CMS_LSP_APPR_LMTS_ID	BIGINT,
	CMS_LIMIT_PROFILE_ID	BIGINT,
  CMS_PLEDGOR_DTL_ID	BIGINT,
  IS_VALID	CHARACTER(1)	DEFAULT 'Y'
) 
  IN CMS_BATCH INDEX IN CMS_BATCH_INDEX;
  
CREATE TABLE SI_TEMP_BOST_CO025_PLEDGOR (
  CIF_NUMBER	VARCHAR(19),
  PLEDGOR_CIF_SOURCE	VARCHAR(4),
  PLEDGOR_LEGAL_NAME	VARCHAR(80),
  INCORPORATION_COUNTRY	VARCHAR(2),
  ID_CAT	VARCHAR(10)	DEFAULT 'ID_TYPE',
  ID_TYPE	VARCHAR(3),
	INC_NUM_TEXT	VARCHAR(100)
) 
  IN CMS_BATCH INDEX IN CMS_BATCH_INDEX;

CREATE TABLE SI_TEMP_BOST_SH001 (
  RECORD_TYPE	VARCHAR(1),
  COUNTER_CODE	VARCHAR(14),
  STOCK_CODE	VARCHAR(14),
  ISIN_CODE	VARCHAR(20),
  STOCK_EXCHANGE_CODE	VARCHAR(3),
  STOCK_EXCHANGE_COUNTRY	VARCHAR(2),
  TOTAL_NO_OF_UNIT	BIGINT,
  SIGN_OF_UNIT	VARCHAR(1),
  ISSUER_NAME	VARCHAR(40),
  IS_VALID	CHARACTER(1)	DEFAULT 'Y'
) 
  IN CMS_BATCH INDEX IN CMS_BATCH_INDEX;


CREATE INDEX SI_BOST_CU005_IDX1 ON SI_TEMP_BOST_CU005
(IS_VALID ASC, CIF_ID ASC, PRIMARY_ADD_TYPE_CODE ASC) ALLOW REVERSE SCANS;

CREATE INDEX SI_BOST_CA001_IDX1 ON SI_TEMP_BOST_CA001
(IS_VALID ASC, CIF_ID ASC, AA_NUMBER ASC) ALLOW REVERSE SCANS;

CREATE INDEX SI_BOST_CA015_IDX1 ON SI_TEMP_BOST_CA015
(IS_VALID ASC, CIF_ID ASC, AA_NUMBER ASC, LIMIT_ID ASC) ALLOW REVERSE SCANS;

CREATE INDEX SI_BOST_CO022_IDX1 ON SI_TEMP_BOST_CO022
(IS_VALID ASC, CIF_ID ASC, SECURITY_ID ASC) ALLOW REVERSE SCANS;

CREATE INDEX SI_BOST_CO022_PLDGR_IDX1 ON SI_TEMP_BOST_CO022_PLEDGOR
(CIF_NUMBER ASC) ALLOW REVERSE SCANS;

CREATE INDEX SI_BOST_CO023_IDX1 ON SI_TEMP_BOST_CO023
(IS_VALID ASC, SECURITY_ID ASC, SHARE_ID ASC) ALLOW REVERSE SCANS;

CREATE INDEX SI_BOST_CO025_IDX1 ON SI_TEMP_BOST_CO025
(IS_VALID ASC, CIF_NUMBER ASC, SECURITY_ID ASC, DEPOSIT_RECEIPT_NO ASC) ALLOW REVERSE SCANS;

CREATE INDEX SI_BOST_CO025_PLDGR_IDX1 ON SI_TEMP_BOST_CO025_PLEDGOR
(CIF_NUMBER ASC) ALLOW REVERSE SCANS;

CREATE INDEX SI_BOST_SH001_IDX1 ON SI_TEMP_BOST_SH001
(IS_VALID ASC, STOCK_CODE ASC, ISIN_CODE ASC, STOCK_EXCHANGE_CODE ASC) ALLOW REVERSE SCANS;

COMMIT;
