LOAD DATA
INFILE 'FILES\Insurance Master.csv'
 "str '~~~'"
BADFILE 'PARTIAL_ERROR_LOG\Insurance Master.bad'
DISCARDFILE 'PARTIAL_ERROR_LOG\Insurance Master.dsc'
DISCARDMAX 1241513983
APPEND INTO TABLE MIG_CMS_INSURANCE_COVERAGE
FIELDS TERMINATED BY '|||'
TRAILING NULLCOLS
(
INSCOMPID "REPLACE(REPLACE(DECODE(UPPER(:INSCOMPID),'NULL',NULL,:INSCOMPID), CHR(10),''), CHR(13),'')",
INSCOMPNAME "DECODE(UPPER(:INSCOMPNAME),'NULL',NULL,:INSCOMPNAME)",
ADDRESS "DECODE(UPPER(:ADDRESS),'NULL',NULL,:ADDRESS)",
CONTACTNUMBER "DECODE(UPPER(:CONTACTNUMBER),'NULL',NULL,:CONTACTNUMBER)"
)