drop table MIG_DC;

drop table MIG_DC_ERR;

drop table MIG_CHARGE_DC;

drop table MIG_CHARGE_DC_ERR;

drop table MIG_PLEDGOR_DC;

drop table MIG_PLEDGOR_DC_ERR;

drop table MIG_VAL_DC;

drop table MIG_VAL_DC_ERR;

CREATE TABLE MIG_DC (
	CIF_NUMBER VARCHAR(20),
	FAC_DESC VARCHAR(40),
	SOURCE_SECURITY_ID VARCHAR(19) NOT NULL,
	SECURITY_TYPE VARCHAR(40) DEFAULT 'Documentation',
	SECURITY_SUB_TYPE VARCHAR(80),
	SECURITY_TYPE_ID CHAR(2) DEFAULT 'DC',
	SECURITY_SUB_TYPE_ID VARCHAR(5),
	SECURITY_CURRENCY CHAR(3),
	SECURITY_LOCATION CHAR(2) DEFAULT 'MY',
	SECURITY_ORGANISATION VARCHAR(60),
	SECURITY_ORGANISATION_CODE VARCHAR(10),	
	SECURITY_CUSTODIAN_TYPE VARCHAR(10) DEFAULT 'I',
	CUSTODIAN_TYPE_CODE CHAR(1),
	SECURITY_CUSTODIAN_VALUE VARCHAR(100),
	CUSTODIAN_VALUE_CODE VARCHAR(10),
	SECURITY_MATURITY_DATE TIMESTAMP,
	SECURITY_PERFECTION_DATE TIMESTAMP,
	LEGAL_ENFORCEABILITY_IND CHAR(1),
	LEGAL_ENFORCEABILITY_DATE TIMESTAMP,
	SECURITY_REF_NOTE VARCHAR(2500),
	EXCHANGE_CONTROL_OBTAINED CHAR(1) DEFAULT 'N',	
	TYPE_OF_DEED_ASSIGNMENT VARCHAR(30),
	TYPE_DEED_ASSN_CODE VARCHAR(10),
	DOCUMENT_DATE TIMESTAMP,
	DOCUMENT_AMT_CCY CHAR(3),
	DOCUMENT_AMT DECIMAL(20,2),
	ISDA_AGREEMENT_DATE TIMESTAMP,
	IFEMA_AGREEMENT_DATE TIMESTAMP,
	ICOM_DOCUMENT_DATE TIMESTAMP,
	ISDA_DESC VARCHAR(20),
	REF_NUMBER VARCHAR(100),
	SPECIFIC_UNDERTAKING_REMARKS VARCHAR(2000),
	IFEMA_DESC VARCHAR(20),
	ICOM_DESC VARCHAR(20),
	MIN_AMT_CCY CHAR(3),
	MIN_AMT DECIMAL(30,2),
	MAX_AMT_CCY CHAR(3),
	MAX_AMT DECIMAL(30,2),
	CMS_COLLATERAL_ID BIGINT,
	CMS_COLLATERAL_STG_ID BIGINT,
	SOURCE_ID VARCHAR(10),
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	VALID_IND CHAR(1) DEFAULT 'Y'
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "MIG_DC" 
	ADD CONSTRAINT "MIG_DC_U" UNIQUE
		("SOURCE_SECURITY_ID", "REGION");

CREATE TABLE MIG_DC_ERR LIKE MIG_DC
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE MIG_DC_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE MIG_DC_ERR
  ADD REASON	CLOB;

-- CHARGE
CREATE TABLE MIG_CHARGE_DC (
	SOURCE_SECURITY_ID VARCHAR(19) NOT NULL,
	SOURCE_LIMIT_ID VARCHAR(20) NOT NULL,
	CHARGE_TYPE CHAR(10) DEFAULT 'G',
	NATURE_OF_CHARGE VARCHAR(60),
	CHARGE_CURRENCY CHAR(3),
	CHARGE_AMT DECIMAL(20,2),
	DATE_LEGALLY_CHARGE TIMESTAMP,
	SOURCE_ID VARCHAR(10),
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	VALID_IND CHAR(1) DEFAULT 'Y',
	VALID_CHARGE_IND CHAR(1) DEFAULT 'Y',
	CHARGE_TYPE_CODE VARCHAR(10),
	NATURE_OF_CHARGE_CODE VARCHAR(10),
	CMS_ACT_CHARGE_ID BIGINT, 
	CMS_ACT_LMT_ID BIGINT,
	CMS_STG_CHARGE_ID BIGINT,
	CMS_ACT_LMT_PROFILE_ID BIGINT,
	CMS_ACT_DTL_ID BIGINT, 
	CMS_STG_DTL_ID BIGINT,
	PRIOR_CHARGE_TYPE_CODE VARCHAR(10)	
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "MIG_CHARGE_DC" 
	ADD CONSTRAINT "MIG_CHARGE_DC_U" UNIQUE
		("SOURCE_LIMIT_ID",
		 "SOURCE_SECURITY_ID");

CREATE TABLE MIG_CHARGE_DC_ERR LIKE MIG_CHARGE_DC
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE MIG_CHARGE_DC_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE MIG_CHARGE_DC_ERR
  ADD REASON	CLOB;

-- PLEDGOR
CREATE TABLE MIG_PLEDGOR_DC (
	CIF_NUMBER VARCHAR(20) NOT NULL,
	SOURCE_LIMIT_ID VARCHAR(20) NOT NULL,
	SOURCE_SECURITY_ID VARCHAR(19) NOT NULL,
	IS_BORROWER_PLEDGOR CHAR(1), 
	CIF_PLEDGOR1 VARCHAR(19),
	CIF_PLEDGOR2 VARCHAR(19),
	CIF_PLEDGOR3 VARCHAR(19),
	CIF_PLEDGOR4 VARCHAR(19),
	CMS_PLEDGOR_ID BIGINT,
	CMS_PLEDGOR1_ID BIGINT,
	CMS_PLEDGOR2_ID BIGINT,
	CMS_PLEDGOR3_ID BIGINT,
	CMS_PLEDGOR4_ID BIGINT,
	SOURCE_ID VARCHAR(10),
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	IS_BRRW_PLGR_IND CHAR(1) DEFAULT 'Y',
	CIF_PLEDGOR1_IND CHAR(1) DEFAULT 'Y',
	CIF_PLEDGOR2_IND CHAR(1) DEFAULT 'Y',
	CIF_PLEDGOR3_IND CHAR(1) DEFAULT 'Y',
	CIF_PLEDGOR4_IND CHAR(1) DEFAULT 'Y'
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "MIG_PLEDGOR_DC" 
	ADD CONSTRAINT "MIG_PGR_DC_U" UNIQUE
		("CIF_NUMBER",
		 "SOURCE_LIMIT_ID",
		 "SOURCE_SECURITY_ID");

CREATE TABLE MIG_PLEDGOR_DC_ERR LIKE MIG_PLEDGOR_DC
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE MIG_PLEDGOR_DC_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE MIG_PLEDGOR_DC_ERR
  ADD REASON	CLOB;


CREATE TABLE MIG_VAL_DC (
	SOURCE_SECURITY_ID VARCHAR(19) NOT NULL,
	VALUATION_DATE TIMESTAMP NOT NULL,
	VALUATION_CCY CHAR(3),
	VALUATION_OMV DECIMAL(17,2) NOT NULL,
	VALUER VARCHAR(200),
	VALUER_CODE VARCHAR(10),
	VALUATION_FSV DECIMAL(17,2),
	COMMENTS VARCHAR(250),
	RESERVE_PRICE DECIMAL(17,2),
	RESERVE_PRICE_DATE TIMESTAMP,
	VALUATION_ID BIGINT,
	VALUATION_STG_ID BIGINT,
	SOURCE_ID VARCHAR(10),
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	VALID_IND CHAR(1) DEFAULT 'Y'
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "MIG_VAL_DC" 
	ADD CONSTRAINT "MIG_VAL_DC_U" UNIQUE
		("SOURCE_SECURITY_ID",
		 "VALUATION_DATE",
		 "VALUATION_OMV");

CREATE TABLE MIG_VAL_DC_ERR LIKE MIG_VAL_DC
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE MIG_VAL_DC_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE MIG_VAL_DC_ERR
  ADD REASON	CLOB;