drop table DC_AB102;

drop table DC_AB102_ERR;

CREATE TABLE DC_AB102 (
	CIF_NUMBER VARCHAR(20),
	BORROWER_NAME VARCHAR(100),
	ACCOUNT_NUMBER VARCHAR(40),
	BUSINESS_UNIT VARCHAR(15),
	BRANCH_CODE VARCHAR(3),
	CMS_COLLATERAL_ID BIGINT NOT NULL,	
	COLLATERAL_CODE VARCHAR(4),
	--COLLATERAL_CODE_DESC VARCHAR(200), -- ignore description
	COLLATERAL_NAME VARCHAR(30),
	CHASSIS_NUMBER VARCHAR(20),
	BRAND VARCHAR(100),
	REGISTRATION_NO VARCHAR(35),
	APPRAISED_VALUE BIGINT,
	APPRAISED_VALUE_DATE TIMESTAMP,
	VALUATION_AMOUNT DECIMAL(17,2),
	VALUER_NAME VARCHAR(200),
	CURRENT_MARKET_VALUE DECIMAL(17,2), --update
	VALUATION_DATE TIMESTAMP, -- update 
	VALUATION_TYPE_DESC VARCHAR(10), --update
	VALUATION_TYPE CHAR(1), -- update
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	VALID_IND CHAR(1) DEFAULT 'Y'
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "DC_AB102" 
	ADD CONSTRAINT "DC_AB102_U" UNIQUE
		("CMS_COLLATERAL_ID",
		 "REGION");

CREATE TABLE DC_AB102_ERR LIKE DC_AB102
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE DC_AB102_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE DC_AB102_ERR
  ADD REASON	CLOB;