-----------------------------
-- Cleanup
-----------------------------
DELETE FROM MIG_QC_REPORT;

-----------------------------
-- SCI_LE_MAIN_PROFILE
-----------------------------
-- CU001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'ARBS', 'CU001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CU001', 'ARBS', 'CU001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CU001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'ARBS', 'CU001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Customer,' || CHAR(COUNT(*)), 'ARBS', 'CU001' FROM SCI_LE_MAIN_PROFILE WHERE SOURCE_ID = 'ARBS');

-- CU004
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'SEMA', 'CU004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CU004', 'SEMA', 'CU004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SEMA', 'CU004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'SEMA', 'CU004');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Customer,' || CHAR(COUNT(*)), 'SEMA', 'CU004' FROM SCI_LE_MAIN_PROFILE WHERE SOURCE_ID = 'SEMA');

-- CU005
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'BOST', 'CU005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CU005', 'BOST', 'CU005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'CU005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'BOST', 'CU005');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Customer,' || CHAR(COUNT(*)), 'BOST', 'CU005' FROM SCI_LE_MAIN_PROFILE WHERE SOURCE_ID = 'BOST');

-- CU006
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'FINS', 'CU006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CU006', 'FINS', 'CU006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CU006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'FINS', 'CU006');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Customer,' || CHAR(COUNT(*)), 'FINS', 'CU006' FROM SCI_LE_MAIN_PROFILE WHERE SOURCE_ID = 'FINS' AND LMP_SGMNT_CODE_VALUE IS NOT NULL);

-- CU007
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'FINS', 'CU007');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CU007', 'FINS', 'CU007');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CU007');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'FINS', 'CU007');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Customer,' || CHAR(COUNT(*)), 'FINS', 'CU007' FROM SCI_LE_MAIN_PROFILE WHERE SOURCE_ID = 'FINS' AND LMP_SGMNT_CODE_VALUE IS NULL);
	
----------------------------
-- SCI_LE_CREDIT_GRADE
----------------------------

-- CU002
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'ARBS', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CU002', 'ARBS', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'ARBS', 'CU002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Credit Grade,' || CHAR(COUNT(*)), 'ARBS', 'CU002' 
     FROM SCI_LE_CREDIT_GRADE, SCI_LE_MAIN_PROFILE 
    WHERE CMS_MAIN_PROFILE_ID = CMS_LE_MAIN_PROFILE_ID
      AND SOURCE_ID = 'ARBS');
      
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'SEMA', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CU002', 'SEMA', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SEMA', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'SEMA', 'CU002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Credit Grade,' || CHAR(COUNT(*)), 'SEMA', 'CU002' 
     FROM SCI_LE_CREDIT_GRADE, SCI_LE_MAIN_PROFILE 
    WHERE CMS_MAIN_PROFILE_ID = CMS_LE_MAIN_PROFILE_ID
      AND SOURCE_ID = 'SEMA');
      
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'FINS', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CU002', 'FINS', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'FINS', 'CU002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Credit Grade,' || CHAR(COUNT(*)), 'FINS', 'CU002' 
     FROM SCI_LE_CREDIT_GRADE, SCI_LE_MAIN_PROFILE 
    WHERE CMS_MAIN_PROFILE_ID = CMS_LE_MAIN_PROFILE_ID
      AND SOURCE_ID = 'FINS');
      
-----------------------------
-- CMS_BATCH_CIF_FUSION
-----------------------------

-- CU003
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'ARBS', 'CU003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CU003', 'ARBS', 'CU003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CU003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'ARBS', 'CU003');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'CIF Fusion,' || CHAR(COUNT(*)), 'ARBS', 'CU003' FROM CMS_BATCH_CIF_FUSION WHERE SOURCE_ID = 'ARBS');


-----------------------------
-- CMS_SECURITY
-----------------------------
-- CO001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'ARBS', 'CO001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO001', 'ARBS', 'CO001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'ARBS', 'CO001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Security,' || CHAR(COUNT(*)), 'ARBS', 'CO001' FROM CMS_SECURITY WHERE SOURCE_ID = 'ARBS' AND SCI_SECURITY_SUBTYPE_VALUE IN ('AB101', 'AB102', 'AB103'));
	
-- CO002
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'ARBS', 'CO002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO002', 'ARBS', 'CO002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'ARBS', 'CO002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Security,' || CHAR(COUNT(*)), 'ARBS', 'CO002' FROM CMS_SECURITY WHERE SOURCE_ID = 'ARBS' AND SCI_SECURITY_SUBTYPE_VALUE = 'AB110');
	
-- CO003
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'ARBS', 'CO003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO003', 'ARBS', 'CO003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'ARBS', 'CO003');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Security,' || CHAR(COUNT(*)), 'ARBS', 'CO003' 
     FROM CMS_SECURITY 
    WHERE SOURCE_ID = 'ARBS' 
      AND SCI_SECURITY_SUBTYPE_VALUE NOT IN ('AB100', 'AB101', 'AB102', 'AB103', 'AB110')
      AND SCI_SECURITY_SUBTYPE_VALUE LIKE 'AB%');
	
-- CO004
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'ARBS', 'CO004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO004', 'ARBS', 'CO004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'ARBS', 'CO004');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Security,' || CHAR(COUNT(*)), 'ARBS', 'CO004' FROM CMS_SECURITY WHERE SOURCE_ID = 'ARBS' AND SCI_SECURITY_SUBTYPE_VALUE = 'AB100');

-- CO005
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'ARBS', 'CO005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO005', 'ARBS', 'CO005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'ARBS', 'CO005');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Security,' || CHAR(COUNT(*)), 'ARBS', 'CO005' FROM CMS_SECURITY WHERE SOURCE_ID = 'ARBS' AND SCI_SECURITY_SUBTYPE_VALUE IN ('CS200', 'CS202', 'CS203'));

-- CO006
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'ARBS', 'CO006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO006', 'ARBS', 'CO006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'ARBS', 'CO006');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Security,' || CHAR(COUNT(*)), 'ARBS', 'CO006' FROM CMS_CASH_DEPOSIT WHERE SOURCE_ID = 'ARBS');

-- CO007
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'ARBS', 'CO007');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO007', 'ARBS', 'CO007');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO007');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'ARBS', 'CO007');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Security,' || CHAR(COUNT(*)), 'ARBS', 'CO007' FROM CMS_SECURITY WHERE SOURCE_ID = 'ARBS' AND SCI_SECURITY_SUBTYPE_VALUE = 'MS602');

-- CO008
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'ARBS', 'CO008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO008', 'ARBS', 'CO008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'ARBS', 'CO008');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Security,' || CHAR(COUNT(*)), 'ARBS', 'CO008' FROM CMS_SECURITY WHERE SOURCE_ID = 'ARBS' AND SCI_SECURITY_TYPE_VALUE = 'MS' AND SCI_SECURITY_SUBTYPE_VALUE <> 'MS602');

-- CO009
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'ARBS', 'CO009');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO009', 'ARBS', 'CO009');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO009');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'ARBS', 'CO009');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Security,' || CHAR(COUNT(*)), 'ARBS', 'CO009' FROM CMS_SECURITY WHERE SOURCE_ID = 'ARBS' AND SCI_SECURITY_TYPE_VALUE = 'PT');

-- CO010
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'ARBS', 'CO010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO010', 'ARBS', 'CO010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'ARBS', 'CO010');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Security,' || CHAR(COUNT(*)), 'ARBS', 'CO010' FROM CMS_SECURITY WHERE SOURCE_ID = 'ARBS' AND SCI_SECURITY_TYPE_VALUE = 'GT');

-- CO011
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'ARBS', 'CO011');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO011', 'ARBS', 'CO011');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO011');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'ARBS', 'CO011');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Security,' || CHAR(COUNT(*)), 'ARBS', 'CO011' FROM CMS_SECURITY WHERE SOURCE_ID = 'ARBS' AND SCI_SECURITY_TYPE_VALUE = 'OT');

-- CO012
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'ARBS', 'CO012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO012', 'ARBS', 'CO012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'ARBS', 'CO012');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Security,' || CHAR(COUNT(*)), 'ARBS', 'CO012' FROM CMS_SECURITY WHERE SOURCE_ID = 'ARBS' AND SCI_SECURITY_TYPE_VALUE = 'IN');

-- CO013
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'ARBS', 'CO013');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO013', 'ARBS', 'CO013');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO013');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'ARBS', 'CO013');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Security,' || CHAR(COUNT(*)), 'ARBS', 'CO013' FROM CMS_SECURITY WHERE SOURCE_ID = 'ARBS' AND SCI_SECURITY_TYPE_VALUE = 'DC');

-- CO014
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'ARBS', 'CO014');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO014', 'ARBS', 'CO014');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO014');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'ARBS', 'CO014');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Security,' || CHAR(COUNT(*)), 'ARBS', 'CO014' FROM CMS_SECURITY WHERE SOURCE_ID = 'ARBS' AND SCI_SECURITY_TYPE_VALUE = 'CL');

-- CO020
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'SEMA', 'CO020');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO020', 'SEMA', 'CO020');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SEMA', 'CO020');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'SEMA', 'CO020');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Security,' || CHAR(COUNT(*)), 'SEMA', 'CO020' FROM CMS_SECURITY WHERE SOURCE_ID = 'SEMA' AND SCI_SECURITY_TYPE_VALUE = 'CS');

-- CO021
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'TSPR', 'CO021');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO021', 'TSPR', 'CO021');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'TSPR', 'CO021');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'TSPR', 'CO021');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Security,' || CHAR(COUNT(*)), 'TSPR', 'CO021' FROM CMS_SECURITY WHERE SOURCE_ID = 'TSPR' AND SCI_SECURITY_TYPE_VALUE = 'CS');

-- CO022
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'BOST', 'CO022');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO022', 'BOST', 'CO022');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'CO022');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'BOST', 'CO022');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Security,' || CHAR(COUNT(*)), 'BOST', 'CO022' FROM CMS_SECURITY WHERE SOURCE_ID = 'BOST' AND SCI_SECURITY_TYPE_VALUE = 'MS');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'STBG', 'CO022');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO022', 'STBG', 'CO022');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'STBG', 'CO022');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'STBG', 'CO022');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Security,' || CHAR(COUNT(*)), 'STBG', 'CO022' FROM CMS_SECURITY WHERE SOURCE_ID = 'STBG' AND SCI_SECURITY_TYPE_VALUE = 'MS');

-- CO025
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'BOST', 'CO025');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO025', 'BOST', 'CO025');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'CO025');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'BOST', 'CO025');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Security,' || CHAR(COUNT(*)), 'BOST', 'CO025' FROM CMS_SECURITY WHERE SOURCE_ID = 'BOST' AND SCI_SECURITY_TYPE_VALUE = 'CS');

-----------------------------
-- CMS_PORTFOLIO_ITEM_DTL
-----------------------------
-- CO023
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'BOST', 'CO023');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO023', 'BOST', 'CO023');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'CO023');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'BOST', 'CO023');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Portfolio Item Detail,' || CHAR(COUNT(*)), 'BOST', 'CO023' FROM CMS_PORTFOLIO_ITEM_DTL I, CMS_PORTFOLIO_ITEM P, CMS_MARKETABLE_SEC MS, CMS_SECURITY S
				WHERE I.ITEM_ID = P.ITEM_ID AND P.CMS_COLLATERAL_ID = MS.CMS_COLLATERAL_ID AND MS.CMS_COLLATERAL_ID = S.CMS_COLLATERAL_ID
					AND P.SOURCE_ID = 'BOST' AND S.SOURCE_ID = 'BOST' AND S.SCI_SECURITY_TYPE_VALUE = 'MS');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'STBG', 'CO023');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CO023', 'STBG', 'CO023');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'STBG', 'CO023');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'STBG', 'CO023');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Portfolio Item Detail,' || CHAR(COUNT(*)), 'STBG', 'CO023' FROM CMS_PORTFOLIO_ITEM_DTL I, CMS_PORTFOLIO_ITEM P, CMS_MARKETABLE_SEC MS, CMS_SECURITY S
				WHERE I.ITEM_ID = P.ITEM_ID AND P.CMS_COLLATERAL_ID = MS.CMS_COLLATERAL_ID AND MS.CMS_COLLATERAL_ID = S.CMS_COLLATERAL_ID
					AND P.SOURCE_ID = 'STBG' AND S.SOURCE_ID = 'STBG' AND S.SCI_SECURITY_TYPE_VALUE = 'MS');

-----------------------------
-- SCI_LSP_LMT_PROFILE
-----------------------------
-- CA001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'ARBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CA001', 'ARBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'ARBS', 'CA001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'AA,' || CHAR(COUNT(*)), 'ARBS', 'CA001' FROM SCI_LSP_LMT_PROFILE WHERE SOURCE_ID = 'ARBS');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'SEMA', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CA001', 'SEMA', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SEMA', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'SEMA', 'CA001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'AA,' || CHAR(COUNT(*)), 'SEMA', 'CA001' FROM SCI_LSP_LMT_PROFILE WHERE SOURCE_ID = 'SEMA');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'BOST', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CA001', 'BOST', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'BOST', 'CA001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'AA,' || CHAR(COUNT(*)), 'BOST', 'CA001' FROM SCI_LSP_LMT_PROFILE WHERE SOURCE_ID = 'BOST');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'FINS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CA001', 'FINS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'FINS', 'CA001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'AA,' || CHAR(COUNT(*)), 'FINS', 'CA001' FROM SCI_LSP_LMT_PROFILE WHERE SOURCE_ID = 'FINS');


-----------------------------
-- SCI_LSP_JOINT_BORROWER
-----------------------------
--CA002
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'ARBS', 'CA002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CA002', 'ARBS', 'CA002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CA002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'ARBS', 'CA002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Joint Borrower,' || CHAR(COUNT(*)), 'ARBS', 'CA002' FROM SCI_LSP_JOINT_BORROWER WHERE SOURCE_ID = 'ARBS');


-----------------------------
-- SCI_LSP_APPR_LMTS
-----------------------------
-- CA003
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'ARBS', 'CA003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CA003', 'ARBS', 'CA003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CA003');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'ARBS', 'CA003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Limit,' || CHAR(COUNT(*)) || chr(13) || chr(10), 'ARBS', 'CA003' FROM SCI_LSP_APPR_LMTS WHERE SOURCE_ID = 'ARBS');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Grand Total of Limit Amount', 'ARBS', 'CA003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', COALESCE(CHAR(SUM(LMT_AMT)),'0'), 'ARBS', 'CA003' FROM SCI_LSP_APPR_LMTS WHERE SOURCE_ID = 'ARBS');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Grand Total of Drawing Amount', 'ARBS', 'CA003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', COALESCE(CHAR(SUM(CMS_ACTIVATED_LIMIT)),'0'), 'ARBS', 'CA003' FROM SCI_LSP_APPR_LMTS WHERE SOURCE_ID = 'ARBS');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Grand Total of Outstanding Amount', 'ARBS', 'CA003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', COALESCE(CHAR(SUM(CMS_OUTSTANDING_AMT)),'0'), 'ARBS', 'CA003' FROM SCI_LSP_APPR_LMTS WHERE SOURCE_ID = 'ARBS');

-- CA006
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'TSPR', 'CA006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CA006', 'TSPR', 'CA006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'TSPR', 'CA006');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'TSPR', 'CA006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Limit,' || CHAR(COUNT(*))  || chr(13) || chr(10), 'TSPR', 'CA006' FROM SCI_LSP_APPR_LMTS WHERE SOURCE_ID = 'TSPR');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Grand Total of Limit Amount', 'TSPR', 'CA006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', COALESCE(CHAR(SUM(LMT_AMT)),'0'), 'TSPR', 'CA006' FROM SCI_LSP_APPR_LMTS WHERE SOURCE_ID = 'TSPR');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Grand Total of Drawing Amount', 'TSPR', 'CA006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', COALESCE(CHAR(SUM(CMS_ACTIVATED_LIMIT)),'0'), 'TSPR', 'CA006' FROM SCI_LSP_APPR_LMTS WHERE SOURCE_ID = 'TSPR');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Grand Total of Outstanding Amount', 'TSPR', 'CA006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', COALESCE(CHAR(SUM(CMS_OUTSTANDING_AMT)),'0'), 'TSPR', 'CA006' FROM SCI_LSP_APPR_LMTS WHERE SOURCE_ID = 'TSPR');

-- CA012
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'SEMA', 'CA012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CA012', 'SEMA', 'CA012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date) || chr(13) || chr(10) || chr(13) || chr(10), 'SEMA', 'CA012');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'SEMA', 'CA012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Limit,' || CHAR(COUNT(*)) || chr(13) || chr(10), 'SEMA', 'CA012' FROM SCI_LSP_APPR_LMTS WHERE SOURCE_ID = 'SEMA');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Grand Total of Limit Amount', 'SEMA', 'CA012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', COALESCE(CHAR(SUM(LMT_AMT)),'0'), 'SEMA', 'CA012' FROM SCI_LSP_APPR_LMTS WHERE SOURCE_ID = 'SEMA');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Grand Total of Drawing Limit Amount', 'SEMA', 'CA012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', COALESCE(CHAR(SUM(CMS_DRAWING_LIMIT)),'0'), 'SEMA', 'CA012' FROM SCI_LSP_APPR_LMTS WHERE SOURCE_ID = 'SEMA');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Grand Total of Outstanding Amount', 'SEMA', 'CA012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', COALESCE(CHAR(SUM(CMS_OUTSTANDING_AMT)),'0'), 'SEMA', 'CA012' FROM SCI_LSP_APPR_LMTS WHERE SOURCE_ID = 'SEMA');

-- CA015
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'BOST', 'CA015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CA015', 'BOST', 'CA015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'CA015');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'BOST', 'CA015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Limit,' || CHAR(COUNT(*)) || chr(13) || chr(10), 'BOST', 'CA015' FROM SCI_LSP_APPR_LMTS WHERE SOURCE_ID = 'BOST');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Grand Total of Limit Amount', 'BOST', 'CA015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', COALESCE(CHAR(SUM(LMT_AMT)),'0'), 'BOST', 'CA015' FROM SCI_LSP_APPR_LMTS WHERE SOURCE_ID = 'BOST');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Grand Total of Available Limit', 'BOST', 'CA015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', COALESCE(CHAR(SUM(AVAILABLE_LMT)),'0'), 'BOST', 'CA015' FROM SCI_LSP_APPR_LMTS WHERE SOURCE_ID = 'BOST');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Grand Total of Outstanding Amount', 'BOST', 'CA015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', COALESCE(CHAR(SUM(CMS_OUTSTANDING_AMT)),'0'), 'BOST', 'CA015' FROM SCI_LSP_APPR_LMTS WHERE SOURCE_ID = 'BOST');

-- CA016
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'QUAN', 'CA016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CA016', 'QUAN', 'CA016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'QUAN', 'CA016');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'QUAN', 'CA016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Limit,' || CHAR(COUNT(*)) || chr(13) || chr(10), 'QUAN', 'CA016' FROM SCI_LSP_APPR_LMTS WHERE SOURCE_ID = 'QUAN');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Grand Total of Limit Amount', 'QUAN', 'CA016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', COALESCE(CHAR(SUM(LMT_AMT)),'0'), 'QUAN', 'CA016' FROM SCI_LSP_APPR_LMTS WHERE SOURCE_ID = 'QUAN');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Grand Total of Outstanding Amount', 'QUAN', 'CA016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', COALESCE(CHAR(SUM(CMS_OUTSTANDING_AMT)),'0'), 'QUAN', 'CA016' FROM SCI_LSP_APPR_LMTS WHERE SOURCE_ID = 'QUAN');

-- CA017
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'FINS', 'CA017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CA017', 'FINS', 'CA017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CA017');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'FINS', 'CA017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Limit,' || CHAR(COUNT(*)) || chr(13) || chr(10), 'FINS', 'CA017' FROM SCI_LSP_APPR_LMTS A, SCI_LE_MAIN_PROFILE B 
		WHERE A.SOURCE_ID = 'FINS' AND B.SOURCE_ID = 'FINS'
		AND A.LMT_LE_ID = B.LMP_LE_ID AND B.LMP_SGMNT_CODE_VALUE IS NOT NULL);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Grand Total of Limit Amount', 'FINS', 'CA017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', COALESCE(CHAR(SUM(LMT_AMT)),'0'), 'FINS', 'CA017' FROM SCI_LSP_APPR_LMTS A, SCI_LE_MAIN_PROFILE B 
		WHERE A.SOURCE_ID = 'FINS' AND B.SOURCE_ID = 'FINS'
		AND A.LMT_LE_ID = B.LMP_LE_ID AND B.LMP_SGMNT_CODE_VALUE IS NOT NULL);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Grand Total of Outstanding Amount', 'FINS', 'CA017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', COALESCE(CHAR(SUM(CMS_OUTSTANDING_AMT)),'0'), 'FINS', 'CA017' FROM SCI_LSP_APPR_LMTS A, SCI_LE_MAIN_PROFILE B 
		WHERE A.SOURCE_ID = 'FINS' AND B.SOURCE_ID = 'FINS'
		AND A.LMT_LE_ID = B.LMP_LE_ID AND B.LMP_SGMNT_CODE_VALUE IS NOT NULL);

-- CA018
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'FINS', 'CA018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: CA018', 'FINS', 'CA018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CA018');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'FINS', 'CA018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Limit,' || CHAR(COUNT(*)) || chr(13) || chr(10), 'FINS', 'CA018' FROM SCI_LSP_APPR_LMTS A, SCI_LE_MAIN_PROFILE B 
		WHERE A.SOURCE_ID = 'FINS' AND B.SOURCE_ID = 'FINS'
		AND A.LMT_LE_ID = B.LMP_LE_ID AND B.LMP_SGMNT_CODE_VALUE IS NULL);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Grand Total of Limit Amount', 'FINS', 'CA018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', COALESCE(CHAR(SUM(LMT_AMT)),'0'), 'FINS', 'CA018' FROM SCI_LSP_APPR_LMTS A, SCI_LE_MAIN_PROFILE B 
		WHERE A.SOURCE_ID = 'FINS' AND B.SOURCE_ID = 'FINS'
		AND A.LMT_LE_ID = B.LMP_LE_ID AND B.LMP_SGMNT_CODE_VALUE IS NULL);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Grand Total of Outstanding Amount', 'FINS', 'CA018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', COALESCE(CHAR(SUM(CMS_OUTSTANDING_AMT)),'0'), 'FINS', 'CA018' FROM SCI_LSP_APPR_LMTS A, SCI_LE_MAIN_PROFILE B 
		WHERE A.SOURCE_ID = 'FINS' AND B.SOURCE_ID = 'FINS'
		AND A.LMT_LE_ID = B.LMP_LE_ID AND B.LMP_SGMNT_CODE_VALUE IS NULL);

-----------------------------
-- CMS_EARMARK_GROUP
-----------------------------
-- SH001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'BOST', 'SH001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: SH001', 'BOST', 'SH001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'SH001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'BOST', 'SH001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Counter Share Holding,' || CHAR(COUNT(*)), 'BOST', 'SH001' FROM CMS_EARMARK_GROUP	WHERE SOURCE_SYSTEM_ID = 'BOST');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'STBG', 'SH001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: SH001', 'STBG', 'SH001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'STBG', 'SH001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'STBG', 'SH001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Counter Share Holding,' || CHAR(COUNT(*)), 'STBG', 'SH001' FROM CMS_EARMARK_GROUP	WHERE SOURCE_SYSTEM_ID = 'STBG');

-----------------------------
-- CMS_PRICE_FEED
-----------------------------
-- PF001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'STBG', 'PF001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: PF001', 'STBG', 'PF001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'STBG', 'PF001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'STBG', 'PF001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Price Feed,' || CHAR(COUNT(*)), 'STBG', 'PF001' FROM CMS_PRICE_FEED	WHERE TYPE IS NOT NULL);

-- PF002
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'QC Report 5 for Migration', 'STBG', 'PF002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report for migration template: PF002', 'STBG', 'PF002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'STBG', 'PF002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Migrated', 'Record Type,Total Number of Records', 'STBG', 'PF002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Migrated', 'Price Feed,' || CHAR(COUNT(*)), 'STBG', 'PF002' FROM CMS_PRICE_FEED	WHERE TYPE IS NULL);

COMMIT;
