-----------------------------
-- Cleanup
-----------------------------
DELETE FROM MIG_QC_REPORT;

-----------------------------
-- Customer
-----------------------------
-- CU001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CU001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CU001', 'ARBS', 'CU001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CU001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CU001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CU001' FROM SI_TEMP_ARBS_CU001);

-- CU002
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CU002', 'ARBS', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CU002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CU002' FROM SI_TEMP_ARBS_CU002);
	
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'SEMA', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CU002', 'SEMA', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SEMA', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'SEMA', 'CU002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'SEMA', 'CU002' FROM SI_TEMP_SEMA_CU002);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'FINS', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CU002', 'FINS', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'FINS', 'CU002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'FINS', 'CU002' FROM SI_TEMP_FINS_CU002);

-- CU003
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CU003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CU003', 'ARBS', 'CU003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CU003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CU003');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CU003' FROM SI_TEMP_ARBS_CU003);

-- CU004
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'SEMA', 'CU004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CU004', 'SEMA', 'CU004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SEMA', 'CU004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'SEMA', 'CU004');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'SEMA', 'CU004' FROM SI_TEMP_SEMA_CU004);

-- CU005
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'BOST', 'CU005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CU005', 'BOST', 'CU005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'CU005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'BOST', 'CU005');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'BOST', 'CU005' FROM SI_TEMP_BOST_CU005);

-- CU006
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'FINS', 'CU006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CU006', 'FINS', 'CU006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CU006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'FINS', 'CU006');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'FINS', 'CU006' FROM SI_TEMP_FINS_CU006);

-- CU007
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'FINS', 'CU007');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CU007', 'FINS', 'CU007');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CU007');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'FINS', 'CU007');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'FINS', 'CU007' FROM SI_TEMP_FINS_CU007);
	
	
-----------------------------
-- Credit Application (CA)
-----------------------------
-- CA001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CA001', 'ARBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CA001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CA001' FROM SI_TEMP_ARBS_CA001);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'SEMA', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CA001', 'SEMA', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SEMA', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'SEMA', 'CA001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'SEMA', 'CA001' FROM SI_TEMP_SEMA_CA001);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'BOST', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CA001', 'BOST', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'BOST', 'CA001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'BOST', 'CA001' FROM SI_TEMP_BOST_CA001);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'FINS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CA001', 'FINS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'FINS', 'CA001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'FINS', 'CA001' FROM SI_TEMP_FINS_CA001);
	
-- CA002
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CA002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CA002', 'ARBS', 'CA002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CA002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CA002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CA002' FROM SI_TEMP_ARBS_CA002);

-- CA003
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CA003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CA003', 'ARBS', 'CA003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CA003');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CA003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CA003' FROM SI_TEMP_ARBS_CA003);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Grand Total of Limit Amount', 'ARBS', 'CA003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', COALESCE(CHAR(SUM(LIMIT_AMT)),'0'), 'ARBS', 'CA003' FROM SI_TEMP_ARBS_CA003);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Grand Total of Drawing Amount', 'ARBS', 'CA003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', COALESCE(CHAR(SUM(DRAWING_LIMIT_AMT)),'0'), 'ARBS', 'CA003' FROM SI_TEMP_ARBS_CA003);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Grand Total of Outstanding Amount', 'ARBS', 'CA003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', COALESCE(CHAR(SUM(OUTSTANDING_AMT)),'0'), 'ARBS', 'CA003' FROM SI_TEMP_ARBS_CA003);

-- CA004
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CA004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CA004', 'ARBS', 'CA004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CA004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CA004');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CA004' FROM SI_TEMP_ARBS_CA004);

-- CA005
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CA005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CA005', 'ARBS', 'CA005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CA005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CA005');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CA005' FROM SI_TEMP_ARBS_CA005);

-- CA006
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'TSPR', 'CA006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CA006', 'TSPR', 'CA006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'TSPR', 'CA006');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'TSPR', 'CA006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'TSPR', 'CA006' FROM SI_TEMP_TSPR_CA006);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Grand Total of Limit Amount', 'TSPR', 'CA006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', COALESCE(CHAR(SUM(LIMIT_AMT)),'0'), 'TSPR', 'CA006' FROM SI_TEMP_TSPR_CA006);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Grand Total of Drawing Amount', 'TSPR', 'CA006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', COALESCE(CHAR(SUM(DRAWING_ACTIVATED_LIMIT_AMT)),'0'), 'TSPR', 'CA006' FROM SI_TEMP_TSPR_CA006);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Grand Total of Outstanding Amount', 'TSPR', 'CA006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', COALESCE(CHAR(SUM(OUTSTANDING_AMT)),'0'), 'TSPR', 'CA006' FROM SI_TEMP_TSPR_CA006);

-- CA007 N/A

-- CA008
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'TSPR', 'CA008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CA008', 'TSPR', 'CA008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'TSPR', 'CA008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'TSPR', 'CA008');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'TSPR', 'CA008' FROM SI_TEMP_TSPR_CA008);

-- CA009 N/A

-- CA010
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'TSPR', 'CA010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CA008', 'TSPR', 'CA010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'TSPR', 'CA010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'TSPR', 'CA010');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'TSPR', 'CA010' FROM SI_TEMP_TSPR_CA010);

-- CA011 N/A

-- CA012
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'SEMA', 'CA012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CA012', 'SEMA', 'CA012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SEMA', 'CA012');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'SEMA', 'CA012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'SEMA', 'CA012' FROM SI_TEMP_SEMA_CA012);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Grand Total of Limit Amount', 'SEMA', 'CA012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', COALESCE(CHAR(SUM(LIMIT_AMT)),'0'), 'SEMA', 'CA012' FROM SI_TEMP_SEMA_CA012);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Grand Total of Drawing Limit Amount', 'SEMA', 'CA012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', COALESCE(CHAR(SUM(DRAWING_LIMIT_AMT)),'0'), 'SEMA', 'CA012' FROM SI_TEMP_SEMA_CA012);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Grand Total of Outstanding Amount', 'SEMA', 'CA012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', COALESCE(CHAR(SUM(OUTSTANDING_AMT)),'0'), 'SEMA', 'CA012' FROM SI_TEMP_SEMA_CA012);

-- CA015
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'BOST', 'CA015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CA015', 'BOST', 'CA015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'CA015');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'BOST', 'CA015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'BOST', 'CA015' FROM SI_TEMP_BOST_CA015);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Grand Total of Limit Amount', 'BOST', 'CA015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', COALESCE(CHAR(SUM(LIMIT_AMT)),'0'), 'BOST', 'CA015' FROM SI_TEMP_BOST_CA015);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Grand Total of Available Limit', 'BOST', 'CA015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', COALESCE(CHAR(SUM(AVAILABLE_LIMIT)),'0'), 'BOST', 'CA015' FROM SI_TEMP_BOST_CA015);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Grand Total of Outstanding Amount', 'BOST', 'CA015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', COALESCE(CHAR(SUM(CAST(OUTSTANDING_AMT_SIGN || CHAR(OUTSTANDING_AMT) AS DECIMAL(17,2)))),'0'), 'BOST', 'CA015' FROM SI_TEMP_BOST_CA015);

-- CA016
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'QUAN', 'CA016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CA016', 'QUAN', 'CA016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'QUAN', 'CA016');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'QUAN', 'CA016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'QUAN', 'CA016' FROM SI_TEMP_QUAN_CA016);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Grand Total of Limit Amount', 'QUAN', 'CA016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', COALESCE(CHAR(SUM(LIMIT_AMOUNT)),'0'), 'QUAN', 'CA016' FROM SI_TEMP_QUAN_CA016);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Grand Total of Outstanding Amount', 'QUAN', 'CA016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', COALESCE(CHAR(SUM(OUTSTANDING_AMOUNT)),'0'), 'QUAN', 'CA016' FROM SI_TEMP_QUAN_CA016);

-- CA017
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'FINS', 'CA017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CA017', 'FINS', 'CA017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CA017');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'FINS', 'CA017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'FINS', 'CA017' FROM SI_TEMP_FINS_CA017);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Grand Total of Limit Amount', 'FINS', 'CA017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', COALESCE(CHAR(SUM(LIMIT_AMT)),'0'), 'FINS', 'CA017' FROM SI_TEMP_FINS_CA017);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Grand Total of Outstanding Amount', 'FINS', 'CA017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', COALESCE(CHAR(SUM(OUTSTANDING_AMT)),'0'), 'FINS', 'CA017' FROM SI_TEMP_FINS_CA017);

-- CA018
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'FINS', 'CA018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CA018', 'FINS', 'CA018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CA018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'FINS', 'CA018');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'FINS', 'CA018' FROM SI_TEMP_FINS_CA018);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Grand Total of Limit Amount', 'FINS', 'CA018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', COALESCE(CHAR(SUM(LIMIT_AMT)),'0'), 'FINS', 'CA018' FROM SI_TEMP_FINS_CA018);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Grand Total of Outstanding Amount', 'FINS', 'CA018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', COALESCE(CHAR(SUM(OUTSTANDING_AMT)),'0'), 'FINS', 'CA018' FROM SI_TEMP_FINS_CA018);

-- CA019
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CA019');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CA019', 'ARBS', 'CA019');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CA019');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CA019');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CA019' FROM SI_TEMP_ARBS_CA019);


-----------------------------
-- Collateral
-----------------------------
-- CO001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CO001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO001', 'ARBS', 'CO001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CO001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CO001' FROM SI_TEMP_ARBS_CO001);

-- CO002
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CO002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO002', 'ARBS', 'CO002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CO002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CO002' FROM SI_TEMP_ARBS_CO002);

-- CO003
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CO003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO003', 'ARBS', 'CO003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CO003');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CO003' FROM SI_TEMP_ARBS_CO003);

-- CO004
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CO004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO004', 'ARBS', 'CO004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CO004');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CO004' FROM SI_TEMP_ARBS_CO004);

-- CO005
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CO005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO005', 'ARBS', 'CO005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CO005');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CO005' FROM SI_TEMP_ARBS_CO005);

-- CO006
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CO006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO006', 'ARBS', 'CO006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CO006');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CO006' FROM SI_TEMP_ARBS_CO006);

-- CO007
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CO007');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO007', 'ARBS', 'CO007');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO007');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CO007');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CO007' FROM SI_TEMP_ARBS_CO007);

-- CO008
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CO008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO008', 'ARBS', 'CO008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CO008');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CO008' FROM SI_TEMP_ARBS_CO008);

-- CO009
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CO009');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO009', 'ARBS', 'CO009');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO009');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CO009');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CO009' FROM SI_TEMP_ARBS_CO009);

-- CO010
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CO010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO010', 'ARBS', 'CO010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CO010');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CO010' FROM SI_TEMP_ARBS_CO010);

-- CO011
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CO011');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO011', 'ARBS', 'CO011');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO011');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CO011');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CO011' FROM SI_TEMP_ARBS_CO011);

-- CO012
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CO012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO012', 'ARBS', 'CO012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CO012');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CO012' FROM SI_TEMP_ARBS_CO012);

-- CO013
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CO013');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO013', 'ARBS', 'CO013');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO013');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CO013');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CO013' FROM SI_TEMP_ARBS_CO013);

-- CO014
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CO014');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO014', 'ARBS', 'CO014');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO014');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CO014');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CO014' FROM SI_TEMP_ARBS_CO014);

-- CO015
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CO015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO015', 'ARBS', 'CO015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CO015');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CO015' FROM SI_TEMP_ARBS_CO015);

-- CO016
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CO016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO016', 'ARBS', 'CO016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CO016');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CO016' FROM SI_TEMP_ARBS_CO016);

-- CO017
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CO017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO017', 'ARBS', 'CO017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CO017');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CO017' FROM SI_TEMP_ARBS_CO017);

-- CO018
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'CO018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO018', 'ARBS', 'CO018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'CO018');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'CO018' FROM SI_TEMP_ARBS_CO018);

-- CO020
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'SEMA', 'CO020');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO020', 'SEMA', 'CO020');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SEMA', 'CO020');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'SEMA', 'CO020');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'SEMA', 'CO020' FROM SI_TEMP_SEMA_CO020);

-- CO021
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'TSPR', 'CO021');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO021', 'TSPR', 'CO021');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'TSPR', 'CO021');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'TSPR', 'CO021');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'TSPR', 'CO021' FROM SI_TEMP_TSPR_CO021);

-- CO022
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'BOST', 'CO022');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO022', 'BOST', 'CO022');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'CO022');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'BOST', 'CO022');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'BOST', 'CO022' FROM SI_TEMP_BOST_CO022);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'STBG', 'CO022');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO022', 'STBG', 'CO022');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'STBG', 'CO022');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'STBG', 'CO022');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'STBG', 'CO022' FROM SI_TEMP_STBG_CO022);

-- CO023
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'BOST', 'CO023');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO023', 'BOST', 'CO023');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'CO023');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'BOST', 'CO023');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'BOST', 'CO023' FROM SI_TEMP_BOST_CO023);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'STBG', 'CO023');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO023', 'STBG', 'CO023');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'STBG', 'CO023');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'STBG', 'CO023');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'STBG', 'CO023' FROM SI_TEMP_STBG_CO023);

-- CO024
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'STBG', 'CO024');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO024', 'STBG', 'CO024');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'STBG', 'CO024');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'STBG', 'CO024');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'STBG', 'CO024' FROM SI_TEMP_STBG_CO024);

-- CO025
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'BOST', 'CO025');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: CO025', 'BOST', 'CO025');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'CO025');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'BOST', 'CO025');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'BOST', 'CO025' FROM SI_TEMP_BOST_CO025);


-----------------------------
-- Price Feed
-----------------------------
-- PF001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'STBG', 'PF001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: PF001', 'STBG', 'PF001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'STBG', 'PF001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'STBG', 'PF001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'STBG', 'PF001' FROM SI_TEMP_STBG_PF001);

-- PF002
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'STBG', 'PF002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: PF002', 'STBG', 'PF002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'STBG', 'PF002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'STBG', 'PF002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'STBG', 'PF002' FROM SI_TEMP_STBG_PF002);

-- PF003
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'ARBS', 'PF003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: PF003', 'ARBS', 'PF003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'PF003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'ARBS', 'PF003');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'ARBS', 'PF003' FROM SI_TEMP_ARBS_PF003);


-----------------------------
-- Counter Share Holding
-----------------------------
-- SH001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'BOST', 'SH001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: SH001', 'BOST', 'SH001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'SH001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'BOST', 'SH001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'BOST', 'SH001' FROM SI_TEMP_BOST_SH001);

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'QC Report 2a for Migration', 'STBG', 'SH001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report for migration template: SH001', 'STBG', 'SH001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'STBG', 'SH001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('LoadCount', 'Total Number of Records', 'STBG', 'SH001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'LoadCount', CHAR(COUNT(*)), 'STBG', 'SH001' FROM SI_TEMP_STBG_SH001);

COMMIT;
