db2 connect to EONCMS user db2admin using db2admin

db2 set current schema = EONCMS_LOCAL
db2 SET CURRENT PATH = SYSIBM,SYSFUN,SYSPROC,SYSIBMADM,EONCMS_LOCAL

db2 DROP TABLE TMP_DOCUMENT_GLOBALLIST
db2 DROP TABLE ERR_DOCUMENT_GLOBALLIST
db2 DROP PROCEDURE LOAD_DOC_GLOBAL_ITEM