LTER TABLE STAGE_CHECKLIST_ITEM ADD 
(FAC_IMAGE_ID  NUMBER(19), FAC_IMAGE_NAME VARCHAR2(3900 CHAR), FAC_IMAGE_STATUS VARCHAR2(100),
SEC_IMAGE_ID NUMBER(19),SEC_IMAGE_NAME VARCHAR2(3900 CHAR),SEC_IMAGE_STATUS VARCHAR2(100));

ALTER TABLE CMS_CHECKLIST_ITEM ADD 
(FAC_IMAGE_ID  NUMBER(19), FAC_IMAGE_NAME VARCHAR2(3900 CHAR), FAC_IMAGE_STATUS VARCHAR2(100),
SEC_IMAGE_ID NUMBER(19),SEC_IMAGE_NAME VARCHAR2(3900 CHAR),SEC_IMAGE_STATUS VARCHAR2(100));


ALTER TABLE CMS_TEMP_IMAGE_UPLOAD
ADD 
(
SECURITY_SUB_TYPE VARCHAR2(100),
STATEMENT_TYPE VARCHAR2(100),
STATEMENT_DOC_NAME VARCHAR2(1000 CHAR),
CAM_DOC_NAME VARCHAR2(500 CHAR),
OTHER_DOC_NAME VARCHAR2(500 CHAR)
);
ALTER TABLE CMS_UPLOADED_IMAGES
ADD 
(
SECURITY_SUB_TYPE VARCHAR2(100),
STATEMENT_TYPE VARCHAR2(100),
STATEMENT_DOC_NAME VARCHAR2(1000 CHAR),
CAM_DOC_NAME VARCHAR2(500 CHAR),
OTHER_DOC_NAME VARCHAR2(500 CHAR)
);


create table cms_checklist_item_image(
	CHK_ITEM_IMAGE_ID number(19) not null,
	DOC_ITEM_ID number(19),
	IMAGE_ID number(19),
	FILE_NAME varchar2(100),
	IMG_PATH VARCHAR2(1000 CHAR),
	STATUS NUMBER,
	SELECTED_IND char(1),
  DOC_DESC VARCHAR2(500),
  SUB_FOLDER_NAME  VARCHAR2(40)
	
);

CREATE INDEX CMS_CHK_ITEM_IMAGE_ID_IDX ON  cms_checklist_item_image(DOC_ITEM_ID);
CREATE UNIQUE INDEX CMS_CHK_IMG_CHK_IMG_IDX ON cms_checklist_item_image(CHK_ITEM_IMAGE_ID);

create table cms_stage_checklist_item_image(
	CHK_ITEM_IMAGE_ID number(19) not null,
	DOC_ITEM_ID number(19),
	IMAGE_ID number(19),
	FILE_NAME varchar2(100),
	SELECTED_IND char(1),
  DOC_DESC VARCHAR2(500),
  SUB_FOLDER_NAME  VARCHAR2(40)
);

CREATE INDEX CMS_STG_CHK_ITEM_IMAGE_ID_IDX ON cms_stage_checklist_item_image(DOC_ITEM_ID);
CREATE UNIQUE INDEX CMS_STG_CHK_IMG_CHK_IMG_IDX ON cms_stage_checklist_item_image(CHK_ITEM_IMAGE_ID);

CREATE SEQUENCE CHK_ITEM_IMAGE_SEQ  MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

ALTER TABLE stage_checklist_item ADD ROC_CHARGE CHAR(1);
ALTER TABLE cms_checklist_item ADD ROC_CHARGE CHAR(1);