--------------------------------
--- CMS_FUNCTION_ACCESS Entries 
--------------------------------

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000256,'InsuranceCoverageDtls','checker_approve_edit',7);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000257,'InsuranceCoverageDtls','checker_edit_read',7);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000258,'InsuranceCoverageDtls','checker_process_create',7);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000259,'InsuranceCoverageDtls','checker_process_delete',7);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000260,'InsuranceCoverageDtls','checker_process_edit',7);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000261,'InsuranceCoverageDtls','checker_reject_edit',7);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000275,'InsuranceCoverageDtls','list_insurance_coverage',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000262,'InsuranceCoverageDtls','maker_confirm_close',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000263,'InsuranceCoverageDtls','maker_confirm_resubmit_edit',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000264,'InsuranceCoverageDtls','maker_edit_insurance_coverage_dtls',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000265,'InsuranceCoverageDtls','maker_prepare_close',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000266,'InsuranceCoverageDtls','maker_prepare_close',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000267,'InsuranceCoverageDtls','maker_prepare_resubmit',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000268,'InsuranceCoverageDtls','maker_prepare_resubmit_create',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000251,'InsuranceCoverageDtls','maker_submit_create_insurance_coverage_dtls',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000269,'InsuranceCoverageDtls','maker_submit_edit',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000270,'InsuranceCoverageDtls','maker_submit_remove',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000252,'InsuranceCoverageDtls','prepare_create_insurance_coverage_dtls',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000253,'InsuranceCoverageDtls','prepare_maker_submit_edit',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000254,'InsuranceCoverageDtls','prepare_maker_submit_remove',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000271,'InsuranceCoverageDtls','rejected_delete_read',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000272,'InsuranceCoverageDtls','rejected_delete_read',7);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000273,'InsuranceCoverageDtls','rejected_read',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000274,'InsuranceCoverageDtls','search_insurance_coverage_dtls',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000255,'InsuranceCoverageDtls','view_insurance_coverage_dtls_by_index',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000276,'InsuranceCoverageDtls','maker_save_create_insurance_coverage_dtls',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000277,'InsuranceCoverageDtls','maker_update_save_process',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000278,'InsuranceCoverageDtls', 'maker_draft_close_process',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000279,'InsuranceCoverageDtls', 'maker_confirm_draft_close',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000280,'InsuranceCoverageDtls', 'maker_confirm_resubmit_draft',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000281,'InsuranceCoverageDtls', 'maker_save_update_insurance_coverage_dtls',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000282,'InsuranceCoverageDtls', 'maker_save_process',6);
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000283,'InsuranceCoverageDtls', 'maker_confirm_resubmit_update',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000284,'InsuranceCoverageDtls', 'maker_update_save_process',6);	

-----------------------------------
--- CMS_STATEMATRIX_ACTION Entries 
-----------------------------------


insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
	values (9251,6,'Process','InsuranceCoverageDtls.do?event=maker_prepare_resubmit&TrxId=','InsuranceCoverageDtls.do?event=to_track&TrxId=');

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
	values (9252,7,'Process','InsuranceCoverageDtls.do?event=checker_process_create&TrxId=',null);

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
	values (9256,7,'Process','InsuranceCoverageDtls.do?event=checker_edit_read&TrxId=',null);

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
	values (9257,6,'Process','InsuranceCoverageDtls.do?event=maker_prepare_resubmit_create&TrxId=',null);

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
	values (9258,6,'Process','InsuranceCoverageDtls.do?event=maker_prepare_resubmit_create&TrxId=',null);

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
	values (9261,6,'Close','InsuranceCoverageDtls.do?event=maker_prepare_close&TrxId=',null);

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
	values (9263,7,'Process','InsuranceCoverageDtls.do?event=checker_process_delete&TrxId=',null);

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
	values (9266,7,'Process','InsuranceCoverageDtls.do?event=checker_process_edit&TrxId=','InsuranceCoverageDtls.do?event=to_track&TrxId=');
	
	
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
	values (9281,6,'Process','InsuranceCoverageDtls.do?event=maker_save_process&TrxId=','InsuranceCoverageDtls.do?event=to_track&TrxId=');

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
	values (9282,6,'Process','InsuranceCoverageDtls.do?event=maker_update_save_process&TrxId=','InsuranceCoverageDtls.do?event=to_track&TrxId=');

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
	values (9285,6,'Close','InsuranceCoverageDtls.do?event=maker_draft_close_process&TrxId=','InsuranceCoverageDtls.do?event=to_track&TrxId=');

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
	values (9287,6,'Process','InsuranceCoverageDtls.do?event=maker_update_save_process&TrxId=','InsuranceCoverageDtls.do?event=to_track&TrxId=');
	

-----------------------------------
--- CMS_TRX_TOTRACK Entries 
-----------------------------------

insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
	values ('INSU_CVRG_DTLS','InsuranceCoverageDtls.do?event=rejected_delete_read&toTrack=yes&TrxId=','DELETED','Deleted','Maintain Insurance Coverage Details',null,null);
	
insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
	values ('INSU_CVRG_DTLS','InsuranceCoverageDtls.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_CREATE','Pending Create','Maintain Insurance Coverage Details',null,null);
	
insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
	values ('INSU_CVRG_DTLS','InsuranceCoverageDtls.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_DELETE','Pending Delete','Maintain Insurance Coverage Details',null,null);
	
insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
	values ('INSU_CVRG_DTLS','InsuranceCoverageDtls.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_UPDATE','Pending Update','Maintain Insurance Coverage Details',null,null);
	
insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
	values ('INSU_CVRG_DTLS','InsuranceCoverageDtls.do?event=rejected_delete_read&toTrack=yes&TrxId=','REJECTED','Rejected','Maintain Insurance Coverage Details',null,null);

	
insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
	values('INSU_CVRG_DTLS','InsuranceCoverageDtls.do?event=rejected_delete_read&toTrack=yes&TrxId=','DRAFT','Draft','Maintain Insurance Coverage Details',null,null);	
-----------------------------------
--- TR_STATE_MATRIX Entries 
-----------------------------------

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9251,'INSU_CVRG_DTLS','EDIT_REJECTED_DELETE','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9252,'INSU_CVRG_DTLS','CREATE_INSU_CVRG_DTLS','PENDING_CREATE','PENDING_CREATE','PENDING_CREATE','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9253,'INSU_CVRG_DTLS','APROVE_INSU_CVRG_DTLS','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9254,'INSU_CVRG_DTLS','UPDATE_INSU_CVRG_DTLS','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9255,'INSU_CVRG_DTLS','APPROVE_CREATE_INSU_CVRG_DTLS','PENDING_CREATE','ACTIVE','ACTIVE','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9256,'INSU_CVRG_DTLS','REJECT_INSU_CVRG_DTLS','PENDING_UPDATE','REJECTED','REJECTED','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9257,'INSU_CVRG_DTLS','EDIT_REJECTED_UPDATE_INSU_CVRG_DTLS','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9258,'INSU_CVRG_DTLS','CLOSE_REJECTED_UPDATE_INSU_CVRG_DTLS','REJECTED','CLOSED','CLOSED','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9259,'INSU_CVRG_DTLS','REJECT_INSU_CVRG_DTLS','PENDING_CREATE','REJECTED','REJECTED','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9260,'INSU_CVRG_DTLS','CLOSE_REJECTED_CREATE_INSU_CVRG_DTLS','REJECTED','CLOSED','CLOSED','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9261,'INSU_CVRG_DTLS','EDIT_REJECTED_CREATE_INSU_CVRG_DTLS','REJECTED','PENDING_CREATE','PENDING_CREATE','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9262,'INSU_CVRG_DTLS','DELETE_INSU_CVRG_DTLS','ACTIVE','PENDING_DELETE','PENDING_DELETE','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9263,'INSU_CVRG_DTLS','DELETE_INSU_CVRG_DTLS','PENDING_DELETE','DELETED','DELETED','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9264,'INSU_CVRG_DTLS','REJECT_INSU_CVRG_DTLS','PENDING_DELETE','REJECTED','REJECTED','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9265,'INSU_CVRG_DTLS','CLOSE_REJECTED_INSU_CVRG_DTLS','REJECTED','CLOSED','CLOSED','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9266,'INSU_CVRG_DTLS','UPDATE_INSU_CVRG_DTLS','PENDING_UPDATE','ACTIVE','PENDING_UPDATE','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9267,'INSU_CVRG_DTLS','CHECKER_APPROVE_UPDATE','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9268,'INSU_CVRG_DTLS','CHECKER_APPROVE_DELETE','PENDING_DELETE','DELETED','DELETED','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9269,'INSU_CVRG_DTLS','APPROVE_INSU_CVRG_DTLS','PENDING_DELETE','DELETED','DELETED','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9270,'INSU_CVRG_DTLS','CHECKER_APPROVE_UPDATE','PENDING_DELETE','DELETED','DELETED','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9271,'INSU_CVRG_DTLS','CREATE_INSU_CVRG_DTLS','ND','PENDING_CREATE','PENDING_CREATE','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9272,'INSU_CVRG_DTLS','CLOSE_REJECTED_DELETE_INSU_CVRG_DTLS','REJECTED','CLOSED','CLOSED','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9273,'INSU_CVRG_DTLS','DELETE_INSU_CVRG_DTLS','CLOSED','PENDING_DELETE','PENDING_DELETE','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9274,'INSU_CVRG_DTLS','APPROVE_DELETE_INSU_CVRG_DTLS','PENDING_DELETE','DELETED','DELETED','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9275,'INSU_CVRG_DTLS','CREATE_INSU_CVRG_DTLS','ACTIVE','PENDING_CREATE','PENDING_CREATE','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9276,'INSU_CVRG_DTLS','EDIT_REJECTED_DELETE_INSU_CVRG_DTLS','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9277,'INSU_CVRG_DTLS','EDIT_REJECTED_INSU_CVRG_DTLS','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9278,'INSU_CVRG_DTLS','EDIT_REJECTED_INSU_CVRG_DTLS','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9279,'INSU_CVRG_DTLS','EDIT_REJECTED_DELETE','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9280,'INSU_CVRG_DTLS','UPDATE_INSU_CVRG_DTLS','CLOSED','PENDING_UPDATE','PENDING_UPDATE','1','1');
	

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9281,'INSU_CVRG_DTLS','SAVE_INSU_CVRG_DTLS','PENDING_PERFECTION','DRAFT','DRAFT','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9282,'INSU_CVRG_DTLS','CREATE_INSU_CVRG_DTLS','DRAFT','PENDING_CREATE','PENDING_CREATE','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9283,'INSU_CVRG_DTLS','MAKER_UPDATE_SAVE','ACTIVE','DRAFT','DRAFT','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9284,'INSU_CVRG_DTLS','UPDATE_INSU_CVRG_DTLS','DRAFT','PENDING_UPDATE','PENDING_UPDATE','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9285,'INSU_CVRG_DTLS','MAKER_UPDATE_CLOSE','DRAFT','ACTIVE','ACTIVE','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9286,'INSU_CVRG_DTLS','CLOSE_CREATE_INSU_CVRG_DTLS','DRAFT','CLOSED','CLOSED','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9287,'INSU_CVRG_DTLS','SAVE_UPDATE_INSU_CVRG_DTLS','ACTIVE','DRAFT','DRAFT','1','1');
	
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (9288,'INSU_CVRG_DTLS','SAVE_UPDATE_INSU_CVRG_DTLS','CLOSED','DRAFT','DRAFT','1','1');
	
	