CREATE TABLE SI_HOST_COL_CODE_MAP (
  SECURITY_TYPE_ID	VARCHAR(5),
  SECURITY_SUB_TYPE_ID	VARCHAR(10),
  HOST_COL_CAT_DESC	VARCHAR(10),
  HOST_COL_CODE	VARCHAR(10),
  HOST_COL_DESC VARCHAR(100),
  SOURCE_ID	VARCHAR(10)
) in CMS_BATCH index in CMS_BATCH_INDEX;
    
COMMENT ON SI_HOST_COL_CODE_MAP ( 
	SECURITY_TYPE_ID IS 'CMS Collateral Type Id',
	SECURITY_SUB_TYPE_ID IS 'CMS Collateral Subtype Id',
	HOST_COL_CODE IS 'Source System Collateral Code',
	HOST_COL_CAT_DESC IS 'Source Sytem Collateral Category Description',
	HOST_COL_DESC IS 'Source System Collateral Code Description',
	SOURCE_ID IS 'Source System ID' );

CREATE TABLE SI_ERROR_LOG (
  SI_NUMBER	BIGINT	GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  TIME_STAMP	TIMESTAMP,
  SYSTEM_ID	VARCHAR(10),
  INTERFACE_ID	VARCHAR(10),
  KEY1_VALUE	VARCHAR(50),
  KEY2_VALUE	VARCHAR(50),
  KEY3_VALUE	VARCHAR(50),
  KEY4_VALUE	VARCHAR(50),
  KEY5_VALUE	VARCHAR(50),
  ERROR_CODE	VARCHAR(20),
  ERROR_MSG	VARCHAR(500)
) in CMS_BATCH index in CMS_BATCH_INDEX;
	
CREATE TABLE SI_PROC_TIME_LOG(
  PROC_NUMBER BIGINT NOT NULL GENERATED ALWAYS
    AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
 PROC_NAME VARCHAR(255),
 SOURCE_ID VARCHAR(10),
 START_FLAG INT,
 TIME_STAMP TIMESTAMP)
in CMS_BATCH index in CMS_BATCH_INDEX;

CREATE TABLE SI_TRX_STG_LMT_UPDATE (
	ACT_LMT_ID BIGINT,
	STG_LMT_ID BIGINT)
	IN CMS_BATCH INDEX IN CMS_BATCH_INDEX;

CREATE TABLE SI_LOAD_TYPE_CONFIG (
  CONFIG_ID BIGINT NOT NULL GENERATED ALWAYS
    AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  PROC_NAME VARCHAR(255),
  SOURCE_ID VARCHAR(10),
  DAY_NUMBER INT,
  LOAD_TYPE VARCHAR(50)
) in CMS_BATCH index in CMS_BATCH_INDEX;

COMMENT ON SI_LOAD_TYPE_CONFIG ( 
	CONFIG_ID IS 'Running Number',
	PROC_NAME IS 'Procedure Name',
	SOURCE_ID IS 'Source System Id',
	DAY_NUMBER IS 'Day of Week (1-7)',
	LOAD_TYPE IS 'SI Loading Type (FULL/DELTA)');

create index SI_TRX_STG_LMT_UPDATE_IDX1 on SI_TRX_STG_LMT_UPDATE
(ACT_LMT_ID asc, STG_LMT_ID) cluster;
	
CREATE INDEX idx_src_colcode1 ON si_host_col_code_map(host_col_code);

COMMIT WORK;