
DECLARE GLOBAL TEMPORARY TABLE SESSION.TEMP_CMS_VALUATION_MVAL (
	CMS_COLLATERAL_ID 		BIGINT,
	CMV 					DECIMAL(20, 2),
	VALUATION_DATE 			TIMESTAMP,
	SOURCE_ID 				VARCHAR(10)
) 
WITH REPLACE ON COMMIT PRESERVE ROWS NOT LOGGED;	

DECLARE GLOBAL TEMPORARY TABLE SESSION.TEMP_CMS_VALUATION_SVAL (
	CMS_COLLATERAL_ID 		BIGINT,
	CMV 					DECIMAL(20, 2),
	VALUATION_DATE 			TIMESTAMP,
	SOURCE_ID 				VARCHAR(10)
) 
WITH REPLACE ON COMMIT PRESERVE ROWS NOT LOGGED;

DECLARE GLOBAL TEMPORARY TABLE SESSION.TEMP_CMS_VALUATION_LVAL (
	CMS_COLLATERAL_ID 		BIGINT,
	CMV 					DECIMAL(20, 2),
	VALUATION_DATE 			TIMESTAMP,
	SOURCE_ID 				VARCHAR(10)
) 
WITH REPLACE ON COMMIT PRESERVE ROWS NOT LOGGED;

DECLARE GLOBAL TEMPORARY TABLE SESSION.TEMP_CMS_SECURITY_MVAL (
	CMS_COLLATERAL_ID 			BIGINT,
	SCI_SECURITY_DTL_ID			VARCHAR(50),
	SCI_SECURITY_SUBTYPE_VALUE	VARCHAR(10),
	SALE_PURCHASE_DATE			TIMESTAMP,
	MVALUATION_DATE 			TIMESTAMP
) 
WITH REPLACE ON COMMIT PRESERVE ROWS NOT LOGGED;

DECLARE GLOBAL TEMPORARY TABLE SESSION.TEMP_CMS_SECURITY_MVAL_SYSVAL (
	CMS_COLLATERAL_ID 			BIGINT,
	SCI_SECURITY_DTL_ID			VARCHAR(50),
	SCI_SECURITY_SUBTYPE_VALUE	VARCHAR(10),
	SALE_PURCHASE_DATE			TIMESTAMP,
	MVALUATION_DATE 			TIMESTAMP,
	SYSVALUATION_DATE 			TIMESTAMP
) 
WITH REPLACE ON COMMIT PRESERVE ROWS NOT LOGGED;

DECLARE GLOBAL TEMPORARY TABLE SESSION.TEMP_CMS_SECURITY_MVAL_SYSVAL_LVAL (
	CMS_COLLATERAL_ID 			BIGINT,
	SCI_SECURITY_DTL_ID			VARCHAR(50),
	SCI_SECURITY_SUBTYPE_VALUE	VARCHAR(10),
	SALE_PURCHASE_DATE			TIMESTAMP,
	MVALUATION_DATE 			TIMESTAMP,
	SYSVALUATED_DATE 			TIMESTAMP,
	LVALUATION_DATE 			TIMESTAMP
) 
WITH REPLACE ON COMMIT PRESERVE ROWS NOT LOGGED;


------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Manual Valuation
insert into SESSION.TEMP_CMS_VALUATION_MVAL (	
	select mval.CMS_COLLATERAL_ID, mval.CMV, mval.VALUATION_DATE, mval.SOURCE_ID from CMS_VALUATION mval
	where mval.SOURCE_TYPE = 'M'
	and year(mval.VALUATION_DATE) < 2000
	and mval.VALUATION_ID = (select max(maxmval.VALUATION_ID) from CMS_VALUATION maxmval
							where maxmval.SOURCE_TYPE = 'M'
							and year(mval.VALUATION_DATE) < 2000
							and maxmval.CMS_COLLATERAL_ID = mval.CMS_COLLATERAL_ID));

-- System valuation			
insert into SESSION.TEMP_CMS_VALUATION_SVAL (	
	select sval.CMS_COLLATERAL_ID, sval.CMV, sval.VALUATION_DATE, sval.SOURCE_ID from CMS_VALUATION sval
	where sval.SOURCE_TYPE = 'A'
	and year(sval.VALUATION_DATE) < 2000
	and sval.VALUATION_ID = (select max(maxsval.VALUATION_ID) from CMS_VALUATION maxsval
							where maxsval.SOURCE_TYPE = 'A'
							and year(sval.VALUATION_DATE) < 2000
							and maxsval.CMS_COLLATERAL_ID = sval.CMS_COLLATERAL_ID));							
							
-- Los Valuation							
insert into SESSION.TEMP_CMS_VALUATION_LVAL (	
	select lval.CMS_COLLATERAL_ID, lval.CMV, lval.VALUATION_DATE, lval.SOURCE_ID from CMS_VALUATION lval
	where lval.SOURCE_TYPE = 'S'
	and year(lval.VALUATION_DATE) < 2000
	and lval.VALUATION_ID = (select max(maxlval.VALUATION_ID) from CMS_VALUATION maxlval
							where maxlval.SOURCE_TYPE = 'S'
							and year(lval.VALUATION_DATE) < 2000
							and maxlval.CMS_COLLATERAL_ID = lval.CMS_COLLATERAL_ID));
							
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

insert into SESSION.TEMP_CMS_SECURITY_MVAL (
	select sec.CMS_COLLATERAL_ID, sec.SCI_SECURITY_DTL_ID, sec.SCI_SECURITY_SUBTYPE_VALUE, pty.SALE_PURCHASE_DATE, 
		mval.VALUATION_DATE
	from CMS_PROPERTY pty, CMS_SECURITY sec left outer join
		    (select mval.CMS_COLLATERAL_ID, mval.CMV, mval.VALUATION_DATE, mval.SOURCE_ID from SESSION.TEMP_CMS_VALUATION_MVAL mval) mval
		    ON sec.CMS_COLLATERAL_ID = mval.CMS_COLLATERAL_ID
	where sec.CMS_COLLATERAL_ID = pty.CMS_COLLATERAL_ID
	and year(pty.SALE_PURCHASE_DATE) < 2000
);		
		
insert into SESSION.TEMP_CMS_SECURITY_MVAL_SYSVAL (						
	SELECT secval.*, sval.VALUATION_DATE FROM SESSION.TEMP_CMS_SECURITY_MVAL secval
	left outer join SESSION.TEMP_CMS_VALUATION_SVAL sval
	on secval.CMS_COLLATERAL_ID = sval.CMS_COLLATERAL_ID	
);

insert into SESSION.TEMP_CMS_SECURITY_MVAL_SYSVAL_LVAL (
	SELECT secval.*, lval.VALUATION_DATE FROM SESSION.TEMP_CMS_SECURITY_MVAL_SYSVAL secval
	left outer join SESSION.TEMP_CMS_VALUATION_LVAL lval
	on secval.CMS_COLLATERAL_ID = lval.CMS_COLLATERAL_ID
);		
		
select SCI_SECURITY_DTL_ID as SECURITY_ID, SCI_SECURITY_SUBTYPE_VALUE as SECURITY_SUBTYPE, SALE_PURCHASE_DATE, MVALUATION_DATE as MANUAL_VAL_DATE,
SYSVALUATED_DATE as SYSTEM_VAL_DATE, LVALUATION_DATE as LOS_VAL_DATE
from SESSION.TEMP_CMS_SECURITY_MVAL_SYSVAL_LVAL		







							
