drop table DC_DOC;

drop table DC_DOC_ERR;

CREATE TABLE DC_DOC (
	CIF_NUMBER VARCHAR(20),
	BORROWER_NAME VARCHAR(100),
	ACCOUNT_NUMBER VARCHAR(40),
	BUSINESS_UNIT VARCHAR(15),
	BRANCH_CODE VARCHAR(3),
	CMS_COLLATERAL_ID BIGINT NOT NULL,	
	COLLATERAL_CODE VARCHAR(4),
	--COLLATERAL_CODE_DESC VARCHAR(200), -- ignore description
	COLLATERAL_NAME VARCHAR(30),
	SECURITY_CUSTODIAN_TYPE VARCHAR(10) DEFAULT 'I', -- update
	CUSTODIAN_TYPE_CODE CHAR(1), -- setvalue
	SECURITY_CUSTODIAN_VALUE VARCHAR(100), --update
	CUSTODIAN_VALUE_CODE VARCHAR(10), -- setvalue
	SECURITY_MATURITY_DATE TIMESTAMP, -- update
	EXCHANGE_CONTROL_OBTAINED CHAR(1) DEFAULT 'N',	-- update (optional)
	TYPE_OF_DEED_ASSIGNMENT VARCHAR(30), --update
	TYPE_DEED_ASSN_CODE VARCHAR(10), --update
	DOCUMENT_DATE TIMESTAMP, --update
	DOCUMENT_AMT_CCY CHAR(3), --update
	DOCUMENT_AMT DECIMAL(20,2), --update
	ISDA_AGREEMENT_DATE TIMESTAMP, --update
	IFEMA_AGREEMENT_DATE TIMESTAMP, --update
	ICOM_DOCUMENT_DATE TIMESTAMP, --update
	ISDA_DESC VARCHAR(20),	-- update (optional)
	REF_NUMBER VARCHAR(100),	-- update (optional)
	SPECIFIC_UNDERTAKING_REMARKS VARCHAR(2000),	-- update (optional)
	IFEMA_DESC VARCHAR(20),	-- update (optional)
	ICOM_DESC VARCHAR(20),		-- update (optional)
	MIN_AMT_CCY CHAR(3),	-- update (optional)
	MIN_AMT DECIMAL(30,2),	-- update (optional)
	MAX_AMT_CCY CHAR(3),	-- update (optional)
	MAX_AMT DECIMAL(30,2),	-- update (optional)
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',	-- update (optional)
	VALID_IND CHAR(1) DEFAULT 'Y'	-- update (optional)
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "DC_DOC" 
	ADD CONSTRAINT "DC_DOC_U" UNIQUE
		("CMS_COLLATERAL_ID",
		 "REGION");

CREATE TABLE DC_DOC_ERR LIKE DC_DOC
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE DC_DOC_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE DC_DOC_ERR
  ADD REASON	CLOB;