drop table DC_ERROR_LOG@
drop table DC_PROC_TIME_LOG@
DROP PROCEDURE DC_log_proc_time
@

CREATE TABLE DC_ERROR_LOG (
  SI_NUMBER	BIGINT	GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  TIME_STAMP	TIMESTAMP,
  SYSTEM_ID	VARCHAR(40),
  INTERFACE_ID	VARCHAR(50),
  KEY1_VALUE	VARCHAR(50),
  KEY2_VALUE	VARCHAR(50),
  KEY3_VALUE	VARCHAR(50),
  KEY4_VALUE	VARCHAR(50),
  KEY5_VALUE	VARCHAR(50),
  ERROR_CODE	VARCHAR(20),
  ERROR_MSG	VARCHAR(1000)
) in CMS_MIG index in CMS_MIG_INDEX
@
	
CREATE TABLE DC_PROC_TIME_LOG(
  PROC_NUMBER BIGINT NOT NULL GENERATED ALWAYS
    AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
 PROC_NAME VARCHAR(255),
 SOURCE_ID VARCHAR(40),
 START_FLAG INT,
 TIME_STAMP TIMESTAMP)
in CMS_MIG index in CMS_MIG_INDEX
@

CREATE PROCEDURE DC_LOG_PROC_TIME (
    IN P_PROC_NAME VARCHAR(255),
    IN P_SOURCE_ID VARCHAR(40),
  	IN P_START_FLAG INT)
  LANGUAGE SQL
BEGIN ATOMIC
 
 INSERT INTO DC_PROC_TIME_LOG (proc_name, source_id, start_flag, time_stamp)
  VALUES (P_PROC_NAME, P_SOURCE_ID, P_START_FLAG, CURRENT_TIMESTAMP);
END
@