drop table DC_PT;

drop table DC_PT_ERR;

CREATE TABLE DC_PT (
	CIF_NUMBER VARCHAR(20),
	BORROWER_NAME VARCHAR(100),
	ACCOUNT_NUMBER VARCHAR(40),
	BUSINESS_UNIT VARCHAR(15),
	BRANCH_CODE VARCHAR(3),
	CMS_COLLATERAL_ID BIGINT NOT NULL,	
	COLLATERAL_CODE VARCHAR(4),
	--COLLATERAL_CODE_DESC VARCHAR(200), -- ignore description
	COLLATERAL_NAME VARCHAR(30),
	PURCHASE_VALUE DECIMAL(15,2), 
	TITLE_TYPE VARCHAR(15), -- update 
	TITLE_TYPE_CODE VARCHAR(40),  -- derive from cc
	LAND_AREA DECIMAL(18,2), -- update
	LAND_AREA_UOM VARCHAR(10),  -- update
	LA_UOM_CODE VARCHAR(40), --derive from cc
	BUILT_UP_AREA DECIMAL(10,0),  -- update
	BUILT_UP_AREA_UOM VARCHAR(10),  -- update 
	BUA_UOM_CODE VARCHAR(40), --derive from cc
	STATE VARCHAR (40), -- update
	STATE_CODE  VARCHAR(40), -- derive from cc
	DISTRICT VARCHAR (40),  -- update
	DISTRICT_CODE  VARCHAR(40), -- derive from cc
	MUKIM VARCHAR (80),  -- update
	MUKIM_CODE  VARCHAR(40), -- derive from cc
	PROPERTY_COMPLETION_STATUS VARCHAR(25),  -- update
	DEVELOPER_NAME VARCHAR(40),  -- update 
	DEVELOPER_NAME_CODE VARCHAR(40),  -- derive from cc
	CURRENT_MARKET_VALUE DECIMAL(17,2), --update
	VALUATION_DATE TIMESTAMP, -- update 
	FSV DECIMAL(20,2), -- update (optional)
	VALUATION_TYPE_DESC VARCHAR(10), --update
	VALUATION_TYPE CHAR(1), -- update
	PROJECT_NAME VARCHAR (40),  -- udpate (optional)
	PROJECT_NAME_CODE VARCHAR(40), --derive from cc
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	VALID_IND CHAR(1) DEFAULT 'Y'
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "DC_PT" 
	ADD CONSTRAINT "DC_PT_U" UNIQUE
		("CMS_COLLATERAL_ID",
		 "REGION");

CREATE TABLE DC_PT_ERR LIKE DC_PT
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE DC_PT_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE DC_PT_ERR
  ADD REASON	CLOB;