drop table DC_GT;

drop table DC_GT_ERR;

CREATE TABLE DC_GT (
	CIF_NUMBER VARCHAR(20),
	BORROWER_NAME VARCHAR(100),
	ACCOUNT_NUMBER VARCHAR(40),
	BUSINESS_UNIT VARCHAR(15),
	BRANCH_CODE VARCHAR(3),
	CMS_COLLATERAL_ID BIGINT NOT NULL,	
	COLLATERAL_CODE VARCHAR(4),
	--COLLATERAL_CODE_DESC VARCHAR(200), -- ignore description
	COLLATERAL_NAME VARCHAR(30),
	SECURITY_CURRENCY CHAR(3),  -- update
	SECURITY_MATURITY_DATE TIMESTAMP, -- update 
	GUARANTEE_DATE TIMESTAMP, -- update
	GUARANTEE_REF_NUMBER VARCHAR(60), --update  (optional)
	CORRESPONDENCE_BANK CHAR(1), --update  (optional)
	WITHIN_CORRESPONDENCE_BANK_LMT CHAR(1), --update  (optional)
	CORRESPONDING_BANK VARCHAR(100), --update  (optional)
	CLAIM_PERIOD DECIMAL(9,3), --update  (optional)
	CLAIM_PERIOD_TIME_UNIT VARCHAR(10), --update  (optional)
	SCHEME VARCHAR(20), --update
	GUARANTEE_FEE_AMT DECIMAL(15,2), --update
	CGC_FEE_PAYMENT_ACCT DECIMAL(15), --update  (optional)
	TENOR INT, --update  (optional)
	TENOR_UOM VARCHAR(10), --update  (optional)
	EFFECTIVE_DATE TIMESTAMP, --update  (optional)
	EXPIRATION_DATE TIMESTAMP, --update 
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	VALID_IND CHAR(1) DEFAULT 'Y'
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "DC_GT" 
	ADD CONSTRAINT "DC_GT_U" UNIQUE
		("CMS_COLLATERAL_ID",
		 "REGION");

CREATE TABLE DC_GT_ERR LIKE DC_GT
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE DC_GT_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE DC_GT_ERR
  ADD REASON	CLOB;