-----------------------------
-- Cleanup
-----------------------------
DELETE FROM MIG_QC_REPORT;

-----------------------------
-- Customer
-----------------------------
-- CU001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CU001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV001SIBS', 'SIBS', 'CU001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CU001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CU001'), 'SIBS', 'CU001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'CIF ID / -, Error Message', 'SIBS', 'CU001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ' / ' || COALESCE(KEY2_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CU001' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CU001');

    
-----------------------------
-- AA
-----------------------------
-- CA001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV002SIBS', 'SIBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CA001'), 'SIBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'CIF ID / AA Number / LOS AA Number, Error Message', 'SIBS', 'CA001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ' / ' || COALESCE(KEY2_VALUE,'-') || ' / ' || COALESCE(KEY3_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CA001' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CA001');


-----------------------------
-- Joint Borrower
-----------------------------    
-- CA002
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CA002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV003SIBS', 'SIBS', 'CA002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CA002'), 'SIBS', 'CA002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'CIF ID / AA Number, Error Message', 'SIBS', 'CA002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ' / ' || COALESCE(KEY2_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CA002' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CA002');

 
 
-----------------------------
-- Facility
-----------------------------    
-- CA003_1
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CA003_1');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV004SIBS', 'SIBS', 'CA003_1');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_1');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CA003_1'), 'SIBS', 'CA003_1');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'CIF ID / Limit ID / AA Number / Facility Code / Facility Sequence, Error Message', 'SIBS', 'CA003_1');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ' / ' || COALESCE(KEY2_VALUE,'-') || ' / ' || COALESCE(KEY3_VALUE,'-') || ' / ' || COALESCE(KEY4_VALUE,'-') || ' / ' || COALESCE(KEY5_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CA003_1' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CA003_1');
 
-- CA003_2
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CA003_2');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV005SIBS', 'SIBS', 'CA003_2');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_2');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CA003_2'), 'SIBS', 'CA003_2');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Limit ID / AA Number /Facility Code / Facility Sequence, Error Message', 'SIBS', 'CA003_2');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ' / ' || COALESCE(KEY2_VALUE,'-') || ' / ' || COALESCE(KEY3_VALUE,'-') || ' / ' || COALESCE(KEY4_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CA003_2' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CA003_2');
 
-- CA003_3
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CA003_3');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV006SIBS', 'SIBS', 'CA003_3');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_3');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CA003_3'), 'SIBS', 'CA003_3');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Limit ID / AA Number /Facility Code / Facility Sequence / Officer Seq No, Error Message', 'SIBS', 'CA003_3');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ' / ' || COALESCE(KEY2_VALUE,'-') || ' / ' || COALESCE(KEY3_VALUE,'-') || ' / ' || COALESCE(KEY4_VALUE,'-') || ' / ' || COALESCE(KEY5_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CA003_3' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CA003_3');
 
-- CA003_4
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CA003_4');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV007SIBS', 'SIBS', 'CA003_4');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_4');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CA003_4'), 'SIBS', 'CA003_4');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Limit ID / AA Number /Facility Code / Facility Sequence / CIF ID, Error Message', 'SIBS', 'CA003_4');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ' / ' || COALESCE(KEY2_VALUE,'-') || ' / ' || COALESCE(KEY3_VALUE,'-') || ' / ' || COALESCE(KEY4_VALUE,'-') || ' / ' || COALESCE(KEY5_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CA003_4' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CA003_4');
 
-- CA003_5
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CA003_5');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV008SIBS', 'SIBS', 'CA003_5');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_5');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CA003_5'), 'SIBS', 'CA003_5');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Limit ID / AA Number /Facility Code / Facility Sequence, Error Message', 'SIBS', 'CA003_5');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ' / ' || COALESCE(KEY2_VALUE,'-') || ' / ' || COALESCE(KEY3_VALUE,'-') || ' / ' || COALESCE(KEY4_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CA003_5' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CA003_5');
 
-- CA003_6
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CA003_6');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV009SIBS', 'SIBS', 'CA003_6');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_6');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CA003_6'), 'SIBS', 'CA003_6');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Limit ID / AA Number /Facility Code / Facility Sequence / Tier Seq No, Error Message', 'SIBS', 'CA003_6');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ' / ' || COALESCE(KEY2_VALUE,'-') || ' / ' || COALESCE(KEY3_VALUE,'-') || ' / ' || COALESCE(KEY4_VALUE,'-') || ' / ' || COALESCE(KEY5_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CA003_6' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CA003_6');
 
-- CA003_7
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CA003_7');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV010SIBS', 'SIBS', 'CA003_7');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_7');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CA003_7'), 'SIBS', 'CA003_7');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Limit ID / AA Number /Facility Code / Facility Sequence, Error Message', 'SIBS', 'CA003_7');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ' / ' || COALESCE(KEY2_VALUE,'-') || ' / ' || COALESCE(KEY3_VALUE,'-') || ' / ' || COALESCE(KEY4_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CA003_7' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CA003_7');
 
-- CA003_8
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CA003_8');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV011SIBS', 'SIBS', 'CA003_8');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_8');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CA003_8'), 'SIBS', 'CA003_8');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Limit ID / AA Number /Facility Code / Facility Sequence, Error Message', 'SIBS', 'CA003_8');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ' / ' || COALESCE(KEY2_VALUE,'-') || ' / ' || COALESCE(KEY3_VALUE,'-') || ' / ' || COALESCE(KEY4_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CA003_8' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CA003_8');
 
 
-----------------------------
-- Limit-Account
-----------------------------    
-- CA004
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CA004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV016SIBS', 'SIBS', 'CA004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CA004'), 'SIBS', 'CA004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Limit ID/ AA Number / External System Account No / Account Sequence, Error Message', 'SIBS', 'CA004');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ' / ' || COALESCE(KEY2_VALUE,'-') || ' / ' || COALESCE(KEY3_VALUE,'-') || ' / ' || COALESCE(KEY4_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CA004' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CA004');
 
 
 
-----------------------------
-- Collateral
-----------------------------
-- CO001:AB
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CO001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV018SIBS', 'SIBS', 'CO001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CO001'), 'SIBS', 'CO001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Security ID, Error Message', 'SIBS', 'CO001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CO001' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CO001'); 
 
-- CO002:AB-Gold
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CO002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV019SIBS', 'SIBS', 'CO002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CO002'), 'SIBS', 'CO002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Security ID, Error Message', 'SIBS', 'CO002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CO002' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CO002'); 
 
-- CO005:CS
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CO005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV022SIBS', 'SIBS', 'CO005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CO005'), 'SIBS', 'CO005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Security ID, Error Message', 'SIBS', 'CO005');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CO005' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CO005');

    
-- CO008:MS
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CO008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV024SIBS', 'SIBS', 'CO008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CO008'), 'SIBS', 'CO008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Security ID, Error Message', 'SIBS', 'CO008');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CO008' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CO008');

-- CO009:PT
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CO009');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV025SIBS', 'SIBS', 'CO009');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO009');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CO009'), 'SIBS', 'CO009');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Security ID, Error Message', 'SIBS', 'CO009');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CO009' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CO009');

-- CO010:GT
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CO010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV026SIBS', 'SIBS', 'CO010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CO010'), 'SIBS', 'CO010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Security ID, Error Message', 'SIBS', 'CO010');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CO010' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CO010');

-- CO011:OT
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CO011');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV027SIBS', 'SIBS', 'CO011');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO011');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CO011'), 'SIBS', 'CO011');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Security ID, Error Message', 'SIBS', 'CO011');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CO011' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CO011');

-- CO012:IN
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CO012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV028SIBS', 'SIBS', 'CO012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CO012'), 'SIBS', 'CO012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Security ID, Error Message', 'SIBS', 'CO012');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CO012' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CO012');

-- CO014:CL
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CO014');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV030SIBS', 'SIBS', 'CO014');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO014');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CO014'), 'SIBS', 'CO014');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Security ID, Error Message', 'SIBS', 'CO014');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CO014' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CO014');    

-- CO015:VL
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CO015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV031SIBS', 'SIBS', 'CO015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CO015'), 'SIBS', 'CO015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Security ID, Error Message', 'SIBS', 'CO015');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CO015' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CO015');    

-- CO016:INS Policy
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CO016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV032SIBS', 'SIBS', 'CO016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CO016'), 'SIBS', 'CO016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Security ID / Policy Number, Error Message', 'SIBS', 'CO016');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ' / ' || COALESCE(KEY2_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CO016' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CO016');    

-- CO017:CD
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CO017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV033SIBS', 'SIBS', 'CO017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CO017'), 'SIBS', 'CO017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Security ID / Application No / Facility Code / Faciltiy Sequence / Ranking of Security, Error Message', 'SIBS', 'CO017');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ' / ' || COALESCE(KEY2_VALUE,'-') || ' / ' || COALESCE(KEY3_VALUE,'-') || ' / ' || COALESCE(KEY4_VALUE,'-') || ' / ' || COALESCE(KEY5_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CO017' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CO017');    

-- CO018:Pledgor
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CO018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV034SIBS', 'SIBS', 'CO018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CO018'), 'SIBS', 'CO018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Security ID / Pledgor CIF ID, Error Message', 'SIBS', 'CO018');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ' / ' || COALESCE(KEY2_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CO018' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CO018');    

-- CO019:Pledge
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'QC Report 3 for Migration', 'SIBS', 'CO019');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report for migration template: CV035SIBS', 'SIBS', 'CO019');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO019');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Records with Error(s): ' || (SELECT char(COUNT(*)) FROM MIG_ERROR_LOG WHERE INTERFACE_ID = 'CO019'), 'SIBS', 'CO019');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Error', 'Security ID / Limit ID / Application No / Facility Code / Faciltiy Sequence, Error Message', 'SIBS', 'CO019');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Error', COALESCE(KEY1_VALUE,'-') || ' / ' || COALESCE(KEY2_VALUE,'-') || ' / ' || COALESCE(KEY3_VALUE,'-') || ' / ' || COALESCE(KEY4_VALUE,'-') || ' / ' || COALESCE(KEY5_VALUE,'-') || ',' || ERROR_MSG, 'SIBS', 'CO019' 
     FROM MIG_ERROR_LOG WHERE SYSTEM_ID = 'SIBS' AND INTERFACE_ID = 'CO019');    

  