--------------------------------------------------------
-- DDL Statements for table ABCLIMS .CMS_OTHER_BANK
--------------------------------------------------------

CREATE TABLE ABCLIMS.CMS_OTHER_BANK  (
		  ID BIGINT NOT NULL , 
		  BANK_CODE VARCHAR(60) , 
		  BANK_NAME VARCHAR(300) , 
		  ADDRESS VARCHAR(300) , 
		  CITY VARCHAR(25) , 
		  STATE VARCHAR(30) , 
		  REGION VARCHAR(20) , 
		  COUNTRY VARCHAR(30) , 
		  CONTACT_NO BIGINT , 
		  CONTACT_MAIL_ID VARCHAR(50) , 
		  VERSION_TIME BIGINT NOT NULL , 
		  CREATE_BY VARCHAR(20) NOT NULL , 
		  CREATION_DATE TIMESTAMP NOT NULL , 
		  LAST_UPDATE_BY VARCHAR(20) NOT NULL , 
		  LAST_UPDATE_DATE TIMESTAMP NOT NULL , 
		  DEPRECATED CHAR(1) NOT NULL , 
		  STATUS VARCHAR(60) NOT NULL , 
		  MASTER_ID BIGINT )   
		 IN CMS_SMALL_DATA INDEX IN CMS_INDEX ; 



ALTER TABLE ABCLIMS.CMS_OTHER_BANK 
	ADD CONSTRAINT PK_OTHER_BANK PRIMARY KEY
		(ID);

--------------------------------
--- Stage Other Bank Dummy Entry
--------------------------------		
		
CREATE TABLE ABCLIMS.CMS_STAGE_OTHER_BANK  (
		  ID BIGINT NOT NULL , 
		  BANK_CODE VARCHAR(60) , 
		  BANK_NAME VARCHAR(300) , 
		  ADDRESS VARCHAR(300) , 
		  CITY VARCHAR(25) , 
		  STATE VARCHAR(30) , 
		  REGION VARCHAR(20) , 
		  COUNTRY VARCHAR(30) , 
		  CONTACT_NO BIGINT , 
		  CONTACT_MAIL_ID VARCHAR(50) , 
		  VERSION_TIME BIGINT NOT NULL , 
		  CREATE_BY VARCHAR(20) NOT NULL , 
		  CREATION_DATE TIMESTAMP NOT NULL , 
		  LAST_UPDATE_BY VARCHAR(20) NOT NULL , 
		  LAST_UPDATE_DATE TIMESTAMP NOT NULL , 
		  DEPRECATED CHAR(1) NOT NULL , 
		  STATUS VARCHAR(60) NOT NULL , 
		  MASTER_ID BIGINT )   
		 IN CMS_SMALL_DATA INDEX IN CMS_INDEX ; 



ALTER TABLE ABCLIMS.CMS_STAGE_OTHER_BANK 
	ADD CONSTRAINT PK_OTHER_BANK PRIMARY KEY
		(ID);		

--------------------------------------------------------
-- DDL Statements for table ABCLIMS .CMS_OTHER_BANK_BRANCH
--------------------------------------------------------		

CREATE TABLE ABCLIMS.CMS_OTHER_BANK_BRANCH  (
		  ID BIGINT NOT NULL , 
		  BRANCH_CODE VARCHAR(60) NOT NULL , 
		  OTHER_BANK_CODE VARCHAR(60) NOT NULL , 
		  BRANCH_NAME VARCHAR(1024) NOT NULL , 
		  ADDRESS VARCHAR(300) ,
		  CITY_TOWN VARCHAR(100) NOT NULL , 
		  STATE VARCHAR(100) NOT NULL , 
		  COUNTRY VARCHAR(100) NOT NULL , 
		  REGION VARCHAR(100) , 		   
		  CONTACT_NUMBER BIGINT , 
		  CONTACT_MAIL VARCHAR(100) , 
		  VERSION_TIME BIGINT NOT NULL , 
		  CREATE_BY VARCHAR(20) NOT NULL , 
		  CREATION_DATE TIMESTAMP NOT NULL , 
		  LAST_UPDATE_BY VARCHAR(20) NOT NULL , 
		  LAST_UPDATE_DATE TIMESTAMP NOT NULL , 
		  DEPRECATED CHAR(1) NOT NULL , 
		  STATUS VARCHAR(60) NOT NULL , 
		  MASTER_ID BIGINT )   
		 IN CMS_MEDIUM_DATA INDEX IN CMS_INDEX ; 


ALTER TABLE ABCLIMS.CMS_OTHER_BANK_BRANCH 
	ADD CONSTRAINT PK_OTHER_BANK_BRANCH PRIMARY KEY
		(ID);

--------------------------------
--- Stage Other Bank Branch Dummy Entry
--------------------------------			

CREATE TABLE ABCLIMS.CMS_STAGE_OTHER_BANK_BRANCH  (
		  ID BIGINT NOT NULL , 
		  BRANCH_CODE VARCHAR(60) NOT NULL , 
		  OTHER_BANK_CODE VARCHAR(60) NOT NULL , 
		  BRANCH_NAME VARCHAR(1024) NOT NULL , 
		  ADDRESS VARCHAR(300) ,
		  CITY_TOWN VARCHAR(100) NOT NULL , 
		  STATE VARCHAR(100) NOT NULL , 
		  COUNTRY VARCHAR(100) NOT NULL , 
		  REGION VARCHAR(100) , 		   
		  CONTACT_NUMBER BIGINT , 
		  CONTACT_MAIL VARCHAR(100) , 
		  VERSION_TIME BIGINT NOT NULL , 
		  CREATE_BY VARCHAR(20) NOT NULL , 
		  CREATION_DATE TIMESTAMP NOT NULL , 
		  LAST_UPDATE_BY VARCHAR(20) NOT NULL , 
		  LAST_UPDATE_DATE TIMESTAMP NOT NULL , 
		  DEPRECATED CHAR(1) NOT NULL , 
		  STATUS VARCHAR(60) NOT NULL , 
		  MASTER_ID BIGINT )   
		 IN CMS_MEDIUM_DATA INDEX IN CMS_INDEX ; 




ALTER TABLE ABCLIMS.CMS_STAGE_OTHER_BANK_BRANCH 
	ADD CONSTRAINT PK_OTHER_BANK_BRANCH PRIMARY KEY
		(ID);
		
		

INSERT INTO CMS_OTHER_BANK VALUES(1,'1','AXIS BANK','ANDHERI','MUMBAI','MAHARASHTRA','WEST','INDIA',67707675,'axis_andheri@axis.com',0,'CMS','2011-02-22 18:18:24.735','CMS','2011-02-22 18:18:24.735','N','ACTIVE',1);

INSERT INTO CMS_STAGE_OTHER_BANK VALUES(1,'1','AXIS BANK','ANDHERI','MUMBAI','MAHARASHTRA','WEST','INDIA',67707675,'axis_andheri@axis.com',0,'CMS','2011-02-22 18:18:24.735','CMS','2011-02-22 18:18:24.735','N','ACTIVE',1);

INSERT INTO CMS_OTHER_BANK_BRANCH VALUES(1,'111','1','AXIS BANK','ANDHERI','MUMBAI','MAHARASHTRA','INDIA','WEST',67707675,'axis_andheri@axis.com',0,'CMS','2011-02-22 18:18:24.735','CMS','2011-02-22 18:18:24.735','N','ACTIVE',1);

INSERT INTO CMS_STAGE_OTHER_BANK_BRANCH VALUES(1,'111','1','AXIS BANK','ANDHERI','MUMBAI','MAHARASHTRA','INDIA','WEST',67707675,'axis_andheri@axis.com',0,'CMS','2011-02-22 18:18:24.735','CMS','2011-02-22 18:18:24.735','N','ACTIVE',1);
