---------------------------------------
----  Director Master CMS_TRX_TOTRACK
---------------------------------------
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
VALUES ('DIRECTOR_MASTER','directorMaster.do?event=rejected_delete_read&toTrack=yes&TrxId=','REJECTED','Rejected','Maintain Director Master',null,null);
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
VALUES('DIRECTOR_MASTER','directorMaster.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_DISABLE','Pending Disable','Maintain Director Master',null,null);
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
VALUES('DIRECTOR_MASTER','directorMaster.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_ENABLE','Pending Enable','Maintain Director Master',null,null);
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
VALUES('DIRECTOR_MASTER','directorMaster.do?event=rejected_delete_read&toTrack=yes&TrxId=','ENABLE','enable','Maintain Director Master',null,null);
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
VALUES('DIRECTOR_MASTER','directorMaster.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_CREATE','Pending Create','Maintain Director Master',null,null);
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
VALUES('DIRECTOR_MASTER','directorMaster.do?event=rejected_delete_read&toTrack=yes&TrxId=','DRAFT','Draft','Maintain Director Master',null,null);
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
VALUES('DIRECTOR_MASTER','directorMaster.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_UPDATE','Pending Update','Maintain Director Master',null,null);
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
VALUES('DIRECTOR_MASTER','directorMaster.do?event=rejected_delete_read&toTrack=yes&TrxId=','REJECTED','Rejected','Maintain Director Master',null,null);
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
VALUES('DIRECTOR_MASTER','directorMaster.do?event=rejected_delete_read&toTrack=yes&TrxId=','DISABLE','disable','Maintain Director Master',null,null);
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
VALUES('DIRECTOR_MASTER','directorMaster.do?event=rejected_delete_read&toTrack=yes&TrxId=','CLOSED','Closed','Maintain Director Master',null,null);
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
VALUES('DIRECTOR_MASTER','directorMaster.do?event=rejected_delete_read&toTrack=yes&TrxId=','ACTIVE','Approved','Maintain Director Master',null,null);

--------------------------------------------
--- Director Master Tr State Matrix
--------------------------------------------
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(240820103, 'DIRECTOR_MASTER', 'EDIT_REJECTED_DIRECTOR_MASTER', 'REJECTED', 'PENDING_DISABLE', 'PENDING_DISABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201001, 'DIRECTOR_MASTER', 'EDIT_REJECTED_DISABLE', 'REJECTED', 'PENDING_DISABLE', 'PENDING_DISABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201002, 'DIRECTOR_MASTER', 'CREATE_DIRECTOR_MASTER', 'PENDING_CREATE', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201003, 'DIRECTOR_MASTER', 'APROVE_DIRECTOR_MASTER', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201004, 'DIRECTOR_MASTER', 'UPDATE_DIRECTOR_MASTER', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201005, 'DIRECTOR_MASTER', 'APPROVE_CREATE_DIRECTOR_MASTER', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201006, 'DIRECTOR_MASTER', 'REJECT_DIRECTOR_MASTER', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201007, 'DIRECTOR_MASTER', 'EDIT_REJECTED_UPDATE_DIRECTOR_MASTER', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201009, 'DIRECTOR_MASTER', 'REJECT_DIRECTOR_MASTER', 'PENDING_CREATE', 'REJECTED', 'REJECTED', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201010, 'DIRECTOR_MASTER', 'CLOSE_REJECTED_CREATE_DIRECTOR_MASTER', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201011, 'DIRECTOR_MASTER', 'EDIT_REJECTED_CREATE_DIRECTOR_MASTER', 'REJECTED', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201012, 'DIRECTOR_MASTER', 'DISABLE_DIRECTOR_MASTER', 'ACTIVE', 'PENDING_DISABLE', 'PENDING_DISABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201013, 'DIRECTOR_MASTER', 'DISABLE_DIRECTOR_MASTER', 'PENDING_DISABLE', 'DISABLE', 'DISABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201014, 'DIRECTOR_MASTER', 'REJECT_DIRECTOR_MASTER', 'PENDING_DISABLE', 'REJECTED', 'REJECTED', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201015, 'DIRECTOR_MASTER', 'CLOSE_REJECTED_DIRECTOR_MASTER', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201016, 'DIRECTOR_MASTER', 'UPDATE_DIRECTOR_MASTER', 'PENDING_UPDATE', 'ACTIVE', 'PENDING_UPDATE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201017, 'DIRECTOR_MASTER', 'CHECKER_APPROVE_UPDATE', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201018, 'DIRECTOR_MASTER', 'CHECKER_APPROVE_DELETE', 'PENDING_DELETE', 'DELETED', 'DELETED', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201019, 'DIRECTOR_MASTER', 'APPROVE_DIRECTOR_MASTER', 'PENDING_DELETE', 'DELETED', 'DELETED', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201020, 'DIRECTOR_MASTER', 'CHECKER_APPROVE_UPDATE', 'DISABLE', 'DISABLE', 'DISABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201021, 'DIRECTOR_MASTER', 'CREATE_DIRECTOR_MASTER', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201022, 'DIRECTOR_MASTER', 'CLOSE_REJECTED_DELETE_DIRECTOR_MASTER', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201023, 'DIRECTOR_MASTER', 'DISABLE_DIRECTOR_MASTER', 'CLOSED', 'PENDING_DISABLE', 'PENDING_DISABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201024, 'DIRECTOR_MASTER', 'APPROVE_DISABLE_DIRECTOR_MASTER', 'PENDING_DISABLE', 'DISABLE', 'DISABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201025, 'DIRECTOR_MASTER', 'CREATE_DIRECTOR_MASTER', 'ACTIVE', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201026, 'DIRECTOR_MASTER', 'EDIT_REJECTED_DISABLE_DIRECTOR_MASTER', 'REJECTED', 'PENDING_DISABLE', 'PENDING_DISABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201027, 'DIRECTOR_MASTER', 'EDIT_REJECTED_DIRECTOR_MASTER', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201028, 'DIRECTOR_MASTER', 'EDIT_REJECTED_DIRECTOR_MASTER', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201029, 'DIRECTOR_MASTER', 'EDIT_REJECTED_DISABLE', 'REJECTED', 'PENDING_DISABLE', 'PENDING_DISABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201030, 'DIRECTOR_MASTER', 'UPDATE_DIRECTOR_MASTER', 'CLOSED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201031, 'DIRECTOR_MASTER', 'CHECKER_APPROVE_UPDATE', 'PENDING_DISABLE', 'DISABLE', 'DISABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201032, 'DIRECTOR_MASTER', 'APPROVE_DIRECTOR_MASTER', 'PENDING_DISABLE', 'DELETED', 'DELETED', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201033, 'DIRECTOR_MASTER', 'APPROVE_DIRECTOR_MASTER', 'PENDING_DISABLE', 'DISABLE', 'DISABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201034, 'DIRECTOR_MASTER', 'CHECKER_APPROVE_DISABLE', 'PENDING_DISABLE', 'DISABLE', 'DISABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201036, 'DIRECTOR_MASTER', 'DISABLE_DIRECTOR_MASTER', 'DISABLE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201038, 'DIRECTOR_MASTER', 'DISABLE_DIRECTOR_MASTER', 'REJECTED', 'PENDING_DISABLE', 'PENDING_DISABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201041, 'DIRECTOR_MASTER', 'EDIT_REJECTED_ENABLE', 'REJECTED', 'PENDING_ENABLE', 'PENDING_ENABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201046, 'DIRECTOR_MASTER', 'APPROVE_DISABLE_DIRECTOR_MASTER', 'PENDING_ENABLE', 'ENABLE', 'ENABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201047, 'DIRECTOR_MASTER', 'EDIT_REJECTED_ENABLE_DIRECTOR_MASTER', 'REJECTED', 'PENDING_ENABLE', 'PENDING_ENABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201048, 'DIRECTOR_MASTER', 'EDIT_REJECTED_ENABLE', 'REJECTED', 'PENDING_ENABLE', 'PENDING_ENABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010001, 'DIRECTOR_MASTER', 'CREATE_DIRECTOR_MASTER', 'DRAFT', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010291, 'DIRECTOR_MASTER', 'EDIT_REJECTED_DISABLE', 'PENDING_DISABLE', 'REJECTED', 'PENDING_DISABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010470, 'DIRECTOR_MASTER', 'EDIT_REJECTED_ENABLE_DIRECTOR_MASTER', 'PENDING_ENABLE', 'REJECTED', 'PENDING_ENABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(240820109219, 'DIRECTOR_MASTER', 'CHECKER_APPROVE_ENABLE', 'PENDING_ENABLE', 'ENABLE', 'ENABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(240820109220, 'DIRECTOR_MASTER', 'APPROVE_DIRECTOR_MASTER', 'PENDING_ENABLE', 'ENABLE', 'ENABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201000102, 'DIRECTOR_MASTER', 'SAVE_UPDATE_DIRECTOR_MASTER', 'ENABLE', 'DRAFT', 'DRAFT', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201009212, 'DIRECTOR_MASTER', 'ENABLE_DIRECTOR_MASTER', 'DISABLE', 'PENDING_ENABLE', 'PENDING_ENABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201009213, 'DIRECTOR_MASTER', 'ENABLE_DIRECTOR_MASTER', 'PENDING_ENABLE', 'ENABLE', 'ACTIVE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201009214, 'DIRECTOR_MASTER', 'REJECT_DIRECTOR_MASTER', 'PENDING_ENABLE', 'REJECTED', 'REJECTED', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201009215, 'DIRECTOR_MASTER', 'CHECKER_APPROVE_ENABLE', 'PENDING_ENABLE', 'ENABLE', 'ENABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201009216, 'DIRECTOR_MASTER', 'APPROVE_DIRECTOR_MASTER', 'PENDING_ENABLE', 'ENABLE', 'ENABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201009217, 'DIRECTOR_MASTER', 'CHECKER_APPROVE_UPDATE', 'PENDING_ENABLE', 'ENABLE', 'ENABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201009218, 'DIRECTOR_MASTER', 'CLOSE_REJECTED_ENABLE_DIRECTOR_MASTER', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201009220, 'DIRECTOR_MASTER', 'ENABLE_DIRECTOR_MASTER', 'CLOSED', 'PENDING_ENABLE', 'PENDING_ENABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201009221, 'DIRECTOR_MASTER', 'APPROVE_ENABLE_DIRECTOR_MASTER', 'PENDING_ENABLE', 'ENABLE', 'ACTIVE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201009230, 'DIRECTOR_MASTER', 'APPROVE_DIRECTOR_MASTER', 'PENDING_DISABLE', 'PENDING_DISABLE', 'DISABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(2408201009314, 'DIRECTOR_MASTER', 'CLOSE_DRAFT_DIRECTOR_MASTER', 'DRAFT', 'CLOSED', 'CLOSED', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24052010009320, 'DIRECTOR_MASTER', 'CLOSE_REJECTED_DISABLE_DIRECTOR_MASTER', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010003105, 'DIRECTOR_MASTER', 'ACTION_MAKER_UPDATE', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010003106, 'DIRECTOR_MASTER', 'MAKER_UPDATE_SAVE', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010003109, 'DIRECTOR_MASTER', 'ACTION_MAKER_CLOSE_DRAFT', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010003130, 'DIRECTOR_MASTER', 'CLOSE_REJECTED_UPDATE_DIRECTOR_MASTER', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010003131, 'DIRECTOR_MASTER', 'ACTION_MAKER_SUBMIT', 'DRAFT', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010003134, 'DIRECTOR_MASTER', 'UPDATE_DIRECTOR_MASTER', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010003135, 'DIRECTOR_MASTER', 'MAKER_UPDATE_CLOSE', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010003136, 'DIRECTOR_MASTER', 'MAKER_UPDATE_SAVE', 'REJECTED ', 'DRAFT', 'REJECTED', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010003137, 'DIRECTOR_MASTER', 'SAVE_DIRECTOR_MASTER', 'PENDING_PERFECTION', 'DRAFT', 'DRAFT', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010003138, 'DIRECTOR_MASTER', 'DISABLE_DIRECTOR_MASTER', 'ENABLE', 'PENDING_DISABLE', 'PENDING_DISABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010003141, 'DIRECTOR_MASTER', 'SAVE_DIRECTOR_MASTER', 'ND', 'DRAFT', 'DRAFT', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010003321, 'DIRECTOR_MASTER', 'MAKER_SAVE', 'PENDING_PERFECTION', 'DRAFT', 'DRAFT', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010009213, 'DIRECTOR_MASTER', 'ACTION_MAKER_ENABLE', 'PENDING_DISABLE', 'DISABLE', 'DISABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010009313, 'DIRECTOR_MASTER', 'ACTION_MAKER_ENABLE', 'DISABLE', 'PENDING_ENABLE', 'PENDING_ENABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010009315, 'DIRECTOR_MASTER', 'EDIT_REJECTED_CREATE_DIRECTOR_MASTER', 'DRAFT', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010009316, 'DIRECTOR_MASTER', 'SAVE_UPDATE_DIRECTOR_MASTER', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010009317, 'DIRECTOR_MASTER', 'SAVE_UPDATE_DIRECTOR_MASTER', 'CLOSED', 'DRAFT', 'DRAFT', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010009318, 'DIRECTOR_MASTER', 'UPDATE_DIRECTOR_MASTER', 'ENABLE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010009319, 'DIRECTOR_MASTER', 'ENABLE_DIRECTOR_MASTER', 'REJECTED', 'PENDING_ENABLE', 'PENDING_ENABLE', '1', '1');
INSERT INTO TR_STATE_MATRIX(STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(24082010009320, 'DIRECTOR_MASTER', 'ENABLE_DIRECTOR_MASTER', 'ACTIVE', 'PENDING_ENABLE', 'PENDING_ENABLE', '1', '1');
----------------------------------------------
--- Director Master State Matrix Action
----------------------------------------------
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (2408201013,	7,	'Process',	'directorMaster.do?event=checker_process_disable&TrxId=',null);
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (24082010003324,	6,'Process','directorMaster.do?event=maker_draft_close_process&TrxId=' null);
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (2408201001,	6,'Process','directorMaster.do?event=maker_prepare_resubmit&TrxId=','directorMaster.do?event=to_track&TrxId=');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (2408201002,	7,'Process','directorMaster.do?event=checker_process_create&TrxId=',null);
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (2408201006,	7,'Process','directorMaster.do?event=checker_process_edit&TrxId=','directorMaster.do?event=to_track&TrxId=');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (2408201007,	6,'Process','directorMaster.do?event=maker_prepare_resubmit_create&TrxId=',null);
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (2408201016,	7,'Process','directorMaster.do?event=checker_process_edit&TrxId=','directorMaster.do?event=to_track&TrxId=');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (2408201009213,7,'Process','directorMaster.do?event=checker_process_enable&TrxId=',null);
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (2408201021,6,'Process','directorMaster.do?event=maker_save_process&TrxId=',null);
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (24082010001,6,'Process','directorMaster.do?event=maker_create_save_process&TrxId=',null);	
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (24082010003134,	6,'Process','directorMaster.do?event=maker_update_save_process&TrxId=',null);
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (24082010003135,	6,'Close','directorMaster.do?event=maker_draft_close_process&TrxId=',null);
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (24082010003130,	6,'Close','directorMaster.do?event=maker_prepare_close&TrxId=','directorMaster.do?event=to_track&TrxId=');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (24082010002,6,'Process','directorMaster.do?event=maker_save_process&TrxId=',null);
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (2408201026,6,'Process','directorMaster.do?event=maker_prepare_resubmit_disable&TrxId=',null);
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (2408201047,6,'Process','directorMaster.do?event=maker_prepare_resubmit_enable&TrxId=',null);

------------------------------------------------------
---- Director Master Maintain Function Access
------------------------------------------------------

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(9999999061,'directorMaster','checker_process_create',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(9999999062,'directorMaster','checker_process_create',7);


INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010001,'directorMaster','maker_submit_create_director_master',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(99999901,'directorMaster','maker_list_director_master_page',6);


INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(99999902,'directorMaster','maker_list_directorMaster',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999903,'directorMaster','maker_prepare_create_directorMaster',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999904,'directorMaster','maker_create_directorMaster',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(99999990121,'directorMaster','maker_update_draft_directorMaster',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999905,'directorMaster','rejected_delete_read',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999906,'directorMaster','rejected_delete_read',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999920,'directorMaster','maker_update_save_process',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999922,'directorMaster','get_list_directorMaster_page',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999924,'directorMaster','maker_view_delete_page',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(9999999925,'directorMaster','checker_view_delete_page',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999926,'directorMaster','maker_view_todo_page',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999927,'directorMaster','maker_prepare_resubmit',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999928,'directorMaster','maker_prepare_close',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999929,'directorMaster','maker_confirm_close',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999930,'directorMaster','work_in_process_page',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999931,'directorMaster','common_submit_page',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999932,'directorMaster','common_close_page',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999933,'directorMaster','common_approve_page',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999934,'directorMaster','checker_reject_edit',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999935,'directorMaster','common_reject_page',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(9999999936,'directorMaster','checker_directorMaster_page',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999937,'directorMaster','rejected_read_page',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999938,'directorMaster','prepare_create_directorMaster',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999939,'directorMaster','redirect_list_directorMaster',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999940,'directorMaster','maker_list_directorMaster',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999941,'directorMaster','checker_approve_edit',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999942,'directorMaster','checker_reject_edit',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999943,'directorMaster','checker_list_directorMaster',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999944,'directorMaster','work_in_process_page',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999946,'directorMaster','maker_list_directorMaster_page',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999947,'directorMaster','maker_update_save',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999948,'directorMaster','checker_directorMaster_page',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(9999999048,'directorMaster','redirect_list_directorMaster',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999950,'directorMaster','checker_directorMaster_page',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010002,'directorMaster','prepare_create_director_master',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010003,'directorMaster','prepare_maker_submit_edit',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(9999999051,'directorMaster','maker_view_directorMaster',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(9999999052,'directorMaster','maker_edit_directorMaster_read',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(9999999053,'directorMaster','maker_delete_directorMaster_read',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(9999999055,'directorMaster','maker_edit_directorMaster',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(9999999056,'directorMaster','maker_confirm_resubmit_create',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010004,'directorMaster','prepare_maker_submit_remove',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(9999999057,'directorMaster','maker_prepare_resubmit_create',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010005,'directorMaster','view_director_master_by_index',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(9999999058,'directorMaster','maker_prepare_resubmit_create',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(9999999059,'directorMaster','to_track',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(9999999060,'directorMaster','event=rejected_delete_read',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010006,'directorMaster','checker_approve_edit',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010007,'directorMaster','checker_edit_read',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010008,'directorMaster','checker_process_create',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010009,'directorMaster','checker_process_delete',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010010,'directorMaster','checker_process_edit',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010011,'directorMaster','checker_reject_edit',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010012,'directorMaster','maker_confirm_close',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010013,'directorMaster','maker_confirm_resubmit_edit',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010014,'directorMaster','maker_edit_directorMaster',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010015,'directorMaster','maker_prepare_close',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010016,'directorMaster','maker_prepare_close',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010017,'directorMaster','maker_prepare_resubmit',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010018,'directorMaster','maker_prepare_resubmit_create',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010019,'directorMaster','maker_submit_edit',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010020,'directorMaster','maker_submit_remove',6);


INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(VALUES(24082010021,'directorMaster','rejected_delete_read',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010022,'directorMaster','rejected_delete_read',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010023,'directorMaster','rejected_read',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010024,'directorMaster','search_director_master',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010025,'directorMaster','view_director_master',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(9999999071,'directorMaster','checker_process_create',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(9999999091,'directorMaster','checker_process_create',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(9999999081,'directorMaster','maker_delete_directorMaster',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(99999999091,'directorMaster','maker_disable_directorMaster_read',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(240820100091,'directorMaster','checker_process_disable',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(240820100212,'directorMaster','rejected_disable_read',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(240820100213,'directorMaster','rejected_disable_read',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(9999999093,'directorMaster','maker_disable_directorMaster',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(9999999094,'directorMaster','maker_confirm_resubmit_disable',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999990101,'directorMaster','maker_search_list_directorMaster',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(999999990102,'directorMaster','checker_search_list_directorMaster',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(99999990104,'directorMaster','maker_search_list_directorMaster',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(99999990110,'directorMaster','maker_enable_directorMaster_read',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010071,'directorMaster','checker_process_enable',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010072,'directorMaster','rejected_enable_read',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(24082010073,'directorMaster','rejected_enable_read',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(99999990105,'directorMaster','maker_enable_directorMaster',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(99999990106,'directorMaster','save',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(99999990107,'directorMaster','maker_draft_directorMaster',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(99999990108,'directorMaster','maker_update_draft_directorMaster',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(99999990109,'directorMaster','maker_draft_close_process',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(99999990111,'directorMaster','maker_update_save_process',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(99999990112,'directorMaster','maker_draft_close_process',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(99999990113,'directorMaster','maker_update_save_process',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(99999990114,'directorMaster','maker_confirm_draft_close',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(99999990115,'directorMaster','maker_save_update',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(99999990116,'directorMaster','maker_save_create',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(99999990123,'directorMaster','maker_draft__directorMaster',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(240820109998,'directorMaster','checker_reject_disable',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
VALUES(240820109999,'directorMaster','checker_reject_enable',7);	
	
