@echo off

call .\setenv.cmd

echo -------------------------------------
echo %date% - %time% Connect to database ...

db2 connect to %DB_NAME% user %DB_USER% using %DB_PASSWD%
db2 set current schema = %DB_SCHEMA%
db2 SET CURRENT PATH = SYSIBM,SYSFUN,SYSPROC,SYSIBMADM,%DB_SCHEMA%

echo -------------------------------------
echo %date% - %time% Start validation and migration scripts ...

echo %date% - %time% Validate: Customer Information ...
db2 CALL MIG_VALIDATE_CU001_CU
echo %date% - %time% Migrate: Customer Information ...
db2 CALL MIG_RUN_CU001_CU

echo %date% - %time% Validate: Credit Application Information ...
db2 CALL MIG_VALIDATE_CA001_AA
echo %date% - %time% Migrate: Credit Application Information ...
db2 CALL MIG_RUN_CA001_AA

echo %date% - %time% Validate: Credit CA - Joint Borrowers Info ...
db2 CALL MIG_VALIDATE_CA002_JB
echo %date% - %time% Migrate: Credit CA - Joint Borrowers Info ...
db2 CALL MIG_RUN_CA002_JB

echo %date% - %time% Validate: Credit Facility Master ...
db2 CALL MIG_VALIDATE_CA003_1
echo %date% - %time% Migrate: Credit Facility Master ...
db2 CALL MIG_RUN_CA003_1

echo %date% - %time% Validate: Credit Facility BNM ...
db2 CALL MIG_VALIDATE_CA003_2_BNM
echo %date% - %time% Migrate: Credit Facility BNM ...
db2 CALL MIG_RUN_CA003_2_BNM

echo %date% - %time% Validate: Credit Facility Officer ...
db2 CALL MIG_VALIDATE_CA003_3_OFF
echo %date% - %time% Migrate: Credit Facility Officer ...
db2 CALL MIG_RUN_CA003_3_OFF

echo %date% - %time% Validate: Credit Facility Relationship ...
db2 CALL MIG_VALIDATE_CA003_4_REL
echo %date% - %time% Migrate: Credit Facility Relationship ...
db2 CALL MIG_RUN_CA003_4_REL

echo %date% - %time% Validate: Credit Facility Insurance ...
db2 CALL MIG_VALIDATE_CA003_5_INS
echo %date% - %time% Migrate: Credit Facility Insurance ...
db2 CALL MIG_RUN_CA003_5_INS

echo %date% - %time% Validate: Credit Facility Multi Tier Financing ...
db2 CALL MIG_VALIDATE_CA003_6_MUL
echo %date% - %time% Migrate: Credit Facility Multi Tier Financing ...
db2 CALL MIG_RUN_CA003_6_MUL

echo %date% - %time% Validate: Credit Facility Islamic Master ...
db2 CALL MIG_VALIDATE_CA003_7_ISL
echo %date% - %time% Migrate: Credit Facility Islamic Master ...
db2 CALL MIG_RUN_CA003_7_ISL

echo %date% - %time% Validate: Credit Facility BBA Vari Package ...
db2 CALL MIG_VALIDATE_CA003_8_BBA
echo %date% - %time% Migrate: Credit Facility BBA Vari Package ...
db2 CALL MIG_RUN_CA003_8_BBA

echo %date% - %time% Validate: CA - Limit Account Info ...
db2 CALL MIG_VALIDATE_CA004
echo %date% - %time% Migrate: CA - Limit Account Info ...
db2 CALL MIG_RUN_CA004

echo %date% - %time% Migrate: Create transaction ...
db2 CALL AUTO_CREATE_TRANSACTION

echo -------------------------------------

echo %date% - %time% Validate: Collateral Asset Based - Vehicle, Plant & Equipment ...
db2 CALL MIG_VALIDATE_CO001_AB
echo %date% - %time% Migrate: Collateral Asset Based - Vehicle, Plant & Equipment ...
db2 CALL MIG_RUN_CO001_AB

echo %date% - %time% Validate: Collateral Asset Based - Gold ...
db2 CALL MIG_VALIDATE_CO002_AB_GOLD
echo %date% - %time% Migrate: Collateral Asset Based - Gold ...
db2 CALL MIG_RUN_CO002_AB_GOLD

echo %date% - %time% Validate: Collateral Deposit ...
db2 CALL MIG_VALIDATE_CO005_CS
echo %date% - %time% Migrate: Collateral Deposit ...
db2 CALL MIG_RUN_CO005_CS

echo %date% - %time% Validate: Collateral - Marketable Security - Stocks ...
db2 CALL MIG_VALIDATE_CO008_MS
echo %date% - %time% Migrate: Collateral - Marketable Security - Stocks ...
db2 CALL MIG_RUN_CO008_MS

echo %date% - %time% Validate: Collateral Property ...
db2 CALL MIG_VALIDATE_CO009_PT
echo %date% - %time% Migrate: Collateral Property ...
db2 CALL MIG_RUN_CO009_PT

echo %date% - %time% Validate: Collateral Guarantees ...
db2 CALL MIG_VALIDATE_CO010_GT
echo %date% - %time% Migrate: Collateral Guarantees ...
db2 CALL MIG_RUN_CO010_GT

echo %date% - %time% Validate: Collateral Others ...
db2 CALL MIG_VALIDATE_CO011_OT
echo %date% - %time% Migrate: Collateral Others ...
db2 CALL MIG_RUN_CO011_OT

echo %date% - %time% Validate: Collateral Insurance Protection ...
db2 CALL MIG_VALIDATE_CO012_IN
echo %date% - %time% Migrate: Collateral Insurance Protection ...
db2 CALL MIG_RUN_CO012_IN

echo %date% - %time% Validate: Collateral Clean ...
db2 CALL MIG_VALIDATE_CO014_CL
echo %date% - %time% Migrate: Collateral Clean ...
db2 CALL MIG_RUN_CO014_CL

echo %date% - %time% Migrate: Create transaction ...
db2 CALL AUTO_CREATE_TRANSACTION

echo -------------------------------------

echo %date% - %time% Validate: Collateral Pledge Information ...
db2 CALL MIG_VALIDATE_CO019_PL
echo %date% - %time% Migrate: Collateral Pledge Information ...
db2 CALL MIG_RUN_CO019_PL

echo %date% - %time% Validate: Collateral Valuation Detail ...
db2 CALL MIG_VALIDATE_CO015_VL
echo %date% - %time% Migrate: Collateral Valuation Detail ...
db2 CALL MIG_RUN_CO015_VL

echo %date% - %time% Validate: Collateral Insurance Policy Detail ...
db2 CALL MIG_VALIDATE_CO016_IN
echo %date% - %time% Migrate: Collateral Insurance Policy Detail ...
db2 CALL MIG_RUN_CO016_IN

echo %date% - %time% Validate: Collateral Charge Detail ...
db2 CALL MIG_VALIDATE_CO017_CD
echo %date% - %time% Migrate: Collateral Charge Detail ...
db2 CALL MIG_RUN_CO017_CD

echo %date% - %time% Validate: Collateral Pledgor Detail ...
db2 CALL MIG_VALIDATE_CO018_PG
echo %date% - %time% Migrate: Collateral Pledgor Detail ...
db2 CALL MIG_RUN_CO018_PG


echo -------------------------------------
echo %date% - %time% Script end.