-----------------------------
-- Cleanup
-----------------------------
DELETE FROM MIG_QC_REPORT;

-----------------------------
-- Standalone Facilities
-----------------------------
-- CA003
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrLMT', 'QC Report 3c for Migration', 'ARBS', 'CA003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrLMT', 'Report for migration template: CA003', 'ARBS', 'CA003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrLMT', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CA003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrLMT', 'Source Facility ID,CIF/AA Number,Remarks', 'ARBS', 'CA003');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrLMT', '''' || COALESCE(KEY3_VALUE,'-') || ',''' || CASE WHEN ERROR_MSG LIKE '%customer%' THEN KEY1_VALUE WHEN ERROR_MSG LIKE '%AA%' THEN KEY2_VALUE END || ',' || ERROR_MSG, 'ARBS', 'CA003' FROM SI_ERROR_LOG
		WHERE ERROR_CODE = 'BizErr003' AND SYSTEM_ID = 'ARBS' AND INTERFACE_ID = 'CA003');

-- CA012
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrLMT', 'QC Report 3c for Migration', 'SEMA', 'CA012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrLMT', 'Report for migration template: CA012', 'SEMA', 'CA012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrLMT', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SEMA', 'CA012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrLMT', 'Source Facility ID,CIF/AA Number,Remarks', 'SEMA', 'CA012');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrLMT', '''' || COALESCE(KEY2_VALUE,'-') || ',''' || KEY1_VALUE || ',' || ERROR_MSG, 'SEMA', 'CA012' FROM SI_ERROR_LOG
		WHERE ERROR_CODE = 'BizErr003' AND SYSTEM_ID = 'SEMA' AND INTERFACE_ID = 'CA012');

-- CA015
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrLMT', 'QC Report 3c for Migration', 'BOST', 'CA015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrLMT', 'Report for migration template: CA015', 'BOST', 'CA015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrLMT', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'CA015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrLMT', 'Source Facility ID,CIF/AA Number,Remarks', 'BOST', 'CA015');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrLMT', '''' || COALESCE(KEY2_VALUE,'-') || ',''' || KEY1_VALUE || ',' || ERROR_MSG, 'BOST', 'CA015' FROM SI_ERROR_LOG
		WHERE ERROR_CODE = 'BizErr003' AND SYSTEM_ID = 'BOST' AND INTERFACE_ID = 'CA015');

-- CA017
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrLMT', 'QC Report 3c for Migration', 'FINS', 'CA017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrLMT', 'Report for migration template: CA017', 'FINS', 'CA017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrLMT', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CA017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrLMT', 'Source Facility ID,CIF/AA Number,Remarks', 'FINS', 'CA017');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrLMT', '''' || COALESCE(KEY2_VALUE,'-') || ',''' || KEY1_VALUE || ',' || ERROR_MSG, 'FINS', 'CA017' FROM SI_ERROR_LOG
		WHERE ERROR_CODE = 'BizErr003' AND SYSTEM_ID = 'FINS' AND INTERFACE_ID = 'CA017');

-- CA018
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrLMT', 'QC Report 3c for Migration', 'FINS', 'CA018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrLMT', 'Report for migration template: CA018', 'FINS', 'CA018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrLMT', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CA018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrLMT', 'Source Facility ID,CIF/AA Number,Remarks', 'FINS', 'CA018');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrLMT', '''' || COALESCE(KEY2_VALUE,'-') || ',''' || KEY1_VALUE || ',' || ERROR_MSG, 'FINS', 'CA018' FROM SI_ERROR_LOG
		WHERE ERROR_CODE = 'BizErr003' AND SYSTEM_ID = 'FINS' AND INTERFACE_ID = 'CA018');
		
COMMIT;


