---------------------------------------
----  Valuation Agency TO Track
---------------------------------------
Insert into CMS_TRX_TOTRACK  (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE)
 Values ('VALUATION_AGENCY', 'ValuationAgency.do?event=rejected_delete_read&toTrack=yes&TrxId=', 'REJECTED', 'Rejected', 'Valuation Agency',NULL, NULL);

 Insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE,FROM_STATE, TRANSACTION_SUBTYPE)
 Values('VALUATION_AGENCY', 'ValuationAgency.do?event=rejected_delete_read&toTrack=yes&TrxId=', 'PENDING_DELETE', 'Pending Delete', 'Valuation Agency',NULL, NULL);

 Insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE,FROM_STATE, TRANSACTION_SUBTYPE)
 Values('VALUATION_AGENCY', 'ValuationAgency.do?event=rejected_delete_read&toTrack=yes&TrxId=', 'ENABLE', 'enable', 'Valuation Agency',NULL, NULL);
Insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE)
 Values ('VALUATION_AGENCY', 'ValuationAgency.do?event=rejected_delete_read&toTrack=yes&TrxId=', 'ACTIVE', 'Approved', 'Valuation Agency',NULL, NULL);
Insert into CMS_TRX_TOTRACK(TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE,FROM_STATE, TRANSACTION_SUBTYPE)
 Values ('VALUATION_AGENCY', 'ValuationAgency.do?event=rejected_delete_read&toTrack=yes&TrxId=', 'PENDING_ENABLE', 'Pending Enable', 'Valuation Agency',NULL, NULL);
Insert into CMS_TRX_TOTRACKTRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE)
 Values ('VALUATION_AGENCY', 'ValuationAgency.do?event=rejected_delete_read&toTrack=yes&TrxId=', 'DRAFT', 'Draft', 'Valuation Agency',NULL, NULL);
Insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE,FROM_STATE, TRANSACTION_SUBTYPE)
 Values('VALUATION_AGENCY', 'ValuationAgency.do?event=rejected_delete_read&toTrack=yes&TrxId=', 'PENDING_DISABLE', 'Pending Disable', 'Valuation Agency',NULL, NULL);
Insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE,FROM_STATE, TRANSACTION_SUBTYPE)
 Values('VALUATION_AGENCY', 'ValuationAgency.do?event=rejected_delete_read&toTrack=yes&TrxId=', 'PENDING_UPDATE', 'Pending Update', 'Valuation Agency', NULL, NULL);
Insert into CMS_TRX_TOTRACK(TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE,FROM_STATE, TRANSACTION_SUBTYPE)
 Values('VALUATION_AGENCY', 'ValuationAgency.do?event=rejected_delete_read&toTrack=yes&TrxId=', 'CLOSED', 'Closed', 'Valuation Agency',NULL, NULL);
Insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE)
Values  ('VALUATION_AGENCY', 'ValuationAgency.do?event=rejected_delete_read&toTrack=yes&TrxId=', 'DELETED', 'Deleted', 'Valuation Agency', NULL, NULL);
Insert into CMS_TRX_TOTRACK   (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE)
 Values ('VALUATION_AGENCY', 'ValuationAgency.do?event=rejected_delete_read&toTrack=yes&TrxId=', 'PENDING_CREATE', 'Pending Create', 'Valuation Agency', NULL, NULL);
Insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE)
 Values ('VALUATION_AGENCY', 'ValuationAgency.do?event=rejected_delete_read&toTrack=yes&TrxId=', 'DISABLE', 'disable', 'Valuation Agency', NULL, NULL);
 
 
 
 
 --------------------------------------------
--- Valuation Agency Tr State Matrix
--------------------------------------------

 
 
 Insert into TR_STATE_MATRIX  (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values (9433350741, 'VALUATION_AGENCY', 'EDIT_REJECTED_ENABLE', 'REJECTED', 'PENDING_ENABLE','PENDING_ENABLE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values(9433350746, 'VALUATION_AGENCY', 'APPROVE_DISABLE_VALUATION_AGENCY', 'PENDING_ENABLE', 'ACTIVE', 'ENABLE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values(9433350747, 'VALUATION_AGENCY', 'EDIT_REJECTED_ENABLE_VALUATION_AGENCY', 'REJECTED', 'PENDING_ENABLE','PENDING_ENABLE', '1', '1');
Insert into TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values (9433350748, 'VALUATION_AGENCY', 'EDIT_REJECTED_ENABLE', 'REJECTED', 'PENDING_ENABLE','PENDING_ENABLE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values (94333507470, 'VALUATION_AGENCY', 'EDIT_REJECTED_ENABLE_VALUATION_AGENCY', 'PENDING_ENABLE', 'REJECTED','PENDING_ENABLE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values (943335079219, 'VALUATION_AGENCY', 'CHECKER_APPROVE_ENABLE', 'PENDING_ENABLE', 'ACTIVE', 'ENABLE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values (943335079220, 'VALUATION_AGENCY', 'APPROVE_VALUATION_AGENCY', 'PENDING_ENABLE', 'ACTIVE', 'ENABLE', '1', '1');
Insert into TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values (9433350700102, 'VALUATION_AGENCY', 'SAVE_UPDATE_VALUATION_AGENCY', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values (9433350709212, 'VALUATION_AGENCY', 'ENABLE_VALUATION_AGENCY', 'DISABLE', 'PENDING_ENABLE','PENDING_ENABLE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values (9433350709213, 'VALUATION_AGENCY', 'ENABLE_VALUATION_AGENCY', 'PENDING_ENABLE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,  USERSTATE, ENABLEIND, FRONTENDOP)
 Values (9433350709214, 'VALUATION_AGENCY', 'REJECT_VALUATION_AGENCY', 'PENDING_ENABLE', 'REJECTED',  'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values(9433350709215, 'VALUATION_AGENCY', 'CHECKER_APPROVE_ENABLE', 'PENDING_ENABLE', 'ACTIVE', 'ENABLE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,USERSTATE, ENABLEIND, FRONTENDOP)
 Values(9433350709216, 'VALUATION_AGENCY', 'APPROVE_VALUATION_AGENCY', 'PENDING_ENABLE', 'ACTIVE', 'ENABLE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values(9433350709217, 'VALUATION_AGENCY', 'CHECKER_APPROVE_UPDATE', 'PENDING_ENABLE', 'ACTIVE', 'ENABLE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values(9433350709218, 'VALUATION_AGENCY', 'CLOSE_REJECTED_ENABLE_VALUATION_AGENCY', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values (9433350709220, 'VALUATION_AGENCY', 'ENABLE_VALUATION_AGENCY', 'CLOSED', 'PENDING_ENABLE','PENDING_ENABLE', '1', '1');
Insert into TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values(9433350709221, 'VALUATION_AGENCY', 'APPROVE_ENABLE_VALUATION_AGENCY', 'PENDING_ENABLE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,USERSTATE, ENABLEIND, FRONTENDOP)
 Values(94333507003138, 'VALUATION_AGENCY', 'DISABLE_VALUATION_AGENCY', 'ACTIVE', 'PENDING_DISABLE','PENDING_DISABLE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values(94333507009213, 'VALUATION_AGENCY', 'ACTION_MAKER_ENABLE', 'PENDING_DISABLE', 'DISABLE','DISABLE', '1', '1');
Insert into TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,USERSTATE, ENABLEIND, FRONTENDOP)
 Values(94333507009313, 'VALUATION_AGENCY', 'ACTION_MAKER_ENABLE', 'DISABLE', 'PENDING_ENABLE','PENDING_ENABLE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values(37538, 'VALUATION_AGENCY', 'CLOSE_REJECTED_UPDATE_VALUATION_AGENCY', 'REJECTED', 'ACTIVE','ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values(94333507009319, 'VALUATION_AGENCY', 'ENABLE_VALUATION_AGENCY', 'REJECTED', 'PENDING_ENABLE',  'PENDING_ENABLE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,  USERSTATE, ENABLEIND, FRONTENDOP)
 Values (94333507009320, 'VALUATION_AGENCY', 'ENABLE_VALUATION_AGENCY', 'ACTIVE', 'PENDING_ENABLE',  'PENDING_ENABLE', '1', '1');
Insert into TR_STATE_MATRIX  (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,  USERSTATE, ENABLEIND, FRONTENDOP)
 Values(9433350713, 'VALUATION_AGENCY', 'DISABLE_VALUATION_AGENCY', 'PENDING_DISABLE', 'DISABLE', 'DISABLE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,  USERSTATE, ENABLEIND, FRONTENDOP)
 Values (9433350714, 'VALUATION_AGENCY', 'REJECT_VALUATION_AGENCY', 'PENDING_DISABLE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,   USERSTATE, ENABLEIND, FRONTENDOP)
 Values (9433350720, 'VALUATION_AGENCY', 'CHECKER_APPROVE_UPDATE', 'DISABLE', 'DISABLE', 'DISABLE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,  USERSTATE, ENABLEIND, FRONTENDOP)
 Values(9433350723, 'VALUATION_AGENCY', 'DISABLE_VALUATION_AGENCY', 'CLOSED', 'PENDING_DISABLE',  'PENDING_DISABLE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,  USERSTATE, ENABLEIND, FRONTENDOP)
 Values(9433350724, 'VALUATION_AGENCY', 'APPROVE_DISABLE_VALUATION_AGENCY', 'PENDING_DISABLE', 'DISABLE', 'DISABLE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values(9433350726, 'VALUATION_AGENCY', 'EDIT_REJECTED_DISABLE_VALUATION_AGENCY', 'REJECTED', 'PENDING_DISABLE','PENDING_DISABLE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
Values (9433350729, 'VALUATION_AGENCY', 'EDIT_REJECTED_DISABLE', 'REJECTED', 'PENDING_DISABLE','PENDING_DISABLE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,  USERSTATE, ENABLEIND, FRONTENDOP)
 Values (9433350731, 'VALUATION_AGENCY', 'CHECKER_APPROVE_UPDATE', 'PENDING_DISABLE', 'DISABLE',  'DISABLE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,  USERSTATE, ENABLEIND, FRONTENDOP)
 Values(9433350732, 'VALUATION_AGENCY', 'APPROVE_VALUATION_AGENCY', 'PENDING_DISABLE', 'DELETED',   'DELETED', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values (9433350736, 'VALUATION_AGENCY', 'DISABLE_VALUATION_AGENCY', 'DISABLE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values(9433350738, 'VALUATION_AGENCY', 'DISABLE_VALUATION_AGENCY', 'REJECTED', 'PENDING_DISABLE',  'PENDING_DISABLE', '1', '1');
Insert into TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values (94333507291, 'VALUATION_AGENCY', 'EDIT_REJECTED_DISABLE', 'PENDING_DISABLE', 'REJECTED','PENDING_DISABLE', '1', '1');
Insert into TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values (9433350709230, 'VALUATION_AGENCY', 'APPROVE_VALUATION_AGENCY', 'PENDING_DISABLE', 'PENDING_DISABLE',  'DISABLE', '1', '1');
Insert into TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values (9433350709219, 'VALUATION_AGENCY', 'CLOSE_REJECTED_DISABLE_VALUATION_AGENCY', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX  (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values (37531, 'VALUATION_AGENCY', 'EDIT_REJECTED_DELETE_VALUATION_AGENCY', 'REJECTED', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
Insert into TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,  USERSTATE, ENABLEIND, FRONTENDOP)
 Values (37532, 'VALUATION_AGENCY', 'CREATE_VALUATION_AGENCY', 'PENDING_CREATE', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,  USERSTATE, ENABLEIND, FRONTENDOP)
 Values (37533, 'VALUATION_AGENCY', 'APPROVE_VALUATION_AGENCY', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,  USERSTATE, ENABLEIND, FRONTENDOP)
 Values (37534, 'VALUATION_AGENCY', 'UPDATE_VALUATION_AGENCY', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values(37535, 'VALUATION_AGENCY', 'APPROVE_CREATE_VALUATION_AGENCY', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,  USERSTATE, ENABLEIND, FRONTENDOP)
 Values (37536, 'VALUATION_AGENCY', 'REJECT_VALUATION_AGENCY', 'PENDING_UPDATE', 'REJECTED','REJECTED', '1', '1');
Insert into TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values(37537, 'VALUATION_AGENCY', 'EDIT_REJECTED_UPDATE_VALUATION_AGENCY', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values(37539, 'VALUATION_AGENCY', 'REJECT_VALUATION_AGENCY', 'PENDING_CREATE', 'REJECTED','REJECTED', '1', '1');
Insert into TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,USERSTATE, ENABLEIND, FRONTENDOP)
 Values(37540, 'VALUATION_AGENCY', 'CLOSE_REJECTED_CREATE_VALUATION_AGENCY', 'REJECTED', 'ACTIVE','ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values(37541, 'VALUATION_AGENCY', 'EDIT_REJECTED_CREATE_VALUATION_AGENCY', 'REJECTED', 'PENDING_CREATE','PENDING_CREATE', '1', '1');
Insert into TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values (37542, 'VALUATION_AGENCY', 'DELETE_VALUATION_AGENCY', 'ACTIVE', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values (37543, 'VALUATION_AGENCY', 'DELETE_VALUATION_AGENCY', 'PENDING_DELETE', 'DELETED','DELETED', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values (37544, 'VALUATION_AGENCY', 'REJECT_VALUATION_AGENCY', 'PENDING_DELETE', 'REJECTED', 'REJECTED', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values(37545, 'VALUATION_AGENCY', 'CLOSE_REJECTED_DELETE_VALUATION_AGENCY', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,  USERSTATE, ENABLEIND, FRONTENDOP)
 Values(37546, 'VALUATION_AGENCY', 'UPDATE_VALUATION_AGENCY', 'PENDING_UPDATE', 'ACTIVE','PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values(37547, 'VALUATION_AGENCY', 'CHECKER_APPROVE_UPDATE', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,  USERSTATE, ENABLEIND, FRONTENDOP)
 Values(37548, 'VALUATION_AGENCY', 'APPROVE_DELETE_VALUATION_AGENCY', 'PENDING_DELETE', 'DELETED', 'DELETED', '1', '1');
Insert into TR_STATE_MATRIX(STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,  USERSTATE, ENABLEIND, FRONTENDOP)
 Values (37549, 'VALUATION_AGENCY', 'APPROVE_VALUATION_AGENCY', 'PENDING_DELETE', 'DELETED',   'DELETED', '1', '1');
Insert into TR_STATE_MATRIX  (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,   USERSTATE, ENABLEIND, FRONTENDOP)
 Values  (37550, 'VALUATION_AGENCY', 'CHECKER_APPROVE_UPDATE', 'PENDING_DELETE', 'DELETED',  'DELETED', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,   USERSTATE, ENABLEIND, FRONTENDOP)
 Values  (37565, 'VALUATION_AGENCY', 'CREATE_VALUATION_AGENCY', 'ND', 'PENDING_CREATE',  'PENDING_CREATE', '1', '1');
Insert into TR_STATE_MATRIX  (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,  USERSTATE, ENABLEIND, FRONTENDOP)
 Values (38021, 'VALUATION_AGENCY', 'MAKER_SAVE', 'PENDING_PERFECTION', 'DRAFT', 'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values (38020, 'VALUATION_AGENCY', 'CREATE_VALUATION_AGENCY', 'DRAFT', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values(38022, 'VALUATION_AGENCY', 'MAKER_UPDATE_SAVE', 'ACTIVE', 'DRAFT',  'DRAFT', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values  (38023, 'VALUATION_AGENCY', 'UPDATE_VALUATION_AGENCY', 'DRAFT', 'PENDING_UPDATE',   'PENDING_UPDATE', '1', '1');
Insert into TR_STATE_MATRIX  (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,  USERSTATE, ENABLEIND, FRONTENDOP)
 Values (38024, 'VALUATION_AGENCY', 'MAKER_UPDATE_CLOSE', 'DRAFT', 'ACTIVE',  'ACTIVE', '1', '1');
Insert into TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE,  USERSTATE, ENABLEIND, FRONTENDOP)
 Values  (38025, 'VALUATION_AGENCY', 'ACTIVATE_VALUATION_AGENCY', 'DELETED', 'PENDING_ENABLE',    'PENDING_ENABLE', '1', '1');


 
 
 ----------------------------------------------
---Valuation Agency State Matrix Action
----------------------------------------------

 
 Insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
 Values  (9433350713, 7, 'Process', 'ValuationAgency.do?event=checker_process_disable&TrxId=', NULL);
Insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
 Values  (9433350726, 6, 'Process', 'ValuationAgency.do?event=maker_prepare_resubmit_disable&TrxId=', NULL);
Insert into CMS_STATEMATRIX_ACTION  (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
 Values  (9433350709213, 7, 'Process', 'ValuationAgency.do?event=checker_process_enable&TrxId=', NULL);
Insert into CMS_STATEMATRIX_ACTION  (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
 Values  (9433350747, 6, 'Process', 'ValuationAgency.do?event=maker_prepare_resubmit_enable&TrxId=', NULL);
Insert into CMS_STATEMATRIX_ACTION  (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
 Values (37543, 7, 'Process', 'ValuationAgency.do?event=checker_process_delete&TrxId=', NULL);
Insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
 Values  (37532, 7, 'Process', 'ValuationAgency.do?event=checker_process_create&TrxId=', NULL);
Insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
 Values (37546, 7, 'Process', 'ValuationAgency.do?event=checker_process_edit&TrxId=', NULL);
Insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
 Values (37536, 7, 'Process', 'ValuationAgency.do?event=checker_process_edit&TrxId=', 'ValuationAgency.do?event=to_track&TrxId=');
Insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
 Values (37537, 6, 'Process', 'ValuationAgency.do?event=maker_prepare_resubmit_create&TrxId=', 'ValuationAgency.do?event=to_track&TrxId=');
Insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
 Values (37538, 6, 'Close', 'ValuationAgency.do?event=maker_prepare_close&TrxId=', 'ValuationAgency.do?event=to_track&TrxId=');
Insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
 Values (37541, 6, 'Process', 'ValuationAgency.do?event=maker_prepare_resubmit_create&TrxId=', NULL);
Insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
 Values (37531, 6, 'Process', 'ValuationAgency.do?event=maker_prepare_resubmit_delete&TrxId=', NULL);
Insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
 Values (38021, 6, 'Process', 'ValuationAgency.do?event=maker_save_process&TrxId=', NULL);
Insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
 Values (38020, 6, 'Process', 'ValuationAgency.do?event=maker_save_process&TrxId=', NULL);
Insert into CMS_STATEMATRIX_ACTION(STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
 Values (38023, 6, 'Process', 'ValuationAgency.do?event=maker_update_save_process&TrxId=', NULL);
Insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
 Values  (38024, 6, 'Close', 'ValuationAgency.do?event=maker_draft_close_process&TrxId=', ' ');

 
 
 
 ------------------------------------------------------
---- Valuation Agency Maintain Function Access
------------------------------------------------------

 
 Insert into CMS_FUNCTION_ACCESS  (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999221, 'ValuationAgency', 'maker_list_valuation', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999222, 'ValuationAgency', 'maker_create_valuation_agency', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999223, 'ValuationAgency', 'maker_submit_valuationAgency', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999263, 'ValuationAgency', 'refresh_city_id', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999264, 'ValuationAgency', 'refresh_state_id', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999262, 'ValuationAgency', 'refresh_region_id', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999224, 'ValuationAgency', 'rejected_delete_read', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999225, 'ValuationAgency', 'checker_process_create', 7);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999226, 'ValuationAgency', 'checker_approve_edit', 7);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999227, 'ValuationAgency', 'checker_reject_edit', 7);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999228, 'ValuationAgency', 'maker_prepare_close', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999229, 'ValuationAgency', 'maker_confirm_close', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999230, 'ValuationAgency', 'maker_prepare_resubmit_create', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999231, 'ValuationAgency', 'maker_confirm_resubmit_edit', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999232, 'ValuationAgency', 'rejected_delete_read', 7);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999233, 'ValuationAgency', 'maker_view_valuationAgency', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999234, 'ValuationAgency', 'maker_edit_valuationAgency_read', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999235, 'ValuationAgency', 'maker_edit_valuationAgency', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999236, 'ValuationAgency', 'checker_process_edit', 7);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999244, 'ValuationAgency', 'maker_enable_valuationAgency_read', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999245, 'ValuationAgency', 'checker_process_enable', 7);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999246, 'ValuationAgency', 'rejected_enable_read', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999247, 'ValuationAgency', 'rejected_enable_read', 7);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999248, 'ValuationAgency', 'maker_enable_valuationAgency', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999249, 'ValuationAgency', 'checker_reject_enable', 7);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999237, 'ValuationAgency', 'maker_disable_valuationAgency_read', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999238, 'ValuationAgency', 'checker_process_disable', 7);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999239, 'ValuationAgency', 'rejected_disable_read', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999240, 'ValuationAgency', 'rejected_disable_read', 7);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999241, 'ValuationAgency', 'maker_disable_valuationAgency', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999242, 'ValuationAgency', 'maker_confirm_resubmit_disable', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999243, 'ValuationAgency', 'checker_reject_disable', 7);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999250, 'ValuationAgency', 'maker_prepare_resubmit_enable', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999251, 'ValuationAgency', 'maker_confirm_resubmit_enable', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999252, 'ValuationAgency', 'maker_cancel_valuationAgency', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999253, 'ValuationAgency', 'maker_draft_valuationAgency', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999254, 'ValuationAgency', 'maker_draft_close_process', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999255, 'ValuationAgency', 'maker_update_save_process', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999256, 'ValuationAgency', 'maker_confirm_draft_close', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999257, 'ValuationAgency', 'maker_save_create', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999258, 'ValuationAgency', 'maker_update_draft_valuationAgency', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999259, 'ValuationAgency', 'maker_save_update', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999261, 'ValuationAgency', 'list_pagination', 6);
Insert into CMS_FUNCTION_ACCESS   (ID, ACTION, EVENT, ROLE_TYPE)
 Values   (999999999260, 'ValuationAgency', 'maker_prepare_resubmit_delete', 6);


 
 
 
 