--DROP TABLE SI_TEMP_SEMA_CU004;
--DROP TABLE SI_TEMP_SEMA_CU002;
--DROP TABLE SI_TEMP_SEMA_CA001;
--DROP TABLE SI_TEMP_SEMA_CA012;
--DROP TABLE SI_TEMP_SEMA_CO020;
--DROP TABLE SI_SEMA_UPDATE_AA_DATE;

CREATE TABLE SI_TEMP_SEMA_CU004( 
    RECORD_TYPE VARCHAR(1),
    CIF_ID VARCHAR(16),
    CUST_NAME_LONG VARCHAR(50),
	CUST_NAME_SHORT VARCHAR(26),
	CUST_CLASS_CAT VARCHAR(20) DEFAULT '56',
	CUST_CLASS_CODE VARCHAR(1),	
    ID_ISSUE_COUNTRY VARCHAR(2), 
	ID_TYPE_CAT VARCHAR(20) DEFAULT 'ID_TYPE',
    ID_TYPE_CODE VARCHAR(3),    
    ID_NUMBER VARCHAR(40),
	ID_ISSUE_DATE TIMESTAMP,
    SECONDARY_ID_TYPE_CAT VARCHAR(20) DEFAULT 'ID_TYPE',
    SECONDARY_ID_TYPE_CODE VARCHAR(3),    
    SECONDARY_ID_NUMBER VARCHAR(40),
	CUST_TYPE_CAT  VARCHAR(20) DEFAULT '8',
	CUST_TYPE_CODE  VARCHAR(1),
	CUST_START_DATE TIMESTAMP,
    CUST_SEGMENT_CAT VARCHAR(20) DEFAULT '5',
    CUST_SEGMENT_CODE VARCHAR(5) DEFAULT 'CC01',    
    BLACKLISTED CHAR(1),
	INCOME_GROUP_CAT VARCHAR(20) DEFAULT 'INCOME_RANGE',	
	INCOME_GROUP VARCHAR(15),	
	ISIC_CAT VARCHAR(20) DEFAULT '17',
    ISIC_CODE VARCHAR(5),    
	PRIMARY_ADD_TYPE_CAT VARCHAR(20) DEFAULT '4',
    PRIMARY_ADD_TYPE_CODE VARCHAR(1),    
    PRIMARY_ADD_1 VARCHAR(50),
    PRIMARY_ADD_2 VARCHAR(50),
    PRIMARY_ADD_3 VARCHAR(50),
	PRIMARY_ADD_4 VARCHAR(50),
    PRIMARY_POSTCODE VARCHAR(9),    
    SECONDARY_ADD_TYPE_CAT VARCHAR(20) DEFAULT '4',
    SECONDARY_ADD_TYPE_CODE VARCHAR(1),    
    SECONDARY_ADD_1 VARCHAR(50),
    SECONDARY_ADD_2 VARCHAR(50),
    SECONDARY_ADD_3 VARCHAR(50),
	SECONDARY_ADD_4 VARCHAR(50),
    SECONDARY_POSTCODE VARCHAR(9),
	UPDATE_STATUS_IND CHAR(1),
	IS_VALID CHAR(1) DEFAULT 'Y',
	CMS_LE_MAIN_PROFILE_ID BIGINT,
	CMS_LE_SUB_PROFILE_ID BIGINT)
	IN CMS_BATCH INDEX IN CMS_BATCH_INDEX;  
    
CREATE TABLE SI_TEMP_SEMA_CU002(
    RECORD_TYPE VARCHAR(1),
    CIF_ID VARCHAR(19),
    CREDIT_GRADE_TYPE_CAT VARCHAR(20) DEFAULT '18',
    CREDIT_GRADE_TYPE VARCHAR(1),
	CREDIT_GRADE_VALUE_CAT VARCHAR(20) DEFAULT '19',
    CREDIT_GRADE_VALUE VARCHAR(3),
    CREDIT_GRADE_EFFECTIVE_DATE TIMESTAMP,
    UPDATE_STATUS_IND CHAR(1),
	IS_VALID CHAR(1) DEFAULT 'Y',
	CMS_LE_MAIN_PROFILE_ID BIGINT)
	IN CMS_BATCH INDEX IN CMS_BATCH_INDEX;
    
CREATE TABLE SI_TEMP_SEMA_CA001(
    RECORD_TYPE VARCHAR(1),
    CIF_ID VARCHAR(19),
    CIF_SOURCE VARCHAR(4),
    AA_NUMBER VARCHAR(19),
    JOINT_BORROWER_IND VARCHAR(1),
    AA_APPROVED_DATE TIMESTAMP,
    ORI_LOC_COUNTRY VARCHAR(2),
    ORI_LOC_ORG_CAT VARCHAR(20) DEFAULT '40',
    ORI_LOC_ORG_CODE VARCHAR(5),
    ORI_LOC_ORG_DESC VARCHAR(40),
    ANNUAL_REVIEW_DATE TIMESTAMP,
    AA_STAT VARCHAR(20),
    AA_CREATE_DATE TIMESTAMP,
	UPDATE_STATUS_IND CHAR(1),
	IS_VALID CHAR(1) DEFAULT 'Y',
	CMS_CUSTOMER_ID BIGINT,
    CMS_ACT_AA_ID BIGINT,
    CMS_STG_AA_ID BIGINT)
	IN CMS_BATCH INDEX IN CMS_BATCH_INDEX; 

CREATE TABLE SI_TEMP_SEMA_CA012(
    RECORD_TYPE VARCHAR(1),
    CIF_ID VARCHAR(16),
    AA_NUMBER VARCHAR(16),
    LIMIT_ID VARCHAR(16),
    STATUS VARCHAR(1),
	APPROVED_DATE TIMESTAMP DEFAULT,
    OUTER_LIMIT_ID VARCHAR(16),
    ORI_LOC_COUNTRY VARCHAR(2),
    ORI_LOC_ORG_CAT VARCHAR(20) DEFAULT '40',
    ORI_LOC_ORG_CODE VARCHAR(5),    
    PRODUCT_TYPE_CAT VARCHAR(20) DEFAULT '27',
    PRODUCT_TYPE_CODE VARCHAR(3),
    PRODUCT_TYPE_DESC VARCHAR(30),
    LIMIT_CURRENCY VARCHAR(3),
    LIMIT_AMT DECIMAL(17,2),
	INTEREST_MARGIN DECIMAL(10,4),
	INTEREST_MARGIN_BASIS VARCHAR(1),
	DRAWING_LIMIT_AMT DECIMAL(17,2),
	AVAILABLE_LIMIT DECIMAL(20,2),
    OUTSTANDING_AMT DECIMAL(17,2),	
    LOAN_SECTOR_CODE VARCHAR(10) DEFAULT '0420',
    DISBURSED_IND VARCHAR(1) DEFAULT 'F',
    EXTERNAL_SYSTEM_ACCT_NO VARCHAR(19),
    NPL_STAT VARCHAR(1),
    NPL_DATE TIMESTAMP,
	IS_VALID CHAR(1) DEFAULT 'Y',
	IS_OUTER_LMT CHAR(1) DEFAULT 'N',
	--IS_INSERT CHAR(1) DEFAULT 'N',
	CMS_OUTER_LIMIT_ID BIGINT,
	CMS_STG_OUTER_LIMIT_ID BIGINT,
	CMS_LIMIT_PROFILE_ID BIGINT,
	CMS_ACT_LMT_ID BIGINT,
    CMS_STG_LMT_ID BIGINT)
	IN CMS_BATCH INDEX IN CMS_BATCH_INDEX;   

CREATE TABLE SI_TEMP_SEMA_CO020(
    RECORD_TYPE 				VARCHAR(1),
    CIF_ID 						VARCHAR(40),
    FD_RECEIPT_NO 				VARCHAR(19),
    FD_DEPOSIT_AMT_CURR 		VARCHAR(3),
    FD_DEPOSIT_AMT 				DECIMAL(17,2),
    FD_DEPOSIT_MATURITY_DATE 	TIMESTAMP,
    FD_PLEDGED_AMT_CURR 		VARCHAR(3),
    FD_PLEDGED_AMT 				DECIMAL(17,2),
	IS_VALID 					CHAR(1) DEFAULT 'Y',
	SOURCE_SEC_ID 				VARCHAR(60),
	CMS_COLLATERAL_ID			BIGINT,
	CMS_STG_COLLATERAL_ID		BIGINT,
	CMS_ACT_LMT_ID 				BIGINT,
    CMS_STG_LMT_ID 				BIGINT
	)
	IN CMS_BATCH INDEX IN CMS_BATCH_INDEX;
	

CREATE TABLE SI_SEMA_UPDATE_AA_DATE (
	CMS_LIMIT_PROFILE_ID BIGINT,
	CMS_STG_LIMIT_PROFILE_ID BIGINT,
	CREATE_DATE TIMESTAMP)
	IN CMS_BATCH INDEX IN CMS_BATCH_INDEX;
	
-- create SI index

-- SI index for CU004
CREATE INDEX SI_SEMA_CU004_IDX1 ON si_temp_sema_cu004
(CUST_CLASS_CODE ASC, CUST_CLASS_CAT ASC);   

CREATE INDEX SI_SEMA_CU004_IDX2 ON si_temp_sema_cu004
(ID_TYPE_CODE ASC, ID_TYPE_CAT ASC);   

CREATE INDEX SI_SEMA_CU004_IDX3 ON si_temp_sema_cu004
(SECONDARY_ID_TYPE_CODE ASC, SECONDARY_ID_TYPE_CAT ASC);  

CREATE INDEX SI_SEMA_CU004_IDX4 ON si_temp_sema_cu004
(CUST_TYPE_CODE ASC, CUST_TYPE_CAT ASC);  

CREATE INDEX SI_SEMA_CU004_IDX5 ON si_temp_sema_cu004
(INCOME_GROUP ASC, INCOME_GROUP_CAT ASC);  
	
CREATE INDEX SI_SEMA_CU004_IDX6 ON si_temp_sema_cu004
(PRIMARY_ADD_TYPE_CODE ASC, PRIMARY_ADD_TYPE_CAT ASC); 
	
CREATE INDEX SI_SEMA_CU004_IDX7 ON si_temp_sema_cu004
(SECONDARY_ADD_TYPE_CODE ASC, SECONDARY_ADD_TYPE_CAT ASC); 

CREATE INDEX SI_SEMA_CU004_IDX8 ON si_temp_sema_cu004
(CIF_ID ASC, IS_VALID ASC);   

create index SI_SEMA_CU004_IDX9 on si_temp_sema_cu004(cms_le_main_profile_id ASC);
create index SI_SEMA_CU004_IDX10 on si_temp_sema_cu004(cms_le_sub_profile_id ASC);

REORG INDEXES ALL FOR TABLE SI_TEMP_SEMA_CU004 ALLOW READ ACCESS;

-- SI index for CU002

CREATE INDEX SI_SEMA_CU002_IDX1 ON si_temp_sema_cu002
( IS_VALID ASC, CIF_ID ASC) allow reverse scans;

create index SI_SEMA_CU002_IDX2 on si_temp_sema_cu002(cms_le_main_profile_id ASC);

REORG INDEXES ALL FOR TABLE si_temp_sema_cu002 ALLOW READ ACCESS;

-- SI index for CA001

CREATE INDEX SI_SEMA_CA001_IDX1 ON si_temp_sema_ca001
( IS_VALID ASC, CIF_ID ASC) allow reverse scans;

create index SI_SEMA_CA001_IDX2 on si_temp_sema_ca001(cms_customer_id ASC);
create index SI_SEMA_CA001_IDX3 on si_temp_sema_ca001(cms_act_aa_id ASC);
create index SI_SEMA_CA001_IDX4 on si_temp_sema_ca001(cms_stg_aa_id ASC);

REORG INDEXES ALL FOR TABLE si_temp_sema_ca001 ALLOW READ ACCESS;

-- SI index for CA012

create index SI_SEMA_CA012_IDX1 on si_temp_sema_ca012 (limit_id asc, cms_act_lmt_id asc, is_valid asc)
allow reverse scans;

create index SI_SEMA_CA012_IDX2 on si_temp_sema_ca012 (limit_id asc, cms_stg_lmt_id asc, is_valid asc)
allow reverse scans;

create index SI_SEMA_CA012_IDX3 on si_temp_sema_ca012 (limit_id asc, is_valid asc)
allow reverse scans;

create index SI_SEMA_CA012_IDX4 on si_temp_sema_ca012(cms_act_lmt_id asc)
allow reverse scans;

create index SI_SEMA_CA012_IDX5 on si_temp_sema_ca012(cms_stg_lmt_id asc)
allow reverse scans;

create index SI_SEMA_CA012_IDX6 ON si_temp_sema_ca012(external_system_acct_no asc, limit_id asc, is_outer_lmt asc);

REORG INDEXES ALL FOR TABLE si_temp_sema_ca012 ALLOW READ ACCESS;

create index si_sema_update_AA_idx1 on si_sema_update_AA_date
(cms_limit_profile_id asc, create_date) cluster;

create index si_sema_update_AA_idx2 on si_sema_update_AA_date
(cms_stg_limit_profile_id asc, create_date);

-- SI index for CO020

create index SI_SEMA_CO020_IDX1 on si_temp_sema_co020
(IS_VALID ASC, SOURCE_SEC_ID ASC);

create index SI_SEMA_CO020_IDX2 on si_temp_sema_co020
(IS_VALID ASC, CMS_COLLATERAL_ID ASC);

create index SI_SEMA_CO020_IDX3 on si_temp_sema_co020
(IS_VALID ASC, CMS_STG_COLLATERAL_ID ASC);

create index SI_SEMA_CO020_IDX4 on si_temp_sema_co020
(IS_VALID ASC, CIF_ID ASC);

COMMIT WORK;