--------------------------------------------------
-- Security Envelope Location CMS_FUNCTION_ACCESS
--------------------------------------------------
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51300001, 'MaintainSecurityEnvelope' , 'maker_prepare_create' , 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51300002, 'MaintainSecurityEnvelope' , 'create_items' , 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51300003, 'MaintainSecurityEnvelopeItem' , 'create_items' , 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51300004, 'MaintainSecurityEnvelopeItem' , 'confirm_create_items' , 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 	
  VALUES(51300005, 'MaintainSecurityEnvelope', 'update_return_create', 2);	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 	
  VALUES(51300006, 'MaintainSecurityEnvelope', 'delete_items', 2);		
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300007, 'MaintainSecurityEnvelope', 'maker_confirm_create', 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300008, 'MaintainSecurityEnvelope' , 'checker_process_create' , 3);	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(51300009, 'MaintainSecurityEnvelope' , 'checker_confirm_approve_create' , 3);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300010, 'MaintainSecurityEnvelope', 'checker_confirm_reject_create', 3);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300011, 'MaintainSecurityEnvelope' , 'maker_prepare_edit' , 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(51300012, 'MaintainSecurityEnvelope', 'edit_items' , 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(51300013, 'MaintainSecurityEnvelopeItem', 'edit_items' , 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 	
  VALUES(51300014, 'MaintainSecurityEnvelope', 'update_return_edit', 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)  			
	VALUES(51300015, 'MaintainSecurityEnvelope', 'maker_confirm_edit', 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 	
	VALUES(51300016, 'MaintainSecurityEnvelope' , 'checker_process_edit' , 3);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300017, 'MaintainSecurityEnvelope', 'checker_confirm_approve_edit', 3);	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300018, 'MaintainSecurityEnvelope' , 'checker_confirm_reject_edit' , 3);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300019, 'MaintainSecurityEnvelope' , 'maker_prepare_resubmit' , 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300020, 'MaintainSecurityEnvelope' , 'maker_confirm_resubmit_edit' , 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300021, 'MaintainSecurityEnvelope' , 'delete_edit_items' , 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300022, 'MaintainSecurityEnvelope' , 'maker_prepare_close' , 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300023, 'MaintainSecurityEnvelope', 'maker_confirm_close', 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300024, 'MaintainSecurityEnvelope' , 'maker_prepare_edit_items' , 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300025, 'MaintainSecurityEnvelope', 'edit_itemdetail' , 2);	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300026, 'MaintainSecurityEnvelopeItem' , 'edit_itemdetail' , 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
  VALUES(51300027, 'MaintainSecurityEnvelope', 'create_itemdetail', 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
  VALUES(51300028, 'MaintainSecurityEnvelopeItem', 'create_itemdetail', 2);	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(51300029, 'MaintainSecurityEnvelopeItem' , 'resubmit_edit_items' , 2);	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300030, 'MaintainSecurityEnvelope' , 'update_return_resubmit_edit' , 2);	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(51300031, 'MaintainSecurityEnvelope' , 'delete_resubmit_edit_items' , 2);	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300032, 'MaintainSecurityEnvelopeItem' , 'resubmit_edit_itemdetail' , 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(51300033, 'MaintainSecurityEnvelope', 'checker_view_sec_envelope' , 3);	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(51300034, 'MaintainSecurityEnvelopeItem', 'cancel_create_items' , 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300035, 'MaintainSecurityEnvelopeItem', 'cancel_edit_items', 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300036, 'MaintainSecurityEnvelopeItem', 'cancel_resubmit_edit_items', 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300037, 'MaintainSecurityEnvelopeItem', 'cancel_create_itemdetail', 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300038, 'MaintainSecurityEnvelopeItem', 'cancel_edit_itemdetail', 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300039, 'MaintainSecurityEnvelopeItem', 'cancel_resubmit_edit_itemdetail', 2);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)	
	VALUES(51300040, 'MaintainSecurityEnvelope' , 'sec_envelope_list' , 2);


---------------------------------
-- Security Envelope Location TR_STATE_MATRIX
---------------------------------
INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP ) 
VALUES (8700, 'SEC_ENVELOPE','CREATE_SECENV','ND','PENDING_CREATE','PENDING_CREATE','1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP ) 
VALUES (8701, 'SEC_ENVELOPE','APPROVE_CREATE_SECENV','PENDING_CREATE','ACTIVE','ACTIVE','1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP ) 
VALUES (8702, 'SEC_ENVELOPE','UPDATE_SECENV','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP ) 
VALUES (8703, 'SEC_ENVELOPE','APPROVE_UPDATE_SECENV','PENDING_UPDATE','ACTIVE','ACTIVE','1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP )
VALUES (8704, 'SEC_ENVELOPE','REJECT_SECENV','PENDING_UPDATE','REJECTED','REJECTED','1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP ) 
VALUES (8705, 'SEC_ENVELOPE','EDIT_REJECTED_UPDATE_SECENV','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP ) 
VALUES (8706, 'SEC_ENVELOPE','CLOSE_REJECTED_UPDATE_SECENV','REJECTED','ACTIVE','ACTIVE','1','1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP ) 
VALUES (8707, 'SEC_ENVELOPE','REJECT_SECENV','PENDING_CREATE','REJECTED','REJECTED','1','1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP ) 
VALUES (8708, 'SEC_ENVELOPE','CLOSE_REJECTED_CREATE_SECENV','REJECTED','CLOSED','CLOSED','1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP ) 
VALUES (8709, 'SEC_ENVELOPE','EDIT_REJECTED_CREATE_SECENV','REJECTED','PENDING_CREATE','PENDING_CREATE','1','1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP ) 
VALUES (8710, 'SEC_ENVELOPE','EDIT_REJECTED_DELETE_SECENV','REJECTED','PENDING_DELETE','PENDING_DELETE','1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP ) 
VALUES (8711, 'SEC_ENVELOPE','DELETE_SECENV','ACTIVE', 'PENDING_DELETE','PENDING_DELETE', '1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP ) 
VALUES (8712, 'SEC_ENVELOPE','APPROVE_DELETE_SECENV','PENDING_DELETE','DELETED','DELETED',	'1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP ) 
VALUES (8713, 'SEC_ENVELOPE','REJECT_SECENV','PENDING_DELETE','REJECTED','REJECTED','1', '1');

INSERT INTO TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP ) 
VALUES (8714, 'SEC_ENVELOPE','CLOSE_REJECTED_DELETE_SECENV','REJECTED','ACTIVE','ACTIVE','1', '1');


----------------------------------------------
-- Security Envelope Location CMS_TRX_TOTRACK
----------------------------------------------

INSERT INTO CMS_TRX_TOTRACK ( TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE ) 
	VALUES ('SEC_ENVELOPE', 'MaintainSecurityEnvelope.do?event=to_track&paramTrxId=', 'ACTIVE', 'Approved', 'Maintain Security Envelope Location', null, null);

INSERT INTO CMS_TRX_TOTRACK ( TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE ) 
	VALUES ('SEC_ENVELOPE', 'MaintainSecurityEnvelope.do?event=to_track&paramTrxId=', 'CLOSED',	'Closed',	'Maintain Security Envelope Location',	null,	null); 

INSERT INTO CMS_TRX_TOTRACK ( TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE ) 
	VALUES ('SEC_ENVELOPE', 'MaintainSecurityEnvelope.do?event=to_track&paramTrxId=', 'DELETED',	'Deleted', 'Maintain Security Envelope Location', null, null); 

INSERT INTO CMS_TRX_TOTRACK ( TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE ) 
	VALUES ('SEC_ENVELOPE', 'MaintainSecurityEnvelope.do?event=to_track&paramTrxId=', 'PENDING_CREATE', 'Pending Create', 'Maintain Security Envelope Location', null, null); 

INSERT INTO CMS_TRX_TOTRACK ( TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE ) 
	VALUES ('SEC_ENVELOPE', 'MaintainSecurityEnvelope.do?event=to_track&paramTrxId=', 'PENDING_DELETE', 'Pending Delete', 'Maintain Security Envelope Location', null, null); 

INSERT INTO CMS_TRX_TOTRACK ( TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE ) 
	VALUES ('SEC_ENVELOPE', 'MaintainSecurityEnvelope.do?event=to_track&paramTrxId=', 'PENDING_UPDATE', 'Pending Update', 'Maintain Security Envelope Location',	null,	null); 

INSERT INTO CMS_TRX_TOTRACK ( TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE ) 
	VALUES ('SEC_ENVELOPE', 'MaintainSecurityEnvelope.do?event=to_track&paramTrxId=', 'REJECTED', 'Rejected', 'Maintain Security Envelope Location', null,	null);


----------------------------------------------------
-- Security Envelope Location CMS_STATEMATRIX_ACTION
----------------------------------------------------
INSERT INTO CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
VALUES (8701, 3, 'Process' , 'MaintainSecurityEnvelope.do?event=checker_process_create&paramTrxId=', 'MaintainSecurityEnvelope.do?event=to_track&paramTrxId=');

INSERT INTO CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
VALUES (8703, 3, 'Process' , 'MaintainSecurityEnvelope.do?event=checker_process_edit&paramTrxId=', 'MaintainSecurityEnvelope.do?event=to_track&paramTrxId=');

INSERT INTO CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
VALUES (8705, 2, 'Process' , 'MaintainSecurityEnvelope.do?event=maker_prepare_resubmit&paramTrxId=', 'MaintainSecurityEnvelope.do?event=to_track&paramTrxId=');

INSERT INTO CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
VALUES (8706, 2, 'Close' , 'MaintainSecurityEnvelope.do?event=maker_prepare_close&paramTrxId=', 'MaintainSecurityEnvelope.do?event=to_track&paramTrxId=');

INSERT INTO CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
VALUES (8712, 3, 'Process' , 'MaintainSecurityEnvelope.do?event=checker_process_delete&paramTrxId=', 'MaintainSecurityEnvelope.do?event=to_track&paramTrxId=');
                   