drop table DC_IN;

drop table DC_IN_ERR;

CREATE TABLE DC_IN (
	CIF_NUMBER VARCHAR(20),
	BORROWER_NAME VARCHAR(100),
	ACCOUNT_NUMBER VARCHAR(40),
	BUSINESS_UNIT VARCHAR(15),
	BRANCH_CODE VARCHAR(3),
	CMS_COLLATERAL_ID BIGINT NOT NULL,	
	COLLATERAL_CODE VARCHAR(4),
	--COLLATERAL_CODE_DESC VARCHAR(200), -- ignore description
	COLLATERAL_NAME VARCHAR(30),
	SECURITY_MATURITY_DATE TIMESTAMP, -- update 
	SECURITY_PERFECTION_DATE TIMESTAMP, -- update
	LEGAL_ENFORCEABILITY_IND CHAR(1), -- update
	LEGAL_ENFORCEABILITY_DATE TIMESTAMP, -- update 
	INSURER_NAME VARCHAR(100), --update
	INSURANCE_TYPE VARCHAR(20), -- update
	INSURED_CURRENCY CHAR(3), -- update
	INSURED_AMT DECIMAL(17,2), -- update
	INSURANCE_EFFECTIVE_DATE TIMESTAMP, -- update
	POLICY_NUMBER VARCHAR(30), -- update
	REGION VARCHAR(50) NOT NULL DEFAULT 'NA',
	VALID_IND CHAR(1) DEFAULT 'Y'
	)
IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE "DC_IN" 
	ADD CONSTRAINT "DC_IN_U" UNIQUE
		("CMS_COLLATERAL_ID",
		 "REGION");

CREATE TABLE DC_IN_ERR LIKE DC_IN
	IN "CMS_MIG" INDEX IN "CMS_MIG_INDEX";

ALTER TABLE DC_IN_ERR
	ADD DATE    TIMESTAMP;

ALTER TABLE DC_IN_ERR
  ADD REASON	CLOB;