
---------------------------------------------------
--insert script for CreditApproval Function Access
---------------------------------------------------


INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680009, 'credit_approval', 'checker_confirm_approve_create', 7);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680024, 'credit_approval', 'checker_confirm_approve_update', 7);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680022, 'credit_approval', 'confirm_maker_submit_remove', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680014, 'credit_approval', 'maker_confirm_close', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680029, 'credit_approval', 'maker_confirm_draft_close', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680018, 'credit_approval', 'maker_confirm_resubmit_edit', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680020, 'credit_approval', 'maker_confirm_resubmit_edit_rejected', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680027, 'credit_approval', 'maker_draft_close_process', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680025, 'credit_approval', 'maker_draft_creditApproval', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680016, 'credit_approval', 'maker_edit_creditApproval_read', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680005, 'credit_approval', 'maker_prepare_submit', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680031, 'credit_approval', 'maker_save_create', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680030, 'credit_approval', 'maker_save_update', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680002, 'credit_approval', 'maker_search_list_creditApproval', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680026, 'credit_approval', 'maker_update_draft_creditApproval', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680028, 'credit_approval', 'maker_update_save_process', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680008, 'credit_approval', 'maker_view_approve_reject_credit', 7);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680023, 'credit_approval', 'maker_view_approve_update_credit', 7);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680007, 'credit_approval', 'maker_view_credit', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680015, 'credit_approval', 'maker_view_creditApproval_read', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680003, 'credit_approval', 'prepare', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680001, 'credit_approval', 'prepare_list', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680017, 'credit_approval', 'prepare_maker_submit_edit', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680021, 'credit_approval', 'prepare_maker_submit_remove', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680011, 'credit_approval', 'event_reject_create', 7);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680004, 'credit_approval', 'save', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680006, 'credit_approval', 'view', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680010, 'credit_approval', 'view', 7);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680019, 'credit_approval', 'view_edit_reject_resubmit', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680012, 'credit_approval', 'view_reject', 7);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680013, 'credit_approval', 'view_reject_close', 6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680032,'credit_approval','event_reject_update',6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680033,'credit_approval','maker_prepare_upload_creditApproval',6);
INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
 ('680034','credit_approval','maker_event_upload_creditApproval',6); 
 INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
 ('680043','credit_approval','checker_prepare_list',7); 
 INSERT INTO cms_function_access(ID , ACTION , EVENT , ROLE_TYPE ) VALUES
(680044, 'credit_approval', 'checker_view_creditApproval_read', 7);
 
 INSERT INTO CMS_FUNCTION_ACCESS VALUES ('680035','credit_approval','checker_process_create_insert','7');
INSERT INTO CMS_FUNCTION_ACCESS VALUES ('680036','credit_approval','maker_rejected_delete_read','6');
INSERT INTO CMS_FUNCTION_ACCESS VALUES ('680037','credit_approval','checker_process_create_insert','7');
INSERT INTO CMS_FUNCTION_ACCESS VALUES ('680038','credit_approval','checker_approve_insert','7');
INSERT INTO CMS_FUNCTION_ACCESS VALUES ('680039','credit_approval','checker_reject_insert','7');
INSERT INTO CMS_FUNCTION_ACCESS VALUES ('680040','credit_approval','maker_prepare_insert_close','6');
INSERT INTO CMS_FUNCTION_ACCESS VALUES ('680041','credit_approval','maker_confirm_insert_close','6');
INSERT INTO CMS_FUNCTION_ACCESS VALUES ('680042','credit_approval','maker_rejected_delete_read','7');
INSERT INTO CMS_FUNCTION_ACCESS VALUES ('680045','credit_approval','checker_search_list_creditApproval','7');



---------------------------------------
--- Credit Approval  TO Track
---------------------------------------

INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE) VALUES
('CREDIT_APPROVAL', 'credit_approval.do?event=view&TrxId=', 'ACTIVE', 'Approved', 'Credit Approval Master', null, null); 
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE) VALUES
('CREDIT_APPROVAL', 'credit_approval.do?event=view&TrxId=', 'DRAFT', 'Draft', 'Credit Approval Master', null, null); 
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE) VALUES
('CREDIT_APPROVAL', 'credit_approval.do?event=view&TrxId=', 'DRAFT', 'Draft', 'Credit Approval Master', null, null);
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE) VALUES
('CREDIT_APPROVAL', 'credit_approval.do?event=maker_view_credit&TrxId=', 'ND', 'Pending Create', 'Credit Approval Master', null, null); 
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE) VALUES
('CREDIT_APPROVAL', 'credit_approval.do?event=maker_view_credit&TrxId=', 'PENDING_CREATE', 'Pending Create', 'Credit Approval Master', null, null); 
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE) VALUES
('CREDIT_APPROVAL', 'credit_approval.do?event=view&TrxId=', 'PENDING_DELETE', 'Pending Delete', 'Credit Approval Master', null, null); 
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE) VALUES
('CREDIT_APPROVAL', 'credit_approval.do?event=view&TrxId=', 'PENDING_UPDATE', 'Pending Update', 'Credit Approval Master', null, null); 
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE) VALUES
('CREDIT_APPROVAL', 'credit_approval.do?event=view_reject&TrxId=', 'REJECTED', 'Rejected', 'Credit Approval Master', null, null); 

INSERT INTO CMS_TRX_TOTRACK VALUES('INSERT_CREDIT_APP','credit_approval.do?event=maker_rejected_delete_read&toTrack=yes&TrxId=','ACTIVE','Approved','CREDIT APPROVER FILE UPLOAD',null,null);
INSERT INTO CMS_TRX_TOTRACK VALUES('INSERT_CREDIT_APP','credit_approval.do?event=maker_rejected_delete_read&toTrack=yes&TrxId=','CLOSED','Closed','CREDIT APPROVER FILE UPLOAD',null,null);
INSERT INTO CMS_TRX_TOTRACK VALUES('INSERT_CREDIT_APP','credit_approval.do?event=maker_rejected_delete_read&toTrack=yes&TrxId=','INSERT','Insert','CREDIT APPROVER FILE UPLOAD',null,null);
INSERT INTO CMS_TRX_TOTRACK VALUES('INSERT_CREDIT_APP','credit_approval.do?event=maker_rejected_delete_read&toTrack=yes&TrxId=','PENDING_INSERT','Pending Insert','CREDIT APPROVER FILE UPLOAD',null,null);
INSERT INTO CMS_TRX_TOTRACK VALUES('INSERT_CREDIT_APP','credit_approval.do?event=maker_rejected_delete_read&toTrack=yes&TrxId=','REJECTED','Rejected','CREDIT APPROVER FILE UPLOAD',null,null);


--------------------------------------------
--- Credit Approval Tr State Matrix
--------------------------------------------

INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3100, 'CREDIT_APPROVAL', 'ACTION_MAKER_UPDATE', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3101, 'CREDIT_APPROVAL', 'ACTION_MAKER_SUBMIT', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3102, 'CREDIT_APPROVAL', 'ACTION_MAKER_UPDATE_REJECTED', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3103, 'CREDIT_APPROVAL', 'ACTION_MAKER_CLOSE_REJECTED', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3105, 'CREDIT_APPROVAL', 'ACTION_CHECKER_REJECT_CREDIT_APPROVAL', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3106, 'CREDIT_APPROVAL', 'MAKER_UPDATE_SAVE', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3108, 'CREDIT_APPROVAL', 'ACTION_MAKER_SUBMIT_REJECTED', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3109, 'CREDIT_APPROVAL', 'ACTION_MAKER_CLOSE_DRAFT', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3110, 'CREDIT_APPROVAL', 'ADD_CREDIT_APPROVAL', 'ND', 'ACTIVE', 'ACTIVE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3111, 'CREDIT_APPROVAL', 'ACTION_MAKER_SUBMIT', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3112, 'CREDIT_APPROVAL', 'ACTION_MAKER_SUBMIT', 'PENDING_CREATE', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3113, 'CREDIT_APPROVAL', 'CHECKER_APPROVE_CREATE_CREDIT_APPROVAL', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3114, 'CREDIT_APPROVAL', 'ACTION_CHECKER_REJECT_CREDIT_APPROVAL', 'REJECTED', 'REJECTED', 'REJECTED', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3115, 'CREDIT_APPROVAL', 'ACTION_CHECKER_REJECT_CREDIT_APPROVAL', 'PENDING_CREATE', 'REJECTED', 'REJECTED', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3116, 'CREDIT_APPROVAL', 'UPDATE_CREDIT_APPROVAL', 'PENDING_UPDATE', 'ACTIVE', 'PENDING_UPDATE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3117, 'CREDIT_APPROVAL', 'UPDATE_CREDIT_APPROVAL', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3118, 'CREDIT_APPROVAL', 'APPROVE_UPDATE_CREDIT_APPROVAL', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3119, 'CREDIT_APPROVAL', 'EDIT_REJECTED_UPDATE_CREDIT_APPROVAL', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3120, 'CREDIT_APPROVAL', 'CHECKER_APPROVE_CREATE_CREDIT_APPROVAL', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3121, 'CREDIT_APPROVAL', 'DELETE_CREDIT_APPROVAL', 'PENDING_DELETE', 'ACTIVE', 'ACTIVE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3122, 'CREDIT_APPROVAL', 'UPDATE_CREDIT_APPROVAL', 'REJECTED ', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3123, 'CREDIT_APPROVAL', 'CHECKER_APPROVE_UPDATE', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3124, 'CREDIT_APPROVAL', 'CHECKER_APPROVE_CREATE_CREDIT_APPROVAL', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3125, 'CREDIT_APPROVAL', 'ACTION_CHECKER_REJECT_CREDIT_APPROVAL', 'PENDING_DELETE', 'REJECTED', 'REJECTED', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3126, 'CREDIT_APPROVAL', 'EDIT_REJECTED_DELETE_CREDIT_APPROVAL', 'REJECTED', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3127, 'CREDIT_APPROVAL', 'EDIT_REJECTED_CREATE_CREDIT_APPROVAL', 'REJECTED', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3128, 'CREDIT_APPROVAL', 'DELETE_CREDIT_APPROVAL', 'REJECTED', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3129, 'CREDIT_APPROVAL', 'DELETE_CREDIT_APPROVAL', 'ACTIVE', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3130, 'CREDIT_APPROVAL', 'CHECKER_APPROVE_UPDATE', 'PENDING_DELETE', 'ACTIVE', 'ACTIVE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3131, 'CREDIT_APPROVAL', 'ACTION_MAKER_SUBMIT', 'DRAFT', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3132, 'CREDIT_APPROVAL', 'MAKER_SAVE', 'PENDING_PERFECTION', 'DRAFT', 'DRAFT', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3133, 'CREDIT_APPROVAL', 'MAKER_UPDATE_SAVE', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3134, 'CREDIT_APPROVAL', 'UPDATE_CREDIT_APPROVAL', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3135, 'CREDIT_APPROVAL', 'MAKER_UPDATE_CLOSE', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1'); 
INSERT INTO TR_STATE_MATRIX (STATEID , STATEINS , OPERATION , FROMSTATE , TOSTATE , USERSTATE , ENABLEIND , FRONTENDOP ) VALUES
(3136, 'CREDIT_APPROVAL', 'MAKER_UPDATE_SAVE', 'REJECTED ', 'DRAFT', 'REJECTED', '1', '1');


--For File Upload
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (3137,'INSERT_CREDIT_APP','FILE_INSERT','PENDING_INSERT','PENDING_INSERT','PENDING_INSERT','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (3138,'INSERT_CREDIT_APP','FILE_INSERT','ND','PENDING_INSERT','PENDING_INSERT','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (3139,'INSERT_CREDIT_APP','REJECT_INSERT_FILE_MASTER','PENDING_INSERT','REJECTED','REJECTED','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (3140,'INSERT_CREDIT_APP','READ_FILE_INSERT','ND','ACTIVE','ACTIVE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (3141,'INSERT_CREDIT_APP','APPROVE_INSERT_FILE_MASTER','PENDING_INSERT','ACTIVE','ACTIVE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (3142,'INSERT_CREDIT_APP','CLOSE_REJECTED_FILE_MASTER','REJECTED','ACTIVE','ACTIVE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (3143,'INSERT_CREDIT_APP','INSERT_FILE_MASTER','ND','PENDING_CREATE','PENDING_CREATE','1','1');

----------------------------------------------
--- Credit Approval State Matrix Action
----------------------------------------------

INSERT INTO CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) VALUES
(3112, 7, 'Process', 'credit_approval.do?event=maker_view_approve_reject_credit&TrxId=', null); 
INSERT INTO CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) VALUES
(3114, 6, 'Close', 'credit_approval.do?event=view_reject_close&TrxId=', null); 
INSERT INTO CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) VALUES
(3114, 6, 'Process', 'credit_approval.do?event=view_edit_reject_resubmit&TrxId=', null); 
INSERT INTO CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) VALUES
(3116, 7, 'Process', 'credit_approval.do?event=maker_view_approve_reject_credit&TrxId=', null); 
INSERT INTO CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) VALUES
(3121, 7, 'Process', 'credit_approval.do?event=maker_view_approve_update_credit&TrxId=', null); 
INSERT INTO CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) VALUES
(3123, 7, 'Process', 'credit_approval.do?event=maker_view_approve_update_credit&TrxId=', null); 
INSERT INTO CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) VALUES
(3134, 6, 'Process', 'credit_approval.do?event=maker_update_save_process&TrxId=', null); 
INSERT INTO CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) VALUES
(3134, 6, 'Process', 'credit_approval.do?event=maker_update_save_process&TrxId=', null);
INSERT INTO CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) VALUES
(3135, 6, 'Close', 'credit_approval.do?event=maker_draft_close_process&TrxId=', null); 


INSERT INTO CMS_STATEMATRIX_ACTION VALUES ('3137','7','Process','credit_approval.do?event=checker_process_create_insert&TrxId=',null);

INSERT INTO CMS_STATEMATRIX_ACTION VALUES ('3142','6','Close','credit_approval.do?event=maker_prepare_insert_close&TrxId=','credit_approval.do?event=to_track&TrxId=');


