LOAD DATA
INFILE 'FILES\Relationship Managers.csv'
 "str '~~~'"
BADFILE 'PARTIAL_ERROR_LOG\Relationship Managers.bad'
DISCARDFILE 'PARTIAL_ERROR_LOG\Relationship Managers.dsc'
DISCARDMAX 1241513983
APPEND INTO TABLE MIG_CMS_RELATIONSHIP_MGR
FIELDS TERMINATED BY '|||'
TRAILING NULLCOLS
(
RMID "REPLACE(REPLACE(DECODE(UPPER(:RMID),'NULL',NULL,:RMID), CHR(10),''), CHR(13),'')",
RMNAME "DECODE(UPPER(:RMNAME),'NULL',NULL,:RMNAME)",
CCMAILID "DECODE(UPPER(:CCMAILID),'NULL',NULL,:CCMAILID)",
UNITHEAD "DECODE(UPPER(:UNITHEAD),'NULL',NULL,:UNITHEAD)",
REGION "DECODE(UPPER(:REGION),'NULL',NULL,:REGION)",
REPORTINGHEADEMAILID "DECODE(UPPER(:REPORTINGHEADEMAILID),'NULL',NULL,:REPORTINGHEADEMAILID)"
)