LOAD DATA
INFILE 'FILES\Facilities Master.csv'
 "str '~~~'"
BADFILE 'PARTIAL_ERROR_LOG\Facilities Master.bad'
DISCARDFILE 'PARTIAL_ERROR_LOG\Facilities Master.dsc'
DISCARDMAX 1241513983
APPEND INTO TABLE MIG_CMS_FACILITY_MASTER
FIELDS TERMINATED BY '|||'
TRAILING NULLCOLS
(
FACILITYID "REPLACE(REPLACE(DECODE(UPPER(:FACILITYID),'NULL',NULL,:FACILITYID), CHR(10),''), CHR(13),'')",
FACILITYNAME "DECODE(UPPER(:FACILITYNAME),'NULL',NULL,:FACILITYNAME)",
FACILITYTYPE  "DECODE(UPPER(:FACILITYTYPE),'NULL',NULL,:FACILITYTYPE)",
SYSTEMID "DECODE(UPPER(:SYSTEMID),'NULL',NULL,:SYSTEMID)",
CREDITLINENO "DECODE(UPPER(:CREDITLINENO),'NULL',NULL,:CREDITLINENO)",
GIVENFOR "DECODE(UPPER(:GIVENFOR),'NULL',NULL,:GIVENFOR)",
WEIGHTAGE "DECODE(UPPER(:WEIGHTAGE),'NULL',NULL,:WEIGHTAGE)"
)