--------------------------------
--- CMS_RELATIONSHIP_MGR 
--------------------------------

CREATE TABLE CMS_RELATIONSHIP_MGR (
		  ID BIGINT NOT NULL , 
		  'RM_MGR_CODE' VARCHAR(25) NOT NULL,
		  'EMPLOYEE_CODE' VARCHAR(25),	 
		  'RM_MGR_NAME' VARCHAR(25) NOT NULL, 
		  'RM_MGR_MAIL' VARCHAR(50) NOT NULL, 
		  'REPORTING_HEAD' VARCHAR(25) NOT NULL, 
		  'REPORTING_HEAD_MAIL' VARCHAR(50) NOT NULL, 
		  'REGION' VARCHAR(25) NOT NULL, 		  
		  'VERSION_TIME' BIGINT NOT NULL , 
		  'CREATE_BY' VARCHAR(25) NOT NULL , 
		  'CREATION_DATE' TIMESTAMP NOT NULL , 
		  'LAST_UPDATE_BY' VARCHAR(25) NOT NULL , 
		  'LAST_UPDATE_DATE' TIMESTAMP NOT NULL , 
		  'DEPRECATED' CHAR(1) NOT NULL , 
		  'STATUS' VARCHAR(30) NOT NULL )   
		 IN CMS_SMALL_DATA INDEX IN CMS_INDEX ; 



ALTER TABLE CMS_RELATIONSHIP_MGR 
	ADD CONSTRAINT PK_RELATIONSHIP_MGR PRIMARY KEY
		(ID);
		
alter table CMS_RELATIONSHIP_MGR add unique (RM_MGR_CODE)		

--------------------------------
--- CMS_STAGE_RELATIONSHIP_MGR 
--------------------------------

CREATE TABLE CMS_STAGE_RELATIONSHIP_MGR  (		   
		  ID BIGINT NOT NULL , 
		  'RM_MGR_CODE' VARCHAR(25) NOT NULL,
		  'EMPLOYEE_CODE' VARCHAR(25),	 
		  'RM_MGR_NAME' VARCHAR(25) NOT NULL, 
		  'RM_MGR_MAIL' VARCHAR(50) NOT NULL, 
		  'REPORTING_HEAD' VARCHAR(25) NOT NULL, 
		  'REPORTING_HEAD_MAIL' VARCHAR(50) NOT NULL, 
		  'REGION' VARCHAR(25) NOT NULL, 		  
		  'VERSION_TIME' BIGINT NOT NULL , 
		  'CREATE_BY' VARCHAR(25) NOT NULL , 
		  'CREATION_DATE' TIMESTAMP NOT NULL , 
		  'LAST_UPDATE_BY' VARCHAR(25) NOT NULL , 
		  'LAST_UPDATE_DATE' TIMESTAMP NOT NULL , 
		  'DEPRECATED' CHAR(1) NOT NULL , 
		  'STATUS' VARCHAR(30) NOT NULL )  
		 IN CMS_SMALL_DATA INDEX IN CMS_INDEX ;

ALTER TABLE CMS_STAGE_RELATIONSHIP_MGR 
	ADD CONSTRAINT PK_RELATIONSHIP_MGR PRIMARY KEY
		(ID);


INSERT INTO CMS_RELATIONSHIP_MGR VALUES(1,'011','011','Nisha Biswas','nisha.b@hdfc.com','Vijay Kulkarni','vijay.k@hdfc.com','North',0,'SC_MAKER','2011-04-12-14.18.23.433000','SC_MAKER','2011-04-12-14.18.23.433000','N','ACTIVE');

INSERT INTO CMS_STAGE_RELATIONSHIP_MGR VALUES(1,'011','011','Nisha Biswas','nisha.b@hdfc.com','Vijay Kulkarni','vijay.k@hdfc.com','North',0,'SC_MAKER','2011-04-12-14.18.23.433000','SC_MAKER','2011-04-12-14.18.23.433000','N','ACTIVE');