--------------------------------
--- CMS_FUNCTION_ACCESS Entries 
--------------------------------

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412001,'Annexure','list',10);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412005,'Annexure','prepare_add_annexure',10);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412006,'Annexure','add_annexure',10);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412007,'Annexure','remove_annexure',10);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412008,'Annexure','view_annexure_item',10);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412012,'Annexure','submit',10);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412013,'Annexure','process',11);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412014,'Annexure','to_track',11);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412016,'Annexure','chk_view_annexure',11);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412017,'Annexure','approve_checklist_item',11);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412018,'Annexure','reject_checklist_item',11);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412019,'Annexure','edit_staging_checklist_item',10);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412020,'Annexure','to_track',10);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412021,'Annexure','close',10);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412022,'Annexure','close_checklist_item',10);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412023,'Annexure','view_ok',10);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412047,'Annexure','view_annexure_item_to_track',10);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412048,'Annexure','view_annexure_item_to_track',11);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412052,'Annexure','update_annexure',10);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412054,'Annexure','edit_annexure_item',10);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412060,'Annexure','save',10);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412062,'Annexure','read',11);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412064,'Annexure','return',11);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412066,'Annexure','return',10);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412067,'Annexure','read',13);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412069,'Annexure','return',13);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412070,'Annexure','view_annexure_item',13);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412072,'Annexure','view_annexure_item',11);

INSERT into CMS_FUNCTION_ACCESS (ID,ACTION,EVENT,ROLE_TYPE) values (8412073,'Annexure','run_batch_job',10);

-----------------------------------
--- CMS_TRX_TOTRACK Entries 
-----------------------------------

INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, TRANSACTION_SUBTYPE) 
	VALUES ('RECURRENT_CHECKLIST', 'CheckListReceipt.do?event=to_track&custTypeTrxID=', 'PENDING_UPDATE', 'Pending Update', 'Update Annexure Checklist', 'REC_CHECKLIST_ANN');
	
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, TRANSACTION_SUBTYPE) 
	VALUES ('RECURRENT_CHECKLIST', 'CheckListReceipt.do?event=to_track&custTypeTrxID=', 'REJECTED', 'Rejected', 'Update Annexure Checklist', 'REC_CHECKLIST_ANN');
	
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE) 
	VALUES ('RECURRENT_CHECKLIST', 'CheckListReceipt.do?event=to_track&custTypeTrxID=', 'ACTIVE', 'Approved', 'Update Annexure Checklist', 'PENDING_UPDATE', 'REC_CHECKLIST_ANN');
	
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, TRANSACTION_SUBTYPE) 
	VALUES ('RECURRENT_CHECKLIST', 'CheckListReceipt.do?event=to_track&custTypeTrxID=', 'DRAFT', 'Draft', 'Update Annexure Checklist', 'REC_CHECKLIST_ANN');
	
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, TRANSACTION_SUBTYPE) 
	VALUES ('RECURRENT_CHECKLIST', 'CheckListReceipt.do?event=to_track&custTypeTrxID=', 'CLOSED', 'Closed', 'Update Annexure Checklist', 'REC_CHECKLIST_ANN');
	
INSERT INTO CMS_TRX_TOTRACK (TRANSACTION_TYPE, TOTRACK_URL, CURR_STATE, USER_STATE, USER_TRX_TYPE, FROM_STATE, TRANSACTION_SUBTYPE) 
	VALUES ('RECURRENT_CHECKLIST', 'CheckListReceipt.do?event=to_track&custTypeTrxID=', 'ACTIVE', 'Approved', 'Update Annexure Checklist', 'REJECTED', 'REC_CHECKLIST_ANN');

-----------------------------------
--- TR_STATE_MATRIX Entries 
-----------------------------------


INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11500,'ANNEXURE_CHECKLIST','CREATE_CHECKLIST_ANNEXURE','ND','PENDING_CREATE','PENDING_CREATE','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11505,'ANNEXURE_CHECKLIST','UPDATE_CHECKLIST_ANNEXURE','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11509,'ANNEXURE_CHECKLIST','CLOSE_REJECTED_UPDATE_CHECKLIST_ANNEXURE','REJECTED','ACTIVE','ACTIVE','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11510,'ANNEXURE_CHECKLIST','REJECT_CHECKLIST_ANNEXURE','PENDING_UPDATE','REJECTED','REJECTED','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11512,'ANNEXURE_CHECKLIST','EDIT_REJECTED_UPDATE_CHECKLIST_ANNEXURE','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11513,'ANNEXURE_CHECKLIST','APPROVE_UPDATE_CHECKLIST_ANNEXURE','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11515,'ANNEXURE_CHECKLIST','SYSTEM_CLOSE_CHECKLIST_ANNEXURE','ACTIVE','CLOSED','CLOSED','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11517,'ANNEXURE_CHECKLIST','SYSTEM_CLOSE_CHECKLIST_ANNEXURE','PENDING_UPDATE','CLOSED','CLOSED','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11518,'ANNEXURE_CHECKLIST','SYSTEM_CLOSE_CHECKLIST_ANNEXURE','REJECTED','CLOSED','CLOSED','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11519,'ANNEXURE_CHECKLIST','CLOSE_DRAFT_CHECKLIST_ANNEXURE','DRAFT','ACTIVE','ACTIVE','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11520,'ANNEXURE_CHECKLIST','SAVE_CHECKLIST_ANNEXURE','ACTIVE','DRAFT','DRAFT','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11521,'ANNEXURE_CHECKLIST','SAVE_CHECKLIST_ANNEXURE','DRAFT','DRAFT','DRAFT','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11522,'ANNEXURE_CHECKLIST','SAVE_CHECKLIST_ANNEXURE','REJECTED','DRAFT','DRAFT','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11523,'ANNEXURE_CHECKLIST','UPDATE_CHECKLIST_ANNEXURE','DRAFT','PENDING_UPDATE','PENDING_UPDATE','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11524,'ANNEXURE_CHECKLIST','SAVE_CREATE_CHECKLIST_ANNEXURE','ND','DRAFT','DRAFT','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11525,'ANNEXURE_CHECKLIST','DRAFT_CREATE_CHECKLIST_ANNEXURE','DRAFT','PENDING_CREATE','PENDING_CREATE','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11526,'ANNEXURE_CHECKLIST','DRAFT_SAVE_CHECKLIST_ANNEXURE','DRAFT','DRAFT','DRAFT','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11527,'ANNEXURE_CHECKLIST','CLOSE_DRAFT_CREATE_CHECKLIST_ANNEXURE','DRAFT','CLOSE','CLOSE','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11528,'ANNEXURE_CHECKLIST','DRAFT_SAVE_CHECKLIST_ANNEXURE','REJECTED','DRAFT','DRAFT','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11529,'ANNEXURE_CHECKLIST','DRAFT_UPDATE_CHECKLIST_ANNEXURE','DRAFT','PENDING_UPDATE','PENDING_UPDATE','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11530,'ANNEXURE_CHECKLIST','SAVE_ACTIVE_CHECKLIST_ANNEXURE','ACTIVE','DRAFT','DRAFT','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11531,'ANNEXURE_CHECKLIST','CLOSE_DRAFT_ACTIVE_CHECKLIST_ANNEXURE','DRAFT','ACTIVE','ACTIVE','1','1');

INSERT into TR_STATE_MATRIX (STATEID,STATEINS,OPERATION,FROMSTATE,TOSTATE,USERSTATE,ENABLEIND,FRONTENDOP) 
	values (11532,'ANNEXURE_CHECKLIST','SYSTEM_CREATE_CHECKLIST_ANNEXURE','ND','ACTIVE','ACTIVE','1','1');
