DROP TABLE MIG_ERROR_LOG;
DROP TABLE PROC_TIME_LOG;

DROP TABLE TRX_STG_LMT_UPDATE;
DROP TABLE TRX_STG_FAC_UPDATE;

DROP TABLE MIG_TMP_AA;
DROP VIEW VW_MIG_SEC;

CREATE TABLE MIG_ERROR_LOG (
  SI_NUMBER	BIGINT	GENERATED ALWAYS
                                AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE,
                                NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  TIME_STAMP	TIMESTAMP,
  SYSTEM_ID	    VARCHAR(10),
  INTERFACE_ID	VARCHAR(10),
  KEY1_VALUE	VARCHAR(50),
  KEY2_VALUE	VARCHAR(50),
  KEY3_VALUE	VARCHAR(50),
  KEY4_VALUE	VARCHAR(50),
  KEY5_VALUE	VARCHAR(50),
  ERROR_CODE	VARCHAR(20),
  ERROR_MSG	    VARCHAR(1000)
) in CMS_MIG index in CMS_MIG_INDEX;
	
CREATE INDEX MIG_ERROR_LOG_IDX1 ON MIG_ERROR_LOG
(INTERFACE_ID ASC, SYSTEM_ID ASC) ALLOW REVERSE SCANS;   
    
CREATE TABLE PROC_TIME_LOG(
  PROC_NUMBER BIGINT NOT NULL GENERATED ALWAYS
                                AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE,
                                NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
 PROC_NAME VARCHAR(255),
 SOURCE_ID VARCHAR(10),
 START_FLAG INT,
 TIME_STAMP TIMESTAMP
) in CMS_MIG index in CMS_MIG_INDEX;



CREATE TABLE TRX_STG_LMT_UPDATE (
	ACT_LMT_ID BIGINT,
	STG_LMT_ID BIGINT
) in CMS_MIG index in CMS_MIG_INDEX;

CREATE TABLE TRX_STG_FAC_UPDATE (
	ACT_FAC_ID BIGINT,
	STG_FAC_ID BIGINT
) in CMS_MIG index in CMS_MIG_INDEX;


CREATE TABLE MIG_TMP_AA(
    CMS_LSP_LMT_PROFILE_ID       BIGINT,
    CMS_CUSTOMER_ID              BIGINT,
    APPLICATION_TYPE             VARCHAR(40),
    TRANSACTION_ID               VARCHAR(20),    
    LLP_BCA_REF_NUM              VARCHAR(35),
    LOS_BCA_REF_NUM              VARCHAR(35)
)
in CMS_MIG index in CMS_MIG_INDEX;

	
drop table tmp_pledgor_checklist;
	create table tmp_pledgor_checklist (
		cms_pledgor_dtl_id	bigint,
		cms_lsp_lmt_profile_id	bigint,		
		pledgor_customer_id	bigint,
		cms_customer_id		bigint,
		pledgor_cif_id			varchar(19),
		is_borrower	char(1) default 'N',
		cms_act_checklist_id	bigint ,
		cms_stg_checklist_id	bigint,
		doc_orig_country	varchar(2),
		doc_orig_organisation	varchar(40),
		application_type	varchar(40),
		trx_reference_id	bigint		
	) in CMS_MIG index in CMS_MIG_INDEX;
	
	drop table mig_sec_tmp_checklist;
	create table mig_sec_tmp_checklist (
		cms_act_checklist_id	bigint,
		cms_stg_checklist_id	bigint,
		cms_lsp_lmt_profile_id	bigint,
		cms_collateral_id	bigint,
		doc_orig_country		varchar(2),
		doc_orig_organisation	varchar(40)
	) in CMS_MIG index in CMS_MIG_INDEX;		

-- CREATE INDEX MIG_TMP_AA_IDX1 ON MIG_TMP_AA
-- (CMS_LSP_LMT_PROFILE_ID ASC, CMS_CUSTOMER_ID ASC);  


CREATE VIEW VW_MIG_SEC (SECURITY_ID, SUBTYPE, CMS_SECURITY_SUBTYPE_ID, SECURITY_REF_NOTE, SOURCE_SECURITY_TYPE, SOURCE_SECURITY_SUB_TYPE, CURRENCY, IS_VALID)
AS
SELECT SECURITY_ID, 'AB' SUBTYPE, CMS_SECURITY_SUBTYPE_ID, SECURITY_REF_NOTE, SOURCE_SECURITY_TYPE, SOURCE_SECURITY_SUB_TYPE, CURRENCY, IS_VALID from MIG_CO001_AB
union 
SELECT SECURITY_ID, 'AB' SUBTYPE, CMS_SECURITY_SUBTYPE_ID, SECURITY_REF_NOTE, SOURCE_SECURITY_TYPE, SOURCE_SECURITY_SUB_TYPE, CURRENCY, IS_VALID from MIG_CO002_AB_GOLD
union 
SELECT SECURITY_ID, 'CS' SUBTYPE, CMS_SECURITY_SUBTYPE_ID, SECURITY_REF_NOTE, SOURCE_SECURITY_TYPE, SOURCE_SECURITY_SUB_TYPE, CURRENCY, IS_VALID from MIG_CO005_CS
union 
SELECT SECURITY_ID, 'MS' SUBTYPE, CMS_SECURITY_SUBTYPE_ID, SECURITY_REF_NOTE, SOURCE_SECURITY_TYPE, SOURCE_SECURITY_SUB_TYPE, CURRENCY, IS_VALID from MIG_CO008_MS
union 
SELECT SECURITY_ID, 'PT' SUBTYPE, CMS_SECURITY_SUBTYPE_ID, SECURITY_REF_NOTE, SOURCE_SECURITY_TYPE, SOURCE_SECURITY_SUB_TYPE, CURRENCY, IS_VALID from MIG_CO009_PT
union 
SELECT SECURITY_ID, 'GT' SUBTYPE, CMS_SECURITY_SUBTYPE_ID, SECURITY_REF_NOTE, SOURCE_SECURITY_TYPE, SOURCE_SECURITY_SUB_TYPE, CURRENCY, IS_VALID from MIG_CO010_GT
union 
SELECT SECURITY_ID, 'OT' SUBTYPE, CMS_SECURITY_SUBTYPE_ID, SECURITY_REF_NOTE, SOURCE_SECURITY_TYPE, SOURCE_SECURITY_SUB_TYPE, CURRENCY, IS_VALID from MIG_CO011_OT
union 
SELECT SECURITY_ID, 'IN' SUBTYPE, CMS_SECURITY_SUBTYPE_ID, SECURITY_REF_NOTE, SOURCE_SECURITY_TYPE, SOURCE_SECURITY_SUB_TYPE, CURRENCY, IS_VALID from MIG_CO012_IN
union 
SELECT SECURITY_ID, 'CL' SUBTYPE, CMS_SECURITY_SUBTYPE_ID, SECURITY_REF_NOTE, SOURCE_SECURITY_TYPE, SOURCE_SECURITY_SUB_TYPE, CURRENCY, IS_VALID from MIG_CO014_CL;
