-----------------------------
-- Cleanup
-----------------------------
-- DELETE FROM MIG_QC_REPORT;		//Use drop and recreate mig report - much faster

-----------------------------
-- Customer
-----------------------------
-- CU001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CU001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV001SIBS', 'SIBS', 'CU001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CU001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CU001_CU WHERE IS_VALID = 'Y'), 'SIBS', 'CU001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'CIF ID / Customer Name Short / ID Number', 'SIBS', 'CU001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(CIF_ID,'-') || ' / ' || COALESCE(CUST_NAME_S,'-') || ' / ' || COALESCE(ID_NUMBER,'-'), 'SIBS', 'CU001' 
     FROM MIG_CU001_CU WHERE IS_VALID = 'Y');
    
-----------------------------
-- AA
-----------------------------
-- CA001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV002SIBS', 'SIBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CA001_AA WHERE IS_VALID = 'Y'), 'SIBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'CIF ID / AA Number / LOS AA Number', 'SIBS', 'CA001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(CIF_ID,'-') || ' / ' || COALESCE(AA_NUMBER,'-') || ' / ' || COALESCE(LOS_BCA_REF_NUM,'-'), 'SIBS', 'CA001' 
     FROM MIG_CA001_AA WHERE IS_VALID = 'Y');


-----------------------------
-- Joint Borrower
-----------------------------    
-- CA002
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CA002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV003SIBS', 'SIBS', 'CA002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CA002_JB WHERE IS_VALID = 'Y'), 'SIBS', 'CA002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'CIF ID / AA Number', 'SIBS', 'CA002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(CIF_ID,'-') || ' / ' || COALESCE(AA_NUMBER,'-'), 'SIBS', 'CA002' 
     FROM MIG_CA002_JB WHERE IS_VALID = 'Y');

 
 
-----------------------------
-- Facility
-----------------------------    
-- CA003_1
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CA003_1');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV004SIBS', 'SIBS', 'CA003_1');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_1');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CA003_1 WHERE IS_VALID = 'Y'), 'SIBS', 'CA003_1');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'CIF ID / Limit ID / AA Number / Facility Code / Facility Sequence', 'SIBS', 'CA003_1');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(CIF_ID,'-') || ' / ' || COALESCE(LIMIT_ID,'-') || ' / ' || COALESCE(ACF_NO,'-') || ' / ' || COALESCE(FACILITY_CODE,'-') || ' / ' || COALESCE(char(FACILITY_SEQ),'-'), 'SIBS', 'CA003_1' 
     FROM MIG_CA003_1 WHERE IS_VALID = 'Y');
 
-- CA003_2
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CA003_2');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV005SIBS', 'SIBS', 'CA003_2');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_2');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CA003_2_BNM WHERE IS_VALID = 'Y'), 'SIBS', 'CA003_2');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Limit ID / AA Number / Facility Code / Facility Sequence', 'SIBS', 'CA003_2');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(LMT_ID,'-') || ' / ' || COALESCE(LLP_BCA_REF_NUM,'-') || ' / ' || COALESCE(LMT_FAC_CODE,'-') || ' / ' || COALESCE(char(LMT_FAC_SEQ),'-'), 'SIBS', 'CA003_2' 
     FROM MIG_CA003_2_BNM WHERE IS_VALID = 'Y');
 
-- CA003_3
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CA003_3');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV006SIBS', 'SIBS', 'CA003_3');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_3');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CA003_3_OFF WHERE IS_VALID = 'Y'), 'SIBS', 'CA003_3');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Limit ID / AA Number / Facility Code / Facility Sequence / Officer Seq No', 'SIBS', 'CA003_3');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(LMT_ID,'-') || ' / ' || COALESCE(LLP_BCA_REF_NUM,'-') || ' / ' || COALESCE(LMT_FAC_CODE,'-') || ' / ' || COALESCE(char(LMT_FAC_SEQ),'-') || ' / ' || COALESCE(char(SEQ_NUM),'-'), 'SIBS', 'CA003_3' 
     FROM MIG_CA003_3_OFF WHERE IS_VALID = 'Y');
 
-- CA003_4
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CA003_4');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV007SIBS', 'SIBS', 'CA003_4');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_4');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CA003_4_REL WHERE IS_VALID = 'Y'), 'SIBS', 'CA003_4');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Limit ID / AA Number / Facility Code / Facility Sequence / CIF ID', 'SIBS', 'CA003_4');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(LMT_ID,'-') || ' / ' || COALESCE(LLP_BCA_REF_NUM,'-') || ' / ' || COALESCE(LMT_FAC_CODE,'-') || ' / ' || COALESCE(char(LMT_FAC_SEQ),'-') || ' / ' || COALESCE(CIF_NUMBER,'-'), 'SIBS', 'CA003_4' 
     FROM MIG_CA003_4_REL WHERE IS_VALID = 'Y');
 
-- CA003_5
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CA003_5');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV008SIBS', 'SIBS', 'CA003_5');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_5');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CA003_5_INS WHERE IS_VALID = 'Y'), 'SIBS', 'CA003_5');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Limit ID / AA Number / Facility Code / Facility Sequence', 'SIBS', 'CA003_5');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(LMT_ID,'-') || ' / ' || COALESCE(LLP_BCA_REF_NUM,'-') || ' / ' || COALESCE(LMT_FAC_CODE,'-') || ' / ' || COALESCE(char(LMT_FAC_SEQ),'-'), 'SIBS', 'CA003_5' 
     FROM MIG_CA003_5_INS WHERE IS_VALID = 'Y');
 
-- CA003_6
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CA003_6');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV009SIBS', 'SIBS', 'CA003_6');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_6');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CA003_6_MUL WHERE IS_VALID = 'Y'), 'SIBS', 'CA003_6');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Limit ID / AA Number / Facility Code / Facility Sequence / Tier Seq No', 'SIBS', 'CA003_6');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(LMT_ID,'-') || ' / ' || COALESCE(LLP_BCA_REF_NUM,'-') || ' / ' || COALESCE(LMT_FAC_CODE,'-') || ' / ' || COALESCE(char(LMT_FAC_SEQ),'-') || ' / ' || COALESCE(char(TIER_SEQ_NO),'-'), 'SIBS', 'CA003_6' 
     FROM MIG_CA003_6_MUL WHERE IS_VALID = 'Y');
 
-- CA003_7
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CA003_7');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV010SIBS', 'SIBS', 'CA003_7');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_7');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CA003_7_ISL WHERE IS_VALID = 'Y'), 'SIBS', 'CA003_7');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Limit ID / AA Number / Facility Code / Facility Sequence', 'SIBS', 'CA003_7');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(LMT_ID,'-') || ' / ' || COALESCE(LLP_BCA_REF_NUM,'-') || ' / ' || COALESCE(LMT_FAC_CODE,'-') || ' / ' || COALESCE(char(LMT_FAC_SEQ),'-'), 'SIBS', 'CA003_7' 
     FROM MIG_CA003_7_ISL WHERE IS_VALID = 'Y');
 
-- CA003_8
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CA003_8');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV011SIBS', 'SIBS', 'CA003_8');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_8');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CA003_8_BBA WHERE IS_VALID = 'Y'), 'SIBS', 'CA003_8');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Limit ID / AA Number / Facility Code / Facility Sequence', 'SIBS', 'CA003_8');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(LMT_ID,'-') || ' / ' || COALESCE(LLP_BCA_REF_NUM,'-') || ' / ' || COALESCE(LMT_FAC_CODE,'-') || ' / ' || COALESCE(char(LMT_FAC_SEQ),'-'), 'SIBS', 'CA003_8' 
     FROM MIG_CA003_8_BBA WHERE IS_VALID = 'Y');
 
 
-----------------------------
-- Limit-Account
-----------------------------    
-- CA004
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CA004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV016SIBS', 'SIBS', 'CA004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CA004 WHERE IS_VALID = 'Y'), 'SIBS', 'CA004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Limit ID / AA Number / External System Account No / Account Sequence', 'SIBS', 'CA004');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(LIMIT_ID,'-') || ' / ' || COALESCE(AA_NUMBER,'-') || ' / ' || COALESCE(EXTERNAL_SYSTEM_ACCT_NO,'-') || ' / ' || COALESCE(char(ACCT_SEQ),'-'), 'SIBS', 'CA004' 
     FROM MIG_CA004 WHERE IS_VALID = 'Y');

	 
 
-----------------------------
-- Collateral
-----------------------------
-- CO001:AB
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CO001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV018SIBS', 'SIBS', 'CO001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CO001_AB WHERE IS_VALID = 'Y'), 'SIBS', 'CO001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Security ID / Security Type ID / Security Sub Type ID / Security Reference Note', 'SIBS', 'CO001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(SECURITY_ID,'-') || ' / ' || COALESCE(CMS_SECURITY_TYPE_ID,'-') || ' / ' || COALESCE(CMS_SECURITY_SUBTYPE_ID,'-') || ' / ' || COALESCE(SECURITY_REF_NOTE,'-'), 'SIBS', 'CO001' 
     FROM MIG_CO001_AB WHERE IS_VALID = 'Y'); 
 
-- CO002:AB-Gold
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CO002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV019SIBS', 'SIBS', 'CO002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CO002_AB_GOLD WHERE IS_VALID = 'Y'), 'SIBS', 'CO002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Security ID / Security Type ID / Security Sub Type ID / Security Reference Note', 'SIBS', 'CO002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(SECURITY_ID,'-') || ' / ' || COALESCE(CMS_SECURITY_TYPE_ID,'-') || ' / ' || COALESCE(CMS_SECURITY_SUBTYPE_ID,'-') || ' / ' || COALESCE(SECURITY_REF_NOTE,'-'), 'SIBS', 'CO002' 
     FROM MIG_CO002_AB_GOLD WHERE IS_VALID = 'Y'); 
 
-- CO005:CS
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CO005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV022SIBS', 'SIBS', 'CO005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CO005_CS WHERE IS_VALID = 'Y'), 'SIBS', 'CO005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Security ID / Security Type ID / Security Sub Type ID / Security Reference Note', 'SIBS', 'CO005');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(SECURITY_ID,'-') || ' / ' || COALESCE(CMS_SECURITY_TYPE_ID,'-') || ' / ' || COALESCE(CMS_SECURITY_SUBTYPE_ID,'-') || ' / ' || COALESCE(SECURITY_REF_NOTE,'-'), 'SIBS', 'CO005' 
     FROM MIG_CO005_CS WHERE IS_VALID = 'Y');
    
-- CO008:MS
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CO008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV024SIBS', 'SIBS', 'CO008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CO008_MS WHERE IS_VALID = 'Y'), 'SIBS', 'CO008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Security ID / Security Type ID / Security Sub Type ID / Security Reference Note', 'SIBS', 'CO008');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(SECURITY_ID,'-') || ' / ' || COALESCE(CMS_SECURITY_TYPE_ID,'-') || ' / ' || COALESCE(CMS_SECURITY_SUBTYPE_ID,'-') || ' / ' || COALESCE(SECURITY_REF_NOTE,'-'), 'SIBS', 'CO008' 
     FROM MIG_CO008_MS WHERE IS_VALID = 'Y');

-- CO009:PT
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CO009');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV025SIBS', 'SIBS', 'CO009');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO009');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CO009_PT WHERE IS_VALID = 'Y'), 'SIBS', 'CO009');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Security ID / Security Sub Type ID / Security Reference Note', 'SIBS', 'CO009');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(SECURITY_ID,'-') || ' / ' || COALESCE(CMS_SECURITY_SUBTYPE_ID,'-') || ' / ' || COALESCE(SECURITY_REF_NOTE,'-'), 'SIBS', 'CO009' 
     FROM MIG_CO009_PT WHERE IS_VALID = 'Y');
    
-- CO010:GT
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CO010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV026SIBS', 'SIBS', 'CO010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CO010_GT WHERE IS_VALID = 'Y'), 'SIBS', 'CO010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Security ID / Security Sub Type ID / Security Reference Note', 'SIBS', 'CO010');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(SECURITY_ID,'-') || ' / ' || COALESCE(CMS_SECURITY_SUBTYPE_ID,'-') || ' / ' || COALESCE(SECURITY_REF_NOTE,'-'), 'SIBS', 'CO010' 
     FROM MIG_CO010_GT WHERE IS_VALID = 'Y');

-- CO011:OT
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CO011');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV027SIBS', 'SIBS', 'CO011');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO011');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CO011_OT WHERE IS_VALID = 'Y'), 'SIBS', 'CO011');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Security ID / Security Sub Type ID / Security Reference Note', 'SIBS', 'CO011');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(SECURITY_ID,'-') || ' / ' || COALESCE(CMS_SECURITY_SUBTYPE_ID,'-') || ' / ' || COALESCE(SECURITY_REF_NOTE,'-'), 'SIBS', 'CO011' 
     FROM MIG_CO011_OT WHERE IS_VALID = 'Y');

-- CO012:IN
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CO012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV028SIBS', 'SIBS', 'CO012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CO012_IN WHERE IS_VALID = 'Y'), 'SIBS', 'CO012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Security ID / Security Sub Type ID / Security Reference Note', 'SIBS', 'CO012');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(SECURITY_ID,'-') || ' / ' || COALESCE(CMS_SECURITY_SUBTYPE_ID,'-') || ' / ' || COALESCE(SECURITY_REF_NOTE,'-'), 'SIBS', 'CO012' 
     FROM MIG_CO012_IN WHERE IS_VALID = 'Y');

-- CO014:CL
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CO014');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV030SIBS', 'SIBS', 'CO014');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO014');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CO014_CL WHERE IS_VALID = 'Y'), 'SIBS', 'CO014');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Security ID / Security Sub Type ID / Security Reference Note', 'SIBS', 'CO014');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(SECURITY_ID,'-') || ' / ' || COALESCE(CMS_SECURITY_SUBTYPE_ID,'-') || ' / ' || COALESCE(SECURITY_REF_NOTE,'-'), 'SIBS', 'CO014' 
     FROM MIG_CO014_CL WHERE IS_VALID = 'Y');    

	 
-----------------------------
-- Lin kages
-----------------------------	 
-- CO015:VL
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CO015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV031SIBS', 'SIBS', 'CO015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CO015_VL WHERE IS_VALID = 'Y'), 'SIBS', 'CO015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Security ID', 'SIBS', 'CO015');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(SECURITY_ID,'-'), 'SIBS', 'CO015' 
     FROM MIG_CO015_VL WHERE IS_VALID = 'Y');    

-- CO016:INS Policy
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CO016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV032SIBS', 'SIBS', 'CO016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CO016_IN WHERE IS_VALID = 'Y'), 'SIBS', 'CO016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Security ID / Policy Number', 'SIBS', 'CO016');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(SECURITY_ID,'-') || ' / ' || COALESCE(POLICY_NUMBER,'-'), 'SIBS', 'CO016' 
     FROM MIG_CO016_IN WHERE IS_VALID = 'Y');     

-- CO017:CD
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CO017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV033SIBS', 'SIBS', 'CO017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CO017_CD WHERE IS_VALID = 'Y'), 'SIBS', 'CO017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Security ID / Limit ID / Application No / Facility Code / Faciltiy Sequence / Ranking of Security', 'SIBS', 'CO017');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(SECURITY_ID,'-') || ' / ' || COALESCE(LIMIT_ID,'-') || ' / ' || COALESCE(APPLICATION_NO,'-') || ' / ' || COALESCE(FACILITY_CODE,'-') || ' / ' || COALESCE(char(FACILITY_SEQ),'-') || ',' || COALESCE(char(RANKING_OF_SECURITY),'-'), 'SIBS', 'CO017' 
     FROM MIG_CO017_CD WHERE IS_VALID = 'Y');  

-- CO018:Pledgor
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CO018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV034SIBS', 'SIBS', 'CO018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CO018_PG WHERE IS_VALID = 'Y'), 'SIBS', 'CO018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Security ID / Pledgor CIF ID', 'SIBS', 'CO018');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(SECURITY_ID,'-') || ' / ' || COALESCE(PLEDGOR_CIF_ID,'-'), 'SIBS', 'CO018' 
     FROM MIG_CO018_PG WHERE IS_VALID = 'Y');     

-- CO019:Pledge
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'QC Report 6 for Migration', 'SIBS', 'CO019');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report for migration template: CV035SIBS', 'SIBS', 'CO019');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO019');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Records migrated(s): ' || (SELECT char(COUNT(*)) FROM MIG_CO019_PL WHERE IS_VALID = 'Y'), 'SIBS', 'CO019');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('Valid', 'Security ID / Limit ID / Application No / Facility Code / Faciltiy Sequence', 'SIBS', 'CO019');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'Valid', COALESCE(SECURITY_ID,'-') || ' / ' || COALESCE(LIMIT_ID,'-') || ' / ' || COALESCE(APPLICATION_NO,'-') || ' / ' || COALESCE(FACILITY_CODE,'-') || ' / ' || COALESCE(char(FACILITY_SEQUENCE),'-'), 'SIBS', 'CO019' 
     FROM MIG_CO019_PL WHERE IS_VALID = 'Y');   