------------------------
-- QC Report Table 
------------------------
DROP TABLE MIG_QC_REPORT;

CREATE TABLE MIG_QC_REPORT(
    MIG_ID	BIGINT	NOT NULL	GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE, NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
    RECORD_TYPE     VARCHAR(30),
    TEXT            VARCHAR(4000),
    SYSTEM_ID       VARCHAR(4),
    INTERFACE_ID	VARCHAR(7),
	KEY_VALUE1		VARCHAR(3), 	-- APPLICATION_TYPE
	KEY_VALUE2		VARCHAR(3), 	-- APPLICATION_LAW_TYPE
	KEY_VALUE3		VARCHAR(20), 	-- CIF_ID
	KEY_VALUE4 		VARCHAR(19), 	-- APPLICATION_NO
	KEY_VALUE5		VARCHAR(3), 	-- FACILITY_CODE
	KEY_VALUE6		BIGINT, 		-- FACILITY_SEQUENCE
	KEY_VALUE7		VARCHAR(20), 	-- SECURITY_ID
	KEY_VALUE8		VARCHAR(3), 	-- SOURCE_SECURITY_SUB_TYPE
	FLAG			VARCHAR(1)
)  IN CMS_MIG;

