CREATE TABLE SCI_LE_VENDOR_DETAILS  
(CMS_LE_VENDOR_ID	NUMBER(19,0)  constraint SYSTEMPK PRIMARY KEY,
CMS_LE_VENDOR_NAME	VARCHAR2(100),
CMS_LE_MAIN_PROFILE_ID	NUMBER(19,0)
);


 CREATE TABLE STAGE_SCI_LE_VENDOR_DETAILS 
 (CMS_LE_VENDOR_ID	NUMBER(19,0) constraint SYSTEM_PK PRIMARY KEY,
CMS_LE_VENDOR_NAME	VARCHAR2(100),
CMS_LE_MAIN_PROFILE_ID	NUMBER(19,0)
);

 CREATE TABLE CMS_JS_INTERFACE_LOG
   (	ID NUMBER(19,0) NOT NULL ENABLE, 
	INTERFACENAME VARCHAR2(200 BYTE), 
	REQUESTDATETIME TIMESTAMP (6), 
	RESPONSEDATETIME TIMESTAMP (6), 
	ERRORMESSAGE VARCHAR2(2000 BYTE), 
	ERRORCODE VARCHAR2(200 BYTE), 
	limitProfileId VARCHAR2(100 BYTE), 
	line_no VARCHAR2(30 BYTE),
	serial_no VARCHAR2(30 BYTE),
	STATUS VARCHAR2(50 BYTE), 
	TRANSACTIONID NUMBER(19,0), 
    REQUESTMESSAGE CLOB, 
	RESPONSEMESSAGE CLOB, 
	MODULENAME VARCHAR2(50 BYTE), 
	OPERATION VARCHAR2(100 BYTE), 
	PARTYID VARCHAR2(50 BYTE), 
	PARTYNAME VARCHAR2(2000 BYTE),
	scmflag varchar2(10)
   );       
   
   CREATE SEQUENCE CMS_JS_INTERFACE_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999
  MINVALUE 1
  CYCLE
  NOCACHE
  NOORDER;