SET DEFINE OFF;

Delete from CMS_UDF where sequence = 97 and FIELDNAME = 'Borrower SCM Flag';
Delete from CMS_STAGE_UDF where sequence = 97 and FIELDNAME = 'Borrower SCM Flag';

DROP TABLE SCI_LE_VENDOR_DETAILS;
DROP TABLE STAGE_SCI_LE_VENDOR_DETAILS;
DROP TABLE  CMS_JS_INTERFACE_LOG;

ALTER TABLE  CMS_FACILITY_NEW_MASTER DROP SCM_FLAG ;
ALTER TABLE  CMS_STAGE_FACILITY_NEW_MASTER DROP SCM_FLAG ;
ALTER TABLE SCI_LSP_SYS_XREF DROP SCM_FLAG ;
ALTER TABLE SCI_LSP_SYS_XREF DROP VENDOR_DTL;
ALTER TABLE CMS_STAGE_LSP_SYS_XREF DROP SCM_FLAG ;
ALTER TABLE CMS_STAGE_LSP_SYS_XREF DROP VENDOR_DTL;
ALTER TABLE SCI_LE_UDF DROP UDF101;
ALTER TABLE STAGE_SCI_LE_UDF DROP UDF101;
ALTER TABLE SCI_LE_UDF DROP UDF102;
ALTER TABLE STAGE_SCI_LE_UDF DROP UDF102;
ALTER TABLE SCI_LE_UDF DROP UDF103;
ALTER TABLE STAGE_SCI_LE_UDF DROP UDF103;
ALTER TABLE SCI_LE_UDF DROP UDF104;
ALTER TABLE STAGE_SCI_LE_UDF DROP UDF104;
ALTER TABLE SCI_LE_UDF DROP UDF105;
ALTER TABLE STAGE_SCI_LE_UDF DROP UDF105;
ALTER TABLE SCI_LE_UDF DROP UDF106;
ALTER TABLE STAGE_SCI_LE_UDF DROP UDF106;
ALTER TABLE SCI_LE_UDF DROP UDF107;
ALTER TABLE STAGE_SCI_LE_UDF DROP UDF107;
ALTER TABLE SCI_LE_UDF DROP UDF108;
ALTER TABLE STAGE_SCI_LE_UDF DROP UDF108;
ALTER TABLE SCI_LE_UDF DROP UDF109;
ALTER TABLE STAGE_SCI_LE_UDF DROP UDF109;
ALTER TABLE SCI_LE_UDF DROP UDF110;
ALTER TABLE STAGE_SCI_LE_UDF DROP UDF110;
ALTER TABLE SCI_LE_UDF DROP UDF111;
ALTER TABLE STAGE_SCI_LE_UDF DROP UDF111;
ALTER TABLE SCI_LE_UDF DROP UDF112;
ALTER TABLE STAGE_SCI_LE_UDF DROP UDF112;
ALTER TABLE SCI_LE_UDF DROP UDF113;
ALTER TABLE STAGE_SCI_LE_UDF DROP UDF113;
ALTER TABLE SCI_LE_UDF DROP UDF114;
ALTER TABLE STAGE_SCI_LE_UDF DROP UDF114;
ALTER TABLE SCI_LE_UDF DROP UDF115;
ALTER TABLE STAGE_SCI_LE_UDF DROP UDF115;
ALTER TABLE SCI_LE_UDF DROP UDF116;
ALTER TABLE STAGE_SCI_LE_UDF DROP UDF116;
ALTER TABLE SCI_LE_UDF DROP UDF117;
ALTER TABLE STAGE_SCI_LE_UDF DROP UDF117;
ALTER TABLE SCI_LE_UDF DROP UDF118;
ALTER TABLE STAGE_SCI_LE_UDF DROP UDF118;
ALTER TABLE SCI_LE_UDF DROP UDF119;
ALTER TABLE STAGE_SCI_LE_UDF DROP UDF119;
ALTER TABLE SCI_LE_UDF DROP UDF120;
ALTER TABLE STAGE_SCI_LE_UDF DROP UDF120;

SET DEFINE ON;
COMMIT;


