<%@ page import="java.util.ArrayList,
				 java.util.List,
                 com.integrosys.base.techinfra.util.DateUtil,
                 com.integrosys.cms.ui.common.CommonCodeList,
                 com.integrosys.cms.app.common.constant.ICMSConstant"%>
<%
/**
 * Copyright Integro Technologies Pte Ltd
 * $Header: /home/cms2/cvsroot/cms2/public_html/ccglobal/global_doc_checklist.jsp,v 1.8 2006/10/27 08:13:10 hmbao Exp $
 * @author $Author: hmbao $<br>
 * @version $Revision: 1.8 $
 * @since $Date: 2006/10/27 08:13:10 $
 * Tag: $Name:  $
 */
 %>
<%@ taglib uri="/WEB-INF/struts-bean.tld" prefix="bean" %>
<%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %>
<%@ taglib uri="/WEB-INF/struts-logic.tld" prefix="logic" %>
<%@ taglib uri="/WEB-INF/IntegroTag.tld" prefix="integro" %>


<%
    int sno = 0;
    boolean viewOnly = false;
    if(request.getParameter("view")!=null &&request.getParameter("view").equals("view")){
        viewOnly=true;
    }
    
%>



<html><!-- InstanceBegin template="/Templates/ContentPage.dwt" codeOutsideHTMLIsLocked="false" -->
<head>
<!-- InstanceBeginEditable name="doctitle" -->
<title>Untitled Document</title>
<!-- InstanceEndEditable -->

<!-- InstanceBeginEditable name="CssStyle" -->

<!-- InstanceEndEditable -->
<!-- InstanceBeginEditable name="head" -->
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}

function refreshContent() {
	window.location="CCDocTemp(sscmaker,corp&eng).htm";
	//parent.location=".htm";
}

function MM_openBrWindow(theURL,winName,features) { //v2.0
    window.open(theURL,winName,features);
}

function reportPop()
{
	alert('Yellow Jello');
	MM_openBrWindow('bfl/reminder_afl.jsp','winOpen','scrollbars=yes,toolbar=yes,menubar=yes,resizable=yes,width=760,height=400,left=5,top=5');
}

function gotopage(aLocation) {
	window.location = aLocation ;
}

function MM_jumpMenu(selObj,docTrxID){ //v3.0
  if(selObj.selectedIndex == 0){
    return ;
  }
  if(selObj.selectedIndex == 1){
    document.forms[0].event.value="edit_doc_item";
    document.forms[0].docTrxID.value=docTrxID;
    document.forms[0].submit();
  }

}

function goToPage() {
    document.forms[0].event.value="prepare_create_doc_item";
    document.forms[0].submit();
}

function generateLI(sno)
{
	if(sno == 1)
	{
		document.forms[0].checklistId.value=document.forms[0].checklistID1.value;
		document.forms[0].template.value="LI_INSURER";
	}
	else if(sno == 2)
	{
		document.forms[0].checklistId.value=document.forms[0].checklistID2.value;
		document.forms[0].template.value="LI_SOLICITOR";
	}
	else if(sno == 3)
	{
		document.forms[0].checklistId.value=document.forms[0].checklistID3.value;
		document.forms[0].template.value="LI_VALUER";
	}

	if(document.forms[0].checklistId.value.length != 0)
	{
		var params1 = 'checklistId='+document.forms[0].checklistId.value;
		var params2 = 'template='+document.forms[0].template.value;
	
		var url = 'GenerateLIDoc.do?event=generate_li';
		url = url + '&'+params1 + '&' +params2;

		MM_openBrWindow(url,'winOpen','scrollbars=yes,toolbar=yes,menubar=yes,resizable=yes,width=760,height=400,left=5,top=5');
	}
	else
		alert("No checklist has been selected. Please maintain a checklist before generating");
	
}
//-->
</script>
<!-- InstanceEndEditable -->
</head>

<body>
<html:form action="GenerateLI.do">

<input type="hidden" name="event" />
<input type="hidden" name="checklistId" />
<input type="hidden" name="template" />
<!-- InstanceBeginEditable name="Content" -->
<table width="90%" border="0" align="center" cellpadding="0" cellspacing="0" class="tblFormSection" style="margin-top:10px">
  <thead>
    <tr>
      <td> <h3>Generate Letter Of Reminder / Instruction</h3></td>
      <td valign="baseline" align="right" width="10%">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="2"><hr /> </td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td colspan="2">
      <table  width="100%" border="0" cellpadding="0" cellspacing="0" class="tblinfo" style="margin-top:0">
        <thead>
        <tr>
          <td rowspan="2" width="4%">S/N</td>
          <td rowspan="2" width="50%">Document Name</td>
          <td rowspan="2" width="4%">Date of First Generation</td>
          <td rowspan="2" width="3%">Date of Subsequence Generation</td>
          <td colspan="2" width="14%">Generated By</td>
		  <td rowspan="2" width="6%">Checklist ID</td>
          <td rowspan="2" width="10%">Action</td>
        </tr>
        </thead>
        
        <logic:present name="genList"  scope="request" >
        	<logic:iterate id="OB" name="genList"  type="com.integrosys.cms.app.generateli.bus.OBLiDoc"  scope="request" >
				<%
					
					String rowClass="";
					int index = 0;
				    sno++;
				    if(sno%2!=0){
				       rowClass="odd";
				    }else{
				       rowClass="even";
				    }
				    
				    if(OB.getLiTemplateName().indexOf("Insurer") > 0)
				    	index = 1;
				    else if(OB.getLiTemplateName().indexOf("Solicitor") > 0)
				    	index = 2;
				    else if(OB.getLiTemplateName().indexOf("Valuer") > 0)
				    	index = 3;
				    else
				    	index = sno;

				  %>
			  <tbody>
			  <tr class="<%=rowClass%>">
			 	<td rowspan="2" width="4%"><%=(sno)%></td>
	         	<td rowspan="2" width="50%"><bean:write name="OB" property="liTemplateName" /></td>
	         	<td rowspan="2" width="4%" nowrap>&nbsp;<integro:empty-if-null value='<%=OB.getFirstGenDate()%>'/></td>
	         	<td rowspan="2" width="3%" nowrap>&nbsp;<integro:empty-if-null value='<%=OB.getLastGenDate()%>'/></td>
	         	<td colspan="2" width="14%">&nbsp;<bean:write name="OB" property="generatedBy" /></td>
		  		<td rowspan="2" width="6%">
		  			
		  			<select name="checklistID<%=index%>" id="checklistID<%=index%>">
		  			<option value="">Select a checklist</option>
		  			<logic:present name="colChkLst"  scope="request" >
		  				<logic:iterate id="OBChk" name="colChkLst"  type="com.integrosys.cms.app.checklist.bus.CollateralCheckListSummary"  scope="request" >
		  					<option value="<%=OBChk.getCheckListID()%>"><%=OBChk.getCheckListID()%></option>
		  				</logic:iterate>
		  			</logic:present>
		  			</select>
		  		</td>
	         	<td rowspan="2" width="10%"><a href="javascript:generateLI(<%=index%>);">Generate</a></td>
	         </tr>
	         </tbody>
         	</logic:iterate>
        </logic:present>
        <logic:notPresent name="genList">
            <tbody>
			  <tr class="odd">
			 	<td rowspan="2" width="4%">1</td>
	         	<td rowspan="2" width="50%">Letter of Instruction to Solicitors</td>
	         	<td rowspan="2" width="4%" nowrap>&nbsp;</td>
	         	<td rowspan="2" width="3%" nowrap>&nbsp;</td>
	         	<td colspan="2" width="14%">&nbsp;</td>
		  		<td rowspan="2" width="6%">
		  			<select name="checklistID2" id="checklistID2">
		  				<option value="">Select a checklist</option>
		  			<logic:present name="colChkLst"  scope="request" >
		  				
		  				<logic:iterate id="OBChk" name="colChkLst"  type="com.integrosys.cms.app.checklist.bus.CollateralCheckListSummary"  scope="request" >
		  					<option value="<%=OBChk.getCollateralRef()%>"><%=OBChk.getCollateralRef()%></option>
		  				</logic:iterate>
		  			</logic:present>
		  			</select>
		  		</td>
	         	<td rowspan="2" width="10%">
	         		<logic:present name="colChkLst"  scope="request" >
	         		&nbsp;<a href="javascript:generateLI(2);">Generate</a>
	         		</logic:present>
	         	</td>
	         </tr>
	         </tbody>
			  <tbody>
			  <tr class="even">
			 	<td rowspan="2" width="4%">2</td>
	         	<td rowspan="2" width="50%">Letter of Instruction to Valuers</td>
	         	<td rowspan="2" width="4%" nowrap>&nbsp;</td>
	         	<td rowspan="2" width="3%" nowrap>&nbsp;</td>
	         	<td colspan="2" width="14%">&nbsp;</td>
		  		<td rowspan="2" width="6%">
		  			<select name="checklistID3" id="checklistID3">
		  				<option value="">Select a checklist</option>
		  			<logic:present name="colChkLst"  scope="request" >
		  				<logic:iterate id="OBChk" name="colChkLst"  type="com.integrosys.cms.app.checklist.bus.CollateralCheckListSummary"  scope="request" >
		  					<option value="<%=OBChk.getCollateralRef()%>"><%=OBChk.getCollateralRef()%></option>
		  				</logic:iterate>
		  			</logic:present>
		  			</select>
		  		</td>
	         	<td rowspan="2" width="10%">
	         		<logic:present name="colChkLst"  scope="request" >
	         		&nbsp;<a href="javascript:generateLI(3);">Generate</a>
	         		</logic:present>
	         	</td>
	         </tr>
	         </tbody>
			  <tbody>
			  <tr class="odd">
			 	<td rowspan="2" width="4%">3</td>
	         	<td rowspan="2" width="50%">Letter of Instruction to Insurers</td>
	         	<td rowspan="2" width="4%" nowrap>&nbsp;</td>
	         	<td rowspan="2" width="3%" nowrap>&nbsp;</td>
	         	<td colspan="2" width="14%">&nbsp;</td>
		  		<td rowspan="2" width="6%">
		  			<select name="checklistID1" id="checklistID1">
		  			<logic:present name="colChkLst"  scope="request" >
		  				<option value="">Select a checklist</option>
		  				<logic:iterate id="OBChk" name="colChkLst"  type="com.integrosys.cms.app.checklist.bus.CollateralCheckListSummary"  scope="request" >
		  					<option value="<%=OBChk.getCollateralRef()%>"><%=OBChk.getCollateralRef()%></option>
		  				</logic:iterate>
		  			</logic:present>
		  			</select>
		  		</td>
	         	<td rowspan="2" width="10%">
	         		<logic:present name="colChkLst"  scope="request" >
	         		&nbsp;<a href="javascript:generateLI(1);">Generate</a>
	         		</logic:present>
	         	</td>
	         </tr>
	         </tbody>
        </logic:notPresent>
</table>
</td>
</tr>
</tbody>
</table>
</html:form>

<!-- InstanceEndEditable -->
</body>
<!-- InstanceEnd --></html>
