LOAD DATA
INFILE 'FILES\HDFC bank branches.csv'
 "str '~~~'"
BADFILE 'PARTIAL_ERROR_LOG\HDFC bank branches.bad'
DISCARDFILE 'PARTIAL_ERROR_LOG\HDFC bank branches.dsc'
DISCARDMAX 1241513983
APPEND INTO TABLE MIG_CMS_SYSTEM_BANK_BRANCH
FIELDS TERMINATED BY '|||'
TRAILING NULLCOLS
(
BANKID "REPLACE(REPLACE(DECODE(UPPER(:BANKID),'NULL',NULL,:BANKID), CHR(10),''), CHR(13),'')",
BANKNAME "DECODE(UPPER(:BANKNAME),'NULL',NULL,:BANKNAME)",
BRANCHCD "DECODE(UPPER(:BRANCHCD),'NULL',NULL,:BRANCHCD)",
BRANCHNAME "DECODE(UPPER(:BRANCHNAME),'NULL',NULL,:BRANCHNAME)",
RBIBANKCODE "DECODE(UPPER(:RBIBANKCODE),'NULL',NULL,:RBIBANKCODE)",
MAINBRANCH"DECODE(UPPER(:MAINBRANCH),'NULL',NULL,:MAINBRANCH)",
LINKEDTOHUB "DECODE(UPPER(:LINKEDTOHUB),'NULL',NULL,:LINKEDTOHUB)",
ISVAULT "DECODE(UPPER(:ISVAULT),'NULL',NULL,:ISVAULT)",
CUSTODIAN1 "DECODE(UPPER(:CUSTODIAN1),'NULL',NULL,:CUSTODIAN1)",
CUSTODIAN2 "DECODE(UPPER(:CUSTODIAN2),'NULL',NULL,:CUSTODIAN2)",
BRANCHADDRESS "DECODE(UPPER(:BRANCHADDRESS),'NULL',NULL,:BRANCHADDRESS)",
CITYID "DECODE(UPPER(:CITYID),'NULL',NULL,:CITYID)",
REGIONNAME "DECODE(UPPER(:REGIONNAME),'NULL',NULL,:REGIONNAME)",
STATENAME "DECODE(UPPER(:STATENAME),'NULL',NULL,:STATENAME)",
TELNO1 "DECODE(UPPER(:TELNO1),'NULL',NULL,:TELNO1)",
TELNO2 "DECODE(UPPER(:TELNO2),'NULL',NULL,:TELNO2)",
TELNO3 "DECODE(UPPER(:TELNO3),'NULL',NULL,:TELNO3)",
FAXNO "DECODE(UPPER(:FAXNO),'NULL',NULL,:FAXNO)",
COUNTRY "DECODE(UPPER(:COUNTRY),'NULL',NULL,:COUNTRY)",
BANKSEMAILID "DECODE(UPPER(:BANKSEMAILID),'NULL',NULL,:BANKSEMAILID)"
)