--------------------------------
--- CMS_FUNCTION_ACCESS Entries 
--------------------------------

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000101,'RelationshipMgr','maker_submit_create_relationship_mgr',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000102,'RelationshipMgr','prepare_create_relationship_mgr',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000103,'RelationshipMgr','prepare_maker_submit_edit',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000104,'RelationshipMgr','prepare_maker_submit_remove',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000105,'RelationshipMgr','view_relationship_mgr_by_index',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000106,'RelationshipMgr','checker_approve_edit',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000107,'RelationshipMgr','checker_edit_read',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000108,'RelationshipMgr','checker_process_create',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000109,'RelationshipMgr','checker_process_delete',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000110,'RelationshipMgr','checker_process_edit',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000111,'RelationshipMgr','checker_reject_edit',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000112,'RelationshipMgr','maker_confirm_close',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000113,'RelationshipMgr','maker_confirm_resubmit_edit',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000114,'RelationshipMgr','maker_edit_RelationshipMgr',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000115,'RelationshipMgr','maker_prepare_close',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000116,'RelationshipMgr','maker_prepare_close',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000117,'RelationshipMgr','maker_prepare_resubmit',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000118,'RelationshipMgr','maker_prepare_resubmit_create',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000119,'RelationshipMgr','maker_submit_edit',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000120,'RelationshipMgr','maker_submit_remove',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000121,'RelationshipMgr','rejected_delete_read',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000122,'RelationshipMgr','rejected_delete_read',7);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000123,'RelationshipMgr','rejected_read',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000124,'RelationshipMgr','search_relationship_mgr',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000125,'RelationshipMgr','view_relationship_mgr',6);
	
	
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000126,'RelationshipMgr','maker_save_create_relationship_mgr',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000127,'RelationshipMgr','maker_update_save_process',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000128,'RelationshipMgr','maker_draft_close_process',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000129,'RelationshipMgr','maker_confirm_draft_close',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000130,'RelationshipMgr','maker_confirm_resubmit_draft',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000131,'RelationshipMgr','maker_save_update_relationship_mgr',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000132,'RelationshipMgr','maker_save_process',6);

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES(229000133,'RelationshipMgr','maker_confirm_resubmit_update',6);	
	
-----------------------------------
--- CMS_STATEMATRIX_ACTION Entries 
-----------------------------------

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9101,6,'Process','RelationshipMgr.do?event=maker_prepare_resubmit&TrxId=','RelationshipMgr.do?event=to_track&TrxId=');

insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9102,7,'Process','RelationshipMgr.do?event=checker_process_create&TrxId=','');

insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9106,7,'Process','RelationshipMgr.do?event=checker_edit_read&TrxId=','');

insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9107,6,'Process','RelationshipMgr.do?event=maker_prepare_resubmit_create&TrxId=','');

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9108,6,'Process','RelationshipMgr.do?event=maker_prepare_resubmit_create&TrxId=','');

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9111,6,'Close','RelationshipMgr.do?event=maker_prepare_close&TrxId=','');

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9113,7,'Process','RelationshipMgr.do?event=checker_process_delete&TrxId=','');

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9116,7,'Process','RelationshipMgr.do?event=checker_process_edit&TrxId=','RelationshipMgr.do?event=to_track&TrxId=');


insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7541,8,'Process','RelationshipMgr.do?event=maker_prepare_resubmit_create&TrxId=',null);

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7531,8,'Process','RelationshipMgr.do?event=maker_prepare_resubmit_delete&TrxId=',null);

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9130,8,'Process','RelationshipMgr.do?event=maker_save_process&TrxId=',null);

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9131,8,'Process','RelationshipMgr.do?event=maker_save_process&TrxId=',null);

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9133,8,'Process','RelationshipMgr.do?event=maker_update_save_process&TrxId=',null);

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (9134,8,'Close','RelationshipMgr.do?event=maker_draft_close_process&TrxId=',null);


-----------------------------------
--- CMS_TRX_TOTRACK Entries 
-----------------------------------

insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values ('RELATIONSHIP_MGR','RelationshipMgr.do?event=rejected_delete_read&toTrack=yes&TrxId=','DELETED','Deleted','Maintain Relationship Manager',null,null);
insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values ('RELATIONSHIP_MGR','RelationshipMgr.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_CREATE','Pending Create','Maintain Relationship Manager',null,null);
insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values ('RELATIONSHIP_MGR','RelationshipMgr.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_DELETE','Pending Delete','Maintain Relationship Manager',null,null);
insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values ('RELATIONSHIP_MGR','RelationshipMgr.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_UPDATE','Pending Update','Maintain Relationship Manager',null,null);
insert into CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values ('RELATIONSHIP_MGR','RelationshipMgr.do?event=rejected_delete_read&toTrack=yes&TrxId=','REJECTED','Rejected','Maintain Relationship Manager',null,null);


insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values ('RELATIONSHIP_MGR','RelationshipMgr.do?event=rejected_delete_read&toTrack=yes&TrxId=','DRAFT','Draft','Maintain Relationship Manager',null,null);

-----------------------------------
--- TR_STATE_MATRIX Entries 
-----------------------------------

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9101,'RELATIONSHIP_MGR','EDIT_REJECTED_DELETE','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9102,'RELATIONSHIP_MGR','CREATE_RELATIONSHIP_MGR','PENDING_CREATE','PENDING_CREATE','PENDING_CREATE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9103,'RELATIONSHIP_MGR','APROVE_RELATIONSHIP_MGR','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9104,'RELATIONSHIP_MGR','UPDATE_RELATIONSHIP_MGR','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9105,'RELATIONSHIP_MGR','APPROVE_CREATE_RELATIONSHIP_MGR','PENDING_CREATE','ACTIVE','ACTIVE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9106,'RELATIONSHIP_MGR','REJECT_RELATIONSHIP_MGR','PENDING_UPDATE','REJECTED','REJECTED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9107,'RELATIONSHIP_MGR','EDIT_REJECTED_UPDATE_RELATIONSHIP_MGR','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9108,'RELATIONSHIP_MGR','CLOSE_REJECTED_UPDATE_RELATIONSHIP_MGR','REJECTED','CLOSED','CLOSED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9109,'RELATIONSHIP_MGR','REJECT_RELATIONSHIP_MGR','PENDING_CREATE','REJECTED','REJECTED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9110,'RELATIONSHIP_MGR','CLOSE_REJECTED_CREATE_RELATIONSHIP_MGR','REJECTED','CLOSED','CLOSED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9111,'RELATIONSHIP_MGR','EDIT_REJECTED_CREATE_RELATIONSHIP_MGR','REJECTED','PENDING_CREATE','PENDING_CREATE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9112,'RELATIONSHIP_MGR','DELETE_RELATIONSHIP_MGR','ACTIVE','PENDING_DELETE','PENDING_DELETE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9113,'RELATIONSHIP_MGR','DELETE_RELATIONSHIP_MGR','PENDING_DELETE','DELETED','DELETED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9114,'RELATIONSHIP_MGR','REJECT_RELATIONSHIP_MGR','PENDING_DELETE','REJECTED','REJECTED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9115,'RELATIONSHIP_MGR','CLOSE_REJECTED_RELATIONSHIP_MGR','REJECTED','CLOSED','CLOSED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9116,'RELATIONSHIP_MGR','UPDATE_RELATIONSHIP_MGR','PENDING_UPDATE','ACTIVE','PENDING_UPDATE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9117,'RELATIONSHIP_MGR','CHECKER_APPROVE_UPDATE','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9118,'RELATIONSHIP_MGR','CHECKER_APPROVE_DELETE','PENDING_DELETE','DELETED','DELETED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9119,'RELATIONSHIP_MGR','APPROVE_RELATIONSHIP_MGR','PENDING_DELETE','DELETED','DELETED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9120,'RELATIONSHIP_MGR','CHECKER_APPROVE_UPDATE','PENDING_DELETE','DELETED','DELETED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9121,'RELATIONSHIP_MGR','CREATE_RELATIONSHIP_MGR','ND','PENDING_CREATE','PENDING_CREATE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9122,'RELATIONSHIP_MGR','CLOSE_REJECTED_DELETE_RELATIONSHIP_MGR','REJECTED','CLOSED','CLOSED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9123,'RELATIONSHIP_MGR','DELETE_RELATIONSHIP_MGR','CLOSED','PENDING_DELETE','PENDING_DELETE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9124,'RELATIONSHIP_MGR','APPROVE_DELETE_RELATIONSHIP_MGR','PENDING_DELETE','DELETED','DELETED','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9125,'RELATIONSHIP_MGR','CREATE_RELATIONSHIP_MGR','ACTIVE','PENDING_CREATE','PENDING_CREATE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9126,'RELATIONSHIP_MGR','EDIT_REJECTED_DELETE_RELATIONSHIP_MGR','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9127,'RELATIONSHIP_MGR','EDIT_REJECTED_RELATIONSHIP_MGR','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9128,'RELATIONSHIP_MGR','EDIT_REJECTED_RELATIONSHIP_MGR','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9129,'RELATIONSHIP_MGR_BRANCH','EDIT_REJECTED_DELETE','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');

insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9135,'RELATIONSHIP_MGR','CLOSE_CREATE_RELATIONSHIP_MGR','DRAFT','ACTIVE','ACTIVE','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9136,'RELATIONSHIP_MGR','SAVE_UPDATE_RELATIONSHIP_MGR','ACTIVE','DRAFT','DRAFT','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9137,'RELATIONSHIP_MGR','SAVE_UPDATE_RELATIONSHIP_MGR','CLOSED','DRAFT','DRAFT','1','1');
insert into TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (9138,'RELATIONSHIP_MGR','SAVE_UPDATE_RELATIONSHIP_MGR','DRAFT','PENDING_UPDATE','PENDING_UPDATE','1','1');
