-----------------------------
-- Cleanup
-----------------------------
DELETE FROM MIG_QC_REPORT;

-----------------------------
-- Customer
-----------------------------
-- CU001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CU001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CU001', 'ARBS', 'CU001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CU001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CU001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CU001' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CU001' AND ERROR_CODE = 'TechErrSI002');

-- CU002
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CU002', 'ARBS', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CU002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CU002' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CU002' AND ERROR_CODE = 'TechErrSI002');
	
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'SEMA', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CU002', 'SEMA', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SEMA', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'SEMA', 'CU002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'SEMA', 'CU002' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'SEMA' AND INTERFACE_ID= 'CU002' AND ERROR_CODE = 'TechErrSI002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'FINS', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CU002', 'FINS', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CU002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'FINS', 'CU002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'FINS', 'CU002' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'FINS' AND INTERFACE_ID= 'CU002' AND ERROR_CODE = 'TechErrSI002');

-- CU003
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CU003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CU003', 'ARBS', 'CU003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CU003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CU003');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CU003' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CU003' AND ERROR_CODE = 'TechErrSI002');

-- CU004
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'SEMA', 'CU004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CU004', 'SEMA', 'CU004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SEMA', 'CU004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'SEMA', 'CU004');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'SEMA', 'CU004' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'SEMA' AND INTERFACE_ID= 'CU004' AND ERROR_CODE = 'TechErrSI002');

-- CU005
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'BOST', 'CU005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CU005', 'BOST', 'CU005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'CU005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'BOST', 'CU005');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'BOST', 'CU005' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'BOST' AND INTERFACE_ID= 'CU005' AND ERROR_CODE = 'TechErrSI002');

-- CU006
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'FINS', 'CU006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CU006', 'FINS', 'CU006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CU006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'FINS', 'CU006');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'FINS', 'CU006' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'FINS' AND INTERFACE_ID= 'CU006' AND ERROR_CODE = 'TechErrSI002');

-- CU007
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'FINS', 'CU007');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CU007', 'FINS', 'CU007');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CU007');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'FINS', 'CU007');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'FINS', 'CU007' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'FINS' AND INTERFACE_ID= 'CU007' AND ERROR_CODE = 'TechErrSI002');
	
	
-----------------------------
-- Credit Application (CA)
-----------------------------
-- CA001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CA001', 'ARBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CA001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CA001' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CA001' AND ERROR_CODE = 'TechErrSI002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'SEMA', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CA001', 'SEMA', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SEMA', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'SEMA', 'CA001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'SEMA', 'CA001' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'SEMA' AND INTERFACE_ID= 'CA001' AND ERROR_CODE = 'TechErrSI002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'BOST', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CA001', 'BOST', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'BOST', 'CA001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'BOST', 'CA001' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'BOST' AND INTERFACE_ID= 'CA001' AND ERROR_CODE = 'TechErrSI002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'FINS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CA001', 'FINS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'FINS', 'CA001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'FINS', 'CA001' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'FINS' AND INTERFACE_ID= 'CA001' AND ERROR_CODE = 'TechErrSI002');
	
-- CA002
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CA002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CA002', 'ARBS', 'CA002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CA002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CA002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CA002' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CA002' AND ERROR_CODE = 'TechErrSI002');

-- CA003
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CA003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CA003', 'ARBS', 'CA003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CA003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CA003');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CA003' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CA003' AND ERROR_CODE = 'TechErrSI002');

-- CA004
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CA004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CA004', 'ARBS', 'CA004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CA004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CA004');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CA004' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CA004' AND ERROR_CODE = 'TechErrSI002');

-- CA005
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CA005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CA005', 'ARBS', 'CA005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CA005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CA005');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CA005' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CA005' AND ERROR_CODE = 'TechErrSI002');

-- CA006
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'TSPR', 'CA006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CA006', 'TSPR', 'CA006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'TSPR', 'CA006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'TSPR', 'CA006');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'TSPR', 'CA006' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'TSPR' AND INTERFACE_ID= 'CA006' AND ERROR_CODE = 'TechErrSI002');

-- CA007 N/A

-- CA008
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'TSPR', 'CA008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CA008', 'TSPR', 'CA008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'TSPR', 'CA008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'TSPR', 'CA008');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'TSPR', 'CA008' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'TSPR' AND INTERFACE_ID= 'CA008' AND ERROR_CODE = 'TechErrSI002');

-- CA009 N/A

-- CA010
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'TSPR', 'CA010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CA008', 'TSPR', 'CA010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'TSPR', 'CA010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'TSPR', 'CA010');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'TSPR', 'CA010' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'TSPR' AND INTERFACE_ID= 'CA010' AND ERROR_CODE = 'TechErrSI002');

-- CA011 N/A

-- CA012
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'SEMA', 'CA012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CA012', 'SEMA', 'CA012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SEMA', 'CA012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'SEMA', 'CA012');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'SEMA', 'CA012' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'SEMA' AND INTERFACE_ID= 'CA012' AND ERROR_CODE = 'TechErrSI002');

-- CA015
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'BOST', 'CA015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CA015', 'BOST', 'CA015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'CA015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'BOST', 'CA015');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'BOST', 'CA015' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'BOST' AND INTERFACE_ID= 'CA015' AND ERROR_CODE = 'TechErrSI002');

-- CA016
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'QUAN', 'CA016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CA016', 'QUAN', 'CA016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'QUAN', 'CA016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'QUAN', 'CA016');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'QUAN', 'CA016' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'QUAN' AND INTERFACE_ID= 'CA016' AND ERROR_CODE = 'TechErrSI002');

-- CA017
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'FINS', 'CA017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CA017', 'FINS', 'CA017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CA017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'FINS', 'CA017');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'FINS', 'CA017' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'FINS' AND INTERFACE_ID= 'CA017' AND ERROR_CODE = 'TechErrSI002');

-- CA018
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'FINS', 'CA018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CA018', 'FINS', 'CA018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CA018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'FINS', 'CA018');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'FINS', 'CA018' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'FINS' AND INTERFACE_ID= 'CA018' AND ERROR_CODE = 'TechErrSI002');

-- CA019
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CA019');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CA019', 'ARBS', 'CA019');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CA019');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CA019');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CA019' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CA019' AND ERROR_CODE = 'TechErrSI002');


-----------------------------
-- Collateral
-----------------------------
-- CO001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CO001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO001', 'ARBS', 'CO001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CO001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CO001' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CO001' AND ERROR_CODE = 'TechErrSI002');

-- CO002
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CO002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO002', 'ARBS', 'CO002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CO002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CO002' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CO002' AND ERROR_CODE = 'TechErrSI002');

-- CO003
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CO003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO003', 'ARBS', 'CO003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CO003');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CO003' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CO003' AND ERROR_CODE = 'TechErrSI002');

-- CO004
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CO004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO004', 'ARBS', 'CO004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CO004');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CO004' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CO004' AND ERROR_CODE = 'TechErrSI002');

-- CO005
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CO005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO005', 'ARBS', 'CO005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CO005');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CO005' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CO005' AND ERROR_CODE = 'TechErrSI002');

-- CO006
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CO006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO006', 'ARBS', 'CO006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO006');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CO006');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CO006' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CO006' AND ERROR_CODE = 'TechErrSI002');

-- CO007
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CO007');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO007', 'ARBS', 'CO007');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO007');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CO007');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CO007' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CO007' AND ERROR_CODE = 'TechErrSI002');

-- CO008
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CO008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO008', 'ARBS', 'CO008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CO008');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CO008' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CO008' AND ERROR_CODE = 'TechErrSI002');

-- CO009
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CO009');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO009', 'ARBS', 'CO009');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO009');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CO009');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CO009' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CO009' AND ERROR_CODE = 'TechErrSI002');

-- CO010
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CO010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO010', 'ARBS', 'CO010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CO010');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CO010' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CO010' AND ERROR_CODE = 'TechErrSI002');

-- CO011
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CO011');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO011', 'ARBS', 'CO011');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO011');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CO011');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CO011' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CO011' AND ERROR_CODE = 'TechErrSI002');

-- CO012
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CO012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO012', 'ARBS', 'CO012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CO012');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CO012' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CO012' AND ERROR_CODE = 'TechErrSI002');

-- CO013
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CO013');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO013', 'ARBS', 'CO013');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO013');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CO013');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CO013' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CO013' AND ERROR_CODE = 'TechErrSI002');

-- CO014
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CO014');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO014', 'ARBS', 'CO014');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO014');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CO014');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CO014' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CO014' AND ERROR_CODE = 'TechErrSI002');

-- CO015
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CO015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO015', 'ARBS', 'CO015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CO015');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CO015' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CO015' AND ERROR_CODE = 'TechErrSI002');

-- CO016
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CO016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO016', 'ARBS', 'CO016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CO016');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CO016' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CO016' AND ERROR_CODE = 'TechErrSI002');

-- CO017
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CO017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO017', 'ARBS', 'CO017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CO017');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CO017' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CO017' AND ERROR_CODE = 'TechErrSI002');

-- CO018
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'CO018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO018', 'ARBS', 'CO018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CO018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'CO018');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CO018' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'CO018' AND ERROR_CODE = 'TechErrSI002');

-- CO020
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'SEMA', 'CO020');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO020', 'SEMA', 'CO020');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SEMA', 'CO020');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'SEMA', 'CO020');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'SEMA', 'CO020' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'SEMA' AND INTERFACE_ID= 'CO020' AND ERROR_CODE = 'TechErrSI002');

-- CO021
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'TSPR', 'CO021');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO021', 'TSPR', 'CO021');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'TSPR', 'CO021');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'TSPR', 'CO021');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'TSPR', 'CO021' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'TSPR' AND INTERFACE_ID= 'CO021' AND ERROR_CODE = 'TechErrSI002');

-- CO022
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'BOST', 'CO022');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO022', 'BOST', 'CO022');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'CO022');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'BOST', 'CO022');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'BOST', 'CO022' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'BOST' AND INTERFACE_ID= 'CO022' AND ERROR_CODE = 'TechErrSI002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'STBG', 'CO022');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO022', 'STBG', 'CO022');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'STBG', 'CO022');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'STBG', 'CO022');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'STBG', 'CO022' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'STBG' AND INTERFACE_ID= 'CO022' AND ERROR_CODE = 'TechErrSI002');

-- CO023
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'BOST', 'CO023');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO023', 'BOST', 'CO023');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'CO023');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'BOST', 'CO023');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'BOST', 'CO023' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'BOST' AND INTERFACE_ID= 'CO023' AND ERROR_CODE = 'TechErrSI002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'STBG', 'CO023');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO023', 'STBG', 'CO023');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'STBG', 'CO023');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'STBG', 'CO023');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'STBG', 'CO023' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'STBG' AND INTERFACE_ID= 'CO023' AND ERROR_CODE = 'TechErrSI002');

-- CO024
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'STBG', 'CO024');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO024', 'STBG', 'CO024');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'STBG', 'CO024');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'STBG', 'CO024');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'STBG', 'CO024' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'STBG' AND INTERFACE_ID= 'CO024' AND ERROR_CODE = 'TechErrSI002');

-- CO025
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'BOST', 'CO025');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: CO025', 'BOST', 'CO025');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'CO025');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'BOST', 'CO025');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'BOST', 'CO025' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'BOST' AND INTERFACE_ID= 'CO025' AND ERROR_CODE = 'TechErrSI002');


-----------------------------
-- Price Feed
-----------------------------
-- PF001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'STBG', 'PF001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: PF001', 'STBG', 'PF001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'STBG', 'PF001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'STBG', 'PF001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'STBG', 'PF001' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'STBG' AND INTERFACE_ID= 'PF001' AND ERROR_CODE = 'TechErrSI002');

-- PF002
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'STBG', 'PF002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: PF002', 'STBG', 'PF002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'STBG', 'PF002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'STBG', 'PF002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'STBG', 'PF002' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'STBG' AND INTERFACE_ID= 'PF002' AND ERROR_CODE = 'TechErrSI002');

-- PF003
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'ARBS', 'PF003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: PF003', 'ARBS', 'PF003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'PF003');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'ARBS', 'PF003');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'PF003' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'ARBS' AND INTERFACE_ID= 'PF003' AND ERROR_CODE = 'TechErrSI002');


-----------------------------
-- Counter Share Holding
-----------------------------
-- SH001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'BOST', 'SH001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: SH001', 'BOST', 'SH001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'SH001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'BOST', 'SH001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'BOST', 'SH001' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'BOST' AND INTERFACE_ID= 'SH001' AND ERROR_CODE = 'TechErrSI002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'QC Report 3d for Migration', 'STBG', 'SH001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report for migration template: SH001', 'STBG', 'SH001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'STBG', 'SH001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrTech', 'CIF / AA number / Facility ID / Security ID / ID / Key , Missing Mandatory data', 'STBG', 'SH001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrTech', '''' || COALESCE(KEY1_VALUE,'-') || ',' || ERROR_MSG, 'STBG', 'SH001' FROM SI_ERROR_LOG WHERE SYSTEM_ID = 'STBG' AND INTERFACE_ID= 'SH001' AND ERROR_CODE = 'TechErrSI002');

COMMIT;
