--In QC DB -Seq is 17. To give bank release need to ask where this field has to be placed.
--For bank its 97
Insert into CMS_UDF
(ID,VERSION_TIME,MODULEID,MODULENAME,FIELDNAME,FIELDTYPEID,FIELDTYPE,OPTIONS,SEQUENCE,MANDATORY,NUMERIC_LENGTH,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE,DEPRECATED,STATUS) 
values (20210518000000000,0,1,'PARTY','Borrower SCM Flag',3,'RADIO BUTTON','Yes,No',17,'on',null,'CPU_ADM',to_timestamp(sysdate,'DD-MM-RR HH12:MI:SSXFF AM'),'CPU_ADM',to_timestamp(sysdate,'DD-MM-RR HH12:MI:SSXFF AM'),'N','ACTIVE');


Insert into CMS_STAGE_UDF (ID,VERSION_TIME,MODULEID,MODULENAME,FIELDNAME,FIELDTYPEID,FIELDTYPE,OPTIONS,SEQUENCE,STATUS,MANDATORY,NUMERIC_LENGTH,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE,DEPRECATED) 
values (20210518000000000,0,1,'PARTY','Borrower SCM Flag',3,'RADIO BUTTON','Yes,No',17,'ACTIVE','on',null,'CPU_ADM',to_timestamp(sysdate,'DD-MM-RR HH12:MI:SSXFF AM'),'CPU_ADM',to_timestamp(sysdate,'DD-MM-RR HH12:MI:SSXFF AM'),'N');


--For bank sequence number is 97
Insert into CMS_UDF
(ID,VERSION_TIME,MODULEID,MODULENAME,FIELDNAME,FIELDTYPEID,FIELDTYPE,OPTIONS,SEQUENCE,MANDATORY,NUMERIC_LENGTH,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE,DEPRECATED,STATUS) 
values (20210518000000000,0,1,'PARTY','Borrower SCM Flag',3,'RADIO BUTTON','Yes,No',96,'on',null,'CPU_ADM',to_timestamp(sysdate,'DD-MM-RR HH12:MI:SSXFF AM'),'CPU_ADM',to_timestamp(sysdate,'DD-MM-RR HH12:MI:SSXFF AM'),'N','ACTIVE');


Insert into CMS_STAGE_UDF (ID,VERSION_TIME,MODULEID,MODULENAME,FIELDNAME,FIELDTYPEID,FIELDTYPE,OPTIONS,SEQUENCE,STATUS,MANDATORY,NUMERIC_LENGTH,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE,DEPRECATED) 
values (20210518000000000,0,1,'PARTY','Borrower SCM Flag',3,'RADIO BUTTON','Yes,No',96,'ACTIVE','on',null,'CPU_ADM',to_timestamp(sysdate,'DD-MM-RR HH12:MI:SSXFF AM'),'CPU_ADM',to_timestamp(sysdate,'DD-MM-RR HH12:MI:SSXFF AM'),'N');


commit;