
--------------------------------
--- CMS_FUNCTION_ACCESS Entries 
--------------------------------

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100503,'approval_matrix_list','add',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100504,'approval_matrix_list','addNoop',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100514,'approval_matrix_list','approve',7);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100518,'approval_matrix_list','close',6);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100516,'approval_matrix_list','listCheckerApproveReject',7);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100517,'approval_matrix_list','listMakerClose',6);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100526,'approval_matrix_list','listRead',7);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100519,'approval_matrix_list','listStaging',6);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100521,'approval_matrix_list','listView',6);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100523,'approval_matrix_list','listView',7);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100508,'approval_matrix_list','paginate',6);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100525,'approval_matrix_list','prepare',6);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100501,'approval_matrix_list','read',6);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100524,'approval_matrix_list','read',7);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100512,'approval_matrix_list','readCheckerApproveReject',7);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100513,'approval_matrix_list','readMakerClose',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100502,'approval_matrix_list','readMakerEdit',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100515,'approval_matrix_list','reject',7);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100505,'approval_matrix_list','remove',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100506,'approval_matrix_list','removeNoop',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100507,'approval_matrix_list','save',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100509,'approval_matrix_list','saveNoop',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100510,'approval_matrix_list','submit',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100511,'approval_matrix_list','submitNoop',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100520,'approval_matrix_list','view',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100522,'approval_matrix_list','view',7);

    
--------------------------------
--- TR_STATE_MATRIX Entries 
--------------------------------
    
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (4500,'APROVAL_MATRIX_GROUP','ACTION_MAKER_UPDATE','ACTIVE','DRAFT','DRAFT','1','1');

insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (4501,'APROVAL_MATRIX_GROUP','ACTION_MAKER_SUBMIT','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');

insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (4502,'APROVAL_MATRIX_GROUP','ACTION_MAKER_UPDATE_REJECTED','REJECTED','DRAFT','DRAFT','1','1');

insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (4503,'APROVAL_MATRIX_GROUP','ACTION_MAKER_CLOSE_REJECTED','REJECTED','ACTIVE','ACTIVE','1','1');

insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (4504,'APROVAL_MATRIX_GROUP','ACTION_CHECKER_APPROVE_APROVAL_MATRIX_GROUP','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');

insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (4505,'APROVAL_MATRIX_GROUP','ACTION_CHECKER_REJECT_APROVAL_MATRIX_GROUP','PENDING_UPDATE','REJECTED','REJECTED','1','1');

insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (4506,'APROVAL_MATRIX_GROUP','ACTION_MAKER_UPDATE','DRAFT','DRAFT','DRAFT','1','1');

insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (4507,'APROVAL_MATRIX_GROUP','ACTION_MAKER_SUBMIT','DRAFT','PENDING_UPDATE','PENDING_UPDATE','1','1');

insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (4508,'APROVAL_MATRIX_GROUP','ACTION_MAKER_SUBMIT_REJECTED','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');

insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (4509,'APROVAL_MATRIX_GROUP','ACTION_MAKER_CLOSE_DRAFT','DRAFT','ACTIVE','ACTIVE','1','1');


----------------------------------
--- CMS_STATEMATRIX_ACTION Entries 
----------------------------------


insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
    values (4502,6,'Process','approval_matrix_list.do?event=readMakerEdit'||'&'||'trxId=',null);

insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
    values (4503,6,'Close','approval_matrix_list.do?event=readMakerClose'||'&'||'offset=0'||'&'||'length=10'||'&'||'trxId=',null);

insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
    values (4504,7,'Process','approval_matrix_list.do?event=readCheckerApproveReject'||'&'||'offset=0'||'&'||'length=10'||'&'||'trxId=',null);

insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
    values (4506,6,'Process','approval_matrix_list.do?event=readMakerEdit'||'&'||'offset=0'||'&'||'length=10'||'&'||'trxId=',null);

insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
    values (4509,6,'Close','approval_matrix_list.do?event=readMakerClose'||'&'||'offset=0'||'&'||'length=10'||'&'||'trxId=',null);   
 
    
--------------------------------
--- CMS_TRX_TOTRACK Entries 
--------------------------------

    
insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,    TOTRACK_URL,    CURR_STATE,    USER_STATE,    USER_TRX_TYPE,    FROM_STATE,    TRANSACTION_SUBTYPE) 
    values ('APROVAL_MATRIX_GROUP','approval_matrix_list.do?event=view'||'&'||'trxId=','ACTIVE','Approved','Maintain Approval Matrix','PENDING_UPDATE',NULL);

insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,    TOTRACK_URL,    CURR_STATE,    USER_STATE,    USER_TRX_TYPE,    FROM_STATE,    TRANSACTION_SUBTYPE) 
    values ('APROVAL_MATRIX_GROUP','approval_matrix_list.do?event=view'||'&'||'trxId=','ACTIVE','Closed','Maintain Approval Matrix','DRAFT',NULL);

insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,    TOTRACK_URL,    CURR_STATE,    USER_STATE,    USER_TRX_TYPE,    FROM_STATE,    TRANSACTION_SUBTYPE) 
    values ('APROVAL_MATRIX_GROUP','approval_matrix_list.do?event=view'||'&'||'trxId=','ACTIVE','Closed','Maintain Approval Matrix','REJECTED',NULL);

insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,    TOTRACK_URL,    CURR_STATE,    USER_STATE,    USER_TRX_TYPE,    FROM_STATE,    TRANSACTION_SUBTYPE) 
    values ('APROVAL_MATRIX_GROUP','approval_matrix_list.do?event=view'||'&'||'trxId=','DRAFT','Draft','Maintain Approval Matrix',NULL,NULL);

insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,    TOTRACK_URL,    CURR_STATE,    USER_STATE,    USER_TRX_TYPE,    FROM_STATE,    TRANSACTION_SUBTYPE) 
    values ('APROVAL_MATRIX_GROUP','approval_matrix_list.do?event=view'||'&'||'trxId=','PENDING_UPDATE','Pending Update','Maintain Approval Matrix',NULL,NULL);

insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,    TOTRACK_URL,    CURR_STATE,    USER_STATE,    USER_TRX_TYPE,    FROM_STATE,    TRANSACTION_SUBTYPE) 
    values ('APROVAL_MATRIX_GROUP','approval_matrix_list.do?event=view'||'&'||'trxId=','REJECTED','Rejected','Maintain Approval Matrix',NULL,NULL);    