INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8601,'FACILITY', 'MAKER_CREATE', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8602,'FACILITY', 'MAKER_CREATE', 'DRAFT', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8603,'FACILITY', 'MAKER_CREATE', 'REJECTED_CREATE', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8604,'FACILITY', 'MAKER_UPDATE', 'ACTIVE', 'PENDING_UPDATE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8605,'FACILITY', 'MAKER_UPDATE', 'DRAFT', 'PENDING_UPDATE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8606,'FACILITY', 'MAKER_UPDATE', 'REJECTED_UPDATE', 'PENDING_UPDATE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8607,'FACILITY', 'MAKER_SAVE', 'ND', 'DRAFT', 'DRAFT', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8608,'FACILITY', 'MAKER_SAVE', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8609,'FACILITY', 'MAKER_SAVE', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8610,'FACILITY', 'MAKER_SAVE', 'REJECTED_CREATE', 'DRAFT', 'DRAFT', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8611,'FACILITY', 'MAKER_SAVE', 'REJECTED_UPDATE', 'DRAFT', 'DRAFT', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8612,'FACILITY', 'MAKER_CLOSE_ND', 'REJECTED_CREATE', 'CLOSED', 'CLOSED', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8613,'FACILITY', 'MAKER_CLOSE', 'REJECTED_UPDATE', 'ACTIVE', 'CLOSED', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8614,'FACILITY', 'MAKER_CLOSE', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8615,'FACILITY', 'MAKER_CLOSE_ND', 'DRAFT', 'CLOSED', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8616,'FACILITY', 'CHECKER_APPROVE', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8617,'FACILITY', 'CHECKER_APPROVE', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8618,'FACILITY', 'CHECKER_REJECT', 'PENDING_CREATE', 'REJECTED_CREATE', 'ACTIVE', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8619,'FACILITY', 'CHECKER_REJECT', 'PENDING_UPDATE', 'REJECTED_UPDATE', 'ACTIVE', '1', '1');

-- Andy Wong: Transaction state matrix called in Stp module 
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8620,'FACILITY', 'SYSTEM_APPROVE', 'LOADING', 'ACTIVE', 'IMPLEMENTED', '1', '1');
	
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8621,'FACILITY', 'SYSTEM_REJECT', 'LOADING', 'PENDING_PERFECTION', 'PENDING_PERFECTION', '1', '1');
	
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8622,'FACILITY', 'SYSTEM_UPDATE', 'LOADING', 'PENDING_RETRY', 'PENDING_RETRY', '1', '1');
	
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8623,'FACILITY', 'SYSTEM_APPROVE', 'LOADING_DELETE', 'DELETED', 'DELETED', '1', '1');

INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8624,'FACILITY', 'SYSTEM_REJECT', 'LOADING_DELETE', 'PENDING_PERFECTION', 'PENDING_PERFECTION', '1', '1');
	
INSERT INTO TR_STATE_MATRIX (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) 
	VALUES (8625,'FACILITY', 'SYSTEM_UPDATE', 'LOADING_DELETE', 'PENDING_RETRY', 'PENDING_RETRY', '1', '1');

INSERT INTO tr_state_matrix (SELECT MAX(stateid)+1, 'FACILITY', 'CHECKER_APPROVE_PASS', 'PENDING_CREATE', 'LOADING', 'LOADING', '1', '1' FROM tr_state_matrix WHERE stateins = 'FACILITY');
INSERT INTO tr_state_matrix (SELECT MAX(stateid)+1, 'FACILITY', 'CHECKER_APPROVE_FAIL', 'PENDING_CREATE', 'PENDING_PERFECTION', 'PENDING_PERFECTION', '1', '1' FROM tr_state_matrix WHERE stateins = 'FACILITY');
INSERT INTO tr_state_matrix (SELECT MAX(stateid)+1, 'FACILITY', 'CHECKER_APPROVE_PASS', 'PENDING_RETRY', 'LOADING', 'LOADING', '1', '1' FROM tr_state_matrix WHERE stateins = 'FACILITY');
INSERT INTO tr_state_matrix (SELECT MAX(stateid)+1, 'FACILITY', 'MAKER_UPDATE', 'PENDING_PERFECTION', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1' FROM tr_state_matrix WHERE stateins = 'FACILITY');
INSERT INTO tr_state_matrix (SELECT MAX(stateid)+1, 'FACILITY', 'MAKER_SAVE', 'PENDING_PERFECTION', 'DRAFT', 'DRAFT', '1', '1' FROM tr_state_matrix WHERE stateins = 'FACILITY');
INSERT INTO tr_state_matrix (SELECT MAX(stateid)+1, 'FACILITY', 'CHECKER_APPROVE_PASS', 'PENDING_UPDATE', 'LOADING', 'LOADING', '1', '1' FROM tr_state_matrix WHERE stateins = 'FACILITY');
INSERT INTO tr_state_matrix (SELECT MAX(stateid)+1, 'FACILITY', 'CHECKER_APPROVE_FAIL', 'PENDING_UPDATE', 'PENDING_PERFECTION', 'PENDING_PERFECTION', '1', '1' FROM tr_state_matrix WHERE stateins = 'FACILITY');