CREATE SEQUENCE BATCH_JOB_SEQ AS INTEGER
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 999999
	MINVALUE 1
	CYCLE
	NO CACHE
	NO ORDER;

CREATE TABLE CMS_BATCH_JOB (
    BATCH_ID BIGINT NOT NULL,
    JOB_NAME VARCHAR(50),
    JOB_PARAMETERS VARCHAR(255),
    CLASS_NAME VARCHAR(100),
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    JOB_STATUS VARCHAR(10),
    MESSAGE VARCHAR(4000),
    PRIMARY KEY (BATCH_ID)
) IN "CMS_MEDIUM_DATA" INDEX IN "CMS_INDEX";