LOAD DATA
INFILE 'FILES\Party Group Master.csv'
 "str '~~~'"
BADFILE 'PARTIAL_ERROR_LOG\Party Group Master.bad'
DISCARDFILE 'PARTIAL_ERROR_LOG\Party Group Master.dsc'
DISCARDMAX 1241513983
APPEND INTO TABLE MIG_CMS_PARTY_GROUP
FIELDS TERMINATED BY '|||'
TRAILING NULLCOLS
(
PTYGROUPID "REPLACE(REPLACE(DECODE(UPPER(:PTYGROUPID),'NULL',NULL,:PTYGROUPID), CHR(10),''), CHR(13),'')",
PTYGROUPDESC "DECODE(UPPER(:PTYGROUPDESC),'NULL',NULL,:PTYGROUPDESC)",
GROUPLIMIT "DECODE(UPPER(:GROUPLIMIT),'NULL',NULL,:GROUPLIMIT)"
)