/* Update FINAL PAYMENT AMOUNT = 0 for facility OD (110)  */

-- View the record effected before proceed to patching
select CMS_FAC_MASTER_ID, APPLICATION_DATE, APPROVED_DATE, FAC_STATUS_CODE_VALUE as FACILITY_STATUS, FINAL_PAYMENT, LMT_ID, LMT_LE_ID as CIF_ID, 
LMT_BCA_REF_NUM as AA_NO, CMS_BKG_ORGANISATION as BRANCH_CODE,  LMT_FAC_CODE AS FACILITY_CODE, LMT_FAC_SEQ AS FACILITY_SEQUENCE, 
APPLICATION_TYPE, APPLICATION_LAW_TYPE 
from CMS_FAC_GENERAL gen, SCI_LSP_APPR_LMTS lmt, CMS_FACILITY_MASTER mas, SCI_LSP_LMT_PROFILE aa 
where lmt.LMT_FAC_TYPE_VALUE = '110' 
and lmt.CMS_LSP_APPR_LMTS_ID = mas.CMS_LSP_APPR_LMTS_ID 
and gen.FINAL_PAYMENT <> 0 
and gen.CMS_FAC_MASTER_ID = mas.ID 
and lmt.CMS_LIMIT_PROFILE_ID = aa.CMS_LSP_LMT_PROFILE_ID;

-- Patch final payment amount to 0
update CMS_FAC_GENERAL gen
set FINAL_PAYMENT = 0
where gen.CMS_FAC_MASTER_ID in (
        select mas.ID 
        from SCI_LSP_APPR_LMTS lmt, CMS_FACILITY_MASTER mas, SCI_LSP_LMT_PROFILE aa
        where lmt.LMT_FAC_TYPE_VALUE = '110' and lmt.CMS_LSP_APPR_LMTS_ID = mas.CMS_LSP_APPR_LMTS_ID 
        and gen.FINAL_PAYMENT <> 0 
        and gen.CMS_FAC_MASTER_ID = mas.ID 
        and lmt.CMS_LIMIT_PROFILE_ID = aa.CMS_LSP_LMT_PROFILE_ID);