-----------------------------
-- Cleanup
-----------------------------
DELETE FROM MIG_QC_REPORT;

-----------------------------
-- Standalone AA
-----------------------------
-- ARBS
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrAA', 'QC Report 3g for Migration', 'ARBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrAA', 'Report for migration template: CA001', 'ARBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrAA', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'ARBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrAA', 'CIF / AA Number,Missing Linkages', 'ARBS', 'CA001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrAA', COALESCE(KEY1_VALUE,'-') || ' / ' || COALESCE(KEY2_VALUE,'-') || ',' || ERROR_MSG, 'ARBS', 'CA001' FROM SI_ERROR_LOG
		WHERE ERROR_CODE = 'BizErr003' AND SYSTEM_ID = 'ARBS' AND INTERFACE_ID = 'CA001');

-- SEMA
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrAA', 'QC Report 3g for Migration', 'SEMA', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrAA', 'Report for migration template: CA001', 'SEMA', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrAA', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SEMA', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrAA', 'CIF / AA Number,Missing Linkages', 'SEMA', 'CA001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrAA', COALESCE(KEY1_VALUE,'-') || ' / ' || COALESCE(KEY2_VALUE,'-') || ',' || ERROR_MSG, 'SEMA', 'CA001' FROM SI_ERROR_LOG
		WHERE ERROR_CODE = 'BizErr003' AND SYSTEM_ID = 'SEMA' AND INTERFACE_ID = 'CA001');

-- BOST
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrAA', 'QC Report 3g for Migration', 'BOST', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrAA', 'Report for migration template: CA001', 'BOST', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrAA', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'BOST', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrAA', 'CIF / AA Number,Missing Linkages', 'BOST', 'CA001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrAA', COALESCE(KEY1_VALUE,'-') || ' / ' || COALESCE(KEY2_VALUE,'-') || ',' || ERROR_MSG, 'BOST', 'CA001' FROM SI_ERROR_LOG
		WHERE ERROR_CODE = 'BizErr003' AND SYSTEM_ID = 'BOST' AND INTERFACE_ID = 'CA001');

-- FINS
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrAA', 'QC Report 3g for Migration', 'FINS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrAA', 'Report for migration template: CA001', 'FINS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrAA', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'FINS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('ErrAA', 'CIF / AA Number,Missing Linkages', 'FINS', 'CA001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'ErrAA', COALESCE(KEY1_VALUE,'-') || ' / ' || COALESCE(KEY2_VALUE,'-') || ',' || ERROR_MSG, 'FINS', 'CA001' FROM SI_ERROR_LOG
		WHERE ERROR_CODE = 'BizErr003' AND SYSTEM_ID = 'FINS' AND INTERFACE_ID = 'CA001');

COMMIT;