--  SET CURRENT PATH = SYSIBM,SYSFUN,SYSPROC,SYSIBMADM, EONCMS_LOCAL@

drop table SI_TEMP_SIBS_CU001;

drop table SI_TEMP_SIBS_CU003;

drop table SI_TEMP_SIBS_CA001;

drop table si_temp_ca001_lmt_sum;

drop table SI_TEMP_SIBS_CA004;

drop table SI_TEMP_SIBS_CO001;

drop table SI_TEMP_SIBS_CO002;

DROP sequence CMS_CREDIT_APP_OD_TL_SEQ;

DROP sequence  CMS_CREDIT_APP_NPL_CLSACC_SEQ;

DROP sequence CMS_SIBS_COLLATERAL_FD_SEQ;

DROP sequence CMS_SIBS_COLLATERAL_SMF_SEQ;

------------------------------
-- SIBS CU001 table
-- Customer Information
--
------------------------------
CREATE TABLE SI_TEMP_SIBS_CU001
(
  RECORD_TYPE VARCHAR(1),
  CIF_ID VARCHAR(19),
  CUST_NAME_L VARCHAR(80),
  CUST_NAME_S VARCHAR(20),
  CUST_CLASS_CODE VARCHAR(1),
  ID_ISSUE_COUNTRY VARCHAR(3),
  ID_ISSUE_DATE TIMESTAMP,
  CUST_TYPE VARCHAR(1),
  CUST_START_DATE TIMESTAMP,
  ISIC_CODE VARCHAR(4),
  ID_NUMBER VARCHAR(40),
  ID_TYPE_CODE VARCHAR(3),
  SECONDARY_ID_NUMBER VARCHAR(40),
  SECONDARY_ID_TYPE_CODE VARCHAR(3),
  PRIMARY_ADD_TYPE_CODE VARCHAR(1),
  PRIMARY_ADD_1 VARCHAR(40),
  PRIMARY_ADD_2 VARCHAR(40),
  PRIMARY_ADD_3 VARCHAR(40),
  PRIMARY_ADD_4 VARCHAR(40),
  PRIMARY_POSTCODE VARCHAR(9),
  PRIMARY_COUNTRY VARCHAR(3),
  LANGUAGE_CODE VARCHAR(3),
  SECONDARY_ADD_TYPE_CODE VARCHAR(1),
  SECONDARY_ADD_1 VARCHAR(40),
  SECONDARY_ADD_2 VARCHAR(40),
  SECONDARY_ADD_3 VARCHAR(40),
  SECONDARY_ADD_4 VARCHAR(40),
  SECONDARY_POSTCODE VARCHAR(9),
  ID_TYPE_CAT VARCHAR(20) DEFAULT 'ID_TYPE',
  SECONDARY_ID_TYPE_CAT VARCHAR(20) DEFAULT 'ID_TYPE',
  CUST_TYPE_CAT VARCHAR(20) DEFAULT '8',
  ISIC_CAT VARCHAR(20) DEFAULT '17',
  PRIMARY_ADD_TYPE_CAT VARCHAR(20) DEFAULT '4',
  LANGUAGE_CAT VARCHAR(20) DEFAULT '11',
  SECONDARY_ADD_TYPE_CAT VARCHAR(20) DEFAULT '4',
  IS_VALID VARCHAR(1) DEFAULT 'Y',
  DATE_CREATED TIMESTAMP DEFAULT CURRENT TIMESTAMP )
in CMS_BATCH index in CMS_BATCH_INDEX;

-- *-----------------------------------
-- * SIBS CU003 table - Customer Fusion
-- *------------------------------------
CREATE TABLE SI_TEMP_SIBS_CU003(
  RECORD_TYPE VARCHAR(1),
  OLD_CIF_ID VARCHAR(19),
  NEW_CIF_ID VARCHAR(19),
  IS_VALID VARCHAR(1) DEFAULT 'Y',
  DATE_CREATED TIMESTAMP DEFAULT CURRENT TIMESTAMP )
in CMS_BATCH index in CMS_BATCH_INDEX;

-- *-------------------------------
-- * SIBS CA001 table - Limit Info
-- * please refer to SIBS CA003(limit)+CA004(limit account)
-- *-------------------------------
CREATE TABLE SI_TEMP_SIBS_CA001(
  FEED_ID      BIGINT,
  RECORD_TYPE VARCHAR(1),
  IS_VALID CHAR(1) DEFAULT 'Y',     
  CMS_ACT_LMT_PROFILE_ID BIGINT,
  CMS_ACT_LMT_ID BIGINT,
  CMS_STG_LMT_ID BIGINT,  
  AA_NUMBER VARCHAR(19),  
  SRC_LIMIT_ID VARCHAR(43),
  FACILITY_TYPE_CODE VARCHAR(3),
  FACILITY_SEQ BIGINT,  
  HAS_ACCOUNT CHAR(1) DEFAULT 'N',
  CMS_ACT_ACCT_ID BIGINT,
  CMS_STG_ACCT_ID BIGINT,  
  EXTERNAL_SYSTEM_ACCT_NO VARCHAR(19),
  ACCT_SEQ BIGINT,  
  ACCT_TYPE VARCHAR(1),  
  CMS_STAGE_TAT_ID BIGINT,
  IS_FIRST_DISBURSEMENT_DATE CHAR(1) DEFAULT 'N',  
  FIRST_DISBURSEMENT_DATE TIMESTAMP,  
  OUT_LIMIT_ID VARCHAR(43),  
  DRAWING_LIMIT_AMT DECIMAL(17,2),
  OUTSTANDING_SIGN VARCHAR(1),
  OUTSTANDING_AMT DECIMAL(17,2),
  LOC_COUNTRY VARCHAR(2),
  LOC_ORG_CODE VARCHAR(5),
  LOC_ORG_CAT VARCHAR(20) DEFAULT '40',
  FINAL_DISBURSEMENT_DATE TIMESTAMP,
  CURRENT_BALANCE_AMT DECIMAL(15,2),
  CURRENT_BALANCE_SIGN VARCHAR(1),  
  FINAL_PAYMENT_AMT_SIGN VARCHAR(1),
  FINAL_PAYMENT_AMT DECIMAL(15,2),
  PAYMENT_AMT_SIGN VARCHAR(1),
  PAYMENT_AMT DECIMAL(15,2),
  RELEASED_AMT_SIGN VARCHAR(1),
  RELEASED_AMT DECIMAL(15,2),
  LATE_CHARGES_AMT_SIGN VARCHAR(1),
  LATE_CHARGES_AMT DECIMAL(13,2),
  OTHER_CHARGES_AMT_SIGN VARCHAR(1),
  OTHER_CHARGES_AMT DECIMAL(13,2),
  MISC_CHARGES_AMT_SIGN VARCHAR(1),
  MISC_CHARGES_AMT DECIMAL(13,2),
  BILLED_INT_OS_AMT_SIGN VARCHAR(1),
  BILLED_INT_OS_AMT DECIMAL(13,2),
  ACCRUED_INTEREST_AMT_SIGN VARCHAR(1),
  ACCRUED_INTEREST_AMT DECIMAL(17,5),
  ACCRUED_LATE_CHARGE_AMT_SIGN VARCHAR(1),
  ACCRUED_LATE_CHARGE_AMT DECIMAL(17,5),
  ACCRUED_COMM_FEE_AMT_SIGN VARCHAR(1),
  ACCRUED_COMM_FEE_AMT DECIMAL(15,5),  
  PRIME_RATE_NUMBER VARCHAR(5),
  PRIME_VARIANCE_SIGN VARCHAR(1),
  PRIME_VARIANCE_AMT DECIMAL(11,9),
  DATE_CREATED TIMESTAMP DEFAULT CURRENT TIMESTAMP )
in CMS_BATCH index in CMS_BATCH_INDEX;

-- *-------------------------------------------------------------
-- * SIBS CA004 table - Loan (Non-Performing Loan, Closed Status)
-- *-------------------------------------------------------------
CREATE TABLE SI_TEMP_SIBS_CA004(
  FEED_ID      BIGINT,
  CMS_ACT_LMT_PROFILE_ID BIGINT,
  CMS_ACT_LMT_ID BIGINT,
  CMS_STG_LMT_ID BIGINT,    
  IS_VALID VARCHAR(1) DEFAULT 'Y',  
  CMS_ACT_ACCT_ID BIGINT,
  CMS_STG_ACCT_ID BIGINT,  
  CMS_NPL_ID BIGINT,
  AA_NUMBER VARCHAR(19),
  SRC_LIMIT_ID VARCHAR(43),
  FACILITY_TYPE_CODE VARCHAR(3),
  EXTERNAL_SYSTEM_ACCT_NO VARCHAR(19),
  ACCT_SEQ BIGINT,  
  ACCT_STAT VARCHAR(1),
  NPL_STAT VARCHAR(1),
  FACILITY_SEQ BIGINT,
  ACCT_TYPE VARCHAR(1),
  LOC_COUNTRY VARCHAR(2),
  LOC_ORG_CODE VARCHAR(5),  
  SETTLED_DATE TIMESTAMP,
  AMT_PARTIALLY_WRITTEN_OFF DECIMAL(17,2),
  NPL_STAT_DATE TIMESTAMP,
  INTEREST_IN_SUSPENSE DECIMAL(17,2),
  SPECIFIC_PROV_CHARGED_TO_ACCT DECIMAL(17,2),
  PART_PAYMENT DECIMAL(17,2),
  LATEST_DATE_DOUBTFUL TIMESTAMP,
  JUDGMENT_DATE TIMESTAMP,
  JUDGMENT_SUM DECIMAL(17,2),
  DATE_WRITE_OFF TIMESTAMP,
  AMT_WRITTEN_OFF DECIMAL(17,2),
  MONTHS_INSTALLMENT_ARREARS DECIMAL(17,2),
  MONTHS_INTEREST_ARREARS DECIMAL(17,2),
  LOC_ORG_CAT VARCHAR(20) DEFAULT '40',
  OUT_LIMIT_ID VARCHAR(43),  
  RECORD_TYPE VARCHAR(1),
  DATE_CREATED TIMESTAMP DEFAULT CURRENT TIMESTAMP,
	FACILITY_STATUS VARCHAR(1),
	CANCEL_REJECT_CODE VARCHAR(2),
	CANCEL_REJECT_DATE TIMESTAMP
)
in CMS_BATCH index in CMS_BATCH_INDEX;

-- *-------------------------------------------------------------
-- * SIBS CO001 table - FD Maturity
-- *-------------------------------------------------------------
CREATE TABLE SI_TEMP_SIBS_CO001(
  FEED_ID     BIGINT,
  RECORD_TYPE VARCHAR(1),
  SECURITY_ID VARCHAR(19),
  REF_NO VARCHAR(19),
  RECEIPT_NUMBER VARCHAR(19),
  AMT_CURRENCY VARCHAR(4),
  AMT DECIMAL(17,2),
  THIRD_PARTY_BANK VARCHAR(1),
  FDR_RATE DECIMAL(20,9),
  ISSUE_DATE TIMESTAMP,
  MATURITY_DATE TIMESTAMP,
  IS_VALID VARCHAR(1) DEFAULT 'Y',
  DATE_CREATED TIMESTAMP DEFAULT CURRENT TIMESTAMP )
in CMS_BATCH index in CMS_BATCH_INDEX;

-- *-------------------------------------------------------------
-- * SIBS CO002 table - Shares Margin Financing
-- *-------------------------------------------------------------
CREATE TABLE SI_TEMP_SIBS_CO002(
  FEED_ID     BIGINT,
  RECORD_TYPE                VARCHAR(1),
  SRC_SECURITY_ID            VARCHAR(19),
  ORIG_SECURITY_CURRENCY     VARCHAR(4),
  SECURITY_CURRENCY          VARCHAR(4),
  SECURITY_LOCATION          VARCHAR(20),
  SECURITY_ORGANISATION      VARCHAR(20),
  CUSTODIAN_TYPE             VARCHAR(1),
  SECURITY_CUSTODIAN         VARCHAR(100),
  IS_LEGAL_ENFORCE           VARCHAR(1),
  IS_LEGAL_ENFORCE_DATE      TIMESTAMP,
  TYPE_NAME                  VARCHAR(40),
  CDS_NUMBER                 BIGINT,
  REGISTERED_NAME            VARCHAR(120),
  NO_OF_UNITS                DECIMAL(17,2),
  UNIT_PRICE                 DECIMAL(22,5),
  SECURITY_MATURITY_DATE     TIMESTAMP,
  STOCK_EXCHANGE             VARCHAR(40),
  STOCK_EXCHANGE_COUNTRY     VARCHAR(2),
  STOCK_CODE                 VARCHAR(30),
  LSX_BCA_REF_NUM            VARCHAR(35),
  SCI_LAS_FAC_CODE           VARCHAR(3),
  SCI_LAS_FAC_SEQ            VARCHAR(19),
  CMS_SECURITY_TYPE_ID       VARCHAR(5) DEFAULT 'MS',
  CMS_SECURITY_SUBTYPE_ID    VARCHAR(10),  
  CMS_ACT_LMT_PROFILE_ID     BIGINT,
  CMS_ACT_LMT_ID 	     BIGINT,
  CMS_STG_LMT_ID 	     BIGINT, 
  CMS_SUB_PROFILE_ID	     BIGINT,
  CMS_ACT_PLEDGOR_DTL_ID     BIGINT,
  CMS_STG_PLEDGOR_DTL_ID     BIGINT,
  SEC_PLEDGOR_ID	     VARCHAR(20),
  SEC_PLEDGOR_NAME	     VARCHAR(100),
  SEC_INC_NUM_TEXT	     VARCHAR(30),
  CMS_ACT_COL_ID             BIGINT,
  COL_TRANSACTION_ID         VARCHAR(20),
  IS_VALID VARCHAR(1)           DEFAULT 'Y',
  DATE_CREATED TIMESTAMP DEFAULT CURRENT TIMESTAMP )
in CMS_BATCH index in CMS_BATCH_INDEX;



CREATE SEQUENCE CMS_CREDIT_APP_OD_TL_SEQ AS INTEGER
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 999999999
	MINVALUE 1
	CYCLE
	NO CACHE
	NO ORDER;

CREATE SEQUENCE CMS_CREDIT_APP_NPL_CLSACC_SEQ AS INTEGER
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 999999999
	MINVALUE 1
	CYCLE
	NO CACHE
	NO ORDER;

	CREATE SEQUENCE CMS_SIBS_COLLATERAL_FD_SEQ AS INTEGER
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 999999999
	MINVALUE 1
	CYCLE
	NO CACHE
	NO ORDER;

	CREATE SEQUENCE CMS_SIBS_COLLATERAL_SMF_SEQ AS INTEGER
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 999999999
	MINVALUE 1
	CYCLE
	NO CACHE
	NO ORDER;

reorg table SI_TEMP_SIBS_CU001;

reorg table SI_TEMP_SIBS_CU003;

reorg table SI_TEMP_SIBS_CA001;

reorg table SI_TEMP_SIBS_CA004;

reorg table SI_TEMP_SIBS_CO001;

reorg table SI_TEMP_SIBS_CO002;


----------------------
--- INDEX FOR CU001
----------------------
CREATE INDEX SI_SIBS_CU001_IDX1 ON SI_TEMP_SIBS_CU001
(IS_VALID ASC, CIF_ID ASC) ALLOW REVERSE SCANS;   

---------------------
---* INDEX FOR CA001
---------------------
CREATE INDEX SI_SIBS_CA001_IDX1 ON SI_TEMP_SIBS_CA001
(IS_VALID ASC, AA_NUMBER ASC, FACILITY_TYPE_CODE ASC) ALLOW REVERSE SCANS;

create index SI_SIBS_CA001_IDX2 on si_temp_SIBS_ca001
(IS_VALID ASC, EXTERNAL_SYSTEM_ACCT_NO, ACCT_SEQ, ACCT_TYPE) ALLOW REVERSE SCANS;

CREATE INDEX SI_SIBS_CA001_IDX3 ON SI_TEMP_SIBS_CA001
(IS_VALID ASC, SRC_LIMIT_ID, EXTERNAL_SYSTEM_ACCT_NO, ACCT_SEQ) ALLOW REVERSE SCANS;

CREATE INDEX "SI_SIBS_CA001_IDX4" ON "SI_TEMP_SIBS_CA001"
   ("IS_VALID" ASC, "CMS_ACT_LMT_ID" ASC, "EXTERNAL_SYSTEM_ACCT_NO" ASC, 
   "ACCT_SEQ" ASC, "ACCT_TYPE" ASC) 
   ALLOW REVERSE SCANS ;

CREATE INDEX "SI_SIBS_CA001_IDX5" ON "SI_TEMP_SIBS_CA001"
   ("IS_VALID" ASC, "CMS_STG_LMT_ID" ASC,  "EXTERNAL_SYSTEM_ACCT_NO" ASC, 
   "ACCT_SEQ" ASC, "ACCT_TYPE" ASC) 
   ALLOW REVERSE SCANS ;
   
CREATE INDEX "SI_SIBS_CA001_IDX6" ON "SI_TEMP_SIBS_CA001"
   ("IS_VALID" ASC, "FEED_ID" ASC) 
   ALLOW REVERSE SCANS ;

CREATE INDEX "SI_SIBS_CA001_IDX7" ON "SI_TEMP_SIBS_CA001"
   ("IS_FIRST_DISBURSEMENT_DATE", "CMS_ACT_LMT_PROFILE_ID" DESC)
   ALLOW REVERSE SCANS ;
   
create index SI_SIBS_CA001_IDX8 on SI_TEMP_SIBS_CA001
	(IS_VALID, CMS_ACT_LMT_ID, CMS_ACT_ACCT_ID)
	ALLOW REVERSE SCANS;
	
create index SI_SIBS_CA001_IDX9 on SI_TEMP_SIBS_CA001
	(IS_VALID, CMS_STG_LMT_ID, CMS_STG_ACCT_ID)
	ALLOW REVERSE SCANS;	
   
CREATE INDEX SI_SIBS_CA001_IDX10 ON SI_TEMP_SIBS_CA001
	(HAS_ACCOUNT, CMS_ACT_ACCT_ID, EXTERNAL_SYSTEM_ACCT_NO, ACCT_SEQ) 
	ALLOW REVERSE SCANS;
	
CREATE INDEX SI_SIBS_CA001_IDX11 ON SI_TEMP_SIBS_CA001
	(HAS_ACCOUNT, CMS_STG_ACCT_ID, EXTERNAL_SYSTEM_ACCT_NO, ACCT_SEQ)
	ALLOW REVERSE SCANS;
	
CREATE INDEX "SI_SIBS_CA001_IDX12" ON "SI_TEMP_SIBS_CA001"
   (IS_VALID, "CMS_ACT_LMT_PROFILE_ID", "FIRST_DISBURSEMENT_DATE", feed_id DESC)
   ALLOW REVERSE SCANS ;	

----------------------
---* INDEX FOR CA004
----------------------
CREATE INDEX SI_SIBS_CA004_IDX1 ON SI_TEMP_SIBS_CA004
(IS_VALID ASC, AA_NUMBER ASC, SRC_LIMIT_ID ASC, EXTERNAL_SYSTEM_ACCT_NO ASC, ACCT_SEQ ASC) 
ALLOW REVERSE SCANS;

CREATE INDEX SI_SIBS_CA004_IDX2 ON SI_TEMP_SIBS_CA004
(IS_VALID ASC, CMS_ACT_LMT_ID) ALLOW REVERSE SCANS;

CREATE INDEX SI_SIBS_CA004_IDX3 ON SI_TEMP_SIBS_CA004
(IS_VALID ASC, CMS_STG_LMT_ID) ALLOW REVERSE SCANS;

CREATE INDEX SI_SIBS_CA004_IDX4 ON SI_TEMP_SIBS_CA004
(IS_VALID ASC, CMS_ACT_LMT_PROFILE_ID, CMS_ACT_LMT_ID) ALLOW REVERSE SCANS;

CREATE INDEX SI_SIBS_CA004_IDX5 ON SI_TEMP_SIBS_CA004
(IS_VALID ASC, CMS_ACT_ACCT_ID) ALLOW REVERSE SCANS;

CREATE INDEX SI_SIBS_CA004_IDX6 ON SI_TEMP_SIBS_CA004
(IS_VALID ASC, CMS_STG_ACCT_ID) ALLOW REVERSE SCANS;

create index SI_SIBS_CA004_IDX7 on SI_TEMP_SIBS_CA004
	(IS_VALID, CMS_ACT_LMT_ID, CMS_ACT_ACCT_ID)
	ALLOW REVERSE SCANS;
	
create index SI_SIBS_CA004_IDX8 on SI_TEMP_SIBS_CA004
	(IS_VALID, CMS_STG_LMT_ID, CMS_STG_ACCT_ID)
	ALLOW REVERSE SCANS;

create index SI_SIBS_CA004_IDX9 on SI_TEMP_SIBS_CA004
	(IS_VALID, CMS_NPL_ID)
	ALLOW REVERSE SCANS;
		
create table si_temp_ca001_lmt_sum (
	cms_act_lmt_id	bigint,
	cms_stg_lmt_id	bigint,
	sum_drawing_lmt	decimal(20,2),
	sum_outstanding_amt	decimal(20,2)	
)in CMS_BATCH index in CMS_BATCH_INDEX;

create index si_temp_ca001_idx1 on si_temp_ca001_lmt_sum
	(cms_act_lmt_id) allow reverse scans;
	
create index si_temp_ca001_idx2 on si_temp_ca001_lmt_sum
	(cms_stg_lmt_id) allow reverse scans;	

COMMIT;

