-- CREATE TABLE HOST_INSURANCE_CO ( 
-- 	INS_NUM          	VARCHAR(10),
-- 	INS_NAME         	VARCHAR(40),
-- 	INS_ADDRESS      	VARCHAR(40),
-- 	INS_CITY_STATE   	VARCHAR(40),
-- 	INS_PHONE        	VARCHAR(30),
-- 	RESERVE_PERCENT  	DECIMAL(11,9),
-- 	PANEL_IND        	CHAR,
-- 	STATUS           	VARCHAR(10),
-- 	LAST_UPDATED_DATE	TIMESTAMP 
-- 	);
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('101', 'UNI.ASIA LIFE ASSURANCE BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.389');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('102', 'ING INSURANCE SDN BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.389');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('103', 'AMERICAN HOME ASSURANCE COMPANY', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('104', 'COMMERCE ASSURANCE BHD (59131M)', '', '', '', 0E-9, 'N', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('105', 'AXA AFFIN ASSURANCE BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('106', 'HONG LEONG ASSURANCE BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('107', 'JERNEH INSURANCE BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('108', 'KURNIA INSURANCE (M) BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('109', 'ALLIANZ GENERAL INSURANCE MALAYSIA BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('110', 'MALAYSIAN ASSURANCE ALLIANCE BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('111', 'QBE-MBF INSURANS BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('112', 'AVIVA INSURANCE BERHAD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('113', 'SYARIKAT TAKAFUL MALAYSIA BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('114', 'MITSUI SUMITOMO INSURANCE (M) BERHAD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('115', 'TENAGA INSURANCE SDN BHD', '', '', '', 0E-9, 'N', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('116', 'PANGLOBAL INSURANCE SDN BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('117', 'UNI.ASIA GENERAL INSURANCE BERHAD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('118', 'ETIQA TAKAFUL BERHAD (266243D)', 'Level 19, Tower C, No. 1, Jalan Maarof,', '59000 Kuala Lumpur', '03-22971888', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('119', 'LONPAC INSURANCE BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('120', 'ORIENTAL CAPITAL ASSURANCE BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('121', 'PERBADANAN NASIONAL INSURANS SDN BHD', '', '', '', 0E-9, 'N', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('122', 'TOKIO MARINE INSURANS (M) BERHAD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('123', 'AMERICAN INTERNATIONAL ASSURANCE CO. LTD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('124', 'AM ASSURANCE BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('125', 'ASIA INSURANCE (M) BHD (THE)', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('126', 'BERJAYA SOMPO INSURANCE BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('127', 'NOT USED', '', '', '', 0E-9, 'N', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('128', 'MALAYSIA & NIPPON INSURANS BHD', '', '', '', 0E-9, 'N', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('129', 'MAYBAN ASSURANCE BHD', '', '', '', 0E-9, 'N', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('130', 'MCIS ZURICH INSURANCE BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('131', 'MUI CONTINENTAL INSURANCE BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('132', 'M/S PERINSU (BROKER INSURANS) SDN BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('133', 'ETIQA INSURANCE BHD (9557T)', 'Level 19, Tower C, No. 1, Jalan Maarof', '59000 Kuala Lumpur', '603-22971888', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('134', 'OVERSEAS ASSURANCE CORPORATION (M) BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('135', 'PROGRESSIVE INSURANCE BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('136', 'RHB INSURANCE BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('137', 'BH INSURANCE (M) SDN BHD (29962-V)', 'WISMA BOUSTEAD, 71, JLN RAJA CHULAN', '50200 KUALA LUMPUR', '03-2141 0233, 03-2142 9219(F)', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('138', 'TAHAN INSURANCE MALAYSIA BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('139', 'PACIFIC INSURANCE BERHAD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.39');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('140', 'MULTI-PURPOSE INSURANS BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.391');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('201', 'ACE SYNERGY INSURANCE BHD', '', '', '', 0E-9, 'N', 'ACTIVE', '2009-03-10 01:09:50.391');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('202', 'ALEXANDER FORBES INSURANCE', '', '', '', 0E-9, 'N', 'ACTIVE', '2009-03-10 01:09:50.391');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('203', 'BRADSTOCK INSURANCE BROKERS', '', '', '', 0E-9, 'N', 'ACTIVE', '2009-03-10 01:09:50.391');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('204', 'GREAT EASTERN LIFE ASSURANCE', '', '', '', 0E-9, 'N', 'ACTIVE', '2009-03-10 01:09:50.391');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('205', 'PACIFIC & ORIENT INSURANCE CO. BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.391');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('206', 'PRUDENTIAL ASSURANCE MALAYSIA BERHAD', '', '', '', 0E-9, 'N', 'ACTIVE', '2009-03-10 01:09:50.391');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('207', 'STATE INSURANCE BROKEN S/B', '', '', '', 0E-9, 'N', 'ACTIVE', '2009-03-10 01:09:50.391');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('208', 'UNIVERSAL LIFE & GENERAL', '', '', '', 0E-9, 'N', 'ACTIVE', '2009-03-10 01:09:50.391');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('209', 'PEOPLE INSURANCE', '', '', '', 0E-9, 'N', 'ACTIVE', '2009-03-10 01:09:50.391');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('210', 'ACE ASIA', '', '', '', 0E-9, 'N', 'ACTIVE', '2009-03-10 01:09:50.391');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('211', 'GUARDIAN INSURANCE', '', '', '', 0E-9, 'N', 'ACTIVE', '2009-03-10 01:09:50.391');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('212', 'SAFETY INSURANCE', '', '', '', 0E-9, 'N', 'ACTIVE', '2009-03-10 01:09:50.391');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('213', 'TAKAFUL IKHLAS SDN BHD (593075U)', '9TH FLR BGN MALAYSIA   NO 17 LRG DUNGUN', 'D''SARA HEIGHTS LOCKED BAG 11094 50990 KL', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.391');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('141', 'AMI INSURANS BHD', '', '', '', 0E-9, 'Y', 'ACTIVE', '2009-03-10 01:09:50.391');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('214', 'CIMB AVIVA TAKAFUL BERHAD (689263M)', 'LEVEL 8, 338, JLN TUANKU ABDUL RAHMAN', '50100 KUALA LUMPUR', '0326123600', 0E-9, 'N', 'ACTIVE', '2009-03-10 01:09:50.391');
INSERT INTO HOST_INSURANCE_CO(INS_NUM, INS_NAME, INS_ADDRESS, INS_CITY_STATE, INS_PHONE, RESERVE_PERCENT, PANEL_IND, STATUS, LAST_UPDATED_DATE)
  VALUES('215', 'MAYBAN TAKAFUL BERHAD', 'LVL 15,MAYBAN LIFE TOWER,DATARAN MAYBANK', 'NO 1,JLN MAAROF, 59000 KUALA LUMPUR', '03-22973999', 0E-9, 'N', 'ACTIVE', '2009-03-10 01:09:50.391');
