-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1400, 'CCC', 'GENERATE_CCC', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1401, 'CCC', 'GENERATE_CCC', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1402, 'CCC', 'APPROVE_GENERATE_CCC', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1403, 'CCC', 'APPROVE_GENERATE_CCC', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1404, 'CCC', 'REJECT_GENERATE_CCC', 'PENDING_CREATE', 'REJECTED', 'REJECTED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1405, 'CCC', 'REJECT_GENERATE_CCC', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1406, 'CCC', 'EDIT_REJECTED_CREATE_GENERATE_CCC', 'REJECTED', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1407, 'CCC', 'EDIT_REJECTED_UPDATE_GENERATE_CCC', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1408, 'CCC', 'CLOSE_REJECTED_CREATE_GENERATE_CCC', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1409, 'CCC', 'CLOSE_REJECTED_UPDATE_GENERATE_CCC', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1410, 'CCC', 'SYSTEM_CLOSE', 'PENDING_CREATE', 'CLOSED', 'CLOSED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1411, 'CCC', 'SYSTEM_CLOSE', 'PENDING_UPDATE', 'CLOSED', 'CLOSED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1412, 'CCC', 'SYSTEM_CLOSE', 'ACTIVE', 'CLOSED', 'CLOSED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1413, 'CCC', 'SYSTEM_CLOSE', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (2401, 'CC_DOC_LOC', 'CREATE_CC_DOC_LOC', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (2402, 'CC_DOC_LOC', 'APPROVE_CREATE_CC_DOC_LOC', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (2403, 'CC_DOC_LOC', 'REJECT_CC_DOC_LOC', 'PENDING_CREATE', 'REJECTED', 'REJECTED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (2404, 'CC_DOC_LOC', 'EDIT_REJECTED_CREATE_CC_DOC_LOC', 'REJECTED', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (2405, 'CC_DOC_LOC', 'CLOSE_REJECTED_CREATE_CC_DOC_LOC', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (2406, 'CC_DOC_LOC', 'UPDATE_CC_DOC_LOC', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (2407, 'CC_DOC_LOC', 'APPROVE_UPDATE_CC_DOC_LOC', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (2408, 'CC_DOC_LOC', 'REJECT_CC_DOC_LOC', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (2409, 'CC_DOC_LOC', 'EDIT_REJECTED_UPDATE_CC_DOC_LOC', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (2410, 'CC_DOC_LOC', 'CLOSE_REJECTED_UPDATE_CC_DOC_LOC', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1901, 'CC_TASK', 'CREATE_CC_TASK', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1902, 'CC_TASK', 'APPROVE_CREATE_CC_TASK', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1903, 'CC_TASK', 'REJECT_CC_TASK', 'PENDING_CREATE', 'REJECTED', 'REJECTED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1904, 'CC_TASK', 'EDIT_REJECTED_CREATE_CC_TASK', 'REJECTED', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1905, 'CC_TASK', 'CLOSE_REJECTED_CREATE_CC_TASK', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1906, 'CC_TASK', 'UPDATE_CC_TASK', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1907, 'CC_TASK', 'APPROVE_UPDATE_CC_TASK', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1908, 'CC_TASK', 'REJECT_CC_TASK', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1909, 'CC_TASK', 'EDIT_REJECTED_UPDATE_CC_TASK', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1910, 'CC_TASK', 'CLOSE_REJECTED_UPDATE_CC_TASK', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1911, 'CC_TASK', 'MAKER_REJECT_CC_TASK', 'ACTIVE', 'PENDING_REJECT', 'PENDING_REJECT', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1912, 'CC_TASK', 'APPROVE_REJECTED_CC_TASK', 'PENDING_REJECT', 'CLOSED', 'CLOSED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1913, 'CC_TASK', 'REJECT_REJECTED_CC_TASK', 'PENDING_REJECT', 'REJECT_REJECTED', 'REJECT_REJECTED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1914, 'CC_TASK', 'CLOSE_REJECT_REJECTED_UPDATE_CC_TASK', 'REJECT_REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1915, 'CC_TASK', 'EDIT_REJECT_REJECTED_UPDATE_CC_TASK', 'REJECT_REJECTED', 'PENDING_REJECT', 'PENDING_UPDATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1920, 'CC_TASK', 'SYSTEM_UPDATE_CC_TASK', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1921, 'CC_TASK', 'SYSTEM_UPDATE_CC_TASK', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1922, 'CC_TASK', 'SYSTEM_UPDATE_CC_TASK', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');

Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2300, 'CHECKLIST', 'DIRECT_UPDATE', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2301, 'CHECKLIST', 'DIRECT_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2302, 'CHECKLIST', 'DIRECT_UPDATE', 'REJECTED', 'REJECTED', 'REJECTED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2303, 'CHECKLIST', 'DIRECT_UPDATE', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2304, 'CHECKLIST', 'DIRECT_UPDATE', 'PENDING_GEN_WAIVER_REQ', 'PENDING_GEN_WAIVER_REQ', 'PENDING_GEN_WAIVER_REQ', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2305, 'CHECKLIST', 'DIRECT_UPDATE', 'PENDING_GEN_DEFER_REQ', 'PENDING_GEN_DEFER_REQ', 'PENDING_GEN_DEFER_REQ', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2306, 'CHECKLIST', 'DIRECT_UPDATE', 'PENDING_MGR_VERIFY', 'PENDING_MGR_VERIFY', 'PENDING_MGR_VERIFY', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2307, 'CHECKLIST', 'SYSTEM_OBSOLETE_CHECKLIST', 'PENDING_UPDATE', 'OBSOLETE', 'OBSOLETE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2308, 'CHECKLIST', 'FORWARD', 'PENDING_UPDATE', 'PENDING_AUTH', 'PENDING_AUTH', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2309, 'CHECKLIST', 'REJECT', 'PENDING_AUTH', 'OFFICER_REJECTED', 'OFFICER_REJECTED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2310, 'CHECKLIST', 'DIRECT_UPDATE', 'PENDING_OFFICE', 'PENDING_OFFICE', 'PENDING_OFFICE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2311, 'CHECKLIST', 'APPROVE', 'PENDING_AUTH', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2312, 'CHECKLIST', 'FORWARD', 'PENDING_AUTH', 'PENDING_OFFICE', 'PENDING_OFFICE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2313, 'CHECKLIST', 'BACKWARD', 'PENDING_OFFICE', 'PENDING_AUTH', 'PENDING_AUTH', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2314, 'CHECKLIST', 'FORWARD', 'PENDING_OFFICE', 'PENDING_OFFICE', 'PENDING_OFFICE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2315, 'CHECKLIST', 'APPROVE', 'PENDING_OFFICE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2316, 'CHECKLIST', 'REJECT', 'PENDING_OFFICE', 'PENDING_VERIFY', 'PENDING_VERIFY', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2317, 'CHECKLIST', 'REJECT', 'PENDING_VERIFY', 'OFFICER_REJECTED', 'OFFICER_REJECTED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2318, 'CHECKLIST', 'DIRECT_UPDATE', 'OFFICER_REJECTED', 'OFFICER_REJECTED', 'OFFICER_REJECTED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2319, 'CHECKLIST', 'EDIT_REJECTED_UPDATE_CHECKLIST_RECEIPT', 'OFFICER_REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2320, 'CHECKLIST', 'CLOSE_REJECTED_UPDATE_CHECKLIST_RECEIPT', 'OFFICER_REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2321, 'CHECKLIST', 'SYSTEM_CLOSE_CHECKLIST', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2322, 'CHECKLIST', 'CHECKER_UPDATE_CHECKLIST_RECEIPT', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2323, 'CHECKLIST', 'SYSTEM_OBSOLETE_CHECKLIST', 'ACTIVE', 'OBSOLETE', 'OBSOLETE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2324, 'CHECKLIST', 'SYSTEM_DELETE', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2325, 'CHECKLIST', 'SYSTEM_DELETE', 'OFFICER_REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2326, 'CHECKLIST', 'COPY_CHECKLIST', 'ND', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2327, 'CHECKLIST', 'SYSTEM_CLOSE_CHECKLIST', 'PENDING_CREATE', 'CLOSED', 'CLOSED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2328, 'CHECKLIST', 'SYSTEM_UPDATE', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2329, 'CHECKLIST', 'SYSTEM_UPDATE', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2330, 'CHECKLIST', 'SYSTEM_UPDATE', 'PENDING_GEN_WAIVER_REQ', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2331, 'CHECKLIST', 'SYSTEM_UPDATE', 'PENDING_GEN_DEFER_REQ', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2332, 'CHECKLIST', 'SYSTEM_UPDATE', 'PENDING_MGR_VERIFY', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2333, 'CHECKLIST', 'CREATE_CHECKLIST', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2334, 'CHECKLIST', 'APPROVE_CREATE_CHECKLIST', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2335, 'CHECKLIST', 'REJECT_CHECKLIST', 'PENDING_CREATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2336, 'CHECKLIST', 'EDIT_REJECTED_CREATE_CHECKLIST', 'REJECTED', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2337, 'CHECKLIST', 'CLOSE_REJECTED_CREATE_CHECKLIST', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2338, 'CHECKLIST', 'UPDATE_CHECKLIST', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2339, 'CHECKLIST', 'REJECT_CHECKLIST', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2340, 'CHECKLIST', 'EDIT_REJECTED_UPDATE_CHECKLIST', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2341, 'CHECKLIST', 'APPROVE_UPDATE_CHECKLIST', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2342, 'CHECKLIST', 'CLOSE_REJECTED_UPDATE_CHECKLIST', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2343, 'CHECKLIST', 'SAVE_CHECKLIST_RECEIPT', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2344, 'CHECKLIST', 'SAVE_CHECKLIST_RECEIPT', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2345, 'CHECKLIST', 'UPDATE_CHECKLIST_RECEIPT', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2346, 'CHECKLIST', 'CANCEL_SAVE_CHECKLIST_RECEIPT', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2347, 'CHECKLIST', 'SAVE_CHECKLIST_RECEIPT', 'REJECTED', 'DRAFT', 'DRAFT', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2348, 'CHECKLIST', 'UPDATE_CHECKLIST_RECEIPT', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2349, 'CHECKLIST', 'APPROVE_UPDATE_CHECKLIST_RECEIPT', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2350, 'CHECKLIST', 'REJECT_CHECKLIST_RECEIPT', 'PENDING_UPDATE', 'REJECTED', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2351, 'CHECKLIST', 'EDIT_REJECTED_UPDATE_CHECKLIST_RECEIPT', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2352, 'CHECKLIST', 'CLOSE_REJECTED_UPDATE_CHECKLIST_RECEIPT', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2353, 'CHECKLIST', 'SAVE_CHECKLIST_RECEIPT', 'OFFICER_REJECTED', 'DRAFT', 'DRAFT', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2354, 'CHECKLIST', 'SYSTEM_DELETE', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2355, 'CHECKLIST', 'SYSTEM_DELETE', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2356, 'CHECKLIST', 'SYSTEM_DELETE', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2357, 'CHECKLIST', 'SYSTEM_DELETE', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2358, 'CHECKLIST', 'SYSTEM_GENERATE_CHECKLIST_WAIVER', 'ACTIVE', 'PENDING_GEN_WAIVER_REQ', 'PENDING_GEN_WAIVER_REQ', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2359, 'CHECKLIST', 'SYSTEM_APPROVE_GENERATE_CHECKLIST_WAIVER', 'PENDING_GEN_WAIVER_REQ', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2360, 'CHECKLIST', 'SYSTEM_REJECT_GENERATE_CHECKLIST_WAIVER', 'PENDING_GEN_WAIVER_REQ', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2361, 'CHECKLIST', 'VERIFY_CHECKLIST_RECEIPT', 'PENDING_UPDATE', 'PENDING_MGR_VERIFY', 'PENDING_MGR_VERIFY', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2362, 'CHECKLIST', 'MGR_VERIFY_CHECKLIST_RECEIPT', 'PENDING_MGR_VERIFY', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2363, 'CHECKLIST', 'MGR_REJECT_CHECKLIST_RECEIPT', 'PENDING_MGR_VERIFY', 'REJECTED', 'REJECTED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2364, 'CHECKLIST', 'SYSTEM_GENERATE_CHECKLIST_DEFER', 'ACTIVE', 'PENDING_GEN_DEFER_REQ', 'PENDING_GEN_DEFER_REQ', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2365, 'CHECKLIST', 'SYSTEM_APPROVE_GENERATE_CHECKLIST_DEFER', 'PENDING_GEN_DEFER_REQ', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2366, 'CHECKLIST', 'SYSTEM_REJECT_GENERATE_CHECKLIST_DEFER', 'PENDING_GEN_DEFER_REQ', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2367, 'CHECKLIST', 'SYSTEM_UPDATE', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2368, 'CHECKLIST', 'SYSTEM_UPDATE', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2369, 'CHECKLIST', 'SYSTEM_CREATE', 'ND', 'ACTIVE', 'ACTIVE', '1', '1');
INSERT INTO tr_state_matrix (SELECT MAX(stateid)+1, 'CHECKLIST', 'SYSTEM_CREATE_DOCUMENT', 'ND', 'ACTIVE', 'ACTIVE', '1', '1' FROM tr_state_matrix WHERE stateins = 'CHECKLIST'); 
   
   
-----------------------   
-- checklist item
-----------------------
--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (601, 'CHECKLIST_ITEM', 'REMIND', 'AWAITING', 'REMINDED', 'REMINDED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (602, 'CHECKLIST_ITEM', 'RECEIVE', 'AWAITING', 'RECEIVED', 'RECEIVED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (606, 'CHECKLIST_ITEM', 'VIEW_RECEIVED', 'RECEIVED', 'RECEIVED', 'RECEIVED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (609, 'CHECKLIST_ITEM', 'VIEW_REMINDED', 'REMINDED', 'REMINDED', 'REMINDED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (610, 'CHECKLIST_ITEM', 'RECEIVE', 'REMINDED', 'RECEIVED', 'RECEIVED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (611, 'CHECKLIST_ITEM', 'COMPLETE', 'REMINDED', 'PENDING_COMPLETE', 'PENDING_COMPLETE', '1', '1');
--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (612, 'CHECKLIST_ITEM', 'COMPLETE', 'DEFERRED', 'PENDING_COMPLETE', 'PENDING_COMPLETE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (613, 'CHECKLIST_ITEM', 'VIEW_PENDING_WAIVE', 'PENDING_WAIVE', 'PENDING_WAIVE', 'PENDING_WAIVE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (614, 'CHECKLIST_ITEM', 'VIEW_DEFERRED', 'DEFERRED', 'DEFERRED', 'DEFERRED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (615, 'CHECKLIST_ITEM', 'RECEIVE', 'DEFERRED', 'RECEIVED', 'RECEIVED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (618, 'CHECKLIST_ITEM', 'VIEW_WAIVED', 'WAIVED', 'WAIVED', 'WAIVED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (619, 'CHECKLIST_ITEM', 'VIEW_PENDING_COMPLETE', 'PENDING_COMPLETE', 'PENDING_COMPLETE', 'PENDING_COMPLETE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (620, 'CHECKLIST_ITEM', 'VIEW_COMPLETED', 'COMPLETED', 'COMPLETED', 'COMPLETED', '1', '1');
--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (621, 'CHECKLIST_ITEM', 'ALLOW_TEMP_UPLIFT', 'COMPLETED', 'PENDING_ALLOW_TEMP_UPLIFT', 'PENDING_ALLOW_TEMP_UPLIFT', '1', '1');
--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (622, 'CHECKLIST_ITEM', 'ALLOW_PERM_UPLIFT', 'COMPLETED', 'PENDING_ALLOW_PERM_UPLIFT', 'PENDING_ALLOW_PERM_UPLIFT', '1', '1');
--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (623, 'CHECKLIST_ITEM', 'DELETE', 'COMPLETED', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (624, 'CHECKLIST_ITEM', 'APPROVE', 'PENDING_DELETE', 'DELETED', 'DELETED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (626, 'CHECKLIST_ITEM', 'VIEW_EXPIRED', 'EXPIRED', 'EXPIRED', 'EXPIRED', '1', '1');
--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (627, 'CHECKLIST_ITEM', 'DELETE', 'EXPIRED', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (628, 'CHECKLIST_ITEM', 'RENEW', 'EXPIRED', 'RENEWED', 'RENEWED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (629, 'CHECKLIST_ITEM', 'VIEW_PENDING_RENEWAL', 'PENDING_RENEWAL', 'PENDING_RENEWAL', 'PENDING_RENEWAL', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (630, 'CHECKLIST_ITEM', 'VIEW_RENEWED', 'RENEWED', 'RENEWED', 'RENEWED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (631, 'CHECKLIST_ITEM', 'ALLOW_PERM_UPLIFT', 'RENEWED', 'PENDING_ALLOW_PERM_UPLIFT', 'PENDING_ALLOW_PERM_UPLIFT', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (632, 'CHECKLIST_ITEM', 'VIEW_DELETED', 'DELETED', 'DELETED', 'DELETED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (633, 'CHECKLIST_ITEM', 'ALLOW_PERM_UPLIFT', 'DELETED', 'PENDING_ALLOW_PERM_UPLIFT', 'PENDING_ALLOW_PERM_UPLIFT', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (634, 'CHECKLIST_ITEM', 'COMPLETE', 'RECEIVED', 'PENDING_COMPLETE', 'PENDING_COMPLETE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (635, 'CHECKLIST_ITEM', 'APPROVE', 'PENDING_COMPLETE', 'COMPLETED', 'COMPLETED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (636, 'CHECKLIST_ITEM', 'APPROVE', 'PENDING_WAIVER_REQ', 'WAIVER_REQ', 'WAIVER_REQ', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (637, 'CHECKLIST_ITEM', 'APPROVE', 'PENDING_DEFER_REQ', 'DEFER_REQ', 'DEFER_REQ', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (640, 'CHECKLIST_ITEM', 'APPROVE', 'PENDING_WAIVER', 'WAIVED', 'WAIVED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (641, 'CHECKLIST_ITEM', 'APPROVE', 'PENDING_DEFER', 'DEFERRED', 'DEFERRED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (642, 'CHECKLIST_ITEM', 'VIEW_PENDING_DELETE', 'PENDING_DELETE', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (646, 'CHECKLIST_ITEM', 'APPROVE', 'WAIVER_REQ', 'WAIVER_REQ_GENERATED', 'WAIVER_REQ_GENERATED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (647, 'CHECKLIST_ITEM', 'APPROVE', 'DEFER_REQ', 'DEFER_REQ_GENERATED', 'DEFER_REQ_GENERATED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (648, 'CHECKLIST_ITEM', 'WAIVER', 'WAIVER_REQ_GENERATED', 'PENDING_WAIVER', 'PENDING_WAIVER', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (649, 'CHECKLIST_ITEM', 'DEFER', 'DEFER_REQ_GENERATED', 'PENDING_DEFER', 'PENDING_DEFER', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (650, 'CHECKLIST_ITEM', 'VIEW_WAIVER_REQ', 'WAIVER_REQ', 'WAIVER_REQ', 'WAIVER_REQ', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (651, 'CHECKLIST_ITEM', 'VIEW_DEFER_REQ', 'DEFER_REQ', 'DEFER_REQ', 'DEFER_REQ', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (652, 'CHECKLIST_ITEM', 'VIEW_PENDING_WAIVER', 'PENDING_WAIVER', 'PENDING_WAIVER', 'PENDING_WAIVER', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (653, 'CHECKLIST_ITEM', 'VIEW_PENDING_DEFER', 'PENDING_DEFER', 'PENDING_DEFER', 'PENDING_DEFER', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (654, 'CHECKLIST_ITEM', 'VIEW_DEFER_REQ_GENERATED', 'DEFER_REQ_GENERATED', 'DEFER_REQ_GENERATED', 'DEFER_REQ_GENERATED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (655, 'CHECKLIST_ITEM', 'VIEW_WAIVER_REQ_GENERATED', 'WAIVER_REQ_GENERATED', 'WAIVER_REQ_GENERATED', 'WAIVER_REQ_GENERATED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (656, 'CHECKLIST_ITEM', 'APPROVE', 'PENDING_RENEWAL', 'RENEWED', 'RENEWED', '1', '1');
--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (657, 'CHECKLIST_ITEM', 'ALLOW_PERM_UPLIFT', 'EXPIRED', 'PENDING_ALLOW_PERM_UPLIFT', 'PENDING_ALLOW_PERM_UPLIFT', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (658, 'CHECKLIST_ITEM', 'REMIND', 'REMINDED', 'REMINDED', 'REMINDED', '1', '1');
--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (659, 'CHECKLIST_ITEM', 'DELETE', 'AWAITING', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (660, 'CHECKLIST_ITEM', 'DELETE', 'RENEWED', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (661, 'CHECKLIST_ITEM', 'DELETE', 'REMINDED', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (662, 'CHECKLIST_ITEM', 'DELETE', 'RECEIVED', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (663, 'CHECKLIST_ITEM', 'DELETE', 'DEFERRED', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (664, 'CHECKLIST_ITEM', 'DELETE', 'WAIVED', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (665, 'CHECKLIST_ITEM', 'DELETE', 'WAIVER_REQ', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (666, 'CHECKLIST_ITEM', 'DELETE', 'DEFER_REQ', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (667, 'CHECKLIST_ITEM', 'DELETE', 'WAIVER_REQ_GENERATED', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (668, 'CHECKLIST_ITEM', 'DELETE', 'DEFER_REQ_GENERATED', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (670, 'CHECKLIST_ITEM', 'WAIVER', 'AWAITING', 'PENDING_WAIVER', 'PENDING_WAIVER', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (671, 'CHECKLIST_ITEM', 'DEFER', 'AWAITING', 'PENDING_DEFER', 'PENDING_DEFER', '1', '1');
--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (672, 'CHECKLIST_ITEM', 'ALLOW_RELODGE', 'COMPLETED', 'PENDING_ALLOW_RELODGE', 'PENDING_ALLOW_RELODGE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (673, 'CHECKLIST_ITEM', 'UPDATE', 'COMPLETED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (674, 'CHECKLIST_ITEM', 'APPROVE', 'PENDING_UPDATE', 'COMPLETED', 'COMPLETED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (675, 'CHECKLIST_ITEM', 'VIEW_PENDING_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (676, 'CHECKLIST_ITEM', 'WAIVER', 'REMINDED', 'PENDING_WAIVER', 'PENDING_WAIVER', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (677, 'CHECKLIST_ITEM', 'DEFER', 'REMINDED', 'PENDING_DEFER', 'PENDING_DEFER', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (679, 'CHECKLIST_ITEM', 'UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (680, 'CHECKLIST_ITEM', 'UPDATE', 'RECEIVED', 'RECEIVED', 'RECEIVED', '1', '1');
--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (681, 'CHECKLIST_ITEM', 'DEFER', 'DEFERRED', 'DEFERRED', 'DEFERRED', '1', '1');
--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (682, 'CHECKLIST_ITEM', 'ALLOW_TEMP_UPLIFT', 'EXPIRED', 'PENDING_ALLOW_TEMP_UPLIFT', 'PENDING_ALLOW_TEMP_UPLIFT', '1', '1');
--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (686, 'CHECKLIST_ITEM', 'COMPLETE', 'AWAITING', 'PENDING_COMPLETE', 'PENDING_COMPLETE', '1', '1');
--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (687, 'CHECKLIST_ITEM', 'REMIND', 'DEFERRED', 'REMINDED', 'REMINDED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (688, 'CHECKLIST_ITEM', 'WAIVER', 'DEFERRED', 'PENDING_WAIVER', 'PENDING_WAIVER', '1', '1');
--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (690, 'CHECKLIST_ITEM', 'UPDATE', 'EXPIRED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (691, 'CHECKLIST_ITEM', 'ALLOW_TEMP_UPLIFT', 'RENEWED', 'PENDING_ALLOW_TEMP_UPLIFT', 'PENDING_ALLOW_TEMP_UPLIFT', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (692, 'CHECKLIST_ITEM', 'ALLOW_RELODGE', 'RENEWED', 'PENDING_ALLOW_RELODGE', 'PENDING_ALLOW_RELODGE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (693, 'CHECKLIST_ITEM', 'UPDATE_RENEWAL', 'RENEWED', 'PENDING_RENEWAL', 'PENDING_RENEWAL', '1', '1');
--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (699, 'CHECKLIST_ITEM', 'UPDATE_NARRATION', 'AWAITING', 'AWAITING', 'AWAITING', '1', '1');

--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (603, 'CHECKLIST_ITEM', 'UPDATE', 'AWAITING', 'AWAITING', 'AWAITING', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (603, 'CHECKLIST_ITEM', 'UPDATE', 'AWAITING', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (604, 'CHECKLIST_ITEM', 'VIEW_AWAITING', 'AWAITING', 'AWAITING', 'AWAITING', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (638, 'CHECKLIST_ITEM', 'LODGE', 'COMPLETED', 'ALLOW_PENDING_LODGE', 'ALLOW_PENDING_LODGE', '1', '1');
--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (616, 'CHECKLIST_ITEM', 'UPDATE_DEFERRED', 'DEFERRED', 'PENDING_DEFER', 'PENDING_DEFER', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (616, 'CHECKLIST_ITEM', 'UPDATE_DEFERRED', 'DEFERRED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (639, 'CHECKLIST_ITEM', 'WAIVER', 'EXPIRED', 'PENDING_WAIVER', 'PENDING_WAIVER', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (683, 'CHECKLIST_ITEM', 'VIEW_LODGED', 'LODGED', 'LODGED', 'LODGED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (684, 'CHECKLIST_ITEM', 'TEMP_UPLIFT', 'LODGED', 'ALLOW_PENDING_TEMP_UPLIFT', 'ALLOW_PENDING_TEMP_UPLIFT', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (685, 'CHECKLIST_ITEM', 'PERM_UPLIFT', 'LODGED', 'ALLOW_PENDING_PERM_UPLIFT', 'ALLOW_PENDING_PERM_UPLIFT', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (689, 'CHECKLIST_ITEM', 'UPDATE_LODGED', 'LODGED', 'LODGED', 'LODGED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (694, 'CHECKLIST_ITEM', 'VIEW_PERM_UPLIFTED', 'PERM_UPLIFTED', 'PERM_UPLIFTED', 'PERM_UPLIFTED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (695, 'CHECKLIST_ITEM', 'VIEW_TEMP_UPLIFTED', 'TEMP_UPLIFTED', 'TEMP_UPLIFTED', 'TEMP_UPLIFTED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (643, 'CHECKLIST_ITEM', 'APPROVE', 'ALLOW_PENDING_LODGE', 'PENDING_LODGE', 'PENDING_LODGE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (644, 'CHECKLIST_ITEM', 'VIEW_PENDING_LODGE', 'PENDING_LODGE', 'PENDING_LODGE', 'PENDING_LODGE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (686, 'CHECKLIST_ITEM', 'VIEW_PENDING_TEMP_UPLIFT', 'PENDING_TEMP_UPLIFT', 'PENDING_TEMP_UPLIFT', 'PENDING_TEMP_UPLIFT', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (687, 'CHECKLIST_ITEM', 'APPROVE', 'ALLOW_PENDING_TEMP_UPLIFT', 'PENDING_TEMP_UPLIFT', 'PENDING_TEMP_UPLIFT', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (696, 'CHECKLIST_ITEM', 'VIEW_PENDING_PERM_UPLIFT', 'PENDING_PERM_UPLIFT', 'PENDING_PERM_UPLIFT', 'PENDING_PERM_UPLIFT', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (697, 'CHECKLIST_ITEM', 'APPROVE', 'ALLOW_PENDING_PERM_UPLIFT', 'PENDING_PERM_UPLIFT', 'PENDING_PERM_UPLIFT', '1', '1');
--Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (698, 'CHECKLIST_ITEM', 'LODGE', 'TEMP_UPLIFTED', 'ALLOW_PENDING_RELODGE', 'ALLOW_PENDING_RELODGE', '1', '1');
--Redeem
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (605, 'CHECKLIST_ITEM', 'REDEEM', 'AWAITING', 'PENDING_REDEEM', 'PENDING_REDEEM', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (607, 'CHECKLIST_ITEM', 'VIEW_PENDING_REDEEM', 'PENDING_REDEEM', 'PENDING_REDEEM', 'PENDING_REDEEM', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (608, 'CHECKLIST_ITEM', 'APPROVE', 'PENDING_REDEEM', 'REDEEMED', 'REDEEMED', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (612, 'CHECKLIST_ITEM', 'VIEW_REDEEMED', 'REDEEMED', 'REDEEMED', 'REDEEMED', '1', '1');
-- Change the temp_uplifted -> pending_lodge -> lodged ===============> temp_uplifted -> pending_relodge -> lodge instead
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (698, 'CHECKLIST_ITEM', 'LODGE', 'TEMP_UPLIFTED', 'PENDING_RELODGE', 'PENDING_RELODGE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (681, 'CHECKLIST_ITEM', 'VIEW_PENDING_RELODGE', 'PENDING_RELODGE', 'PENDING_RELODGE', 'PENDING_RELODGE', '1', '1');
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (682, 'CHECKLIST_ITEM', 'APPROVE', 'PENDING_RELODGE', 'LODGED', 'LODGED', '1', '1');

--
Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (8901, 'CHECKLIST_ITEM','VIEW_PENDING_LODGE','ALLOW_PENDING_RELODGE', 'ALLOW_PENDING_RELODGE', 'ALLOW_PENDING_RELODGE', '1', '1');

Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (8902, 'CHECKLIST_ITEM','APPROVE','ALLOW_PENDING_RELODGE', 'PENDING_RELODGE', 'PENDING_RELODGE','1', '1');

Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (8903, 'CHECKLIST_ITEM','LODGE', 'PERM_UPLIFTED','ALLOW_PENDING_RELODGE', 'ALLOW_PENDING_RELODGE','1', '1');

Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (8904, 'CHECKLIST_ITEM','LODGE', 'LODGED','ALLOW_PENDING_LODGE', 'ALLOW_PENDING_LODGE','1', '1');

Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (8905, 'CHECKLIST_ITEM','UPDATE', 'TEMP_UPLIFTED','PENDING_TEMP_UPDATE', 'PENDING_TEMP_UPDATE','1', '1');

Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (8906, 'CHECKLIST_ITEM', 'APPROVE','PENDING_TEMP_UPDATE', 'TEMP_UPLIFTED', 'TEMP_UPLIFTED','1', '1');

Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (8907, 'CHECKLIST_ITEM', 'UPDATE', 'PERM_UPLIFTED', 
'PENDING_PERM_UPDATE', 'PENDING_PERM_UPDATE','1', '1');

Insert into tr_state_matrix (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP) Values (8908, 'CHECKLIST_ITEM', 'APPROVE', 
'PENDING_PERM_UPDATE', 'PERM_UPLIFTED', 'PERM_UPLIFTED','1', '1');

-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1701, 'COLLATERAL_TASK', 'CREATE_COLLATERAL_TASK', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1702, 'COLLATERAL_TASK', 'APPROVE_CREATE_COLLATERAL_TASK', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1703, 'COLLATERAL_TASK', 'REJECT_COLLATERAL_TASK', 'PENDING_CREATE', 'REJECTED', 'REJECTED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1704, 'COLLATERAL_TASK', 'EDIT_REJECTED_CREATE_COLLATERAL_TASK', 'REJECTED', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1705, 'COLLATERAL_TASK', 'CLOSE_REJECTED_CREATE_COLLATERAL_TASK', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1706, 'COLLATERAL_TASK', 'UPDATE_COLLATERAL_TASK', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1707, 'COLLATERAL_TASK', 'APPROVE_UPDATE_COLLATERAL_TASK', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1708, 'COLLATERAL_TASK', 'REJECT_COLLATERAL_TASK', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1709, 'COLLATERAL_TASK', 'EDIT_REJECTED_UPDATE_COLLATERAL_TASK', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1710, 'COLLATERAL_TASK', 'CLOSE_REJECTED_UPDATE_COLLATERAL_TASK', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1711, 'COLLATERAL_TASK', 'MAKER_REJECT_COLLATERAL_TASK', 'ACTIVE', 'PENDING_REJECT', 'PENDING_REJECT', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1712, 'COLLATERAL_TASK', 'APPROVE_REJECTED_COLLATERAL_TASK', 'PENDING_REJECT', 'CLOSED', 'CLOSED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1713, 'COLLATERAL_TASK', 'REJECT_REJECTED_COLLATERAL_TASK', 'PENDING_REJECT', 'REJECT_REJECTED', 'REJECT_REJECTED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1714, 'COLLATERAL_TASK', 'CLOSE_REJECT_REJECTED_COLLATERAL_TASK', 'REJECT_REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1715, 'COLLATERAL_TASK', 'EDIT_REJECT_REJECTED_COLLATERAL_TASK', 'REJECT_REJECTED', 'PENDING_REJECT', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2800, 'CUSTODIAN', 'MAKER_SAVE', 'ND', 'DRAFT', 'DRAFT', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2801, 'CUSTODIAN', 'MAKER_SAVE', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2802, 'CUSTODIAN', 'MAKER_SAVE', 'REJECTED', 'DRAFT', 'DRAFT', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2803, 'CUSTODIAN', 'MAKER_SAVE', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2804, 'CUSTODIAN', 'MAKER_UPDATE', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2805, 'CUSTODIAN', 'MAKER_UPDATE', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2806, 'CUSTODIAN', 'MAKER_CREATE', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2807, 'CUSTODIAN', 'MAKER_CREATE', 'DRAFT', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2808, 'CUSTODIAN', 'MAKER_CLOSE_CREATE', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2809, 'CUSTODIAN', 'MAKER_CLOSE_CREATE', 'DRAFT', 'CLOSED', 'CLOSED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2810, 'CUSTODIAN', 'MAKER_CLOSE_UPDATE', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2811, 'CUSTODIAN', 'MAKER_CLOSE_UPDATE', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2812, 'CUSTODIAN', 'CHECKER_APPROVE_CREATE', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2813, 'CUSTODIAN', 'CHECKER_APPROVE_UPDATE', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2814, 'CUSTODIAN', 'CHECKER_REJECT_CREATE', 'PENDING_CREATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2815, 'CUSTODIAN', 'CHECKER_REJECT_UPDATE', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2816, 'CUSTODIAN', 'REQUIRED_ACTION', 'ND', 'REQUIRED_STATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2817, 'CUSTODIAN', 'REQUIRED_ACTION', 'ACTIVE', 'REQUIRED_STATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2818, 'CUSTODIAN', 'MAKER_CREATE', 'REQUIRED_STATE', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2819, 'CUSTODIAN', 'MAKER_UPDATE', 'REQUIRED_STATE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2820, 'CUSTODIAN', 'MAKER_SAVE', 'REQUIRED_STATE', 'DRAFT', 'DRAFT', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2821, 'CUSTODIAN', 'MAKER_CREATE', 'REJECTED', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (2822, 'CUSTODIAN', 'MAKER_UPDATE', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (2901, 'DDN', 'SYSTEM_CLOSE', 'PENDING_CREATE', 'CLOSED', 'CLOSED', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (2902, 'DDN', 'SYSTEM_CLOSE', 'PENDING_UPDATE', 'CLOSED', 'CLOSED', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (2903, 'DDN', 'SYSTEM_CLOSE', 'ACTIVE', 'CLOSED', 'CLOSED', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (2904, 'DDN', 'SYSTEM_CLOSE', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (2905, 'DDN', 'SYSTEM_CLOSE', 'NEW', 'CLOSED', 'CLOSED', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (2906, 'DDN', 'SYSTEM_CREATE_DDN', 'ND', 'NEW', 'NEW', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (2907, 'DDN', 'GENERATE_DDN', 'NEW', 'PENDING_CREATE', 'PENDING_UPDATE', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (2908, 'DDN', 'GENERATE_DDN', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (2909, 'DDN', 'APPROVE_GENERATE_DDN', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (2910, 'DDN', 'REJECT_GENERATE_DDN', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (2911, 'DDN', 'CLOSE_REJECTED_CREATE_GENERATE_DDN', 'REJECTED', 'NEW', 'NEW', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (2912, 'DDN', 'CLOSE_REJECTED_UPDATE_GENERATE_DDN', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (2913, 'DDN', 'EDIT_REJECTED_CREATE_GENERATE_DDN', 'REJECTED', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (2914, 'DDN', 'EDIT_REJECTED_UPDATE_GENERATE_DDN', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (2915, 'DDN', 'APPROVE_GENERATE_DDN', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (2916, 'DDN', 'REJECT_GENERATE_DDN', 'PENDING_CREATE', 'REJECTED', 'REJECTED', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (2917, 'DDN', 'GENERATE_DDN', 'ND', 'PENDING_CREATE', 'PENDING_UPDATE', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (1200, 'PSCC', 'GENERATE_PSCC', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (1201, 'PSCC', 'GENERATE_PSCC', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (1202, 'PSCC', 'APPROVE_GENERATE_PSCC', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (1203, 'PSCC', 'APPROVE_GENERATE_PSCC', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (1204, 'PSCC', 'REJECT_GENERATE_PSCC', 'PENDING_CREATE', 'REJECTED', 'REJECTED', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (1205, 'PSCC', 'REJECT_GENERATE_PSCC', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (1206, 'PSCC', 'EDIT_REJECTED_CREATE_GENERATE_PSCC', 'REJECTED', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (1207, 'PSCC', 'EDIT_REJECTED_UPDATE_GENERATE_PSCC', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (1208, 'PSCC', 'CLOSE_REJECTED_CREATE_GENERATE_PSCC', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (1209, 'PSCC', 'CLOSE_REJECTED_UPDATE_GENERATE_PSCC', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (1210, 'PSCC', 'SYSTEM_PSCC_CLOSE', 'PENDING_CREATE', 'CLOSED', 'CLOSED', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (1211, 'PSCC', 'SYSTEM_PSCC_CLOSE', 'PENDING_UPDATE', 'CLOSED', 'CLOSED', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (1212, 'PSCC', 'SYSTEM_PSCC_CLOSE', 'ACTIVE', 'CLOSED', 'CLOSED', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (1213, 'PSCC', 'SYSTEM_PSCC_CLOSE', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (1214, 'PSCC', 'SYSTEM_PSCC_RESET', 'PENDING_CREATE', 'CLOSED', 'CLOSED', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (1215, 'PSCC', 'SYSTEM_PSCC_RESET', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (1216, 'PSCC', 'SYSTEM_PSCC_RESET', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
 Insert into tr_state_matrix
    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
  Values
    (1217, 'PSCC', 'SYSTEM_PSCC_RESET', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');

-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1500, 'RECURRENT_CHECKLIST', 'CREATE_RECURRENT_CHECKLIST', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1501, 'RECURRENT_CHECKLIST', 'APPROVE_CREATE_RECURRENT_CHECKLIST', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1502, 'RECURRENT_CHECKLIST', 'REJECT_RECURRENT_CHECKLIST', 'PENDING_CREATE', 'REJECTED', 'REJECTED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1503, 'RECURRENT_CHECKLIST', 'EDIT_REJECTED_CREATE_RECURRENT_CHECKLIST', 'REJECTED', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1504, 'RECURRENT_CHECKLIST', 'CLOSE_REJECTED_CREATE_RECURRENT_CHECKLIST', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1505, 'RECURRENT_CHECKLIST', 'UPDATE_RECURRENT_CHECKLIST', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1506, 'RECURRENT_CHECKLIST', 'REJECT_RECURRENT_CHECKLIST', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1507, 'RECURRENT_CHECKLIST', 'EDIT_REJECTED_UPDATE_RECURRENT_CHECKLIST', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1508, 'RECURRENT_CHECKLIST', 'APPROVE_UPDATE_RECURRENT_CHECKLIST', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1509, 'RECURRENT_CHECKLIST', 'CLOSE_REJECTED_UPDATE_RECURRENT_CHECKLIST', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1510, 'RECURRENT_CHECKLIST', 'REJECT_RECURRENT_CHECKLIST_RECEIPT', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1511, 'RECURRENT_CHECKLIST', 'UPDATE_RECURRENT_CHECKLIST_RECEIPT', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1512, 'RECURRENT_CHECKLIST', 'EDIT_REJECTED_UPDATE_RECURRENT_CHECKLIST_RECEIPT', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1513, 'RECURRENT_CHECKLIST', 'APPROVE_UPDATE_RECURRENT_CHECKLIST_RECEIPT', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1514, 'RECURRENT_CHECKLIST', 'CLOSE_REJECTED_UPDATE_RECURRENT_CHECKLIST_RECEIPT', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1515, 'RECURRENT_CHECKLIST', 'SYSTEM_CLOSE_RECURRENT_CHECKLIST', 'ACTIVE', 'CLOSED', 'CLOSED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1516, 'RECURRENT_CHECKLIST', 'SYSTEM_CLOSE_RECURRENT_CHECKLIST', 'PENDING_CREATE', 'CLOSED', 'CLOSED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1517, 'RECURRENT_CHECKLIST', 'SYSTEM_CLOSE_RECURRENT_CHECKLIST', 'PENDING_UPDATE', 'CLOSED', 'CLOSED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1518, 'RECURRENT_CHECKLIST', 'SYSTEM_CLOSE_RECURRENT_CHECKLIST', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1519, 'RECURRENT_CHECKLIST', 'CLOSE_DRAFT_RECURRENT_CHECKLIST_RECEIPT', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1520, 'RECURRENT_CHECKLIST', 'SAVE_RECURRENT_CHECKLIST_RECEIPT', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1521, 'RECURRENT_CHECKLIST', 'SAVE_RECURRENT_CHECKLIST_RECEIPT', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1522, 'RECURRENT_CHECKLIST', 'SAVE_RECURRENT_CHECKLIST_RECEIPT', 'REJECTED', 'DRAFT', 'DRAFT', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1523, 'RECURRENT_CHECKLIST', 'UPDATE_RECURRENT_CHECKLIST_RECEIPT', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1524, 'RECURRENT_CHECKLIST', 'SAVE_CREATE_RECURRENT_CHECKLIST', 'ND', 'DRAFT', 'DRAFT', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1525, 'RECURRENT_CHECKLIST', 'DRAFT_CREATE_RECURRENT_CHECKLIST', 'DRAFT', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1526, 'RECURRENT_CHECKLIST', 'DRAFT_SAVE_RECURRENT_CHECKLIST', 'DRAFT', 'DRAFT', 'DRAFT', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1527, 'RECURRENT_CHECKLIST', 'CLOSE_DRAFT_CREATE_RECURRENT_CHECKLIST', 'DRAFT', 'CLOSE', 'CLOSE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1528, 'RECURRENT_CHECKLIST', 'DRAFT_SAVE_RECURRENT_CHECKLIST', 'REJECTED', 'DRAFT', 'DRAFT', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1529, 'RECURRENT_CHECKLIST', 'DRAFT_UPDATE_RECURRENT_CHECKLIST', 'DRAFT', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1530, 'RECURRENT_CHECKLIST', 'SAVE_ACTIVE_RECURRENT_CHECKLIST', 'ACTIVE', 'DRAFT', 'DRAFT', '1', '1');
-- Insert into tr_state_matrix
--    (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
--  Values
--    (1531, 'RECURRENT_CHECKLIST', 'CLOSE_DRAFT_ACTIVE_RECURRENT_CHECKLIST', 'DRAFT', 'ACTIVE', 'ACTIVE', '1', '1');

Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1300, 'SCC', 'GENERATE_SCC', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1301, 'SCC', 'GENERATE_SCC', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1302, 'SCC', 'APPROVE_GENERATE_SCC', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1303, 'SCC', 'APPROVE_GENERATE_SCC', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1304, 'SCC', 'REJECT_GENERATE_SCC', 'PENDING_CREATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1305, 'SCC', 'REJECT_GENERATE_SCC', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1306, 'SCC', 'EDIT_REJECTED_CREATE_GENERATE_SCC', 'REJECTED', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1307, 'SCC', 'EDIT_REJECTED_UPDATE_GENERATE_SCC', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1308, 'SCC', 'CLOSE_REJECTED_CREATE_GENERATE_SCC', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1309, 'SCC', 'CLOSE_REJECTED_UPDATE_GENERATE_SCC', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1310, 'SCC', 'SYSTEM_SCC_CLOSE', 'PENDING_CREATE', 'CLOSED', 'CLOSED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1311, 'SCC', 'SYSTEM_SCC_CLOSE', 'PENDING_UPDATE', 'CLOSED', 'CLOSED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1312, 'SCC', 'SYSTEM_SCC_CLOSE', 'ACTIVE', 'CLOSED', 'CLOSED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1313, 'SCC', 'SYSTEM_SCC_CLOSE', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1314, 'SCC', 'SYSTEM_SCC_RESET', 'PENDING_CREATE', 'CLOSED', 'CLOSED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1315, 'SCC', 'SYSTEM_SCC_RESET', 'ACTIVE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1316, 'SCC', 'SYSTEM_SCC_RESET', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (1317, 'SCC', 'SYSTEM_SCC_RESET', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3400, 'TEMPLATE', 'CREATE_TEMPLATE', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3401, 'TEMPLATE', 'APPROVE_CREATE_TEMPLATE', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3402, 'TEMPLATE', 'REJECT_TEMPLATE', 'PENDING_CREATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3403, 'TEMPLATE', 'EDIT_REJECTED_CREATE_TEMPLATE', 'REJECTED', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3404, 'TEMPLATE', 'CLOSE_REJECTED_CREATE_TEMPLATE', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3405, 'TEMPLATE', 'UPDATE_TEMPLATE', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3406, 'TEMPLATE', 'REJECT_TEMPLATE', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3407, 'TEMPLATE', 'EDIT_REJECTED_UPDATE_TEMPLATE', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3408, 'TEMPLATE', 'APPROVE_UPDATE_TEMPLATE', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3409, 'TEMPLATE', 'CLOSE_REJECTED_UPDATE_TEMPLATE', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');
   
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (20, 'DOCITEM', 'CREATE_DOC_ITEM', 'ND', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (21, 'DOCITEM', 'APPROVE_CREATE_DOC_ITEM', 'PENDING_CREATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (22, 'DOCITEM', 'REJECT_DOC_ITEM', 'PENDING_CREATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (23, 'DOCITEM', 'CLOSE_REJECTED_CREATE_DOC_ITEM', 'REJECTED', 'CLOSED', 'CLOSED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (24, 'DOCITEM', 'EDIT_REJECTED_CREATE_DOC_ITEM', 'REJECTED', 'PENDING_CREATE', 'PENDING_CREATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (25, 'DOCITEM', 'UPDATE_DOC_ITEM', 'ACTIVE', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (26, 'DOCITEM', 'APPROVE_UPDATE_DOC_ITEM', 'PENDING_UPDATE', 'ACTIVE', 'ACTIVE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (27, 'DOCITEM', 'REJECT_DOC_ITEM', 'PENDING_UPDATE', 'REJECTED', 'REJECTED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (28, 'DOCITEM', 'EDIT_REJECTED_UPDATE_DOC_ITEM', 'REJECTED', 'PENDING_UPDATE', 'PENDING_UPDATE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (29, 'DOCITEM', 'CLOSE_REJECTED_UPDATE_DOC_ITEM', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');

   
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3025, 'DOCITEM', 'DELETE_DOC_ITEM', 'ACTIVE', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3026, 'DOCITEM', 'APPROVE_DELETE_DOC_ITEM', 'PENDING_DELETE', 'DELETED', 'DELETED', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3028, 'DOCITEM', 'EDIT_REJECTED_DELETE_DOC_ITEM', 'REJECTED', 'PENDING_DELETE', 'PENDING_DELETE', '1', '1');
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3029, 'DOCITEM', 'CLOSE_REJECTED_DELETE_DOC_ITEM', 'REJECTED', 'ACTIVE', 'ACTIVE', '1', '1');   
Insert into tr_state_matrix
   (STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE, ENABLEIND, FRONTENDOP)
 Values
   (3027, 'DOCITEM', 'REJECT_DOC_ITEM', 'PENDING_DELETE', 'REJECTED', 'REJECTED', '1', '1');   
   
   
COMMIT WORK;

