/********************************
CMS_DOC_DYNAMIC_PROPERTY_SETUP
********************************/

insert into CMS_DOC_DYNAMIC_PROPERTY_SETUP 
(SETUP_ID, SECURITY_SUB_TYPE_ID, PROPERTY_NAME, PROPERTY_LABEL, CATEGORY_CODE, INPUT_TYPE)
Values (1, 'AB102', 'GoodsStatus', 'label.goodsstatus', 'GOODS_STATUS', 'CB'); 

insert into CMS_DOC_DYNAMIC_PROPERTY_SETUP 
(SETUP_ID, SECURITY_SUB_TYPE_ID, PROPERTY_NAME, PROPERTY_LABEL, CATEGORY_CODE, INPUT_TYPE)
Values (2, 'AB102', 'PbtPbr', 'label.pbtpbr', 'PBR_PBT_IND', 'CB'); 

INSERT INTO CMS_LI_DOC(LI_TEMPLATE_ID, LI_TEMPLATE_NAME, GENERATED_BY, GENERATED_DATE, CHECKLIST_ID, FILE_LOC) 
    VALUES(1, 'Letter of Instruction to Solicitor', '', null, 0, '');

INSERT INTO CMS_LI_DOC(LI_TEMPLATE_ID, LI_TEMPLATE_NAME, GENERATED_BY, GENERATED_DATE, CHECKLIST_ID, FILE_LOC) 
    VALUES(2, 'Letter of Instruction to Valuers', '', null, 0, '');

INSERT INTO CMS_LI_DOC(LI_TEMPLATE_ID, LI_TEMPLATE_NAME, GENERATED_BY, GENERATED_DATE, CHECKLIST_ID, FILE_LOC) 
    VALUES(3, 'Letter of Instruction to Insurers', '', null, 0, '');