
-- =================== 
-- CMS_FUNCTION_ACCESS
-- ===================

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000013,'OtherBank','view_other_bank',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000014,'OtherBank','view_other_bank_by_index',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000015,'OtherBank','prepare_maker_submit_edit',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000016,'OtherBank','prepare_maker_submit_remove',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000017,'OtherBank','maker_submit_edit',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000018,'OtherBank','maker_submit_remove',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000019,'OtherBank','search_other_bank',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000020,'OtherBank','prepare_create_other_bank',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000021,'OtherBank','maker_submit_create_other_bank',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000022,'OtherBank','checker_edit_read',7);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000023,'OtherBank','maker_edit_otherBank',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000024,'OtherBank','maker_prepare_close',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000025,'OtherBank','maker_prepare_resubmit',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000026,'OtherBank','rejected_read',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000027,'OtherBank','checker_approve_edit',7);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000028,'OtherBank','rejected_delete_read',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000029,'OtherBank','checker_reject_edit',7);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000030,'OtherBank','checker_process_create',7);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000041,'OtherBank','checker_process_delete',7);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000042,'OtherBank','maker_prepare_resubmit_create',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000043,'OtherBank','maker_prepare_close',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000044,'OtherBank','rejected_delete_read',7);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000045,'OtherBank','maker_confirm_close',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000046,'OtherBank','maker_confirm_resubmit_edit',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000047,'OtherBank','checker_process_edit',7);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000048,'OtherBank','maker_update_save_process',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000049,'OtherBank','maker_draft_close_process',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000050,'OtherBank','maker_confirm_draft_close',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000081,'OtherBank','maker_confirm_resubmit_draft',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000082,'OtherBank','maker_save_update_other_bank',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000083,'OtherBank','maker_save_process',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000084,'OtherBank','maker_confirm_resubmit_update',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000085,'OtherBank','maker_update_save_process',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
	VALUES (229000086,'OtherBank','maker_save_create_other_bank',6);




INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000031,'OtherBranch','view_other_branch',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000032,'OtherBranch','view_other_branch_by_index',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000033,'OtherBranch','prepare_edit_branch',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000034,'OtherBranch','prepare_maker_submit_remove_branch',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000035,'OtherBranch','maker_submit_remove_branch',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000036,'OtherBranch','maker_submit_edit_branch',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000037,'OtherBranch','search_other_branch',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000038,'OtherBranch','prepare_create_other_bank_branch',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000039,'OtherBranch','maker_submit_create_other_bank_branch',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000051,'OtherBranch','checker_process_create',7);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000052,'OtherBranch','checker_edit_read',7);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000053,'OtherBranch','checker_process_create',7);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000054,'OtherBranch','checker_process_delete',7);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000055,'OtherBranch','checker_process_edit',7);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000056,'OtherBranch','maker_confirm_close',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000057,'OtherBranch','maker_confirm_resubmit_edit',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000058,'OtherBranch','maker_edit_otherBankBranch',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000059,'OtherBranch','maker_prepare_close',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000060,'OtherBranch','maker_prepare_close',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000061,'OtherBranch','maker_prepare_resubmit',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000062,'OtherBranch','maker_prepare_resubmit_create',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000063,'OtherBranch','maker_submit_create_other_bank_branch',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000064,'OtherBranch','maker-submit_edit',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000065,'OtherBranch','maker_submit_remove',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000066,'OtherBranch','prepare_create_other_bank_branch',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000067,'OtherBranch','prepare_maker-submit_edit',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000068,'OtherBranch','prepare_maker_submit_remove',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000069,'OtherBranch','rejected_delete_read',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000070,'OtherBranch','rejected_delete_read',7);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000071,'OtherBranch','rejected_read',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000072,'OtherBranch','search_other_bank_branch',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000073,'OtherBranch','view_other_bank_branch',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000074,'OtherBranch','view_other_bank_branch_index',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000075,'OtherBranch','checker_approve_edit',7);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000076,'OtherBranch','checker_reject_edit',7);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000087,'OtherBranch','maker_save_create_other_bank_branch',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000088,'OtherBranch','maker_update_save_process',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000089,'OtherBranch','maker_draft_close_process',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000090,'OtherBranch','maker_confirm_draft_close',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000091,'OtherBranch','maker_confirm_resubmit_draft',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000092,'OtherBranch','maker_save_update_other_bank_branch',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000093,'OtherBranch','maker_save_process',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)
	VALUES(229000094,'OtherBranch','maker_confirm_resubmit_update',6);
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE)]
	VALUES(229000095,'OtherBranch','maker_update_save_process',6);
	
	
-- ================= 
-- CMS_TRX_TOTRACK
-- =================

insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values('OTHER_BANK','OtherBank.do?event=rejected_delete_read&toTrack=yes&TrxId=','DELETED','Deleted','Maintain Other Bank',null,null);
insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values('OTHER_BANK','OtherBank.do?event=rejected_delete_read&toTrack=yes&TrxId=','DRAFT','Draft','Maintain Other Bank',null,null);
insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values('OTHER_BANK','OtherBank.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_CREATE','Pending Create','Maintain Other Bank',null,null);
insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values('OTHER_BANK','OtherBank.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_DELETE','Pending Delete','Maintain Other Bank',null,null);
insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values('OTHER_BANK','OtherBank.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_UPDATE','Pending Update','Maintain Other Bank',null,null);
insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values('OTHER_BANK','OtherBank.do?event=rejected_delete_read&toTrack=yes&TrxId=','REJECTED','Rejected','Maintain Other Bank',null,null);	

insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values('OTHER_BANK_BRANCH','OtherBranch.do?event=rejected_delete_read&toTrack=yes&TrxId=','DELETED','Deleted','Maintain Other Bank Branch',null,null);
insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values('OTHER_BANK_BRANCH','OtherBranch.do?event=rejected_delete_read&toTrack=yes&TrxId=','DRAFT','Draft','Maintain Other Bank Branch',null,null);
insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values('OTHER_BANK_BRANCH','OtherBranch.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_CREATE','Pending Create','Maintain Other Bank Branch',null,null);
insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values('OTHER_BANK_BRANCH','OtherBranch.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_DELETE','Pending Delete','Maintain Other Bank Branch',null,null);
insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values('OTHER_BANK_BRANCH','OtherBranch.do?event=rejected_delete_read&toTrack=yes&TrxId=','PENDING_UPDATE','Pending Update','Maintain Other Bank Branch',null,null);
insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,	TOTRACK_URL,	CURR_STATE,	USER_STATE,	USER_TRX_TYPE,	FROM_STATE,	TRANSACTION_SUBTYPE) 
values('OTHER_BANK_BRANCH','OtherBranch.do?event=rejected_delete_read&toTrack=yes&TrxId=','REJECTED','Rejected','Maintain Other Bank Branch',null,null);


-- ================= 
-- TR_STATE_MATRIX
-- =================

insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
	values (7551,'OTHER_BANK','EDIT_REJECTED_DELETE','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7552,'OTHER_BANK','CREATE_OTHER_BANK','PENDING_CREATE','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7553,'OTHER_BANK','APROVE_OTHER_BANK','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7554,'OTHER_BANK','UPDATE_OTHER_BANK','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7555,'OTHER_BANK','APPROVE_CREATE_OTHER_BANK','PENDING_CREATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7556,'OTHER_BANK','REJECT_OTHER_BANK','PENDING_UPDATE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7557,'OTHER_BANK','EDIT_REJECTED_UPDATE_OTHER_BANK','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7558,'OTHER_BANK','CLOSE_REJECTED_UPDATE_OTHER_BANK','REJECTED','CLOSED','CLOSED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7559,'OTHER_BANK','REJECT_OTHER_BANK','PENDING_CREATE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7560,'OTHER_BANK','CLOSE_REJECTED_CREATE_OTHER_BANK','REJECTED','CLOSED','CLOSED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7561,'OTHER_BANK','EDIT_REJECTED_CREATE_OTHER_BANK','REJECTED','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7562,'OTHER_BANK','DELETE_OTHER_BANK','ACTIVE','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7563,'OTHER_BANK','DELETE_OTHER_BANK','PENDING_DELETE','DELETED','DELETED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 	
	VALUES(7564,'OTHER_BANK','REJECT_OTHER_BANK','PENDING_DELETE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7566,'OTHER_BANK','CLOSE_REJECTED_OTHER_BANK','REJECTED','CLOSED','CLOSED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7567,'OTHER_BANK','UPDATE_OTHER_BANK','PENDING_UPDATE','ACTIVE','PENDING_UPDATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7568,'OTHER_BANK','CHECKER_APPROVE_UPDATE','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7569,'OTHER_BANK','CHECKER_APPROVE_DELETE','PENDING_DELETE','DELETED','DELETED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7570,'OTHER_BANK','APPROVE_OTHER_BANK','PENDING_DELETE','DELETED','DELETED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7571,'OTHER_BANK','CHECKER_APPROVE_UPDATE','PENDING_DELETE','DELETED','DELETED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7572,'OTHER_BANK','CREATE_OTHER_BANK','ND','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7573,'OTHER_BANK','CLOSE_REJECTED_DELETE_OTHER_BANK','REJECTED','CLOSED','CLOSED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7574,'OTHER_BANK','DELETE_OTHER_BANK','CLOSED','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7575,'OTHER_BANK','APPROVE_DELETE_OTHER_BANK','PENDING_DELETE','DELETED','DELETED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7614,'OTHER_BANK','CREATE_OTHER_BANK','ACTIVE','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7615,'OTHER_BANK','EDIT_REJECTED_DELETE_OTHER_BANK','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7616,'OTHER_BANK','EDIT_REJECTED_OTHER_BANK','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7617,'OTHER_BANK','EDIT_REJECTED_OTHER_BANK','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7618,'OTHER_BANK','SAVE_OTHER_BANK','PENDING_PERFECTION','DRAFT','DRAFT','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7619,'OTHER_BANK','CREATE_OTHER_BANK','DRAFT','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7620,'OTHER_BANK','MAKER_UPDATE_SAVE','ACTIVE','DRAFT','DRAFT','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7621,'OTHER_BANK','UPDATE_OTHER_BANK','DRAFT','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7622,'OTHER_BANK','MAKER_UPDATE_CLOSE','DRAFT','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7623,'OTHER_BANK','CLOSE_CREATE_OTHER_BANK','DRAFT','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7624,'OTHER_BANK','SAVE_UPDATE_OTHER_BANK','ACTIVE','DRAFT','DRAFT','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7625,'OTHER_BANK','SAVE_UPDATE_OTHER_BANK','CLOSED','DRAFT','DRAFT','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
	VALUES(7626,'OTHER_BANK','SAVE_UPDATE_OTHER_BANK','REJECTED','DRAFT','DRAFT','1','1');

	
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7576,'OTHER_BANK_BRANCH','EDIT_REJECTED_DELETE','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7577,'OTHER_BANK_BRANCH','CREATE_OTHER_BANK_BRANCH','PENDING_CREATE','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7578,'OTHER_BANK_BRANCH','APROVE_OTHER_BANK_BRANCH','PENDING_CREATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7579,'OTHER_BANK_BRANCH','UPDATE_OTHER_BANK_BRANCH','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7580,'OTHER_BANK_BRANCH','APPROVE_CREATE_OTHER_BANK_BRANCH','PENDING_CREATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7581,'OTHER_BANK_BRANCH','REJECT_OTHER_BANK_BRANCH','PENDING_UPDATE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7582,'OTHER_BANK_BRANCH','EDIT_REJECTED_UPDATE_OTHER_BANK_BRANCH','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7583,'OTHER_BANK_BRANCH','CLOSE_REJECTED_UPDATE_OTHER_BANK_BRANCH','REJECTED','CLOSED','CLOSED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7584,'OTHER_BANK_BRANCH','REJECT_OTHER_BANK_BRANCH','PENDING_CREATE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7585,'OTHER_BANK_BRANCH','CLOSE_REJECTED_CREATE_OTHER_BANK_BRANCH','REJECTED','CLOSED','CLOSED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7586,'OTHER_BANK_BRANCH','EDIT_REJECTED_CREATE_OTHER_BANK_BRANCH','REJECTED','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7587,'OTHER_BANK_BRANCH','DELETE_OTHER_BANK_BRANCH','ACTIVE','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7588,'OTHER_BANK_BRANCH','DELETE_OTHER_BANK_BRANCH','PENDING_DELETE','DELETED','DELETED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7589,'OTHER_BANK_BRANCH','REJECT_OTHER_BANK_BRANCH','PENDING_DELETE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7590,'OTHER_BANK_BRANCH','CLOSE_REJECTED_OTHER_BANK_BRANCH','REJECTED','CLOSED','CLOSED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7591,'OTHER_BANK_BRANCH','UPDATE_OTHER_BANK_BRANCH','PENDING_UPDATE','ACTIVE','PENDING_UPDATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7592,'OTHER_BANK_BRANCH','CHECKER_APPROVE_UPDATE','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7593,'OTHER_BANK_BRANCH','CHECKER_APPROVE_DELETE','PENDING_DELETE','DELETED','DELETED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7594,'OTHER_BANK_BRANCH','APPROVE_OTHER_BANK_BRANCH','PENDING_DELETE','DELETED','DELETED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7595,'OTHER_BANK_BRANCH','CHECKER_APPROVE_UPDATE','PENDING_DELETE','DELETED','DELETED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7596,'OTHER_BANK_BRANCH','CREATE_OTHER_BANK_BRANCH','ND','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7597,'OTHER_BANK_BRANCH','CLOSE_REJECTED_DELETE_OTHER_BANK_BRANCH','REJECTED','CLOSED','CLOSED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7598,'OTHER_BANK_BRANCH','DELETE_OTHER_BANK_BRANCH','CLOSED','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7599,'OTHER_BANK_BRANCH','APPROVE_DELETE_OTHER_BANK_BRANCH','PENDING_DELETE','DELETED','DELETED','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7611,'OTHER_BANK_BRANCH','EDIT_REJECTED_OTHER_BANK_BRANCH','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES  (7612,'OTHER_BANK_BRANCH','EDIT_REJECTED_OTHER_BANK_BRANCH','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7613,'OTHER_BANK_BRANCH','EDIT_REJECTED_DELETE_OTHER_BANK_BRANCH','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7630,'OTHER_BANK_BRANCH','SAVE_OTHER_BANK_BRANCH','PENDING_PERFECTION','DRAFT','DRAFT','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7631,'OTHER_BANK_BRANCH','CREATE_OTHER_BANK_BRANCH','DRAFT','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7632,'OTHER_BANK_BRANCH','MAKER_UPDATE_SAVE','ACTIVE','DRAFT','DRAFT','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7633,'OTHER_BANK_BRANCH','UPDATE_OTHER_BANK_BRANCH','DRAFT','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP ) 
VALUES  (7634,'OTHER_BANK_BRANCH','MAKER_UPDATE_CLOSE','DRAFT','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7635,'OTHER_BANK_BRANCH','CLOSE_CREATE_OTHER_BANK_BRANCH','DRAFT','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7636,'OTHER_BANK_BRANCH','SAVE_UPDATE_OTHER_BANK_BRANCH','ACTIVE','DRAFT','DRAFT','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7637,'OTHER_BANK_BRANCH','SAVE_UPDATE_OTHER_BANK_BRANCH','CLOSED','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )  
VALUES  (7638,'OTHER_BANK_BRANCH','CLOSE_CREATE_OTHER_BANK_BRANCH','REJECTED','CLOSED','CLOSED','1','1');
	
-- ================= 
-- TR_STATE_MATRIX
-- =================

insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7551,6,'Process','OtherBank.do?event=maker_prepare_resubmit&TrxId=','OtherBank.do?event=to_track&TrxId=');
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7552,7,'Process','OtherBank.do?event=checker_process_create&TrxId=',null);
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7557,6,'Process','OtherBank.do?event=maker_prepare_resubmit_create&TrxId=',null);
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7556,7,'Process','OtherBank.do?event=checker_edit_read&TrxId=',null);
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7558,6,'Process','OtherBank.do?event=maker_prepare_resubmit_create&TrxId=',null);
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7561,6,'Close','OtherBank.do?event=maker_prepare_close&TrxId=',null);
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7563,7,'Process','OtherBank.do?event=checker_process_delete&TrxId=',null);
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7567,7,'Process','OtherBank.do?event=checker_process_edit&TrxId=','OtherBank.do?event=to_track&TrxId=');
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7623,6,'Process','OtherBank.do?event=maker_update_save_process&TrxId=',null);
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7618,6,'Process','OtherBank.do?event=maker_update_save_process&TrxId=',null);
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7619,6,'Process','OtherBank.do?event=maker_update_save_process&TrxId=',null);
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7622,6,'Close','OtherBank.do?event=maker_draft_close_process&TrxId=',null);
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7621,6,'Process','OtherBank.do?event=maker_update_save_process&TrxId=',null);


insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7576,6,'Process','OtherBranch.do?event=maker_prepare_resubmit&TrxId=','OtherBranch.do?event=to_track&TrxId=');
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7577,7,'Process','OtherBranch.do?event=checker_process_create&TrxId=',null);
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7582,6,'Process','OtherBranch.do?event=maker_prepare_resubmit_create&TrxId=',null);
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7581,7,'Process','OtherBranch.do?event=checker_edit_read&TrxId=',null);
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7583,6,'Process','OtherBranch.do?event=maker_prepare_resubmit_create&TrxId=',null);
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7586,6,'Close','OtherBranch.do?event=maker_prepare_close&TrxId=',null);
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7588,7,'Process','OtherBranch.do?event=checker_process_delete&TrxId=',null);
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7591,7,'Process','OtherBranch.do?event=checker_process_edit&TrxId=','OtherBranch.do?event=to_track&TrxId=');
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7630,6,'Process','OtherBranch.do?event=maker_update_save_process&TrxId=',null);
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7631,6,'Process','OtherBranch.do?event=maker_update_save_process&TrxId=',null);
insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
values (7634,6,'Close','OtherBranch.do?event=maker_draft_close_process&TrxId=',null);

