--------------------------------
--- CMS_INSURANCE_COVERAGE_DTLS 
--------------------------------

CREATE TABLE CMS_INSURANCE_COVERAGE_DTLS (
		  ID BIGINT NOT NULL , 
		  'INSURANCE_COVERAGE_CODE' VARCHAR(10) NOT NULL,
		  'INSURANCE_TYPE' VARCHAR(20) NOT NULL,
		  'CATEGORY_NAME' VARCHAR(20) NOT NULL,	 
		  	  
		  'VERSION_TIME' BIGINT NOT NULL , 
		  'CREATE_BY' VARCHAR(25) NOT NULL , 
		  'CREATION_DATE' TIMESTAMP NOT NULL , 
		  'LAST_UPDATE_BY' VARCHAR(25) NOT NULL , 
		  'LAST_UPDATE_DATE' TIMESTAMP NOT NULL , 
		  'DEPRECATED' CHAR(1) NOT NULL , 
		  'STATUS' VARCHAR(30) NOT NULL )   
		 IN CMS_SMALL_DATA INDEX IN CMS_INDEX ; 



ALTER TABLE CMS_INSURANCE_COVERAGE_DTLS 
	ADD CONSTRAINT PK_INSURANCE_COVERAGE_DTLS PRIMARY KEY
		(ID);
		

-------------------------------------
--- CMS_STAGE_INSURANCE_COVERAGE_DTLS 
-------------------------------------


CREATE TABLE CMS_STAGE_INSURANCE_COVERAGE_DTLS  (		   
		  ID BIGINT NOT NULL , 
		  'INSURANCE_COVERAGE_CODE' VARCHAR(10) NOT NULL,
		  'INSURANCE_TYPE' VARCHAR(20) NOT NULL,
		  'CATEGORY_NAME' VARCHAR(20) NOT NULL,	  
		  'VERSION_TIME' BIGINT NOT NULL , 
		  'CREATE_BY' VARCHAR(25) NOT NULL , 
		  'CREATION_DATE' TIMESTAMP NOT NULL , 
		  'LAST_UPDATE_BY' VARCHAR(25) NOT NULL , 
		  'LAST_UPDATE_DATE' TIMESTAMP NOT NULL , 
		  'DEPRECATED' CHAR(1) NOT NULL , 
		  'STATUS' VARCHAR(30) NOT NULL ) 
		 IN CMS_SMALL_DATA INDEX IN CMS_INDEX ;

ALTER TABLE CMS_STAGE_INSURANCE_COVERAGE_DTLS  
	ADD CONSTRAINT PK_INSURANCE_COVERAGE_DTLS PRIMARY KEY
		(ID);


INSERT INTO CMS_INSURANCE_COVERAGE_DTLS VALUES(1,'1','General Insurance','Fire Insurance',0,'SC_MAKER','2011-04-12-15.58.38.689000','SC_MAKER','2011-04-12-15.58.38.689000','N','ACTIVE');

INSERT INTO CMS_STAGE_INSURANCE_COVERAGE_DTLS VALUES(1,'1','General Insurance','Fire Insurance',0,'SC_MAKER','2011-04-12-15.58.38.689000','SC_MAKER','2011-04-12-15.58.38.689000','N','ACTIVE');