
--------------------------------
--- CMS_FUNCTION_ACCESS Entries 
--------------------------------

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100803,'general_param_list','add',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100804,'general_param_list','addNoop',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100814,'general_param_list','approve',7);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100818,'general_param_list','close',6);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100816,'general_param_list','listCheckerApproveReject',7);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100817,'general_param_list','listMakerClose',6);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100826,'general_param_list','listRead',7);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100819,'general_param_list','listStaging',6);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100821,'general_param_list','listView',6);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100823,'general_param_list','listView',7);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100808,'general_param_list','paginate',6);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100825,'general_param_list','prepare',6);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100801,'general_param_list','read',6);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100824,'general_param_list','read',7);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100812,'general_param_list','readCheckerApproveReject',7);
    
INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100813,'general_param_list','readMakerClose',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100802,'general_param_list','readMakerEdit',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100815,'general_param_list','reject',7);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100805,'general_param_list','remove',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100806,'general_param_list','removeNoop',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100807,'general_param_list','save',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100809,'general_param_list','saveNoop',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100810,'general_param_list','submit',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100811,'general_param_list','submitNoop',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100820,'general_param_list','view',6);

INSERT INTO ABCLIMS.CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) 
    VALUES(6100822,'general_param_list','view',7);

    
--------------------------------
--- TR_STATE_MATRIX Entries 
--------------------------------
    
insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (4800,'GENERAL_PARAM_GROUP','ACTION_MAKER_UPDATE','ACTIVE','DRAFT','DRAFT','1','1');

insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (4801,'GENERAL_PARAM_GROUP','ACTION_MAKER_SUBMIT','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');

insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (4802,'GENERAL_PARAM_GROUP','ACTION_MAKER_UPDATE_REJECTED','REJECTED','DRAFT','DRAFT','1','1');

insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (4803,'GENERAL_PARAM_GROUP','ACTION_MAKER_CLOSE_REJECTED','REJECTED','ACTIVE','ACTIVE','1','1');

insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (4804,'GENERAL_PARAM_GROUP','ACTION_CHECKER_APPROVE_GENERAL_PARAM_GROUP','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');

insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (4805,'GENERAL_PARAM_GROUP','ACTION_CHECKER_REJECT_GENERAL_PARAM_GROUP','PENDING_UPDATE','REJECTED','REJECTED','1','1');

insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (4806,'GENERAL_PARAM_GROUP','ACTION_MAKER_UPDATE','DRAFT','DRAFT','DRAFT','1','1');

insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (4807,'GENERAL_PARAM_GROUP','ACTION_MAKER_SUBMIT','DRAFT','PENDING_UPDATE','PENDING_UPDATE','1','1');

insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (4808,'GENERAL_PARAM_GROUP','ACTION_MAKER_SUBMIT_REJECTED','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');

insert into ABCLIMS.TR_STATE_MATRIX ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )
values (4809,'GENERAL_PARAM_GROUP','ACTION_MAKER_CLOSE_DRAFT','DRAFT','ACTIVE','ACTIVE','1','1');


----------------------------------
--- CMS_STATEMATRIX_ACTION Entries 
----------------------------------


insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
    values (4802,6,'Process','general_param_list.do?event=readMakerEdit'||'&'||'trxId=',null);

insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
    values (4803,6,'Close','general_param_list.do?event=readMakerClose'||'&'||'offset=0'||'&'||'length=10'||'&'||'trxId=',null);

insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
    values (4804,7,'Process','general_param_list.do?event=readCheckerApproveReject'||'&'||'offset=0'||'&'||'length=10'||'&'||'trxId=',null);

insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
    values (4806,6,'Process','general_param_list.do?event=readMakerEdit'||'&'||'offset=0'||'&'||'length=10'||'&'||'trxId=',null);

insert into ABCLIMS.CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL)
    values (4809,6,'Close','general_param_list.do?event=readMakerClose'||'&'||'offset=0'||'&'||'length=10'||'&'||'trxId=',null);   
 
    
--------------------------------
--- CMS_TRX_TOTRACK Entries 
--------------------------------

    
insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,    TOTRACK_URL,    CURR_STATE,    USER_STATE,    USER_TRX_TYPE,    FROM_STATE,    TRANSACTION_SUBTYPE) 
    values ('GENERAL_PARAM_GROUP','general_param_list.do?event=view'||'&'||'trxId=','ACTIVE','Approved','Maintain Approval Matrix','PENDING_UPDATE',NULL);

insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,    TOTRACK_URL,    CURR_STATE,    USER_STATE,    USER_TRX_TYPE,    FROM_STATE,    TRANSACTION_SUBTYPE) 
    values ('GENERAL_PARAM_GROUP','general_param_list.do?event=view'||'&'||'trxId=','ACTIVE','Closed','Maintain Approval Matrix','DRAFT',NULL);

insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,    TOTRACK_URL,    CURR_STATE,    USER_STATE,    USER_TRX_TYPE,    FROM_STATE,    TRANSACTION_SUBTYPE) 
    values ('GENERAL_PARAM_GROUP','general_param_list.do?event=view'||'&'||'trxId=','ACTIVE','Closed','Maintain Approval Matrix','REJECTED',NULL);

insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,    TOTRACK_URL,    CURR_STATE,    USER_STATE,    USER_TRX_TYPE,    FROM_STATE,    TRANSACTION_SUBTYPE) 
    values ('GENERAL_PARAM_GROUP','general_param_list.do?event=view'||'&'||'trxId=','DRAFT','Draft','Maintain Approval Matrix',NULL,NULL);

insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,    TOTRACK_URL,    CURR_STATE,    USER_STATE,    USER_TRX_TYPE,    FROM_STATE,    TRANSACTION_SUBTYPE) 
    values ('GENERAL_PARAM_GROUP','general_param_list.do?event=view'||'&'||'trxId=','PENDING_UPDATE','Pending Update','Maintain Approval Matrix',NULL,NULL);

insert into ABCLIMS.CMS_TRX_TOTRACK (TRANSACTION_TYPE,    TOTRACK_URL,    CURR_STATE,    USER_STATE,    USER_TRX_TYPE,    FROM_STATE,    TRANSACTION_SUBTYPE) 
    values ('GENERAL_PARAM_GROUP','general_param_list.do?event=view'||'&'||'trxId=','REJECTED','Rejected','Maintain Approval Matrix',NULL,NULL);    