			--------------------- CREATE COUNTRY TABLES ------------------------

create table "ABCLIMS".CMS_COUNTRY
( ID NUMBER(30) NOT NULL primary key,
  COUNTRY_CODE VARCHAR(50) NOT NULL,
  COUNTRY_NAME VARCHAR(50) NOT NULL,
  STATUS VARCHAR(20) NOT NULL,
  DEPRECATED CHAR(2) NOT NULL
);

create table "ABCLIMS".CMS_STAGE_COUNTRY
( ID NUMBER(30) NOT NULL primary key,
  COUNTRY_CODE VARCHAR(50) NOT NULL,
  COUNTRY_NAME VARCHAR(50),
  STATUS VARCHAR(20) NOT NULL,
  DEPRECATED CHAR(2) NOT NULL
);

			--------------------- CREATE REGION TABLES ------------------------

create table "ABCLIMS".CMS_REGION
( ID NUMBER(30) NOT NULL primary key,
  REGION_CODE VARCHAR(50) NOT NULL,
  REGION_NAME VARCHAR(50) NOT NULL,
  COUNTRY_ID BIGINT NOT NULL,
  STATUS VARCHAR(20) NOT NULL,
  DEPRECATED CHAR(2) NOT NULL
);

create table "ABCLIMS".CMS_STAGE_REGION
( ID NUMBER(30) NOT NULL primary key,
  REGION_CODE VARCHAR(50) NOT NULL,
  REGION_NAME VARCHAR(50),
  COUNTRY_ID REFERENCES cms_country(id),
  STATUS VARCHAR(20) NOT NULL,
  DEPRECATED CHAR(2) NOT NULL
);

			--------------------- CREATE STATE TABLES ------------------------

create table "ABCLIMS".CMS_STATE
( ID NUMBER(30) NOT NULL primary key,
  STATE_CODE VARCHAR(50) NOT NULL,
  STATE_NAME VARCHAR(50) NOT NULL,
  REGION_ID BIGINT NOT NULL,
  STATUS VARCHAR(20) NOT NULL,
  DEPRECATED CHAR(2) NOT NULL
);

create table "ABCLIMS".CMS_STAGE_STATE
( ID NUMBER(30) NOT NULL primary key,
  STATE_CODE VARCHAR(50) NOT NULL,
  STATE_NAME VARCHAR(50),
  REGION_ID REFERENCES cms_region(id),
  STATUS VARCHAR(20) NOT NULL,
  DEPRECATED CHAR(2) NOT NULL
);

			--------------------- CREATE City TABLES ------------------------

create table "ABCLIMS".CMS_CITY
( ID NUMBER(30) NOT NULL primary key,
  CITY_CODE VARCHAR(50) NOT NULL,
  CITY_NAME VARCHAR(50) NOT NULL,
  STATE_ID BIGINT NOT NULL,
  STATUS VARCHAR(20) NOT NULL,
  DEPRECATED CHAR(2) NOT NULL
);

create table "ABCLIMS".CMS_STAGE_CITY
( ID NUMBER(30) primary key,
  CITY_CODE VARCHAR(50) NOT NULL,
  CITY_NAME VARCHAR(50),
  STATE_ID REFERENCES cms_state(id),
  STATUS VARCHAR(20) NOT NULL,
  DEPRECATED CHAR(2) NOT NULL
);

			------------------------	CMS_FUNCTION_ACCESS	 Geography Script	------------------------

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000153,'Geography','checker_view_geography',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000031,'Geography','view_geography',6);

			------------------------	CMS_FUNCTION_ACCESS	 Country Script		------------------------

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000044,'Country','prepare_create_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000137,'City','prepare_maker_edit_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000005,'Country','prepare_list_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000011,'Country','view_list_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000180,'Country','checker_view_list_country',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000025,'Country','prepare_remove_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(6000030,'Country','remove_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000032,'Country','view_country_by_index',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000036,'Country','maker_create_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000042,'Country','maker_edit_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000040,'Country','maker_prepare_create_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000041,'Country','maker_create_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000043,'Country','maker_edit_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000045,'Country','totrack_maker_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000046,'Country','checker_approve_country',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000047,'Country','checker_reject_country',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000048,'Country','checker_process_create_country',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000049,'Country','prepare_maker_edit_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000050,'Country','checker_process_edit_country',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000051,'Country','maker_prepare_close',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000052,'Country','maker_resubmit_create_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000053,'Country','checker_process_edit',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000054,'Country','maker_confirm_resubmit_edit',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000055,'Country','maker_confirm_close',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000056,'Country','maker_delete_country_read',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000057,'Country','maker_delete_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000058,'Country','totrack_maker_country',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000172,'Country','maker_save_edit_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000165,'Country','maker_save_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000166,'Country','todo_maker_save_create_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000167,'Country','maker_save_edit_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000177,'Country','maker_prepare_close_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000178,'Country','maker_create_saved_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000171,'Country','todo_maker_save_create_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000170,'Country','maker_save_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000149,'Country','maker_prepare_activate_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000150,'Country','maker_activate_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000184,'Country','view_country_by_index',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000191,'Country','maker_edit_save_created_country',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000191,'Country','paginate',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000195,'Country','checker_paginate',7);


			------------------------	CMS_FUNCTION_ACCESS	 Region Script		------------------------

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000059,'Region','checker_approve_region',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000060,'Region','checker_process_create_region',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000061,'Region','checker_process_edit',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000062,'Region','checker_process_edit_region',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000063,'Region','checker_reject_region',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000064,'Region','maker_confirm_close_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000065,'Region','maker_confirm_resubmit_edit_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000066,'Region','maker_create_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000067,'Region','maker_create_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000068,'Region','maker_delete_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000069,'Region','maker_delete_region_read',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000070,'Region','maker_edit_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000071,'Region','maker_edit_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000072,'Region','maker_prepare_close_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000073,'Region','maker_prepare_create_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000074,'Region','maker_resubmit_create_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000075,'Region','prepare_create_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000076,'Region','prepare_list_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000077,'Region','prepare_maker_edit_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000078,'Region','prepare_remove_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000079,'Region','remove_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000080,'Region','totrack_maker_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000081,'Region','view_region_by_index',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000082,'Region','view_list_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000181,'Region','checker_view_list_region',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000083,'Region','totrack_maker_region',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000162,'Region','maker_save_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000163,'Region','todo_maker_save_create_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000175,'Region','maker_create_saved_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000164,'Region','maker_save_edit_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000147,'Region','maker_prepare_activate_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000148,'Region','maker_activate_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000185,'Region','view_region_by_index',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000189,'Region','maker_edit_save_created_region',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000192,'Region','paginate',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000196,'Region','checker_paginate',7);

			------------------------	CMS_FUNCTION_ACCESS	 State Script		------------------------


INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000084,'State','checker_approve_state',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000085,'State','checker_process_create_state',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000086,'State','maker_create_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000087,'State','maker_create_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000088,'State','maker_delete_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000089,'State','maker_delete_state_read',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000090,'State','maker_edit_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000091,'State','maker_edit_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000092,'State','maker_prepare_close_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000093,'State','maker_prepare_create_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000094,'State','maker_resubmit_create_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000095,'State','prepare_create_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000096,'State','prepare_list_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000097,'State','prepare_maker_edit_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000098,'State','prepare_remove_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000099,'State','remove_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000100,'State','totrack_maker_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000101,'State','view_state_by_index',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000102,'State','view_list_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000182,'State','checker_view_list_state',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000103,'State','totrack_maker_state',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000104,'State','checker_process_edit',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000105,'State','checker_process_edit_state',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000106,'State','checker_reject_state',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000107,'State','maker_confirm_close_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000108,'State','maker_confirm_resubmit_edit_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000140,'State','refresh_region_id',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000143,'State','maker_prepare_activate_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000146,'State','maker_activate_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000159,'State','maker_save_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000161,'State','maker_save_edit_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000176,'State','maker_create_saved_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000160,'State','todo_maker_save_create_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000186,'State','view_state_by_index',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000190,'State','maker_edit_save_created_state',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000193,'State','paginate',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000197,'State','checker_paginate',7);

			------------------------	CMS_FUNCTION_ACCESS	 City Script		------------------------

INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000109,'City','checker_approve_city',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000110,'City','checker_process_create_city',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000111,'City','checker_process_edit',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000112,'City','checker_process_edit_city',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000113,'City','checker_reject_city',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000114,'City','maker_confirm_close',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000115,'City','maker_confirm_resubmit_edit_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000116,'City','maker_create_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000117,'City','maker_create_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000118,'City','maker_delete_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000119,'City','maker_delete_city_read',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000120,'City','maker_edit_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000123,'City','maker_prepare_create_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000124,'City','maker_resubmit_create_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000125,'City','prepare_create_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000126,'City','prepare_list_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000128,'City','prepare_remove_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000129,'City','remove_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000130,'City','totrack_maker_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000131,'City','view_city_by_index',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000132,'City','view_list_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000183,'City','checker_view_list_city',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000133,'City','totrack_maker_city',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000134,'City','maker_edit_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000135,'City','maker_edit_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000136,'City','maker_prepare_close_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000138,'City','maker_confirm_close_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000139,'City','maker_save_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000141,'City','maker_prepare_activate_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000142,'City','maker_activate_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000151,'City','refresh_city_list',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000152,'City','refresh_state_id',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000154,'City','todo_maker_save_create_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000155,'City','todo_maker_save_edited_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000156,'City','maker_create_saved_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000157,'City','maker_save_edit_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000158,'City','checker_reject_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000179,'City','maker_resubmit_create_city',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000187,'City','view_city_by_index',7);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000188,'City','maker_edit_save_created_city',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000189,'City','refresh_region_id',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000194,'City','paginate',6);
INSERT INTO CMS_FUNCTION_ACCESS(ID, ACTION, EVENT, ROLE_TYPE) VALUES(60000198,'City','checker_paginate',7);


				------------------------	TR_STATE_MATRIX Country Script	------------------------
	
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2101,'COUNTRY','EDIT_REJECTED_DELETE','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2102,'COUNTRY','CREATE_COUNTRY','PENDING_CREATE','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2103,'COUNTRY','APPROVE_COUNTRY','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2104,'COUNTRY','UPDATE_COUNTRY','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2105,'COUNTRY','APPROVE_CREATE_COUNTRY','PENDING_CREATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2106,'COUNTRY','REJECT_COUNTRY','PENDING_UPDATE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2107,'COUNTRY','EDIT_REJECTED_UPDATE_COUNTRY','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2108,'COUNTRY','CLOSE_REJECTED_UPDATE_COUNTRY','REJECTED','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2109,'COUNTRY','REJECT_COUNTRY','PENDING_CREATE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2110,'COUNTRY','CLOSE_REJECTED_CREATE_COUNTRY','REJECTED','CLOSED','CLOSED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2111,'COUNTRY','EDIT_REJECTED_CREATE_COUNTRY','REJECTED','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2112,'COUNTRY','DELETE_COUNTRY','ACTIVE','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2113,'COUNTRY','DELETE_COUNTRY','PENDING_DELETE','DELETED','DELETED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2114,'COUNTRY','REJECT_COUNTRY','PENDING_DELETE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2115,'COUNTRY','CLOSE_REJECTED_COUNTRY','REJECTED','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2116,'COUNTRY','UPDATE_COUNTRY','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2117,'COUNTRY','CHECKER_APPROVE_UPDATE','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2118,'COUNTRY','CHECKER_APPROVE_DELETE','PENDING_DELETE','DELETED','INACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2119,'COUNTRY','APPROVE_COUNTRY','PENDING_DELETE','DELETED','INACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2120,'COUNTRY','CHECKER_APPROVE_UPDATE','PENDING_DELETE','DELETED','INACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2121,'COUNTRY','CREATE_COUNTRY','ND','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2122,'COUNTRY','CLOSE_REJECTED_DELETE_COUNTRY','REJECTED','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2124,'COUNTRY','APPROVE_DELETE_COUNTRY','PENDING_DELETE','DELETED','DELETED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2125,'COUNTRY','CREATE_COUNTRY','ACTIVE','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2126,'COUNTRY','EDIT_REJECTED_DELETE_COUNTRY','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2127,'COUNTRY','EDIT_REJECTED_COUNTRY','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2128,'COUNTRY','EDIT_REJECTED_COUNTRY','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2229,'COUNTRY','DELETE_COUNTRY','DELETED','PENDING_ACTIVATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2237,'COUNTRY','ACTIVATE_COUNTRY','DELETED','PENDING_ACTIVATE','PENDING_ACTIVATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2238,'COUNTRY','ACTIVATE_COUNTRY','PENDING_ACTIVATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2239,'COUNTRY','REJECT_COUNTRY','PENDING_ACTIVATE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2248,'COUNTRY','MAKER_SAVE_COUNTRY','PENDING_PERFECTION','DRAFT','DRAFT','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2249,'COUNTRY','CREATE_COUNTRY','DRAFT','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2250,'COUNTRY','MAKER_UPDATE_SAVE_COUNTRY','ACTIVE','DRAFT','DRAFT','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2251,'COUNTRY','MAKER_UPDATE_SAVE_COUNTRY','DRAFT','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2252,'COUNTRY','CLOSE_REJECTED_UPDATE_COUNTRY','DRAFT','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2253,'COUNTRY','CLOSE_REJECTED_CREATE_COUNTRY','DRAFT','CLOSED','CLOSED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2261,'COUNTRY','EDIT_REJECTED_INACTIVE_COUNTRY','REJECTED','PENDING_ACTIVATE','DELETED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2262,'COUNTRY','CLOSE_REJECTED_INACTIVE_COUNTRY','REJECTED','DELETED','DELETED','1','1');


				------------------------	TR_STATE_MATRIX Region Script	------------------------


insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2131,'REGION','EDIT_REJECTED_DELETE','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2132,'REGION','CREATE_REGION','PENDING_CREATE','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2133,'REGION','APPROVE_REGION','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2134,'REGION','UPDATE_REGION','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2135,'REGION','APPROVE_CREATE_REGION','PENDING_CREATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2136,'REGION','REJECT_REGION','PENDING_UPDATE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2137,'REGION','EDIT_REJECTED_UPDATE_REGION','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2138,'REGION','CLOSE_REJECTED_UPDATE_REGION','REJECTED','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2139,'REGION','REJECT_REGION','PENDING_CREATE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2140,'REGION','CLOSE_REJECTED_CREATE_REGION','REJECTED','CLOSED','CLOSED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2141,'REGION','EDIT_REJECTED_CREATE_REGION','REJECTED','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2142,'REGION','DELETE_REGION','ACTIVE','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2143,'REGION','DELETE_REGION','PENDING_DELETE','DELETED','DELETED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2144,'REGION','REJECT_REGION','PENDING_DELETE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2145,'REGION','CLOSE_REJECTED_REGION','REJECTED','CLOSED','CLOSED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2146,'REGION','UPDATE_REGION','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2147,'REGION','CHECKER_APPROVE_UPDATE','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2148,'REGION','CHECKER_APPROVE_DELETE','PENDING_DELETE','DELETED','INACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2149,'REGION','APPROVE_REGION','PENDING_DELETE','DELETED','INACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2150,'REGION','CHECKER_APPROVE_UPDATE','PENDING_DELETE','DELETED','INACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2151,'REGION','CREATE_REGION','ND','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2152,'REGION','CLOSE_REJECTED_DELETE_REGION','REJECTED','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2154,'REGION','APPROVE_DELETE_REGION','PENDING_DELETE','DELETED','DELETED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2156,'REGION','EDIT_REJECTED_DELETE_REGION','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2157,'REGION','EDIT_REJECTED_REGION','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2158,'REGION','EDIT_REJECTED_REGION','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2228,'REGION','DELETE_REGION','DELETED','PENDING_ACTIVATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2234,'REGION','ACTIVATE_REGION','DELETED','PENDING_ACTIVATE','PENDING_ACTIVATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2235,'REGION','ACTIVATE_REGION','PENDING_ACTIVATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2236,'REGION','REJECT_REGION','PENDING_ACTIVATE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2254,'REGION','MAKER_SAVE_REGION','PENDING_PERFECTION','DRAFT','DRAFT','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2255,'REGION','CREATE_REGION','DRAFT','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2256,'REGION','MAKER_UPDATE_SAVE_REGION','ACTIVE','DRAFT','DRAFT','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2257,'REGION','MAKER_UPDATE_SAVE_REGION','DRAFT','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2258,'REGION','CLOSE_REJECTED_UPDATE_REGION','DRAFT','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2260,'REGION','CLOSE_REJECTED_CREATE_REGION','DRAFT','CLOSED','CLOSED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2263,'REGION','PENDING_ACTIVATE','REJECTED','DELETED','DELETED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2265,'REGION','CLOSE_REJECTED_INACTIVE_REGION','REJECTED','DELETED','DELETED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2266,'REGION','EDIT_REJECTED_INACTIVE_REGION','REJECTED','PENDING_ACTIVATE','PENDING_ACTIVATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (112264,'REGION','CLOSE_REJECTED_INACTIVE_COUNTRY','REJECTED','DELETED','DELETED','1','1');

				------------------------	TR_STATE_MATRIX State Script	------------------------


insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2161,'STATE','EDIT_REJECTED_DELETE','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2162,'STATE','CREATE_STATE','PENDING_CREATE','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2163,'STATE','APPROVE_STATE','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2164,'STATE','UPDATE_STATE','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2165,'STATE','APPROVE_CREATE_STATE','PENDING_CREATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2166,'STATE','REJECT_STATE','PENDING_UPDATE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2167,'STATE','EDIT_REJECTED_UPDATE_STATE','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2168,'STATE','CLOSE_REJECTED_UPDATE_STATE','REJECTED','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2169,'STATE','REJECT_STATE','PENDING_CREATE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2170,'STATE','CLOSE_REJECTED_CREATE_STATE','REJECTED','CLOSED','CLOSED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2171,'STATE','EDIT_REJECTED_CREATE_STATE','REJECTED','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2172,'STATE','DELETE_STATE','ACTIVE','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2173,'STATE','DELETE_STATE','PENDING_DELETE','DELETED','DELETED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2174,'STATE','REJECT_STATE','PENDING_DELETE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2175,'STATE','CLOSE_REJECTED_STATE','REJECTED','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2176,'STATE','UPDATE_STATE','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2177,'STATE','CHECKER_APPROVE_UPDATE','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2178,'STATE','CHECKER_APPROVE_DELETE','PENDING_DELETE','DELETED','INACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2179,'STATE','APPROVE_STATE','PENDING_DELETE','DELETED','INACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2180,'STATE','CHECKER_APPROVE_UPDATE','PENDING_DELETE','DELETED','INACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2181,'STATE','CREATE_STATE','ND','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2182,'STATE','CLOSE_REJECTED_DELETE_STATE','REJECTED','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2184,'STATE','APPROVE_DELETE_STATE','PENDING_DELETE','DELETED','DELETED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2185,'STATE','CREATE_STATE','ACTIVE','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2186,'STATE','EDIT_REJECTED_DELETE_STATE','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2187,'STATE','EDIT_REJECTED_STATE','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2188,'STATE','EDIT_REJECTED_STATE','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2189,'STATE','EDIT_REJECTED_DELETE','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2227,'STATE','DELETE_STATE','DELETED','PENDING_ACTIVATE','PENDING_ACTIVATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2230,'STATE','ACTIVATE_STATE','PENDING_ACTIVATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2233,'STATE','REJECT_STATE','PENDING_ACTIVATE','REJECTED','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2242,'STATE','MAKER_SAVE_STATE','PENDING_PERFECTION','DRAFT','DRAFT','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2243,'STATE','CREATE_STATE','DRAFT','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2244,'STATE','MAKER_UPDATE_SAVE_STATE','ACTIVE','DRAFT','DRAFT','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2245,'STATE','MAKER_UPDATE_SAVE_STATE','DRAFT','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2246,'STATE','CLOSE_REJECTED_UPDATE_STATE','DRAFT','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2247,'STATE','CLOSE_REJECTED_CREATE_STATE','DRAFT','CLOSED','CLOSED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2267,'STATE','CLOSE_REJECTED_INACTIVE_STATE','REJECTED','DELETED','DELETED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2268,'STATE','EDIT_REJECTED_INACTIVE_STATE','REJECTED','PENDING_ACTIVATE','PENDING_ACTIVATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2276,'STATE','ACTIVATE_STATE','DELETED','PENDING_ACTIVATE','PENDING_ACTIVATE','1','1');

				------------------------	TR_STATE_MATRIX City Script	------------------------

insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2191,'CITY','EDIT_REJECTED_DELETE','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2192,'CITY','CREATE_CITY','PENDING_CREATE','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2193,'CITY','APPROVE_CITY','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2194,'CITY','UPDATE_CITY','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2195,'CITY','APPROVE_CREATE_CITY','PENDING_CREATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2196,'CITY','REJECT_CITY','PENDING_UPDATE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2197,'CITY','EDIT_REJECTED_UPDATE_CITY','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2198,'CITY','CLOSE_REJECTED_UPDATE_CITY','REJECTED','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2199,'CITY','REJECT_CITY','PENDING_CREATE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2200,'CITY','CLOSE_REJECTED_CREATE_CITY','REJECTED','CLOSED','CLOSED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2201,'CITY','EDIT_REJECTED_CREATE_CITY','REJECTED','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2202,'CITY','DELETE_CITY','ACTIVE','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2203,'CITY','DELETE_CITY','PENDING_DELETE','DELETED','DELETED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2204,'CITY','REJECT_CITY','PENDING_DELETE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2205,'CITY','CLOSE_REJECTED_CITY','REJECTED','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2206,'CITY','UPDATE_CITY','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2207,'CITY','CHECKER_APPROVE_UPDATE','PENDING_UPDATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2208,'CITY','CHECKER_APPROVE_DELETE','PENDING_DELETE','DELETED','INACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2209,'CITY','APPROVE_CITY','PENDING_DELETE','DELETED','INACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2210,'CITY','CHECKER_APPROVE_UPDATE','PENDING_DELETE','DELETED','INACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2211,'CITY','CREATE_CITY','ND','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2212,'CITY','CLOSE_REJECTED_DELETE_CITY','REJECTED','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2214,'CITY','APPROVE_DELETE_CITY','PENDING_DELETE','DELETED','DELETED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2215,'CITY','CREATE_CITY','ACTIVE','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2216,'CITY','EDIT_REJECTED_DELETE_CITY','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2217,'CITY','EDIT_REJECTED_CITY','REJECTED','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2218,'CITY','EDIT_REJECTED_CITY','ACTIVE','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2219,'CITY','EDIT_REJECTED_DELETE','REJECTED','PENDING_DELETE','PENDING_DELETE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2221,'CITY','MAKER_SAVE_CITY','PENDING_PERFECTION','DRAFT','DRAFT','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2222,'CITY','CREATE_CITY','DRAFT','PENDING_CREATE','PENDING_CREATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2223,'CITY','MAKER_UPDATE_SAVE_CITY','ACTIVE','DRAFT','DRAFT','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2224,'CITY','MAKER_UPDATE_SAVE_CITY','DRAFT','PENDING_UPDATE','PENDING_UPDATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2225,'CITY','CLOSE_REJECTED_UPDATE_CITY','DRAFT','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2226,'CITY','ACTIVATE_CITY','DELETED','PENDING_ACTIVATE','PENDING_ACTIVATE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2231,'CITY','ACTIVATE_CITY','PENDING_ACTIVATE','ACTIVE','ACTIVE','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2232,'CITY','REJECT_CITY','PENDING_ACTIVATE','REJECTED','REJECTED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2240,'CITY','CLOSE_REJECTED_CREATE_CITY','DRAFT','CLOSED','CLOSED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2269,'CITY','CLOSE_REJECTED_INACTIVE_CITY','REJECTED','DELETED','DELETED','1','1');
insert into ABCLIMS.'TR_STATE_MATRIX' ( STATEID, STATEINS, OPERATION, FROMSTATE, TOSTATE, USERSTATE,ENABLEIND, FRONTENDOP )values (2270,'CITY','EDIT_REJECTED_INACTIVE_CITY','REJECTED','PENDING_ACTIVATE','PENDING_ACTIVATE','1','1');


				------------------------	CMS_TRX_TOTRACK	 Country Script	------------------------

insert into CMS_TRX_TOTRACK values('COUNTRY','Country.do?event=totrack_maker_country&toTrack=yes&TrxId=','PENDING_CREATE','Pending Create','Country',null,null);
insert into CMS_TRX_TOTRACK values('COUNTRY','Country.do?event=totrack_maker_country&toTrack=yes&TrxId=','PENDING_UPDATE','Pending Update','Country',null,null);
insert into CMS_TRX_TOTRACK values('COUNTRY','Country.do?event=totrack_maker_country&toTrack=yes&TrxId=','PENDING_DELETE','Pending Inactive','Country',null,null);
insert into CMS_TRX_TOTRACK values('COUNTRY','Country.do?event=totrack_maker_country&toTrack=yes&TrxId=','DELETED','Inactive','Country',null,null);
insert into CMS_TRX_TOTRACK values('COUNTRY','Country.do?event=totrack_maker_country&toTrack=yes&TrxId=','REJECTED','Rejected','Country',null,null);
insert into CMS_TRX_TOTRACK values('COUNTRY','Country.do?event=totrack_maker_country&toTrack=yes&TrxId=','DRAFT','Draft','Country',null,null);
insert into CMS_TRX_TOTRACK values('COUNTRY','Country.do?event=totrack_maker_country&toTrack=yes&TrxId=','PENDING_ACTIVATE','Pending Activate','Country',null,null);
insert into CMS_TRX_TOTRACK values('COUNTRY','Country.do?event=totrack_maker_country&toTrack=yes&TrxId=','ACTIVE','Approved','Country',null,null);
insert into CMS_TRX_TOTRACK values('COUNTRY','Country.do?event=totrack_maker_country&toTrack=yes&TrxId=','PENDING_CREATE','Pending Create','Country','ND',null);
insert into CMS_TRX_TOTRACK values('COUNTRY','Country.do?event=totrack_maker_country&toTrack=yes&TrxId=','PENDING_CREATE','Pending Create','Country','REJECTED',null);

				------------------------	CMS_TRX_TOTRACK	 Region Script	------------------------

insert into CMS_TRX_TOTRACK values('REGION','Region.do?event=totrack_maker_region&toTrack=yes&TrxId=','ACTIVE','Approved','Region',null,null);
insert into CMS_TRX_TOTRACK values('REGION','Region.do?event=totrack_maker_region&toTrack=yes&TrxId=','PENDING_ACTIVATE','Pending Activate','Region',null,null);
insert into CMS_TRX_TOTRACK values('REGION','Region.do?event=totrack_maker_region&toTrack=yes&TrxId=','DRAFT','Draft','Region',null,null);
insert into CMS_TRX_TOTRACK values('REGION','Region.do?event=totrack_maker_region&toTrack=yes&TrxId=','DELETED','Inactive','Region',null,null);
insert into CMS_TRX_TOTRACK values('REGION','Region.do?event=totrack_maker_region&toTrack=yes&TrxId=','PENDING_CREATE','Pending Create','Region',null,null);
insert into CMS_TRX_TOTRACK values('REGION','Region.do?event=totrack_maker_region&toTrack=yes&TrxId=','PENDING_DELETE','Pending Inactive','Region',null,null);
insert into CMS_TRX_TOTRACK values('REGION','Region.do?event=totrack_maker_region&toTrack=yes&TrxId=','PENDING_UPDATE','Pending Update','Region',null,null);
insert into CMS_TRX_TOTRACK values('REGION','Region.do?event=totrack_maker_region&toTrack=yes&TrxId=','REJECTED','Rejected','Region',null,null);

				------------------------	CMS_TRX_TOTRACK	 State Script	------------------------

insert into CMS_TRX_TOTRACK values('STATE','State.do?event=totrack_maker_state&toTrack=yes&TrxId=','PENDING_CREATE','Pending Create','State',null,null);
insert into CMS_TRX_TOTRACK values('STATE','State.do?event=totrack_maker_state&toTrack=yes&TrxId=','PENDING_UPDATE','Pending Update','State',null,null);
insert into CMS_TRX_TOTRACK values('STATE','State.do?event=totrack_maker_state&toTrack=yes&TrxId=','PENDING_DELETE','Pending Inactive','State',null,null);
insert into CMS_TRX_TOTRACK values('STATE','State.do?event=totrack_maker_state&toTrack=yes&TrxId=','DELETED','Inactive','State',null,null);
insert into CMS_TRX_TOTRACK values('STATE','State.do?event=totrack_maker_state&toTrack=yes&TrxId=','REJECTED','Rejected','State',null,null);
insert into CMS_TRX_TOTRACK values('STATE','State.do?event=totrack_maker_state&toTrack=yes&TrxId=','ACTIVE','Approved','State',null,null);
insert into CMS_TRX_TOTRACK values('STATE','State.do?event=totrack_maker_state&toTrack=yes&TrxId=','DRAFT','Draft','State',null,null);
insert into CMS_TRX_TOTRACK values('STATE','State.do?event=totrack_maker_state&toTrack=yes&TrxId=','PENDING_ACTIVATE','Pending Activate','State',null,null);

				------------------------	CMS_TRX_TOTRACK	 City Script	------------------------

insert into CMS_TRX_TOTRACK values('CITY','City.do?event=totrack_maker_city&toTrack=yes&TrxId=','PENDING_CREATE','Pending Create','City',null,null);
insert into CMS_TRX_TOTRACK values('CITY','City.do?event=totrack_maker_city&toTrack=yes&TrxId=','PENDING_UPDATE','Pending Update','City',null,null);
insert into CMS_TRX_TOTRACK values('CITY','City.do?event=totrack_maker_city&toTrack=yes&TrxId=','PENDING_DELETE','Pending Inactive','City',null,null);
insert into CMS_TRX_TOTRACK values('CITY','City.do?event=totrack_maker_city&toTrack=yes&TrxId=','DELETED','Inactive','City',null,null);
insert into CMS_TRX_TOTRACK values('CITY','City.do?event=totrack_maker_city&toTrack=yes&TrxId=','REJECTED','Rejected','City',null,null);
insert into CMS_TRX_TOTRACK values('CITY','City.do?event=totrack_maker_city&toTrack=yes&TrxId=','DRAFT','Draft','City',null,null);
insert into CMS_TRX_TOTRACK values('CITY','City.do?event=totrack_maker_city&toTrack=yes&TrxId=','ACTIVE','Approved','City',null,null);
insert into CMS_TRX_TOTRACK values('CITY','City.do?event=totrack_maker_city&toTrack=yes&TrxId=','PENDING_ACTIVATE','Pending Activate','City',null,null);



				------------------------	CMS_STATEMATRIX_ACTION 	 Country Script	------------------------

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2102,7,'Process','Country.do?event=checker_process_create_country&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2106,7,'Process','Country.do?event=checker_process_create_country&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2101,6,'Process','Country.do?event=maker_prepare_resubmit&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2107,6,'Process','Country.do?event=maker_resubmit_create_country&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2108,6,'Process','Country.do?event=maker_resubmit_create_country&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2111,6,'Close','Country.do?event=maker_prepare_close&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2113,7,'Process','Country.do?event=checker_process_create_country&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2116,7,'Process','Country.do?event=checker_process_create_country&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2238,7,'Process','Country.do?event=checker_process_create_country&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2252,6,'Close','Country.do?event=maker_prepare_close&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2249,6,'Process','Country.do?event=todo_maker_save_create_country&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2262,6,'Close','Country.do?event=maker_prepare_close&TrxId=','');

				------------------------	CMS_STATEMATRIX_ACTION 	 Region Script	------------------------

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2131,6,'Process','Region.do?event=maker_prepare_resubmit&TrxId=','Region.do?event=to_track&TrxId=');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2132,7,'Process','Region.do?event=checker_process_create_region&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2136,7,'Process','Region.do?event=checker_process_create_region&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2138,6,'Process','Region.do?event=maker_resubmit_create_region&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2141,6,'Close','Region.do?event=maker_prepare_close_region&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2143,7,'Process','Region.do?event=checker_process_create_region&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2146,7,'Process','Region.do?event=checker_process_create_region&TrxId=','Region.do?event=to_track&TrxId=');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2235,7,'Process','Region.do?event=checker_process_create_region&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2255,6,'Process','Region.do?event=todo_maker_save_create_region&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2258,6,'Close','Region.do?event=maker_prepare_close_region&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2265,6,'Close','Region.do?event=maker_prepare_close_region&TrxId=','');

				------------------------	CMS_STATEMATRIX_ACTION 	 State Script	------------------------

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2161,6,'Process','State.do?event=maker_prepare_resubmit&TrxId=','State.do?event=to_track&TrxId=');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2162,7,'Process','State.do?event=checker_process_create_state&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2166,7,'Process','State.do?event=checker_process_create_state&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2168,6,'Process','State.do?event=maker_resubmit_create_state&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2171,6,'Close','State.do?event=maker_prepare_close_state&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2173,7,'Process','State.do?event=checker_process_create_state&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2176,7,'Process','State.do?event=checker_process_create_state&TrxId=','State.do?event=to_track&TrxId=');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2230,7,'Process','State.do?event=checker_process_create_state&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2246,6,'Close','State.do?event=maker_prepare_close_state&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2243,6,'Process','State.do?event=todo_maker_save_create_state&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2167,6,'Process','State.do?event=maker_resubmit_create_state&TrxId=','');

			------------------------	CMS_STATEMATRIX_ACTION 	 City Script	------------------------

insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2191,6,'Process','City.do?event=maker_prepare_resubmit&TrxId=','City.do?event=to_track&TrxId=');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2222,6,'Process','City.do?event=todo_maker_save_create_city&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2192,7,'Process','City.do?event=checker_process_create_city&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2196,7,'Process','City.do?event=checker_process_create_city&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2198,6,'Process','City.do?event=maker_resubmit_create_city&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2201,6,'Close','City.do?event=maker_prepare_close_city&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2203,7,'Process','City.do?event=checker_process_create_city&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2206,7,'Process','City.do?event=checker_process_create_city&TrxId=','City.do?event=to_track&TrxId=');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2231,7,'Process','City.do?event=checker_process_create_city&TrxId=','');
insert into CMS_STATEMATRIX_ACTION (STATE_ID, TEAM_MEMBERSHIP_TYPE_ID, USER_ACTION, URL, TOTRACK_URL) values (2225,6,'Close','City.do?event=maker_prepare_close_city&TrxId=','');
