--------------------------------------------------
-- schema setup for facility module, mainly for 
-- line loading
--------------------------------------------------

CREATE SEQUENCE FACILITY_MASTER_SEQ AS INTEGER
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 999999999
	MINVALUE 1
	CYCLE
	NO CACHE
	NO ORDER;

CREATE SEQUENCE FAC_INSR_SEQ AS INTEGER
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 999999999
	MINVALUE 1
	CYCLE
	NO CACHE
	NO ORDER;

CREATE SEQUENCE FAC_OFFICER_SEQ AS INTEGER
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 999999999
	MINVALUE 1
	CYCLE
	NO CACHE
	NO ORDER;

CREATE SEQUENCE FAC_RELATIONSHIP_SEQ AS INTEGER
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 999999999
	MINVALUE 1
	CYCLE
	NO CACHE
	NO ORDER;
	
CREATE SEQUENCE FAC_MULTI_TIER_SEQ AS INTEGER
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 999999999
	MINVALUE 1
	CYCLE
	NO CACHE
	NO ORDER;
	
CREATE SEQUENCE FAC_MSG_SEQ AS INTEGER
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 999999999
	MINVALUE 1
	CYCLE
	NO CACHE
	NO ORDER;
	
CREATE SEQUENCE FAC_INCREMENTAL_SEQ AS INTEGER
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 999999999
	MINVALUE 1
	CYCLE
	NO CACHE
	NO ORDER;
    
CREATE SEQUENCE FAC_REDUCTION_SEQ AS INTEGER
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 999999999
	MINVALUE 1
	CYCLE
	NO CACHE
	NO ORDER;

CREATE TABLE CMS_FACILITY_MASTER (
    ID BIGINT 						NOT NULL,
    CURRENCY_CODE 					CHARACTER(3),
    CMS_LSP_APPR_LMTS_ID 			BIGINT,
    ACTUAL_PLEDGED_LIMIT 			DECIMAL(20,2),
    ALLOW_INCENTIVE_IND 			CHARACTER(1),
    ALT_RATE 						CHARACTER(1),
    ALT_SCHEDULE 					CHARACTER(1),
    APPL_SRC_CODE_NUM 				VARCHAR(100),
    APPL_SRC_CODE_VALUE 			VARCHAR(100),
    AVAIL_PERIOD_DAY 				SMALLINT,
    AVAIL_PERIOD_MONTH 				SMALLINT,
    CAL_FIRST_INSTL_DATE		 	CHARACTER(1),
    CGC_BNM_APPROVED_DATE 			TIMESTAMP,
    CREDIT_LINE_IND 				CHARACTER(1),
    DEALER_NUM_LPP_CODE_NUM 		VARCHAR(40),
    DEALER_NUM_LPP_CODE_VALUE 		VARCHAR(40),
    DEPARTMENT_CODE_NUM 			VARCHAR(40),
    DEPARTMENT_CODE_VALUE 			VARCHAR(10),
    DISBURSEMENT_MANNER 			VARCHAR(100),
    ECOF_ADMIN_COST 				DECIMAL(20,2),
    ECOF_RATE 						DECIMAL(11,7),
    ECOF_VARIANCE 					DECIMAL(11,7),
    ECOF_VARIANCE_CODE 				CHARACTER(1),
    EFFECTIVE_COSE_OF_FUND 			CHARACTER(1),
    AVAIL_DATE 						TIMESTAMP,
    AVAIL_PERIOD 					VARCHAR(100),
    FLOOR_PLEDGED_LIMIT 			DECIMAL(20,2),
    INT_IN_SUSPENSE 				DECIMAL(20,2),
    ISO_REFERRAL_NUM 				VARCHAR(20),
    LAST_MAINTENANCE_DATE 			TIMESTAMP,
    LAWYER_CODE_NUM 				VARCHAR(40),
    LAWYER_CODE_VALUE 				VARCHAR(10),
    LEVEL 							SMALLINT,
    MAIN_FACILITY_IND 				CHARACTER(1),
    MAIN_FACILITY_AA_NUM 			VARCHAR(35),
    MAIN_FACILITY_CODE 				VARCHAR(100),
    MAIN_FACILITY_SEQ 				BIGINT,
    OD_EXCESS_RATE_VAR 				DECIMAL(11,7),
    OD_EXCESS_RATE_VAR_CODE 		CHARACTER(1),
    PAR_VALUE_SHARES 				CHARACTER(1),
    PROD_PACKAGE_CODE_NUM 			VARCHAR(40),
    PROD_PACKAGE_CODE_VALUE 		VARCHAR(10),
    REFINANCE_FROM_BANK_CODE_NUM 	VARCHAR(40),
    REFINANCE_FROM_BANK_CODE_VALUE 	VARCHAR(10),
    RETENTION_PERIOD_CODE 			CHARACTER(1),
    RETENTION_SUM 					DECIMAL(20,2),
    REVOLVING_IND 					CHARACTER(1),
    REVOLVING_ON_CRITERIA_IND 		CHARACTER(1),
    SOLICITOR_NAME 					VARCHAR(255),
    SOLICITOR_REFERENCE 			VARCHAR(100),
    SPEC_PROVISION 					DECIMAL(20,2),
    STANDBY_LINE 					CHARACTER(1),
    STANDBY_LINE_FAC_CODE			VARCHAR(100),
    STANDBY_LINE_FAC_SEQ 			BIGINT,
	ACF_NO 							VARCHAR(40),
	RETENTION_PERIOD 				SMALLINT,
	DATE_INSTRUCTED 				TIMESTAMP,
	CMS_REQ_SEC_COVERAGE 			DOUBLE,
	CMS_DRAWING_LIMIT 				DECIMAL(20,2),
	LMT_PRD_TYPE_VALUE 				VARCHAR(60),
	TO_BE_CANCELLED_IND				VARCHAR(1),
    PRIMARY KEY (ID)
) IN CMS_DATA INDEX IN CMS_INDEX;

CREATE UNIQUE INDEX CMS_FAC_MASTER_U1 
	ON CMS_FACILITY_MASTER (CMS_LSP_APPR_LMTS_ID)
	ALLOW REVERSE SCANS;

CREATE TABLE CMS_FAC_BNM_CODES (
    CMS_FAC_MASTER_ID 				BIGINT NOT NULL,
    BUMI_NRCC_CODE_NUM 				VARCHAR(40),
    BUMI_NRCC_CODE_VALUE 			VARCHAR(10),
    EXEMPTED_CODE_NUM 				VARCHAR(40),
    EXEMPTED_CODE_VALUE 			VARCHAR(10),
    GOODS_FINANCED_ONE_CODE_NUM 	VARCHAR(40),
    GOODS_FINANCED_ONE_CODE_VALUE 	VARCHAR(10),
    GOODS_FINANCED_TWO_CODE_NUM 	VARCHAR(40),
    GOODS_FINANCED_TWO_CODE_VALUE 	VARCHAR(10),
    HOST_TIER_SEQ	 				BIGINT,
    INDUSTRY_CODE_NUM 				VARCHAR(40),
    INDUSTRY_CODE_VALUE 			VARCHAR(10),
    PRESCRIBED_RATE_CODE_NUM 		VARCHAR(40),
    PRESCRIBED_RATE_CODE_VALUE 		VARCHAR(10),
    PURPOSE_CODE_NUM 				VARCHAR(40),
    PURPOSE_CODE_VALUE 				VARCHAR(10),
    RELATIONSHIP_CODE_NUM 			VARCHAR(40),
    RELATIONSHIP_CODE_VALUE 		VARCHAR(10),
    SECTOR_CODE_NUM 				VARCHAR(40),
    SECTOR_CODE_VALUE 				VARCHAR(10),
    SMALL_SCALE_CODE_NUM 			VARCHAR(40),
    SMALL_SCALE_CODE_VALUE 			VARCHAR(10),
    STATE_CODE_NUM 					VARCHAR(40),
    STATE_CODE_VALUE 				VARCHAR(10),
	TIER_SEQ_NUM_CODE_NUM 			VARCHAR(40),
	TIER_SEQ_NUM_CODE_VALUE 		VARCHAR(10),
	EXEMPTED_CODE_IND 				CHARACTER(1),
	BASEL_SA_FINALISED_NUM 			VARCHAR(40),
	BASEL_SA_FINALISED_VALUE 		VARCHAR(10),
	BASEL_IRB_NUM 					VARCHAR(40),
	BASEL_IRB_VALUE 				VARCHAR(10),
    BASEL_SA_CONCEPT_NUM 			VARCHAR(40),
    BASEL_SA_CONCEPT_VALUE 			VARCHAR(10),
    PRIMARY KEY (CMS_FAC_MASTER_ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_FAC_BNM_CODES 
    ADD CONSTRAINT FK23423A9BECE7333E 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_FACILITY_MASTER;

CREATE TABLE CMS_FAC_FEE_CHARGE (
    CMS_FAC_MASTER_ID 				BIGINT NOT NULL,
    CURRENCY_CODE 					CHARACTER(3),
    COMMISSION_BASIS_CODE_NUM 		VARCHAR(40),
    COMMISSION_BASIS_CODE_VALUE 	VARCHAR(10),
    COMMISSION_FEES 				DECIMAL(20,2),
    COMMISSION_RATE 				DECIMAL(11,7),
    COMMITMENT_RATE 				DECIMAL(11,7),
    COMTMT_RATE_NUM_CODE_NUM 		VARCHAR(40),
    COMTMT_RATE_NUM_CODE_VALUE	 	VARCHAR(10),
    HANDLING_FEES 					DECIMAL(20,2),
    LATE_CHARGE_TYPE 				SMALLINT,
    MAX_COMSSN_AMOUNT 				DECIMAL(20,2),
    MIN_COMSSN_AMOUNT 				DECIMAL(20,2),
    OTHERS_FEE 						DECIMAL(20,2),
    SUBSIDY_AMOUNT 					DECIMAL(20,2),
    PRIMARY KEY (CMS_FAC_MASTER_ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_FAC_FEE_CHARGE 
    ADD CONSTRAINT FKA055BD3AECE7333E 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_FACILITY_MASTER;

CREATE TABLE CMS_FAC_GENERAL (
    CMS_FAC_MASTER_ID 			BIGINT NOT NULL,
    CURRENCY_CODE 				CHARACTER(3),
    APPLICATION_DATE 			TIMESTAMP,
    APPROVED_DATE 				TIMESTAMP,
    CANCEL_REJECT_CODE_NUM 		VARCHAR(40),
    CANCEL_REJECT_DATE 			TIMESTAMP,
    CANCEL_REJECT_CODE_VALUE 	VARCHAR(10),
    CAR_CODE_NUM 				VARCHAR(40),
    CAR_CODE_FLAG 				CHARACTER(1),
    CAR_CODE_VALUE 				VARCHAR(10),
    ENTERED_DATE 				TIMESTAMP,
    FAC_STATUS_CODE_NUM 		VARCHAR(40),
    FAC_STATUS_CODE_VALUE 		VARCHAR(10),
    FINAL_PAYMENT 				DECIMAL(20,2),
    FINANCED_AMOUNT 			DECIMAL(20,2),
	APPROVED_AMOUNT				DECIMAL(20,2),
    INSTALLMENT_AMOUNT 			DECIMAL(20,2),
    LMT_STATUS_CODE_NUM 		VARCHAR(40),
    LMT_STATUS_CODE_VALUE 		VARCHAR(10),
    LOAN_PURPOSE_CODE_NUM 		VARCHAR(40),
    LOAN_PURPOSE_CODE_VALUE 	VARCHAR(10),
    OFFER_ACCEPTED_DATE 		TIMESTAMP,
    OFFER_DATE 					TIMESTAMP,
    OFFICER_CODE_NUM 			VARCHAR(40),
    OFFICER_CODE_VALUE 			VARCHAR(10),
    ORIGINAL_AMOUNT 			DECIMAL(20,2),
    OUTSTANDING_AMOUNT 			DECIMAL(20,2),
    PERSON_APPROVED_CODE_NUM 	VARCHAR(40),
    PERSON_APPROVED_CODE_VALUE 	VARCHAR(10),
    TERM 						SMALLINT,
    TERM_CODE_NUM 				VARCHAR(40),
    TERM_CODE_VALUE 			VARCHAR(10),
    UTILISED_AMOUNT 			DECIMAL(20,2),
    PRIMARY KEY (CMS_FAC_MASTER_ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_FAC_GENERAL 
    ADD CONSTRAINT FKE135D05BECE7333E 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_FACILITY_MASTER;

CREATE TABLE CMS_FAC_INSURANCE (
    ID 							BIGINT not null,
    CMS_FAC_MASTER_ID 			BIGINT,
    CMS_REF_ID 					BIGINT,
    CURRENCY_CODE 				CHARACTER(3),
    ARRANGEMENT_IND 			CHARACTER(1),
    COVERAGE_TYPE_CODE_NUM 		VARCHAR(40),
    COVERAGE_TYPE_CODE_VALUE 	VARCHAR(10),
    EFFECTIVE_DATE 				TIMESTAMP,
    EXPIRY_DATE 				TIMESTAMP,
    INSR_COMPANY_CODE_NUM 		VARCHAR(40),
    INSR_COMPANY_CODE_VALUE 	VARCHAR(10),
    INSURANCE_PREMIUM 			DECIMAL(20,2),
    INSURED_AMOUNT 				DECIMAL(20,2),
    ISSUED_DATE 				TIMESTAMP,
    POLICY_NUMBER 				VARCHAR(100),
    POLICY_NUMBER_CV_NOTE 		VARCHAR(100),
    REMARKS 					VARCHAR(100),
	DISPLAY_ORDER 				SMALLINT,
    PRIMARY KEY (ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_FAC_INSURANCE 
    ADD CONSTRAINT FK5E43598DECE7333E 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_FACILITY_MASTER;
    
create index fac_insurance_idx1 on cms_fac_insurance
	(cms_fac_master_id, cms_ref_id)
	allow reverse scans;    

CREATE TABLE CMS_FAC_OFFICER (
    ID 							BIGINT NOT NULL,
    CMS_FAC_MASTER_ID 			BIGINT,
    CMS_REF_ID 					BIGINT,
    HOST_SEQ_NUM 				BIGINT,
    OFFICER_CODE_NUM 			VARCHAR(40),
    OFFICER_CODE_VALUE 			VARCHAR(10),
    OFFICER_TYPE_CODE_NUM 		VARCHAR(40),
    OFFICER_TYPE_CODE_VALUE 	VARCHAR(10),
    RELATIONSHIP_CODE_NUM 		VARCHAR(40),
    RELATIONSHIP_CODE_VALUE 	VARCHAR(10),
	STATUS 						VARCHAR(1),
    SEQ_NUM 					BIGINT,
    PRIMARY KEY (ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_FAC_OFFICER 
    ADD CONSTRAINT FK89AD60A9ECE7333E 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_FACILITY_MASTER;

create index fac_officer_idx1 on cms_fac_officer
	(cms_fac_master_id, cms_ref_id)
	allow reverse scans;
	    
CREATE TABLE CMS_FAC_RELATIONSHIP (
    ID 								BIGINT NOT NULL,
    CMS_FAC_MASTER_ID 				BIGINT,
    CMS_REF_ID 						BIGINT,
    CURRENCY_CODE 					CHARACTER(3),
    ACCT_RELATIONSHIP_CODE_NUM 		VARCHAR(40),
    ACCT_RELATIONSHIP_CODE_VALUE 	VARCHAR(10),
    CIF_NUMBER 						VARCHAR(40),
    CUSTOMER_NAME 					VARCHAR(80),
    CMS_LE_MAIN_PROFILE_ID 			BIGINT,
    DIVIDEND_RATIO 					DOUBLE,
    GUARANTEE_AMOUNT 				DECIMAL(20,2),
    GUARANTEE_PERCENTAGE 			DECIMAL(11,7),
    GUARANTEE_TYPE_IND				CHARACTER(1),
    HOLD_MAIN_CODE_NUM 				VARCHAR(40),
    HOLD_MAIN_CODE_VALUE 			VARCHAR(10),
    HOST_ADD_SEQ_NUM 				BIGINT,
    NAME_ASSOC_WITH_FAC_ORDER 		SMALLINT,
    NAME_CONJUNCTION 				VARCHAR(100),
    NAME_CONJUNCTION_POSITION 		CHARACTER(1),
    PROFIT_RATIO 					DECIMAL(11,7),
    RECEIVE_MAIL_CODE 				CHARACTER(1),
    SHARE_HOLDER_PERCENTAGE 		DECIMAL(11,7),
	STATUS 							VARCHAR(1),
    PRIMARY KEY (ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_FAC_RELATIONSHIP 
    ADD CONSTRAINT FKBEB76685ECE7333E 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_FACILITY_MASTER;
    
CREATE INDEX CMS_FAC_REL_IDX1
	ON CMS_FAC_RELATIONSHIP (CMS_FAC_MASTER_ID, CMS_REF_ID)
	ALLOW REVERSE SCANS;

create index CMS_FAC_REL_IDX2 
	on cms_fac_relationship (cif_number, cms_fac_master_id) 
	allow reverse scans;	
	
CREATE TABLE CMS_FAC_INTEREST (
    CMS_FAC_MASTER_ID 				BIGINT NOT NULL,
    INTEREST_RATE 					DECIMAL(11,7),
    INTEREST_TYPE_CODE_NUM 			VARCHAR(40),
    INTEREST_TYPE_CODE_VALUE 		VARCHAR(10),
    PRIME_RATE_CEILING 				DECIMAL(11,7),
    PRIME_RATE_FLOOR 				DECIMAL(11,7),
    PRIME_REVIEW_DATE 				TIMESTAMP,
    PRIME_REVIEW_TERM 				SMALLINT,
    PRIME_REVIEW_TERM_CODE_NUM 		VARCHAR(40),
    PRIME_REVIEW_TERM_CODE_VALUE 	VARCHAR(10),
    SPREAD 							DECIMAL(11,7),
    SPREAD_SIGN 					CHARACTER(1),
    INTEREST_BASE					SMALLINT,
	INTEREST_MODE 					CHARACTER(1),
	INTEREST_YEAR_BASE 				SMALLINT,
	NEXT_REVIEW_DATE				TIMESTAMP,
	NEXT_REVIEW_TERM				SMALLINT,
	NEXT_REVIEW_TERM_CODE_NUM		VARCHAR(40),
	NEXT_REVIEW_TERM_CODE_VALUE 	VARCHAR(40),
    PRIMARY KEY (CMS_FAC_MASTER_ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_FAC_INTEREST 
    ADD CONSTRAINT FKFB9BCDF7ECE7333E 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_FACILITY_MASTER;

CREATE TABLE CMS_FAC_PAYMENT (
    CMS_FAC_MASTER_ID 				BIGINT NOT NULL,
    GRADE_PERIOD_CODE_NUM 			VARCHAR(40),
    GRADE_PERIOD_CODE_VALUE 		VARCHAR(10),
    GRADE_PERIOD_CD_CODE_NUM 		VARCHAR(40),
    GRADE_PERIOD_CD_CODE_VALUE 		VARCHAR(10),
    INT_PAYMENT_FREQ_CODE_NUM 		VARCHAR(40),
    INT_PAYMENT_FREQ_CODE_VALUE 	VARCHAR(10),
    PAYMENT_CD_CODE_NUM 			VARCHAR(40),
    PAYMENT_CD_CODE_VALUE 			VARCHAR(10),
    PAYMENT_FREQ_CODE_NUM 			VARCHAR(40),
    PAYMENT_FREQ_CODE_VALUE 		VARCHAR(10),
    PAYMENT_FREQ_CD_CODE_NUM 		VARCHAR(40),
    PAYMENT_FREQ_CD_CODE_VALUE 		VARCHAR(10),
	INT_PAYMENT_FREQ_CD_CODE_NUM 	VARCHAR(40),
	INT_PAYMENT_FREQ_CD_CODE_VALUE 	VARCHAR(10),
    PRIMARY KEY (CMS_FAC_MASTER_ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_FAC_PAYMENT 
    ADD CONSTRAINT FKB718F979ECE7333E 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_FACILITY_MASTER;

CREATE TABLE CMS_STG_FACILITY_MASTER (
    ID BIGINT 						NOT NULL,
    CURRENCY_CODE 					CHARACTER(3),
    CMS_LSP_APPR_LMTS_ID 			BIGINT,
    ACTUAL_PLEDGED_LIMIT 			DECIMAL(20,2),
    ALLOW_INCENTIVE_IND 			CHARACTER(1),
    ALT_RATE 						CHARACTER(1),
    ALT_SCHEDULE 					CHARACTER(1),
    APPL_SRC_CODE_NUM 				VARCHAR(100),
    APPL_SRC_CODE_VALUE 			VARCHAR(100),
    AVAIL_PERIOD_DAY 				SMALLINT,
    AVAIL_PERIOD_MONTH 				SMALLINT,
    CAL_FIRST_INSTL_DATE		 	CHARACTER(1),
    CGC_BNM_APPROVED_DATE 			TIMESTAMP,
    CREDIT_LINE_IND 				CHARACTER(1),
    DEALER_NUM_LPP_CODE_NUM 		VARCHAR(40),
    DEALER_NUM_LPP_CODE_VALUE 		VARCHAR(40),
    DEPARTMENT_CODE_NUM 			VARCHAR(40),
    DEPARTMENT_CODE_VALUE 			VARCHAR(10),
    DISBURSEMENT_MANNER 			VARCHAR(100),
    ECOF_ADMIN_COST 				DECIMAL(20,2),
    ECOF_RATE 						DECIMAL(11,7),
    ECOF_VARIANCE 					DECIMAL(11,7),
    ECOF_VARIANCE_CODE 				CHARACTER(1),
    EFFECTIVE_COSE_OF_FUND 			CHARACTER(1),
    AVAIL_DATE 						TIMESTAMP,
    AVAIL_PERIOD 					VARCHAR(100),
    FLOOR_PLEDGED_LIMIT 			DECIMAL(20,2),
    INT_IN_SUSPENSE 				DECIMAL(20,2),
    ISO_REFERRAL_NUM 				VARCHAR(20),
    LAST_MAINTENANCE_DATE 			TIMESTAMP,
    LAWYER_CODE_NUM 				VARCHAR(40),
    LAWYER_CODE_VALUE 				VARCHAR(10),
    LEVEL 							SMALLINT,
    MAIN_FACILITY_IND 				CHARACTER(1),
    MAIN_FACILITY_AA_NUM 			VARCHAR(35),
    MAIN_FACILITY_CODE 				VARCHAR(100),
    MAIN_FACILITY_SEQ 				BIGINT,
    OD_EXCESS_RATE_VAR 				DECIMAL(11,7),
    OD_EXCESS_RATE_VAR_CODE 		CHARACTER(1),
    PAR_VALUE_SHARES 				CHARACTER(1),
    PROD_PACKAGE_CODE_NUM 			VARCHAR(40),
    PROD_PACKAGE_CODE_VALUE 		VARCHAR(10),
    REFINANCE_FROM_BANK_CODE_NUM 	VARCHAR(40),
    REFINANCE_FROM_BANK_CODE_VALUE 	VARCHAR(10),
    RETENTION_PERIOD_CODE 			CHARACTER(1),
    RETENTION_SUM 					DECIMAL(20,2),
    REVOLVING_IND 					CHARACTER(1),
    REVOLVING_ON_CRITERIA_IND 		CHARACTER(1),
    SOLICITOR_NAME 					VARCHAR(255),
    SOLICITOR_REFERENCE 			VARCHAR(100),
    SPEC_PROVISION 					DECIMAL(20,2),
    STANDBY_LINE 					CHARACTER(1),
    STANDBY_LINE_FAC_CODE			VARCHAR(100),
    STANDBY_LINE_FAC_SEQ 			BIGINT,
	ACF_NO 							VARCHAR(40),
	RETENTION_PERIOD 				SMALLINT,
	DATE_INSTRUCTED 				TIMESTAMP,
	CMS_REQ_SEC_COVERAGE 			DOUBLE,
	CMS_DRAWING_LIMIT 				DECIMAL(20,2),
	LMT_PRD_TYPE_VALUE 				VARCHAR(60),
	TO_BE_CANCELLED_IND				VARCHAR(1),
    PRIMARY KEY (ID)
) IN CMS_DATA INDEX IN CMS_INDEX;

CREATE INDEX STG_FAC_MASTER_IDX
	ON CMS_STG_FACILITY_MASTER (CMS_LSP_APPR_LMTS_ID, ID)
	ALLOW REVERSE SCANS;

CREATE TABLE CMS_STG_FAC_BNM_CODES (
    CMS_FAC_MASTER_ID 				BIGINT NOT NULL,
    BUMI_NRCC_CODE_NUM 				VARCHAR(40),
    BUMI_NRCC_CODE_VALUE 			VARCHAR(10),
    EXEMPTED_CODE_NUM 				VARCHAR(40),
    EXEMPTED_CODE_VALUE 			VARCHAR(10),
    GOODS_FINANCED_ONE_CODE_NUM 	VARCHAR(40),
    GOODS_FINANCED_ONE_CODE_VALUE 	VARCHAR(10),
    GOODS_FINANCED_TWO_CODE_NUM 	VARCHAR(40),
    GOODS_FINANCED_TWO_CODE_VALUE 	VARCHAR(10),
    HOST_TIER_SEQ	 				BIGINT,
    INDUSTRY_CODE_NUM 				VARCHAR(40),
    INDUSTRY_CODE_VALUE 			VARCHAR(10),
    PRESCRIBED_RATE_CODE_NUM 		VARCHAR(40),
    PRESCRIBED_RATE_CODE_VALUE 		VARCHAR(10),
    PURPOSE_CODE_NUM 				VARCHAR(40),
    PURPOSE_CODE_VALUE 				VARCHAR(10),
    RELATIONSHIP_CODE_NUM 			VARCHAR(40),
    RELATIONSHIP_CODE_VALUE 		VARCHAR(10),
    SECTOR_CODE_NUM 				VARCHAR(40),
    SECTOR_CODE_VALUE 				VARCHAR(10),
    SMALL_SCALE_CODE_NUM 			VARCHAR(40),
    SMALL_SCALE_CODE_VALUE 			VARCHAR(10),
    STATE_CODE_NUM 					VARCHAR(40),
    STATE_CODE_VALUE 				VARCHAR(10),
	TIER_SEQ_NUM_CODE_NUM 			VARCHAR(40),
	TIER_SEQ_NUM_CODE_VALUE 		VARCHAR(10),
	EXEMPTED_CODE_IND 				CHARACTER(1),
	BASEL_SA_FINALISED_NUM 			VARCHAR(40),
	BASEL_SA_FINALISED_VALUE 		VARCHAR(10),
	BASEL_IRB_NUM 					VARCHAR(40),
	BASEL_IRB_VALUE 				VARCHAR(10),
    BASEL_SA_CONCEPT_NUM 			VARCHAR(40),
    BASEL_SA_CONCEPT_VALUE 			VARCHAR(10),
    PRIMARY KEY (CMS_FAC_MASTER_ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_STG_FAC_BNM_CODES 
    ADD CONSTRAINT FKBAAA87228A6108AE 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_STG_FACILITY_MASTER;

CREATE TABLE CMS_STG_FAC_FEE_CHARGE (
    CMS_FAC_MASTER_ID 				BIGINT NOT NULL,
    CURRENCY_CODE 					CHARACTER(3),
    COMMISSION_BASIS_CODE_NUM 		VARCHAR(40),
    COMMISSION_BASIS_CODE_VALUE 	VARCHAR(10),
    COMMISSION_FEES 				DECIMAL(20,2),
    COMMISSION_RATE 				DECIMAL(11,7),
    COMMITMENT_RATE 				DECIMAL(11,7),
    COMTMT_RATE_NUM_CODE_NUM 		VARCHAR(40),
    COMTMT_RATE_NUM_CODE_VALUE	 	VARCHAR(10),
    HANDLING_FEES 					DECIMAL(20,2),
    LATE_CHARGE_TYPE 				SMALLINT,
    MAX_COMSSN_AMOUNT 				DECIMAL(20,2),
    MIN_COMSSN_AMOUNT 				DECIMAL(20,2),
    OTHERS_FEE 						DECIMAL(20,2),
    SUBSIDY_AMOUNT 					DECIMAL(20,2),
    PRIMARY KEY (CMS_FAC_MASTER_ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_STG_FAC_FEE_CHARGE 
    ADD CONSTRAINT FKF5F701938A6108AE 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_STG_FACILITY_MASTER;

CREATE TABLE CMS_STG_FAC_GENERAL (
    CMS_FAC_MASTER_ID 			BIGINT NOT NULL,
    CURRENCY_CODE 				CHARACTER(3),
    APPLICATION_DATE 			TIMESTAMP,
    APPROVED_DATE 				TIMESTAMP,
    CANCEL_REJECT_CODE_NUM 		VARCHAR(40),
    CANCEL_REJECT_DATE 			TIMESTAMP,
    CANCEL_REJECT_CODE_VALUE 	VARCHAR(10),
    CAR_CODE_NUM 				VARCHAR(40),
    CAR_CODE_FLAG 				CHARACTER(1),
    CAR_CODE_VALUE 				VARCHAR(10),
    ENTERED_DATE 				TIMESTAMP,
    FAC_STATUS_CODE_NUM 		VARCHAR(40),
    FAC_STATUS_CODE_VALUE 		VARCHAR(10),
    FINAL_PAYMENT 				DECIMAL(20,2),
    FINANCED_AMOUNT 			DECIMAL(20,2),
	APPROVED_AMOUNT				DECIMAL(20,2),
    INSTALLMENT_AMOUNT 			DECIMAL(20,2),
    LMT_STATUS_CODE_NUM 		VARCHAR(40),
    LMT_STATUS_CODE_VALUE 		VARCHAR(10),
    LOAN_PURPOSE_CODE_NUM 		VARCHAR(40),
    LOAN_PURPOSE_CODE_VALUE 	VARCHAR(10),
    OFFER_ACCEPTED_DATE 		TIMESTAMP,
    OFFER_DATE 					TIMESTAMP,
    OFFICER_CODE_NUM 			VARCHAR(40),
    OFFICER_CODE_VALUE 			VARCHAR(10),
    ORIGINAL_AMOUNT 			DECIMAL(20,2),
    OUTSTANDING_AMOUNT 			DECIMAL(20,2),
    PERSON_APPROVED_CODE_NUM 	VARCHAR(40),
    PERSON_APPROVED_CODE_VALUE 	VARCHAR(10),
    TERM 						SMALLINT,
    TERM_CODE_NUM 				VARCHAR(40),
    TERM_CODE_VALUE 			VARCHAR(10),
    UTILISED_AMOUNT 			DECIMAL(20,2),
    PRIMARY KEY (CMS_FAC_MASTER_ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_STG_FAC_GENERAL 
    ADD CONSTRAINT FK4D8592A28A6108AE 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_STG_FACILITY_MASTER;

CREATE TABLE CMS_STG_FAC_INSURANCE (
    ID 							BIGINT not null,
    CMS_FAC_MASTER_ID 			BIGINT,
    CMS_REF_ID 					BIGINT,
    CURRENCY_CODE 				CHARACTER(3),
    ARRANGEMENT_IND 			CHARACTER(1),
    COVERAGE_TYPE_CODE_NUM 		VARCHAR(40),
    COVERAGE_TYPE_CODE_VALUE 	VARCHAR(10),
    EFFECTIVE_DATE 				TIMESTAMP,
    EXPIRY_DATE 				TIMESTAMP,
    INSR_COMPANY_CODE_NUM 		VARCHAR(40),
    INSR_COMPANY_CODE_VALUE 	VARCHAR(10),
    INSURANCE_PREMIUM 			DECIMAL(20,2),
    INSURED_AMOUNT 				DECIMAL(20,2),
    ISSUED_DATE 				TIMESTAMP,
    POLICY_NUMBER 				VARCHAR(100),
    POLICY_NUMBER_CV_NOTE 		VARCHAR(100),
    REMARKS 					VARCHAR(100),
	DISPLAY_ORDER 				SMALLINT,
    PRIMARY KEY (ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_STG_FAC_INSURANCE 
    ADD CONSTRAINT FKF5ABA6148A6108AE 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_STG_FACILITY_MASTER;

CREATE TABLE CMS_STG_FAC_OFFICER (
    ID 							BIGINT NOT NULL,
    CMS_FAC_MASTER_ID 			BIGINT,
    CMS_REF_ID 					BIGINT,
    HOST_SEQ_NUM 				BIGINT,
    OFFICER_CODE_NUM 			VARCHAR(40),
    OFFICER_CODE_VALUE 			VARCHAR(10),
    OFFICER_TYPE_CODE_NUM 		VARCHAR(40),
    OFFICER_TYPE_CODE_VALUE 	VARCHAR(10),
    RELATIONSHIP_CODE_NUM 		VARCHAR(40),
    RELATIONSHIP_CODE_VALUE 	VARCHAR(10),
	STATUS 						VARCHAR(1),
    SEQ_NUM 					BIGINT,
    PRIMARY KEY (ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_STG_FAC_OFFICER 
    ADD CONSTRAINT FKF5FD22F08A6108AE 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_STG_FACILITY_MASTER;
    
CREATE INDEX STG_FAC_OFFICER_IDX1
	ON CMS_STG_FAC_OFFICER (CMS_FAC_MASTER_ID)
	ALLOW REVERSE SCANS;

CREATE TABLE CMS_STG_FAC_RELATIONSHIP (
    ID 								BIGINT NOT NULL,
    CMS_FAC_MASTER_ID 				BIGINT,
    CMS_REF_ID 						BIGINT,
    CURRENCY_CODE 					CHARACTER(3),
    ACCT_RELATIONSHIP_CODE_NUM 		VARCHAR(40),
    ACCT_RELATIONSHIP_CODE_VALUE 	VARCHAR(10),
    CIF_NUMBER 						VARCHAR(40),
    CUSTOMER_NAME 					VARCHAR(80),
    CMS_LE_MAIN_PROFILE_ID 			BIGINT,
    DIVIDEND_RATIO 					DOUBLE,
    GUARANTEE_AMOUNT 				DECIMAL(20,2),
    GUARANTEE_PERCENTAGE 			DECIMAL(11,7),
    GUARANTEE_TYPE_IND				CHARACTER(1),
    HOLD_MAIN_CODE_NUM 				VARCHAR(40),
    HOLD_MAIN_CODE_VALUE 			VARCHAR(10),
    HOST_ADD_SEQ_NUM 				BIGINT,
    NAME_ASSOC_WITH_FAC_ORDER 		SMALLINT,
    NAME_CONJUNCTION 				VARCHAR(100),
    NAME_CONJUNCTION_POSITION 		CHARACTER(1),
    PROFIT_RATIO 					DECIMAL(11,7),
    RECEIVE_MAIL_CODE 				CHARACTER(1),
    SHARE_HOLDER_PERCENTAGE 		DECIMAL(11,7),
	STATUS 							VARCHAR(1),
    PRIMARY KEY (ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_STG_FAC_RELATIONSHIP 
    ADD CONSTRAINT FK3118F89E8A6108AE 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_STG_FACILITY_MASTER;
    
CREATE INDEX STG_FAC_RELATIONSHIP_IDX1
	ON CMS_STG_FAC_RELATIONSHIP (CMS_FAC_MASTER_ID)
	ALLOW REVERSE SCANS;

CREATE TABLE CMS_STG_FAC_INTEREST (
    CMS_FAC_MASTER_ID 				BIGINT NOT NULL,
    INTEREST_RATE 					DECIMAL(11,7),
    INTEREST_TYPE_CODE_NUM 			VARCHAR(40),
    INTEREST_TYPE_CODE_VALUE 		VARCHAR(10),
    PRIME_RATE_CEILING 				DECIMAL(11,7),
    PRIME_RATE_FLOOR 				DECIMAL(11,7),
    PRIME_REVIEW_DATE 				TIMESTAMP,
    PRIME_REVIEW_TERM 				SMALLINT,
    PRIME_REVIEW_TERM_CODE_NUM 		VARCHAR(40),
    PRIME_REVIEW_TERM_CODE_VALUE 	VARCHAR(10),
    SPREAD 							DECIMAL(11,7),
    SPREAD_SIGN 					CHARACTER(1),
    INTEREST_BASE					SMALLINT,
	INTEREST_MODE 					CHARACTER(1),
	INTEREST_YEAR_BASE 				SMALLINT,
	NEXT_REVIEW_DATE				TIMESTAMP,
	NEXT_REVIEW_TERM				SMALLINT,
	NEXT_REVIEW_TERM_CODE_NUM		VARCHAR(40),
	NEXT_REVIEW_TERM_CODE_VALUE 	VARCHAR(40),
    PRIMARY KEY (CMS_FAC_MASTER_ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_STG_FAC_INTEREST 
    ADD CONSTRAINT FK194454908A6108AE 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_STG_FACILITY_MASTER;

CREATE TABLE CMS_STG_FAC_PAYMENT (
    CMS_FAC_MASTER_ID 				BIGINT NOT NULL,
    GRADE_PERIOD_CODE_NUM 			VARCHAR(40),
    GRADE_PERIOD_CODE_VALUE 		VARCHAR(10),
    GRADE_PERIOD_CD_CODE_NUM 		VARCHAR(40),
    GRADE_PERIOD_CD_CODE_VALUE 		VARCHAR(10),
    INT_PAYMENT_FREQ_CODE_NUM 		VARCHAR(40),
    INT_PAYMENT_FREQ_CODE_VALUE 	VARCHAR(10),
    PAYMENT_CD_CODE_NUM 			VARCHAR(40),
    PAYMENT_CD_CODE_VALUE 			VARCHAR(10),
    PAYMENT_FREQ_CODE_NUM 			VARCHAR(40),
    PAYMENT_FREQ_CODE_VALUE 		VARCHAR(10),
    PAYMENT_FREQ_CD_CODE_NUM 		VARCHAR(40),
    PAYMENT_FREQ_CD_CODE_VALUE 		VARCHAR(10),
	INT_PAYMENT_FREQ_CD_CODE_NUM 	VARCHAR(40),
	INT_PAYMENT_FREQ_CD_CODE_VALUE 	VARCHAR(10),
    PRIMARY KEY (CMS_FAC_MASTER_ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_STG_FAC_PAYMENT 
    ADD CONSTRAINT FK2368BBC08A6108AE 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_STG_FACILITY_MASTER;
    
CREATE TABLE CMS_FAC_ISLAMIC_MASTER (
    CMS_FAC_MASTER_ID 				BIGINT NOT NULL,
    GPP_TERM						SMALLINT,
    GPP_TERM_CODE					CHAR(1),
    GPP_PAYMENT_MODE_NUM			VARCHAR(40),
    GPP_PAYMENT_MODE_VALUE			VARCHAR(10),
    SELLING_PRICE					DECIMAL(20,2),
    TOTAL_GPP_AMT					DECIMAL(20,2),
    SECURITY_DEP_OF_MTH				SMALLINT,
    SECURITY_DEP_PERCENTAGE			DECIMAL(11,7),
    SECURITY_DEP_AMT				DECIMAL(20,2),
    CUSOTMER_INTEREST_RATE			DECIMAL(11,7),
    GPP_CALCULATION_METHOD_NUM		VARCHAR(40),
    GPP_CALCULATION_MEHTOD_VALUE	VARCHAR(10),
    FULREL_PROFIC_CALC_METHOD		VARCHAR(1),
    COMPOUNDING_METHOD				CHAR(1),
    DATE_STOP_COMPOUNDING			TIMESTAMP,
    REFUND_GPP_PROFIT_NUM			VARCHAR(40),
    REFUND_GPP_PROFIT_VALUE			VARCHAR(10),
    REFUND_FULREL_PROFIT_NUM		VARCHAR(40),
    REFUND_FULREL_PROFIT_VALUE		VARCHAR(10),
    COMMISSION_RATE					DECIMAL(11,7),
    FIXED_COM_AMOUNT				DECIMAL(20,2),
    COMMISSION_TERM					SMALLINT,
    COMMISSION_EXPIRY_DATE			TIMESTAMP,
    EXC_CMP_IN_PMT_AMT				CHAR(1),
    SPTF_DUAL_REPAYMENT_MODE_NUM	VARCHAR(40),
    SPTF_DUAL_REPAYMENT_MODE_VALUE	VARCHAR(10),
    SPTF_GRACE_EXP_DATE             TIMESTAMP,
    SnP_AGREEMENT_DATE				TIMESTAMP,
    GPP_DURATION_FOR_SnP			VARCHAR(1),
    SnP_TERM						SMALLINT,
    SnP_TERM_CODE_NUM				VARCHAR(40),
    SnP_TERM_CODE_VALUE				VARCHAR(10),
    FULL_REL_PFT_12_METHOD			CHAR(1),
    FIXED_AMT_REFUND                DECIMAL(15,2), 
    CURRENCY_CODE 					CHARACTER(3),
    PRIMARY KEY (CMS_FAC_MASTER_ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

CREATE TABLE CMS_STG_FAC_ISLAMIC_MASTER (
    CMS_FAC_MASTER_ID 				BIGINT NOT NULL,
    GPP_TERM						SMALLINT,
    GPP_TERM_CODE					CHAR(1),
    GPP_PAYMENT_MODE_NUM			VARCHAR(40),
    GPP_PAYMENT_MODE_VALUE			VARCHAR(10),
    SELLING_PRICE					DECIMAL(20,2),
    TOTAL_GPP_AMT					DECIMAL(20,2),
    SECURITY_DEP_OF_MTH				SMALLINT,
    SECURITY_DEP_PERCENTAGE			DECIMAL(11,7),
    SECURITY_DEP_AMT				DECIMAL(20,2),
    CUSOTMER_INTEREST_RATE			DECIMAL(11,7),
    GPP_CALCULATION_METHOD_NUM		VARCHAR(40),
    GPP_CALCULATION_MEHTOD_VALUE	VARCHAR(10),
    FULREL_PROFIC_CALC_METHOD		VARCHAR(1),
    COMPOUNDING_METHOD				CHAR(1),
    DATE_STOP_COMPOUNDING			TIMESTAMP,
    REFUND_GPP_PROFIT_NUM			VARCHAR(40),
    REFUND_GPP_PROFIT_VALUE			VARCHAR(10),
    REFUND_FULREL_PROFIT_NUM		VARCHAR(40),
    REFUND_FULREL_PROFIT_VALUE		VARCHAR(10),
    COMMISSION_RATE					DECIMAL(11,7),
    FIXED_COM_AMOUNT				DECIMAL(20,2),
    COMMISSION_TERM					SMALLINT,
    COMMISSION_EXPIRY_DATE			TIMESTAMP,
    EXC_CMP_IN_PMT_AMT				CHAR(1),
    SPTF_DUAL_REPAYMENT_MODE_NUM	VARCHAR(40),
    SPTF_DUAL_REPAYMENT_MODE_VALUE	VARCHAR(10),
    SPTF_GRACE_EXP_DATE             TIMESTAMP,
    SnP_AGREEMENT_DATE				TIMESTAMP,
    GPP_DURATION_FOR_SnP			VARCHAR(1),
    SnP_TERM						SMALLINT,
    SnP_TERM_CODE_NUM				VARCHAR(40),
    SnP_TERM_CODE_VALUE				VARCHAR(10),
    FULL_REL_PFT_12_METHOD			CHAR(1),
    FIXED_AMT_REFUND                DECIMAL(15,2), 
	CURRENCY_CODE 					CHARACTER(3),
    PRIMARY KEY (CMS_FAC_MASTER_ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

CREATE TABLE CMS_FAC_MULTI_TIER_FINANCING (
	ID								BIGINT NOT NULL,
	CMS_FAC_MASTER_ID				BIGINT,
	CMS_REF_ID						BIGINT,
	TIER_SEQ_NO						SMALLINT,
	TIER_TERM						SMALLINT,
	TIER_TERM_CODE					CHAR(1),
	RATE							DECIMAL(11,7),
	STATUS							VARCHAR(1),
	RATE_NUM 						SMALLINT,
	RATE_VARIANCE 					DECIMAL(11,7),
	VARIANCE_CODE 					CHARACTER(1),
	GRACE_PERIOD 					CHARACTER(1),
	PAYMENT_AMOUNT 					DECIMAL(15,2),
	CURRENCY_CODE 					CHARACTER(3),
	PRIMARY KEY (ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_FAC_MULTI_TIER_FINANCING 
    ADD CONSTRAINT FK_FAC_MULTI_TIER 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_FACILITY_MASTER;
    
CREATE INDEX CMS_FAC_MULTI_TIER_FIN_IDX1
	ON CMS_FAC_MULTI_TIER_FINANCING (CMS_FAC_MASTER_ID, CMS_REF_ID)
	ALLOW REVERSE SCANS;
     
CREATE TABLE CMS_STG_FAC_MULTI_TIER_FINANCING (
	ID								BIGINT NOT NULL,
	CMS_FAC_MASTER_ID				BIGINT,
	CMS_REF_ID						BIGINT,
	TIER_SEQ_NO						SMALLINT,
	TIER_TERM						SMALLINT,
	TIER_TERM_CODE					CHAR(1),
	RATE							DECIMAL(11,7),
	STATUS							VARCHAR(1),
	RATE_NUM 						SMALLINT,
	RATE_VARIANCE 					DECIMAL(11,7),
	VARIANCE_CODE 					CHARACTER(1),
	GRACE_PERIOD 					CHARACTER(1),
	PAYMENT_AMOUNT 					DECIMAL(15,2),
	CURRENCY_CODE 					CHARACTER(3),
	PRIMARY KEY (ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_STG_FAC_MULTI_TIER_FINANCING 
    ADD CONSTRAINT FK_STG_MULTI_TIER
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_STG_FACILITY_MASTER;   
    
CREATE INDEX STG_FAC_MULTI_TIER_FINANCING_IDX1
	ON CMS_STG_FAC_MULTI_TIER_FINANCING (CMS_FAC_MASTER_ID)
	ALLOW REVERSE SCANS;
    
CREATE TABLE CMS_FAC_BBA_VARI_PACKAGE (
	CMS_FAC_MASTER_ID				BIGINT NOT NULL,
	CUST_PROF_RATE					DECIMAL(11,7),
	REBATE_METHOD					CHAR(1),
	GPP_PAYMENT_MODE				CHAR(1),
	GPP_CAL_METHOD					CHAR(1),
	GPP_TERM						SMALLINT,
	GPP_TERM_CODE					CHAR(1),
	FULL_RELEASE_PROFIT				CHAR(1),
	REFUND_FULL_RELEASE_PROFIT		CHAR(1),
	FUL_REL_PROFIT_CAL_METHOD		CHAR(1),
	INSTALLMENT						DECIMAL(20,2),
	FINAL_PAYMENT_AMT				DECIMAL(20,2),
	TOTAL_GPP_AMT					DECIMAL(20,2),
	SELLING_PRICE					DECIMAL(20,2),
	TOTAL_PROFIT					DECIMAL(20,2),
	LAST_MAINTAIN_DATE				TIMESTAMP,
	CURRENCY_CODE 					CHARACTER(3),
	PRIMARY KEY (CMS_FAC_MASTER_ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

CREATE TABLE CMS_STG_FAC_BBA_VARI_PACKAGE (
	CMS_FAC_MASTER_ID				BIGINT NOT NULL,
	CUST_PROF_RATE					DECIMAL(11,7),
	REBATE_METHOD					CHAR(1),
	GPP_PAYMENT_MODE				CHAR(1),
	GPP_CAL_METHOD					CHAR(1),
	GPP_TERM						SMALLINT,
	GPP_TERM_CODE					CHAR(1),
	FULL_RELEASE_PROFIT				CHAR(1),
	REFUND_FULL_RELEASE_PROFIT		CHAR(1),
	FUL_REL_PROFIT_CAL_METHOD		CHAR(1),
	INSTALLMENT						DECIMAL(20,2),
	FINAL_PAYMENT_AMT				DECIMAL(20,2),
	TOTAL_GPP_AMT					DECIMAL(20,2),
	SELLING_PRICE					DECIMAL(20,2),
	TOTAL_PROFIT					DECIMAL(20,2),
	LAST_MAINTAIN_DATE				TIMESTAMP,
	CURRENCY_CODE 					CHARACTER(3),
	PRIMARY KEY (CMS_FAC_MASTER_ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

CREATE TABLE CMS_FAC_MESSAGE (
    ID BIGINT NOT NULL,
    CMS_REF_ID BIGINT,
    CMS_FAC_MASTER_ID BIGINT,
    MESSAGE VARCHAR(300),
    MSG_TYPE_CODE_NUM VARCHAR(40),
    MSG_TYPE_CODE_VALUE VARCHAR(10),
    MSG_SEVERITY_CODE_NUM VARCHAR(40),
    MSG_SEVERITY_CODE_VALUE VARCHAR(10),
    EXPIRATION_DATE TIMESTAMP,
    SEQ_NO BIGINT,
    STATUS VARCHAR(1),
    PRIMARY KEY (ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_FAC_MESSAGE 
    ADD CONSTRAINT FK1EE7C77A19860C7 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_FACILITY_MASTER;

CREATE TABLE CMS_FAC_RENTAL_RENEWAL (
    CMS_FAC_MASTER_ID BIGINT NOT NULL,
    RENEWAL_TERM BIGINT,
    RENEWAL_TERM_CODE_NUM VARCHAR(40),
    RENEWAL_TERM_CODE_VALUE VARCHAR(10),
    PRIME_RATE_CODE_NUM VARCHAR(40),
    PRIME_RATE_CODE_VALUE VARCHAR(10),
    RENEWAL_RATE DECIMAL(11,7),
    PRIME_VARIANCE DECIMAL(11,7),
    PRIME_VARIANCE_CODE VARCHAR(1),
    STATUS VARCHAR(1),
    PRIMARY KEY (CMS_FAC_MASTER_ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_FAC_RENTAL_RENEWAL 
    ADD CONSTRAINT FKE049104A19860C7 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_FACILITY_MASTER;

CREATE TABLE CMS_FAC_SECURITY_DEPOSIT (
    CMS_FAC_MASTER_ID BIGINT NOT NULL,
    NUM_OF_MONTH BIGINT,
    SECURITY_DEPOSIT DECIMAL(11,7),
    FIX_SECURITY_DEPOSIT_AMOUNT DECIMAL(15,2),
    ORIG_SECURITY_DEPOSIT_AMOUNT DECIMAL(15,2),
    STATUS VARCHAR(1),
    IS_RECAL_UPON_REVIEW VARCHAR(1),
    MTH_BEFORE_PRINT_REN_RPT INTEGER,
    REMARKS VARCHAR(60),
    PRIMARY KEY (CMS_FAC_MASTER_ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_FAC_SECURITY_DEPOSIT 
    ADD CONSTRAINT FKDC2C8A4C19860C7 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_FACILITY_MASTER;
    
CREATE TABLE CMS_STG_FAC_MESSAGE (
    ID BIGINT NOT NULL,
    CMS_REF_ID BIGINT,
    CMS_FAC_MASTER_ID BIGINT,
    MESSAGE VARCHAR(300),
    MSG_TYPE_CODE_NUM VARCHAR(40),
    MSG_TYPE_CODE_VALUE VARCHAR(10),
    MSG_SEVERITY_CODE_NUM VARCHAR(40),
    MSG_SEVERITY_CODE_VALUE VARCHAR(10),
    EXPIRATION_DATE TIMESTAMP,
    SEQ_NO BIGINT,
    STATUS VARCHAR(1),
    PRIMARY KEY (ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_STG_FAC_MESSAGE 
    ADD CONSTRAINT FK8B3789C148CAE557 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_STG_FACILITY_MASTER;

CREATE TABLE CMS_STG_FAC_RENTAL_RENEWAL (
    CMS_FAC_MASTER_ID BIGINT NOT NULL,
    RENEWAL_TERM BIGINT,
    RENEWAL_TERM_CODE_NUM VARCHAR(40),
    RENEWAL_TERM_CODE_VALUE VARCHAR(10),
    PRIME_RATE_CODE_NUM VARCHAR(40),
    PRIME_RATE_CODE_VALUE VARCHAR(10),
    RENEWAL_RATE DECIMAL(11,7),
    PRIME_VARIANCE DECIMAL(11,7),
    PRIME_VARIANCE_CODE VARCHAR(1),
    STATUS VARCHAR(1),
    PRIMARY KEY (CMS_FAC_MASTER_ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_STG_FAC_RENTAL_RENEWAL 
    ADD CONSTRAINT FK408E802348CAE557 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_STG_FACILITY_MASTER;

CREATE TABLE CMS_STG_FAC_SECURITY_DEPOSIT (
    CMS_FAC_MASTER_ID BIGINT NOT NULL,
    NUM_OF_MONTH BIGINT,
    SECURITY_DEPOSIT DECIMAL(11,7),
    FIX_SECURITY_DEPOSIT_AMOUNT DECIMAL(15,2),
    ORIG_SECURITY_DEPOSIT_AMOUNT DECIMAL(15,2),
    STATUS VARCHAR(1),
    IS_RECAL_UPON_REVIEW VARCHAR(1),
    MTH_BEFORE_PRINT_REN_RPT INTEGER,
    REMARKS VARCHAR(60),
    PRIMARY KEY (CMS_FAC_MASTER_ID)
) IN CMS_SMALL_DATA INDEX IN CMS_INDEX;

ALTER TABLE CMS_STG_FAC_SECURITY_DEPOSIT 
    ADD CONSTRAINT FK40D567E548CAE557 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_STG_FACILITY_MASTER;
    
CREATE TABLE CMS_FAC_INCREMENTAL (
    ID 							BIGINT NOT NULL,
    CMS_REF_ID 					BIGINT,
    CMS_FAC_MASTER_ID 			BIGINT,
    INCREMENTAL_NUMBER 			INTEGER,
    AMOUNT_APPLIED 				DECIMAL(15,2),
    INCREMENTAL_LIMIT 			DECIMAL(15,2),
    ORIGINAL_LIMIT 				DECIMAL(15,2),
    APPLICATION_DATE 			TIMESTAMP,
    LOAN_PURPOSE_CODE_NUM 		VARCHAR(40),
    LOAN_PURPOSE_CODE_VALUE 	VARCHAR(10),
    DATE_OF_OFFER 				TIMESTAMP,
    DATE_OFFER_ACCEPTED 		TIMESTAMP,
    DATE_APPROVED 				TIMESTAMP,
    PERSON_APPROVED_CODE_NUM 	VARCHAR(40),
    PERSON_APPROVED_CODE_VALUE 	VARCHAR(10),
    CANCEL_REJECT_CODE_NUM 		VARCHAR(40),
    CANCEL_REJECT_CODE_VALUE 	VARCHAR(10),
    CANCEL_REJECT_DATE 			TIMESTAMP,
    FACILITY_STATUS_CODE_NUM 	VARCHAR(40),
    FACILITY_STATUS_CODE_VALUE 	VARCHAR(10),
    DEALER_LLP_CODE_NUM 		VARCHAR(40),
    DEALER_LLP_CODE_VALUE 		VARCHAR(40),
    SOLICITOR_NAME 				VARCHAR(255),
    REQUEST_REASON_CODE_NUM 	VARCHAR(40),
    REQUEST_REASON_CODE_VALUE 	VARCHAR(10),
    DOC_STATUS_CODE_NUM 		VARCHAR(40),
    DOC_STATUS_CODE_VALUE 		VARCHAR(10),
    LAWYER_CODE_NUM 			VARCHAR(40),
    LAWYER_CODE_VALUE 			VARCHAR(10),
    STATUS 						VARCHAR(1),
	PRIME_REVIEW_DATE 			TIMESTAMP,
	PRIME_REVIEW_TERM 			INTEGER,
	PRIME_REVIEW_TERM_NUM 		varchar(40),
	PRIME_REVIEW_TERM_VALUE 	VARCHAR(10),
	DATE_SEND_DECISION_CENTER 	TIMESTAMP,
	DATE_RECEIVE_DECISION_CENTER TIMESTAMP,
	DATE_APPROVE_BY_CGC_BNM 	TIMESTAMP,
	DATE_ENTER_OFFER 			TIMESTAMP,
	DATE_ENTER_APPLIED 			TIMESTAMP,
	DATE_ENTER_APPROVE 			TIMESTAMP,
	DATE_ENTER_OFFER_ACCEPTANCE TIMESTAMP,
	DATE_ENTER_CANCEL_REJECT 	TIMESTAMP,
	DOCUMENTATION_DATE 			TIMESTAMP,
	DATE_INSTRUCTED 			TIMESTAMP,
	SOLICITOR_REFERENCE 		VARCHAR(40),
	DATE_ENTERED 				TIMESTAMP,
    PRIMARY KEY (ID)
);
    
CREATE TABLE CMS_STG_FAC_INCREMENTAL (
    ID 							BIGINT NOT NULL,
    CMS_REF_ID 					BIGINT,
    CMS_FAC_MASTER_ID 			BIGINT,
    INCREMENTAL_NUMBER 			INTEGER,
    AMOUNT_APPLIED 				DECIMAL(15,2),
    INCREMENTAL_LIMIT 			DECIMAL(15,2),
    ORIGINAL_LIMIT 				DECIMAL(15,2),
    APPLICATION_DATE 			TIMESTAMP,
    LOAN_PURPOSE_CODE_NUM 		VARCHAR(40),
    LOAN_PURPOSE_CODE_VALUE 	VARCHAR(10),
    DATE_OF_OFFER 				TIMESTAMP,
    DATE_OFFER_ACCEPTED 		TIMESTAMP,
    DATE_APPROVED 				TIMESTAMP,
    PERSON_APPROVED_CODE_NUM 	VARCHAR(40),
    PERSON_APPROVED_CODE_VALUE 	VARCHAR(10),
    CANCEL_REJECT_CODE_NUM 		VARCHAR(40),
    CANCEL_REJECT_CODE_VALUE 	VARCHAR(10),
    CANCEL_REJECT_DATE 			TIMESTAMP,
    FACILITY_STATUS_CODE_NUM 	VARCHAR(40),
    FACILITY_STATUS_CODE_VALUE 	VARCHAR(10),
    DEALER_LLP_CODE_NUM 		VARCHAR(40),
    DEALER_LLP_CODE_VALUE 		VARCHAR(40),
    SOLICITOR_NAME 				VARCHAR(255),
    REQUEST_REASON_CODE_NUM 	VARCHAR(40),
    REQUEST_REASON_CODE_VALUE 	VARCHAR(10),
    DOC_STATUS_CODE_NUM 		VARCHAR(40),
    DOC_STATUS_CODE_VALUE 		VARCHAR(10),
    LAWYER_CODE_NUM 			VARCHAR(40),
    LAWYER_CODE_VALUE 			VARCHAR(10),
    STATUS 						VARCHAR(1),
	PRIME_REVIEW_DATE 			TIMESTAMP,
	PRIME_REVIEW_TERM 			INTEGER,
	PRIME_REVIEW_TERM_NUM 		varchar(40),
	PRIME_REVIEW_TERM_VALUE 	VARCHAR(10),
	DATE_SEND_DECISION_CENTER 	TIMESTAMP,
	DATE_RECEIVE_DECISION_CENTER TIMESTAMP,
	DATE_APPROVE_BY_CGC_BNM 	TIMESTAMP,
	DATE_ENTER_OFFER 			TIMESTAMP,
	DATE_ENTER_APPLIED 			TIMESTAMP,
	DATE_ENTER_APPROVE 			TIMESTAMP,
	DATE_ENTER_OFFER_ACCEPTANCE TIMESTAMP,
	DATE_ENTER_CANCEL_REJECT 	TIMESTAMP,
	DOCUMENTATION_DATE 			TIMESTAMP,
	DATE_INSTRUCTED 			TIMESTAMP,
	SOLICITOR_REFERENCE 		VARCHAR(40),
	DATE_ENTERED 				TIMESTAMP,    
    PRIMARY KEY (ID)
);

CREATE TABLE CMS_FAC_REDUCTION (
    ID 							BIGINT NOT NULL,
    CMS_REF_ID 					BIGINT,
    CMS_FAC_MASTER_ID 			BIGINT,
    INCREMENTAL_NUMBER 			INTEGER,
    AMOUNT_APPLIED 				DECIMAL(15,2),
    INCREMENTAL_LIMIT 			DECIMAL(15,2),
    ORIGINAL_LIMIT 				DECIMAL(15,2),
    APPLICATION_DATE 			TIMESTAMP,
    DATE_OFFER_ACCEPTED 		TIMESTAMP,
    DATE_APPROVED 				TIMESTAMP,
    PERSON_APPROVED_CODE_NUM 	VARCHAR(40),
    PERSON_APPROVED_CODE_VALUE 	VARCHAR(10),
    CANCEL_REJECT_CODE_NUM 		VARCHAR(40),
    CANCEL_REJECT_CODE_VALUE 	VARCHAR(10),
    CANCEL_REJECT_DATE 			TIMESTAMP,
    FACILITY_STATUS_CODE_NUM 	VARCHAR(40),
    FACILITY_STATUS_CODE_VALUE 	VARCHAR(10),
    SOLICITOR_NAME 				VARCHAR(255),
    REQUEST_REASON_CODE_NUM 	VARCHAR(40),
    REQUEST_REASON_CODE_VALUE 	VARCHAR(10),
    DOC_STATUS_CODE_NUM 		VARCHAR(40),
    DOC_STATUS_CODE_VALUE 		VARCHAR(10),
    LAWYER_CODE_NUM 			VARCHAR(40),
    LAWYER_CODE_VALUE 			VARCHAR(10),
    STATUS 						VARCHAR(1),
	DATE_ENTER_OFFER 			TIMESTAMP,
	DATE_ENTER_APPLIED 			TIMESTAMP,
	DATE_ENTER_APPROVE 			TIMESTAMP,
	DATE_ENTER_OFFER_ACCEPTANCE TIMESTAMP,
	DATE_ENTER_CANCEL_REJECT 	TIMESTAMP,
	DOCUMENTATION_DATE 			TIMESTAMP,
	DATE_INSTRUCTED 			TIMESTAMP,
	SOLICITOR_REFERENCE 		VARCHAR(40),
	DATE_ENTERED 				TIMESTAMP,       
    PRIMARY KEY (ID)
);

CREATE TABLE CMS_STG_FAC_REDUCTION (
    ID 							BIGINT NOT NULL,
    CMS_REF_ID 					BIGINT,
    CMS_FAC_MASTER_ID 			BIGINT,
    INCREMENTAL_NUMBER 			INTEGER,
    AMOUNT_APPLIED 				DECIMAL(15,2),
    INCREMENTAL_LIMIT 			DECIMAL(15,2),
    ORIGINAL_LIMIT 				DECIMAL(15,2),
    APPLICATION_DATE 			TIMESTAMP,
    DATE_OFFER_ACCEPTED 		TIMESTAMP,
    DATE_APPROVED 				TIMESTAMP,
    PERSON_APPROVED_CODE_NUM 	VARCHAR(40),
    PERSON_APPROVED_CODE_VALUE 	VARCHAR(10),
    CANCEL_REJECT_CODE_NUM 		VARCHAR(40),
    CANCEL_REJECT_CODE_VALUE 	VARCHAR(10),
    CANCEL_REJECT_DATE 			TIMESTAMP,
    FACILITY_STATUS_CODE_NUM 	VARCHAR(40),
    FACILITY_STATUS_CODE_VALUE 	VARCHAR(10),
    SOLICITOR_NAME 				VARCHAR(255),
    REQUEST_REASON_CODE_NUM 	VARCHAR(40),
    REQUEST_REASON_CODE_VALUE 	VARCHAR(10),
    DOC_STATUS_CODE_NUM 		VARCHAR(40),
    DOC_STATUS_CODE_VALUE 		VARCHAR(10),
    LAWYER_CODE_NUM 			VARCHAR(40),
    LAWYER_CODE_VALUE 			VARCHAR(10),
    STATUS 						VARCHAR(1),
	DATE_ENTER_OFFER 			TIMESTAMP,
	DATE_ENTER_APPLIED 			TIMESTAMP,
	DATE_ENTER_APPROVE 			TIMESTAMP,
	DATE_ENTER_OFFER_ACCEPTANCE TIMESTAMP,
	DATE_ENTER_CANCEL_REJECT 	TIMESTAMP,
	DOCUMENTATION_DATE 			TIMESTAMP,
	DATE_INSTRUCTED 			TIMESTAMP,
	SOLICITOR_REFERENCE 		VARCHAR(40),
	DATE_ENTERED 				TIMESTAMP,       
    PRIMARY KEY (ID)
);
    
ALTER TABLE CMS_FAC_INCREMENTAL 
    ADD CONSTRAINT FKC33845CD19860C7 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_FACILITY_MASTER;
    
ALTER TABLE CMS_FAC_REDUCTION 
    ADD CONSTRAINT FKD378652619860C7 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_FACILITY_MASTER;
    
ALTER TABLE CMS_STG_FAC_INCREMENTAL 
    ADD CONSTRAINT FK21BF8C9448CAE557 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_STG_FACILITY_MASTER;
    
ALTER TABLE CMS_STG_FAC_REDUCTION 
    ADD CONSTRAINT FK6AE0B1AD48CAE557 
    FOREIGN KEY (CMS_FAC_MASTER_ID) 
    REFERENCES CMS_STG_FACILITY_MASTER;
