DROP PROCEDURE PROC_LIMIT_BOOK_UPDATE_EXPIRED@

CREATE PROCEDURE PROC_LIMIT_BOOK_UPDATE_EXPIRED
	LANGUAGE SQL
BEGIN 
	UPDATE CMS_LMT_BOOK SET (BK_STATUS, LAST_MODIFIED_DATE) = ('E', CURRENT TIMESTAMP)
	WHERE DATE( EXPIRY_DATE ) = DATE(CURRENT TIMESTAMP)
	AND BK_STATUS = 'B';	
	
END
@