--------------------------------
--- CMS_INSURANCE_COVERAGE 
--------------------------------

CREATE TABLE CMS_INSURANCE_COVERAGE (
		  ID BIGINT NOT NULL , 
		  'INSURANCE_COVERAGE_CODE' VARCHAR(10) NOT NULL,
		  'COMPANY_NAME' VARCHAR(50) NOT NULL,	 
		  'ADDRESS' VARCHAR(200) , 
		  'CONTACT_NUMBER' BIGINT ,	  
		  'VERSION_TIME' BIGINT NOT NULL , 
		  'CREATE_BY' VARCHAR(25) NOT NULL , 
		  'CREATION_DATE' TIMESTAMP NOT NULL , 
		  'LAST_UPDATE_BY' VARCHAR(25) NOT NULL , 
		  'LAST_UPDATE_DATE' TIMESTAMP NOT NULL , 
		  'DEPRECATED' CHAR(1) NOT NULL , 
		  'STATUS' VARCHAR(30) NOT NULL )   
		 IN CMS_SMALL_DATA INDEX IN CMS_INDEX ; 



ALTER TABLE CMS_INSURANCE_COVERAGE 
	ADD CONSTRAINT PK_INSURANCE_COVERAGE PRIMARY KEY
		(ID);
		
alter table CMS_INSURANCE_COVERAGE add unique (INSURANCE_COVERAGE_CODE)			

--------------------------------
--- CMS_STAGE_INSURANCE_COVERAGE 
--------------------------------

CREATE TABLE CMS_STAGE_INSURANCE_COVERAGE  (		   
		  ID BIGINT NOT NULL , 
		  'INSURANCE_COVERAGE_CODE' VARCHAR(10) NOT NULL,
		  'COMPANY_NAME' VARCHAR(50) NOT NULL,	 
		  'ADDRESS' VARCHAR(200) , 
		  'CONTACT_NUMBER' BIGINT ,	  
		  'VERSION_TIME' BIGINT NOT NULL , 
		  'CREATE_BY' VARCHAR(25) NOT NULL , 
		  'CREATION_DATE' TIMESTAMP NOT NULL , 
		  'LAST_UPDATE_BY' VARCHAR(25) NOT NULL , 
		  'LAST_UPDATE_DATE' TIMESTAMP NOT NULL , 
		  'DEPRECATED' CHAR(1) NOT NULL , 
		  'STATUS' VARCHAR(30) NOT NULL ) 
		 IN CMS_SMALL_DATA INDEX IN CMS_INDEX ;

ALTER TABLE CMS_STAGE_INSURANCE_COVERAGE  
	ADD CONSTRAINT PK_INSURANCE_COVERAGE PRIMARY KEY
		(ID);


INSERT INTO CMS_INSURANCE_COVERAGE VALUES(1,'011','Aegon Religare ','Lower Parel Mumbai',2265484514,0,'SC_MAKER','2011-04-12-15.21.43.557000','SC_MAKER','2011-04-12-15.21.43.557000','N','ACTIVE');

INSERT INTO CMS_STAGE_INSURANCE_COVERAGE VALUES(1,'011','Aegon Religare ','Lower Parel Mumbai',2265484514,0,'SC_MAKER','2011-04-12-15.21.43.557000','SC_MAKER','2011-04-12-15.21.43.557000','N','ACTIVE');