--DROP TABLE SI_TEMP_STBG_CO022;
--DROP TABLE SI_TEMP_STBG_CO023;
--DROP TABLE SI_TEMP_STBG_CO024;
--DROP TABLE SI_TEMP_STBG_CO024_PLEDGOR;
--DROP TABLE SI_TEMP_STBG_PF001;
--DROP TABLE SI_TEMP_STBG_PF002;
--DROP TABLE SI_TEMP_STBG_SH001;

CREATE TABLE SI_TEMP_STBG_CO022 (
  RECORD_TYPE	VARCHAR(1),
  SECURITY_ID	VARCHAR(29),
  CIF_ID	VARCHAR(19),
  SECURITY_TYPE	VARCHAR(2),
  CMS_SECURITY_TYPE_ID	VARCHAR(5),
  CMS_SECURITY_SUBTYPE_ID	VARCHAR(10),
  ORIGINAL_CURRENCY	VARCHAR(3),
  LOC_COUNTRY	VARCHAR(2),
  SECURITY_CUSTODIAN_TYPE	VARCHAR(1),
  SECURITY_EXPIRY_DATE	TIMESTAMP,
  EXCHANGE_CONTROL_OBTAINED	VARCHAR(1),
  LEGAL_ENFORCEABILITY	VARCHAR(1),
  LEGAL_ENFORCEABILITY_DATE	TIMESTAMP,
  SECURITY_PERFECTION_DATE	TIMESTAMP,
  TYPE	VARCHAR(20),
  NOMINEE_NAME	VARCHAR(120),
  REGISTERED_NAME	VARCHAR(120),
  UNITS	BIGINT,
  UNITS_SIGN	VARCHAR(1),
  UNIT_PRICE	DECIMAL(10,6),
  CUSTODIAN_TYPE	VARCHAR(1),
  CUSTODIAN	VARCHAR(120),
  MATURITY_DATE	TIMESTAMP,
  STOCK_EXCHANGE	VARCHAR(3),
  STOCK_EXCHANGE_COUNTRY	VARCHAR(2),
  INDEX_NAME	VARCHAR(10),
  STOCK_CODE	VARCHAR(14),
  ISIN_CODE	VARCHAR(20),
  RECOGNIZED_EXCHANGE	VARCHAR(1),
  CMS_COLLATERAL_ID	BIGINT,
  CMS_COLLATERAL_ID_STG	BIGINT,
  CMS_LSP_SYS_XREF_ID BIGINT,
  CMS_LSP_APPR_LMTS_ID	BIGINT,
	CMS_LIMIT_PROFILE_ID	BIGINT,
  IS_VALID	CHARACTER(1)	DEFAULT 'Y'
) 
  in CMS_BATCH index in CMS_BATCH_INDEX;

CREATE TABLE SI_TEMP_STBG_CO023 (
  RECORD_TYPE	VARCHAR(1),
  CIF	VARCHAR(19),
  SECURITY_ID	VARCHAR(29),
  SHARE_ID	VARCHAR(50),
  TRANSACTION_DATE	TIMESTAMP,
  SHARES_TYPE	VARCHAR(1),
  UNITS	BIGINT,
  SIGN_OF_UNITS	VARCHAR(1),
	CMS_ITEM_ID	BIGINT,
  IS_VALID	CHARACTER(1)	DEFAULT 'Y'
) 
  in CMS_BATCH index in CMS_BATCH_INDEX;

CREATE TABLE SI_TEMP_STBG_CO024 (
  RECORD_TYPE	VARCHAR(1),
  SECURITY_ID	VARCHAR(27),
  CIF_NUMBER	VARCHAR(19),
  SETTLEMENT_ACCT_NUMBER	VARCHAR(19),
  PLEDGOR_CIF_SOURCE	VARCHAR(4),
  PLEDGOR_LEGAL_NAME	VARCHAR(50),
  INCORPORATION_COUNTRY	VARCHAR(2),
  ID_DESC	VARCHAR(40),
  ID_TYPE	VARCHAR(3),
  CMS_PLEDGOR_DTL_ID	BIGINT,
  CMS_COLLATERAL_ID	BIGINT,
  IS_VALID	CHARACTER(1)	DEFAULT 'Y'
) 
  in CMS_BATCH index in CMS_BATCH_INDEX;

CREATE TABLE SI_TEMP_STBG_CO024_PLEDGOR (
  CIF_NUMBER	VARCHAR(19),
  SETTLEMENT_ACCT_NUMBER	VARCHAR(19),
  PLEDGOR_CIF_SOURCE	VARCHAR(4),
  PLEDGOR_LEGAL_NAME	VARCHAR(50),
  INCORPORATION_COUNTRY	VARCHAR(2),
  ID_CAT	VARCHAR(10)	DEFAULT 'ID_TYPE',
  ID_DESC	VARCHAR(40),
  ID_TYPE	VARCHAR(3)
) 
  in CMS_BATCH index in CMS_BATCH_INDEX;

CREATE TABLE SI_TEMP_STBG_PF001 (
  RECORD_TYPE	VARCHAR(1),
  STOCK_CODE	VARCHAR(10),
  COUNTER_NAME	VARCHAR(50),
  EXCHANGE_CODE	VARCHAR(3),
  UNIT_PRICE	DECIMAL(7,3),
  UNIT_PRICE_CURRENCY	VARCHAR(3),
  ISIN_CODE	VARCHAR(20),
  STOCK_EXCHG_TRAD_BOARD_CAT	VARCHAR(10),
  STOCK_EXCHG_TRAD_BOARD_CODE	VARCHAR(5),
  STOCK_EXCHG_TRAD_BOARD_DESC	VARCHAR(40),
  STOCK_TYPES	VARCHAR(3),
  LISTED_SHARES_QUANTITY	BIGINT,
  PAR_VALUE	DECIMAL(20,2),
  PAID_UP_CAPITAL	DECIMAL(20,2),
  EXPIRY_DATE	TIMESTAMP,
  SHARE_STAT	VARCHAR(3),
  STOCK_EXCHG_SUSPEND_COUNT_IND	VARCHAR(1),
	FEED_GROUP_ID	BIGINT,
	STAGE_FEED_GROUP_ID	BIGINT,
  IS_VALID	CHARACTER(1)	DEFAULT 'Y'
) 
  in CMS_BATCH index in CMS_BATCH_INDEX;

CREATE TABLE SI_TEMP_STBG_PF002 (
  RECORD_TYPE	VARCHAR(1),
  EXCHANGE_CODE	VARCHAR(3),
  STOCK_INDEX_CODE	VARCHAR(3),
  STOCK_INDEX_PRICE	DECIMAL(20,2),
	FEED_GROUP_ID	BIGINT,
	STAGE_FEED_GROUP_ID	BIGINT,
  IS_VALID	CHARACTER(1)	DEFAULT 'Y'
) 
  in CMS_BATCH index in CMS_BATCH_INDEX;

CREATE TABLE SI_TEMP_STBG_SH001 (
  RECORD_TYPE	VARCHAR(1),
  COUNTER_CODE	VARCHAR(14),
  STOCK_CODE	VARCHAR(14),
  ISIN_CODE	VARCHAR(20),
  STOCK_EXCHANGE_CODE	VARCHAR(3),
  STOCK_EXCHANGE_COUNTRY	VARCHAR(2),
  TOTAL_NO_OF_UNIT	BIGINT,
  SIGN_OF_UNIT	VARCHAR(1),
  ISSUER_NAME	VARCHAR(40),
  IS_VALID	CHARACTER(1)	DEFAULT 'Y'
) 
  in CMS_BATCH index in CMS_BATCH_INDEX;

CREATE INDEX SI_STBG_CO022_IDX1 ON SI_TEMP_STBG_CO022
(IS_VALID ASC, SECURITY_ID ASC, CIF_ID ASC) ALLOW REVERSE SCANS;

create index SI_STBG_CO022_IDX2 on si_temp_stbg_co022 (is_valid asc, cms_lsp_sys_xref_id asc)
allow reverse scans;

CREATE INDEX SI_STBG_CO023_IDX1 ON SI_TEMP_STBG_CO023
(IS_VALID ASC, SECURITY_ID ASC, SHARE_ID ASC) ALLOW REVERSE SCANS;

CREATE INDEX SI_STBG_CO024_IDX1 ON SI_TEMP_STBG_CO024
(IS_VALID ASC, SECURITY_ID ASC, CIF_NUMBER ASC) ALLOW REVERSE SCANS;

CREATE INDEX SI_STBG_CO024_PLDGR_IDX1 ON SI_TEMP_STBG_CO024_PLEDGOR
(CIF_NUMBER ASC) ALLOW REVERSE SCANS;

CREATE INDEX SI_STBG_PF001_IDX1 ON SI_TEMP_STBG_PF001
(IS_VALID ASC, STOCK_CODE ASC, ISIN_CODE ASC) ALLOW REVERSE SCANS;

CREATE INDEX SI_STBG_PF002_IDX1 ON SI_TEMP_STBG_PF002
(IS_VALID ASC, STOCK_INDEX_CODE ASC) ALLOW REVERSE SCANS;

CREATE INDEX SI_STBG_SH001_IDX1 ON SI_TEMP_STBG_SH001
(IS_VALID ASC, STOCK_CODE ASC, STOCK_EXCHANGE_CODE ASC, ISIN_CODE ASC) ALLOW REVERSE SCANS;

COMMIT;
