-- Branch Number Mapping
DROP PROCEDURE BR_RUN_RPT_BVLNCMBR@

CREATE PROCEDURE BR_RUN_RPT_BVLNCMBR
LANGUAGE SQL

BEGIN

CALL BR_LOG_PROC_TIME('BR_RUN_RPT_BVLNCMBR', 'BVLNCMBR', 1);

-----------------------------
-- AA
-----------------------------
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-AA', 0, 'Branch Rationalization Audit Report', 'BVLNCMBR', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-AA', 0, 'Mapping file name: BVLNCMBR', 'BVLNCMBR', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-AA', 0, '"Branch Rationalization for AA (SEMA, Quantum, Trade Spring)"', 'BVLNCMBR', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-AA', 0, 'Report Date: ' || char(current date)  || chr(13) || chr(10), 'BVLNCMBR', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-AA', 0, 'Old Branch No.,New Branch No.,AA Number,Source System,AA Status', 'BVLNCMBR', CURRENT_TIMESTAMP);

INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) 
  (SELECT 'BRM-AA', A.KEY_VALUE_1, '''' || A.OLD_VALUE || ',''' || A.NEW_VALUE || ',''' || A.KEY_VALUE_2 || ',' || A.SOURCE_ID || ',' || (CASE P.UPDATE_STATUS_IND WHEN 'D' THEN 'DELETED' ELSE 'ACTIVE' END), 'BVLNCMBR', CURRENT_TIMESTAMP
		FROM BR_AUDIT_LOG A, SCI_LSP_LMT_PROFILE P
    WHERE A.TABLE_NAME = 'SCI_LSP_LMT_PROFILE' AND A.COLUMN_NAME = 'CMS_ORIG_ORGANISATION' AND A.SOURCE_ID IN ('SEMA','QUAN','TSPR') 
	AND P.CMS_LSP_LMT_PROFILE_ID = A.KEY_VALUE_1 AND A.SOURCE_ID = P.SOURCE_ID
	ORDER BY A.SOURCE_ID);

CALL BR_LOG_PROC_TIME('BR_RUN_RPT_BVLNCMBR', 'BVLNCMBR', 2);
COMMIT;

-----------------------------
-- Limit
-----------------------------
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-LIMIT', 0, 'Branch Rationalization Audit Report', 'BVLNCMBR', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-LIMIT', 0, 'Mapping file name: BVLNCMBR', 'BVLNCMBR', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-LIMIT', 0, '"Branch Rationalization for Limit (SEMA, Quantum, Trade Spring)"', 'BVLNCMBR', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-LIMIT', 0, 'Report Date: ' || char(current date)  || chr(13) || chr(10), 'BVLNCMBR', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-LIMIT', 0, 'Old Branch No.,New Branch No.,Limit ID,Source System,Limit Status', 'BVLNCMBR', CURRENT_TIMESTAMP);

INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) 
  (SELECT 'BRM-LIMIT', A.KEY_VALUE_1, '''' || A.OLD_VALUE || ',''' || A.NEW_VALUE || ',''' || A.KEY_VALUE_2 || ',' || A.SOURCE_ID || ',' || L.CMS_LIMIT_STATUS, 'BVLNCMBR', CURRENT_TIMESTAMP
		FROM BR_AUDIT_LOG A, SCI_LSP_APPR_LMTS L
    WHERE A.TABLE_NAME = 'SCI_LSP_APPR_LMTS' AND A.COLUMN_NAME = 'CMS_BKG_ORGANISATION' AND A.SOURCE_ID IN ('SEMA','QUAN','TSPR') 
	AND L.CMS_LSP_APPR_LMTS_ID = A.KEY_VALUE_1 AND A.SOURCE_ID = L.SOURCE_ID
	ORDER BY A.SOURCE_ID);

CALL BR_LOG_PROC_TIME('BR_RUN_RPT_BVLNCMBR', 'BVLNCMBR', 3);
COMMIT;

-----------------------------
-- Security
-----------------------------
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-SEC', 0, 'Branch Rationalization Audit Report', 'BVLNCMBR', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-SEC', 0, 'Mapping file name: BVLNCMBR', 'BVLNCMBR', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-SEC', 0, '"Branch Rationalization for Security (ARBS, SEMA, CLIMS)"', 'BVLNCMBR', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-SEC', 0, 'Report Date: ' || char(current date)  || chr(13) || chr(10), 'BVLNCMBR', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-SEC', 0, 'Old Branch No.,New Branch No.,Security ID,Source System,Security Status', 'BVLNCMBR', CURRENT_TIMESTAMP);

INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) 
  (SELECT 'BRM-SEC', A.KEY_VALUE_1, '''' || A.OLD_VALUE || ',''' || A.NEW_VALUE || ',''' || S.SCI_SECURITY_DTL_ID || ',' || A.SOURCE_ID || ',' || S.STATUS, 'BVLNCMBR', CURRENT_TIMESTAMP
		FROM BR_AUDIT_LOG A, CMS_SECURITY S
    WHERE A.TABLE_NAME = 'CMS_SECURITY' AND A.COLUMN_NAME = 'SECURITY_ORGANISATION' AND A.SOURCE_ID IN ('ARBS','SEMA','CLMS')
			AND S.CMS_COLLATERAL_ID = A.KEY_VALUE_1 AND A.SOURCE_ID = S.SOURCE_ID ORDER BY A.SOURCE_ID);

CALL BR_LOG_PROC_TIME('BR_RUN_RPT_BVLNCMBR', 'BVLNCMBR', 4);
COMMIT;

-----------------------------
-- Pledgor
-----------------------------
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-PLDGR', 0, 'Branch Rationalization Audit Report', 'BVLNCMBR', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-PLDGR', 0, 'Mapping file name: BVLNCMBR', 'BVLNCMBR', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-PLDGR', 0, '"Branch Rationalization for Pledgor (ARBS, SEMA, CLIMS)"', 'BVLNCMBR', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-PLDGR', 0, 'Report Date: ' || char(current date)  || chr(13) || chr(10), 'BVLNCMBR', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-PLDGR', 0, 'Old Branch No.,New Branch No.,CIF Number,Name,Source System,Pledgor Status', 'BVLNCMBR', CURRENT_TIMESTAMP);

INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) 
  (SELECT DISTINCT 'BRM-PLDGR', A.KEY_VALUE_1, '''' || A.OLD_VALUE || ',''' || A.NEW_VALUE || ',''' || P.PLG_LE_ID || ',' || P.PLG_LEGAL_NAME || ',' || A.SOURCE_ID || ',' || (CASE M.UPDATE_STATUS_IND WHEN 'D' THEN 'DELETED' ELSE 'ACTIVE' END), 'BVLNCMBR', CURRENT_TIMESTAMP
		FROM BR_AUDIT_LOG A, SCI_PLEDGOR_DTL P, SCI_SEC_PLDGR_MAP M
    WHERE A.TABLE_NAME = 'SCI_PLEDGOR_DTL' AND A.COLUMN_NAME = 'CMS_ORIG_ORGANISATION' AND A.SOURCE_ID IN ('ARBS','SEMA','CLMS')
			AND A.KEY_VALUE_1 = M.CMS_COLLATERAL_ID AND M.CMS_PLEDGOR_DTL_ID = P.CMS_PLEDGOR_DTL_ID AND A.SOURCE_ID = P.SOURCE_ID);

CALL BR_LOG_PROC_TIME('BR_RUN_RPT_BVLNCMBR', 'BVLNCMBR', 5);
COMMIT;

-----------------------------
-- User (Team)
-----------------------------
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-USR', 0, 'Branch Rationalization Audit Report', 'BVLNCMBR', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-USR', 0, 'Mapping file name: BVLNCMBR', 'BVLNCMBR', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-USR', 0, 'Branch Rationalization for User(Team)', 'BVLNCMBR', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-USR', 0, 'Report Date: ' || char(current date)  || chr(13) || chr(10), 'BVLNCMBR', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('BRM-USR', 0, 'Record ID,Branch No.,Team Name', 'BVLNCMBR', CURRENT_TIMESTAMP);

INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) 
  (SELECT DISTINCT 'BRM-USR', A.KEY_VALUE_1, '''' || CHAR(A.KEY_VALUE_1) || ',''' || A.OLD_VALUE || ',' || A.KEY_VALUE_2, 'BVLNCMBR', CURRENT_TIMESTAMP FROM BR_AUDIT_LOG A, SCI_PLEDGOR_DTL P, SCI_SEC_PLDGR_MAP M
    WHERE A.TABLE_NAME = 'CMS_TEAM_ORGANISATION_CODE' AND A.COLUMN_NAME = 'CODE_ID');

CALL BR_LOG_PROC_TIME('BR_RUN_RPT_BVLNCMBR', 'BVLNCMBR', 0);
END@

-- AA
DROP PROCEDURE BR_RUN_RPT_BVLNCMAA@

CREATE PROCEDURE BR_RUN_RPT_BVLNCMAA
LANGUAGE SQL

BEGIN
DECLARE T_OAA VARCHAR(50);
DECLARE T_NAA VARCHAR(50);
DECLARE T_OBR VARCHAR(50);
DECLARE T_NBR VARCHAR(50);
DECLARE PREV_KEY BIGINT;

CALL BR_LOG_PROC_TIME('BR_RUN_RPT_BVLNCMAA', 'BVLNCMAA', 1);

INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('AA', 0, 'Branch Rationalization Audit Report', 'BVLNCMAA', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('AA', 0, 'Mapping file name: BVLNCMAA', 'BVLNCMAA', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('AA', 0, 'Branch Rationalization for AA (ARBS)', 'BVLNCMAA', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('AA', 0, 'Report Date: ' || char(current date)  || chr(13) || chr(10), 'BVLNCMAA', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('AA', 0, 'Old Branch No.,New Branch No.,Old AA No.,New AA No.,Name,CIF No.,Approval Date,AA Status', 'BVLNCMAA', CURRENT_TIMESTAMP);

FOR REC AS

  SELECT DISTINCT A.KEY_VALUE_1 C1, A.COLUMN_NAME C2, A.OLD_VALUE V1, A.NEW_VALUE V2, C.LMP_LONG_NAME V3, AA.LLP_LE_ID V4, TS_FMT(AA.LLP_BCA_REF_APPR_DATE,'dd/mm/yyyy hh:mi:ss') V5,
  (CASE AA.UPDATE_STATUS_IND WHEN 'D' THEN 'DELETED' ELSE 'ACTIVE' END) V6
		FROM BR_AUDIT_LOG A, SCI_LSP_LMT_PROFILE AA, SCI_LE_MAIN_PROFILE C
		WHERE A.TABLE_NAME = 'SCI_LSP_LMT_PROFILE' AND A.COLUMN_NAME  IN ('LLP_BCA_REF_NUM','CMS_ORIG_ORGANISATION') AND A.KEY_VALUE_1 = AA.CMS_LSP_LMT_PROFILE_ID
			AND AA.LLP_LE_ID = C.LMP_LE_ID AND AA.SOURCE_ID = 'ARBS' AND C.SOURCE_ID = 'ARBS' AND A.SOURCE_ID = 'ARBS' ORDER BY A.KEY_VALUE_1

DO
	
	IF REC.C2 = 'LLP_BCA_REF_NUM' THEN
		SET T_OAA = REC.V1;
		SET T_NAA = REC.V2;
	ELSEIF REC.C2 = 'CMS_ORIG_ORGANISATION' THEN
		SET T_OBR = REC.V1;
		SET T_NBR = REC.V2;
	END IF;

	IF PREV_KEY IS NULL THEN
		SET PREV_KEY = REC.C1;
	ELSEIF PREV_KEY = REC.C1 THEN
		INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) 
  	VALUES ('AA', REC.C1, '''' || T_OBR || ',''' || T_NBR || ',''' || T_OAA || ',''' || T_NAA || ',' || REC.V3 || ',''' || REC.V4 || ',' || REC.V5 || ',' || REC.V6, 'BVLNCMAA', CURRENT_TIMESTAMP);
		
		SET PREV_KEY = NULL;
		SET T_OAA = NULL;
		SET T_NAA = NULL;
		SET T_OBR = NULL;
		SET T_NBR = NULL;
	END IF;
	
END FOR;

CALL BR_LOG_PROC_TIME('BR_RUN_RPT_BVLNCMAA', 'BVLNCMAA', 0);
END@
		
-- Loan Account		
DROP PROCEDURE BR_RUN_RPT_BVLNCMAC@

CREATE PROCEDURE BR_RUN_RPT_BVLNCMAC
LANGUAGE SQL

BEGIN
DECLARE T_OAC VARCHAR(50);
DECLARE T_NAC VARCHAR(50);
DECLARE T_OBR VARCHAR(50);
DECLARE T_NBR VARCHAR(50);
DECLARE PREV_KEY BIGINT;

CALL BR_LOG_PROC_TIME('BR_RUN_RPT_BVLNCMAC', 'BVLNCMAC', 1);

INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('LOAN-ACC', 0, 'Branch Rationalization Audit Report', 'BVLNCMAC', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('LOAN-ACC', 0, 'Mapping file name: BVLNCMAC', 'BVLNCMAC', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('LOAN-ACC', 0, 'Branch Rationalization for Loan Account (ARBS)', 'BVLNCMAC', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('LOAN-ACC', 0, 'Report Date: ' || char(current date)  || chr(13) || chr(10), 'BVLNCMAC', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('LOAN-ACC', 0, 'Old Branch No.,New Branch No.,Old Account No.,New Account No.,Account Type,Name,Outstanding Balance,Account Status', 'BVLNCMAC', CURRENT_TIMESTAMP);

FOR REC AS

  SELECT DISTINCT A.KEY_VALUE_1 C1, A.COLUMN_NAME C2, A.OLD_VALUE V1, A.NEW_VALUE V2, X.LSX_EXT_SYS_ACCT_TYPE V3, P.LMP_LONG_NAME V4, CHAR(L.CMS_OUTSTANDING_AMT) V5,
  M.CMS_STATUS V6
		FROM BR_AUDIT_LOG A, SCI_LSP_SYS_XREF X, SCI_LE_MAIN_PROFILE P, SCI_LSP_LMTS_XREF_MAP M, SCI_LSP_APPR_LMTS L
    WHERE A.TABLE_NAME = 'SCI_LSP_SYS_XREF' AND A.COLUMN_NAME IN ('LSX_EXT_SYS_ACCT_NUM', 'LSX_BKG_LOCTN_ORG') AND A.KEY_VALUE_2 = 'L'
			AND A.KEY_VALUE_1 = X.CMS_LSP_SYS_XREF_ID AND X.LSX_LE_ID = P.LMP_LE_ID AND P.SOURCE_ID = 'ARBS' AND A.KEY_VALUE_2 = X.LSX_EXT_SYS_ACCT_TYPE
			AND X.CMS_LSP_SYS_XREF_ID = M.CMS_LSP_SYS_XREF_ID AND M.CMS_LSP_APPR_LMTS_ID = L.CMS_LSP_APPR_LMTS_ID AND L.SOURCE_ID = 'ARBS' ORDER BY A.KEY_VALUE_1

DO
	
	IF REC.C2 = 'LSX_EXT_SYS_ACCT_NUM' THEN
		SET T_OAC = REC.V1;
		SET T_NAC = REC.V2;
	ELSEIF REC.C2 = 'LSX_BKG_LOCTN_ORG' THEN
		SET T_OBR = REC.V1;
		SET T_NBR = REC.V2;
	END IF;

	IF PREV_KEY IS NULL THEN
		SET PREV_KEY = REC.C1;
	ELSEIF PREV_KEY = REC.C1 THEN
		INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) 
  	VALUES ('LOAN-ACC', REC.C1, '''' || T_OBR || ',''' || T_NBR || ',''' || T_OAC || ',''' || T_NAC || ',' || REC.V3 || ',' || REC.V4 || ',' || REC.V5 || ',' || REC.V6, 'BVLNCMAA', CURRENT_TIMESTAMP);
		
		SET PREV_KEY = NULL;
		SET T_OAC = NULL;
		SET T_NAC = NULL;
		SET T_OBR = NULL;
		SET T_NBR = NULL;
	END IF;
	
END FOR;

CALL BR_LOG_PROC_TIME('BR_RUN_RPT_BVLNCMAC', 'BVLNCMAC', 0);
END@		
		
-- Current/Saving Account		
DROP PROCEDURE BR_RUN_RPT_BVDDCLIMS@

CREATE PROCEDURE BR_RUN_RPT_BVDDCLIMS
LANGUAGE SQL

BEGIN
DECLARE T_OAC VARCHAR(50);
DECLARE T_NAC VARCHAR(50);
DECLARE T_OBR VARCHAR(50);
DECLARE T_NBR VARCHAR(50);
DECLARE PREV_KEY BIGINT;

CALL BR_LOG_PROC_TIME('BR_RUN_RPT_BVDDCLIMS', 'BVDDCLIMS', 1);

INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('CASA-ACC', 0, 'Branch Rationalization Audit Report', 'BVDDCLIMS', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('CASA-ACC', 0, 'Mapping file name: BVDDCLIMS', 'BVDDCLIMS', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('CASA-ACC', 0, 'Branch Rationalization for Current/Saving Account (ARBS)', 'BVDDCLIMS', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('CASA-ACC', 0, 'Report Date: ' || char(current date)  || chr(13) || chr(10), 'BVDDCLIMS', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('CASA-ACC', 0, 'Old Branch No.,New Branch No.,Old Account No.,New Account No.,Account Type,Name,Outstanding Balance,Account Status', 'BVDDCLIMS', CURRENT_TIMESTAMP);

FOR REC AS

  SELECT DISTINCT A.KEY_VALUE_1 C1, A.COLUMN_NAME C2, A.OLD_VALUE V1, A.NEW_VALUE V2, X.LSX_EXT_SYS_ACCT_TYPE V3, P.LMP_LONG_NAME V4, CHAR(L.CMS_OUTSTANDING_AMT) V5,
  M.CMS_STATUS V6
		FROM BR_AUDIT_LOG A, SCI_LSP_SYS_XREF X, SCI_LE_MAIN_PROFILE P, SCI_LSP_LMTS_XREF_MAP M, SCI_LSP_APPR_LMTS L
    WHERE A.TABLE_NAME = 'SCI_LSP_SYS_XREF' AND A.COLUMN_NAME IN ('LSX_EXT_SYS_ACCT_NUM', 'LSX_BKG_LOCTN_ORG') AND A.KEY_VALUE_2 IN ('D', 'S')
			AND A.KEY_VALUE_1 = X.CMS_LSP_SYS_XREF_ID AND X.LSX_LE_ID = P.LMP_LE_ID AND P.SOURCE_ID = 'ARBS' AND A.KEY_VALUE_2 = X.LSX_EXT_SYS_ACCT_TYPE
			AND X.CMS_LSP_SYS_XREF_ID = M.CMS_LSP_SYS_XREF_ID AND M.CMS_LSP_APPR_LMTS_ID = L.CMS_LSP_APPR_LMTS_ID AND L.SOURCE_ID = 'ARBS' ORDER BY A.KEY_VALUE_1

DO
	
	IF REC.C2 = 'LSX_EXT_SYS_ACCT_NUM' THEN
		SET T_OAC = REC.V1;
		SET T_NAC = REC.V2;
	ELSEIF REC.C2 = 'LSX_BKG_LOCTN_ORG' THEN
		SET T_OBR = REC.V1;
		SET T_NBR = REC.V2;
	END IF;

	IF PREV_KEY IS NULL THEN
		SET PREV_KEY = REC.C1;
	ELSEIF PREV_KEY = REC.C1 THEN
		INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) 
  	VALUES ('CASA-ACC', REC.C1, '''' || T_OBR || ',''' || T_NBR || ',''' || T_OAC || ',''' || T_NAC || ',' || REC.V3 || ',' || REC.V4 || ',' || REC.V5 || ',' || REC.V6, 'BVDDCLIMS', CURRENT_TIMESTAMP);
		
		SET PREV_KEY = NULL;
		SET T_OAC = NULL;
		SET T_NAC = NULL;
		SET T_OBR = NULL;
		SET T_NBR = NULL;
	END IF;
	
END FOR;

CALL BR_LOG_PROC_TIME('BR_RUN_RPT_BVDDCLIMS', 'BVDDCLIMS', 0);
END@

-- Fixed Deposit Account		
DROP PROCEDURE BR_RUN_RPT_BVCDCLIMS@

CREATE PROCEDURE BR_RUN_RPT_BVCDCLIMS
LANGUAGE SQL

BEGIN
DECLARE T_OAC VARCHAR(50);
DECLARE T_NAC VARCHAR(50);
DECLARE T_OFDR VARCHAR(50);
DECLARE T_NFDR VARCHAR(50);
DECLARE PREV_KEY BIGINT;

CALL BR_LOG_PROC_TIME('BR_RUN_RPT_BVCDCLIMS', 'BVCDCLIMS', 1);

INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('FD-ACC', 0, 'Branch Rationalization Audit Report', 'BVCDCLIMS', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('FD-ACC', 0, 'Mapping file name: BVCDCLIMS', 'BVCDCLIMS', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('FD-ACC', 0, '"Branch Rationalization for Fixed Deposit Account (ARBS, SEMA)"', 'BVCDCLIMS', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('FD-ACC', 0, 'Report Date: ' || char(current date)  || chr(13) || chr(10), 'BVCDCLIMS', CURRENT_TIMESTAMP);
INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) VALUES ('FD-ACC', 0, 'Issue Date,Old Group Account No.,New Group Account No.,Old FDR No.,New FDR No.,Name,Fixed Deposit Amount,Source System,Account Status', 'BVCDCLIMS', CURRENT_TIMESTAMP);

FOR REC AS

  SELECT DISTINCT D.ISSUE_DATE ISSUE_DATE, A.KEY_VALUE_1 C1, A.COLUMN_NAME C2, A.OLD_VALUE V1, A.NEW_VALUE V2, C.LMP_LONG_NAME V3, CHAR(D.DEPOSIT_AMOUNT) V4, A.SOURCE_ID SRC_ID, 
  (CASE M.UPDATE_STATUS_IND WHEN 'D' THEN 'DELETED' ELSE 'ACTIVE' END) V6
		FROM BR_AUDIT_LOG A, CMS_CASH_DEPOSIT D, CMS_LIMIT_SECURITY_MAP M, SCI_LE_MAIN_PROFILE C
		WHERE A.TABLE_NAME = 'CMS_CASH_DEPOSIT' AND A.COLUMN_NAME IN ('DEPOSIT_RECEIPT_NUMBER', 'DEPOSIT_REFERENCE_NUMBER')
			AND A.KEY_VALUE_1 = D.CMS_COLLATERAL_ID AND D.CMS_COLLATERAL_ID = M.CMS_COLLATERAL_ID AND M.SCI_LAS_LE_ID = C.LMP_LE_ID
			ORDER BY ISSUE_DATE, A.KEY_VALUE_1

DO
	
	IF REC.C2 = 'DEPOSIT_REFERENCE_NUMBER' THEN
		SET T_OAC = REC.V1;
		SET T_NAC = REC.V2;
	ELSEIF REC.C2 = 'DEPOSIT_RECEIPT_NUMBER' THEN
		SET T_OFDR = REC.V1;
		SET T_NFDR = REC.V2;
	END IF;

	IF PREV_KEY IS NULL AND REC.SRC_ID = 'ARBS' THEN
		SET PREV_KEY = REC.C1;
	ELSEIF PREV_KEY = REC.C1 OR REC.SRC_ID <> 'ARBS' THEN
		INSERT INTO BR_AUDIT_REPORT (REPORT_TYPE, REC_KEY, TEXT, FILE_NAME, TIME_STAMP) 
  	VALUES ('FD-ACC', REC.C1, '''' || CHAR(REC.ISSUE_DATE) || ',''' || T_OAC || ',''' || T_NAC || ',''' || T_OFDR || ',''' || T_NFDR || ',' || REC.V3 || ',' || REC.V4 || ',' || REC.SRC_ID || ',' || REC.V6, 'BVCDCLIMS', CURRENT_TIMESTAMP);
		
		SET PREV_KEY = NULL;
		SET T_OAC = NULL;
		SET T_NAC = NULL;
		SET T_OFDR = NULL;
		SET T_NFDR = NULL;
	END IF;
	
END FOR;

CALL BR_LOG_PROC_TIME('BR_RUN_RPT_BVCDCLIMS', 'BVCDCLIMS', 0);
END@

-- Run All
DROP PROCEDURE BR_RUN_RPT_ALL@

CREATE PROCEDURE BR_RUN_RPT_ALL
LANGUAGE SQL

BEGIN

CALL UTIL_TRUNCATE_TABLE('BR_AUDIT_REPORT');

CALL BR_RUN_RPT_BVLNCMBR;

CALL BR_RUN_RPT_BVLNCMAA;

CALL BR_RUN_RPT_BVLNCMAC;

CALL BR_RUN_RPT_BVDDCLIMS;

CALL BR_RUN_RPT_BVCDCLIMS;

END@
