--DROP TABLE SI_TEMP_MIMB_CU002;
--DROP TABLE SI_TEMP_MIMB_CA003;
--DROP TABLE SI_TEMP_MIMB_CO003;
--DROP TABLE SI_TEMP_MIMB_CO004;
--DROP TABLE SI_TEMP_MIMB_PF002;

CREATE TABLE SI_TEMP_MIMB_CU002 (
    TEMP_ID  BIGINT NOT NULL,
    RECORD_TYPE VARCHAR(1) DEFAULT 'D',
    AA_NO VARCHAR(6),
    CIF_ID VARCHAR(6),
    LEGAL_NAME VARCHAR(60),
    CUSTOMER_NAME VARCHAR(60),
    ID_TYPE_CAT VARCHAR(10) DEFAULT 'ID_TYPE',
    ID_TYPE_CODE VARCHAR(2),
    ID_NO VARCHAR(20),
    REL_START_DATE_BANK TIMESTAMP,
    CUST_TYPE_CAT VARCHAR(10) DEFAULT '8',
    CUST_TYPE_CODE VARCHAR(1),
    CUST_TYPE_DESC VARCHAR(40),
    CUST_LEGAL_CONST_CAT VARCHAR(10) DEFAULT '56',
    CUST_LEGAL_CONST_CODE VARCHAR(2),
    CUST_LEGAL_CONST_DESC VARCHAR(40),
    ADDRESS_TYPE_CAT VARCHAR(10) DEFAULT '4',
    ADDRESS_TYPE_CODE VARCHAR(1),
    ADDRESS_1 VARCHAR(40),
    ADDRESS_2 VARCHAR(30),
    ADDRESS_3 VARCHAR(30),
    ADDRESS_4 VARCHAR(30),
    COUNTRY VARCHAR(2),
	    cms_le_main_profile_id BIGINT,
	    cms_le_sub_profile_id BIGINT,
    IS_VALID VARCHAR(1) DEFAULT 'Y', 
    DATE_CREATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP )
in CMS_BATCH index in CMS_BATCH_INDEX;

CREATE TABLE SI_TEMP_MIMB_CA003 (
    TEMP_ID  BIGINT NOT NULL,
    RECORD_TYPE VARCHAR(1) DEFAULT 'D',
    AA_NO VARCHAR(6),
    SOURCE_LMT_ID VARCHAR(6),
    LMT_BOOK_LOC_CAT VARCHAR(10) DEFAULT '40',
    LMT_BOOK_LOC_CODE VARCHAR(5),
    LMT_BOOK_LOC_DESC VARCHAR(60),
    PROD_TYPE_CAT VARCHAR(10) DEFAULT '27',
    PROD_TYPE_CODE VARCHAR(3),
    PROD_TYPE_DESC VARCHAR(30),
    APPROVED_LMT DECIMAL(12,2),
    DRAWING_LMT DECIMAL(12,2),
    OUTSTD_BALANCE_SIGN VARCHAR(1),
    OUTSTD_BALANCE DECIMAL(12,2),
    LMT_STATUS VARCHAR(7),
		cms_customer_id BIGINT,
		cms_act_aa_id BIGINT,
		cms_stg_aa_id BIGINT,
        cms_act_lmt_profile_id BIGINT,
        cms_act_lmt_id BIGINT,
        cms_stg_lmt_id BIGINT,    
    IS_VALID VARCHAR(1) DEFAULT 'Y' ,
    DATE_CREATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP )
in CMS_BATCH index in CMS_BATCH_INDEX;

CREATE TABLE SI_TEMP_MIMB_CO003 (
    TEMP_ID  BIGINT NOT NULL,
    RECORD_TYPE VARCHAR(1) DEFAULT 'D',
    SOURCE_SEC_ID VARCHAR(13),
    SEC_TYPE VARCHAR(2),
    CMS_SECURITY_TYPE_ID    VARCHAR(5),
    CMS_SECURITY_SUBTYPE_ID    VARCHAR(10),    
    ORIG_SEC_CURRENCY VARCHAR(3),
    CMS_SEC_CURRENCY VARCHAR(3),
    SEC_LOCATION VARCHAR(2),
    BRANCH_NAME_CAT VARCHAR(10) DEFAULT '40',
    BRANCH_NAME_CODE VARCHAR(5),
    BRANCH_NAME_DESC VARCHAR(60),
    SEC_CUSTODIAN_TYPE VARCHAR(1),
    SEC_CUSTODIAN_VALUE VARCHAR(5),
    SEC_MATURITY_DATE TIMESTAMP,
    SEC_PERFECTION_DATE TIMESTAMP,
    LEGAL_ENFORCE VARCHAR(1),
    LEGAL_ENFORCE_DATE TIMESTAMP,
    NATURE_CHARGE VARCHAR(8),
    AMOUNT_CHARGE DECIMAL(12,2),
    DATE_LEGAL_CHARGED TIMESTAMP,
    CHARGE_TYPE VARCHAR(1),
    EQUITY_TYPE VARCHAR(1),
    CDS_NUMBER VARCHAR(15),
    NOMINEE_NAME VARCHAR(3),
    RECOG_EXCHANGE VARCHAR(1),
    REG_OWNER VARCHAR(60),
    NUMBER_UNITS DECIMAL(11,0),
    UNIT_PRICE DECIMAL(10,6),
    STOCK_EXCHANGE VARCHAR(3),
    COUNTRY_STOCK_EXCHANGE VARCHAR(2),
    EXCHANGE_CTRL_APPROVAL VARCHAR(2),
    STOCK_CODE VARCHAR(7),
    BASEL_COMPLT_UNIT_TRUST VARCHAR(2),
	SIGN_OF_UNITS VARCHAR(1),
    SEC_PLEDGOR_ID VARCHAR(6),
    SEC_PLEDGOR_NAME VARCHAR(60),
    SEC_PLEDGOR_REL_CAT VARCHAR(16) DEFAULT 'RELATIONSHIP',
    SEC_PLEDGOR_REL_CODE VARCHAR(5),
    SEC_PLEDGOR_REL_NUM VARCHAR(40),
		cms_act_col_id			BIGINT,
		cms_stg_col_id			BIGINT,
        cms_collateral_id       BIGINT,
        cms_stg_collateral_id   BIGINT,    
        cms_lsp_appr_lmts_id    BIGINT,
        cms_limit_profile_id    BIGINT,
        cms_pledgor_dtl_id      BIGINT,  
		cms_stg_pledgor_dtl_id	BIGINT,
		cms_act_chrg_dtl_id 	BIGINT,
		cms_stg_chrg_dtl_id 	BIGINT,  
		cms_item_id 			BIGINT,
		source_security_sub_type VARCHAR(3) DEFAULT 'C10',
    AA_NO VARCHAR(6),
    SOURCE_LMT_ID VARCHAR(6),
    IS_VALID VARCHAR(1) DEFAULT 'Y' , 
    DATE_CREATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP )
in CMS_BATCH index in CMS_BATCH_INDEX;

CREATE TABLE SI_TEMP_MIMB_CO004 (
    TEMP_ID  BIGINT NOT NULL,
    RECORD_TYPE VARCHAR(1) DEFAULT 'D',
    SOURCE_SEC_ID VARCHAR(8),
    SEC_TYPE VARCHAR(2),
    SEC_SUB_TYPE VARCHAR(5),
    ORIG_SEC_CURRENCY VARCHAR(3),
    CMS_SEC_CURRENCY VARCHAR(3) DEFAULT 'MYR',
    SEC_LOCATION VARCHAR(2) DEFAULT 'MY',
    BRANCH_NAME_CAT VARCHAR(10) DEFAULT '40',
    BRANCH_NAME_CODE VARCHAR(5),
    BRANCH_NAME_DESC VARCHAR(60),
    SEC_CUSTODIAN_TYPE VARCHAR(1) DEFAULT 'I',
    SEC_CUSTODIAN_VALUE VARCHAR(5),
    SEC_PERFECTION_DATE TIMESTAMP,
    LEGAL_ENFORCE VARCHAR(1) DEFAULT 'Y',
    LEGAL_ENFORCE_DATE TIMESTAMP,
    EXCHANGE_CTRL_APPROVAL VARCHAR(2) DEFAULT 'NA',
    DEPOSIT_REF_NUMBER VARCHAR(8),
    DEPOSIT_CURRENCY VARCHAR(3) DEFAULT 'MYR',
    DEPOSIT_AMOUNT DECIMAL(12,2),
    SEC_PLEDGOR_ID VARCHAR(8),
    SEC_PLEDGOR_NAME VARCHAR(60),
    SEC_PLEDGOR_REL_CAT VARCHAR(16) DEFAULT 'RELATIONSHIP',
    SEC_PLEDGOR_REL_CODE VARCHAR(5),
    SEC_PLEDGOR_REL_NUM VARCHAR(40),
		cms_act_col_id			BIGINT,
		cms_stg_col_id			BIGINT,	
        cms_collateral_id       BIGINT,
        cms_stg_collateral_id   BIGINT,    
        cms_lsp_appr_lmts_id    BIGINT,
        cms_limit_profile_id    BIGINT,
        cms_pledgor_dtl_id      BIGINT,  
		cms_stg_pledgor_dtl_id	BIGINT,		
		source_security_sub_type VARCHAR(3) DEFAULT 'C10',		
    AA_NO VARCHAR(6),
    SOURCE_LMT_ID VARCHAR(6),
    IS_VALID VARCHAR(1) DEFAULT 'Y'    , 
    DATE_CREATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP )
in CMS_BATCH index in CMS_BATCH_INDEX;

CREATE TABLE SI_TEMP_MIMB_PF002 (
    TEMP_ID  BIGINT NOT NULL,
    RECORD_TYPE VARCHAR(1) DEFAULT 'D',
    STOCK_CODE VARCHAR(10),
    COUNTER_NAME VARCHAR(40),
    EXCHANGE_CODE VARCHAR(3),
    UNIT_PRICE DECIMAL(10,6),
    UNIT_PRICE_CURR VARCHAR(3),
    ISIN_CODE  VARCHAR(14),
    STOCK_EXCHG_TRD_BRD_CAT VARCHAR(10) DEFAULT 'BOARD_TYPE',
    STOCK_EXCHG_TRD_BRD_CODE VARCHAR(1),
    STOCK_EXCHG_TRD_BRD_DESC VARCHAR(40),
    STOCK_TYPES VARCHAR(3),
    LISTED_SHARES_QTY DECIMAL(11,0),
    PAR_VALUE DECIMAL(20,2),
    PAID_UP_CAPITAL DECIMAL(20,2),
    EXPIRY_DATE TIMESTAMP DEFAULT '2999-12-31 12:00:00.00000',
    SHARE_STATUS VARCHAR(1),
    STOCK_EXCHG_SUSP_IND VARCHAR(1),
	LAUNCH_DATE TIMESTAMP,
        FEED_GROUP_ID    BIGINT,
        STAGE_FEED_GROUP_ID    BIGINT,    
    IS_VALID VARCHAR(1) DEFAULT 'Y'   ,
    DATE_CREATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP   )
in CMS_BATCH index in CMS_BATCH_INDEX;


CREATE SEQUENCE SI_TEMP_MIMB_CU002_SEQ AS INTEGER
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999
    MINVALUE 1
    CYCLE
    NO CACHE
    NO ORDER;
    
CREATE SEQUENCE SI_TEMP_MIMB_PF002_SEQ AS INTEGER
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999
    MINVALUE 1
    CYCLE
    NO CACHE
    NO ORDER;
    
CREATE SEQUENCE SI_TEMP_MIMB_CA003_SEQ AS INTEGER
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999
    MINVALUE 1
    CYCLE
    NO CACHE
    NO ORDER;
    
CREATE SEQUENCE SI_TEMP_MIMB_CO003_SEQ AS INTEGER
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999
    MINVALUE 1
    CYCLE
    NO CACHE
    NO ORDER;
    
CREATE SEQUENCE SI_TEMP_MIMB_CO004_SEQ AS INTEGER
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999
    MINVALUE 1
    CYCLE
    NO CACHE
    NO ORDER;
	
-- CA003 - Limit Profile
CREATE INDEX "SI_MIMB_CA003_I1" ON "SCI_LE_SUB_PROFILE" 
("CMS_LE_MAIN_PROFILE_ID" ASC, "LSP_LE_ID" ASC, "CMS_LE_SUB_PROFILE_ID" ASC) 
ALLOW REVERSE SCANS; 	

CREATE INDEX "SI_MIMB_CA003_I2" ON "TRANSACTION" 
("REFERENCE_ID" ASC, "TRANSACTION_TYPE" ASC, "STAGING_REFERENCE_ID" ASC) 
ALLOW REVERSE SCANS; 

CREATE INDEX "SI_MIMB_CA003_I3" ON "SI_TEMP_MIMB_CA003" 
("CMS_STG_LMT_ID" ASC, "IS_VALID" ASC, "CMS_ACT_LMT_PROFILE_ID" ASC, "LMT_STATUS" ASC, "OUTSTD_BALANCE" ASC, 
"OUTSTD_BALANCE_SIGN" ASC, "DRAWING_LMT" ASC, "APPROVED_LMT" ASC, "PROD_TYPE_CODE" ASC, "PROD_TYPE_CAT" ASC, 
"LMT_BOOK_LOC_CODE" ASC, "SOURCE_LMT_ID" ASC, "AA_NO" ASC) 
ALLOW REVERSE SCANS; 


-- CO003 – Marketable Security
--DROP INDEX "SI_MIMB_CO003_I1";
CREATE INDEX "SI_MIMB_CO003_I1" ON "CMS_PORTFOLIO_ITEM" 
("SOURCE_ID" ASC, "STATUS" ASC, "CMS_COLLATERAL_ID" ASC) 
ALLOW REVERSE SCANS; 

--DROP INDEX "SI_MIMB_CO003_I2";
CREATE INDEX "SI_MIMB_CO003_I2" ON "SI_TEMP_MIMB_CO003" 
("IS_VALID" ASC, "SOURCE_SEC_ID" DESC) 
ALLOW REVERSE SCANS; 

--DROP INDEX "SI_MIMB_CO003_I3";
CREATE INDEX "SI_MIMB_CO003_I3" ON "SCI_LSP_APPR_LMTS" 
("LMT_ID" ASC, "SOURCE_ID" ASC, "CMS_LIMIT_PROFILE_ID" ASC, "CMS_LSP_APPR_LMTS_ID" ASC) 
ALLOW REVERSE SCANS; 

--DROP INDEX "SI_MIMB_CO003_I4";
CREATE INDEX "SI_MIMB_CO003_I4" ON "SI_TEMP_MIMB_CO003" 
("IS_VALID" ASC, "CMS_LIMIT_PROFILE_ID" DESC) 
ALLOW REVERSE SCANS; 

--DROP INDEX "SI_MIMB_CO003_I5";
CREATE UNIQUE INDEX "SI_MIMB_CO003_I5" ON "SCI_LSP_APPR_LMTS" 
("CMS_LSP_APPR_LMTS_ID" ASC) 
INCLUDE ( "SOURCE_ID", "CMS_LIMIT_STATUS") 
ALLOW REVERSE SCANS; 

--DROP INDEX "SI_MIMB_CO003_I6";
CREATE UNIQUE INDEX "SI_MIMB_CO003_I6" ON "CMS_SECURITY" 
("CMS_COLLATERAL_ID" ASC) 
INCLUDE ( "SOURCE_ID", "SCI_SECURITY_TYPE_VALUE", "STATUS") 
ALLOW REVERSE SCANS; 

--DROP INDEX "SI_MIMB_CO003_I7";
CREATE INDEX "SI_MIMB_CO003_I7" ON "CMS_LIMIT_SECURITY_MAP" 
("UPDATE_STATUS_IND" ASC, "DELETION_DATE" ASC, "CMS_COLLATERAL_ID" ASC, "CMS_LSP_APPR_LMTS_ID" ASC, "SOURCE_ID" ASC) 
ALLOW REVERSE SCANS; 

--DROP INDEX "SI_MIMB_CO003_I8";
CREATE UNIQUE INDEX "SI_MIMB_CO003_I8" ON "CMS_STAGE_SECURITY" 
("CMS_COLLATERAL_ID" ASC) 
INCLUDE ( "SOURCE_ID", "SCI_SECURITY_TYPE_VALUE", "STATUS") 
ALLOW REVERSE SCANS; 

--DROP INDEX "SI_MIMB_CO003_I9";
CREATE INDEX "SI_MIMB_CO003_I9" ON "CMS_STAGE_LIMIT_SECURITY_MAP" 
("SOURCE_ID" ASC, "CMS_LSP_APPR_LMTS_ID" DESC) 
ALLOW REVERSE SCANS; 

CREATE INDEX "SI_MIMB_CO003_I10" ON "SI_TEMP_MIMB_CO003" 
("IS_VALID" ASC, "BASEL_COMPLT_UNIT_TRUST" ASC, "STOCK_CODE" ASC, "EXCHANGE_CTRL_APPROVAL" ASC, "COUNTRY_STOCK_EXCHANGE" ASC, "STOCK_EXCHANGE" ASC, 
"UNIT_PRICE" ASC, "NUMBER_UNITS" ASC, "REG_OWNER" ASC, "RECOG_EXCHANGE" ASC, "NOMINEE_NAME" ASC, "CDS_NUMBER" ASC, "EQUITY_TYPE" ASC, "SOURCE_SEC_ID" ASC) 
ALLOW REVERSE SCANS; 

--DROP INDEX "SI_MIMB_CO003_I11";
CREATE INDEX "SI_MIMB_CO003_I11" ON "SI_TEMP_MIMB_CO003" 
("CMS_STG_COLLATERAL_ID" ASC) 
ALLOW REVERSE SCANS;

-- CREATE INDEX "SI_MIMB_CO003_I12" ON "TRANSACTION" 
-- ("TRANSACTION_TYPE" ASC, 
-- "STAGING_REFERENCE_ID" DESC) 
-- ALLOW REVERSE SCANS; 

--DROP INDEX "SI_MIMB_CO003_I13";
CREATE INDEX "SI_MIMB_CO003_I13" ON "SI_TEMP_MIMB_CO003" 
("IS_VALID" ASC, "CMS_STG_PLEDGOR_DTL_ID" ASC, "CMS_STG_COLLATERAL_ID" ASC, "SEC_PLEDGOR_REL_CODE" ASC, "SEC_PLEDGOR_REL_CAT" ASC, "SOURCE_SEC_ID" ASC) 
ALLOW REVERSE SCANS; 

CREATE INDEX "SI_MIMB_CO003_I14" ON "STAGE_SEC_PLDGR_MAP" 
("CMS_COLLATERAL_ID" ASC, "CMS_PLEDGOR_DTL_ID" DESC) 
ALLOW REVERSE SCANS; 

CREATE INDEX "SI_MIMB_CO003_I15" ON "SI_TEMP_MIMB_CO003" 
("CMS_COLLATERAL_ID" ASC, "CMS_PLEDGOR_DTL_ID" DESC) 
ALLOW REVERSE SCANS; 

CREATE INDEX "SI_MIMB_CO003_I16" ON "SI_TEMP_MIMB_CO003" 
("CMS_COLLATERAL_ID" ASC, "CMS_PLEDGOR_DTL_ID" ASC, "IS_VALID" ASC) 
ALLOW REVERSE SCANS; 

-- CREATE INDEX "SI_MIMB_CO003_I17" ON "CMS_PORTFOLIO_ITEM" 
-- ("TYPE" ASC, "CDS_NUMBER" ASC, "AGENT_NAME" ASC, "RECOGNIZED_EXCHANGE_FLAG" ASC, "RECOGN_EXCHANGE" ASC, "CUSTODIAN_TYPE" ASC, "REGISTERED_NAME" ASC, "NO_OF_UNITS" ASC, 
-- "UNIT_PRICE" ASC, "STOCK_EXCHANGE" ASC, "STOCK_EXCHANGE_COUNTRY" ASC, "EXCHANGE_CONTROL_OBTAINED" ASC, "STOCK_CODE" ASC, "BASEL_COMPLIANT_TEXT" ASC, "STATUS" ASC, 
-- "CMS_COLLATERAL_ID" ASC) 
-- ALLOW REVERSE SCANS; 


-- CO004 – Cash (Collateral)
--DROP INDEX "SI_MIMB_CO004_I1";
CREATE INDEX "SI_MIMB_CO004_I1" ON "SI_TEMP_MIMB_CO004" 
("IS_VALID" ASC, "SOURCE_LMT_ID" DESC) 
ALLOW REVERSE SCANS;

--DROP INDEX "SI_MIMB_CO004_I2";
CREATE INDEX "SI_MIMB_CO004_I2" ON "CMS_SECURITY" 
("SCI_SECURITY_TYPE_VALUE" ASC, "SOURCE_ID" ASC, "STATUS" ASC, "CMS_COLLATERAL_ID" ASC) 
ALLOW REVERSE SCANS;

--DROP INDEX "SI_MIMB_CO004_I3";
CREATE INDEX "SI_MIMB_CO004_I3" ON "CMS_LIMIT_SECURITY_MAP" 
("SOURCE_ID" ASC, "UPDATE_STATUS_IND" ASC, "DELETION_DATE" ASC, "CMS_COLLATERAL_ID" ASC, "CMS_LSP_APPR_LMTS_ID" ASC) 
ALLOW REVERSE SCANS ;

--DROP INDEX "SI_MIMB_CO004_I4";
CREATE INDEX "SI_MIMB_CO004_I4" ON "SI_TEMP_MIMB_CO004" 
("IS_VALID" ASC, "CMS_LIMIT_PROFILE_ID" ASC, "SOURCE_LMT_ID" ASC, "CMS_COLLATERAL_ID" ASC, "CMS_LSP_APPR_LMTS_ID" ASC, "SOURCE_SEC_ID" ASC) 
ALLOW REVERSE SCANS;

--DROP INDEX "SI_MIMB_CO004_I5";
CREATE INDEX "SI_MIMB_CO004_I5" ON "CMS_SECURITY" 
("SCI_SECURITY_DTL_ID" ASC, "SOURCE_ID" ASC, "CMS_COLLATERAL_ID" ASC) 
ALLOW REVERSE SCANS;

--DROP INDEX "SI_MIMB_CO004_I6";
CREATE INDEX "SI_MIMB_CO004_I6" ON "CMS_LIMIT_SECURITY_MAP" 
("SOURCE_ID" ASC, "CMS_COLLATERAL_ID" DESC) 
ALLOW REVERSE SCANS;


