-----------------------------
-- Cleanup
-----------------------------
DELETE FROM MIG_QC_REPORT;

-----------------------------
-- Customer
-----------------------------
-- CU001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CU001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV001SIBS', 'SIBS', 'CU001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CU001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CU001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CU001' FROM MIG_CU001_CU WHERE IS_VALID = 'Y');

    
-----------------------------
-- AA
-----------------------------
-- CA001
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV002SIBS', 'SIBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CA001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CA001' FROM MIG_CA001_AA WHERE IS_VALID = 'Y');


-----------------------------
-- Joint Borrower
-----------------------------    
-- CA002
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CA002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV003SIBS', 'SIBS', 'CA002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CA002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CA002' FROM MIG_CA002_JB WHERE IS_VALID = 'Y');

 
 
-----------------------------
-- Facility
-----------------------------    
-- CA003_1
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CA003_1');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV004SIBS', 'SIBS', 'CA003_1');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_1');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CA003_1');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	 (SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CA003_1' FROM MIG_CA003_1 WHERE IS_VALID = 'Y');
 
-- CA003_2
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CA003_2');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV005SIBS', 'SIBS', 'CA003_2');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_2');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CA003_2');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	 (SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CA003_2' FROM MIG_CA003_2_BNM WHERE IS_VALID = 'Y');
 
-- CA003_3
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CA003_3');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV006SIBS', 'SIBS', 'CA003_3');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_3');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CA003_3');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	 (SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CA003_3' FROM MIG_CA003_3_OFF WHERE IS_VALID = 'Y');
 
-- CA003_4
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CA003_4');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV007SIBS', 'SIBS', 'CA003_4');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_4');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CA003_4');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	 (SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CA003_4' FROM MIG_CA003_4_REL WHERE IS_VALID = 'Y');
 
-- CA003_5
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CA003_5');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV008SIBS', 'SIBS', 'CA003_5');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_5');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CA003_5');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	 (SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CA003_5' FROM MIG_CA003_5_INS WHERE IS_VALID = 'Y');
 
-- CA003_6
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CA003_6');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV009SIBS', 'SIBS', 'CA003_6');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_6');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CA003_6');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	 (SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CA003_6' FROM MIG_CA003_6_MUL WHERE IS_VALID = 'Y');
 
-- CA003_7
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CA003_7');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV010SIBS', 'SIBS', 'CA003_7');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_7');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CA003_7');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	 (SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CA003_7' FROM MIG_CA003_7_ISL WHERE IS_VALID = 'Y');
 
-- CA003_8
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CA003_8');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV011SIBS', 'SIBS', 'CA003_8');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA003_8');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CA003_8');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	 (SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CA003_8' FROM MIG_CA003_8_BBA WHERE IS_VALID = 'Y');
 
 
-----------------------------
-- Limit-Account
-----------------------------    
-- CA004
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CA004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV016SIBS', 'SIBS', 'CA004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CA004');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CA004');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CA004' FROM MIG_CA004 WHERE IS_VALID = 'Y');
 
 
 
-----------------------------
-- Collateral
-----------------------------
-- CO001:AB
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CO001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV018SIBS', 'SIBS', 'CO001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO001');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CO001');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CO001' FROM MIG_CO001_AB WHERE IS_VALID = 'Y'); 
 
-- CO002:AB-Gold
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CO002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV019SIBS', 'SIBS', 'CO002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO002');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CO002');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CO002' FROM MIG_CO002_AB_GOLD WHERE IS_VALID = 'Y'); 
 
-- CO005:CS
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CO005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV022SIBS', 'SIBS', 'CO005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO005');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CO005');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CO005' FROM MIG_CO005_CS WHERE IS_VALID = 'Y');

    
-- CO008:MS
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CO008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV024SIBS', 'SIBS', 'CO008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO008');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CO008');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CO008' FROM MIG_CO008_MS WHERE IS_VALID = 'Y');

-- CO009:PT
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CO009');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV025SIBS', 'SIBS', 'CO009');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO009');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CO009');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CO009' FROM MIG_CO009_PT WHERE IS_VALID = 'Y');

-- CO010:GT
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CO010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV026SIBS', 'SIBS', 'CO010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO010');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CO010');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CO010' FROM MIG_CO010_GT WHERE IS_VALID = 'Y');

-- CO011:OT
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CO011');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV027SIBS', 'SIBS', 'CO011');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO011');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CO011');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CO011' FROM MIG_CO011_OT WHERE IS_VALID = 'Y');

-- CO012:IN
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CO012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV028SIBS', 'SIBS', 'CO012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO012');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CO012');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CO012' FROM MIG_CO012_IN WHERE IS_VALID = 'Y');

-- CO014:CL
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CO014');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV030SIBS', 'SIBS', 'CO014');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO014');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CO014');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CO014' FROM MIG_CO014_CL WHERE IS_VALID = 'Y');    

-- CO015:VL
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CO015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV031SIBS', 'SIBS', 'CO015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO015');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CO015');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CO015' FROM MIG_CO015_VL WHERE IS_VALID = 'Y');    

-- CO016:INS Policy
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CO016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV032SIBS', 'SIBS', 'CO016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO016');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CO016');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CO016' FROM MIG_CO016_IN WHERE IS_VALID = 'Y');    

-- CO017:CD
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CO017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV033SIBS', 'SIBS', 'CO017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO017');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CO017');

DECLARE GLOBAL TEMPORARY TABLE SESSION.COUNT_CHARGE_DETAIL(
    total_charge_detail bigint
) 
WITH REPLACE ON COMMIT PRESERVE ROWS NOT LOGGED;		
		
INSERT INTO SESSION.COUNT_CHARGE_DETAIL (total_charge_detail)
(select count(*) from(SELECT count(*) FROM MIG_CO017_CD WHERE IS_VALID = 'Y' GROUP BY CMS_ACT_COL_ID, RANKING_OF_SECURITY) as temp);
INSERT INTO SESSION.COUNT_CHARGE_DETAIL (total_charge_detail)
(SELECT count(*) FROM MIG_CO005_CS WHERE IS_VALID = 'Y');
INSERT INTO SESSION.COUNT_CHARGE_DETAIL (total_charge_detail)
(SELECT count(*) FROM MIG_CO008_MS WHERE IS_VALID = 'Y');
INSERT INTO SESSION.COUNT_CHARGE_DETAIL (total_charge_detail)
(SELECT count(*) FROM MIG_CO010_GT WHERE IS_VALID = 'Y');
INSERT INTO SESSION.COUNT_CHARGE_DETAIL (total_charge_detail)
(SELECT count(*) FROM MIG_CO012_IN WHERE IS_VALID = 'Y');

select sum(total_charge_detail) from SESSION.COUNT_CHARGE_DETAIL

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'IsValid', sum(total_charge_detail), 'SIBS', 'CO017' FROM SESSION.COUNT_CHARGE_DETAIL);    

-- CO018:Pledgor
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CO018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV034SIBS', 'SIBS', 'CO018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO018');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CO018');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CO018' FROM (select PLEDGOR_CIF_ID from MIG_CO018_PG where is_valid = 'Y' group by PLEDGOR_CIF_ID) as temp);    

-- CO019:Pledge
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'QC Report 4 for Migration', 'SIBS', 'CO019');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report for migration template: CV035SIBS', 'SIBS', 'CO019');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Report Date: ' || char(current date)  || chr(13) || chr(10) || chr(13) || chr(10), 'SIBS', 'CO019');
INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID) VALUES ('IsValid', 'Total Number of Records', 'SIBS', 'CO019');

INSERT INTO MIG_QC_REPORT (RECORD_TYPE, TEXT, SYSTEM_ID, INTERFACE_ID)
	(SELECT 'IsValid', CHAR(COUNT(*)), 'SIBS', 'CO019' FROM MIG_CO019_PL WHERE IS_VALID = 'Y');    

