-- Extraction scripts for LPP and non-LPP
------------------------------------------------------------------------------------------------------------------------------
DROP INDEX IDX_PROPERTY_PATCH_001;
DROP INDEX IDX_PROPERTY_PATCH_002;
DROP INDEX IDX_PROPERTY_PATCH_003;
DROP INDEX IDX_PROPERTY_PATCH_004;
DROP INDEX IDX_PROPERTY_PATCH_005;
DROP INDEX IDX_PROPERTY_PATCH_006;
DROP INDEX IDX_PROPERTY_PATCH_007;
DROP INDEX IDX_PROPERTY_PATCH_008;
DROP INDEX IDX_PROPERTY_PATCH_009;
DROP INDEX IDX_PROPERTY_PATCH_010;

CREATE INDEX IDX_PROPERTY_PATCH_001 ON PATCH_CO009_PT (SIBS_PROPERTY_ADDRESS ASC, CMS_ACT_COL_ID ASC) ALLOW REVERSE SCANS;
CREATE INDEX IDX_PROPERTY_PATCH_002 ON SCI_LSP_LMT_PROFILE (APPLICATION_LAW_TYPE ASC, APPLICATION_TYPE ASC, 
CMS_LSP_LMT_PROFILE_ID ASC, LLP_LE_ID ASC) ALLOW REVERSE SCANS;
CREATE INDEX IDX_PROPERTY_PATCH_003 ON SCI_LE_MAIN_PROFILE (LMP_LONG_NAME ASC, LMP_LE_ID ASC) ALLOW REVERSE SCANS;
CREATE INDEX IDX_PROPERTY_PATCH_004 ON CMS_FACILITY_MASTER (DEALER_NUM_LPP_CODE_VALUE ASC, CMS_LSP_APPR_LMTS_ID ASC) ALLOW REVERSE SCANS;
CREATE INDEX IDX_PROPERTY_PATCH_005 ON SCI_LSP_APPR_LMTS (LOS_BCA_REF_NUM ASC, LMT_BCA_REF_NUM ASC, CMS_BKG_ORGANISATION ASC, CMS_LSP_APPR_LMTS_ID ASC,
CMS_LIMIT_PROFILE_ID ASC) ALLOW REVERSE SCANS;
CREATE INDEX IDX_PROPERTY_PATCH_006 ON CMS_PROPERTY (TAMAN ASC, DISTRICT ASC, MUKIM ASC, STATE ASC, POSTCODE ASC, PROPERTY_ADDRESS_3 ASC,
PROPERTY_ADDRESS_2 ASC, PROPERTY_ADDRESS ASC, CMS_COLLATERAL_ID ASC) ALLOW REVERSE SCANS;
CREATE INDEX IDX_PROPERTY_PATCH_007 ON EXTRACT_PROPERTY_WITH_LPP (CMS_COLLATERAL_ID ASC, SIBS_MUKIM_DISTRICT ASC) ALLOW REVERSE SCANS;
CREATE INDEX IDX_PROPERTY_PATCH_008 ON EXTRACT_PROPERTY_WITHOUT_LPP (CMS_COLLATERAL_ID ASC, SIBS_MUKIM_DISTRICT ASC) ALLOW REVERSE SCANS;
CREATE INDEX IDX_PROPERTY_PATCH_009 ON "PATCH_CO009_PT" 
("CMS_ACT_COL_ID" ASC) 
ALLOW REVERSE SCANS; 
CREATE INDEX IDX_PROPERTY_PATCH_010 ON "PATCH_CO009_PT" 
("CMS_ACT_COL_ID" ASC, "SIBS_PROPERTY_ADDRESS" DESC) 
ALLOW REVERSE SCANS; 

call ADMIN_CMD('RUNSTATS ON TABLE EONCMS.PATCH_CO009_PT ON ALL COLUMNS WITH DISTRIBUTION AND DETAILED INDEXES ALL'); 
call ADMIN_CMD('RUNSTATS ON TABLE EONCMS.SCI_LSP_LMT_PROFILE ON ALL COLUMNS WITH DISTRIBUTION AND DETAILED INDEXES ALL'); 
call ADMIN_CMD('RUNSTATS ON TABLE EONCMS.SCI_LE_MAIN_PROFILE ON ALL COLUMNS WITH DISTRIBUTION AND DETAILED INDEXES ALL'); 
call ADMIN_CMD('RUNSTATS ON TABLE EONCMS.CMS_FACILITY_MASTER ON ALL COLUMNS WITH DISTRIBUTION AND DETAILED INDEXES ALL'); 
call ADMIN_CMD('RUNSTATS ON TABLE EONCMS.SCI_LSP_APPR_LMTS ON ALL COLUMNS WITH DISTRIBUTION AND DETAILED INDEXES ALL'); 
call ADMIN_CMD('RUNSTATS ON TABLE EONCMS.CMS_PROPERTY ON ALL COLUMNS WITH DISTRIBUTION AND DETAILED INDEXES ALL'); 
call ADMIN_CMD('RUNSTATS ON TABLE EONCMS.EXTRACT_PROPERTY_WITH_LPP ON ALL COLUMNS WITH DISTRIBUTION AND DETAILED INDEXES ALL'); 
call ADMIN_CMD('RUNSTATS ON TABLE EONCMS.EXTRACT_PROPERTY_WITHOUT_LPP ON ALL COLUMNS WITH DISTRIBUTION AND DETAILED INDEXES ALL'); 

------------------------------------------------------------------------------------------------------------------------------
DROP TABLE EXTRACT_PROPERTY_WITH_LPP;
DROP TABLE EXTRACT_PROPERTY_WITHOUT_LPP; 

CREATE TABLE EXTRACT_PROPERTY_WITH_LPP (
	CMS_COLLATERAL_ID				BIGINT,
	APPLICATION_TYPE				VARCHAR(2),
	APPLICATION_LAW_TYPE			VARCHAR(3),		
	CUSTOMER_NAME					VARCHAR(150),
	CIF_ID							VARCHAR(20),
	BRANCH							VARCHAR(20),
	CENTER							VARCHAR(100),
	SIBS_AA_NUMBER					VARCHAR(35),
	LOS_AA_NUMBER					VARCHAR(35),
	SECURITY_ID						VARCHAR(50),
    PROPERTY_ADDRESS                VARCHAR(150),
    PROPERTY_ADDRESS_2              VARCHAR(50),
    PROPERTY_ADDRESS_3              VARCHAR(50),	
    POST_CODE                       VARCHAR(6),
    STATE		                    VARCHAR(80),
	MUKIM		                    VARCHAR(80),
	DISTRICT	                    VARCHAR(80),
	TAMAN							VARCHAR(50),
	SIBS_MUKIM_DISTRICT				VARCHAR(50),
	LPP_CODE						VARCHAR(40),
	LPP_DESC						VARCHAR(100)
) in CMS_MIG index in CMS_MIG_INDEX;

CREATE TABLE EXTRACT_PROPERTY_WITHOUT_LPP (
	CMS_COLLATERAL_ID				BIGINT,
	APPLICATION_TYPE				VARCHAR(2),
	APPLICATION_LAW_TYPE			VARCHAR(3),		
	CUSTOMER_NAME					VARCHAR(150),
	CIF_ID							VARCHAR(20),
	BRANCH							VARCHAR(20),
	CENTER							VARCHAR(100),
	SIBS_AA_NUMBER					VARCHAR(35),
	LOS_AA_NUMBER					VARCHAR(35),
	SECURITY_ID						VARCHAR(50),
    PROPERTY_ADDRESS                VARCHAR(150),
    PROPERTY_ADDRESS_2              VARCHAR(50),
    PROPERTY_ADDRESS_3              VARCHAR(50),	
    POST_CODE                       VARCHAR(6),
    STATE		                    VARCHAR(80),
	MUKIM		                    VARCHAR(80),
	DISTRICT	                    VARCHAR(80),
	TAMAN							VARCHAR(50),
	SIBS_MUKIM_DISTRICT				VARCHAR(50),
	LPP_CODE						VARCHAR(40),
	LPP_DESC						VARCHAR(100)
) in CMS_MIG index in CMS_MIG_INDEX;

------------------------------------------------------------------------------------------------------------------------------

-- Mukim_District_with_LPP
insert into EXTRACT_PROPERTY_WITH_LPP (CMS_COLLATERAL_ID, APPLICATION_TYPE, APPLICATION_LAW_TYPE, CUSTOMER_NAME, CIF_ID, BRANCH, CENTER, SIBS_AA_NUMBER,
	LOS_AA_NUMBER, SECURITY_ID, PROPERTY_ADDRESS, PROPERTY_ADDRESS_2, PROPERTY_ADDRESS_3, POST_CODE, STATE, MUKIM, DISTRICT, TAMAN, LPP_CODE, LPP_DESC) (
select sec.CMS_COLLATERAL_ID, aa.APPLICATION_TYPE, aa.APPLICATION_LAW_TYPE, cust.LMP_LONG_NAME as CUSTOMER_NAME, cust.LMP_LE_ID as CIF_ID, 
	lmt.CMS_BKG_ORGANISATION as BRANCH,
    (select comm.REF_ENTRY_CODE as CENTER from COMMON_CODE_CATEGORY_ENTRY comm
        where comm.ENTRY_CODE = lmt.CMS_BKG_ORGANISATION
        and comm.CATEGORY_CODE = '40'), 
    lmt.LMT_BCA_REF_NUM as SIBS_AA_NUMBER, lmt.LOS_BCA_REF_NUM as LOS_AA_NUMBER, sec.SCI_SECURITY_DTL_ID as SECURITY_ID,
    pty.PROPERTY_ADDRESS, pty.PROPERTY_ADDRESS_2, pty.PROPERTY_ADDRESS_3, pty.POSTCODE, 
    (select comm1.ENTRY_NAME as STATE from COMMON_CODE_CATEGORY_ENTRY comm1
        where comm1.ENTRY_CODE = pty.STATE
        and comm1.CATEGORY_CODE = 'STATE'), 
    (select comm2.ENTRY_NAME as MUKIM from COMMON_CODE_CATEGORY_ENTRY comm2
        where comm2.ENTRY_CODE = pty.MUKIM
        and comm2.CATEGORY_CODE = 'MUKIM'), 
    (select comm3.ENTRY_NAME as DISTRICT from COMMON_CODE_CATEGORY_ENTRY comm3
        where comm3.ENTRY_CODE = pty.DISTRICT
        and comm3.CATEGORY_CODE = 'DISTRICT'), pty.TAMAN,
    facmas.DEALER_NUM_LPP_CODE_VALUE as LPP_CODE,
    (select comm4.ENTRY_NAME as LPP_DESC from COMMON_CODE_CATEGORY_ENTRY comm4
        where comm4.ENTRY_CODE = facmas.DEALER_NUM_LPP_CODE_VALUE
        and comm4.CATEGORY_CODE = 'DEALER')
from SCI_LE_MAIN_PROFILE cust, SCI_LSP_LMT_PROFILE aa, SCI_LSP_APPR_LMTS lmt, CMS_LIMIT_SECURITY_MAP lsm, 
    CMS_SECURITY sec, CMS_PROPERTY pty, CMS_FACILITY_MASTER facmas
where cust.LMP_LE_ID = aa.LLP_LE_ID
and aa.CMS_LSP_LMT_PROFILE_ID = lmt.CMS_LIMIT_PROFILE_ID
and lmt.CMS_LSP_APPR_LMTS_ID = lsm.CMS_LSP_APPR_LMTS_ID
and lsm.CMS_COLLATERAL_ID = sec.CMS_COLLATERAL_ID
and sec.CMS_COLLATERAL_ID = pty.CMS_COLLATERAL_ID
and lmt.CMS_LSP_APPR_LMTS_ID = facmas.CMS_LSP_APPR_LMTS_ID
and exists (select 1 from COMMON_CODE_CATEGORY_ENTRY comm5
                where comm5.ENTRY_CODE = facmas.DEALER_NUM_LPP_CODE_VALUE
                and comm5.CATEGORY_CODE = 'DEALER'));
				
UPDATE EXTRACT_PROPERTY_WITH_LPP temp
SET SIBS_MUKIM_DISTRICT = (select pth.SIBS_PROPERTY_ADDRESS as SIBS_MUKIM_DISTRICT from PATCH_CO009_PT pth
							where pth.CMS_ACT_COL_ID = temp.CMS_COLLATERAL_ID)	
WHERE EXISTS (select 1 from PATCH_CO009_PT pth1
				where pth1.CMS_ACT_COL_ID = temp.CMS_COLLATERAL_ID);							

-- Mukim_District_withno_LPP				
insert into EXTRACT_PROPERTY_WITHOUT_LPP (CMS_COLLATERAL_ID, APPLICATION_TYPE, APPLICATION_LAW_TYPE, CUSTOMER_NAME, CIF_ID, BRANCH, CENTER, SIBS_AA_NUMBER,
	LOS_AA_NUMBER, SECURITY_ID, PROPERTY_ADDRESS, PROPERTY_ADDRESS_2, PROPERTY_ADDRESS_3, POST_CODE, STATE, MUKIM, DISTRICT, TAMAN, LPP_CODE) (
select sec.CMS_COLLATERAL_ID, aa.APPLICATION_TYPE, aa.APPLICATION_LAW_TYPE, cust.LMP_LONG_NAME as CUSTOMER_NAME, cust.LMP_LE_ID as CIF_ID, 
	lmt.CMS_BKG_ORGANISATION as BRANCH,
    (select comm.REF_ENTRY_CODE as CENTER from COMMON_CODE_CATEGORY_ENTRY comm
        where comm.ENTRY_CODE = lmt.CMS_BKG_ORGANISATION
        and comm.CATEGORY_CODE = '40'), 
    lmt.LMT_BCA_REF_NUM as SIBS_AA_NUMBER, lmt.LOS_BCA_REF_NUM as LOS_AA_NUMBER, sec.SCI_SECURITY_DTL_ID as SECURITY_ID,
    pty.PROPERTY_ADDRESS, pty.PROPERTY_ADDRESS_2, pty.PROPERTY_ADDRESS_3, pty.POSTCODE, 
    (select comm1.ENTRY_NAME as STATE from COMMON_CODE_CATEGORY_ENTRY comm1
        where comm1.ENTRY_CODE = pty.STATE
        and comm1.CATEGORY_CODE = 'STATE'), 
    (select comm2.ENTRY_NAME as MUKIM from COMMON_CODE_CATEGORY_ENTRY comm2
        where comm2.ENTRY_CODE = pty.MUKIM
        and comm2.CATEGORY_CODE = 'MUKIM'), 
    (select comm3.ENTRY_NAME as DISTRICT from COMMON_CODE_CATEGORY_ENTRY comm3
        where comm3.ENTRY_CODE = pty.DISTRICT
        and comm3.CATEGORY_CODE = 'DISTRICT'), pty.TAMAN,
    facmas.DEALER_NUM_LPP_CODE_VALUE as LPP_CODE
from SCI_LE_MAIN_PROFILE cust, SCI_LSP_LMT_PROFILE aa, SCI_LSP_APPR_LMTS lmt, CMS_LIMIT_SECURITY_MAP lsm, 
    CMS_SECURITY sec, CMS_PROPERTY pty, CMS_FACILITY_MASTER facmas
where cust.LMP_LE_ID = aa.LLP_LE_ID
and aa.CMS_LSP_LMT_PROFILE_ID = lmt.CMS_LIMIT_PROFILE_ID
and lmt.CMS_LSP_APPR_LMTS_ID = lsm.CMS_LSP_APPR_LMTS_ID
and lsm.CMS_COLLATERAL_ID = sec.CMS_COLLATERAL_ID
and sec.CMS_COLLATERAL_ID = pty.CMS_COLLATERAL_ID
and lmt.CMS_LSP_APPR_LMTS_ID = facmas.CMS_LSP_APPR_LMTS_ID
and not exists (select 1 from COMMON_CODE_CATEGORY_ENTRY comm5
                where comm5.ENTRY_CODE = facmas.DEALER_NUM_LPP_CODE_VALUE
                and comm5.CATEGORY_CODE = 'DEALER'));
				
UPDATE EXTRACT_PROPERTY_WITHOUT_LPP temp
SET SIBS_MUKIM_DISTRICT = (select pth.SIBS_PROPERTY_ADDRESS as SIBS_MUKIM_DISTRICT from PATCH_CO009_PT pth
							where pth.CMS_ACT_COL_ID = temp.CMS_COLLATERAL_ID)	
WHERE EXISTS (select 1 from PATCH_CO009_PT pth1
				where pth1.CMS_ACT_COL_ID = temp.CMS_COLLATERAL_ID);					
				