LOAD DATA
INFILE 'FILES\REGIONMASTER.csv'
 "str '~~~'"
BADFILE 'PARTIAL_ERROR_LOG\REGIONMASTER.bad'
DISCARDFILE 'PARTIAL_ERROR_LOG\REGIONMASTER.dsc'
DISCARDMAX 1241513983
APPEND INTO TABLE MIG_CMS_REGIONMASTER
FIELDS TERMINATED BY '|||'
TRAILING NULLCOLS
(
REGIONID "REPLACE(REPLACE(DECODE(UPPER(:REGIONID),'NULL',NULL,:REGIONID), CHR(10),''), CHR(13),'')",
REGIONNAME "DECODE(UPPER(:REGIONNAME),'NULL',NULL,:REGIONNAME)",
COUNTRY  "DECODE(UPPER(:COUNTRY),'NULL',NULL,:COUNTRY)"
)