LOAD DATA
INFILE 'FILES\CAM Document Master Withcam + Mandatory.csv'
 "str '~~~'"
BADFILE 'PARTIAL_ERROR_LOG\CAM Document Master Withcam + Mandatory.bad'
DISCARDFILE 'PARTIAL_ERROR_LOG\CAM Document Master Withcam + Mandatory.dsc'
DISCARDMAX 1241513983
APPEND INTO TABLE MIG_CAM_DOCUMENT_MASTER
FIELDS TERMINATED BY '|||'
TRAILING NULLCOLS
(
DOCID "REPLACE(REPLACE(DECODE(UPPER(:DOCID),'NULL',NULL,:DOCID), CHR(10),''), CHR(13),'')",
DOCNAME "DECODE(UPPER(:DOCNAME),'NULL',NULL,:DOCNAME)",
DOCGROUP "DECODE(UPPER(:DOCGROUP),'NULL',NULL,:DOCGROUP)",
DOCTYPE "DECODE(UPPER(:DOCTYPE),'NULL',NULL,:DOCTYPE)",
DOCTENURE "DECODE(UPPER(:DOCTENURE),'NULL',NULL,:DOCTENURE)",
INCLUDEINRL "DECODE(UPPER(:INCLUDEINRL),'NULL',NULL,:INCLUDEINRL)",
CRITICAL "DECODE(UPPER(:CRITICAL),'NULL',NULL,:CRITICAL)",
MANDATORY "DECODE(UPPER(:MANDATORY),'NULL',NULL,:MANDATORY)"
)