LOAD DATA
INFILE 'FILES\CityMaster.csv'
 "str '~~~'"
BADFILE 'PARTIAL_ERROR_LOG\CityMaster.bad'
DISCARDFILE 'PARTIAL_ERROR_LOG\CityMaster.dsc'
DISCARDMAX 1241513983
APPEND INTO TABLE MIG_CMS_LOCATION
FIELDS TERMINATED BY '|||'
TRAILING NULLCOLS
(
CITYID "REPLACE(REPLACE(DECODE(UPPER(:CITYID),'NULL',NULL,:CITYID), CHR(10),''), CHR(13),'')",
CITYNAME "DECODE(UPPER(:CITYNAME),'NULL',NULL,:CITYNAME)",
COUNTRYNAME  "DECODE(UPPER(:COUNTRYNAME),'NULL',NULL,:COUNTRYNAME)",
REGIONNAME "DECODE(UPPER(:REGIONNAME),'NULL',NULL,:REGIONNAME)",
STATENAME "DECODE(UPPER(:STATENAME),'NULL',NULL,:STATENAME)"
)